### ISSUE TITLE
MultiGPU

### ISSUE THREAD

**Issue by plasticbomb1986** [flightlessmango/MangoHud#100]
Is it possible for mangohud, to differentiate and mark which gpu an application is rendering on? If nothing else, just marking with pcie bus index next to the GPU marker?

(Vulkan sometimes launch apps on the secondary gpu in multigpu systems, where the gpus are identical expect which one is in which slot and which one have the display connected to. Plus OC/UV potentioal differences, but thats an another story. On my VEGA64s i can see it by the GPUTach leds which GPu is getting the load, but only because the case is opened now. In the past there where problems, when apps even launched on the IGPs, instead of the dedicated gpus, and while its somewhat mitigated, its still not hundred percent, plus they havent solved the issue with real multiGPU systems.)

**Comment by flightlessmango** [comment]
I don't think we get more information than device and vendor id, that's not enough to guess between to identical cards.

**Comment by jackun** [comment]
To be continued on #114

**Comment by flightlessmango** [comment]
I don't think this is possible
