### ISSUE TITLE
New GPU Fan reporting wrong value on GTX 1070

### ISSUE THREAD

**Issue by mmbossoni** [flightlessmango/MangoHud#1000]
**Describe the bug**
I'm trying the new gpu_fan option and it is reporting a huge value for my GTX 1070

**List relevant hardware/software information**
Operating System: Arch Linux 
KDE Plasma Version: 5.27.4
KDE Frameworks Version: 5.105.0
Kernel Version: 6.2.12-1-cachyos-bore (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 5700X 8-Core Processor
Memory: 15.5 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1070/PCIe/SSE2

Mangohud git just pulled from chaotic aur

**To Reproduce**
Just use the new gpu_fan config

**Expected behavior**
Proper gpu fan speed being shown

Value being shown on vkcube:
Ranging from 14000 to 35000 RPM
Fan speed on nvidia-settings: 8-10%

I think this might actually be the percentage of the fan speed instead of the actual RPM value

**Comment by mmbossoni** [comment]
Comparing with nvidia-settings on x11, it seems like fan speed being reported by nvidia-settings = mangohud fan speed / 100

**Comment by mmbossoni** [comment]
Even on xorg values are odd
it shows 30000 while nvidia-settings show 0% ,0 rpm

**Comment by flightlessmango** [comment]
Does this commit fix it? 1093de8c4406a96642e139243911a571874c3d11

**Comment by mmbossoni** [comment]
It just show 0 rpm now

**Comment by flightlessmango** [comment]
what about this commit? cbf531e6c83a6eff928f80b7399a06dfb1484593

**Comment by mmbossoni** [comment]
Works on xorg but not on wayland

Authorization required, but no authorization protocol specified
[2023-05-04 22:01:59.238] [MANGOHUD] [error] [nvctrl.cpp:53] XNVCtrl didn't find the correct display

But I assume xnvctrl is, well, x only.

**Comment by flightlessmango** [comment]
Yes exactly it requires X and NVML can't get speed in RPM.. So this is the best we can do for now
