### ISSUE TITLE
No GPU detected - RTX 3070

### ISSUE THREAD

**Issue by amithiel** [flightlessmango/MangoHud#1002]
**Describe the bug**
Tried compiling the most recent version, and the ones from AUR. Still can't get it to show GPU usage/temp

**List relevant hardware/software information**
- Linux Distribution: Arch
- MangoHud version: mangohud-git 0.6.9.1.r24.g20b729c-1
- GPU: Nvidia RTX 3070

**To Reproduce**
1. execute mangohud glxgears

**Expected behavior**
Should display gpu usage/temp

**Screenshots**
https://i.imgur.com/q18GFbo.png

**Additional context**
deleted the config file several times, tried configuring with Govelay. For the life of me, i can't figure this out. I used mangohud on arch in the past, worked everytime, including with this card

**Comment by amithiel** [comment]
No worries, take your time! 
cheers

**Comment by flightlessmango** [comment]
Fixed here 7ea1f33fa1d31007b56c883336e83ec683e8ad4b
