### ISSUE TITLE
0.6.9/0.6.9.1 regression: gpu_core_clock stuck at 1200MhZ for RDNA3/AMDGPU

### ISSUE THREAD

**Issue by Mershl** [flightlessmango/MangoHud#1004]
**Describe the bug**
Starting with mangohud 0.6.9 the `gpu_core_clock` value is stuck at 1200MhZ under any load/at all times on an AMDGPU RX7900XTX.

Downgrading to mangohud 0.6.8 immediatly fixes the issue.

**List relevant hardware/software information**
- Fedora 37
- mangohud 0.6.9 and 0.6.9.1 tested
- AMD RX7900 XTX
- kernel 6.2.12

**To Reproduce**
1. Enable `gpu_core_clock` in MangoHud.conf
2. Start `vblank_mode=0 mangohud glxgears` (through visible in all games - tested Cyberpunk and CS:GO)
3. Value for GPU core clock is permanently stuck at 1200MhZ in the overlay

**Screenshots**
![image](https://user-images.githubusercontent.com/520251/235375837-72bd8655-7981-4b90-8d72-58d0dc1f0c5e.png)

**Comment by Mershl** [comment]
Bisecting the issue on an 7900XTX system shows 08431a0221623fa83e3c884ccc0b03e53f7a7eda as the first commit with this issue.

**Comment by gort818** [comment]
Using `current_gfxclk` is the correct way. Like i said in #954 seems to be a bug in the kernel. I haven't got around to reporting it the amdgpu devs.

` current_gfxclk` seems to work fine with other GPUs expect RDNA3

**Comment by abc-mikey** [comment]
I'm seeing the same `opensuse tumbleweed` with `mangohud 0.6.9~1-1.1`.

Monitoring the output of `/sys/kernel/debug/dri/1/amdgpu_pm_info` I can see that my PSTATE_MCLK and MCLK stay at 1249 MHz, my PSTATE_SCLK says at 1904MHz, and my SCLK varies between 0MHz and 3048MHz.

**Comment by ojsl1** [comment]
Same problem for me on my Sapphire 7900 XTX PULSE, my `gpu_metrics` file only outputs garbage so there's no `current_gfxclk` to be read at all.

Tried:
Both `linux-firmware-git:20230525.d11ae984` and `linux-firmware:20230404.2e92a49f`
And kernels: 6.4.0rc4, 6.3.5, 6.2.16, 6.1.31
```
$ cat /sys/class/drm/card0/device/gpu_metrics
x5=H97;J5!
```
```
$ cat /sys/devices/pci0000:00/0000:00:03.1/0000:0a:00.0/0000:0b:00.0/0000:0c:00.0/gpu_metrics
x5<H97;?Ky%
```
```
$ file  /sys/class/drm/card0/device/gpu_metrics                                                                                                                                                
/sys/class/drm/card0/device/gpu_metrics: Targa image data - Map 42 x 41 x 1 +56 +42 ""
$ file  /sys/class/drm/card0/device/gpu_metrics                                                                                                                                                
/sys/class/drm/card0/device/gpu_metrics: data
$ file  /sys/class/drm/card0/device/gpu_metrics                                                                                                                                                
/sys/class/drm/card0/device/gpu_metrics: Targa image data - Map 43 x 42 x 1 +56 +43 "\001"
```
I did find this [gist](https://gist.github.com/leuc/e45f4dc64dc1db870e4bad1c436228bb) where a user succesfully commented their RDNA3 `gpu_metrics` content, leading me to think there's been some regression after the comment, could someone else check whether their `gpu_metrics` is currently working on an RDNA3 card? For me downgrading to non-git linux-firmware changed how the garbage looked, but it was still garbage nonetheless.

The SCLK and MCLK are reported just fine through the gui of radeon-profile([qt5](https://github.com/marazmista/radeon-profile/blob/master/radeon-profile/globalStuff.h)) and rocm-smi:
```
$ watch -n1 /opt/rocm/bin/rocm-smi --showclocks
======================= ROCm System Management Interface =======================
========================== Current clock frequencies ===========================
GPU[0]          : fclk clock level: 4: (2000Mhz)
GPU[0]          : mclk clock level: 3: (1249Mhz)
GPU[0]          : sclk clock level: 1: (1420Mhz)
GPU[0]          : socclk clock level: 1: (1285Mhz)
GPU[0]          : PCIe current clock frequency not found
================================================================================
============================= End of ROCm SMI Log ==============================
```
Cant mangohud have fallback parameters for reading the SCLK values etc. through the hwmon sysfs interface in cases like this? That'd make the app less prone to similar param breakages not just for amd but in the future across multiple vendors [intel](https://www.phoronix.com/news/Linux-i915-HWMON-Linux),[nvidia](https://www.phoronix.com/review/nvidia-open-kernel)
```
$ watch -n1 cat /sys/class/drm/card0/device/hwmon/hwmon0/freq1*
2387000000
sclk
```

**Comment by Mershl** [comment]
The last known working release for RDNA3 users is 0.6.8.

Flatpak users can use the following to pin the last working commit for the time being:

```
$ sudo flatpak update --commit=b9647bcf41029a1d43c2684e6668be2e42401eafb6de64c437cdde8c0896a7ba org.freedesktop.Platform.VulkanLayer.MangoHud
$ flatpak mask org.freedesktop.Platform.VulkanLayer.MangoHud
```

To disable the pin in the future:

```
$ flatpak mask --remove org.freedesktop.Platform.VulkanLayer.MangoHud
$ flatpak update
```

**Comment by flightlessmango** [comment]
This has been fixed here 6abc794

**Comment by Mershl** [comment]
Hi @flightlessmango, the latest stable release 0.6.9.1 does not include 6abc794. Do you have plans for a new release in the upcoming months?

**Comment by flightlessmango** [comment]
Yes we are very close to a new release
