### ISSUE TITLE
can not disable gpu information, cpu load, frame timings

### ISSUE THREAD

**Issue by ewbteewbte** [flightlessmango/MangoHud#101]
first I've tried with variables only, then I've tried with config only, after that with both. And no matter what, those metrics do not disappear. Also tried to rebuild it as well as "release" installation. Also GPU load always shows zero, guess it's because it is integrated?

Pop_os 19.10
ryzen 3400g + vega apu

**Comment by jackun** [comment]
> Also GPU load always shows zero,

This seems to be a driver issue.

The default items you have to disable explicitly like `cpu_stats=0` if you didn't try already.

**Comment by ewbteewbte** [comment]
> > Also GPU load always shows zero,
> 
> This seems to be a driver issue.
> 
> The default items you have to disable explicitly like `cpu_stats=0` if you didn't try already.

Oh thanks! That worked out, I guess I misunderstood the readme.
About the driver issue, lm-sensors do show the gpu temp (seems lik it is always the same with cpu), tho I didn't install any of the drivers myself, it just works smooth out of the box on this Dist

**Comment by flightlessmango** [comment]
It's not a driver issue exactly, it's that it's not supported in the driver for these devices
