### ISSUE TITLE
Stop forcing a whole config refresh when one setting is changed.

### ISSUE THREAD

**Issue by LethalManBoob** [flightlessmango/MangoHud#1012]
If i want to have a minimalist config or make changes globally then i cannot make a single edit in goverlay after the fact. An option to auto update all configs in the default directory would also be nice

**Comment by flightlessmango** [comment]
What is the actual issue here? how does it affect your minimalist config?

**Comment by LethalManBoob** [comment]
When I make a change on goverlay, the whole config is overwritten with a complete config. Even if i make one change.
Its also annoying because it keeps changing the custom colours I select when I make changes.

**Comment by flightlessmango** [comment]
So this is specifically related to goverlay? that is a separate project and you should make an issue there instead
