### ISSUE TITLE
MangoHud (and mangoapp) break Tales of Arise [proton 7.0-6]

### ISSUE THREAD

**Issue by zany130** [flightlessmango/MangoHud#1017]
**Describe the bug**
MangoHud (and mangoapp) break Tales of Arise when loading or starting a new game

**List relevant hardware/software information**
```
inxi -b
System:
  Host: Garuda-Linux Kernel: 6.2.14-273-tkg-bmq arch: x86_64 bits: 64
    Desktop: KDE Plasma v: 5.27.5 Distro: Garuda Linux
Machine:
  Type: Desktop Mobo: ASRock model: X470 Taichi serial: <superuser required>
    UEFI: American Megatrends v: P5.10 date: 10/20/2022
CPU:
  Info: 6-core AMD Ryzen 5 5600X [MT MCP] speed (MHz): avg: 2862
    min/max: 2200/4650
Graphics:
  Device-1: AMD Navi 22 [Radeon RX 6700/6700 XT/6750 XT / 6800M/6850M XT]
    driver: amdgpu v: kernel
  Display: wayland server: X.org v: 1.21.1.8 with: Xwayland v: 23.1.1
    compositor: kwin_wayland driver: N/A resolution: 1: 2048x864 2: 1536x864
    3: 1536x864
  API: OpenGL v: 4.6 Mesa 23.0.3 renderer: AMD Radeon RX 6700 XT (navi22
    LLVM 15.0.7 DRM 3.49 6.2.14-273-tkg-bmq)
Network:
  Device-1: Intel Dual Band Wireless-AC 3168NGW [Stone Peak] driver: iwlwifi
  Device-2: Intel I211 Gigabit Network driver: igb
  Device-3: Sony WH-1000XM3 [Wireless Noise-Canceling Headphones]
    driver: hid-generic,usbhid type: USB
Drives:
  Local Storage: total: 2.96 TiB used: 4 TiB (135.3%)
Info:
  Processes: 441 Uptime: 46m Memory: available: 31.26 GiB
  used: 11.87 GiB (38.0%) Shell: fish inxi: 3.3.27
  ```
mangohud version: `0.6.9.1.r46.g3f8f036-1`
mangoapp version: `0.6.9.1`
gamescope version: `3.12.0.beta3.r3.g1716555-1`

**To Reproduce**
1. start game
2. either load a game save or start a new one
3. game gets stuck

**Expected behavior**
The game should not get stuck when getting into the game

**Additional context**
Tested with both mangoapp and mangohud. Game works as expected with the overlay disabled. 

Works as expected on the steam deck in game mode.

**Comment by zany130** [comment]
Strangely I can't reproduce this on the Steam deck desktop mode. Both regular mangohud and mango app work just fine with this game.

**Comment by flightlessmango** [comment]
Packages on steam deck will be older, so it's possible it's a regression in gamescope or mangohud

**Comment by zany130** [comment]
> Packages on steam deck will be older, so it's possible it's a regression in gamescope or mangohud

do you know what version the latest steamos beta uses?

setting the overlay to full on the deck shows this version `0.6.8.-17-gebb0f96` though I can't find the corresponding commit

**Comment by flightlessmango** [comment]
it's this commit ebb0f969dea2c5df1600e6e299cd5665920e0020

**Comment by zany130** [comment]
I got the game to work with mango app `0.6.9.1` but couldn't work with mangohud `0.6.9.1` nor mangohud from that commit. 

It seems the hangs with mango app where because of a modification I made to the game engine file; however, mangohud doesn't seem to work with the game stock

**Comment by zany130** [comment]
not a mangohud issue was able to reproduce without mangohud. No idea what is going on with this game on my system (other games work fine) but it doesn't seem mangohud is the cause
