### ISSUE TITLE
Mangohud 'gpu_core_clock' not displaying correct current clocks, when using CoreCtrl to manage GPU clocks.

### ISSUE THREAD

**Issue by Gkirmathal** [flightlessmango/MangoHud#1018]
Just noticed this issue in a game, this is several days to 2 weeks after having gotten several updates on my Manjaro Testing Branch (23-4-27). Tracking back what packages or versions could have started causing this is a bit 'vague'.

So, noticed MangoHud GPU clocks stopped showing the clocks I expected (and known to me) under load, that were set in my CoreCtrl GPU profile. The profile clocks are set to a target Max Mhz of 1820Mhz and the actual clocks reached hoover under load around ~_1770Mhz_

To keep the rest of the report simple, I'll refer to stock GPU clocks from here on. Is the issue persists on 

**Describe the bug**
When using CoreCtrl to manage the GPU clocks in an _Automatic_ and or _Manual_ profile, with _Performance Mode_ set to '_Advanced_' or _Performance Mode_ set to '_Fixed_' on _Low or High_. 
MangoHud `gpu_core_clock` value shown, **does no longer correspond to** the actual and expected current clock shown by `sudo cat /sys/kernel/debug/dri/0/amdgpu_pm_info`.

The `gpu_core_clock` value shown shows the _Minimum Mhz_ set by CoreCtrl (800Mhz) for the GPU profile, when _Performance Mode_ set to _Advanced_. 
Or when using _Performance Mode_ set to _Fixed_ (_high or low_), `gpu_core_clock` shown corresponds to the max (1780) and min (300) Mhz that CoreCtrl sets for my GPU for those two modes.

When _disabling GPU management_ in CoreCtrl, thus letting the GPU manage it self, then Mangohud `gpu_core_clock` **does show** the correct current clocks as shown in `sudo cat /sys/kernel/debug/dri/0/amdgpu_pm_info` under load.

**List relevant hardware/software information**
- Manjaro (Testing branch, update 23-04-27)
- Kernel 6.2.13
- MangoHud 0.6.9.1
- CoreCtrl 1.3.5
- GPU AMD RX 5600 XT

For reference: 
- _Performance Mode_ set to '_Advanced_',  CoreCtrl sets the RX 5600 XT stock frequencies at Minimum Mhz of _800Mhz_ and Maximum Mhz of _1780Mhz._ 
- _Performance Mode_ set to '_Fixed_' on _Low/High_, CoreCtrl sets the RX 5600 XT stock frequencies at Minimum Mhz of _300Mhz_ and Maximum Mhz of _1780Mhz_. 

The actual clock under load then hoover around ~_1730Mhz_.

**To Reproduce**
1. create a manual GPU profile in CoreCtrl
2. set Performance Mode to Advanced, or Fixed (High or Low)
3. leave GPU profile by Core Ctrl as is
4. run a 'windowed' GPU load/game/benchmark.
5. check MangoHud reported `gpu_core_clock` value
6. check system reported current clocks `sudo cat /sys/kernel/debug/dri/0/amdgpu_pm_info` 

**Expected behavior**
MangoHud showing the correct and actual GPU current clocks, when used in combination with CoreCtrl, that are similarly reported by reading `sudo cat /sys/kernel/debug/dri/0/amdgpu_pm_info` when CoreCtrl is managing the GPU clocks.

Up till those few updates ago, that was what I was seeing in MangoHud overlay.

**Screenshots**
Not really applicable

**Additional context**
Since running Testing Branch and nor having read reports from other users on the Manjaro forums, it is unclear to me which updated package, or updated kernel might be causing this. Bisecting is a skill level or bridge too far for me atm.

Also my pacman config was, regretfully, set to retain only 2 versions. Thus I could not downgrade to 0.6.8 to see if that would fix the issue. 

I'll test downgrading CoreCtrl to it's previous version to see if the issue is perhaps related to it.

**Comment by flightlessmango** [comment]
This should be resolved in 6abc794b42edc1a397448ce4330e8fd164a5c529
