### ISSUE TITLE
List of supported hotkeys

### ISSUE THREAD

**Issue by aclist** [flightlessmango/MangoHud#1019]
**Describe the bug**
Is there a list of supported keys? I tried setting `toggle_hud` to `Super_R`, since I have an unused Super key on my keyboard, but it doesn't seem to pick this up, whereas Shift variants and the default keybind work.

**List relevant hardware/software information**
- Arch Linux
- MangoHud 0.6.8
- X11

**Comment by gort818** [comment]
I don't have a right super, but left super worked for me, and also menu worked fine.

Any of the standard X11 keycodes should work.

Are you sure the key is identified as `Super_R`?

**Comment by aclist** [comment]
Thanks for the brain jog, you sent me looking through `xev` for keycodes and I found that my `.Xmodmap` had keycode 134 unbound. It was enough to add `Super_R` to there and reinitialize the file.
