### ISSUE TITLE
Screen flicker or black screen when MangoHud is on

### ISSUE THREAD

**Issue by agolinux** [flightlessmango/MangoHud#102]
Hello,

When I use MangoHud while gaming, my screen flicker sometimes and even go black screen and then reboot on my system. I don't had such issue with the DXVK HUD. I'm asking if it's could be releated to Mesa driver or something?

I have RX 5700 XT on Mesa 20.0.2 running Debian Sid.

**Comment by jackun** [comment]
Try disabling most GPU HW related stats like temp, usage etc.

**Comment by agolinux** [comment]
I tried with the default setting, I still had some flicker but no reboot so far.

**Comment by agolinux** [comment]
Well it appears the issue is coming from my GPU. I booted under Windows for testing and I got a black screen while gaming and I had to reset my computer. I ended up to update my GPU bios and it seem stable right now.
