### ISSUE TITLE
Intel GPU Stats disabled under Proton: `sh: 1: intel_gpu_top: not found`

### ISSUE THREAD

**Issue by big-lip-bob** [flightlessmango/MangoHud#1020]
**Describe the bug**
Akin to #840, but this time, affecting one of the bigger features, the GPU stats (which are completely missing in this case)
It seems that for games under Proton, `$PATH` is changed so that the usual executables are not present anymore, which makes so that `intel_gpu_top` is not present in there, which is nescessary to get GPU stats for Intel cards as of now it seems ? I know that there are issues on Intel driver's side not allowing access to the hwmon, as do other drivers do, but `intel_gpu_top` can be enabled for non root users and get the stats through it, in fact, it works in `glxgears` and non Proton games, is there some kind of monkeypatch to add it to Proton's `$PATH`, or use the absolute path instead ?
```
sh: 1: glxinfo: not found
# Later down the line
sh: 1: intel_gpu_top: not found
[2023-05-13 21:02:57.763] [MANGOHUD] [info] [intel.cpp:55] Failed to open 'intel_gpu_top'
[2023-05-13 21:02:57.763] [MANGOHUD] [info] [intel.cpp:60] Disabling gpu_stats
```

**To Reproduce**
Get an Intel GPU, get a game that runs under Proton, launch the game in MangoHud
-> No GPU stats available

**Setup**
Using Artix, with Linux Zen 6.3.1 with an Alder Lake-UP3 GT2 (`mesa` 23.0.3-1), with `aur/mangohud-nonvidia 0.6.9.1-1`, tried with BattleBit Remastered, under Proton-GE

**Comment by flightlessmango** [comment]
The problem is that proton runs inside the [steam runtime](https://github.com/ValveSoftware/steam-runtime) container.

**Comment by big-lip-bob** [comment]
Hmmm, I always use Steam with `STEAM_RUNTIME=0`, can I somehow disable the fact that Proton runs inside it despite in the meantime ?

**Comment by flightlessmango** [comment]
It's not recommended to disable the steam runtime container

**Comment by tazz4843** [comment]
This issue also affects Arc dGPUs, is there no workaround besides disabling the runtime container?

**Comment by big-lip-bob** [comment]
Or at least, some kind of patch to the container's entrypoint script so that we can inject `glxinfo` and `intel_gpu_top` (Albeit it needs additional capabilities, i couldn't get it to work)

**Comment by flightlessmango** [comment]
Moving conversation to #1082
