### ISSUE TITLE
Make the logger more silent by default for config file locations

### ISSUE THREAD

**Issue by strycore** [flightlessmango/MangoHud#1023]
Mangohud loading config files ends up being the bigger part of the logs when launching a game from lutris with Mangohud enabled.
I believe those log messages should be demoted from info to debug so they won't get displayed by default.
![Screenshot from 2023-05-18 23-52-31](https://github.com/flightlessmango/MangoHud/assets/280336/7f1e2d54-3007-44a4-a0d7-3a7ef68ed1ab)

**Comment by flightlessmango** [comment]
This has been fixed here 0b3904f
