### ISSUE TITLE
No option for cells / hud text center

### ISSUE THREAD

**Issue by wilk85** [flightlessmango/MangoHud#1024]
Please add option to center text inside hud, or some padding or some other feature to center text in horizontal setup

![mango-poe](https://github.com/flightlessmango/MangoHud/assets/10927846/bbc7b0a7-8298-4dc7-b1dd-806c92b0a79f)

**Comment by gort818** [comment]
Try the latest master and use
`position=top-center`
`horizontal_stretch=0`

**Comment by wilk85** [comment]
right now i cannot even get the horizontal position, i can have only box, not horizontal line, if i put horizontal option, nothing happens

**Comment by flightlessmango** [comment]
> cannot even get the horizontal position

Sounds like a user issue or old version. Reopen after testing with 0.7.1+
