### ISSUE TITLE
Outline Text?

### ISSUE THREAD

**Issue by DisasterIncarnate** [flightlessmango/MangoHud#1025]
Is there an option, or planned option to enable Outlined Text?  im finding it hard to read some of the text on bright games like subnautica and having a black outline would be more preferable to changing the alpha level/entire background opacity.

**Comment by flightlessmango** [comment]
Text outline has been added and is currently enabled by default

**Comment by DisasterIncarnate** [comment]
legend   :bowdown:

**Comment by Perkolator** [comment]
New release in sight? Flatpak user here asking. :) "Comes when it comes"?
