### ISSUE TITLE
`mangohud sh -c 'echo XX$(cat /dev/null)XX'` can include MangoHud logs between the `XX`s

### ISSUE THREAD

**Issue by CobaltCause** [flightlessmango/MangoHud#1026]
**Describe the bug**

`mangohud yuzu` creates directories named after MangoHud log messages with a file called `profilerc` in them, the contents look like this:

```
$ cat \[2023-05-24\ 15:55:44.762\]\ \[error\]\ \[loader_x11.cpp:19\]\ Failed\ to\ open\ 64bit\ libX11.so.6:\ libX11.so.6:\ cannot\ open\ shared\ object\ file:\ No\ such\ file\ or\ directory/profilerc
[2023-05-24 15:55:44.766] [error] [loader_x11.cpp:19] Failed to open 64bit libX11.so.6: libX11.so.6: cannot open shared object file: No such file or directory

[x-scheme-handler/discord-712465656758665259 - 1]
Application=discord-712465656758665259.desktop
AllowAsDefault=true
GenericServiceType=Application
Preference=1
ServiceType=x-scheme-handler/discord-712465656758665259
```

After spending quite a while searching through various codebases and getting some help from various people (thank you!) to figure out what's going on, the order of events is:

1. mangohud runs yuzu
2. yuzu runs `xdg-mime`
    1. https://github.com/yuzu-emu/yuzu/blob/72a14a68177a7ecab4d36fbaf8533cf4e0d70566/src/yuzu/discord_impl.cpp#L22
    2. https://github.com/yuzu-emu/discord-rpc/blob/20cc99aeffa08a4834f156b6ab49ed68618cf94a/src/discord_rpc.cpp#LL273
    3. https://github.com/yuzu-emu/discord-rpc/blob/20cc99aeffa08a4834f156b6ab49ed68618cf94a/src/discord_rpc.cpp#L288
    4. https://github.com/yuzu-emu/discord-rpc/blob/20cc99aeffa08a4834f156b6ab49ed68618cf94a/src/discord_register_linux.cpp#L88
3. `xdg-mime` runs a bunch of stuff in a bash command substitution to build a path
    1. https://gitlab.freedesktop.org/xdg/xdg-utils/-/blob/8ae02631a9806da11b34cd6b274af02d28aee5da/scripts/xdg-mime.in#L142
4. The value it gets is completely unexpected because MangoHud's `LD_PRELOAD` causes it to print a log message to `stdout` at the beginning of every single subprocess
    1. The **suspected cause** is that https://github.com/flightlessmango/MangoHud/blob/ea3ba7e30d1ee6f742d6fa10506222789f37223a/src/loaders/loader_x11.cpp#L92 runs before https://github.com/flightlessmango/MangoHud/blob/ea3ba7e30d1ee6f742d6fa10506222789f37223a/src/gl/gl_hud.cpp#L74 which might otherwise cause this log message to go to `stderr`
5. `xdg-mime` goes about its business thinking it's gotten a suitable value
    1. https://gitlab.freedesktop.org/xdg/xdg-utils/-/blob/8ae02631a9806da11b34cd6b274af02d28aee5da/scripts/xdg-mime.in#L151 creates the directory named after the MangoHud log line
    2. The redirection on this line https://gitlab.freedesktop.org/xdg/xdg-utils/-/blob/8ae02631a9806da11b34cd6b274af02d28aee5da/scripts/xdg-mime.in#L211 in combination with MangoHud printing this log to `stdout` at the beginning of every subprocess explains why the contents of the file shown above also include a copy of the log message, because `awk` itself would be emitting it in addition to the things it's supposed to be emitting
6. There is now a directory named after a MangoHud log line in the current working directory with a file called `profilerc` in it that contains the log line again, among other things, as shown at the very beginning of this issue description

**List relevant hardware/software information**

- Linux Distribution: NixOS 23.11.20230523.d30264c (Tapir)
- MangoHud version: 0.6.9-1
- GPU: RX 7900 XTX

**To Reproduce**

1. Trigger any use of `spdlog` before `init_spdlog()` is called, for example by missing a shared library
2. Run `mangohud sh -c 'echo XX$(cat /dev/null)XX' 2> /dev/null`
3. Observe this output:
    ```
    [2023-05-24 19:30:39.822] [error] [loader_x11.cpp:19] Failed to open 64bit libX11.so.6: libX11.so.6: cannot open shared object file: No such file or directory
    XX[2023-05-24 19:30:39.825] [error] [loader_x11.cpp:19] Failed to open 64bit libX11.so.6: libX11.so.6: cannot open shared object file: No such file or directoryXX
    ```

**Expected behavior**

1. Run `mangohud sh -c 'echo XX$(cat /dev/null)XX' 2> /dev/null`
2. Observe this output:
    ```
    XXXX
    ```

**Comment by jackun** [comment]
Check if it fixes it https://github.com/flightlessmango/MangoHud/commit/5fde8749afc5d3f8c20abc66c3e16fb426dd82cc

**Comment by CobaltCause** [comment]
Yep, that fixes it! The behavior I see with that patch is exactly what's described in the "expected behavior" section, and `mangohud yuzu` doesn't make directories named after log messages anymore.
