### ISSUE TITLE
Blacklist requests

### ISSUE THREAD

**Issue by jackun** [flightlessmango/MangoHud#103]
Add blacklist requests here.
Current list:

* Battle.net.exe
* EpicGamesLauncher.exe
* IGOProxy.exe
* IGOProxy64.exe
* Origin.exe
* OriginThinSetupInternal.exe
* Steam.exe
* BethesdaNetLauncher.exe

**Comment by witchymary** [comment]
- ffxivlauncher.exe
- ffxivlauncher64.exe

**Comment by jackun** [comment]
>     * ffxivlauncher.exe
> 
>     * ffxivlauncher64.exe

For the record, in 8b13f8db7cef03833d7ab1adf07876ba9b6b99ee

**Comment by Sporif** [comment]
UplayService.exe, it doesn't have a gui but it may as well be blacklisted so it doesn't show up in the log.

**Comment by FaithLV** [comment]
```
Lutris
League Of Legends.exe
```

Lutris and League client segfault with `MANGOHUD=1`

**Comment by remi75** [comment]
"Oulala, on est pas sortie de l'auberge!"
This is going south way too deep, if "we" have to recompile to reinstall a program every time we want to inhibit the hud in an application it will never end, and is time consuming for, the developer, the resources, the users AND the distributions maintainers .

I highly recommend handling this by reading an auxiliary configuration file containing the names of the blacklisted applications, one can be shipped pre-filled, then the user can add later on extra data.

This should be easier on everyone .

Best regards

**Comment by gort818** [comment]
@remi75 You can leave l'auberge, this feature is in the latest release.

**Comment by remi75** [comment]
Super! :-)

And thank you for the message !

**Comment by vesterlay** [comment]
> launcher

For Unigine Superposition, the settings menu is just called launcher, so it's probably not a good idea.

**Comment by flightlessmango** [comment]
Don't think this is required anymore since the param exists
