### ISSUE TITLE
Show non-cached IO read/write, in MiB/s on Arch Linux

### ISSUE THREAD

**Issue by massatt212** [flightlessmango/MangoHud#1032]
**Describe the bug**
Show non-cached IO read/write, in MiB/s is showing zero on Arch and on Nobara its working.

**List relevant hardware/software information**
- Arch Linux
- mangohud 0.6.9.1-4
- RX 6400

How do i fix this problem?

**Comment by flightlessmango** [comment]
This doesn't sounds like a mangohud issue

**Comment by Xen192** [comment]
io rw is always 0 on my manjaro system as well
