### ISSUE TITLE
After running mangoapp, modifying the color parameters does not take effect.

### ISSUE THREAD

**Issue by Gawah** [flightlessmango/MangoHud#1037]
**Describe the bug**
After configuring the colors in the configuration file and then launching mangoapp, the colors will be updated. However, if color parameters (e.g. cpu_color) are modified after mangoapp is launched, the changes will not take effect. I have tested mangohud and found that it can modify colors during runtime.

**List relevant hardware/software information**
- OS: Arch Linux
- Kernel Version: 6.1.1-valve1-1-neptune-61 (64-bit)
- Processors: 16 × AMD Ryzen 7 6800U with Radeon Graphics
- RAM: 32 GB
- MangoHud version:0.6.9.r178.g4341843-1

**To Reproduce**
1.Run in the console: gamescope -- sh -c "mangoapp& vkcube"
2.Modifying the configuration parameters in the /home/deck/.config/MangoHud/MangoHud.conf directory, setting cpu_color=FFFFFF, does not result in a change in the color of the CPU font.

**Expected behavior**
After setting cpu_color=FFFFFF, the CPU font should appear white.

**Comment by flightlessmango** [comment]
fixed here 7c2a90c2094273fb1bba1aabb09e5c82c68f48be
