### ISSUE TITLE
Feature: single / total cores cpu load

### ISSUE THREAD

**Issue by axet** [flightlessmango/MangoHud#1038]
**Describe the bug**

Some games has single core engines and it loads 100% of single core. Bug total cpu usage become 20% which is not accurate since game can only utilize one core.

**List relevant hardware/software information**

- debian bookworm
- MangoHud 0.6.8-2

**Expected behavior**

allow to show single core cpu load + total load like this:

CPU 100% 20% 45°

**Comment by axet** [comment]
Right we can not know if game engine only using one core. But from user perspective showing single core usage and total usage would be more accurate.

here is a patch

https://gitlab.com/axet/homebin/-/blob/debian/cdebian-dget.d/bookworm/mangohud/cpusingle.patch

**Comment by axet** [comment]
For example game showing 30fps with 60fps limit. CPU usage 20% GPU usage  20%

From user perspective this makes no sense. What causing low FPS? We have to show a single core load (maximum load from all cores)

**Comment by flightlessmango** [comment]
You're making an assumption that the highest load on a core is from the game, which again we can't know. It could be anything. If the user happens to be running something in the background it will be even more confusing

**Comment by coffeecrisp** [comment]
I suppose it can be done since System Monitor in KDE can show a list of all processes and % CPU usage.
Then, you just do some math.
If the process uses 20% and you have 16 cores:
20% of 16 = 3.2 cores <==== we approximate to 3 cores.

MangoHud would display ===> This game is using 3 cores.

I am not an expert in Linux, so I do not know how to get that percentage for a process.

**Comment by axet** [comment]
We can call it compact version of 'core_load=1'. Modern CPU has a lot of cores (8-12). Showing all of them takes a lot of space on screen, and not very informative. Simply compact all cores into one maximum load core + showing total load can achieve the same result with one/two lines of text.

**Comment by coffeecrisp** [comment]
You want MangoHud to show only cores that are at 100% usage?
Can you write it as an algorithm?

**Comment by axet** [comment]
Algorithm? patch above

**Comment by flightlessmango** [comment]
I don't think this is a good idea

**Comment by JFingerle** [comment]
I know that this issue has been closed, but this would be a really good feature to detect a CPU bottleneck.

**Comment by axet** [comment]
Use patch from above. Histogram pull request does not cover it.

**Comment by JFingerle** [comment]
> Use patch from above. Histogram pull request does not cover it.

Thank you, but the patch in your gitlab repo is missing :(

**Comment by axet** [comment]
It's have been moved https://gitlab.com/axet/homebin/-/blob/debian/dbuild.d/bookworm/mangohud/cpusingle.patch
