### ISSUE TITLE
[Question] Is it possible to see all the CPU cores, their % usage and clock speed?

### ISSUE THREAD

**Issue by coffeecrisp** [flightlessmango/MangoHud#1039]
Is it possible to see all the CPU cores, their % usage and clock speed?

I usually run Steam games.
In the launch properties, I usually have the line
mangohud %command%

I tried a few combinations but I was not able to make it show each core.
It shows a clock speed and usage but I am not sure it is for which core.

**Comment by Billli11** [comment]
use `core_load`

check [README.md](https://github.com/flightlessmango/MangoHud#readme) for the options

**Comment by coffeecrisp** [comment]
Thanks. I can't believe I missed that.
