### ISSUE TITLE
Allow reading specific configuration file

### ISSUE THREAD

**Issue by Freso** [flightlessmango/MangoHud#104]
Right now MangoHud can read configurations from a [somewhat hardcoded set of locations](https://github.com/flightlessmango/MangoHud#hud-configuration).

This can cause issues with games that run through an interpreter (e.g., `java -jar ….jar` or `python ….py`) as MangoHud will look for a `MangoHud.conf` in places such as `/usr/lib/jvm/${javaversion}/jre/bin/` (Java on Arch Linux) or `/usr/bin`, or for `~/.config/MangoHud/java.conf` or `python.conf`.

Being able to specify a specific `.conf` file to read on program launch would provide much more flexibility in each cases and would often be easier to handle than managing a set of options in the `MANGOHUD_CONFIG` variable. Esp. so for cases such as using [MultiMC](https://multimc.org/) where you might want one configuration file for several difference game instances.

Maybe a `MANGOHUD_CONFIGFILE` environment variable could be an option, and/or extending the `read_cfg` option to take an optional argument as a path to a config file.

**Comment by jackun** [comment]
Added `MANGOHUD_CONFIGFILE=`
