### ISSUE TITLE
Intel GPU configs not working / GPUs not recognized (?)

### ISSUE THREAD

**Issue by Wonakiri** [flightlessmango/MangoHud#1041]
**Description**
Whenever I try to use a gpu related configuration (e.g. gpu_temp, ...) It just won't show.

**List relevant hardware/software information**
- Debian 'Release 12 (bookworm) 64-bit'
- MangoHud version: 'mangohud/testing 0.6.8-2'
- GPU: Intel Arc A750

**To Reproduce**
Use one of the "gpu configs" (e.g. gpu_temp) **!** 'gpu_name' is the only "gpu config" that worked for me **!**

**Expected behavior**
It won't show anything (e.g. If I put 'gpu_temp' It won't show anything, just the other things that don't have to do with the GPU).

**Screenshots**
![image](https://github.com/flightlessmango/MangoHud/assets/126415289/dd2d20ea-ef0d-405e-a25c-2e1bf8bc52a6)
![image](https://github.com/flightlessmango/MangoHud/assets/126415289/31ec1681-1318-4073-ba11-8120ca3d9cb6)

**Additional Information**
I'm using the launch option "MANGOHUD=1 %command%" on steam

**Comment by tazz4843** [comment]
This issue was fixed for a few weeks, but appears to be broken again now. Using Sniper runtime beta and Steam client beta, Satisfactory does not show GPU usage or GPU frequency, while it used to show both before. This happens in all Steam games.

**Comment by ToastedWookiee** [comment]
It looks Flatpak is required for this to work. I was getting:

```
Jul 23 05:09:36 Scott-PC steam-runtime-launch-client[86934]: E: Unable to connect to any of the specified bus names
Jul 23 05:09:36 Scott-PC plasmashell[86785]: [2023-07-23 05:09:36.334] [MANGOHUD] [info] [intel.cpp:66] Disabling gpu_stats
```

and testing in a terminal:

```
./steam-runtime-launch-client --alongside-steam --host --verbose -- intel_gpu_top
steam-runtime-launch-client[89825]: N: Enabled profiling
steam-runtime-launch-client[89825]: I: Unable to connect to com.steampowered.PressureVessel.LaunchAlongsideSteam: Could not get owner of name 'com.steampowered.PressureVessel.LaunchAlongsideSteam': no such name
steam-runtime-launch-client[89825]: I: Unable to connect to org.freedesktop.Flatpak: The name org.freedesktop.Flatpak was not provided by any .service files
steam-runtime-launch-client[89825]: E: Unable to connect to any of the specified bus names
steam-runtime-launch-client[89825]: D: Exiting with status 125
```

Running Arch, so after installing Flatpak the terminal command worked, as well as the MangoHud GPU stats in games as well.

**Comment by flightlessmango** [comment]
> It looks Flatpak is required for this to work.

Correct and I should have mentioned that. When it's fully implemented in the runtime you won't need flatpak anymore tho

**Comment by flightlessmango** [comment]
Moving conversation to #1082
