### ISSUE TITLE
Recent Arch Linux Upgrade breaks Proton/Wine Games

### ISSUE THREAD

**Issue by FormBurden** [flightlessmango/MangoHud#1046]
**Describe the bug**
After doing a pacman upgrade (last one I did was 6/08/23, which Mango works), it seemed to have broken games that run on Proton/Wine on Steam. I played a linux native game, and Mango still works correctly. 

I reverted back to above date (pacman packages), and ignored the following packages, and it seems to be looking towards one of the GPU/mesa packages, for my AMD GPU.

``` 
warning: lib32-libva-mesa-driver: ignoring package upgrade (23.1.1-1 => 23.1.2-1)
warning: lib32-libxcrypt: ignoring package upgrade (4.4.34-1 => 4.4.35-1)
warning: lib32-mesa: ignoring package upgrade (23.1.1-1 => 23.1.2-1)
warning: lib32-openssl: ignoring package upgrade (1:3.0.9-1 => 1:3.1.1-1)
warning: lib32-vulkan-icd-loader: ignoring package upgrade (1.3.245-1 => 1.3.251-1)
warning: lib32-vulkan-radeon: ignoring package upgrade (23.1.1-1 => 23.1.2-1)
warning: libva-mesa-driver: ignoring package upgrade (23.1.1-1 => 23.1.2-1)
warning: mesa: ignoring package upgrade (23.1.1-1 => 23.1.2-1)
warning: vulkan-headers: ignoring package upgrade (1:1.3.248-1 => 1:1.3.253-1)
warning: vulkan-icd-loader: ignoring package upgrade (1.3.245-1 => 1.3.251-1)
warning: vulkan-radeon: ignoring package upgrade (23.1.1-1 => 23.1.2-1)
warning: wine: ignoring package upgrade (8.9-1 => 8.10-1)

``` 

Pretty much what happens is the overlay on the game is not there at all, even with all the commands you can use for troubleshooting (from main page). 

**List relevant hardware/software information**
- Arch Linux
- MangoHud: 0.6.9.1-6 - yay version
- AMD RX 6900 XT

**To Reproduce**
AMD GPU, Mesa packages, pretty much the above packages on Arch-Linux, upgrade date: 6-14-23 for pacman. Downgraded to date 6-08-23, and everything works correctly.

**Additional context**
Doubt it's the Wine package because I did downgrade that first, but issue still happened before I downgraded all the packages.

**Comment by fpennica** [comment]
I can confirm, mangohud package v. 0.6.9.1-6 works with opengl (`mangohud glxgears`) but not with vulkan (`mangohud vkcube`).

Solved by replacing it with `mangohud-git`.

**Comment by flightlessmango** [comment]
Try recompiling mangohud. If a package that mangohud depends on has been upgraded, then mangohud needs to be recompiled

**Comment by serebit** [comment]
Package maintainer here, working on this.

**Comment by wilk85** [comment]
i had different problem, on latest steam update mangohud stopped working, it's working fine on lutris

**Comment by wilk85** [comment]
Hello guys, im adding resolution to mangohud problem, which have helped me 
https://forum.garudalinux.org/t/steam-mangohud-stopped-working/29156/13
