### ISSUE TITLE
Latest commit to install Mangoapp by default breaks build on Wayland

### ISSUE THREAD

**Issue by stele95** [flightlessmango/MangoHud#1047]
**Describe the bug**
[Latest commit](https://github.com/flightlessmango/MangoHud/commit/801b5ef5fc88de8d3db0b34ad5d30651f4f4c5ea) broke the build process on Wayland. I've tried the previous commit that doesn't build Mangoapp by default and the build is passing.
My guess is that the Mangoapp is not recognizing Wayland since this (picture below) is the output I'm getting when it fails. It's looking for `glfw-x11`, but `glfw-wayland` is installed since I'm on Wayland.

![image](https://github.com/flightlessmango/MangoHud/assets/26225081/54e95133-55d4-4c00-a0e6-0e81acf73fb8)

**List relevant hardware/software information**
- Linux Distribution: EndeavourOS
- MangoHud version: Latest git commit, link at the start of the issue

**To Reproduce**
1. Try building the latest commit on Wayland

**Comment by flightlessmango** [comment]
reverted here 381c519631510735d1538765114c689feae4588d
