### ISSUE TITLE
MangoHud hud does not display in Serious Sam Classics Revolution

### ISSUE THREAD

**Issue by Growebis** [flightlessmango/MangoHud#1049]
**Describe the bug**
Trying to run MangoHud hud on Serious Sam Classics Revolution with `mangohud %command%` does nothing, it doesn't do anything, i tried to run it with `mangohud --dlsym %command%` and it only worked 2 times, but the second i try to switch windows and then try to comeback, it disappears once again. Then second time it worked but the game screen was frozen but i could still interact with the menu.
**List relevant hardware/software information**
- Linux Mint 21.1 Cinnamon "Vera" 
- MangoHud version 0.6.9-1
- Nvidia Geforce 1650 TI
- Intel core i5 10300H
**To Reproduce**
1. put the `mangohud --dlsym %command%` in the console properties in steam
2. run the game and wait for a bit
3. game loads but it isnt there

**Expected behavior**
to see the MangoHud hud

**Screenshots**

https://github.com/flightlessmango/MangoHud/assets/113867283/03273adf-9f17-44f5-bbc2-f05b6521e740

**Additional context**

it only worked 2 times for some reason, maybe because the engine for the game is really old?

**Comment by flightlessmango** [comment]
![image](https://github.com/flightlessmango/MangoHud/assets/42713625/adf41c0d-5fe0-4f3c-9952-6e9b732becc0)
Works just fine here, no dlsym or anything.
Do you have 32bit mangohud libs installed?

**Comment by Growebis** [comment]
I tried to install mangohud 32bit libs and i still dont see the hud. I just want to check how can i tell i also have 32bit mangohud libs? Also try switching windows and see if it the hud is still there.

**Comment by flightlessmango** [comment]
> how can i tell i also have 32bit mangohud libs

You need to run a 32bit app to verify that it works.
Like another game you have that is 32bit, possibly glxgears32

> Also try switching windows and see if the hud is still there.

There is no window tabbing in my WM so I can't try easily.

**Comment by flightlessmango** [comment]
I was able to repro the issue and the `gl_bind_framebuffer=0` workaround fixes it.
