### ISSUE TITLE
Overlay not displaying for Non-Steam Game

### ISSUE THREAD

**Issue by FireCulex** [flightlessmango/MangoHud#105]
Using the Launch Parameter
`mangohud MANGOHUD_CONFIG=output_file=/home/culex/doom3fps.log,log_duration=90 %command%`

Adding RBDoom3BFG.exe as a non-steam game the overlay does not display.

If I rename RBDoom3BFG.exe to Doom3BFG.exe and launch as a steam game the overlay is displayed.

Not sure how to diagnose?

**Comment by flightlessmango** [comment]
I think that's a steam issue, everything before `%command%` doesn't register with non-steam games. I usually add `"MANGOHUD": "1",` to the proton config instead

**Comment by FireCulex** [comment]
That is actually 100x more convenient than adding custom launch parameters to each and every game. I'd recommend adding it as a method on the main page. 

Other non-steam games I was launching having to launch mangohud proton via cmdline before now work within Steam itself. yay! However this appears to only work if the API is DXVK and not OpenGL.

**Comment by flightlessmango** [comment]
That is correct. `MANGOHUD=1` only activates the vulkan layer, that's why I don't recommend it, could be mentioned as a option with caveats

**Comment by Faalagorn** [comment]
I think it's https://github.com/ValveSoftware/steam-for-linux/issues/6046 if someone want to see the appropriate bug report upstream
