### ISSUE TITLE
vram usage always shows 0

### ISSUE THREAD

**Issue by joelsgp** [flightlessmango/MangoHud#1050]
**Describe the bug**

**List relevant hardware/software information**
- Linux Distribution
arch
linux 6.3.8.arch1-1
kde

- MangoHud version
0.6.9.1-6

- GPU
msi radeon rx 570 4G

**To Reproduce**
1. enable `vram` in .config/MangoHud/MangoHud.conf
2. run `mangohud glxgears`

**Expected behavior**
vram is displayed the same as nvtop does it, e.g. 1.885Gi/4.000Gi

**Screenshots**

nvtop displaying vram usage correctly
![image](https://github.com/flightlessmango/MangoHud/assets/26749912/34c85edf-d2b0-4476-8db5-99905e87f08c)

mangohud displays 0.0GiB
![image](https://github.com/flightlessmango/MangoHud/assets/26749912/e0672e25-8b17-43e3-92d8-f7978205a84f)

**Additional context**

doesn't display vram in any application, opengl, vulkan, dxvk, whatever

**Comment by flightlessmango** [comment]
what does `cat /sys/class/drm/card0/device/mem_info_vram_used` return?

**Comment by joelsgp** [comment]
```shell
user@host ~> cat /sys/class/drm/card0/device/mem_info_vram_used
2131996672
user@host ~>
```

**Comment by flightlessmango** [comment]
This should be resolved at least in 0.7, reopen if still an issue

**Comment by joelsgp** [comment]
fixed

**Comment by flightlessmango** [comment]
thanks for confirming :+1:

**Comment by LethalManBoob** [comment]
broke for me as of latest mangohud-git on aur

**Comment by SiemdeNijs** [comment]
> broke for me as of latest mangohud-git on aur (chaotic-aur)

same here with latest mangohud-git on aur Arch but also tried latest git pull / build.sh, same issue. Works fine on "stable" branch.

**Comment by flightlessmango** [comment]
Please create a new issue and supply information on the setup
