### ISSUE TITLE
The `alpha` option does not apply to any text since v0.6.9 

### ISSUE THREAD

**Issue by GrzegorzKozub** [flightlessmango/MangoHud#1051]
**Describe the bug**

The `alpha` option does not apply to any text since v0.6.9. It does still apply to frametime graph in my config.

**List relevant hardware/software information**

- Arch Linux
- MangoHud v0.6.9 
- RTX 3080

**To Reproduce**

Config:

```
alpha=0.33
background_alpha=0

text_color=c0c0c0
gpu_color=c0c0c0
cpu_color=c0c0c0
vram_color=c0c0c0
ram_color=c0c0c0
engine_color=c0c0c0
frametime_color=c0c0c0
io_color=c0c0c0
```

**Expected behavior**

Text is barely visible. Like a watermark. 

**Screenshots**

Since v0.6.9 the `alpha` is not applied to text and you can only see it applied to my time graph.

<img width="245" alt="image" src="https://github.com/flightlessmango/MangoHud/assets/154056/4c724428-4d8a-437e-96e8-625e319eb23a">

**Comment by flightlessmango** [comment]
Should be fixed here 41f8446cf13c672da51100c014fc518c27d2768c and here 1f2b31008e3cc48c96ae10d0380dff1b499c6871
