### ISSUE TITLE
CPU Power Draw

### ISSUE THREAD

**Issue by pl232602** [flightlessmango/MangoHud#1056]
MangoHud displays the wrong CPU power draw in Watts. The value displayed does not line up with zenmonitor3 or s-tui.

OS: Arch Linux x86_64
Motherboard: B550M AORUS ELITE
Kernel: 6.3.9-arch1-1
DE: Plasma 5.27.6 
WM: KWin
CPU: AMD Ryzen 5 5600X (12) @ 3.700GHz
GPU: NVIDIA GeForce GTX 1060 3GB

1. Enable MangoHud
2. Enable Power metric under CPU

![image_2023-06-25_105706992](https://github.com/flightlessmango/MangoHud/assets/90462248/9db180df-826f-43e5-9466-024ba1e16265)

**Comment by flightlessmango** [comment]
It looks like we're calculating core power and soc power, I don't know what the remainder is and where they get that from

**Comment by pl232602** [comment]
Would the package power be higher than core and soc due to cache?

**Comment by pl232602** [comment]
Would it be possible for Mangohud to utilize the package power, or would the root permission for msr block that?

**Comment by flightlessmango** [comment]
In order to do it we would have to have a helper program that runs beside mangohud and has root permissions
