### ISSUE TITLE
Can't get nvidia information in Debian 12 bookworm

### ISSUE THREAD

**Issue by Mario156090** [flightlessmango/MangoHud#1061]
**Describe the bug**
If you want to execute mangohud with any vulkan app, video card information does not appears. Appears message:

[2023-07-02 10:50:01.617] [MANGOHUD] [error] [nvctrl.cpp:53] XNVCtrl didn't find the correct display

**List relevant hardware/software information**
- Debian 12 bookworm
- MangoHud version 0.6.8-2 amd64
- RTX3060

**To Reproduce**
1. Execute mangohud vkcube
2. get not show video card values

**Expected behavior**
Shows video card values

**Screenshots**

VKcube execution:
![image](https://github.com/flightlessmango/MangoHud/assets/47507975/cd13af10-d8c3-4ed1-bcc1-48d41e106524)

nvidia-smi query:
![image](https://github.com/flightlessmango/MangoHud/assets/47507975/bdb2af8b-71f9-4eb2-a170-23af9d521ccf)

mangohud error:
![image](https://github.com/flightlessmango/MangoHud/assets/47507975/88f0272d-3a94-4003-8c9d-0b7e946df5a8)

**Additional context**

**Comment by Mario156090** [comment]
Closed, fixed adding the nvidia-primus-vk-common package.

**Comment by flightlessmango** [comment]
The Debian mangohud package comes without nvml since it's non-free

**Comment by Mario156090** [comment]
> The Debian mangohud package comes without nvml since it's non-free

Hello @flightlessmango  so what I should to do?

compile from source code?

**Comment by flightlessmango** [comment]
Compiling from source should resolve your issue yes

**Comment by Mario156090** [comment]
> Compiling from source should resolve your issue yes

![image](https://github.com/flightlessmango/MangoHud/assets/47507975/bc9bc91f-4a20-45d5-8600-76d88ea2effa)

After compile I can get nvidia monitoring but appears that error message.

**Comment by flightlessmango** [comment]
You can ignore that error, you're not using that method anyway so it has no effect

**Comment by Mario156090** [comment]
> You can ignore that error, you're not using that method anyway so it has no effect

Thank's a lot, this is working. :)
