### ISSUE TITLE
[Feature] Playtime counter

### ISSUE THREAD

**Issue by jarrard** [flightlessmango/MangoHud#1064]
Just a suggestion, it be nice if you could also setup a play timer for keeping track how long game has been running.

**Comment by flightlessmango** [comment]
This already exists but probably not documented yet. `duration` option

**Comment by jarrard** [comment]
Do you mean log_duration? I thought that was just for log file duration.

**Comment by flightlessmango** [comment]
No I mean `duration` 30748bd
