### ISSUE TITLE
Red Faction (2001) MangoHud fails to run

### ISSUE THREAD

**Issue by Frambooisier** [flightlessmango/MangoHud#1066]
**Describe the bug**
MangoHud is not showing up when starting Steam version of Red Faction 2001 (appID20530) with protonexperimental and ``mangohud %command%`` launch option or `mangohud --dlsym %command%`

mangohud works fine with D8VK and Red Faction via proton and Tony hawk 3 via wine

the errors I could see in atteched log file:

``ERROR: ld.so: object '/tmp/pressure-vessel-libs-ZONL71/${PLATFORM}/libMangoHud_dlsym.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/tmp/pressure-vessel-libs-ZONL71/${PLATFORM}/libMangoHud.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.``

I also tried these launch options, if it's relevant I have log files for each combination:

both 32 and 64 bit at the same time (dunno if it's even legal)

``LD_PRELOAD=$LD_PRELOAD:/usr/lib/mangohud/lib64/libMangoHud_dlsym.so:/usr/lib/mangohud/lib64/libMangoHud.so:/usr/lib/mangohud/lib32/libMangoHud_dlsym.so:/usr/lib/mangohud/lib32/libMangoHud.so PROTON_LOG=1 mangohud --dlsym %command%``

64 bit only

``LD_PRELOAD=$LD_PRELOAD:/usr/lib/mangohud/lib64/libMangoHud_dlsym.so:/usr/lib/mangohud/lib64/libMangoHud.so PROTON_LOG=1 mangohud --dlsym %command%``

32bit only

``LD_PRELOAD=$LD_PRELOAD:/usr/lib/mangohud/lib32/libMangoHud_dlsym.so:/usr/lib/mangohud/lib32/libMangoHud.so PROTON_LOG=1 mangohud --dlsym %command%
``

**List relevant hardware/software information**
- Linux Distribution Kubuntu 23.04
- MangoHud version 0.6.9-1(BTW WHAT IS THE FASTEST WAY TO CHECK VERSION like mangohud --version)
- GPU RTX 3070
-I initially installed mangohud from ubuntu repo, but I assume it was missing 32bit becuase it was not wroking with D8VK and Redfaction and tony hawk 3, after installing mangohud from github script it's working fine.
**To Reproduce**
1. launch red faction with `mangohud --dlsym %command%`
2. observe no hud

**Expected behavior**

**Screenshots**

**Additional context**
[steam-20530.log](https://github.com/flightlessmango/MangoHud/files/12032477/steam-20530.log)

**Comment by flightlessmango** [comment]
> mangohud works fine with D8VK and Red Faction via proton and Tony hawk 3 via wine

>after installing mangohud from github script it's working fine

What exactly isn't working?

**Comment by flightlessmango** [comment]
This game requires the opengl workaround `gl_bind_framebuffer=0`
Another option is to install d8vk

**Comment by Frambooisier** [comment]
how should this workaround be applied, I can't seem to find the proper steam command to do that

**Comment by gort818** [comment]
Add `gl_bind_framebuffer=0` to your MangoHud.conf file
