### ISSUE TITLE
blue overlay

### ISSUE THREAD

**Issue by FireCulex** [flightlessmango/MangoHud#107]
![Screenshot from 2020-03-27 13-23-44](https://user-images.githubusercontent.com/9983630/77797474-5aa83100-702e-11ea-838e-f8f8b3ea39c3.png)
If I compile RBDoom3BFG using OpenGL the overlay turns blue. I can still output fps with a duration using the hotkey, but the overlay itself is corrupted. Native binary not using Steam.

**Comment by jackun** [comment]
I think this is mostly fixed in `develop`. Re-open if not.
