### ISSUE TITLE
[BUG] Sonic and all stars racing transformed crashes with mangohud

### ISSUE THREAD

**Issue by Garbg** [flightlessmango/MangoHud#1072]
**Describe the bug**

**List relevant hardware/software information**
- Linux Distribution
Opensuse tumbleweed
- MangoHud version
0.6.9~1-1.4
- GPU
AMD Radeon RX 6600

**To Reproduce**
1. Go to 'Sonic and all stars racing transformed' on steam
2. Change custom launch options to 'mangohud %command%'
3. Launch game
4. Witness the game crash
**Expected behavior**
The game should launch properly

**Screenshots**

https://github.com/flightlessmango/MangoHud/assets/83542885/9aab7db0-fe46-47ee-912f-a1df728dbb90

**Comment by flightlessmango** [comment]
A steam log file could be useful

**Comment by Garbg** [comment]
where can I find the logs?

**Comment by Garbg** [comment]
It seems this game does not have a logging system, I looked everywhere for log files in the game files and compatdata. Then I tried launching the game from the terminal without mango hud with the following command: ```protontricks-launch --appid 212480 ASN_App_PcDx9_Final.exe``` but then it crashed instantly

**Comment by flightlessmango** [comment]
set `PROTON_LOG=1 %command%` in launch options of the game and then you should see `steam-$game_appid` in your home folder after you've tried to run the game

**Comment by Garbg** [comment]
Log without mangohud (game runs normally):
[withoutmangohud.log](https://github.com/flightlessmango/MangoHud/files/12099653/withoutmangohud.log)
Log with mangohud (game crashes)
[withmangohud.log](https://github.com/flightlessmango/MangoHud/files/12099664/withmangohud.log)

**Comment by flightlessmango** [comment]
`error while loading shared libraries: libspdlog.so.1.12: cannot open shared object file: No such file or directory` is probably the issue.

Either you need to install spdlog or you need to recompile mangohud with the current spdlog version

**Comment by Garbg** [comment]
It works for other games like tf2 and trackmania though

**Comment by flightlessmango** [comment]
Did you install mangohud from the official opensuse repos?

**Comment by Garbg** [comment]
yes

**Comment by flightlessmango** [comment]
![image](https://github.com/flightlessmango/MangoHud/assets/42713625/a30c923a-18d1-4641-ad40-4c1c6b753ade)
It's works fine here. I would wager there's something off with the opensuse package or it's been fixed in latest mangohud git

**Comment by Garbg** [comment]
I built mangohud from git and the game launches successfully but mangohud is empty 
![image](https://github.com/flightlessmango/MangoHud/assets/83542885/235831ae-d025-4d11-a866-c722f82b0f12)

**Comment by flightlessmango** [comment]
What's in your config?

**Comment by Garbg** [comment]
This is my config in ~/.config/MangoHud/MangoHud.conf (it looks like it was created by goverlay which I installed with mangohud when I installed it from the opensuse repos, my current install is built from git)
```
################### File Generated by GOverlay ###################

toggle_fps_limit=F1


legacy_layout=false
gpu_load_change
gpu_load_value=50,90
gpu_load_color=FFFFFF,FFAA7F,CC0000
gpu_text=GPU
cpu_load_change
core_load_change
cpu_load_value=50,90
cpu_load_color=FFFFFF,FFAA7F,CC0000
cpu_color=2e97cb
cpu_text=CPU
io_color=a491d3
vram_color=ad64c1
ram_color=c26693
engine_color=eb5b5b
gpu_color=2e9762
wine_color=eb5b5b
frame_timing=0
frametime_color=00ff00
media_player_color=ffffff
table_columns=3
background_alpha=0.4
font_size=24

background_color=020202
position=top-left
text_color=ffffff
round_corners=0
#GOVERLAY_THEME=mangohuddefault
toggle_hud=Shift_R+F12
toggle_logging=Shift_L+F2
upload_log=F5
output_folder=/home/garbg
media_player_name=spotify
```

**Comment by Garbg** [comment]
After using the example config that fixed it
