### ISSUE TITLE
GPU fan RPM not showing

### ISSUE THREAD

**Issue by chardinson** [flightlessmango/MangoHud#1076]
**Describe the bug**
I have enabled the `gpu_fan` variable in the MangoHud configuration file. However, when MangoHud displays information, it does not display the information about the GPU fan RPM.

**List relevant hardware/software information**
- Fedora release 38 (Thirty Eight)
- MangoHud 0.6.9-1
- AMD Radeon™ RX 590 Series
- Flatpak 1.15.4

**To Reproduce**

1. Go to `/var/home/chardinson/.var/app/com.valvesoftware.Steam/config/MangoHud/MangoHud.conf`.
2. Remove `#` from the `gpu_fan` variable.
3. Add variable `MANGOHUD=1` to Steam Flatpak.
4. Start Steam Flatpak.
5. Launch a game.
6. The game will not display the fan RPM.

**Expected behavior**
A new line showing the RPM of the GPU fan.

**Screenshots**
![Screenshot from 2023-07-21 15-55-16](https://github.com/flightlessmango/MangoHud/assets/36754778/9406b7b4-5bbb-4c61-8c44-c48ffcad42df)
![Screenshot from 2023-07-21 13-59-34](https://github.com/flightlessmango/MangoHud/assets/36754778/02cb6fb6-649c-4a27-879f-cc425b963caa)

**Additional context**
I am using the Flatpak version.

**Comment by flightlessmango** [comment]
Gpu fan isn't in 0.6.9, will be included in next release
