### ISSUE TITLE
GPU Usage Not Showing on 700 (Kepler) 

### ISSUE THREAD

**Issue by BrainlessDylan** [flightlessmango/MangoHud#108]
hey so Ive been trying multiple distros, the precompiled & built from source and no matter what i do i can not seem to get the GPU stats to show at all, does mangohud not support 700 series?

Hardware used:
OS:  Kubuntu 18.04
CPU: Athlon X4 860K Black Edition 4.70GHz 
GPU: ASUS GTX 760
GPU Driver: 440.64
RAM: 14GB Crucial DDR3 2400
Motherboard: GIGABYTE GA-F2A68HM-S1
SSD: SanDisk SSD PLUS 120 GB
HDD: 1TB WD Blue 7200rpm HDD

**Comment by guihkx** [comment]
https://github.com/flightlessmango/MangoHud/issues/3#issuecomment-602748292
