### ISSUE TITLE
MangoHud Intel GPU metrics

### ISSUE THREAD

**Issue by flightlessmango** [flightlessmango/MangoHud#1082]
This issue is for tracking the progress and issues with Intel GPU metrics. dGPU and iGPU.

### Current state
- `intel_gpu_top` has to be installed and it has to be setcap'd  e.g `sudo setcap cap_perfmon=+ep /usr/bin/intel_gpu_top`
- We are set up to get GPU load at least from `intel_gpu_top`
- MangoHud is only able to run `intel_gpu_top` unhindered outside of proton/runtime
- In order for us to run `intel_gpu_top` you need to have flatpak installed and set sniper runtime to beta

**Comment by flightlessmango** [comment]
What mangohud version are you using?

**Comment by nokia8801** [comment]
It does not work for me either with `sudo setcap cap_perfmon=+ep /usr/bin/intel_gpu_top`.

`getcap /usr/bin/intel_gpu_top` shows it is applied correctly.
`/usr/bin/intel_gpu_top cap_perfmon=ep`

```
Failed to initialize PMU! (Permission denied)

When running as a normal user CAP_PERFMON is required to access performance
monitoring. See "man 7 capabilities", "man 8 setcap", or contact your
distribution vendor for assistance.

More information can be found at 'Perf events and tool security' document:
https://www.kernel.org/doc/html/latest/admin-guide/perf-security.html
[2024-01-22 15:52:48.046] [MANGOHUD] [info] [intel.cpp:74] Missing permissions for 'intel_gpu_top'
[2024-01-22 15:52:48.046] [MANGOHUD] [info] [intel.cpp:76] Disabling gpu_stats
```
MangoHud 0.7.0-2+
Arch Linux
GNOME 45.3 on Wayland
Linux 6.7.0-arch3-1

**Comment by tazz4843** [comment]
> MangoHud is only able to run intel_gpu_top unhindered outside of proton/runtime
> In order for us to run intel_gpu_top you need to have flatpak installed and set sniper runtime to beta

These two points seem to be fixed, I have everything working in Proton 8.0-5, v0.7.0-2+ with no hitches. GPU load and frequency function without issues.

Only major remaining thing that would be nice is GPU power draw.

**Comment by kira-bruneau** [comment]
I was just wondering, is there a specific reason why intel gpu metrics are collected with `intel_gpu_top`? It looks like it should be possible to obtain the same stats through the drm & hwmon kernel interfaces, like what's done in resources: https://github.com/nokyan/resources/blob/v1.4.0/src/utils/gpu/intel.rs#L38.

That way you wouldn't need to rely on `intel_gpu_top` being installed and having it setcap'd.

**Comment by flightlessmango** [comment]
> is there a specific reason why intel gpu metrics are collected with intel_gpu_top

Most of these metrics required root for access and as a shared library we're not able to access root things without a middle man program

**Comment by jcsstelar** [comment]
Hi hi, after upgrading to 0.7.2 from 0.7.1 (flatpak) my GPU % use is always 0. I have an iGPU that is HD610. Im with ubuntu 22.04.4 and I use MangoHud with retroarch, lutris and also steam, not sure if I can help, Im new to linux. Love your work <3

**Comment by KF-Art** [comment]
Setcapping` intel_gpu_top` made it show the usage percentage, but it only works if I'm running a OpenGL game. If I use Vulkan, it will remain at 0%. This happens as well if the game is running with the card that was not used to start Xorg. For example, If I'm using my dGPU to start Xorg and I start a game using the iGPU (both Intel, of course), it will remain at 0%, but `intel_gpu_top` does shows the usage regardless of that.

I'm using Intel Iris Xe as iGPU and Intel Iris Xe MAX as dGPU (both working with i915 driver).

**Comment by eclairevoyant** [comment]
pretty sure igt doesn't support xe yet, unless I've missed some recent release or such.

**Comment by KF-Art** [comment]
> pretty sure igt doesn't support xe yet, unless I've missed some recent release or such.

Well, at least in my case it seems to work correctly. I don't know if all features are supported yet, though.

![imagen](https://github.com/user-attachments/assets/0e10bb97-5de4-46b7-b117-543de3a8aa08)

![imagen](https://github.com/user-attachments/assets/87e77fd3-5c0d-4b5e-a045-5a6ea4142cfd)

(The second one is the Intel Iris Xe MAX discrete GPU).

**Comment by retrixe** [comment]
For the new Xe kmd, `gputop` is the new monitoring utility for getting GPU utilisation stats

Xe kmd is the new default on my Lunar Lake system so unfortunately GPU utilisation under mangohud is totally unavailable

**Comment by flightlessmango** [comment]
Should be easily added into mangohud.
Just not sure which is which regarding `rcs, ccs, bcs, vcs, vecs`

**Comment by retrixe** [comment]
These docs explain the meaning of these fields: https://dri.freedesktop.org/docs/drm/gpu/i915.html#intel-gpu-basics

It seems RCS is what "Render/3D" refers to in `intel_gpu_top` as the segment responsible for compute and 3D rendering, so I guess it's the field that's most relevant to mangohud

**Comment by flightlessmango** [comment]
Yeah that seems about right

**Comment by 17314642** [comment]
https://www.kernel.org/doc/Documentation/gpu/i915.rst
CTRL + F for "Render Command Streamer"

in short:
rcs - Render Command Streamer (3D Graphics)
bcs - Blitting Command Streamer (Data Copying)
vcs - Video Command Streamer (Hardware Encoding and Decoding (H.264, HEVC, AV1))
vecs - Video Enhancement Command Streamer (Video Super Resolution)
ccs - Compute Command Streamer (GPGPU like AI and OpenCL, Hashcat)

**Comment by retrixe** [comment]
`gputop` reports an output like this, as far as I can tell, it doesn't have an option to report JSON, CSV or anything machine readable

<details>
<summary>Details</summary>

```
DRM minor 0                                                                                     
  PID      MEM      RSS     rcs        vcs       vecs        bcs        ccs     NAME            
 2572       1G       1G |  0.8% ▏ ||  0.0%   ||  0.0%   ||  0.0%   ||  0.0%   | gnome-shell     
 5816       0B       0B |  0.0%   ||  0.0%   ||  0.0%   ||  0.0%   ||  0.0%   | Xwayland        
DRM minor 128                                                                                   
  PID      MEM      RSS     rcs        vcs       vecs        bcs        ccs     NAME            
 2572       0B       0B |  0.0%   ||  0.0%   ||  0.0%   ||  0.0%   ||  0.0%   | gnome-shell     
 3595       0B       0B |  0.0%   ||  0.0%   ||  0.0%   ||  0.0%   ||  0.0%   | ptyxis          
 3595     218M     218M |  0.0%   ||  0.0%   ||  0.0%   ||  0.0%   ||  0.0%   | ptyxis          
 5758       0B       0B |  0.0%   ||  0.0%   ||  0.0%   ||  0.0%   ||  0.0%   | chrome          
 5816      14M      14M |  0.0%   ||  0.0%   ||  0.0%   ||  0.0%   ||  0.0%   | Xwayland        
 5851     308K     308K |  0.0%   ||  0.0%   ||  0.0%   ||  0.0%   ||  0.0%   | gsd-xsettings   
 5815     120M     120M |  0.0%   ||  0.0%   ||  0.0%   ||  0.0%   ||  0.0%   | chrome          
 5940       2M       2M |  0.0%   ||  0.0%   ||  0.0%   ||  0.0%   ||  0.0%   | mutter-x11-fram 
 5815     394M     394M |  0.0%   ||  0.0%   ||  0.0%   ||  0.0%   ||  0.0%   | chrome          
 5815       0B       0B |  0.0%   ||  0.0%   ||  0.0%   ||  0.0%   ||  0.0%   | chrome          
 7193      36M      36M |  0.0%   ||  0.0%   ||  0.0%   ||  0.0%   ||  0.0%   | Discord         
 7193     181M     181M |  0.0%   ||  0.0%   ||  0.0%   ||  0.0%   ||  0.0%   | Discord         
 7193       0B       0B |  0.0%   ||  0.0%   ||  0.0%   ||  0.0%   ||  0.0%   | Discord         
 3595       6M       6M |  0.0%   ||  0.0%   ||  0.0%   ||  0.0%   ||  0.0%   | ptyxis          
68586       0B       0B |  0.0%   ||  0.0%   ||  0.0%   ||  0.0%   ||  0.0%   | gnome-system-mo 
68586      71M      71M |  0.0%   ||  0.0%   ||  0.0%   ||  0.0%   ||  0.0%   | gnome-system-mo 
```

</details>

> So specifically `drm-cycles-rcs` for util?

If you're calling the DRM client usage stats API, looking at gputop's [code](https://gitlab.freedesktop.org/drm/igt-gpu-tools/-/blob/master/tools/gputop.c), it seems to be taking the delta of `drm-cycles-rcs` and `drm-total-cycles-rcs` over 2 seconds (by default), then dividing the increase in cycles by the increase in total cycles to get the utilisation of the RCS engine

**Comment by PerAstraAdDeum** [comment]
With the release of the 6.12 Kernel I made the switch to the xe driver and so far it's been smooth sailing. I'd love for mangohud to display GPU metrics, is there any way I can feed the `gpu-top` data to mangohud?

**Comment by 17314642** [comment]
@PerAstraAdDeum support for `xe` driver will be available by the end of the week in master branch, so you'll have to compile it yourself or wait for a new release.

**Comment by PerAstraAdDeum** [comment]
Ohh nice! Can I just install `mangohud-git` from the AUR once support for the `xe` driver has landed in the master branch, or do I need to compile it then?

**Comment by 17314642** [comment]
@PerAstraAdDeum I think you can just install `mangohud-git` because yay compiles it for you.

While we're at it, can you launch this in terminal?

```
ls /sys/class/drm/renderD*/device/hwmon/hwmon*/energy*
ls -ld /sys/class/drm/renderD*/device/driver
```

I want to compare against my intel card if everything's the same.

**Comment by PerAstraAdDeum** [comment]
> @PerAstraAdDeum I think you can just install `mangohud-git` because yay compiles it for you.
> 
> While we're at it, can you launch this in terminal?
> 
> ```
> ls /sys/class/drm/renderD*/device/hwmon/hwmon*/energy*
> ls -ld /sys/class/drm/renderD*/device/driver
> ```
> 
> I want to compare against my intel card if everything's the same.

I'm on MTL iGPU! (Intel(R) Core(TM) Ultra 7 155H with Intel Arc Graphics). Here's the output of the commands you gave me:

`ls /sys/class/drm/renderD*/device/hwmon/hwmon*/energy*`

-->

`ls: cannot access '/sys/class/drm/renderD*/device/hwmon/hwmon*/energy*': No such file or directory`

`ls -ld /sys/class/drm/renderD*/device/driver`

-->

`lrwxrwxrwx 1 root root 0 Nov 25 13:20 /sys/class/drm/renderD128/device/driver -> ../../../bus/pci/drivers/xe`

Hope that helps!

**Comment by 17314642** [comment]
Thank you, and I forgot last one:

`ls /sys/class/drm/renderD128/device/hwmon/*`

I'm checking for whether I need to account for different `energy` files to get power usage. In your case you don't have file called `energy2_input`, so power usage might now work.

**Comment by PerAstraAdDeum** [comment]
`ls /sys/class/drm/renderD128/device/hwmon/*`

-->

`ls: cannot access '/sys/class/drm/renderD128/device/hwmon/*': No such file or directory`

Something else I can do?

**Comment by 17314642** [comment]
ahahah, yeah..., do you have hwmon at all?

`ls /sys/class/drm/renderD128/device/

**Comment by PerAstraAdDeum** [comment]
Nope. 

And if `ls /sys/class/drm/*/device/hwmon/*` works as I suspect, none of the other drm entries has hwmon either.

... what does that mean? No metrics for me? :sob:

**Comment by 17314642** [comment]
It means no power usage for you, probably because it's a laptop

**Comment by 17314642** [comment]
No, that's all. Thank you once again.

**Comment by PerAstraAdDeum** [comment]
Sure, glad I could help! I'll be waiting for the `xe` driver support to land in master and then report back.

**Comment by nokia8801** [comment]
I just compiled mangohud-git after the latest commits ae4c411a4cff536081ff0ccafa5841401ceba5d5 and 6c49103ed0d927c2028da2a86799053f82a60bb7 but unfortunately, it is still broken with Arc A750 using Xe driver. Does not show usage percentage or temperature and it shows over -100000 W power usage and it doesn't stop increasing, always climbing up. No VRAM either, though that could be related to Wine. 

![image](https://github.com/user-attachments/assets/e89025ea-4118-46ca-b6f7-25184bf41d90)

Most efficient card on the planet, supplies infinite power to the world :smile:

**Comment by PerAstraAdDeum** [comment]
> @nokia8801 can I contact you on discord for debugging purposes?

I'm not Nokia and I'm not on discord, but if you need me to test something (Arc iGPU with xe driver, Arch Linux) for the next release, let me know.

**Comment by 17314642** [comment]
@PerAstraAdDeum do you have same issues as nokia? if yes, I can use your help too.

**Comment by nokia8801** [comment]
Of course I can help mate, but I'm also not on Discord. I do have Matrix, I use the Fractal client.

**Comment by PerAstraAdDeum** [comment]
+1 for Matrix, I'm there too.

And I don't have the newest version yet, according to `yay` `mangohud-git` is out-of-date. Should I compile manually?

**Comment by nokia8801** [comment]
mangohud-git is out of date because some newbie user flagged it as such. It is a git package so it always builds the latest version. Just go ahead and compile/install it.

**Comment by 17314642** [comment]
okay, I'll try to use matrix, don't think I used it before. Can either of you create a matrix group so we could coordinate there?

@PerAstraAdDeum you would need to compile it manually, yeah. I don't use arch linux and I thought that yay downloads latest git versions. Apparently it's also manually updated. Last update for git version was on 19th of june, which is quite old for a git version.

**Comment by PerAstraAdDeum** [comment]
Sure thing, but sadly it fails:
![image](https://github.com/user-attachments/assets/5f2fb23c-6b30-4eca-bca5-31711f8b8be1)

Full meson-log.txt:

Build started at 2024-12-03T13:14:57.390071
Main binary: /usr/bin/python
Build Options: -Db_pie=true -Dpython.bytecompile=1 -Dmangoapp=true -Dmangohudctl=true -Dmangoapp_layer=true -Dprefix=/usr -Dlibexecdir=lib -Dsbindir=bin -Dauto_features=enabled -Dbuildtype=plain -Dwrap_mode=default
Python system: Linux
The Meson build system
Version: 1.6.0
Source dir: /home/ian/.cache/yay/mangohud-git/src/MangoHud
Build dir: /home/ian/.cache/yay/mangohud-git/src/build
Build type: native build

MangoHud/meson.build:1:0: ERROR: Unknown options: "mangoapp_layer"

**Comment by 17314642** [comment]
I don't follow, you mean like create an alternative to discord server but on matrix?

**Comment by nokia8801** [comment]
Here is the room link. You should download a Matrix client and also create a matrix account.

[MangoHud | Intel Xe Driver](https://matrix.to/#/!FyaOaVGESGSFrZzExM:matrix.org?via=matrix.org)

**Comment by Lassebq** [comment]
Compiled latest git on my igpu-only laptop and I can see usage precent but not frequency
`cat /sys/class/drm/card1/gt/gt0/rps_cur_freq_mhz`
I can query it from sysfs like this. GPU is Intel UHD 620

**Comment by 17314642** [comment]
@Lassebq woah, i didn't know you could get frequency via sysfs. What's your cpu?

Anyway, currently mangohud doesn't know how to do that, but I can try and add that if you could help me test it.

**Comment by Lassebq** [comment]
Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz

**Comment by 17314642** [comment]
Woah again, I didn't even know i915 had that functionality. I'll add frequency support in a few days. Note that this will only work for i915 driver and xe, because xe doesn't have `gt` directory at least on my pc with Arc A770.

**Comment by 17314642** [comment]
@Lassebq https://github.com/flightlessmango/MangoHud/pull/1499

**Comment by Lassebq** [comment]
Clock speed works with that PR, however it seems a bit different from the value reported in intel_gpu_top?
The value from sysfs only goes as low as 300Mhz while intel_gpu_top shows values below 100Mhz. I'm not sure why that is. It also hovers around 1000-1100Mhz at full load, while sysfs value is a constant 1150Mhz

**Comment by 17314642** [comment]
@Lassebq intel_gpu_top gathers statistics via debugfs, not sysfs, maybe there are some different values. Also polling period might play a role. Mangohud checks every 500ms, while intel_gpu_top does it every 2 seconds, maybe that can affect the output.


I'll compare intel_gpu_top and mangohud and check if something can be done about this.


If you could, can you join matrix room for intel mangohud discussion? It will be easier to chat there instead of cluttering github.

Discord is also fine.

**Comment by 17314642** [comment]
@Lassebq

I indeed see that intel_gpu_top and mangohud are showing different values. This is because of different methods of gathering gpu frequency.

1. intel_gpu_top does this by using perf events which require root permissions or by setting "sysctl kernel.perf_event_paranoid=0"
2. mangohud does this by reading "/sys/bus/pci/devices/0000:03:00.0/drm/card1/gt_act_freq_mhz" which only shows frequency in increments of 50mhz

I truly don't know which way of gathering is the correct one, but considering that perf_events by default require root, second method seems more natural and I'll keep it as is.

![image](https://github.com/user-attachments/assets/80a91e25-6ac5-4f3c-a70e-0a073d2454ba)
