### ISSUE TITLE
can't compile version v0.6.9-1

### ISSUE THREAD

**Issue by CytronBR** [flightlessmango/MangoHud#1083]
I was trying to compile the version v0.6.9-1 on my fedora system and I'm getting the following error:

> [61/100] Linking target src/libMangoHud.so
> FAILED: src/libMangoHud.so 
c++  -o src/libMangoHud.so src/libMangoHud.a.p/vulkan.cpp.o src/libMangoHud.a.p/mesa_util_os_socket.c.o src/libMangoHud.a.p/mesa_util_os_time.c.o src/libMangoHud.a.p/hud_elements.cpp.o src/libMangoHud.a.p/overlay.cpp.o src/libMangoHud.a.p/overlay_params.cpp.o src/libMangoHud.a.p/font.cpp.o src/libMangoHud.a.p/keybinds.cpp.o src/libMangoHud.a.p/font_unispace.c.o src/libMangoHud.a.p/logging.cpp.o src/libMangoHud.a.p/config.cpp.o src/libMangoHud.a.p/gpu.cpp.o src/libMangoHud.a.p/blacklist.cpp.o src/libMangoHud.a.p/file_utils.cpp.o src/libMangoHud.a.p/intel.cpp.o src/libMangoHud.a.p/cpu.cpp.o src/libMangoHud.a.p/memory.cpp.o src/libMangoHud.a.p/iostats.cpp.o src/libMangoHud.a.p/notify.cpp.o src/libMangoHud.a.p/elfhacks.cpp.o src/libMangoHud.a.p/real_dlsym.cpp.o src/libMangoHud.a.p/pci_ids.cpp.o src/libMangoHud.a.p/battery.cpp.o src/libMangoHud.a.p/control.cpp.o src/libMangoHud.a.p/gamepad.cpp.o src/libMangoHud.a.p/amdgpu.cpp.o src/libMangoHud.a.p/nvml.cpp.o src/libMangoHud.a.p/loaders_loader_nvml.cpp.o src/libMangoHud.a.p/loaders_loader_nvctrl.cpp.o src/libMangoHud.a.p/nvctrl.cpp.o src/libMangoHud.a.p/loaders_loader_x11.cpp.o src/libMangoHud.a.p/shared_x11.cpp.o src/libMangoHud.a.p/dbus.cpp.o src/libMangoHud.a.p/loaders_loader_dbus.cpp.o src/libMangoHud.a.p/meson-generated_.._.._vk_enum_to_str.c.o -Wl,--as-needed -Wl,--no-undefined -Wl,-O1 -shared -fPIC -Wl,--start-group -Wl,-soname,libMangoHud.so src/libMangoHud.a subprojects/imgui-1.81/libimgui.a subprojects/spdlog-1.8.5/src/libspdlog.a -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--exclude-libs,ALL -lGL -Wl,--end-group -static-libstdc++ -Wl,--version-script,/home/cytronbr/Downloads/MangoHud/src/mangohud.version -pthread
> /usr/bin/ld: unable to find -lstdc++: No such file or directory
> collect2: error: ld returned 1 exit status

I tried to compile using these commands:

> git clone --recurse-submodules https://github.com/flightlessmango/MangoHud.git
> cd MangoHud
> ./build.sh build

All dependencies prompted by the build.sh script were installed.

The previous version v0.6.9 I was able to successfully compile and install on my machine using those same commands.

System: Fedora Linux 38 Workstation Edition (x86-64)
Kernel: 6.4.4-200.fc38.x86_64
Processor: Intel Core i5-3337U
GPU: GeForce GT 730M

Full build log:

> Command: build 
> Checking dependencies for "fedora"
> The Meson build system
> Version: 1.0.1
> Source dir: /home/cytronbr/Downloads/MangoHud
> Build dir: /home/cytronbr/Downloads/MangoHud/build/meson64
> Build type: native build
> Project name: MangoHud
> Project version: v0.6.9
> C compiler for the host machine: cc (gcc 13.1.1 "cc (GCC) 13.1.1 20230614 (Red Hat 13.1.1-4)")
> C linker for the host machine: cc ld.bfd 2.39-9
> C++ compiler for the host machine: c++ (gcc 13.1.1 "c++ (GCC) 13.1.1 20230614 (Red Hat 13.1.1-4)")
> C++ linker for the host machine: c++ ld.bfd 2.39-9
> Host machine cpu family: x86_64
> Host machine cpu: x86_64
> Program python3 (mako) found: YES (/usr/bin/python3) modules: mako
> Checking if "GCC atomic builtins" compiles: YES 
> Checking if "Supports timespec_get" compiles: YES 
> Checking for function "bswap32" : YES 
> Checking for function "bswap64" : YES 
> Checking for function "clz" : YES 
> Checking for function "clzll" : YES 
> Checking for function "ctz" : YES 
> Checking for function "expect" : YES 
> Checking for function "ffs" : YES 
> Checking for function "ffsll" : YES 
> Checking for function "popcount" : YES 
> Checking for function "popcountll" : YES 
> Checking for function "unreachable" : YES 
> Found pkg-config: /usr/bin/pkg-config (1.8.0)
> Run-time dependency x11 found: YES 1.8.6
> Dependency wayland-client skipped: feature with_wayland disabled
> Run-time dependency dbus-1 found: YES 1.14.8
> Run-time dependency threads found: YES
> Compiler for C supports arguments -Werror=implicit-function-declaration: YES 
> Compiler for C supports arguments -Werror=missing-declarations: YES 
> Compiler for C supports arguments -Werror=missing-prototypes: YES 
> Compiler for C supports arguments -Werror=return-type: YES 
> Compiler for C supports arguments -Werror=incompatible-pointer-types: YES 
> Compiler for C supports arguments -Wno-unused-parameter: YES 
> Compiler for C supports arguments -Qunused-arguments: NO 
> Compiler for C supports arguments -fno-math-errno: YES 
> Compiler for C supports arguments -fno-trapping-math: YES 
> Compiler for C supports arguments -Wno-missing-field-initializers: YES 
> Compiler for C++ supports arguments -Werror=missing-declarations: YES 
> Compiler for C++ supports arguments -Werror=return-type: YES 
> Compiler for C++ supports arguments -Wno-unused-parameter: YES 
> Compiler for C++ supports arguments -Qunused-arguments: NO 
> Compiler for C++ supports arguments -fno-math-errno: YES 
> Compiler for C++ supports arguments -fno-trapping-math: YES 
> Compiler for C++ supports arguments -Wno-non-virtual-dtor: YES 
> Compiler for C++ supports arguments -Wno-missing-field-initializers: YES 
> Checking for function "dlopen" : YES 
> Checking for function "clock_gettime" : YES 
> Downloading vulkan-headers source from https://github.com/KhronosGroup/Vulkan-Headers/archive/v1.2.158.tar.gz
> Downloading file of unknown size.
> Downloading vulkan-headers patch from https://wrapdb.mesonbuild.com/v2/vulkan-headers_1.2.158-2/get_patch
> Download size: 1107
> Downloading: ..........
> 
> Executing subproject vulkan-headers 
> 
> vulkan-headers| Project name: vulkan-headers
> vulkan-headers| Project version: 1.2.158
> vulkan-headers| C compiler for the host machine: cc (gcc 13.1.1 "cc (GCC) 13.1.1 20230614 (Red Hat 13.1.1-4)")
> vulkan-headers| C linker for the host machine: cc ld.bfd 2.39-9
> vulkan-headers| Build targets in project: 1
> vulkan-headers| Subproject vulkan-headers finished.
> 
> Checking for size of "void*" : 8
> Downloading imgui source from https://github.com/ocornut/imgui/archive/v1.81.tar.gz
> Downloading file of unknown size.
> Downloading imgui patch from https://wrapdb.mesonbuild.com/v2/imgui_1.81-1/get_patch
> Download size: 1850
> Downloading: ..........
> 
> Executing subproject imgui 
> 
> imgui| Project name: imgui
> imgui| Project version: 1.81
> imgui| C++ compiler for the host machine: c++ (gcc 13.1.1 "c++ (GCC) 13.1.1 20230614 (Red Hat 13.1.1-4)")
> imgui| C++ linker for the host machine: c++ ld.bfd 2.39-9
> imgui| Library d3d9 skipped: feature dx9 disabled
> imgui| Library d3d10 skipped: feature dx10 disabled
> imgui| Library d3d11 skipped: feature dx11 disabled
> imgui| Library d3d12 skipped: feature dx12 disabled
> imgui| Library metal skipped: feature metal disabled
> imgui| Dependency glew skipped: feature opengl disabled
> imgui| Dependency vulkan skipped: feature vulkan disabled
> imgui| Dependency glfw3 skipped: feature glfw disabled
> imgui| Dependency sdl2 skipped: feature sdl2 disabled
> imgui| Dependency allegro5 skipped: feature allegro5 disabled
> imgui| Library marmalade skipped: feature marmalade disabled
> imgui| Build targets in project: 3
> imgui| Subproject imgui finished.
> 
> Library spdlog skipped: feature use_system_spdlog disabled
> Downloading spdlog source from https://github.com/gabime/spdlog/archive/v1.8.5.tar.gz
> Download size: 321229
> Downloading: ..........
> Downloading spdlog patch from https://wrapdb.mesonbuild.com/v2/spdlog_1.8.5-1/get_patch
> Download size: 2211
> Downloading: ..........
> 
> Executing subproject spdlog 
> 
> spdlog| Project name: spdlog
> spdlog| Project version: 1.8.5
> spdlog| C++ compiler for the host machine: c++ (gcc 13.1.1 "c++ (GCC) 13.1.1 20230614 (Red Hat 13.1.1-4)")
> spdlog| C++ linker for the host machine: c++ ld.bfd 2.39-9
> spdlog| Dependency threads found: YES unknown (cached)
> spdlog| Build targets in project: 4
> spdlog| Subproject spdlog finished.
> 
> Did not find CMake 'cmake'
> Found CMake: NO
> Run-time dependency nlohmann_json found: NO (tried pkgconfig and cmake)
> Looking for a fallback subproject for the dependency nlohmann_json
> Downloading nlohmann_json source from https://github.com/nlohmann/json/releases/download/v3.10.5/include.zip
> Download size: 260679
> Downloading: ..........
> 
> Executing subproject nlohmann_json 
> 
> nlohmann_json| Project name: nlohmann_json
> nlohmann_json| Project version: 3.10.5
> nlohmann_json| C++ compiler for the host machine: c++ (gcc 13.1.1 "c++ (GCC) 13.1.1 20230614 (Red Hat 13.1.1-4)")
> nlohmann_json| C++ linker for the host machine: c++ ld.bfd 2.39-9
> nlohmann_json| Build targets in project: 4
> nlohmann_json| Subproject nlohmann_json finished.
> 
> Dependency nlohmann_json from subproject subprojects/nlohmann_json-3.10.5 found: YES 3.10.5
> Program glslangValidator found: YES (/usr/bin/glslangValidator)
> WARNING: You should add the boolean check kwarg to the run_command call.
>          It currently defaults to false,
>          but it will default to true in future releases of meson.
>          See also: https://github.com/mesonbuild/meson/issues/9300
> Has header "NVCtrl/NVCtrl.h" : YES 
> Compiler for C supports link arguments -Wl,-Bsymbolic-functions: YES 
> Compiler for C supports link arguments -Wl,-z,relro: YES 
> Compiler for C supports link arguments -Wl,--exclude-libs,ALL: YES 
> Compiler for C supports link arguments -lGL: YES 
> Compiler for C supports link arguments -static-libstdc++: YES 
> WARNING: extract_all_objects called without setting recursive
> keyword argument. Meson currently defaults to
> non-recursive to maintain backward compatibility but
> the default will be changed in the future.
> 
> Configuring MangoHud.x86_64.json using configuration
> Configuring mangohud using configuration
> Program appstreamcli found: YES (/usr/bin/appstreamcli)
> Build targets in project: 10
> 
> MangoHud v0.6.9
> 
>   Subprojects
>     imgui                 : YES
>     nlohmann_json         : YES
>     spdlog                : YES
>     vulkan-headers        : YES
> 
>   User defined options
>     libdir                : lib/mangohud/lib64
>     prefix                : /usr
>     werror                : true
>     append_libdir_mangohud: false
> 
> Found ninja-1.11.1 at /usr/bin/ninja
> WARNING: Running the setup command as `meson [options]` instead of `meson setup [options]` is ambiguous and deprecated.
> The Meson build system
> Version: 1.0.1
> Source dir: /home/cytronbr/Downloads/MangoHud
> Build dir: /home/cytronbr/Downloads/MangoHud/build/meson32
> Build type: native build
> Project name: MangoHud
> Project version: v0.6.9
> C compiler for the host machine: gcc -m32 (gcc 13.1.1 "gcc (GCC) 13.1.1 20230614 (Red Hat 13.1.1-4)")
> C linker for the host machine: gcc -m32 ld.bfd 2.39-9
> C++ compiler for the host machine: g++ -m32 (gcc 13.1.1 "g++ (GCC) 13.1.1 20230614 (Red Hat 13.1.1-4)")
> C++ linker for the host machine: g++ -m32 ld.bfd 2.39-9
> Host machine cpu family: x86
> Host machine cpu: i686
> Program python3 (mako) found: YES (/usr/bin/python3) modules: mako
> Checking if "GCC atomic builtins" compiles: YES 
> Checking if "Supports timespec_get" compiles: YES 
> Checking for function "bswap32" : YES 
> Checking for function "bswap64" : YES 
> Checking for function "clz" : YES 
> Checking for function "clzll" : YES 
> Checking for function "ctz" : YES 
> Checking for function "expect" : YES 
> Checking for function "ffs" : YES 
> Checking for function "ffsll" : YES 
> Checking for function "popcount" : YES 
> Checking for function "popcountll" : YES 
> Checking for function "unreachable" : YES 
> Found pkg-config: /usr/bin/pkg-config (1.8.0)
> Run-time dependency x11 found: YES 1.8.6
> Dependency wayland-client skipped: feature with_wayland disabled
> Run-time dependency dbus-1 found: YES 1.14.8
> Run-time dependency threads found: YES
> Compiler for C supports arguments -Werror=implicit-function-declaration: YES 
> Compiler for C supports arguments -Werror=missing-declarations: YES 
> Compiler for C supports arguments -Werror=missing-prototypes: YES 
> Compiler for C supports arguments -Werror=return-type: YES 
> Compiler for C supports arguments -Werror=incompatible-pointer-types: YES 
> Compiler for C supports arguments -Wno-unused-parameter: YES 
> Compiler for C supports arguments -Qunused-arguments: NO 
> Compiler for C supports arguments -fno-math-errno: YES 
> Compiler for C supports arguments -fno-trapping-math: YES 
> Compiler for C supports arguments -Wno-missing-field-initializers: YES 
> Compiler for C++ supports arguments -Werror=missing-declarations: YES 
> Compiler for C++ supports arguments -Werror=return-type: YES 
> Compiler for C++ supports arguments -Wno-unused-parameter: YES 
> Compiler for C++ supports arguments -Qunused-arguments: NO 
> Compiler for C++ supports arguments -fno-math-errno: YES 
> Compiler for C++ supports arguments -fno-trapping-math: YES 
> Compiler for C++ supports arguments -Wno-non-virtual-dtor: YES 
> Compiler for C++ supports arguments -Wno-missing-field-initializers: YES 
> Checking for function "dlopen" : YES 
> Checking for function "clock_gettime" : YES 
> 
> Executing subproject vulkan-headers 
> 
> vulkan-headers| Project name: vulkan-headers
> vulkan-headers| Project version: 1.2.158
> vulkan-headers| C compiler for the host machine: gcc -m32 (gcc 13.1.1 "gcc (GCC) 13.1.1 20230614 (Red Hat 13.1.1-4)")
> vulkan-headers| C linker for the host machine: gcc -m32 ld.bfd 2.39-9
> vulkan-headers| Build targets in project: 1
> vulkan-headers| Subproject vulkan-headers finished.
> 
> Checking for size of "void*" : 4
> 
> Executing subproject imgui 
> 
> imgui| Project name: imgui
> imgui| Project version: 1.81
> imgui| C++ compiler for the host machine: g++ -m32 (gcc 13.1.1 "g++ (GCC) 13.1.1 20230614 (Red Hat 13.1.1-4)")
> imgui| C++ linker for the host machine: g++ -m32 ld.bfd 2.39-9
> imgui| Library d3d9 skipped: feature dx9 disabled
> imgui| Library d3d10 skipped: feature dx10 disabled
> imgui| Library d3d11 skipped: feature dx11 disabled
> imgui| Library d3d12 skipped: feature dx12 disabled
> imgui| Library metal skipped: feature metal disabled
> imgui| Dependency glew skipped: feature opengl disabled
> imgui| Dependency vulkan skipped: feature vulkan disabled
> imgui| Dependency glfw3 skipped: feature glfw disabled
> imgui| Dependency sdl2 skipped: feature sdl2 disabled
> imgui| Dependency allegro5 skipped: feature allegro5 disabled
> imgui| Library marmalade skipped: feature marmalade disabled
> imgui| Build targets in project: 3
> imgui| Subproject imgui finished.
> 
> Library spdlog skipped: feature use_system_spdlog disabled
> 
> Executing subproject spdlog 
> 
> spdlog| Project name: spdlog
> spdlog| Project version: 1.8.5
> spdlog| C++ compiler for the host machine: g++ -m32 (gcc 13.1.1 "g++ (GCC) 13.1.1 20230614 (Red Hat 13.1.1-4)")
> spdlog| C++ linker for the host machine: g++ -m32 ld.bfd 2.39-9
> spdlog| Dependency threads found: YES unknown (cached)
> spdlog| Build targets in project: 4
> spdlog| Subproject spdlog finished.
> 
> Did not find CMake 'cmake'
> Found CMake: NO
> Run-time dependency nlohmann_json found: NO (tried pkgconfig and cmake)
> Looking for a fallback subproject for the dependency nlohmann_json
> 
> Executing subproject nlohmann_json 
> 
> nlohmann_json| Project name: nlohmann_json
> nlohmann_json| Project version: 3.10.5
> nlohmann_json| C++ compiler for the host machine: g++ -m32 (gcc 13.1.1 "g++ (GCC) 13.1.1 20230614 (Red Hat 13.1.1-4)")
> nlohmann_json| C++ linker for the host machine: g++ -m32 ld.bfd 2.39-9
> nlohmann_json| Build targets in project: 4
> nlohmann_json| Subproject nlohmann_json finished.
> 
> Dependency nlohmann_json from subproject subprojects/nlohmann_json-3.10.5 found: YES 3.10.5
> Program glslangValidator found: YES (/usr/bin/glslangValidator)
> WARNING: You should add the boolean check kwarg to the run_command call.
>          It currently defaults to false,
>          but it will default to true in future releases of meson.
>          See also: https://github.com/mesonbuild/meson/issues/9300
> Has header "NVCtrl/NVCtrl.h" : YES 
> Compiler for C supports link arguments -Wl,-Bsymbolic-functions: YES 
> Compiler for C supports link arguments -Wl,-z,relro: YES 
> Compiler for C supports link arguments -Wl,--exclude-libs,ALL: YES 
> Compiler for C supports link arguments -lGL: NO 
> Compiler for C supports link arguments -static-libstdc++: YES 
> WARNING: extract_all_objects called without setting recursive
> keyword argument. Meson currently defaults to
> non-recursive to maintain backward compatibility but
> the default will be changed in the future.
> 
> Configuring MangoHud.x86.json using configuration
> Configuring mangohud using configuration
> Program appstreamcli found: YES (/usr/bin/appstreamcli)
> Build targets in project: 10
> 
> MangoHud v0.6.9
> 
>   Subprojects
>     imgui                 : YES
>     nlohmann_json         : YES
>     spdlog                : YES
>     vulkan-headers        : YES
> 
>   User defined options
>     libdir                : lib/mangohud/lib32
>     prefix                : /usr
>     werror                : true
>     append_libdir_mangohud: false
> 
> Found ninja-1.11.1 at /usr/bin/ninja
> WARNING: Running the setup command as `meson [options]` instead of `meson setup [options]` is ambiguous and deprecated.
> ninja: Entering directory `build/meson64'
> [11/100] Generating src/overlay.frag.spv.h with a custom command
> ../../src/overlay.frag
> [12/100] Generating src/overlay.vert.spv.h with a custom command
> ../../src/overlay.vert
> [61/100] Linking target src/libMangoHud.so
> FAILED: src/libMangoHud.so 
> c++  -o src/libMangoHud.so src/libMangoHud.a.p/vulkan.cpp.o src/libMangoHud.a.p/mesa_util_os_socket.c.o src/libMangoHud.a.p/mesa_util_os_time.c.o src/libMangoHud.a.p/hud_elements.cpp.o src/libMangoHud.a.p/overlay.cpp.o src/libMangoHud.a.p/overlay_params.cpp.o src/libMangoHud.a.p/font.cpp.o src/libMangoHud.a.p/keybinds.cpp.o src/libMangoHud.a.p/font_unispace.c.o src/libMangoHud.a.p/logging.cpp.o src/libMangoHud.a.p/config.cpp.o src/libMangoHud.a.p/gpu.cpp.o src/libMangoHud.a.p/blacklist.cpp.o src/libMangoHud.a.p/file_utils.cpp.o src/libMangoHud.a.p/intel.cpp.o src/libMangoHud.a.p/cpu.cpp.o src/libMangoHud.a.p/memory.cpp.o src/libMangoHud.a.p/iostats.cpp.o src/libMangoHud.a.p/notify.cpp.o src/libMangoHud.a.p/elfhacks.cpp.o src/libMangoHud.a.p/real_dlsym.cpp.o src/libMangoHud.a.p/pci_ids.cpp.o src/libMangoHud.a.p/battery.cpp.o src/libMangoHud.a.p/control.cpp.o src/libMangoHud.a.p/gamepad.cpp.o src/libMangoHud.a.p/amdgpu.cpp.o src/libMangoHud.a.p/nvml.cpp.o src/libMangoHud.a.p/loaders_loader_nvml.cpp.o src/libMangoHud.a.p/loaders_loader_nvctrl.cpp.o src/libMangoHud.a.p/nvctrl.cpp.o src/libMangoHud.a.p/loaders_loader_x11.cpp.o src/libMangoHud.a.p/shared_x11.cpp.o src/libMangoHud.a.p/dbus.cpp.o src/libMangoHud.a.p/loaders_loader_dbus.cpp.o src/libMangoHud.a.p/meson-generated_.._.._vk_enum_to_str.c.o -Wl,--as-needed -Wl,--no-undefined -Wl,-O1 -shared -fPIC -Wl,--start-group -Wl,-soname,libMangoHud.so src/libMangoHud.a subprojects/imgui-1.81/libimgui.a subprojects/spdlog-1.8.5/src/libspdlog.a -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--exclude-libs,ALL -lGL -Wl,--end-group -static-libstdc++ -Wl,--version-script,/home/cytronbr/Downloads/MangoHud/src/mangohud.version -pthread
> /usr/bin/ld: unable to find -lstdc++: No such file or directory
> collect2: error: ld returned 1 exit status
> [66/100] Compiling C++ object src/libMangoHud_opengl.so.p/overlay_params.cpp.o
> ninja: build stopped: subcommand failed.

**Comment by gort818** [comment]
do you have `libstdc++` installed?

**Comment by CytronBR** [comment]
Yes.

![Captura de tela de 2023-07-26 01-35-08](https://github.com/flightlessmango/MangoHud/assets/32803215/fd22da04-0f27-4ee0-9b67-099cb8987445)

**Comment by gort818** [comment]
does fedora have a separate static package? ` libstdc++-static` ?

**Comment by CytronBR** [comment]
This kind of worked, I installed `libstdc++-static.x86_64` and `libstdc++-static.i686` and I was able to compile and install the latest version.

But now I have another problem, GPU info is not showing anymore: 

![Screenshot from 2023-07-26 02-41-57](https://github.com/flightlessmango/MangoHud/assets/32803215/947e4ffa-17e1-400b-8046-8135236ddc9e)

I tested on glxgears, vkcube and 3 games that use dxvk, same result

This is also happening on the packed release from the fedora repo, witch is why I was trying to compile from source

In the previous v0.6.9 that I've compiled it shows gpu info just fine

![Screenshot from 2023-07-26 02-43-09](https://github.com/flightlessmango/MangoHud/assets/32803215/021732bf-691f-42b1-a9b7-7ed4f24cf4c0)

My gpu is a Nvidia GT 730M, witch I think uses XNVCtrl instead of NVML. I have the packages `libXNVCtrl-devel.x86_64`, `libXNVCtrl.x86_64`, `libXNVCtrl.i686` installed.

**Comment by CytronBR** [comment]
also, when I run either glxgears or vkcube with mangohud, it give this warning on the terminal:

> [2023-07-26 03:18:17.691] [MANGOHUD] [error] [nvctrl.cpp:54] XNVCtrl didn't find the correct display

**Comment by CytronBR** [comment]
Does anyone knows how to fix this?

**Comment by needlesslygrim** [comment]
The problem, according to [this](https://bugs.archlinux.org/task/79212) Arch page is that upstream has reneamed `glslangValidator` to `glslang`. The bug should be fixed soon? For now try making the symlink yourself maybe.

**Comment by flightlessmango** [comment]
@needlesslygrim don't think that's related to this issue, but I pushed a commit for that

**Comment by needlesslygrim** [comment]
Yeah, I only realised once I'd posted the comment lol. Thanks for fixing that so quickly though!

**Comment by needlesslygrim** [comment]
Sorry @CytronBR, I myself cannot help with the issue you seem to be having now since I'm not familiar with MangoHud's internals.

**Comment by flightlessmango** [comment]
The initial issue is resolved, open a new issues of other issues
