### ISSUE TITLE
fsr option doesn't work in gamescope

### ISSUE THREAD

**Issue by rtentser** [flightlessmango/MangoHud#1087]
**Describe the bug**
fsr option uncommented in config file, but still doesn't work

**List relevant hardware/software information**
- Linux Distribution: EndeavourOS
- MangoHud version: v0.6.9-1-114-g7189b75
- GPU: Sapphire RX 6750 XT

**To Reproduce**
Run gamescope with fsr. No fsr info in overlay

**Expected behavior**
FSR info in overlay

**Screenshots**
![FSR](https://github.com/flightlessmango/MangoHud/assets/34958119/c308f931-e1f2-4a44-8150-b47d715283e0)

**Additional context**
Assassin's Creed Liberation HD
```gamescope -w 3200 -h 1800 -W 3840 -H 2160 -F fsr -f -- mangohud gamemoderun wine a*.exe```

**Comment by flightlessmango** [comment]
It only works with mangoapp as mangoapp has direct communication with gamescope

**Comment by rtentser** [comment]
Oh. Sorry. Probably should be mentioned in option description.
