### ISSUE TITLE
MANGOHUD_CONFIG is no longer "space bar" friendly

### ISSUE THREAD

**Issue by mhmarf** [flightlessmango/MangoHud#1088]
first thank you for this amazing software you have created.

**Describe the bug**
When typing MANGOHUD_CONFIG=x,y,z as Env Variable inside lutris... if you place a space before any element like this: MANGOHUD_CONFIG=x, y, z (notice spacebar before y and z) that element will not be recognized with this error:
`[MANGOHUD] [error] [overlay_params.cpp:576] Unknown option ' gpu_power' `(notice space before gpu_power)
it wasn't like this before was it?? (I'm 99.99% sure it was space-bar friendly)

**List relevant hardware/software information**
- Linux Distribution
  Linux Mint 21.1 Vera
- MangoHud version
  0.6.9-1
- GPU
  6900 xt

**To Reproduce**
1. Go to Lutris
2. Click on Configure -> System Options
3. Scroll down to Environment Variable
4. Add MANGOHUD_CONFIG =gpu_power, gpu_temp, cpu_temp
5. Only gpu_power will be recognized because other two have a space before them.

**Comment by flightlessmango** [comment]
No you shouldn't be able to use spaces in environment variable values. You could by escaping the space but I assume that's not what you want to do

**Comment by jansol** [comment]
I suppose it wouldn't hurt to trim whitespace from the start and end of the individual config items after splitting the string by commas (or by newlines, in the case of the config file)?

Unnecessary whitespace in a text file happens easily, and trimming it is fairly minimal work that should be trivially shareable between config file and environment variable code paths.

**Comment by flightlessmango** [comment]
Can't repro this anymore, did something change to fix it?

**Comment by mhmarf** [comment]
On Lutris 0.5.12 which I use it sitll is there (though now I'm on Nobara Linux)...
[2023-11-09 20:54:26.527] [MANGOHUD] [error] [overlay_params.cpp:586] Unknown option ' gpu_power'
[2023-11-09 20:54:26.527] [MANGOHUD] [error] [overlay_params.cpp:586] Unknown option ' gpu_temp'

**Comment by flightlessmango** [comment]
should be resolved in dcb87415811919830c20d4c6eab8b44475c7f2a4
