### ISSUE TITLE
code bug: gpu power usage code in cpu power section

### ISSUE THREAD

**Issue by siroccal** [flightlessmango/MangoHud#1089]
https://github.com/flightlessmango/MangoHud/blob/7189b75efe24f5ebbcf34102e505dde34c0787bb/src/hud_elements.cpp#L338

What is `gpu_info.powerUsage` doing in the section of `cpu_power`? Shouldn't this be `cpuStats.GetCPUDataTotal().power` like the lines below it?

**Comment by flightlessmango** [comment]
closing as #1090 is merged
