### ISSUE TITLE
Mangohud Overlay Layout distored between 0.6.8 and 0.6.9

### ISSUE THREAD

**Issue by linuxazo** [flightlessmango/MangoHud#1094]
**Describe the bug**

**List relevant hardware/software information**
- Linux Distribution
- MangoHud version:  0.6.8 and 0.6.9
- GPU: Radeon R680M & Radeon RX 6700M

**To Reproduce**
1. Go to 'Launch MangoHud with existing settings.'
2. Click on 'n/a'
3. Scroll down to 'n/a'
4. See error:  Observer that lines  "Distro:", "Version:", "Kernel:" and "Session:" move their outputs to a new line which results in an ugly looking output.

**Expected behavior**
The output of aforementioned lines should be in the same line as the lines themselves.

**Screenshots**
Correct layout shown with MangoHud 0.6.8:
<img width="705" alt="Mangohud_0 6 8" src="https://github.com/flightlessmango/MangoHud/assets/65850835/16926441-4cfa-4f26-b136-7041ce2a4ccc">

Disturbed layout shown with MangoHud 0.6.9:
<img width="705" alt="Mangohud_0 6 9" src="https://github.com/flightlessmango/MangoHud/assets/65850835/d67717e0-33c1-4c93-9ea8-b70a6ca06886">

**Additional context**
Thank You for all your work.  Hopefully this could be rectified in future version of MangoHud.

Kind regards

**Comment by flightlessmango** [comment]
Can you post your mangohud config?

**Comment by linuxazo** [comment]
Hi!  Sure thing.  Thank You so much for quick reply.
[MangoHud.conf.txt](https://github.com/flightlessmango/MangoHud/files/12372844/MangoHud.conf.txt)

**Comment by flightlessmango** [comment]
Should be fixed here 53ee2275e4d2997f6bda8f263efcbdd8bd70441b

**Comment by linuxazo** [comment]
> Should be fixed here [53ee227](https://github.com/flightlessmango/MangoHud/commit/53ee2275e4d2997f6bda8f263efcbdd8bd70441b)

@flightlessmango Thank You for replying.  Unfortunately, Resolution field in 0.7.0 is still ugly like in 0.6.9.
Hopefully, it can be restored to 0.6.8 look as shown in above images.

**Comment by flightlessmango** [comment]
reopen if still an issue in 0.7.2
