### ISSUE TITLE
Linking issue with inject_glx.cpp and gl_hud.cpp on Alpine Linux

### ISSUE THREAD

**Issue by CuriouslyCurious** [flightlessmango/MangoHud#1096]
**Describe the bug**
Unable to compile MangoHud as it fails to link `libMangoHud_opengl.so`.

**List relevant hardware/software**
- Distro: Alpine Linux v3.18
- MangoHud (41f923b0b2be07f035df221d01625e11f1305fde, master)
- GPU: Intel® HD Graphics 4000

**To Reproduce**
```sh
$ meson setup build -Dwith_wayland=enabled -Dwith_x11=disabled -Dwith_dbus=disabled -Dwith_xnvctrl=disabled -D
use_system_spdlog=enabled -Dwith_nvml=enabled
$ ninja -C build
```

Results in:
```sh
ninja: job failed: clang++  -o src/libMangoHud_opengl.so src/libMangoHud_opengl.so.p/gl_glad.c.o src/libMangoHud_opengl.so.p/gl_gl_renderer.cpp.o src/libMangoHud_opengl.so.p/gl_gl_hud.cpp.o src/libMangoHud_opengl.so.p/gl_inject_egl.cpp.o src/libMangoHud_opengl.so.p/hud_elements.cpp.o src/libMangoHud_opengl.so.p/overlay.cpp.o src/libMangoHud_opengl.so.p/overlay_params.cpp.o src/libMangoHud_opengl.so.p/font.cpp.o src/libMangoHud_opengl.so.p/keybinds.cpp.o src/libMangoHud_opengl.so.p/font_unispace.c.o src/libMangoHud_opengl.so.p/logging.cpp.o src/libMangoHud_opengl.so.p/config.cpp.o src/libMangoHud_opengl.so.p/gpu.cpp.o src/libMangoHud_opengl.so.p/blacklist.cpp.o src/libMangoHud_opengl.so.p/file_utils.cpp.o src/libMangoHud_opengl.so.p/intel.cpp.o src/libMangoHud_opengl.so.p/cpu.cpp.o src/libMangoHud_opengl.so.p/memory.cpp.o src/libMangoHud_opengl.so.p/iostats.cpp.o src/libMangoHud_opengl.so.p/notify.cpp.o src/libMangoHud_opengl.so.p/elfhacks.cpp.o src/libMangoHud_opengl.so.p/real_dlsym.cpp.o src/libMangoHud_opengl.so.p/pci_ids.cpp.o src/libMangoHud_opengl.so.p/battery.cpp.o src/libMangoHud_opengl.so.p/control.cpp.o src/libMangoHud_opengl.so.p/gamepad.cpp.o src/libMangoHud_opengl.so.p/amdgpu.cpp.o src/libMangoHud_opengl.so.p/nvml.cpp.o src/libMangoHud_opengl.so.p/loaders_loader_nvml.cpp.o src/libMangoHud_opengl.so.p/mesa_util_os_socket.c.o src/libMangoHud_opengl.so.p/mesa_util_os_time.c.o -Wl,--as-needed -Wl,--no-undefined -Wl,-O1 -shared -fPIC -Wl,--start-group -Wl,-soname,libMangoHud_opengl.so subprojects/imgui-1.81/libimgui.a -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--exclude-libs,ALL -lGL -static-libstdc++ -Wl,--version-script,/home/curious/build/MangoHud/src/mangohud.version /usr/lib/libwayland-client.so /usr/lib/libspdlog.so -pthread /usr/lib/libfmt.so -Wl,--end-group
/usr/bin/ld: src/libMangoHud_opengl.so.p/gl_gl_hud.cpp.o: in function `MangoHud::GL::imgui_create(void*, MangoHud::GL::gl_wsi)':
gl_hud.cpp:(.text+0x5fa): undefined reference to `glx_mesa_queryInteger(int, unsigned int*)'
clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: subcommand failed
```

**Additional context**
I am not familiar enough with `meson` and linking in C++ to know exactly why there is a need for `inject_glx.cpp` or why this fails. I can guess it has something to do with my combination of feature flags and musl, but unsure how to investigate further.

**Comment by gort818** [comment]
missing mesa libgl dev library? maybe `mesa-dev` package?

**Comment by gort818** [comment]
Has building worked for you before? worth doing a bisect? Does running ninja with `-v` show anything useful?

**Comment by CxLynx** [comment]
I have the exact same issue on Gentoo LLVM/glibc profile, so I think it's Clang specific and not musl specific. Compiles just fine after switching to GCC. Haven't done a bisect yet but I think I encountered it first about a week ago, building from master.

**Comment by e2dk4r** [comment]
| Key      | Value                                    |
|----------|------------------------------------------|
| Distro   | Gentoo                                   |
| MangoHud | c38132c964adbd858db074e7bb464f07e398f816 |
| GPU      | AMD Radeon RX 6900 XT (RADV NAVI21)      |
| CPU      | AMD Ryzen 9 5950X 16-Core Processor      |
| Arch     | x86_64                                   |
| Kernel   | 6.7.0-rc5                                |
| Wine     | 9.0-rc1                                  |
| WM       | sway (wayland, without xwayland)         |

I encountered same problem on my system.
Steps to produce the bug:
```
git clone --depth 1  --recurse-submodules https://github.com/flightlessmango/MangoHud.git mangohud-git
cd mangohud-git
meson -Dwith_wayland=enabled -Dwith_x11=disabled -Dwith_nvml=disabled -Dwith_xnvctrl=disabled build
ninja -C build
```
Results with:
```
[4/4] Linking target src/libMangoHud_opengl.so
FAILED: src/libMangoHud_opengl.so
...
ld: src/libMangoHud_opengl.so.p/gl_gl_hud.cpp.o: in function `MangoHud::GL::imgui_create(void*, MangoHud::GL::gl_wsi)':
gl_hud.cpp:(.text+0x2bd5): undefined reference to `glx_mesa_queryInteger(int, unsigned int*)'
```
Expected:
```
...
[91/91] Linking target src/libMangoHud_opengl.so
```

[This patch](https://github.com/flightlessmango/MangoHud/files/13642519/fix-only-with-wayland.patch.txt) fixes it.
You can apply with
```
cd mangohud-git
patch -p1 < fix-only-with-wayland.patch.txt
```
It basicly adds below lines to `src/meson.build` after `with_x11` option check
```
if is_unixy
  ...
  if get_option('with_wayland').enabled()
    opengl_files += files(
      'loaders/loader_glx.cpp',
      'gl/inject_glx.cpp',
    )
  endif
```

If you are enabling only wayland option, `loaders/loader_glx.cpp` and `gl/inject_glx.cpp` files  won't be added to `opengl_files`. This causes linking errors.

**Comment by flightlessmango** [comment]
I think this is resolved. reopen otherwise
