### ISSUE TITLE
Average FPS is calculated wrongly when logging performance

### ISSUE THREAD

**Issue by Cippo95** [flightlessmango/MangoHud#1097]
Hi everyone and thanks for your free software!

I was writing a python script to make graphs and data from logging with goverlay, which uses mangohud.

For what I see the average FPS is calculated from the average of FPS in the csv, I understand the idea but I think it is wrong? Feel free to say if it isn't.

You should report the average FPS from the average frametime like this: 1000/avg_frametime.

I'll make an example.

We have 2 frames: the first frame takes 1 ms, the second frame takes 4 ms.

Average ms => (1+4)/2 = 2.5 ms.
If we have this pattern for a second how many frame per seconds? 1000/2.5 = 400 FPS.
These are surely the average frames per second that you see.

How you calculate average FPS in the logs => (1000/1 + 1000/4)/2 = (1000 + 250)/2 = 625 FPS.
This way of calculating overvalues low frame times if you think about it.

Thanks for your time!

**Comment by flightlessmango** [comment]
0815232 does this resolve it?

**Comment by Cippo95** [comment]
I have just compiled and tested it, yes, it seems to solve the issue.

For more information and context, I have tested it with Counter Strike: Global Offensive, with the custom map "FPS Benchmark" from the workshop.

The in-game benchmark reports around 554 FPS average, MangoHud now reports 550 FPS meanwhile on previous runs MangoHud reported around 710 FPS.

Thanks for your time!

**Comment by alou-S** [comment]
@Cippo95 Please do close the issue :>
