### ISSUE TITLE
HUD flickers on Dota 2 (Arch Linux)

### ISSUE THREAD

**Issue by Strykar** [flightlessmango/MangoHud#11]
I load the HUD via Steam launch options: MANGOHUD=1 %command% -vulkan
The HUD loads, but flickers constantly, I do not have the lib32 version installed anymore.

**Comment by telans** [comment]
Does that include the text flickering constantly, or just the frametime graph? I think I know what you're talking about if the latter.

If you could get a video that would be good

**Comment by Strykar** [comment]
@telans Both, I'll try and get a video soon.

**Comment by VortexAcherontic** [comment]
I can confirm the HUD flickering also form DOOM 2016 using Proton + Vulkan.
I made a short video about this issue I assume this add up here.

I use the official 0.1.0 release.

My launch Options
`MANGOHUD=1 MANGOHUD_CONFIG=cpu_temp,gpu_temp,core_load,ram,vram,frame_timing %command%`

https://youtu.be/HaFeHUgCoiA

**Comment by Strykar** [comment]
@VortexAcherontic That's what it looks like for me, thanks for posting the vid.

**Comment by aaulia** [comment]
Any update on this issue?

**Comment by VortexAcherontic** [comment]
Issue seems still to be persist in 0.3.0 release, tested Doom 2016 just right now.

**Comment by DadSchoorse** [comment]
This issue is not really fixable, in Doom you can circumvent it by using FXAA.

**Comment by aaulia** [comment]
> This issue is not really fixable, in Doom you can circumvent it by using FXAA.

Great, good to know. Basically any other anti-aliasing that isn't the `TXAA 8x` (IIRC) will work.

**Comment by DadSchoorse** [comment]
please try the develop branch, 1fc94600e928db2624a0e52b80d14d8e3850af2a have fixed it.

**Comment by aaulia** [comment]
> please try the develop branch, [1fc9460](https://github.com/flightlessmango/MangoHud/commit/1fc94600e928db2624a0e52b80d14d8e3850af2a) have fixed it.

![20200328080446_1](https://user-images.githubusercontent.com/161797/77813147-c9da5f80-70d8-11ea-8977-9041a6e19f98.jpg)

Confirmed, it's working with `TSSAA(8x)`
