### ISSUE TITLE
Mangohud not reading just the .conf file.

### ISSUE THREAD

**Issue by krem-Kalashnikov** [flightlessmango/MangoHud#110]
When I setup my config, no matter how I set it up, certain items will enable themselves, such as the frametime graph. Setting the environment variables also gets ignored and the frametime graph appears regardless.

**Comment by flightlessmango** [comment]
A few options are on by default, they haft to be explicitly disabled if you don't want them to show.
`frame_timing=0` for the frametime graph for example.
https://github.com/flightlessmango/MangoHud/blob/a5f691284de3cc2b086f4d05f917dcaeb00344e7/src/overlay_params.cpp#L318

**Comment by krem-Kalashnikov** [comment]
I forgot this project was open source... I should have had a look through the code first. Thanks, adding frame_timing=0 has disabled it.
