### ISSUE TITLE
Wrong path for some hwmon sensors

### ISSUE THREAD

**Issue by JB0xc390cc** [flightlessmango/MangoHud#1100]
One of my friend(has amdgpu) had that issue MangoHud  showed _0_ gpu power usage however days ago it worked.
From just static review I think this function https://github.com/flightlessmango/MangoHud/blob/41f923b0b2be07f035df221d01625e11f1305fde/src/overlay.cpp#L735 needs to be reviewed by somebody related to how it uses it's local variables. And also when to break or continue from the loops.( _I've nothing to do with hwmon interfaces nor mangohud, it's a pure guess..._)

So I think after this commit https://github.com/flightlessmango/MangoHud/commit/dd5795146258704bec66472e24d9fb0f2edee633 dirs only gets new value in scope of the if statement, but I assume it should have the same value here https://github.com/flightlessmango/MangoHud/blob/41f923b0b2be07f035df221d01625e11f1305fde/src/overlay.cpp#L906C33-L906C37 too(as how it was before). Don't know why shadowing needed here instead different name anyway.

Some other what maybe could be a problem too at some places/in the future but not related to this issue(not so important as I said I have nothing to do with these things nor can test this dynamically):
Here https://github.com/flightlessmango/MangoHud/blob/41f923b0b2be07f035df221d01625e11f1305fde/src/overlay.cpp#L896 and https://github.com/flightlessmango/MangoHud/blob/41f923b0b2be07f035df221d01625e11f1305fde/src/overlay.cpp#L902
Are you sure you use these statements right...? 
-  Like fore sure you read all metrics data(what possibly opened after line 896) from gpu_metrics, and do not read ones with metrics what opened before(like near line 882)?
- Also when continue at line 902 it will try to open for ex.: a hwinfo file for a cardY at next iteration. And I think this can be a problem because at current iteration we possibly already opened some hwinfo interfaces from cardX. => amdgpu_files structure  will contain file pointers related to different cards??

**Comment by JasonBourne0x90** [comment]
Not really a github user so https://github.com/flightlessmango/MangoHud/issues/1099 probably the same

**Comment by flightlessmango** [comment]
Yeah possibly same as #1099 or resolved by #1098

**Comment by JasonBourne0x90** [comment]
Yea its CPU related :D

**Comment by JasonBourne0x90** [comment]
no, https://github.com/flightlessmango/MangoHud/pull/1098 is CPU related which is non related to our gpu isssues...

> For me it's GPU ;) Think that is the difference in our issues.

**Comment by Lassebq** [comment]
> One of my friend(has amdgpu) had that issue MangoHud showed 0 gpu power usage however days ago it worked.

Does this https://github.com/flightlessmango/MangoHud/commit/c33ce2b734856934f53721eeffe421b1da0fb935 commit fix the issue for your friend? Apparently it's related to the changes in kernel, not mangohud

**Comment by flightlessmango** [comment]
Reopen if not resolved
