### ISSUE TITLE
Feature request: Add dynamic FPS 1% and 0.1% [PATCH]

### ISSUE THREAD

**Issue by axet** [flightlessmango/MangoHud#1102]
**Describe the bug**

mangohud only support for 1% and 0.1% when fps logging enabled. This patch enable showing 1% and 0.1% by default.

First patch using ARRAY_SIZE(swapchain_stats::frames_stats) everywhere, replacing '200' const around the code:

* https://gitlab.com/axet/homebin/-/blob/debian/dbuild.d/bookworm/mangohud/const200.patch

Second patch enabling showing 1% and 0.1%

* https://gitlab.com/axet/homebin/-/blob/debian/dbuild.d/bookworm/mangohud/fps1.patch

mangohud-0.6.8

**Comment by flightlessmango** [comment]
Seems fine to me, can you make a PR?

**Comment by axet** [comment]
It is not a PR ready. We may need another config option for that. const 200 causing issues with frame time bars, they are jumping. Not sure what is going on here. Looks like a bug. Need more investigating.

**Comment by flightlessmango** [comment]
I believe this is superseded by the new `fps_metrics` option
