### ISSUE TITLE
gpu_core_clock inaccuracy revisited?

### ISSUE THREAD

**Issue by DonKatsu** [flightlessmango/MangoHud#1104]
**Describe the bug**
Recently I noticed that CoreCtrl's reported GPU clock was lower than the value reported by MangoHud. That lead me to #1018.
My `gpu_core_clock` in MangoHud since the change in that issue only shows the set MAXIMUM MHz by CoreCtrl while under heavyload. Lighter loads have a value that fluctuates but is still higher than what amdgpu_pm_info/CoreCtrl report.
`cat /sys/kernel/debug/dri/1/amdgpu_pm_info` and CoreCtrl report the same value under load which is around 150MHz lower than the set maximum clock, in Unigine Heaven.
Setting CoreCtrl to `Do not control` results in MangoHud's `gpu_core_clock` changing to a fluctuating value at any load, but still higher than what's being reported by amdgpu_pm_info and CoreCtrl.

**List relevant hardware/software information**
- Linux Distribution: Fedora 38 KDE
- MangoHud version: 0.6.9.1
- GPU: 6700XT

**To Reproduce**
1. Launch a game or something with MangoHud
2. Open a CoreCtrl profile or watch amdgpu_pm_info
3. Compare with MangoHud's `gpu_core_clock` reading

**Expected behavior**
`gpu_core_clock` to show the actual GPU clock value.

**Screenshots**
[Example while running Unigine Heaven](https://github.com/flightlessmango/MangoHud/assets/8627704/8db4d7dc-dece-401b-8590-37108c1b65ff)

**Additional context**
As a sanity check I ran Heaven in Windows with the same GPU settings in Adrenalin. Adrenalin and hwinfo64 both read around 2500MHz on GPU clock, same as amdgpu_pm_info and CoreCtrl on Linux.

**Comment by flightlessmango** [comment]
I believe this should be resolved here 6abc794

**Comment by DonKatsu** [comment]
Oh, I really should have checked the date on that commit before I posted this to see that it's not in a release yet...
Unfortunately I can't seem to build from source even with pip meson+ninja. [buildfail.txt](https://github.com/flightlessmango/MangoHud/files/12568012/buildfail.txt)

**Comment by flightlessmango** [comment]
You need to install the `libstdc++-static` package

**Comment by DonKatsu** [comment]
Hmm, that package wasn't included in `build_deps.sh`, and Fedora didn't try to download it as a dependency.
Built and installed, and MangoHud does indeed show the correct GPU clock. Sorry, and thanks for the help.
