### ISSUE TITLE
gpu_junction_temp gpu_mem_temp not showing anything?

### ISSUE THREAD

**Issue by Kopetan4egX** [flightlessmango/MangoHud#1105]
Hello. I see new options (listed in title) were added. But they doesn't show anything for me. Only the regular GPU temp.
What am i doing wrong, please?
Debian testing 6.4.11-1
RX 6600 Mesa 23.1.6-1

**Comment by flightlessmango** [comment]
Attach a screenshot of the hud with the options set

**Comment by Kopetan4egX** [comment]
![Снимок экрана в 2023-09-02 10-58-48](https://github.com/flightlessmango/MangoHud/assets/18350912/47b414a4-fa1c-42bf-86a6-37c2185979ac)

**Comment by flightlessmango** [comment]
What version of mangohud are you using?

**Comment by Kopetan4egX** [comment]
0.6.9.1 from debian repository (it says 0.6.9.1-2 in package manager)

**Comment by Kopetan4egX** [comment]
I removed the one installed from repository, installed from github. Didn't show anything in game (tried Grim dawn), literally nothing, like it doesn't exist. So i removed it and installed again from debian repository (both x64 and i386 packages), but now i'm using conf file from github, not the previous one from i don't remember where.
Temps still not showing, but i have MUCH more stable FPS in some older games and less stutters due to CPU bottleneck (Grim Dawn, Batman Arkham Asylum - the ones i tested, maybe there are others too). I like it, but it's strange. Does that mean, that Mangohud may influence FPS and stuttering?

**Comment by flightlessmango** [comment]
These options don't exist in 0.6.9, they will be introduced in the next release

**Comment by Kopetan4egX** [comment]
Thank you for your work.
Will be waiting.
