### ISSUE TITLE
mx master battery picked up by gamepad_battery

### ISSUE THREAD

**Issue by zany130** [flightlessmango/MangoHud#1108]
**Describe the bug**
Mx Master 3 Battery is shown by mangohud

**List relevant hardware/software information**
- Garuda Linux
- MangoHud version 0.6.9.1.r124.gf667002-1
- GPU 6700xt

**To Reproduce**
1. enable `gamepad_battery`
2. plug in Mx Master 3 mouse
3. see error

**Expected behavior**
Mx master 3 mouse does not show up in mangohud

**Screenshots**
![image](https://github.com/flightlessmango/MangoHud/assets/25832539/f9294b14-2ee6-4302-9271-4dbcee9decf9)
****
**Additional context**
Text bunching up due to horizontal layout is because of font sizing I think

**Comment by zany130** [comment]
could be because of this? https://github.com/flightlessmango/MangoHud/commit/1de9551d384a74dc80a9e31059b9771edaf2ea42
doesn't seem to happen on older commits

**Comment by Etaash-mathamsetty** [comment]
we could probably have a blacklist or whitelist of devices

**Comment by gort818** [comment]
I was planning to combine all wireless devices(gamepad, mice,keyboards) into one parameter like `device_battery` or something. but it seems I need to have different options for types of devices. I will work on this soon Thanks for the feedback.

**Comment by gort818** [comment]
Ok just pushed a commit, it changes things a bit though.

`gamepad_battey` is no more now it is `device_battery` which takes a string.

for example `device_battery=gamepad` or `device_battery=mouse` or `device_battery=gamepad,mouse` for both.

**Comment by zany130** [comment]
yup works perfectly and solves my issue
