### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by JustCauseWhyNot** [flightlessmango/MangoHud#1116]
**Describe the bug**
Crashing after updating to games-util/mangohud-0.6.9.1.

**List relevant hardware/software information**
- Linux Distribution Gentoo
- MangoHud version 0.6.9.1
- GPU Gtx 1660 suepr

**To Reproduce**
When launching warthunder with this desktop file
```
[Desktop Entry]
Version=1.0
Name=War Thunder
Exec=env __GL_SHARPEN_ENABLE=1 __GL_SHARPEN_VALUE=100 OBS_USE_EGL=1 OBS_VKCAPTURE=1 /home/justcausewhynot/Games/WarThunder/launcher
Terminal=false
Type=Application
Icon=/home/justcausewhynot/Games/WarThunder/launcher.ico
```
I get a segfault. I've noticed though it won't segfault if I skip the launcher and run `mangohud ~/aces` 
**Expected behavior**
No crashing. It was working before I upgraded just now to 0.6.9.1. Previously I was running mangohud built from a [different ebuild](https://gitlab.com/TheGreatMcPain/thegreatmcpain-overlay/-/blob/master/games-util/mangohud/mangohud-9999-r6.ebuild?ref_type=heads). I'm not sure which exact commit it was built to.

**Additional context**
Here's this [xorg](https://gist.githubusercontent.com/JustCauseWhyNot/2a5f3d9b1ca5f80bce06ffb5a340de3e/raw/4fef7313da02e34b7ae9aa1d38c129a68859e883/.localsharexorgXorg.0.log.old) log.

**Comment by Leopard1907** [comment]
Probably a duplicate of this

https://github.com/flightlessmango/MangoHud/issues/1084#issuecomment-1682763493

**Comment by JustCauseWhyNot** [comment]
Thats quite likely since the guru ebuild doesn't have abi uses to set. I'll use a different ebuild.

**Comment by flightlessmango** [comment]
Can you try if latest git works to verify?

**Comment by JustCauseWhyNot** [comment]
I will try it out.

**Comment by JustCauseWhyNot** [comment]
I'm trying to compile the latest version, but I get this error `meson.buil:169:9: ERROR: Automatic wrap-based subproject downloading is disabled`, and Here's the full [meson-log](hubusercontent.com/JustCauseWhyNot/888967bf0120685733336367bb7cbecb/raw/7cce3fe43bc53065267358edf559b84486919c24/vartmpportagegames-utilmangohud-9999workmangohud-9999-buildmeson-logsmeson-log.txt). I don't know which subproject (or I guess dependency) I don't have installed that is causing the compilation to fail.

**Comment by JustCauseWhyNot** [comment]
Well It doesn't crash anymore if I build using the link to the other live ebuild, and I did disable abi_x86_32.

**Comment by flightlessmango** [comment]
Is this resolved or not?

**Comment by JustCauseWhyNot** [comment]
I'll say yes.
