### ISSUE TITLE
mangohud command no longer works when installed from flatpak in OpenSUSE MicroOS (Aeon)

### ISSUE THREAD

**Issue by AED-001** [flightlessmango/MangoHud#1118]
**Describe the bug**
mangohud command no longer works when installed from flatpak in OpenSUSE MicroOS (Aeon)

**List relevant hardware/software information**
- OpenSUSE MicroOS (Aeon)
- MangoHud 0.6.9-1
- AMD Radeon RX 6800

**To Reproduce**
1. Open terminal
2. Type `mangohud`
3. Hit `ENTER`
4. Command not found

**Expected behavior**
Normally the mangohud application will execute. This causes Steam applications to hang if you have it in your launch options with `mangohud %command%`

**Comment by flightlessmango** [comment]
Is your steam install also a flatpak?

**Comment by AED-001** [comment]
Hi,

My Steam install is also a flatpak. It just stopped working when I booted up my PC today and games that I had `mangohud %command%` in my launch options stopped working until I removed it.

I'm thinking maybe some sort of automated update to something else other than mangohud broke it?

Thank you for the quick reply!

**Comment by AED-001** [comment]
![image](https://github.com/flightlessmango/MangoHud/assets/12076835/459d29a7-8c67-4f01-854c-de3f52dd93e2)
doesn't exist according to terminal output-- is there a filepath I can check? already tried un-installing and re-installing

**Comment by AED-001** [comment]
removed 22.08, installed 23.08, same issue is happening. running mangohud (either with the command or directly via flatpak run) telling me that mangohud cannot be found even though the grep returns that 23.08 is installed

`aed@localhost:~> flatpak --columns=application,branch --runtime list | grep MangoHud
org.freedesktop.Platform.VulkanLayer.MangoHud	23.08
aed@localhost:~> flatpak run org.freedesktop.Platform.VulkanLayer.MangoHud
bwrap: execvp /bin/sh: No such file or directory
aed@localhost:~> mangohud
bash: mangohud: command not found
aed@localhost:~> flatpak run org.freedesktop.Platform.VulkanLayer.MangoHud/x86_64/23.08
bwrap: execvp /bin/sh: No such file or directory
aed@localhost:~> 
`

**Comment by AED-001** [comment]
understood, thought it would give some terminal output to know that it's working since steam was previously giving an error when running via flatpak run in terminal saying mangohud could not be found

thx for all the help, all set-- manually installing 23.08 fixed it
