### ISSUE TITLE
Incomplete overlay in citra-qt

### ISSUE THREAD

**Issue by ahmubashshir** [flightlessmango/MangoHud#112]
When using mangohud with citra-qt, the overlay is shown partially, like this
![image](https://user-images.githubusercontent.com/24864366/77886789-4c0a8580-728b-11ea-9835-6936f3a4ff0e.png)
But with citra, it show up properly.
![image](https://user-images.githubusercontent.com/24864366/77887080-c63b0a00-728b-11ea-9d33-bd159a3faaab.png)

**Comment by jackun** [comment]
If you can, try to build `develop` branch.

**Comment by ahmubashshir** [comment]
This issue was fixed in `develop` branch.
But when these changes will land on master?

**Comment by ahmubashshir** [comment]
Its also fixed in master now. So I'm closing this issue.
