### ISSUE TITLE
Unable to set some options in presets.conf

### ISSUE THREAD

**Issue by hannesmann** [flightlessmango/MangoHud#1120]
**Describe the bug**
I'd like to use the new preset feature in 0.7.0-rc1 to create two presets: One where the default FPS limit is 0 and one where the default FPS limit is 140. If I use `fps_limit=0` in the preset this works but if I use `fps_limit=0:140:120:60` (so I can toggle between them) MangoHud throws an error in overlay_params.cpp. 

The same thing happens if I try to set hotkeys like `toggle_fps_limit`. Setting `toggle_fps_limit=Shift_R` parses correctly but `toggle_fps_limit=Shift_R+F10` throws an error. It seems like there are some "special" characters that work in the regular config but not the new presets.conf. 

**List relevant hardware/software information**
- Arch Linux
- MangoHud 0.7.0-rc1
- AMD Radeon RX 6700 XT

**To Reproduce**
1. Create ~/.config/MangoHud/presets.conf with the contents: 
```
[preset 1]
cpu_stats
cpu_temp
cpu_power
cpu_mhz
gpu_stats
gpu_temp
gpu_core_clock
gpu_mem_clock
gpu_mem_temp
gpu_power
vram
ram
fps
frametime
frame_timing
no_display
round_corners=4
text_outline=0
fps_limit=0:140:120:60

[preset 2]
...
fps_limit=140:120:60:0
```
2. Set `preset=1` in ~/.config/MangoHud/MangoHud.conf
3. MangoHud fails with an error `[overlay_params.cpp:815] Unknown option '140:120:60'`

**Expected behavior**
Presets should support the same options as MangoHud.conf.

**Comment by gort818** [comment]
Shouldn't `fps_limit` be comma seperated?

**Comment by hannesmann** [comment]
> Shouldn't fps_limit be comma seperated?

It should... but the code seems to [support both](https://github.com/flightlessmango/MangoHud/blob/master/src/string_utils.h#L113). I'm not sure if that changed at some point. Setting `fps_limit=140,120,60,0` doesn't work either.

**Comment by hannesmann** [comment]
#1121
