### ISSUE TITLE
Can't toggle presets.

### ISSUE THREAD

**Issue by ecabott** [flightlessmango/MangoHud#1122]
**Describe the bug**
Can't toggle between presets.

**To Reproduce**
1. Create ~/.config/MangoHud/MangoHud.conf with the contents:
```
preset=2,3
toggle_preset
```
2. Press RightShift+F10 -> Does nothing.

**Expected behavior**
It should toggle between presets.

**Comment by flightlessmango** [comment]
Are you on X11?

**Comment by flightlessmango** [comment]
Actually the problem is `toggle_preset`, this option is used to set the key you want to toggle with.
If you just set `toggle_preset` you're unbinding the default to nothing

**Comment by ecabott** [comment]
Yes, I am on X11.
Removing ``` toggle_preset ``` didn't work and setting ``` toggle_preset=Shift_R+F10 ``` didn't work either.

**Comment by flightlessmango** [comment]
Does other keybinds work?

**Comment by ecabott** [comment]
Other keybinds also doesn't  work.

**Comment by ecabott** [comment]
Setting ``` toggle_hud=Shift_R+F10 ``` works for its purpose.

**Comment by ecabott** [comment]
Any updates?

**Comment by flightlessmango** [comment]
So far I'm unable to reproduce it.
Can you post a new config that would repro this issue?

**Comment by flightlessmango** [comment]
I haven't had any other reports of this and since keybinds work in general, I would assume this is a user error
