### ISSUE TITLE
Resizing vulkan windows leaks memory

### ISSUE THREAD

**Issue by arttuc** [flightlessmango/MangoHud#1125]
**Describe the bug**
Resizing any(?) vulkan window (vkcube, retroarch with vulkan backend, etc...) will leak memory.

**List relevant hardware/software information**
- Linux Distribution: Arch Linux
- MangoHud version: 0.6.9
- GPU: Radeon RX 6700 XT

**To Reproduce**
1. Run `vkcube` or any other vulkan application that allows resizing with MangoHud.
2. Resize the window.
3. Observe memory usage rise with `htop` or `procmem` mangohud option.

**Expected behavior**
No memory leak.

**Screenshots**
![kuva](https://github.com/flightlessmango/MangoHud/assets/37794543/7a01b242-2799-4be6-aecc-a1b5eac23018)

Video **(Photosensitivity warning!!!)**:

https://github.com/flightlessmango/MangoHud/assets/37794543/a5e16b3d-87dc-41fe-b4af-56eea0666c83

**Additional context**
KDE Plasma 5.27.8 on Wayland

vkcube was running on xwayland.
RetroArch is wayland native.

**Comment by gort818** [comment]
Thanks for opening an issue, would you mind checking if 41e48595478f290dd801d5eeb1549d49ddf4a5e6 fixes the issue?

**Comment by arttuc** [comment]
Yes, it fixes the leak. :+1:
