### ISSUE TITLE
Horizontal window is a fixed size

### ISSUE THREAD

**Issue by HugLifeTiZ** [flightlessmango/MangoHud#1126]
**Describe the bug**
It doesn't seem that you can change the width of the window in horizontal mode, at least not when overriding a preset. I've tried an explicit `width` parameter as well as various `table_columns` parameters.

**List relevant hardware/software information**
- Linux Distribution: SteamOS 3.5 in Preview
- MangoHud version: (Whatever's in 3.5. Sorry, I'm not sure how to tell.)
- GPU: Steam Deck's Aerith APU

**To Reproduce**
`$XDG_CONFIG_HOME/MangoHud/presets.conf`:
```
[preset 1]
horizontal
hud_no_margin
width=200
table_columns=3
legacy_layout=0
fps
frametime=0
frame_timing=1
```

**Expected behavior**
The width of the background can be changed as specified.

**Screenshots**
Screenshots taken on the Deck don't include the FPS overlay, but I was able to record video including it.
![vlcsnap-2023-09-21-11h26m54s579-crop](https://github.com/flightlessmango/MangoHud/assets/4130673/3f67db80-e714-4d54-99fd-26a84632ecbe)

**Additional context**
The idea here is that I'm trying to change the Deck's first preset to show both FPS and frametime, and nothing else. The background stretches far out past where I need it. I can work around this issue with `background_alpha=0.0`, but it becomes hard to see in bright scenes.

**Comment by mmbossoni** [comment]
@HugLifeTiZ , have you tried horizontal_stretch=0 on your config?

**Comment by gort818** [comment]
Is the issue that window spans the entire horizontal width?
You only want it to encapsulate the items you have enabled? if so what @mmbossoni said should work.
Or do you want to be able to fine tune the width?

**Comment by HugLifeTiZ** [comment]
The issue is that the window spans an arbitrary 1280px width, no matter what I do. I got that screenshot from a video captured on a 1920x1080 monitor. `horizontal_stretch` does nothing no matter what I set it to. But then again, attempting to set that may be affected by the bug fixed in #1121 because it's a pretty long option.

**Comment by gort818** [comment]
I am not sure what version mangohud is currently on the steamdeck, but with the latest version setting `horizontal_stretch=0` should do the trick the width will only expand as needed.
![Screenshot_20231004_211502](https://github.com/flightlessmango/MangoHud/assets/9098121/1ae6892a-57e5-458e-99b8-3eee5a1a7826)

**Comment by HugLifeTiZ** [comment]
This is now fixed in SteamOS 3.5.1. Thanks for your time, all!

**Comment by gort818** [comment]
No problem glad it works!

**Comment by niluzz** [comment]
> Não tenho certeza de qual versão do mangohud está atualmente no Steamdeck, mas com a versão mais recente, a configuração `horizontal_stretch=0`deve resolver o problema, a largura só aumentará conforme necessário. ![Screenshot_20231004_211502](https://github.com/flightlessmango/MangoHud/assets/9098121/1ae6892a-57e5-458e-99b8-3eee5a1a7826)

What would your configuration be? I liked it a lot
