### ISSUE TITLE
Sometimes spams stdout with "0"

### ISSUE THREAD

**Issue by MithicSpirit** [flightlessmango/MangoHud#1127]
**Describe the bug**
Having the magohud overlay on causes it to sometimes spam the output with a bunch of lines just containing `0`.

**List relevant hardware/software information**
- Linux Distribution: Arch Linux
- MangoHud version: 0.6.9.1
- GPU: AMD integrated graphics (Ryzen 5 5600U)

**To Reproduce**
1. Run `mangohud glxgears`
2. Start the overlay
3. Observe terminal output (sometimes it takes a while to show up)

**Expected behavior**
No stdout spam

**Additional context**
[MangoHud.conf](https://github.com/flightlessmango/MangoHud/files/12707318/MangoHud.conf.txt)

**Comment by flightlessmango** [comment]
Can you test if this happens in 0.7.0-rc1?
https://github.com/flightlessmango/MangoHud/releases/tag/v0.7.0-rc1

**Comment by MithicSpirit** [comment]
Some testing does suggest that it's fixed, but it can be quite inconsistent so I'm not sure. I've had more consistent results with some games I play in flatpak, but since the flathub package isn't updated yet I can't test that atm. I'll close this for now and if I encounter it again in newer versions I'll reopen.
