### ISSUE TITLE
mangohud-setup.sh does not install OpenGL libraries

### ISSUE THREAD

**Issue by gwaub** [flightlessmango/MangoHud#1130]
**The Problem:**
Unlike the build script, the installer script bundled with the generic release tarball forgets to install libMangoHud_opengl.so.

This obviously causes mangohud to fail to load with OpenGL applications and throw this error:
`ERROR: ld.so: object '/usr/lib/mangohud/$LIB/libMangoHud_opengl.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored`.

**Solution:**
Simply adding these lines to `mangohud_install()` in mangohud-setup.sh and running it again fixes it:

```
/usr/bin/install -Dvm644 ./usr/lib/mangohud/lib64/libMangoHud_opengl.so /usr/lib/mangohud/lib64/libMangoHud_opengl.so
/usr/bin/install -Dvm644 ./usr/lib/mangohud/lib32/libMangoHud_opengl.so /usr/lib/mangohud/lib32/libMangoHud_opengl.so
```

**Comment by flightlessmango** [comment]
Added here 8fca45f, also replaced the `mangohud-setup.sh` in the release
