### ISSUE TITLE
Incorrect GPU stats shown (drm card1 APU shown, card0 discrete GPU wanted)

### ISSUE THREAD

**Issue by john-tho** [flightlessmango/MangoHud#114]
Using 0.3.1, with a Ryzen APU (drm `card1`), and an RX580 (drm `card0`).

The RX580 is the active card with the monitor attached.

HUD shows the stats from card1 (always 0% load, GPU temp matches CPU temp), `cat: /sys/class/drm/card1/device/gpu_busy_percent: Invalid argument`, rather that the wanted discrete GPU stats.

Guessing the values selected by the first loop pass `card0` are overwritten by a later loop over `card1`?

https://github.com/flightlessmango/MangoHud/blob/40c112b80c1210341b60a4f945b7022022362bbc/src/overlay.cpp#L797

Possible workarounds / fixes?:
- OVERLAY_PARAM_CUSTOM _drm_gpuname_
- Support multiple GPUs
- Determine which GPU is active

Happy to try implementing a parameter, just looking for discussion for best option.

Cheers!

**Comment by plasticbomb1986** [comment]
Similar issue.

Dual Vega64 system, when the game runs (on GPU0 the hud shows GPU1 info). For a while its not been working correctly, i thought i messed up something, but today, when i was playing, left foldingahome running on the secondary gpu, and i was surprised to see gpu activity is shown, so made a fast fact check. GPU usage freq, temp, vram all what was shown is connected to gpu1, the secondary gpu in my system.

**Comment by VortexAcherontic** [comment]
I am not sure if this relates to this too since I do not have an AMD dGPU but I am experiencing the same issue (or a similar one)

I the nvidia-settings window you can see the actual GPU load.

![Screenshot_20200410_150631](https://user-images.githubusercontent.com/11244092/78997193-5c054d80-7b46-11ea-8eb4-48858bcfbc0e.png)
![Screenshot_20200410_150928](https://user-images.githubusercontent.com/11244092/78997197-5c9de400-7b46-11ea-9606-469172c74d3b.png)

Specs:
OS: openSUSE Tumbleweed
CPU: i5-3230M
iGPU: Intel HD 3000
dGPU: NVidia GT 730M (Driver: 440.86)
MangoHUD: 0.3.1
Prime support by: suse-prime (aka. Prime Manager or prime-select)

**Comment by jackun** [comment]
@VortexAcherontic Kind of. Latest release uses only NVML which apparently doesn't work with old cards. You need XNVCtrl which will be in next release but usually these "prime" launchers run nvidia gpu in a separate Xorg session with `DISPLAY=:8` or something similar. XNVCtrl tries to use current session $DISPLAY which is usually `:0`. No idea which way is best for detecting correct DISPLAY env var so it might still be borked in next release.

**Comment by VortexAcherontic** [comment]
@jackun Thanks for your reply. I checked the used XScreen which the NVidia card is running on and according to nvidia-settings and a play echo $DISPLAY show the nvidia card is running on :0 it seems.
Also as far as I understand how suse-prime/prime-select works since you need to log out and log in to switch between the iGPU and dGPU the whole X11 session runs on the GPU which was selected.

Furthermore I checked if libXNVCtrl is installed on my system and it seems my distro offers 2 versions libNVCtrl0 and libXNVCtrl. I installed both but this seems not to change anything.

Can you point me somewhere where I can check if NVML is supported/working or not?
Since I think it is related to the NVML thing maybe.

**Comment by jackun** [comment]
If you can, try building `develop` branch to see [if selecting with MANGOHUD_PCI_DEV works.](https://github.com/flightlessmango/MangoHud/commit/a9311bb5788a204928cd915e780c4d834e368f81)

Like `MANGOHUD_PCI_DEV=0000:xx:xx.x MANGOHUD=1 vkcube` where the x's are `domain:bus:slot.function`. Check with `lspci -D`.

**Comment by john-tho** [comment]
Yes, that work for me, thanks. 
```
readlink /sys/class/drm/card0
../../devices/pci0000:00/0000:00:01.1/0000:01:00.0/drm/card0
```
`MANGOHUD=1 MANGOHUD_CONFIG=full MANGOHUD_PCI_DEV="0000:01:00.0" vkcube`
Gives me values for the wanted GPU.

Console shows `MANGOHUD: skipping GPU, no PCI ID match` for the skipped device. It is worth showing the skipped pci_device here, or hiding this in debug?

Cheers

**Comment by VortexAcherontic** [comment]
@jackun Thank you for your reply, unfortunetely this did not helped on my end.

lspci -D
````
0000:00:00.0 Host bridge: Intel Corporation 3rd Gen Core processor DRAM Controller (rev 09)
0000:00:01.0 PCI bridge: Intel Corporation Xeon E3-1200 v2/3rd Gen Core processor PCI Express Root Port (rev 09)
0000:00:01.1 PCI bridge: Intel Corporation Xeon E3-1200 v2/3rd Gen Core processor PCI Express Root Port (rev 09)
0000:00:02.0 VGA compatible controller: Intel Corporation 3rd Gen Core processor Graphics Controller (rev 09)
0000:00:14.0 USB controller: Intel Corporation 7 Series/C210 Series Chipset Family USB xHCI Host Controller (rev 04)
0000:00:16.0 Communication controller: Intel Corporation 7 Series/C216 Chipset Family MEI Controller #1 (rev 04)
0000:00:1a.0 USB controller: Intel Corporation 7 Series/C216 Chipset Family USB Enhanced Host Controller #2 (rev 04)
0000:00:1b.0 Audio device: Intel Corporation 7 Series/C216 Chipset Family High Definition Audio Controller (rev 04)
0000:00:1c.0 PCI bridge: Intel Corporation 7 Series/C216 Chipset Family PCI Express Root Port 1 (rev c4)
0000:00:1c.3 PCI bridge: Intel Corporation 7 Series/C216 Chipset Family PCI Express Root Port 4 (rev c4)
0000:00:1d.0 USB controller: Intel Corporation 7 Series/C216 Chipset Family USB Enhanced Host Controller #1 (rev 04)
0000:00:1f.0 ISA bridge: Intel Corporation HM76 Express Chipset LPC Controller (rev 04)
0000:00:1f.2 SATA controller: Intel Corporation 7 Series Chipset Family 6-port SATA Controller [AHCI mode] (rev 04)
0000:00:1f.3 SMBus: Intel Corporation 7 Series/C216 Chipset Family SMBus Controller (rev 04)
0000:01:00.0 3D controller: NVIDIA Corporation GK208M [GeForce GT 730M] (rev a1)
0000:03:00.0 Network controller: Intel Corporation Centrino Wireless-N 135 (rev c4)
0000:04:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 06)
````

reveals: `0000:01:00.0 3D controller: NVIDIA Corporation GK208M [GeForce GT 730M] (rev a1)`
So I ran:
`MANGOHUD_PCI_DEV=0000:01:00.0 MANGOHUD=1 MANGOHUD_CONFIG=full,toggle_hud=F10 vkmark -p immediate` but this time no GPU device was shown at all :/

ALso without the `MANGOHUD_PCI_DEV=` parameter there is no GPU shown.

Here's how I setup Mangohud

`git clone https://github.com/flightlessmango/MangoHud.git`
`cd MangoHud/`
`git checkout develop`
`./build.sh build`
`./build.sh package`
`./build.sh install`

No errors where displayed and all dependencies could be installed right away.

`MANGOHUD=1 MANGOHUD_CONFIG=full,toggle_hud=F10 vkmark -p immediate`
![Screenshot_20200411_155142](https://user-images.githubusercontent.com/11244092/79045619-60943980-7c0c-11ea-93e8-8ec828a518f0.png)

`MANGOHUD_PCI_DEV=0000:01:00.0 MANGOHUD=1 MANGOHUD_CONFIG=full,toggle_hud=F10 vkmark -p immediate`
![Screenshot_20200411_155230](https://user-images.githubusercontent.com/11244092/79045659-83265280-7c0c-11ea-8a1c-697a01d2d640.png)

**Comment by flightlessmango** [comment]
@VortexAcherontic I'm pretty sure these are two different issues, this fix was for NVML but your problem has to do with xnvctrl. I think you should make a separate issue on it

**Comment by VortexAcherontic** [comment]
@flightlessmango Alright, should I remove my comments here since they do not belong to this issue anyway?

**Comment by plasticbomb1986** [comment]
Or an another option could be in the mangohud config, to show x gpu or x+y. Like:

GPU0 Usage% Freq Temp
GPU0 VRAMused
GPU1 Usage% Freq Temp
GPU1 VRAMused
CPU Usage% Average freq temp
RAM usage
IO RD/RW
DXVK/OGL FPS frametime
dxvkver
Frametime graph

With AMDGPUs under /sys/class/drm/ these are the presented "options" for me:
card0  card0-DP-1  card0-DP-2  card0-DP-3  card0-HDMI-A-1  card1  card1-DP-4  card1-DP-5  card1-DP-6  card1-HDMI-A-2  renderD128  renderD129  ttm  version
under /sys/class/drm/card0/device and /sys/class/drm/card1/device

![Screenshot from 2020-04-20 18-41-35](https://user-images.githubusercontent.com/26345407/79776967-d5ffb880-8336-11ea-9137-3bec5e5e84e8.png)

**Comment by john-tho** [comment]
Thanks for the fix.
Works fine for me with the latest release:
`MANGOHUD=1 MANGOHUD_CONFIG="full,pci_dev=0000\:01\:00.0" vkcube`
