### ISSUE TITLE
Mangohud 0.7.0 freeze some games

### ISSUE THREAD

**Issue by cyberconan** [flightlessmango/MangoHud#1146]
With the latest version, some games like Red Dead Redemption 2 or Cyberpunk 2077 froze after a random time. The sound continues but the game is completely frozen. In dmesg it shows me this error:

[lun oct  2 19:02:27 2023] GpuWatchdog[2065]: segfault at 0 ip 00007fbdf1992a66 sp 00007fbde7f304f0 error 6 in libcef.so[7fbded4ef000+7770000] likely on CPU 2 (core 2, socket 0)
[lun oct  2 19:02:27 2023] Code: 89 de e8 4d ee 6e ff 80 7d cf 00 79 09 48 8b 7d b8 e8 4e 66 2c 03 41 8b 84 24 e0 00 00 00 89 45 b8 48 8d 7d b8 e8 9a d2 b5 fb <c7> 04 25 00 00 00 00 37 13 00 00 48 83 c4 38 5b 41 5c 41 5d 41 5e

The issue happens in Archlinux with vanilla and LTS kernels. I have a NVIDIA GTX 2080 in MSI laptop.

Downgrading to 6.9.1 resolves the issue.

**Comment by flightlessmango** [comment]
`libcef.so` makes me think this is related to the steam overlay. Do you have that on?

**Comment by cyberconan** [comment]
No, I have in-game overlay disabled.

![imagen](https://github.com/flightlessmango/MangoHud/assets/1497109/8cb5e13e-40e1-4efd-9f21-ce7d1e26a0af)

**Comment by flightlessmango** [comment]
Unable to reproduce so far.
Can you send a crash dump?
