### ISSUE TITLE
Show metrics (AVG and 1%Low) during the benchmark

### ISSUE THREAD

**Issue by Faugus** [flightlessmango/MangoHud#1147]
Currently it's only possible to see the metrics when the benchmark is finished.
Is there any way of displaying the metrics during the benchmark, like MSI Afterburner / Riva Tuner does?
If not, would it be possible to implement this?

**Comment by flightlessmango** [comment]
This has been implemented here https://github.com/flightlessmango/MangoHud/commit/48f8db420b836bd29c963888cbd013b894477ae8

`fps_metrics`          Takes a list of decimal values or the value avg, e.g `avg,0.001`

**Comment by Faugus** [comment]
I think I didn't explain it correctly @flightlessmango:
When I press Shift+F2 the benchmark starts.
And when I press Shift+F2 again the benchmark stops and THEN it shows the AVG, 1%Low, 0.1%Low...
Is there a way to show the AVG, 1%Low, 0.1%Low DURING the benchmarking, updating the values in realtime?
Is it something hard to implement?
Thank you very much for your software.

**Comment by flightlessmango** [comment]
That's what `fps_metrics` does. If you set `fps_metrics=0.001` then it always shows 0.1% fps regardless of benchmarking

**Comment by Faugus** [comment]
Oh, I got it now. Just tried it and it's working. Is there a way to reset the metrics @flightlessmango?

**Comment by flightlessmango** [comment]
Yes you can reset with `Shift_R + F9`

**Comment by Faugus** [comment]
Thank you so much!
