### ISSUE TITLE
The 'cpu power' does not show the correct consumption

### ISSUE THREAD

**Issue by Alekyo4** [flightlessmango/MangoHud#1148]
**Describe the bug**
The 'cpu power' does not work correctly, it does not show consumption.

**List relevant hardware/software information**
- Ubuntu 22.04.3 LTS
- v0.7.0-24-g2bf2793
- Radeon RX 580 2048SP

**To Reproduce**
`mangohud glxgears`

**Expected behavior**
Consumption is stagnant at 0.0 something that would be unlikely, I also tested Tomb Raider on Steam.

**Screenshots**
![Glxgears](https://github.com/flightlessmango/MangoHud/assets/84733423/63523a27-8e55-4a87-9681-c9094cb7220c)

**Additional context**
My processor is an Intel Xeon E5 2640V3

I tested with another resource monitor on another operating system and the consumption returns as expected, so I believe it is not due to the absence of the sensor.

**Comment by flightlessmango** [comment]
You have to set some permissions manually, this is documented in the readme
> Note: RAPL is currently used for Intel CPUs to show power draw with cpu_power which may be unreadable for non-root users due to [vulnerability](https://platypusattack.com/)

**Comment by cloudishBenne** [comment]
@Alekyo4 I would argue, if you are on a gaming only system, you can use this installation script for a systemd service file:
```bash
#!/bin/bash

# Check if script is running as root
if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

# Create the systemd service file
cat << EOF > /etc/systemd/system/mangohud_intel-rapl_permissions.service
[Unit]
Description=MangoHud - Change permissions of intel-rapl file at boot
After=multi-user.target

[Service]
Type=oneshot
ExecStart=/bin/chmod +r '/sys/class/powercap/intel-rapl:0/energy_uj'
RemainAfterExit=yes
User=root

[Install]
WantedBy=multi-user.target
EOF

# Reload the systemd daemon to recognize the new service
systemctl daemon-reload

# Enable the new service so it starts on boot
systemctl enable --now mangohud_intel-rapl_permissions.service

echo "Service installed and enabled successfully"

```
1. save the script as `~/.config/MangoHud/install_intel-rapl_systemd-unit.sh`
2. make it runnable with `chmod +x ~/.config/MangoHud/install_intel-rapl_systemd-unit.sh`
3. run it

I use the user-config folder of MangoHud because it is the easiest to remember for me, if i have to run it again after a system version upgrade.
