### ISSUE TITLE
Failed to parse PCI device

### ISSUE THREAD

**Issue by Yoss101** [flightlessmango/MangoHud#1149]
**Describe the bug**
Mangohud crashes any game if used through proton? (only tested dota2 vulkan without issues)
glxgears and vkcube crash

Odd part is it still works in dota; but if i run gears it returns:
`[⚡] × mangohud glxgears
[2023-10-07 08:31:32.661] [MANGOHUD] [error] [overlay.cpp:768] Failed to parse PCI device ID: '0:0000:01'
[2023-10-07 08:31:32.661] [MANGOHUD] [error] [overlay.cpp:769] Specify it as 'domain:bus:slot.func'
[2023-10-07 08:31:32.664] [MANGOHUD] [error] [nvml.cpp:29] Getting device handle by PCI bus ID failed: Not Found
[2023-10-07 08:31:32.664] [MANGOHUD] [error] [nvml.cpp:30] Using index 0.
[2023-10-07 08:31:32.670] [MANGOHUD] [info] [gl_renderer.cpp:422] GL version: 4.6
Running synchronized to the vertical refresh.  The framerate should be
approximately the same as the monitor refresh rate.
X Error of failed request:  BadValue (integer parameter out of range for operation)
Major opcode of failed request:  157 (NV-CONTROL)
Minor opcode of failed request:  27 ()
Value in failed request:  0x17
Serial number of failed request:  14
Current serial number in output stream:  14
terminate called after throwing an instance of 'std::system_error'
what():  Resource deadlock avoided
fish: Job 1, 'mangohud glxgears' terminated by signal SIGABRT (Abort)`

**List relevant hardware/software information**
OS: Garuda Linux
MangoHud version: 0.7.0-1
Intel iGpu and Nvidia 3080 Laptop max-q 16gb

**To Reproduce**
1. Attempt to use mangohud in any game and it will crash

**Expected behavior**
Mangohud should parse and render.

**Additional context**
Doesn't matter what gpu it's set to. It still fails to parse.
`
0000:00:02.0 VGA compatible controller: Intel Corporation TigerLake-H GT1 [UHD Graphics] (rev 01)
0000:01:00.0 VGA compatible controller: NVIDIA Corporation GA104M [GeForce RTX 3080 Mobile / Max-Q 8GB/16GB] (rev a1)`
Nvida Driver Version: 535.113.01

`[⚡] × VK_LOADER_DEBUG=all mangohud vkcube
DRIVER | LAYER:       <Device>
DRIVER | LAYER:           Using "NVIDIA GeForce RTX 3080 Laptop GPU" with driver: "libGLX_nvidia.so.0"
[2023-10-07 08:45:00.600] [MANGOHUD] [error] [overlay.cpp:768] Failed to parse PCI device ID: '0:0000:01'
[2023-10-07 08:45:00.600] [MANGOHUD] [error] [overlay.cpp:769] Specify it as 'domain:bus:slot.func'
[2023-10-07 08:45:00.603] [MANGOHUD] [error] [nvml.cpp:29] Getting device handle by PCI bus ID failed: Not Found
[2023-10-07 08:45:00.603] [MANGOHUD] [error] [nvml.cpp:30] Using index 0.
X Error of failed request:  BadValue (integer parameter out of range for operation)
Major opcode of failed request:  157 (NV-CONTROL)
Minor opcode of failed request:  27 ()
Value in failed request:  0x17
Serial number of failed request:  14
Current serial number in output stream:  14
terminate called after throwing an instance of 'fish: Job 1, 'VK_LOADER_DEBUG=all mangohud vk…' terminated by signal SIGSEGV (Address boundary error)`

**Comment by flightlessmango** [comment]
What is your config file?

**Comment by Yoss101** [comment]
################### File Generated by GOverlay ###################

toggle_fps_limit=F1
vsync=0
gl_vsync=-1
legacy_layout=false
pci_dev=0:0000:01
gpu_text=GPU
cpu_color=0068B5
cpu_text=CPU
io_color=D8D8D8
vram_color=4FB830
ram_color=0068B5
fps
engine_color=3A8623
gpu_color=4FB830
wine_color=3A8623
frame_timing=1
frametime_color=4FB830
media_player_color=3A8623
table_columns=3
background_alpha=0.4
font_size=24

background_color=020202
position=top-left
text_color=D8D8D8
round_corners=3
#GOVERLAY_THEME=intelnvidia
toggle_hud=Shift_R+F12
toggle_logging=Shift_L+F2
upload_log=F5
output_folder=/home/yoss
media_player_name=spotify

**Comment by flightlessmango** [comment]
The `pci_dev` option appears to be wrong as the error suggests

**Comment by Yoss101** [comment]
Maybe I'm not understanding but using any variation of: 0000:01:00.0 results in errors as well. Apologies if I'm overlooking something.

**Comment by flightlessmango** [comment]
is it the same error?

**Comment by Yoss101** [comment]
Unless I'm using the wrong device id. (0000:01)

[2023-10-07 23:57:53.325] [MANGOHUD] [error] [overlay.cpp:768] Failed to parse PCI device ID: '0000:01'
[2023-10-07 23:57:53.325] [MANGOHUD] [error] [overlay.cpp:769] Specify it as 'domain:bus:slot.func'
[2023-10-07 23:57:53.327] [MANGOHUD] [error] [nvml.cpp:29] Getting device handle by PCI bus ID failed: InvalidArgument
[2023-10-07 23:57:53.327] [MANGOHUD] [error] [nvml.cpp:30] Using index 0.
X Error of failed request:  BadValue (integer parameter out of range for operation)

**Comment by flightlessmango** [comment]
Using my GPU as an example
`03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 31 [Radeon RX 7900 XT/7900 XTX]`
take 03:00.0 and add 0000: to the beginning of it `0000:03:00.0`

**Comment by gort818** [comment]
Was just about to post the same thing.
this also should work
`pci_dev=0:03:00.0`

**Comment by Yoss101** [comment]
That results in

DRIVER | LAYER:           Using "NVIDIA GeForce RTX 3080 Laptop GPU" with driver: "libGLX_nvidia.so.0"
X Error of failed request:  BadValue (integer parameter out of range for operation)
Major opcode of failed request:  157 (NV-CONTROL)
Minor opcode of failed request:  27 ()
Value in failed request:  0x17
Serial number of failed request:  14
Current serial number in output stream:  14
terminate called after throwing an instance of 'std::system_error'
what():  Resource deadlock avoided
fish: Job 1, 'VK_LOADER_DEBUG=all mangohud vk…' terminated by signal SIGABRT (Abort)

**Comment by flightlessmango** [comment]
that's a different error, it's a bug that's been fixed after 0.7. You would need to get a newer or older version

**Comment by Yoss101** [comment]
I'm currently on MangoHud version: 0.7.0-1

**Comment by Yoss101** [comment]
Downgrading to 0.6.9.1 worked like a charm! Thanks a ton for all the help friends!

**Comment by Perkolator** [comment]
> that's a different error, it's a bug that's been fixed after 0.7. You would need to get a newer or older version

What version is that? I have the same "X Error of failed request: BadValue (integer parameter out of range for operation)..." problem. I'm using Bottles and Flatpak MangoHud and there hasn't been any updates since 0.7 was finally released for Flatpak too.

**Comment by Yoss101** [comment]
I used downgrade to the last 6.x version and it solved this issue for me.

**Comment by Perkolator** [comment]
> > that's a different error, it's a bug that's been fixed after 0.7. You would need to get a newer or older version
> 
> What version is that? I have the same "X Error of failed request: BadValue (integer parameter out of range for operation)..." problem. I'm using Bottles and Flatpak MangoHud and there hasn't been any updates since 0.7 was finally released for Flatpak too.

@flightlessmango: Did you see my question? Is there a newer version released that fixes this problem? Flatpak versions/branches haven't been updated since 0.7 was released and I can't see any other releases in this repo either.

**Comment by flightlessmango** [comment]
@Perkolator No there is no release after 0.7 yet

**Comment by Perkolator** [comment]
> @Perkolator No there is no release after 0.7 yet

Thanks for answering. This "X Error of failed request: BadValue (integer parameter out of range for operation)..." error has been affecting several games for me already, any chance you could do a quick bug fix release (that would hopefully then trickle down to Flatpak MangoHud as well)? Thanks.
