### ISSUE TITLE
Found a GUI of MangoHud

### ISSUE THREAD

**Issue by TheEvilSkeleton** [flightlessmango/MangoHud#115]
Hello, I have found an awesome project made by [benjamimgois](https://github.com/benjamimgois), which brings a GUI to MangoHud. In case you want to, you can add it in your README.

Here's the link: https://github.com/benjamimgois/goverlay

In case you are wondering, this is not advertisement. I am not associated with him in any way, shape or form. I independently decided to create this issue because I support both of your projects.

**Comment by flightlessmango** [comment]
I've added GOverlay to the readme. Also semi-relevant, I added a GOverlay channel on discord
https://github.com/flightlessmango/MangoHud/commit/b9725ef82badc94bb6e0c095fb506a2bab3aea53
