### ISSUE TITLE
XNVCTRLIsNvScreen should call DefaultScreen for screen number

### ISSUE THREAD

**Issue by cthbleachbit** [flightlessmango/MangoHud#1152]
https://github.com/flightlessmango/MangoHud/blob/113912eb6b9ae0b08b2a1606a76aefcfb4d2007c/src/nvctrl.cpp#L28 mangohud is calling `XNVCTRLIsNvScreen` with `(":0", 0)`. `(":1", 1)` and so on. It seems like this does not always find the correct screen:

```
[2023-10-12 17:44:35.612] [MANGOHUD] [error] [nvctrl.cpp:55] XNVCtrl didn't find the correct display
```

My X11 display is at `:1` but screen `0`, thus mangohud will always fail to find a nv screen:
```
int main() {
        Display *d = XOpenDisplay(":1");
        auto ret = is_nv_screen(d, 0);
        std::cout << "Call with screen 0: " << ret << std::endl;
        ret = is_nv_screen(d, 1);
        std::cout << "Call with screen 1: " << ret << std::endl;
        return 0;
}

--------------

Call with screen 0: 1
Call with screen 1: 0
```

The screen number should be obtained by calling `DefaultScreen(Display *d)`, then pass this number to `XNVCTRLIsNvScreen`.

**Comment by flightlessmango** [comment]
fix merged #1153
