### ISSUE TITLE
Game's Not Starting in Steam Using LMDE 6 With Mangohud enabled And Installed

### ISSUE THREAD

**Issue by gunther6000** [flightlessmango/MangoHud#1158]
**Describe the bug**
Game's Not Starting in Steam Using LMDE 6 With Mangohud enabled

**List relevant hardware/software information**
- LMDE 6 Faye
- MangoHud 0.7.0
- GPU Advanced Micro Devices, Inc. [AMD/ATI] Navi 21 [Radeon RX 6800/6800 XT / 6900 XT]

**To Reproduce**
1. Go to Mangohud Folder in Terminal and Use the ./mangohud-setup.sh install script tells You it is Installed
2. Then Go To Steam Then put Mangohud %Command% in Any game 

**Expected behavior**
Games Wont start using the Mangohud %Command% on any game

**Comment by flightlessmango** [comment]
check that mangohud is actually installed, try using `mangohud` in terminal.
are you using flatpak verison of steam? you can't mix normal mangohud with flatpak applications

**Comment by gunther6000** [comment]
Not Using Flatpak i am using the script inside extracted folder from your github (https://github.com/flightlessmango/MangoHud/releases)
This is What it Said When put in what you said

ERROR: No program supplied

Usage: mangohud <program>

**Comment by flightlessmango** [comment]
install `vulkan-tools` package and try `mangohud vkcube` in a terminal.
Do this run and display mangohud?

**Comment by gunther6000** [comment]
I Fixed It The Flatpak Version of Steam Was The Problem i changed it to the deb version And It Worked in Vkcube Thanks For The Help.
