### ISSUE TITLE
Add VRAM temperatures

### ISSUE THREAD

**Issue by Bengt** [flightlessmango/MangoHud#1159]
**Describe the bug**

Currently, MangoHUD does not display the VRAM temperatures, although that is possible.

**List relevant hardware/software information**

- Linux Distribution: Ubuntu 22.04.3
- MangoHud version: 0.7.0
- GPU: RTX 3090

**To Reproduce**

1. Configure MangoHUD to show all values using `full`
2. Start an application using MangoHUD

**Expected behavior**

MangoHUD shows the temperature of the memory chips.

**Additional context**

There is a library providing the necessary functionality to read the sensors of the VRAM:

<https://github.com/olealgoritme/gddr6>

This works without setting the kernel boot flag under Ubuntu 22.04.3.

**Comment by flightlessmango** [comment]
I don't think this is a good way to go about it, I'd be much happier if nvidia could expose these metrics through NVML instead.

**Comment by Bengt** [comment]
I feel the same way. Requiring superuser rights for reading (!) VRAM temperatures seems very overkill.
