### ISSUE TITLE
Mangohud not working with Minetest

### ISSUE THREAD

**Issue by Potato-Waffles** [flightlessmango/MangoHud#1168]
**Describe the bug**
I am very new to this, I am sorry if its my incompetence getting in the way. I am trying to run Minetest with MangoHud. I already have it configured through the global config because of other apps I use it with (steam running games with Proton). I tried the following commands: 
- mangohud minetest
- mangohud --dlsym minetest
- MANGOHUD=1 mangohud minetest
- MANGOHUD_DLSYM=1 mangohud minetest
Nothing makes the mangohud appear. The terminal does not show anything. I also tried through steam by adding it as a non-steam game, trying to add the following commands one by one in "Launch options":
- mangohud %command%
- mangohud --dlsym %command%
- MANGOHUD=1 mangohud %command%
- MANGOHUD_DLSYM=1 mangohud %command%

Didn't work either. It does work with "glxgears" and "vkcubes", as well as with 2 steam games from windows. I also tried running minetest in both iGPU and dGPU (Intel and Nvidia respectively). Could it be, that I don't understand how to use it with OpenGL games? Could it be a problem with the config file? 

**List relevant hardware/software information**
- MangoHud Version: 0.7.0
- OS: Ubuntu 20.04.2 LTS x86_64
- CPU: Intel i7-10750H
- GPU: Intel UHD Graphics
- GPU: NVIDIA GeForce RTX 2060

**To Reproduce**
Steps to reproduce the behavior from terminal:
1. mangohud minetest (or any of the other commands listed above)
2. game launches without mangohud

Steps to reproduce the behavior from Steam:
1. Open Steam
3. "Add a Game" at the bottom left
4. In "Search list" type "minetest"
5. Put a tickmark on the left of the game
6. Click "Add Selected Programs"
7. Right click on the Minetest in Steam
8. Click "Properties"
9. Under "Launch Options" put "mangohud %command%" at the start (or any of the other commands listed above)
10. Minetest launches without MangoHud

**Expected behavior**
Minetest should launch with mangohud, showing what the global config tells it to.

**Screenshots**

Working example: Downwell (Running with Proton from Steam)
![image](https://github.com/flightlessmango/MangoHud/assets/54952106/7e80fe3d-e989-46e8-b581-05dce54d4f8c)

Minetest:
![image](https://github.com/flightlessmango/MangoHud/assets/54952106/26d07337-39f3-4482-a18a-1fda3efa3748)

**Comment by flightlessmango** [comment]
Works just fine here, with steam or otherwise.
I'd imagine it's either been fixed since 0.7 or there's something wrong with your mangohud install
![image](https://github.com/flightlessmango/MangoHud/assets/42713625/ca24d972-f089-47ab-a1c6-220f0c3446d2)

**Comment by Potato-Waffles** [comment]
Hmm, what linux distro are you using? Maybe it's not the installation of Mangohud, but rather my Ubuntu installation. I am having an issue with Steam as well due to not being able to update xdg-desktop-portal (drive select menu is empty). I will try to upgrade and I will get back with the results once I do.

**Comment by Potato-Waffles** [comment]
I upgraded to Ubuntu 22, reinstalled mangohud with apt and with "mangohud --dlsym minetest" I got an error "can't get libdl.so". Building from source fixed that issue, but there still is no hud in minetest. I also tried a few other linux-native games and no hud in them either. Steam games will have it though.

In 2 weeks I will be able to do a clean install of Ubuntu, hopefully that will fix the issue I am having.

**Comment by flightlessmango** [comment]
Are you using the build.sh script to install mangohud?

**Comment by Potato-Waffles** [comment]
Yes, I am.

**Comment by Potato-Waffles** [comment]
Ok, after installing Ubuntu 22 fresh and tinkering around I figured out why Minetest and many other games were not working - if they are installed through SNAP or the Snap Store, they refuse to work. Using APT package manager works fine.

**Comment by flightlessmango** [comment]
apps installed with snap, flatpak or other containerized systems require a specific mangohud for it.
Flatpak has a version of mangohud for flatpak apps, I don't think there is one for snap however

**Comment by Potato-Waffles** [comment]
Thank you for the insight! I did not find anything connected to MangoHUD and SNAP besides Steam when installed from SNAP. But Steam has support for mangohud build-in, so that is of no use. The solution is to get games from other package managers.
