### ISSUE TITLE
MangoHud ignoring graphs settings

### ISSUE THREAD

**Issue by DownloadFreeloader** [flightlessmango/MangoHud#1169]
**Describe the bug**
The overlay is not respecting the `graphs` settings in my .conf file. The only graph is the frametime.

**List relevant hardware/software information**
- Arch Linux
- MangoHud ver. 0.7.0-2
- 7900 XTX

**To Reproduce**
1. Go to `~/.config/MangoHud/MangoHud.conf`
2. Set `graphs` to `graphs=cpu_load,gpu_load`
3. Launch game with `mangohud %command%` parameter
4. See error (top right in this case in the screenshot)

**Expected behavior**
There would be a graph showing the current CPU and GPU loads.

**Screenshots**
This screenshot is with `graphs=cpu_load,gpu_load` present in my .conf file.
![Screenshot_20231118_093507](https://github.com/flightlessmango/MangoHud/assets/103989993/645b4aee-6c3d-4672-a639-a1e78c20c027)

**Additional context**
I tried having separate `graphs=cpu_load` and `graphs=gpu_load` in my .conf file to no avail. I also tried `graphs=vram` out of curiosity but there was no graph for that, either.

**Comment by flightlessmango** [comment]
should be resolved here 60779dda9a8c0a5419d8bccb47485a408a6506d1
