### ISSUE TITLE
MANGOHUD: XNVCtrl failed to load

### ISSUE THREAD

**Issue by witchymary** [flightlessmango/MangoHud#117]
After trying compiling the develop branch myself and using https://github.com/flightlessmango/MangoHud/issues/3#issuecomment-602748292, this error always pops up. I'm on arch and have libxnvctrl installed. I'm also pretty sure the library is working properly since nvidia-settings is displaying everything fine. 

Here's the output with vkcube:
```
$ mangohud vkcube
skipping config: /usr/bin/MangoHud.conf [ not found ]
parsing config: /home/mary/.config/MangoHud/vkcube.conf [ ok ]
MANGOHUD: XNVCtrl failed to load
```

**Comment by flightlessmango** [comment]
What hardware are we talking about? Is it a laptop with intel and nvidia graphics?

**Comment by witchymary** [comment]
It's a computer. I7 4770 and the gpu is a GTX 770.

**Comment by medusalix** [comment]
@witchymary You could try adding `printf("XNVCtrl dlopen failed: %s\n", dlerror());` after the call to `dlopen` (assuming you are able to compile it).

https://github.com/flightlessmango/MangoHud/blob/772ab6aa5b92bd64e6976693032eaec7273ff24f/src/loaders/loader_nvctrl.cpp#L28-L30

I've had a similar issue with NVML on Debian and I found out that I missed the 32-bit version of the libraries.

**Comment by witchymary** [comment]
> I've had a similar issue with NVML on Debian and I found out that I missed the 32-bit version of the libraries.
Oh, at first I thought that could've been the case, but assumed it wasn't since the 32-bit version of the library isn't in the repositories. I'll compile it again and with that bit of code just to be sure.

**Comment by weter11** [comment]
Problem with XNVCtrl, at least on Ubuntu is simple: by default it looking for libXNVCtrl.so which is absent under /usr/lib/x86_64-linux-gnu/. Don't know about other distros, but in that folder 2 files:  libXNVCtrl.so.0 which refers to libXNVCtrl.so.0.0.0.
To resolve problem I simply copy libXNVCtrl.so.0.0.0 with a name libXNVCtrl.so.

**Comment by NerosTie** [comment]
On Arch, the symbolic link is already here:

```
$ ll /usr/lib64/libXNVCtrl.  
libXNVCtrl.a          libXNVCtrl.so@        libXNVCtrl.so.0@      libXNVCtrl.so.0.0.0*
```

But XNVCtrl still fail to load with manghud.

**Comment by weter11** [comment]
Is libXNVCtrl.so a symbolic link? Because I copy library, not symbolic link.

**Comment by NerosTie** [comment]
Yes, it's a symbolic link:

```
$ ll libXNVCtrl.so
lrwxrwxrwx 1 root root 19 14 avril 01:04 libXNVCtrl.so -> libXNVCtrl.so.0.0.0
```

But I tested with a copy of the library and it doesn't work either.

**Comment by jackun** [comment]
@NerosTie did you build from latest `develop`? Start something simple like vkcube and post the output. Maybe X11 loader fails to load.

Also so it is clear:
* using X11?
* dedicated GPU, not an Optimus?

**Comment by NerosTie** [comment]
@jackun 

Tested with the `develop` tree and now I have this error (with vkcube):

`MANGOHUD: XNVCtrl didn't find the correct display`

Yes it's an Optimus GPU but I now it uses the Nvidia GPU (the Intel GPU is not compatible with Vulkan).

But if I try with the Intel GPU (glxgears, to use OpenGL), I have the same error...

**Comment by jackun** [comment]
Yea, it won't with optimus currently.

**Comment by NerosTie** [comment]
Why? Shouldn't XNVCtrl work the same way?

**Comment by jackun** [comment]
@NerosTie check if [this](https://github.com/flightlessmango/MangoHud/commit/86f8ebed30809d71ace443d540f485a1deff2dd9) latest commit works for you.

**Comment by NerosTie** [comment]
Tested and unfortunately, nothing has changed. The error is still the same.

**Comment by jackun** [comment]
What do you use to "launch" optimus? bumblebee/primusrun works for me with this hack. Dunno how the Nvidia prime deals with it.

**Comment by NerosTie** [comment]
With `__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia`.

Which is the official "PRIME Render Offload":

https://download.nvidia.com/XFree86/Linux-x86_64/435.17/README/primerenderoffload.html

(bumblebee is very outdated and unmaintained!)

**Comment by jackun** [comment]
Probably SoL then.

**Comment by witchymary** [comment]
Tested it again on the latest `develop` commit and it seems to be working as intended now. Closing the issue.
```
$ mangohud vkcube
skipping config: /usr/bin/MangoHud.conf [ not found ]
parsing config: /home/mary/.config/MangoHud/vkcube.conf [ ok ]
MANGOHUD: XNVCtrl is using display :0
```

**Comment by NerosTie** [comment]
It still doesn't work wit Optimus though.

**Comment by flightlessmango** [comment]
That specific issue is in #128
