### ISSUE TITLE
Mangohud not showing in Minecraft

### ISSUE THREAD

**Issue by plOloV2** [flightlessmango/MangoHud#1171]
I know there were closed issues with this problem, but solutions presented there don't work for me.  I tried lunching MC with this command `MANGOHUD_DLSYM=1 mangohud minecraft-launcher`, but with no success (Minecraft lunches but no mangohud overlay is present). I also tried modifying my `minecraft-launcher.desktop` to use `Exec=gamemoderun MANGOHUD_DLSYM=1 mangohud minecraft-launcher` but is also didn't helped. Anyone has ideas what can help me resolve the issue?

**Comment by Leopard1907** [comment]
https://github.com/flightlessmango/MangoHud/commit/cac664bef144e3cf476581caf55eff04ba36fbdc

Because that env var was removed.

Use `mangohud --dlsym`

**Comment by plOloV2** [comment]
It works now. Thanks!
