### ISSUE TITLE
MangoHud not working with games running through "Legendary" a game launcher

### ISSUE THREAD

**Issue by aboode95** [flightlessmango/MangoHud#1173]
As Epic Games don't provide a native launcher in Linux, we have to resort to using an alternative game launcher: [Legendary](https://github.com/derrod/legendary).

the way to run/launch a game through Legendary after installing the game is:
```
$ legendary launch <game_name>
```

I tried to run MangoHud with the game but unfortunately it doesn't work :\
```
$ mangohud legendary launch <game_name>
```

I also tried the following incase the game is using vulkan:
```
$ MANGOHUD=1 legendary launch <game_name>
```

but this isn't working. Is there something that I am doing wrong? Or is MangoHud not suppose to work like this (on a game laucher running a game)? 

System information:
OS: NixOS
CPU: i7 12th gen
Graphic: Nvidia 3050
RAM: 16 gb

**Comment by flightlessmango** [comment]
If the legendary is already running, then using environment variables with these commands won't have any effect at all

**Comment by flightlessmango** [comment]
I don't think this is a mangohud issue
