### ISSUE TITLE
Blacklist Epic Games Launher

### ISSUE THREAD

**Issue by shelterx** [flightlessmango/MangoHud#1175]
Perhaps there is no way to do this but I always get Mangohud to show up in Epic Games Launcher.
Epic Games Launcher IS blacklisted in Mangohud but it still shows up.
I suspect it's because they use unreal engine and there is no way around it.

Does anyone have a solution?

**Comment by flightlessmango** [comment]
It should work, it's possible that you don't have the correct name blacklisted.
Try using `exec_name` and see what mangohud thinks the launcher is called

**Comment by shelterx** [comment]
> It should work, it's possible that you don't have the correct name blacklisted. Try using `exec_name` and see what mangohud thinks the launcher is called

Thanks for pointing me in the right direction. EpicWebHelper.exe needs to be blacklisted too.

**Comment by shelterx** [comment]
I guess it's safe to add to blacklist.cpp if you want a permanent/default block.

**Comment by flightlessmango** [comment]
added here 7f439879e05c2d3fca6056cd1ea0866ddb8ff7ef
