### ISSUE TITLE
Crash under steam when auto-logging starts

### ISSUE THREAD

**Issue by Chais** [flightlessmango/MangoHud#1183]
**Describe the bug**
When starting any game from steam it will crash the moment auto-logging starts.

**List relevant hardware/software information**
- NixOS 24.05
- MangoHud version 0.7.0
- GPU AMD Radeon RX 7900 XTX

**To Reproduce**
1. Ensure `autostart_log` is set to a value n>0. 
2. Open steam
3. Right-click any game
4. Select 'Properties'
5. Set launch options to `mangohud %command%` or, if you're in Wayland, to 'gamescope -- mangohud %command%`
6. Start game
7. Game hangs and crashes after exactly n seconds.

**Expected behavior**
MangoHud starts logging after the configured amount of seconds.

**Additional context**
I don't get any error from MangoHud in the proton logs. Its last log message before the crash is
```
[MANGOHUD] [info] [blacklist.cpp:68] process 'steam.exe' is blacklisted in MangoHud
```
but that message is logged if auto-logging is disabled, too.  
Also starting logging manually, via hotkey, works just fine.

**Comment by flightlessmango** [comment]
Should be fixed here 1d357e17c8db600e8564e22ad135fe8972750bb9
