### ISSUE TITLE
MangoHUD not show any gpu graph

### ISSUE THREAD

**Issue by Augusto7743** [flightlessmango/MangoHud#1184]
Hello.
Thanks for reading my topic.
Using MangoHUD 0.6.5-1 installed from https://launchpad.net/~flexiondotorg/+archive/ubuntu/mangohud?field.series_filter=

GPU graphs details not are showed.
Only CPU and RAM.
MangoHUD not has access to gpu drivers ?
Here is Geforce GT 640 driver 470.
Any help ?

Have an nice day.

![01](https://github.com/flightlessmango/MangoHud/assets/21184987/2751906c-11fc-4135-a458-25555246d0aa)

**Comment by flightlessmango** [comment]
version 0.6.5 is ancient, please try the latest release before reporting issues
