### ISSUE TITLE
text_outline_color using BBGGRR and not RRGGBB

### ISSUE THREAD

**Issue by photosheep** [flightlessmango/MangoHud#1185]
**Describe the bug**
text_outline_color is using BBGGRR instead of RRGGBB

**List relevant hardware/software information**
Tested on three machines
- openSUSE Tumbleweed, MangoHud v0.7.0-2.2, Intel Alder Lake-UP4 GT2 [Iris XE Graphics]
- openSUSE Tumbleweed, MangoHud v0.7.0-2.2, AMD Cezanne [Radeon Vega Series / Radeon Mobile Series]
- Arch Linux, MangoHud v0.7.0-2, Intel HD Graphics 5500

**To Reproduce**
1. Run `MANGOHUD_CONFIG=text_color=ff0000,text_outline_color=0000ff mangohud vkcube`
2. See outline color match text color.

**Expected behavior**
Outline color appears as set.

Screenshot with enhanced thickness.
![2023-12-09_011137](https://github.com/flightlessmango/MangoHud/assets/51524685/bf594ac0-8860-4094-b0ab-1aadb29694fd)

**Comment by flightlessmango** [comment]
Should be fixed here c38132c964adbd858db074e7bb464f07e398f816
