### ISSUE TITLE
Total War Warhammer II not launching with MangoHud

### ISSUE THREAD

**Issue by rckwzrd** [flightlessmango/MangoHud#1191]
**Describe the bug**
Total War Warhammer II is not launching with MangoHud. The following launch options have been used without success:

- `PROTON_LOG=1 mangohud %command%`
- `MANGOHUD=1 PROTON_LOG=1 %command%`

I have attached logs for failing commands and a log for successful launch for reference.

**List relevant hardware/software information**
- PopOS 22.04
- MangoHud 0.7.0
- Radeon 7800XT, Mesa 23.2.1

Total War is running with GE-Proton8-25. MangoHud was installed from latest tar.gz release with `./mangohud-setup.sh install`. Steam was installed from apt as a `.deb`.

**To Reproduce**
1. add launch options above to game properties
2. click on play button in steam
3. play button turns blue and launcher does not appear
4. see error logs and success log

**Expected behavior**
The Total War launcher is expected to appear and then the game will launch with the configured MangoHud overlay.

Game will launch with this launch option: `PROTON_LOG=1`

**Screenshots**

**Additional context**
I have verified that MangoHud is working with Slay the Spire (proton) and Factorio (native). I suspect that the Total War `launcher.exe` is interfering with the `Warhammer2.exe`

---
[error_log_1_steam-594570.log](https://github.com/flightlessmango/MangoHud/files/13696274/error_log_1_steam-594570.log)
[error_log_2_steam-594570.log](https://github.com/flightlessmango/MangoHud/files/13696275/error_log_2_steam-594570.log)
[success_log_steam-594570.log](https://github.com/flightlessmango/MangoHud/files/13696277/success_log_steam-594570.log)

**Comment by flightlessmango** [comment]
No issue to run this game with current git and linux version, dx11 and dx12.
Try latest mangohud git to see if this is an issue that's been resolved since 0.7

**Comment by rckwzrd** [comment]
Is latest Git in Master branch or another location?

**Comment by rckwzrd** [comment]
Installed current git. Game and mangohud now run as expected. Closing the issue...
