### ISSUE TITLE
Text is now blurry and ugly.

### ISSUE THREAD

**Issue by AlawamiAZ** [flightlessmango/MangoHud#1192]
**Describe the bug**
Recently the text became blurry with ugly black outline. it wasn't before (few months back).

**List relevant hardware/software information**
- Fedora
- 0.7; Flatpak org.freedesktop.Platform.VulkanLayer.MangoHud//22.08
- RTX 2080, Prop driver

-Only happens with bright background, so i think it has smothing to do with text outline.
![Screenshot from 2023-12-18 00-59-09](https://github.com/flightlessmango/MangoHud/assets/85796614/1a5d808c-c51b-426a-b28d-435188e760fe)

**Comment by flightlessmango** [comment]
Since 0.7 there is a text outline that is enabled by default, you can disable it with `text_outline=false`
as for blurry, I'm not seeing it
