### ISSUE TITLE
mangohud not start (symbol lookup error)

### ISSUE THREAD

**Issue by FGYada1984** [flightlessmango/MangoHud#1193]
Everything was working fine, after a routine system update, the games in lutris didn't start opening anymore and when I went to read the logs the problem was precisely the failure that is occurring with the loading of mangohud.

After deactivating it, the games started loading normally again.

when i try to load any game with it or try to load goverlay, the error message it displays is:
`
/usr/lib64/goverlay: symbol lookup error: /usr/lib64/mangohud/libMangoHud_opengl.so: undefined symbol: _ZN6spdlog7details7log_msgC1ENS_10source_locEN3fmt3v1017basic_string_viewIcEENS_5level10level_enumES6_`

- openSUSE Tumbleweed x86_64 (Kernel: 6.6.6-1-default)
- MangoHud version: 0.7.0-2.2
- NVIDIA GeForce RTX 2070 SUPER

**Comment by flightlessmango** [comment]
The error says the `goverlay` library is failing to find a symbol in the mangohud library.
Which doesn't make sense? I don't think there is a goverlay library?
Either way I recon this is a goverlay issue rather than a mangohud one

**Comment by FGYada1984** [comment]
maybe i explained it wrong, if that's what it was, i'm sorry, but it happens with any program or game that i try to load mangohud, i'll give another example in an attempt to get help, when i try to use mangohud with vkube it gives the same error: 
```
vkcube: symbol lookup error: /usr/lib64/mangohud/libMangoHud_opengl.so: undefined symbol: _ZN6spdlog7details7log_msgC1ENS_10source_locEN3fmt3v1017basic_string_viewIcEENS_5level10level_enumES6_

```
or when I try to run any game on lutris that has mangohud enabled, it gives the following error:


```
lutris-wrapper: Automobilista 2
Started initial process 31761 from gamemoderun mangohud /home/yada/.local/share/lutris/runners/wine/wine-ge-8-25-x86_64/bin/wine /home/yada/Games/Lutris/drive_c/Games/Automobilista 2/AMS2AVX.exe
Start monitoring process.
env: symbol lookup error: /usr/lib64/mangohud/libMangoHud_opengl.so: undefined symbol: _ZN6spdlog7details7log_msgC1ENS_10source_locEN3fmt3v1017basic_string_viewIcEENS_5level10level_enumES6_
Monitored process exited.
Initial process has exited (return code: 32512)
All processes have quit
Exit with return code 32512

```


maybe it's not a problem specific to mangohud, I'm just looking for an idea of how to solve it.

**Comment by flightlessmango** [comment]
mangohud needs to be recompiled against the current spdlog you're using

**Comment by flightlessmango** [comment]
if mangohud is supplied by the OS repo, then that's where the bug is, probably.

**Comment by FGYada1984** [comment]
yes, it came from the official opensuse repository, I really don't know how to do this recompile step, I even tried the script, but anyway, I'll be without it for a while, thanks for your attention.

**Comment by FGYada1984** [comment]
just to inform any users who might be having the same problem as me, I managed to solve it by downgrading libspdlog1_12 and libspdlog1_12-32bit, in my case I did it directly via Yast.
