### ISSUE TITLE
only one param works when set with MANGOHUD_CONFIG argument in lutris

### ISSUE THREAD

**Issue by esanscoopsers** [flightlessmango/MangoHud#1194]
trying to limit the fps of an application and also have no mangohud display but whichever i put first in the params overides the other. is no_display and fps_limit not compatible with each other? as stated in the title i am setting these configs with the MANGOHUD_CONFIG argument in lutris

**Comment by flightlessmango** [comment]
Can you show exactly what your option looks like

**Comment by flightlessmango** [comment]
Works fine for me
![image](https://github.com/flightlessmango/MangoHud/assets/42713625/00f54eb9-e6a0-47b6-854c-4f358457d4f0)
