### ISSUE TITLE
Some Steam Deck OLED overlay elements have missing values

### ISSUE THREAD

**Issue by matte-schwartz** [flightlessmango/MangoHud#1197]
**Describe the bug**
Some of the hardware values for Steam Deck OLED are not working correctly on several Fedora-based distros running up-to-date kernels. I've included screenshots where you can see the CPU wattage and temp is 0. There was also a regression when built from source 10 days ago where Preset 2 overlay in Steam is missing the frame graph. A version built 14 days ago did not have this issue.

**List relevant hardware**
- both Nobara + Bazzite (6.6.7-203)
- MangoHud 0.7.0, several recent revisions built from source in the Nobara and Bazzite COPRs.
- AMD VanGogh/Galileo chipset

**To Reproduce**
1. No steps necessary to reproduce the missing values. For the frame graph in Preset 2, downgrading from 0.7.0-9 (10 days old) to 0.7.0-8 (14 days old) restores the missing graph.

**Screenshots**
Missing values: 
![IMG_0424](https://github.com/flightlessmango/MangoHud/assets/136293710/77bff051-0956-4839-b4f9-f2e2ab9f7a7e)

Missing graph: 
![IMG_0425](https://github.com/flightlessmango/MangoHud/assets/136293710/ab4fc617-fcab-4320-b43f-3998c06060ab)

**Additional context**
Please let me know if you'd like any logs or config files. I haven't touched anything. Thanks!

**Comment by flightlessmango** [comment]
The missing frame time graph should be fixed here 53281f3

CPU temp and watt being 0 should be fixed here 971791d5daf383d31d04603151336e66891e1941

**Comment by matte-schwartz** [comment]
I have rebuilt locally with these two additional commits.

Commit [53281f3](https://github.com/flightlessmango/MangoHud/commit/53281f3f2c4c34aa82256d41dce13ac7020d7d97) has successfully restored the Preset 2 graph.

Commit [971791d](https://github.com/flightlessmango/MangoHud/commit/971791d5daf383d31d04603151336e66891e1941) shows no change in CPU readings. I have also lost my GPU statistics, which were previously working correctly, with this commit. 

Here is a screenshot of my current Overlay Preset 4: 
![d36434f1-5cec-4372-8cff-219beb8c7de7](https://github.com/flightlessmango/MangoHud/assets/136293710/396fca9d-61c3-451e-929d-328baca72fbc)

Here is my current output of `mangohud vkcube`
```
matt@steamdeck-oled:~$ mangohud vkcube
[2023-12-23 17:03:13.918] [MANGOHUD] [error] [overlay_params.cpp:999] Failed to read presets file: '/home/matt/.config/MangoHud/presets.conf'
[2023-12-23 17:03:13.934] [MANGOHUD] [error] [cpu.cpp:530] Could not find cpu temp sensor location
Selected GPU 0: AMD Radeon Graphics (RADV VANGOGH), type: IntegratedGpu
```
I double-checked to make sure and it's definitely up-to-date with the source here since I can see the updated versions of those two files in my src directory.

**Comment by flightlessmango** [comment]
Can you upload a copy of `/sys/class/drm/card0/device/gpu_metrics` ?

**Comment by matte-schwartz** [comment]
Well I think we've found a major part of the issue: it doesn't exist. 

Instead, the only `gpu_metrics` file I could find is located at `/sys/class/drm/card1/device/gpu_metrics`  [Here](https://pixeldrain.com/u/iFsF2kJf) is a link to the gpu_metrics file.

I was doing some dmesg comparing of my own between SteamOS' latest kernel and Nobara's 6.6.7-203 a couple of hours ago after someone confirmed that other 6.6 and 6.7 kernels on different distros are having an identical issue with setting the display refresh rate and frame limit while in Game Mode. I found this difference between the two which now seems relevant to this specific MangoHud issue:

`[    6.148206] [drm] Initialized amdgpu 3.54.0 20150101 for 0000:04:00.0 on minor 0` on SteamOS
is
`[    0.901373] [drm] Initialized simpledrm 1.0.0 20200625 for simple-framebuffer.0 on minor 0` and `[    5.241008] [drm] Initialized amdgpu 3.54.0 20150101 for 0000:04:00.0 on minor 1` on Nobara.

This minor 0 (which I assume would get translated to card0 at some point?) does not seem to appear in my `/sys/class/drm/` folder at all.

I've shared my findings here with the Nobara + Bazzite devs via Discord. I've mostly just been the testing guinea pig for OLED support.

**Comment by matte-schwartz** [comment]
update: tried the kernel boot paramter `initcall_blacklist=simpledrm_platform_driver_init` which causes amdgpu to get initialized as card0 since it skips simpledrm. No change in MangoHud behavior. [Here](https://pixeldrain.com/u/SKWZ9iaX) is a link to `/sys/class/drm/card0/device/gpu_metrics` while it's showing up as card0.

**Comment by flightlessmango** [comment]
can you try this commit c8c987dadb44a545850638135a470ffd8975918f ?

**Comment by matte-schwartz** [comment]
Great stuff, we now have metrics across the board. 
![IMG_0447](https://github.com/flightlessmango/MangoHud/assets/136293710/e18a5c2b-d6ce-480b-a6ab-4a6be2a78669)
![IMG_0448](https://github.com/flightlessmango/MangoHud/assets/136293710/d100f9fe-d6fc-454c-903d-d6014f2419dd)
![IMG_0446](https://github.com/flightlessmango/MangoHud/assets/136293710/7eb7044a-5bde-4656-84d0-774540dc77d6)

Closing this issue as completed, but feel free to let me know if you’d like me to test any other commits down the road.
