### ISSUE TITLE
MangoHud not working with system running only on dGPU

### ISSUE THREAD

**Issue by nazdridoy** [flightlessmango/MangoHud#1198]
I've encountered an issue with MangoHud when running my Arch Linux system in exclusive NVIDIA mode on my laptop with NVIDIA Optimus. I use the Zen Kernel on the Plasma DE over Xorg. The system works perfectly with the dGPU, but MangoHud crashes when launching games or running applications like glxgears and vkcube.

## System Information

- **Operating System:** Arch Linux
- **Kernel:** Zen Kernel
- **Desktop Environment:** Plasma DE

## Issue Details

- **MangoHud Version:** Latest (as of [date])
- **Problem:** When launching games or running glxgears/vkcube with MangoHud, it results in a segmentation fault. The error message indicates an issue with NV-CONTROL and an "integer parameter out of range for operation."

### Steps to Reproduce

1. Set the system to NVIDIA mode (exclusive dGPU usage).
2. Launch any game or run glxgears/vkcube with MangoHud enabled.

### Expected Behavior

MangoHud should work seamlessly with the NVIDIA mode, allowing for monitoring while gaming or running GPU-intensive applications.

## Additional Information

- EnvyControl and Optimus-Manager were used to enable exclusive dGPU usage.
- NVIDIA X Server Settings works properly in NVIDIA mode but requires Hybrid mode for MangoHud to function.
- Downgrading MangoHud to version 0.6.9-1 resolves the issue.

## Reproduction Environment

- **MangoHud Version:** [Version causing the issue]
- **NVIDIA Driver Version:** [Your NVIDIA driver version]
- **Other Relevant Software Versions:** [Any other software versions relevant to the issue]

## Logs and Screenshots

- glxgears output with MangoHud:
`
[2023-12-02 19:19:21.823] [MANGOHUD] [info] [gl_renderer.cpp:422] GL version: 4.6
Running synchronized to the vertical refresh. The framerate should be
approximately the same as the monitor refresh rate.
X Error of failed request: BadValue (integer parameter out of range for operation)
Major opcode of failed request: 157 (NV-CONTROL)
Minor opcode of failed request: 27 ()
Value in failed request: 0x17
Serial number of failed request: 14
Current serial number in output stream: 14
[1] 4250 segmentation fault (core dumped) mangohud glxgears
`

- vkcube output with MangoHud:

`
Selected GPU 0: NVIDIA GeForce GTX 1660 Ti with Max-Q Design, type: DiscreteGpu
X Error of failed request: BadValue (integer parameter out of range for operation)
Major opcode of failed request: 157 (NV-CONTROL)
Minor opcode of failed request: 27 ()
Value in failed request: 0x17
Serial number of failed request: 14
Current serial number in output stream: 14
[1] 4323 segmentation fault (core dumped) mangohud vkcube
`

## Workaround

- Downgrading MangoHud to version 0.6.9-1 resolves the issue. Please investigate changes in newer versions that may be causing the problem.

Any assistance or guidance on resolving this issue would be greatly appreciated. Thank you!

**Comment by flightlessmango** [comment]
This issue should be resolved in 0.7.1 rc1
