### ISSUE TITLE
Can't build without nvidia-settings

### ISSUE THREAD

**Issue by EduFrazao** [flightlessmango/MangoHud#12]
Hi. I'm trying to build the master branch, and I got this error:
`eduardo MangoHud (master) $ ./build.sh install
# Checking Dependencies
# Unable to find distro information!
# Attempting to build regardless
The Meson build system
Version: 0.52.1
Source dir: /home/eduardo/Downloads/MangoHud
Build dir: /home/eduardo/Downloads/MangoHud/build/meson64
Build type: native build
Project name: mangohud
Project version: v1.0.0
C compiler for the host machine: ccache cc (gcc 9.2.0 "cc (Gentoo 9.2.0-r2 p3) 9.2.0")
C linker for the host machine: GNU ld.bfd 2.32
C++ compiler for the host machine: ccache c++ (gcc 9.2.0 "c++ (Gentoo 9.2.0-r2 p3) 9.2.0")
C++ linker for the host machine: GNU ld.bfd 2.32
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program python3 found: YES (/usr/bin/python3)
Checking if "GCC atomic builtins" compiles: YES 
Checking if "Supports timespec_get" compiles: YES 
Checking for function "bswap32" : YES 
Checking for function "bswap64" : YES 
Checking for function "clz" : YES 
Checking for function "clzll" : YES 
Checking for function "ctz" : YES 
Checking for function "expect" : YES 
Checking for function "ffs" : YES 
Checking for function "ffsll" : YES 
Checking for function "popcount" : YES 
Checking for function "popcountll" : YES 
Checking for function "unreachable" : YES 
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Run-time dependency x11 found: YES 1.6.9
Compiler for C supports arguments -Werror=implicit-function-declaration: YES 
Compiler for C supports arguments -Werror=missing-prototypes: YES 
Compiler for C supports arguments -Werror=return-type: YES 
Compiler for C supports arguments -Werror=incompatible-pointer-types: YES 
Compiler for C supports arguments -fno-math-errno: YES 
Compiler for C supports arguments -fno-trapping-math: YES 
Compiler for C supports arguments -Qunused-arguments: NO 
Compiler for C supports arguments -Wmissing-field-initializers: YES 
Compiler for C supports arguments -Wformat-truncation: YES 
Compiler for C supports arguments -fvisibility=hidden: YES 
Compiler for C++ supports arguments -Werror=return-type: YES 
Compiler for C++ supports arguments -fno-math-errno: YES 
Compiler for C++ supports arguments -fno-trapping-math: YES 
Compiler for C++ supports arguments -Qunused-arguments: NO 
Compiler for C++ supports arguments -Wnon-virtual-dtor: YES 
Compiler for C++ supports arguments -Wmissing-field-initializers: YES 
Compiler for C++ supports arguments -Wformat-truncation: YES 
Compiler for C++ supports arguments -Wpointer-arith: YES 
Compiler for C++ supports arguments -Wunused-variable: YES 
Compiler for C supports arguments -Woverride-init: YES 
Compiler for C supports arguments -Winitializer-overrides: NO 
Compiler for C++ supports arguments -fvisibility=hidden: YES 
Checking for function "dlopen" : NO 
Library dl found: YES
Library pthread found: YES
Program glslangValidator found: YES (/usr/bin/glslangValidator)
Compiler for C supports link arguments -Wl,-Bsymbolic-functions: YES 
Compiler for C supports link arguments -Wl,-z,relro: YES 
Build targets in project: 7
Found ninja-1.8.2 at /usr/bin/ninja
The Meson build system
Version: 0.52.1
Source dir: /home/eduardo/Downloads/MangoHud
Build dir: /home/eduardo/Downloads/MangoHud/build/meson32
Build type: native build
Project name: mangohud
Project version: v1.0.0
C compiler for the host machine: gcc -m32 (gcc 9.2.0 "gcc (Gentoo 9.2.0-r2 p3) 9.2.0")
C linker for the host machine: GNU ld.bfd 2.32
C++ compiler for the host machine: g++ -m32 (gcc 9.2.0 "g++ (Gentoo 9.2.0-r2 p3) 9.2.0")
C++ linker for the host machine: GNU ld.bfd 2.32
Host machine cpu family: x86
Host machine cpu: i686
Program python3 found: YES (/usr/bin/python3)
Checking if "GCC atomic builtins" compiles: YES 
Checking if "Supports timespec_get" compiles: YES 
Checking for function "bswap32" : YES 
Checking for function "bswap64" : YES 
Checking for function "clz" : YES 
Checking for function "clzll" : YES 
Checking for function "ctz" : YES 
Checking for function "expect" : YES 
Checking for function "ffs" : YES 
Checking for function "ffsll" : YES 
Checking for function "popcount" : YES 
Checking for function "popcountll" : YES 
Checking for function "unreachable" : YES 
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Run-time dependency x11 found: YES 1.6.9
Compiler for C supports arguments -Werror=implicit-function-declaration: YES 
Compiler for C supports arguments -Werror=missing-prototypes: YES 
Compiler for C supports arguments -Werror=return-type: YES 
Compiler for C supports arguments -Werror=incompatible-pointer-types: YES 
Compiler for C supports arguments -fno-math-errno: YES 
Compiler for C supports arguments -fno-trapping-math: YES 
Compiler for C supports arguments -Qunused-arguments: NO 
Compiler for C supports arguments -Wmissing-field-initializers: YES 
Compiler for C supports arguments -Wformat-truncation: YES 
Compiler for C supports arguments -fvisibility=hidden: YES 
Compiler for C++ supports arguments -Werror=return-type: YES 
Compiler for C++ supports arguments -fno-math-errno: YES 
Compiler for C++ supports arguments -fno-trapping-math: YES 
Compiler for C++ supports arguments -Qunused-arguments: NO 
Compiler for C++ supports arguments -Wnon-virtual-dtor: YES 
Compiler for C++ supports arguments -Wmissing-field-initializers: YES 
Compiler for C++ supports arguments -Wformat-truncation: YES 
Compiler for C++ supports arguments -Wpointer-arith: YES 
Compiler for C++ supports arguments -Wunused-variable: YES 
Compiler for C supports arguments -Woverride-init: YES 
Compiler for C supports arguments -Winitializer-overrides: NO 
Compiler for C++ supports arguments -fvisibility=hidden: YES 
Checking for function "dlopen" : NO 
Library dl found: YES
Library pthread found: YES
Program glslangValidator found: YES (/usr/bin/glslangValidator)
Compiler for C supports link arguments -Wl,-Bsymbolic-functions: YES 
Compiler for C supports link arguments -Wl,-z,relro: YES 
Build targets in project: 7
Found ninja-1.8.2 at /usr/bin/ninja
ninja: Entering directory `build/meson32'
[1/25] Generating overlay.vert.spv.h with a custom command.
../../src/overlay.vert
[2/25] Generating overlay.frag.spv.h with a custom command.
../../src/overlay.frag
[11/25] Compiling C++ object 'src/25a6634@@MangoHud@sha/overlay.cpp.o'.
FAILED: src/25a6634@@MangoHud@sha/overlay.cpp.o 
g++ -m32 -Isrc/25a6634@@MangoHud@sha -Isrc -I../../src -I../../include -I../../modules/Vulkan-Headers/include -I../../modules/ImGui/src -I. -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++14 -O3 -Werror=return-type -fno-math-errno -fno-trapping-math -Wno-non-virtual-dtor -Wno-missing-field-initializers -Wno-format-truncation -Wno-pointer-arith -Wno-unused-variable -fPIC -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS '-DPACKAGE_VERSION="v1.0.0"' -DNDEBUG -D_GNU_SOURCE -DHAVE_PTHREAD -DUSE_GCC_ATOMIC_BUILTINS -DHAVE_TIMESPEC_GET -DHAVE___BUILTIN_BSWAP32 -DHAVE___BUILTIN_BSWAP64 -DHAVE___BUILTIN_CLZ -DHAVE___BUILTIN_CLZLL -DHAVE___BUILTIN_CTZ -DHAVE___BUILTIN_EXPECT -DHAVE___BUILTIN_FFS -DHAVE___BUILTIN_FFSLL -DHAVE___BUILTIN_POPCOUNT -DHAVE___BUILTIN_POPCOUNTLL -DHAVE___BUILTIN_UNREACHABLE -fvisibility=hidden -DVK_USE_PLATFORM_XLIB_KHR -MD -MQ 'src/25a6634@@MangoHud@sha/overlay.cpp.o' -MF 'src/25a6634@@MangoHud@sha/overlay.cpp.o.d' -o 'src/25a6634@@MangoHud@sha/overlay.cpp.o' -c ../../src/overlay.cpp
In file included from ../../src/cpu_gpu.h:18,
                 from ../../src/overlay.cpp:49:
../../src/nvctrl.h:2:10: fatal error: NVCtrl/NVCtrl.h: No such file or directory
    2 | #include "NVCtrl/NVCtrl.h"
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
[22/25] Compiling C++ object 'src/25a6634@@MangoHud@sha/cpu.cpp.o'.
ninja: build stopped: subcommand failed.
ninja: Entering directory `build/meson64'
[5/25] Generating overlay.frag.spv.h with a custom command.
../../src/overlay.frag
[6/25] Generating overlay.vert.spv.h with a custom command.
../../src/overlay.vert
[23/25] Compiling C++ object 'src/25a6634@@MangoHud@sha/overlay.cpp.o'.
FAILED: src/25a6634@@MangoHud@sha/overlay.cpp.o 
ccache c++ -Isrc/25a6634@@MangoHud@sha -Isrc -I../../src -I../../include -I../../modules/Vulkan-Headers/include -I../../modules/ImGui/src -I. -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++14 -O3 -Werror=return-type -fno-math-errno -fno-trapping-math -Wno-non-virtual-dtor -Wno-missing-field-initializers -Wno-format-truncation -Wno-pointer-arith -Wno-unused-variable -fPIC -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS '-DPACKAGE_VERSION="v1.0.0"' -DNDEBUG -D_GNU_SOURCE -DHAVE_PTHREAD -DUSE_GCC_ATOMIC_BUILTINS -DHAVE_TIMESPEC_GET -DHAVE___BUILTIN_BSWAP32 -DHAVE___BUILTIN_BSWAP64 -DHAVE___BUILTIN_CLZ -DHAVE___BUILTIN_CLZLL -DHAVE___BUILTIN_CTZ -DHAVE___BUILTIN_EXPECT -DHAVE___BUILTIN_FFS -DHAVE___BUILTIN_FFSLL -DHAVE___BUILTIN_POPCOUNT -DHAVE___BUILTIN_POPCOUNTLL -DHAVE___BUILTIN_UNREACHABLE -fvisibility=hidden -DVK_USE_PLATFORM_XLIB_KHR -MD -MQ 'src/25a6634@@MangoHud@sha/overlay.cpp.o' -MF 'src/25a6634@@MangoHud@sha/overlay.cpp.o.d' -o 'src/25a6634@@MangoHud@sha/overlay.cpp.o' -c ../../src/overlay.cpp
In file included from ../../src/cpu_gpu.h:18,
                 from ../../src/overlay.cpp:49:
../../src/nvctrl.h:2:10: fatal error: NVCtrl/NVCtrl.h: No such file or directory
    2 | #include "NVCtrl/NVCtrl.h"
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
cp: cannot stat 'build/release/usr/lib32/libMangoHud.so': No such file or directory
cp: cannot stat 'build/release/usr/lib64/libMangoHud.so': No such file or directory
cp: cannot stat 'build/release/usr/share/vulkan/implicit_layer.d/mangohud.json': No such file or directory
cp: cannot stat 'build/release/usr/share/vulkan/implicit_layer.d/mangohud.json': No such file or directory
sed: can't read build/package/MangoHud/.local/share/vulkan/implicit_layer.d/mangohud32.json: No such file or directory
sed: can't read /home/eduardo/.local/share/vulkan/implicit_layer.d/mangohud32.json: No such file or directory
sed: can't read /home/eduardo/.local/share/vulkan/implicit_layer.d/mangohud64.json: No such file or directory
`

I belive that this is related to nvidia-settings stuff, that I really don't have, as I use an AMD GPU. Is this a mandatory dependency?

**Comment by flightlessmango** [comment]
That was left in by accident, it should be fixed now. Can you pull latest master and try again please?

**Comment by jackun** [comment]
Do `git fetch origin master` and  `git reset --hard origin/master` if it is stubborn.

**Comment by EduFrazao** [comment]
@flightlessmango its working now! Thank you for your fast response. Can I close this bug?
