### ISSUE TITLE
Steam games not using the set `font_file=`

### ISSUE THREAD

**Issue by Kagukara** [flightlessmango/MangoHud#1201]
**Describe the bug**
Games launched via Steam (including non-steam games) aren't using the set font in `font_file=` of the config file. 

I have tested this with GW2, which I can launch via both Steam and Bottles. Via Steam it doesn't use the set font, but via Bottles it does.

Adding GW2 via non-steam game also doesn't use the set font.

**List relevant hardware/software information**
- OS: Arch Linux
- MangoHud version: v0.7.1-rc1-4-g971791d
- GPU: AMD Radeon RX 7900 XTX (radeonsi, navi31, LLVM 18.0.0, DRM 3.54, 6.6.8-arch1-1)
- GPU Driver: 4.6 Mesa 24.0.0-devel (git-551924aa87)

**To Reproduce**
1. Add or make sure `mangohud %command%` is set in the 'Launch Options' of a Steam game.
2. Add or make sure a custom font is set for `font_file=` in your `MangoHud.conf` file.
3. Launch the Steam game
4. Check MangoHud
5. Close game
6. Launch a game not using Steam with `mangohud %command%` set in whatever you're using to launch the game.
7. Check MangoHud
8. Close game

**Expected behavior**
I expect the font I set in `font_file=` of my config file to work for all games no matter the launcher.

**Screenshots**
Guild Wars 2 MangoHud via Steam
![capture_2023-12-26_02-13-39](https://github.com/flightlessmango/MangoHud/assets/43391109/22bd1126-6091-4d6c-92f6-ca46200de9cf)

Guild Wars 2 MangoHud via Bottles
![capture_2023-12-26_02-17-03](https://github.com/flightlessmango/MangoHud/assets/43391109/ef452f80-c261-4af6-9e2c-3eede53c4d9d)

**Comment by flightlessmango** [comment]
This is likely because the steam runtime container does not have access to the font file.
Try placing it somewhere in your home directory instead

**Comment by Kagukara** [comment]
Placing the font file in my home directory and didn't fix it.

**Comment by Kagukara** [comment]
Ignore me, I had the wrong name. That worked thank you.
