### ISSUE TITLE
[Request] [Package the app as appimage]

### ISSUE THREAD

**Issue by Twig6943** [flightlessmango/MangoHud#1203]
title.

**Comment by Leopard1907** [comment]
How would you pack an appimage Mangohud and what purpose would it serve?

Normal Mangohud works for Appimage apps anyways.

**Comment by flightlessmango** [comment]
mangohud is a shared library, it doesn't make any sense as an appimage.
mangoapp is only designed for gamescope and I don't think there is an appimage for gamescope, so I don't see the purpose there either
