### ISSUE TITLE
NVML has non-free license

### ISSUE THREAD

**Issue by stephanlachnit** [flightlessmango/MangoHud#121]
I already mentioned this in #34, but now I'm quite sure that `nvml.h` is not free software (the [Debian package](https://packages.debian.org/unstable/libnvidia-ml-dev) is in non-free). Including it in this git repo is probably questionable, but I guess no-one cares. Besides, it makes it way harder to be included in distro since they need to evaluate the license. Here are two possible solutions:

1. Just use XNVCtrl instead (if possible, I don't know weather the features are similar), the source code is licensed under MIT.
2. Just don't import `nvml.h` in this git repo and use the version that's shipped with the distro. On Debian based systems that's `libnvidia-ml-dev`, on arch it's in the `cuda` package. Don't know how to search for Fedora, Solus or Suse packages. Maybe I can combine this with some sneaky wrap subproject power to still grab the source on distros that don't have it properly packed (like arch).

**Comment by flightlessmango** [comment]
Would it work to have a build option that excludes nvml and uses nvctrl instead?

**Comment by stephanlachnit** [comment]
That would be good, but `nvml.h` shouldn't be in the source tarball at all.
I can write a script that releases two source tarballs, one with nvml and one without it, maybe I can even combine it with wrap that makes it even simpler.
I will look into it and create a PR.

**Comment by stephanlachnit** [comment]
Another question, all the `meson.build` files are licensed with Intel as copyright owner. Is that intended?

**Comment by jackun** [comment]
> Another question, all the meson.build files are licensed with Intel as copyright owner. Is that intended?

"Left" over from Mesa vulkan layer. Probably can be change with all these changes?

**Comment by stephanlachnit** [comment]
> "Left over" from Mesa vulkan layer. Probably can be changed with all these changes?

I guess, can you change it? Or just remove it, I don't think a meson file needs a copyright disclaimer anyway. Would make the copyright file for Debian a bit easier.

**Comment by stephanlachnit** [comment]
@flightlessmango sorry to come back at this:
> Would it work to have a build option that excludes nvml and uses nvctrl instead?

Would that still be possible? I imagine something like:
```meson
option('use_nvml', type : 'combo', value : 'true', combo: ['true', 'system', 'false'])
```

I would like to disable NVML for the Debian build and use XNVCtrl instead since XNVCtrl doesn't have any dependencies and has a free license.
