### ISSUE TITLE
Toggling `fps_limit` only works if values follow ascending order

### ISSUE THREAD

**Issue by purplebar0** [flightlessmango/MangoHud#1212]
**Describe the bug**
Setting the `MANGOHUD_CONFIG` environment variable (or values inside the configuration file) to this results the value being stuck at 60 no matter how many times the toggle FPS limit button is pressed:
```
MANGOHUD_CONFIG=fps_limit='60\,0',toggle_fps_limit=F10
```

It appears that this issue occurs if the list of numbers does not follow ascending order, since combinations like `60,10000` fail the same way.

**List relevant hardware/software information**
- Linux Distribution: Artix Linux 6.7.0-zen3-1-zen
- MangoHud version: 0.7.0-2
- GPU: Radeon RX 6600 XT

**To Reproduce**
1. Set `fps_limit` such that the values don't follow ascending order, and set a `toggle_fps_limit` key
2. Enter the game
3. Toggle the values using the toggle key
4. Some values are ignored

**Expected behavior**
All values, no matter their order, are to be switched to by repeatedly pressing the `toggle_fps_limit` key.

**Additional context**
In GTA IV (v1.0.7.0), FPS has to be capped when the game initially starts to avoid a rendering crash, so I had to settle for a workaround, which is to set it to the highest value the game seems to not crash on (ex. `1500,60`).

**Comment by flightlessmango** [comment]
Does this work as expected outside of steam, using vkcube/glxgears for example?

**Comment by purplebar0** [comment]
> Does this work as expected outside of steam, using vkcube/glxgears for example?

Oddly enough, it does.

**Comment by flightlessmango** [comment]
Actually it works in steam on my end, might have been fixed since 0.7.0

**Comment by flightlessmango** [comment]
reopen if still an issue
