### ISSUE TITLE
error report:  [overlay_params.cpp:145] Unrecognized key: '=Shift_L'

### ISSUE THREAD

**Issue by kamikaze211** [flightlessmango/MangoHud#1213]
**Describe the bug**
When using goverlay to save mangohud configuration, it takes over 2 minutes to complete, and the terminal will give an error report like this:
[MANGOHUD] [error] [overlay_params.cpp:145] Unrecognized key: '=Shift_L'

**List relevant hardware/software information**
- Linux Distribution: Archlinux
- MangoHud version : 0.7.1.rc2-1
- GPU : AMD RX6600XT

**To Reproduce**
1. Open goverlay in terminal
2. Click on 'save'
3. Goverlay will lost response
4. See error in terminal : [MANGOHUD] [error] [overlay_params.cpp:145] Unrecognized key: '=Shift_L'
5. After about 2 minutes, the configuration file will be saved

**Expected behavior**
I also write the question on the page of goverlay
https://github.com/benjamimgois/goverlay/issues/56#issuecomment-1902722272

**Comment by flightlessmango** [comment]
This doesn't seem related to mangohud

**Comment by kamikaze211** [comment]
> This doesn't seem related to mangohud

Thank you for replying.
It seems to be a Goverlay bug.
https://github.com/benjamimgois/goverlay/issues/87
