### ISSUE TITLE
How to show Percentiles without having to log them in (1%, 97% or Adjustables)

### ISSUE THREAD

**Issue by luisalvarado** [flightlessmango/MangoHud#1217]
This is not a bug, but a question or request for information. How can I show the 1%, 97% or basically set the percentiles I want to show without having to log them in. What I am trying to do is edit the current setup (Horizontal) I have at https://www.youtube.com/@xtremelinux so that it shows the graph but also shows the Percentiles next to it. Very similar to the tool that is used on Windows. Thank you.

PS: My current setting is this:

MANGOHUD_CONFIG=output_folder=/home/luis/mangohud-logs,horizontal,horizontal_stretch,frame_timing=off,frametime=off,font_size=56,gpu_name,resolution gamemoderun mangohud %command%

**Comment by flightlessmango** [comment]
Have a look at `fps_metrics` in readme, it's a new feature coming in 0.7.1

**Comment by luisalvarado** [comment]
@flightlessmango 

I just read it, you blew my mind, so one last question, this would be used like this:

MANGOHUD_CONFIG=output_folder=/home/luis/mangohud-logs,horizontal,horizontal_stretch,frame_timing=off,frametime=off,font_size=56,gpu_name,resolution,fps_metrics=0.001,0.97,avg gamemoderun mangohud %command%

So that it would show

1%
97%
AVG

Correct?

For the 0.7.1, I also read that the comma separated values should use + since the comma is used as a parameter separator, meaning, I should do it like this then

MANGOHUD_CONFIG=output_folder=/home/luis/mangohud-logs,horizontal,horizontal_stretch,frame_timing=off,frametime=off,font_size=56,gpu_name,resolution,fps_metrics=0.001+0.97+avg gamemoderun mangohud %command%

I ask because the documentation still says this:

![image](https://github.com/flightlessmango/MangoHud/assets/29236/d984c08c-ff84-456d-a32a-cc2068477e00)


To be honest, I want to create a better video about mangohud. The one I did was this one https://www.youtube.com/watch?v=5D2lpPFj-Fw but I really feel mangohud needs a much better video explaining in a more flexible way how to set it up, including using the overlay, but also easily knowing where to edit the mangohud configuration, custom parameters as seen above, which parameters overlap each other and more. As another developer I understand many things involved here but the public will not easily understand it, so maybe I can shed some light.
