### ISSUE TITLE
[Feature Request] Add option to render text using vectors

### ISSUE THREAD

**Issue by livingsilver94** [flightlessmango/MangoHud#1218]
In MSI Afterburner you have "Vector 2D" and "Vector 3D" options to render text, plus "Raster 3D". Raster 3D is basically what MangoHud uses, that is a font that eventually gets scaled, antialiased, etc. Vectors are instead simple glyphs with no particular features like ligatures, curves, serifs and whatnot. Just straight lines.

While that may sound dull, I think vector text is **much** more readable, especially when scaled down and with an outline applied. It doesn't get jagged on low-DPI screens (like mine) and I think it's less distracting while gaming since it's simpler geometry.

I'd really love to see vector text available in MangoHud for better readability. I'm not particularly knowledgeable in 3D graphics but I think it's "just" a fragment shader in its implementation.

**Comment by flightlessmango** [comment]
We use ImGui to render the hud, so it would have to be implemented there rather than in mangohud
