### ISSUE TITLE
How to reset the ftp metrics

### ISSUE THREAD

**Issue by luisalvarado** [flightlessmango/MangoHud#1220]
When recording a game for YouTube, I might want to be fair and only show stats for ingame play time instead of loading the game, game intro, game menu, etc. How can I reset the stats when using ftp metrics so that the public sees the proper stats for the game.

**Comment by flightlessmango** [comment]
Added a keybind for resetting fps metrics 4969eed348959536f02c050aee3a8d23d018692b
