### ISSUE TITLE
cpu_mhz showing highest instead of AVG

### ISSUE THREAD

**Issue by luisalvarado** [flightlessmango/MangoHud#1221]
This is using 0.7.1 current commit. When run like this

MANGOHUD_CONFIG=output_folder=/home/luis/mangohud-logs,horizontal,horizontal_stretch,font_size=56,engine_short_names,gpu_name,gpu_power,cpu_mhz,cpu_temp,resolution,fps_metrics=0.001+0.01+0.97+avg gamemoderun mangohud %command%

It shows the highest CPU clock instead of the average one. This is on a 13900k which has multiple cores (Hybrid)

![image](https://github.com/flightlessmango/MangoHud/assets/29236/a0b71fcf-75b4-42b5-9e8c-00608bd936a0)

**Comment by flightlessmango** [comment]
This behavior is consistent with how afterburner displays the cpu clock.
I don't think we want to change it

**Comment by luisalvarado** [comment]
> This behavior is consistent with how afterburner displays the cpu clock. I don't think we want to change it

Thank you, but there is no way of showing AVG? Just asking, no need to code anything extra.
