### ISSUE TITLE
ASUS Temperature not read

### ISSUE THREAD

**Issue by luisalvarado** [flightlessmango/MangoHud#1222]
I did the whole bug report wrong here, sorry. Here is the original message from

https://github.com/flightlessmango/MangoHud/commit/d30cf162c15bfabfddd456ceb48a6d3848fa7098

Looks like after this update, on the Asus Z790 Hero the CPU Temp does not show anymore. It shows as 0 always. If I rollback to https://github.com/flightlessmango/MangoHud/commit/3cee6f15ded1b086333738e2388eb1d10dce9ba6 then it works correctly.

**Comment by flightlessmango** [comment]
I'm not sure why this changed caused an issue.
I also have an asus z790 with the module `nct6798` and it appears to work correctly

**Comment by luisalvarado** [comment]
@flightlessmango Okay let me provide the specs if it helps. I am on Ubuntu 23.10 with the following:

![image](https://github.com/flightlessmango/MangoHud/assets/29236/a60e51d0-6a87-48ec-b1eb-5ca7f5bb6a37)

Running sensors shows this:

![image](https://github.com/flightlessmango/MangoHud/assets/29236/5e52ad6c-a6e8-42a6-bbb1-fc386dc324b1)

![image](https://github.com/flightlessmango/MangoHud/assets/29236/b5786051-e06b-47f6-a3c0-573394bb7b87)


![image](https://github.com/flightlessmango/MangoHud/assets/29236/41600524-1d5a-4a4f-8ae4-dde4189265a2)

Is there anything else I can put here as info to provide more relevant data?

**Comment by flightlessmango** [comment]
Coretemp should already have been used for cpu temp, this change shouldn't have changed anything

**Comment by luisalvarado** [comment]
> Coretemp should already have been used for cpu temp, this change shouldn't have changed anything

Apologies because I  do not know what you want me to reply now. All I am reporting is, before the commit it showed, after it did not.

**Comment by luisalvarado** [comment]
I could do a video if that helps?

**Comment by luisalvarado** [comment]
Okay here is the video, I did a git hard on the commit and then the most recent commit to show you. Let me know if I did something wrong (Please wait like 15 minutes for the video to show properly)

https://www.youtube.com/watch?v=LuFixCwIwWU

**Comment by flightlessmango** [comment]
Resetting fps metrics is F10 by default
This commit should resolve the cpu temp issue fc54f48257e011a629487e2f4b965c90355d9c9d

**Comment by luisalvarado** [comment]
@flightlessmango Yes sir, the temperature is fixed!. Thank you a lot.

In regards to resetting the FPS Metrics, the only "issue" if we can call it that is the following behavior. Let us say we initialize a game and I have it like this setup in the beginning:

This is  5 seconds into the game

![image](https://github.com/flightlessmango/MangoHud/assets/29236/4c4240d1-c628-464d-844d-b69bedb6cadc)


This is 20 seconds into the game

![image](https://github.com/flightlessmango/MangoHud/assets/29236/804e4297-310b-4938-ba90-2b44cf48a5d7)


This is about 40 seconds into the game

![image](https://github.com/flightlessmango/MangoHud/assets/29236/4656bcf4-f310-42dc-8510-0c14ca404b7a)


As you can see between each image, the 1% and 0.1% were not updated till, I would guess, there was enough data to fill them in. Like it needed X amount of time to start showing data for them. This makes sense, since I would need more data to properly provide a 1% FPS stat and even more time to provide a 0.1% FPS stat. Up to this point everything is fine.

The problem is when I try to reset by pressing SHIFT + F10, every time I press it it sets all of them to 0 FPS, which is good, but then they go back to their original values. Here are two images one second apart:

![image](https://github.com/flightlessmango/MangoHud/assets/29236/60add9c5-e334-40a3-ad8c-e440d6b39b56)

![image](https://github.com/flightlessmango/MangoHud/assets/29236/c34d8d9c-d19e-4697-89b3-7a88fc1692db)

It immediately starts filling in the 1%  and 0.1% even though it needed more data before starting to show them.

If you like I can do another video to show it by pressing SHIFT + F10 multiple times?

**Comment by luisalvarado** [comment]
@flightlessmango Hi friend, did the above make sense. Do you feel it is okay or did I find an error with the resetting?

**Comment by flightlessmango** [comment]
This should resolve the issue 48d84262cd21ae3916e2d9713b9f1a223190b1a6.
It should fill in the metrics right away now from the start and when resetting

**Comment by luisalvarado** [comment]
Apologies, just noticed this message. I am testing this out ASAP!
