### ISSUE TITLE
AMD GPU 0% load, CPU power 0 W, VRAM 0.0 GB

### ISSUE THREAD

**Issue by Motor7724** [flightlessmango/MangoHud#1223]
The HUD is not displaying any values for GPU load, CPU power, or VRAM. This happens using Steam, Ryujinx, and Yuzu. CoreCtrl correctly displays these values.

- Ubuntu 22.04.3 LTS, Kernel 6.5.0, Mesa 23.3.3
- MangoHud version 0.6.5-2
- GPU AMD RX 7600
- CPU AMD R5 5600G

**Expected behavior**
The GPU load, CPU power, and VRAM usage should all be shown.

**Screenshots**
![Screenshot from 2024-02-02 16-00-59](https://github.com/flightlessmango/MangoHud/assets/158144647/02940814-078a-48ac-a946-ad1cbda2e5ca)

Help greatly appreciated!

**Comment by flightlessmango** [comment]
Start by using an up to date version of mangohud

**Comment by Motor7724** [comment]
V0.7.0 solved GPU load and VRAM usage - thanks. Turns out that Ubuntu 22.04 has the outdated package when installing through apt.

CPU is still showing 0W throughout various games that are definitely taxing the CPU though. Would you recommend trying 0.7.1-rc2?

![Screenshot from 2024-02-02 19-01-46](https://github.com/flightlessmango/MangoHud/assets/158144647/c1a622fa-0583-4f96-bb2c-8ef93e903807)

**Comment by flightlessmango** [comment]
Amd CPUs require the zenpower kernel module to show power

**Comment by Motor7724** [comment]
Thanks FM - sorted now. Good work on this program btw.
