### ISSUE TITLE
Starting some games with MangoHUD enabled causes blackscreen

### ISSUE THREAD

**Issue by MatGS-Minty** [flightlessmango/MangoHud#1224]
**Describe the bug**
When i start Tekken 8 or Genshin Impact the games start with a black screen.
Sound plays normally and i can navigate the menus but i only see a black screen.
Disabling MangoHUD through the Environment Variables in Lutris makes Genshin Impact start with picture again.
I start Tekken 8 through Steam, tried Proton GE-30, GE-29, Hotfix and Experimental. The only version i get a picture in is Experimental but it crashes with "Fatal Error!" as soon as it tries to build a network connection.
Tekken 8 worked a couple of days ago without issues, i could even play a few online matches.

Disabling MangoHUD globally through GOverlay makes Tekken 8 start with a picture (with Proton GE-30 and GE-29) but as soon as it asks me to press a button the picture freezes but continues to play music and sound FX when i try to navigate through the menus. 

**List relevant hardware/software information**
- Linux Distribution
Nobara Linux 39
- MangoHud version
mangohud-0.7.0-12.fc39.i686
mangohud-0.7.0-12.fc39.x86_64
- GPU
AMD ATI Radeon RX 6950 XT

**Expected behavior**
The games start and show a picture.
Tekken 8 doesn't crash on network connection buildup.

**Screenshots**
![blackscreen](https://github.com/flightlessmango/MangoHud/assets/94957670/e31d97ae-2d16-4a9d-88f9-f3e34965866d)

![Fatal_error_ProtonExperimental](https://github.com/flightlessmango/MangoHud/assets/94957670/d26eed4b-6c94-42b0-bdd9-50d66f925ff9)

**Additional Info**
The error happened the first time after Nobara Linux pushed new MESA drivers a couple of days ago, i assume it was around 30. or 31.

- installed AMD drivers
amd-gpu-pro-firmware-5.7.2-1.fc39.x86_64
amd-ucode-firmware-20240115-2.fc39.noarch
amdamf-pro-runtime-5.7.2-1.fc39.x86_64
amdogl-pro-5.7.2-4.fc39.i686
amdogl-pro-5.7.2-4.fc39.x86_64
amdvlk-2023.Q4.1-4.i686
amdvlk-2023.Q4.1-4.x86_64
amdvlk-pro-5.7.2-4.fc39.i686
amdvlk-pro-5.7.2-4.fc39.x86_64

- MESA
mesa-libGLU-9.0.1-9.fc39.i686
mesa-libGLU-9.0.1-9.fc39.x86_64
mesa-libOpenCL-23.3.3-2.fc39.x86_64
mesa-vdpau-drivers-freeworld-23.3.3-1.fc39.x86_64

**Comment by luisalvarado** [comment]
Hi buddy, do note some games are VERY picky about using mangohud or any overlay. They will basically fail to load. There was once a case with Bendy and the Dark Revival (got solved with a game update), Dying Light (Got solved with a game update), Dead Island Riptide (Fixed with game update) and I do not remember if Alien Isolation or Abandon Ship had the issue too.

The crashes I know for sure also happened on Bendy and Dying Light after a couple of seconds of playing with MangoHud, after both games got an update, they worked perfectly with MangoHud.

Just pointing this out in case Tekken 8 has the same thing because it is a new game, I think from this year.

**Comment by flightlessmango** [comment]
You have two distinct issues here, it's preferable to make two separate issues for them.
If tekken 8 doesn't work with or without manoghud, I would hold of on investigating that until tekken 8 works on it's own.
As for genshin impact, what is your mangohud config file? are you using the picmip or af options?

**Comment by MatGS-Minty** [comment]
The latest Mesa 24.1.0 update fixed all of my issues.

More detailed description of the solution can be found here:
https://github.com/HansKristian-Work/vkd3d-proton/issues/1878

Issue closed
