### ISSUE TITLE
Does Not Work With Flatpak Steam - Games Refuse To Launch

### ISSUE THREAD

**Issue by BluesAdam** [flightlessmango/MangoHud#1225]
**Describe the bug**
If used with flatpak version of Steam, when I add mangohud %command% launch parameter, games refuse to launch.

**List relevant hardware/software information**
- Fedora 39 Workstation
- MangoHud version 0.7.0
- AMD Rx 7600

**To Reproduce**
1. Install Flatpak version of Steam
2. Install Flatpak or rpm version of MangoHud (tried both)
3. Add mangohud %command% launch parameter to a game (tried Apex Legends and Deep Rock Galactic)
4. Game refuses to launch.

**Expected behavior**
Game should launch with MangoHud overlay enabled.

**Additional context**
I need Flatpak version of Steam and OBS Studio to make Game Capture (obs-vkcapture) work on OBS. Otherwise I cannot record and stream games on OBS. Unfortunately, this means MangoHud overlay doesn't work.

**Comment by flightlessmango** [comment]
if games don't start at all, it usually means that the mangohud script can't be found.
Either because mangohud is not installed or you're using an incompatible combination like normal mangohud and flatpak steam.
You can install flatpak and normal mangohud at the same time

**Comment by BluesAdam** [comment]
> if games don't start at all, it usually means that the mangohud script can't be found. Either because mangohud is not installed or you're using an incompatible combination like normal mangohud and flatpak steam. You can install flatpak and normal mangohud at the same time

Installed both rpm and flatpak versions. Still, the game struggles to run for a couple seconds and then nothing happens. Works completely fine with rpm Steam though. It's just the Flatpak version that breaks it for me.

**Comment by flightlessmango** [comment]
I would say you should report the issue to the flatpak repo https://github.com/flathub/org.freedesktop.Platform.VulkanLayer.MangoHud
We don't deal with issues stemming from packaging
