### ISSUE TITLE
0.7.1 Failed to read presets file

### ISSUE THREAD

**Issue by JupiterRider** [flightlessmango/MangoHud#1229]
**Describe the bug**
Since 0.7.1 I get the following error:
[2024-02-11 17:50:05.618] [MANGOHUD] [error] [overlay_params.cpp:1003] Failed to read presets file: '/home/jupiterrider/.config/MangoHud/presets.conf'

**List relevant hardware/software information**
- Linux Distribution: Archlinux 
- MangoHud version: 0.7.1 (installed via official repo)
- GPU: Intel HD

**Expected behavior**
Having a presets.conf should be optional. So this should not be an error.

**Comment by flightlessmango** [comment]
The preset error is not an actual error, it will not be the cause of a crash and the error will be removed

**Comment by mentaldust** [comment]
It's not really a crash, but a failure to launch. The game (Stellaris) can't launch after the launcher screen, because of Mangohud. Turning off the Mangohud, game works fine. I don't get why HoI4, which also uses a launcher and also a Paradox game isn't affected.

**Comment by mentaldust** [comment]
This wasn't like this a few days ago. Error is happening after mangohud got updated on Fedora 39.

**Comment by FrankeyUser** [comment]
i have many errors

$mangohud glxgears

and show that:
[2024-02-26 22:15:57.446] [MANGOHUD] [error] [overlay_params.cpp:1009] Failed to read presets file: '/home/frank/.config/MangoHud/presets.conf'
[2024-02-26 22:15:59.494] [MANGOHUD] [error] [cpu.cpp:665] Failed to initialize CPU power data
[2024-02-26 22:15:59.592] [MANGOHUD] [error] [loader_nvml.cpp:42] Failed to open 64bit libnvidia-ml.so.1: libnvidia-ml.so.1: cannot open shared object file: No such file or directory
[2024-02-26 22:15:59.592] [MANGOHUD] [error] [nvml.cpp:45] Failed to load NVML
[2024-02-26 22:15:59.877] [MANGOHUD] [error] [nvctrl.cpp:56] XNVCtrl didn't find the correct display

**Comment by flightlessmango** [comment]
Follow the issue template please, need much more information

**Comment by ForeverZer0** [comment]
>The preset error is not an actual error, it will not be the cause of a crash and the error will be removed

While it appears this was split from a larger issue, and some context is missing with more going on here, just on the "logging a non-error as an error" topic, is this the desired behavior? From a logging standpoint, it could be argued that this would barely qualify as a log-worthy event, least of all a warning or an error entry. It is admittedly a nitpick, but mildly annoying to see a "error that isn't really an error" message in an otherwise error-free run from the terminal.

**Comment by flightlessmango** [comment]
> "logging a non-error as an error" topic, is this the desired behavior?

No like I said, it was going to be removed and it has been removed.
Please follow the issue template and create a new issue if the other issue is still present

**Comment by ryanmusante** [comment]
```
Apr 08 16:22:48 xmg org.gnome.Shell.desktop[1146]: [2024-04-08 16:22:48.236] [MANGOHUD] [error] [overlay_params.cpp:1003] Failed to read presets file: '/var/lib/gdm/.config/MangoHud/presets.conf'
```
~ > \cat /etc/environment | grep -i mangohud
```
MANGOHUD=1
MANGOHUD_CONFIGFILE=/home/ryan/.config/mangohud/mangohud.conf
```
