### ISSUE TITLE
`vsync = 0` option causes XWayland games to not launch on NVidia drivers 550

### ISSUE THREAD

**Issue by Fxzzi** [flightlessmango/MangoHud#1232]
**Describe the bug**

**List relevant hardware/software information**
- Arch Linux
- MangoHud version 0.7.1
- NVidia RTX 3070

**To Reproduce**
1. Update to NVidia drivers 550
2. Set `vsync=0` in mangohud config
3. Launch a game with XWayland (Elden Ring and Doom Eternal both display these issues for me)
4. Observe that the game doesn't lanuch and stays on a White / Black screen (MangoHud also does not display)
5. Set `vsync=1` (off) instead and lanuch, observe that the games launch completely fine with no issues.

**Expected behavior**
The game should launch correctly with the correct FIFO Relaxed Vsync option enabled

**Additional context**
Does not occur on NVidia Driver version 535.

**Comment by flightlessmango** [comment]
This seems like an issue on nvidia's end

**Comment by Revival8697** [comment]
On GTX 1660 Ti Mobile, driver vesion 550.67, games launch but result in black screen.

**Comment by flightlessmango** [comment]
This is not likely to be a mangohud issue as we just set the user specified present mode. This should be reported to nvidia

**Comment by Fxzzi** [comment]
Understood, thanks. I had posted on the Nvidia forum as well as here. Please like the post or say you're experiencing the issue yourself, Nvidia hasn't made a single reply on it. 

https://forums.developer.nvidia.com/t/blank-screens-on-games-with-adaptive-vsync-fifo-relaxed-khr-enabled-driver-550-regression-works-on-535/284442?u=faaris.ansari
