### ISSUE TITLE
Percentile Visual is wrong

### ISSUE THREAD

**Issue by luisalvarado** [flightlessmango/MangoHud#1238]
Since last compile (Today) the percentile shows wrong

![image](https://github.com/flightlessmango/MangoHud/assets/29236/ef8813af-5443-4fce-807b-1d623e297570)

The image is supposed to be

0.1% (Where it says 0.0)
1% (Where is says 0.9%)
97% (Where it says 96.9%)

But it shows with 0.1 less than normal

**Comment by flightlessmango** [comment]
It looks normal on my end on latest commit, could you recompile with latest and list what commit it is?

**Comment by luisalvarado** [comment]
Confirmed, you were right. No idea what the hell happened.

![image](https://github.com/flightlessmango/MangoHud/assets/29236/0d442bb3-6a61-4b19-b088-63a4522304b6)
