### ISSUE TITLE
Can't get time_no_label to work

### ISSUE THREAD

**Issue by GenocideStomper** [flightlessmango/MangoHud#1239]
**Describe the bug**
I've upgraded from 0.7.0 to 0.7.1. One of the changes is that there's (imo) an unnecessary title next to the time.
In the [README.md](https://github.com/flightlessmango/MangoHud/blob/45671161c4fc84593feef408a23c7d29d140f590/README.md?plain=1#L414) and [data/MangoHud.conf](https://github.com/flightlessmango/MangoHud/blob/45671161c4fc84593feef408a23c7d29d140f590/data/MangoHud.conf#L66) files there's mention of a new "time_no_label" variable, which "removes the time label".

Putting time_no_label in my MangoHud.conf makes no different. I've tried the following along with the result:

1.: `time` & `time_no_label` --> shows time label
2.: only `time_no_label` --> shows no time (and of course no time label)
3.: `time` & `time_no_label=true` --> shows time label

Am I doing something wrong with how the parameter is supposed to be used?

**List relevant hardware/software information**
- Linux Distribution: EndeavourOS
- MangoHud version: 0.7.1
- GPU: Nvidia GTX 1080

**To Reproduce**
1. Update to MangoHud 0.7.1
2. Put time_no_label in MangoHud.conf
3. (Optional?) Put time in MangoHud.conf
4. Start game, still see time label

**Expected behavior**
Putting time_no_label in my MangoHud.conf file should remove the time label

**Screenshots**
![CS2 screenshot](https://github.com/flightlessmango/MangoHud/assets/5098895/def16641-9a4b-47c7-a46d-5d45ae67fee7)
![Config screenshot](https://github.com/flightlessmango/MangoHud/assets/5098895/39d7a4e5-db81-47c1-b868-53a7f532ea7d)
![image](https://github.com/flightlessmango/MangoHud/assets/5098895/3c33578e-ccc2-47f5-b7a2-105e0ab2a680)

**Additional context**
Running from the command line gives the error: Unknown option 'time_no_label' (see screenshot 3)

**Comment by flightlessmango** [comment]
`time_no_label` is not in 0.7.1

**Comment by GenocideStomper** [comment]
Will it be in 0.7.2, and is there an ETA for it?

**Comment by flightlessmango** [comment]
It will be 0.7.2 but there is no ETA

**Comment by GenocideStomper** [comment]
Thanks. I'll downgrade to 0.7.0 and will wait for 0.7.2.
