### ISSUE TITLE
[Nvidia or just Asus cards with Nvidia GPU] Fan "percentage" field shows rpm value

### ISSUE THREAD

**Issue by CPioGH2002** [flightlessmango/MangoHud#1244]
**Describe the bug**
**EDIT**: Read my posts below: The simple error is that "percentage" might have that label but actually shows fan rpm.

~~The fan percentage value on Nvidia cards shows very high numbers, _starting_ at close to 1000% percent. The "zero" state is fine (showing "0%"), but fan activation triggers the high percentage values.~~

**List relevant hardware/software information**
- Linux Distribution: Kubuntu 23.10
- MangoHud version: 0.7.1 (Flatpak and manual install)
- GPU: Nvidia RTX4070Ti Super (feel free to make fun of the name, I approve)
- Card Manufacturer: **Asus** (they might do some weird stuff with their sensors and reporting, could be a source for the problem)

**To Reproduce**
Steps to reproduce the behaviour:
1. Enable fan percentage display in conf file (Section: "### Display the current GPU information" > "gpu_fan")
2. Start any instance which creates enough load for your graphic card fans to come alive
3. Watch fan percentage in Mangohud

**Expected behavior**
Expecting values between 0 and 100%, certainly not above 1000%

**Screenshots**
![MH_fan_value_a](https://github.com/flightlessmango/MangoHud/assets/134099708/fbf7d7c7-47bf-4ba0-a8b5-f6cb70f31c8f)

**Additional context**
My GPU-related settings in the conf file:
```
### Display the current GPU information
## Note: gpu_mem_clock and gpu_mem_temp also need "vram" to be enabled
gpu_stats
gpu_temp
gpu_junction_temp
gpu_core_clock
gpu_mem_temp
gpu_mem_clock
gpu_power
# gpu_text=
gpu_load_change
# gpu_load_value=60,90
# gpu_load_color=39F900,FDFD09,B22222
# GPU fan in rpm on AMD, FAN in percent on NVIDIA
gpu_fan
## gpu_voltage only works on AMD GPUs
# gpu_voltage
```

**Thanks for your work on this great tool helping us Linux gamers.** :-)

**Comment by flightlessmango** [comment]
I believe this is already fixed in master

**Comment by flightlessmango** [comment]
That and maybe another commit, but yes
