### ISSUE TITLE
MangoHud Lists "DOOM Eternal" as OpenGL

### ISSUE THREAD

**Issue by sonic2kk** [flightlessmango/MangoHud#125]
I used MangoHud to display system information in DOOM Eternal running under Proton (GloriousEggroll's 5.5-GE-1 specifically). However it says that DOOM Eternal is using OpenGL. This cannot be the case however since the game exclusively uses Vulkan, so I would expect to see a DXVK version here.

![Screenshot_20200412_195202](https://user-images.githubusercontent.com/7917345/79077151-2c497780-7cf7-11ea-8187-91bac0d0fe54.png)

Obviously this isn't a major bug or anything but why is this happening? Am I doing something wrong? If it's at all relevant, I have the Steam Overlay disabled but enabling it didn't fix the issue. I'm using Arch Linux and MangoHud v0.3.0-3 installed through the Yay package manager.

Cheers!

**Comment by flightlessmango** [comment]
I believe this was fixed in 0.3.1. Try updating mangohud and see if that does it

**Comment by sonic2kk** [comment]
Ah, sorry! I didn't realise there was a 0.3.1, should've checked. I'll install the mangohud-git package and see if that fixes it.

**Comment by sonic2kk** [comment]
Ah, for some reason when I updated my AUR packages the standard MangoHud package was listed and it's now updated to 0.3.1. I can indeed confirm that this fixed it. All fixed now, thank you!

![Screenshot_20200412_215208](https://user-images.githubusercontent.com/7917345/79079580-f365ce80-7d07-11ea-8095-e37426d5fc56.png)
