### ISSUE TITLE
Not working on Arkham Origins

### ISSUE THREAD

**Issue by Lewis-Hamilton** [flightlessmango/MangoHud#1250]
**Describe the bug**
I am trying to use MangoHud with Batman Arkham Origins on steam. It works fine on other games I've tried (Rise of the Tomb Raider and GTA V by adding `MANGOHUD=1 %command%` to the launch options for those games) and I'm loving it so far, just can't get it to work with Origins.

**List relevant hardware/software information**
- Ubuntu 22.04
- v0.6.5
- GTX 960

**To Reproduce**
1. Add one of the following to Arkham Origin's launch options (I've tried each of these)
`mangohud %command%` `MANGOHUD=1 %command%` `mangohud --dlsym %command%` `MANGOHUD_DLSYM=1 %command%` or `NODEVICE_SELECT=1 mangohud %command%`
2. Launch the game
3. The game either doesn't launch, or launches fine but mango hud doesn't appear

**Expected behavior**
I expect to see the hud in Arkham Origins when I launch the game with one of the above launch options.

**Screenshots**
NA

**Additional context**
- I've tried the solution described in #455 
- I've tried the solution described in #369 but I don't have the soldier file, mine is sniper (I guess that's the newer version?)
- I installed MangoHud by cloning into the repo and building/installing with the build script

**Comment by Leopard1907** [comment]
1-) 0.6.5 is very old.

2-) You probably use that because Ubuntu ships that but iirc it lacks 32 bit Mangohud and that game is 32 bit.

3-) So; nuke it and install this as described.

https://github.com/flightlessmango/MangoHud?tab=readme-ov-file#github-releases

**Comment by Lewis-Hamilton** [comment]
> 1-) 0.6.5 is very old.
> 
> 2-) You probably use that because Ubuntu ships that but iirc it lacks 32 bit Mangohud and that game is 32 bit.
> 
> 3-) So; nuke it and install this as described.
> 
> https://github.com/flightlessmango/MangoHud?tab=readme-ov-file#github-releases

I can't believe it was so simple, I spent way too long trying to figure this out. I'm on v0.7.1 now and it worked perfectly. Thank you!
