### ISSUE TITLE
CPU_power is 0W

### ISSUE THREAD

**Issue by cemkaya-mpi** [flightlessmango/MangoHud#1253]
Hello, my CPU power usage is reported as 0W, even though zenpower3 and zenergy are installed.

- Arch Linux
- MangoHud 0.7.1.r21.g2aa6042-1
- Ryzen 6800H Laptop with NVIDIA RTX3060

CPU power usage in watts is available using zenmonitor, but it is not visible from `sensors`. Could this be the issue?

**Comment by Etaash-mathamsetty** [comment]
> Hello, my CPU power usage is reported as 0W, even though zenpower3 and zenergy are installed.
> 
>     * Arch Linux
> 
>     * MangoHud 0.7.1.r21.g2aa6042-1
> 
>     * Ryzen 6800H Laptop with NVIDIA RTX3060
> 
> 
> CPU power usage in watts is available using zenmonitor, but it is not visible from `sensors`. Could this be the issue?

try removing zenpower3

**Comment by cemkaya-mpi** [comment]
Yes, removing zenpower3 seems to work. Thanks!

**Comment by flightlessmango** [comment]
@Etaash-mathamsetty why exactly does removing zenpower3 work?
Is there a bug in zenpower3 or mangohud?

**Comment by Etaash-mathamsetty** [comment]
> @Etaash-mathamsetty why exactly does removing zenpower3 work?
> Is there a bug in zenpower3 or mangohud?

The code prefers one path if it's present and checks for zenpower3 first even if it doesn't report anything.

**Comment by flightlessmango** [comment]
This commit should resolve issues like this in the future 77d6244cea5503297b27e9283dae2781050768e7
