### ISSUE TITLE
Counter-Strike 2 Xubuntu 22.04.4 LTS MangoHud Crash

### ISSUE THREAD

**Issue by Slo2018** [flightlessmango/MangoHud#1255]
Counter-Strike 2 crash at starting with MangoHud. Only working without MangoHud. The same problem in Linux Mint 21.3. I'm using RTX 4080 and Xubuntu 22.04.4 LTS.

**Comment by flightlessmango** [comment]
What mangohud version?

**Comment by Slo2018** [comment]
0.7.1

**Comment by VladimirMrzv** [comment]
try to change config, use only fps parameter. 
On my system some games not start with font_size=36 . Games - Elden Ring, Portal, L4D

**Comment by h3-Hanouzz** [comment]
I am having the same issue on Linux Mint Edge, it will crash a few seconds after startup whether I do `mangohud %command%` or `MANGOHUD=1 %command%`

**Comment by flightlessmango** [comment]
@h3-Hanouzz what mangohud version?

**Comment by h3-Hanouzz** [comment]
@flightlessmango dw, building from source has fixed the issue

**Comment by flightlessmango** [comment]
@Slo2018 if you still have an issue with this, follow up in #1278
