### ISSUE TITLE
Latest mangohud crashes with Wine Wayland

### ISSUE THREAD

**Issue by shmerl** [flightlessmango/MangoHud#1258]
Trying to enable HUD for Wine Wayland (vkd3d-proton game run for Cyberpunk 2077) crashes like this:

```
0228:err:seh:call_seh_handlers invalid frame 000000010306C1D0 (00007FBA24202000-00007FBA24400000)
0228:err:seh:NtRaiseException Exception frame is not in stack limits => unable to dispatch exception.
```

I don't really see much of other errors.

* Wine: 9.4 + esync (Wayland mode)
* MangoHud: Master (git) 83af57a9b31fd04a66c49d7ceab046066dde4792

**Comment by gort818** [comment]
Is this with a specific application or anything running wine wayland? I tested a few days ago without issue.

**Comment by shmerl** [comment]
Cyberpunk 2077 running with Wine Wayland (+vkd3d-proton + esync)

**Comment by gort818** [comment]
Just tested Cyberpunk 2077 seems to work fine for me with a wine build from yesterday and latest mangohud

**Comment by shmerl** [comment]
Weird, I don't see code changing commits past mine.

Are you sure you are running Wine in Wayland mode?

**Comment by gort818** [comment]
Kde here
![Screenshot_20240311_175339](https://github.com/flightlessmango/MangoHud/assets/9098121/49296bca-6461-4d44-b457-23b139f25c45)

**Comment by shmerl** [comment]
Interesting. May be some weird combination of distro libs then? I'll try rebuilding things just in case. I'm doing it on Debian testing.

**Comment by shmerl** [comment]
Oh, forgot to ask, Plasma 5 or Plasma 6? They are pretty far apart as Wayland compositors so not comparable for bugs.

**Comment by shmerl** [comment]
That could contribute to difference. Trying to build with debug now and see what happens.

**Comment by shmerl** [comment]
Hmm, with debug build of mangohud it's not crashing, but it's sitting with black window doing nothing.

**Comment by shmerl** [comment]
Attaching with gdb to it - 81 threads there... 😬

**Comment by gort818** [comment]
Can you still reproduce this issue? Have you switched to Plasma 6 yet?

**Comment by shmerl** [comment]
Not yes. Waiting for Debian maintainers to package it. There was a humongous 64-bit time_t transition which probably slowed things down a bit, but they are working on packaging needed dependencies. So hopefully it won't be too long.

**Comment by shmerl** [comment]
I'll update the bug once I get a chance to confirm that it's working with Plasma 6 or it's still broken.

**Comment by shmerl** [comment]
Also for the reference, it appears to be Wine path related issue, since it's working fine for example with `vkcube-wayland`.

**Comment by Rrauros** [comment]
Latest release also introduced this issue on my end. Both Gnome and Kde affected. I'm using bottles for my games. Could it be related to bottles or flatpak? Using xwayland fixes the issue.

**Comment by shmerl** [comment]
I don't use flatpak, so that shouldn't be the main reason.

**Comment by shmerl** [comment]
Just got to finally install Plasma 6.1.3 in Debian testing (pulling from experimental there).

The issue is gone for me with Mangohud 0.7.2 but note that it's broken with 0.7.1 if anyone is still using that one. I think we can close it.

**Comment by gort818** [comment]
Good to know thank you!
