### ISSUE TITLE
Half Life 2: Episode 2, Witcher 2, Tropico 5

### ISSUE THREAD

**Issue by longusnickus** [flightlessmango/MangoHud#126]
I use this Launch Option "mangohud.x86 %command%"

Witcher 2 crashes while loading a savegame. Main Menu works.

HL2 and Tropico 5: The Hud jumps around randomly: https://streamable.com/e6xkcx

**Comment by Leopard1907** [comment]
Fwiw Witcher 2 likes to crash if you have 10+ save files. Try deleting some of them. Game issue , exists on both platforms.

**Comment by longusnickus** [comment]
it works without mangohud.
but i deleted all, but 6 savegames (disabled cloud, or else it downloads it again). it still crashes

**Comment by Leopard1907** [comment]
Are you on master or latest release? It works for me with Witcher 2 Linux port on Intel gpu , latest MangoHud release.

**Comment by longusnickus** [comment]
0.3.1

**Comment by flightlessmango** [comment]
It's probably worth trying the develop branch [MangoHud-latest.tar.gz](https://flightlessmango.com/MangoHud-latest.tar.gz)

**Comment by longusnickus** [comment]
it fixed tropico 5 und HL. thx
witcher 2 still crashes on my rx580, mesa 20.0.4
if it works for leopard1907 it is maybe just my maschine

**Comment by Leopard1907** [comment]
Works on Mesa 20.0.4, with Haswell igpu. Didn't check on Nvidia.
![Ekran_Goruntusu_-_2020-04-14_03-01-27](https://user-images.githubusercontent.com/24878978/79174409-56885b80-7e03-11ea-9a6e-868c23fdc377.png)

**Comment by longusnickus** [comment]
main menu works for me too... it crashes, when i load a savegame

**Comment by Faalagorn** [comment]
Might not be related, but I also have crashes on a 32-bit game (World of Guns), but it only happens when I use this package: https://aur.archlinux.org/packages/mangohud-git/ so I'm sticking to [this](https://aur.archlinux.org/packages/mangohud/) for now. Can you check if there's any difference for you @longusnickus ?

**Comment by longusnickus** [comment]
World of Guns works for me with "mangohud %command%"
disassembled 2 guns

**Comment by longusnickus** [comment]
works with latest mango so far
