### ISSUE TITLE
Segmentation fault on shortcut press.

### ISSUE THREAD

**Issue by Steamvoker** [flightlessmango/MangoHud#1263]
When I press Shift_R+F9 mangohud crashes.

**List relevant hardware/software information**
- EndeavourOS
- MangoHud version 0.7.1-1
- GPU RTX 4090 (550.54.14-5)

**To Reproduce**
1. run `mangohud vkcube` (or anything else using vulkan)
2. Press Shift_R+F9
```
mangohud vkcube
[2024-03-17 14:16:01.023] [MANGOHUD] [error] [overlay_params.cpp:1003] Failed to read presets file: '/home/steamvoker/.config/MangoHud/presets.conf'
Selected GPU 0: NVIDIA GeForce RTX 4090, type: DiscreteGpu
Segmentation fault (core dumped)
```

**Expected behavior**
Shortcut executes as expected (if it is configured).

**Additional context**
So I noticed this happens when I press `Shift_R+F9`  and I thought this is related to `toggle_fps_limit`, because that's where my fps limit toggle was set. I have tried changing number of values in `fps_limit` and nothing happened. Tried changing the shortcut to a different set of keys, and that worked (as in, I was able to toggle the limit), but `Shift_R+F9` still crashed, even without anything bound to it. I've checked #1084, but that should not be the problem now.

I have tried this with `mangohud vkcube` and through Steam. it seems to be related to Vulkan because titles like Balatro, which say are using OpenGL are fine, but something like C&C Remastered Collection (through proton) or Dota 2 (native) crash.

**Comment by flightlessmango** [comment]
This has already been fixed in 95141de657e02577f1d3fab0ca12122bfb68bc56
