### ISSUE TITLE
Not really an issue but a question 

### ISSUE THREAD

**Issue by ripplingsnake** [flightlessmango/MangoHud#1264]
I am trying to tie mangohud fps to ryzenadj so my script will adjust tpd if the fps drops below or above the set fps. However I am struggling with getting it done. Is there a simple way to capture the fps ? Thanks 

**Describe the bug**

**List relevant hardware/software information**
- Linux Distribution
- MangoHud version
- GPU

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by flightlessmango** [comment]
The only way currently is to have mangohud log to a file and read that file

**Comment by flightlessmango** [comment]
You can write this as a feature request

**Comment by flightlessmango** [comment]
> You can write this as a feature request

Scratch that, there is already a feature request for this here #1166
