### ISSUE TITLE
Cant build locally Ubuntu 22.04.4 LTS 

### ISSUE THREAD

**Issue by pawcijo** [flightlessmango/MangoHud#1265]
**Describe the bug**
[107/110] Linking target src/libMangoHud_dlsym.so
FAILED: src/libMangoHud_dlsym.so 
g++ -m32  -o src/libMangoHud_dlsym.so src/libMangoHud_dlsym.so.p/elfhacks.cpp.o src/libMangoHud_dlsym.so.p/real_dlsym.cpp.o src/libMangoHud_dlsym.so.p/hook_dlsym.cpp.o -Wl,--as-needed -Wl,--no-undefined -Wl,-O1 -shared -fPIC -Wl,--start-group -Wl,-soname,libMangoHud_dlsym.so -Wl,-rpath,/usr/lib/x86_64-linux-gnu -Wl,-rpath-link,/usr/lib/x86_64-linux-gnu src/libMangoHud.a subprojects/imgui-1.89.9/libimgui.a subprojects/spdlog-1.13.0/src/libspdlog.a subprojects/implot-0.16/libimplot.a -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--exclude-libs,ALL -static-libstdc++ -Wl,--version-script,/home/pawcijo/github/MangoHud/src/mangohud.version /usr/lib/x86_64-linux-gnu/libwayland-client.so /usr/lib/x86_64-linux-gnu/libxkbcommon.so -Wl,--end-group -pthread
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libwayland-client.so: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
[108/110] Linking target src/libMangoHud.so
FAILED: src/libMangoHud.so 
g++ -m32  -o src/libMangoHud.so src/libMangoHud.a.p/vulkan.cpp.o src/libMangoHud.a.p/mesa_util_os_socket.c.o src/libMangoHud.a.p/mesa_util_os_time.c.o src/libMangoHud.a.p/hud_elements.cpp.o src/libMangoHud.a.p/overlay.cpp.o src/libMangoHud.a.p/overlay_params.cpp.o src/libMangoHud.a.p/font.cpp.o src/libMangoHud.a.p/keybinds.cpp.o src/libMangoHud.a.p/font_unispace.c.o src/libMangoHud.a.p/logging.cpp.o src/libMangoHud.a.p/config.cpp.o src/libMangoHud.a.p/gpu.cpp.o src/libMangoHud.a.p/blacklist.cpp.o src/libMangoHud.a.p/file_utils.cpp.o src/libMangoHud.a.p/cpu.cpp.o src/libMangoHud.a.p/memory.cpp.o src/libMangoHud.a.p/iostats.cpp.o src/libMangoHud.a.p/notify.cpp.o src/libMangoHud.a.p/elfhacks.cpp.o src/libMangoHud.a.p/real_dlsym.cpp.o src/libMangoHud.a.p/pci_ids.cpp.o src/libMangoHud.a.p/battery.cpp.o src/libMangoHud.a.p/control.cpp.o src/libMangoHud.a.p/device.cpp.o src/libMangoHud.a.p/amdgpu.cpp.o src/libMangoHud.a.p/intel.cpp.o src/libMangoHud.a.p/msm.cpp.o src/libMangoHud.a.p/nvml.cpp.o src/libMangoHud.a.p/loaders_loader_nvml.cpp.o src/libMangoHud.a.p/loaders_loader_nvctrl.cpp.o src/libMangoHud.a.p/nvctrl.cpp.o src/libMangoHud.a.p/loaders_loader_x11.cpp.o src/libMangoHud.a.p/shared_x11.cpp.o src/libMangoHud.a.p/wayland_hook.cpp.o src/libMangoHud.a.p/wayland_keybinds.cpp.o src/libMangoHud.a.p/dbus.cpp.o src/libMangoHud.a.p/loaders_loader_dbus.cpp.o src/libMangoHud.a.p/meson-generated_.._.._vk_enum_to_str.c.o -Wl,--as-needed -Wl,--no-undefined -Wl,-O1 -shared -fPIC -Wl,--start-group -Wl,-soname,libMangoHud.so -Wl,-rpath,/usr/lib/x86_64-linux-gnu -Wl,-rpath-link,/usr/lib/x86_64-linux-gnu src/libMangoHud.a subprojects/imgui-1.89.9/libimgui.a subprojects/spdlog-1.13.0/src/libspdlog.a subprojects/implot-0.16/libimplot.a -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--exclude-libs,ALL -static-libstdc++ -Wl,--version-script,/home/pawcijo/github/MangoHud/src/mangohud.version /usr/lib/x86_64-linux-gnu/libwayland-client.so /usr/lib/x86_64-linux-gnu/libxkbcommon.so -Wl,--end-group -pthread
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libwayland-client.so: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
[109/110] Linking target src/libMangoHud_opengl.so
FAILED: src/libMangoHud_opengl.so 
g++ -m32  -o src/libMangoHud_opengl.so src/libMangoHud_opengl.so.p/gl_glad.c.o src/libMangoHud_opengl.so.p/gl_gl_renderer.cpp.o src/libMangoHud_opengl.so.p/gl_gl_hud.cpp.o src/libMangoHud_opengl.so.p/gl_inject_egl.cpp.o src/libMangoHud_opengl.so.p/loaders_loader_glx.cpp.o src/libMangoHud_opengl.so.p/gl_inject_glx.cpp.o src/libMangoHud_opengl.so.p/hud_elements.cpp.o src/libMangoHud_opengl.so.p/overlay.cpp.o src/libMangoHud_opengl.so.p/overlay_params.cpp.o src/libMangoHud_opengl.so.p/font.cpp.o src/libMangoHud_opengl.so.p/keybinds.cpp.o src/libMangoHud_opengl.so.p/font_unispace.c.o src/libMangoHud_opengl.so.p/logging.cpp.o src/libMangoHud_opengl.so.p/config.cpp.o src/libMangoHud_opengl.so.p/gpu.cpp.o src/libMangoHud_opengl.so.p/blacklist.cpp.o src/libMangoHud_opengl.so.p/file_utils.cpp.o src/libMangoHud_opengl.so.p/cpu.cpp.o src/libMangoHud_opengl.so.p/memory.cpp.o src/libMangoHud_opengl.so.p/iostats.cpp.o src/libMangoHud_opengl.so.p/notify.cpp.o src/libMangoHud_opengl.so.p/elfhacks.cpp.o src/libMangoHud_opengl.so.p/real_dlsym.cpp.o src/libMangoHud_opengl.so.p/pci_ids.cpp.o src/libMangoHud_opengl.so.p/battery.cpp.o src/libMangoHud_opengl.so.p/control.cpp.o src/libMangoHud_opengl.so.p/device.cpp.o src/libMangoHud_opengl.so.p/amdgpu.cpp.o src/libMangoHud_opengl.so.p/intel.cpp.o src/libMangoHud_opengl.so.p/msm.cpp.o src/libMangoHud_opengl.so.p/nvml.cpp.o src/libMangoHud_opengl.so.p/loaders_loader_nvml.cpp.o src/libMangoHud_opengl.so.p/loaders_loader_nvctrl.cpp.o src/libMangoHud_opengl.so.p/nvctrl.cpp.o src/libMangoHud_opengl.so.p/loaders_loader_x11.cpp.o src/libMangoHud_opengl.so.p/shared_x11.cpp.o src/libMangoHud_opengl.so.p/wayland_hook.cpp.o src/libMangoHud_opengl.so.p/wayland_keybinds.cpp.o src/libMangoHud_opengl.so.p/dbus.cpp.o src/libMangoHud_opengl.so.p/loaders_loader_dbus.cpp.o src/libMangoHud_opengl.so.p/mesa_util_os_socket.c.o src/libMangoHud_opengl.so.p/mesa_util_os_time.c.o -Wl,--as-needed -Wl,--no-undefined -Wl,-O1 -shared -fPIC -Wl,--start-group -Wl,-soname,libMangoHud_opengl.so -Wl,-rpath,/usr/lib/x86_64-linux-gnu -Wl,-rpath-link,/usr/lib/x86_64-linux-gnu src/libMangoHud.a subprojects/imgui-1.89.9/libimgui.a subprojects/spdlog-1.13.0/src/libspdlog.a subprojects/implot-0.16/libimplot.a -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--exclude-libs,ALL -static-libstdc++ -Wl,--version-script,/home/pawcijo/github/MangoHud/src/mangohud.version /usr/lib/x86_64-linux-gnu/libwayland-client.so /usr/lib/x86_64-linux-gnu/libxkbcommon.so -Wl,--end-group -pthread
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libwayland-client.so: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

**List relevant hardware/software information**
- Ubuntu 22.04.4 LTS
- Latest master (a7a73afdadd045ed9235afae0b414c96808d24ee)
- RTX 3070 Ti Gigabyte 8gb

**To Reproduce**
run : ./build.sh build

**Comment by pawcijo** [comment]
No errors on 0.7.1

**Comment by dnbduck** [comment]
Same problem with Pop!_OS 22.04

**Comment by aloepker** [comment]
same on Fedora

**Comment by Potato-Waffles** [comment]
I found a work-around - on Ubuntu 22.04, the previous version **0.7.1-rc2** of mangohud does compile from source. 

To switch to it, after doing "git clone" and "cd ./MangoHud" type: 
`git checkout d30cf16`

Then execute the compile steps as normal.

**Comment by aloepker** [comment]
fix doesnt work on fedora: 
![Screenshot from 2024-03-31 22-45-36](https://github.com/flightlessmango/MangoHud/assets/91484770/5c1732bf-11aa-4aee-937c-146e4ecf13d3)
![Screenshot from 2024-03-31 22-45-50](https://github.com/flightlessmango/MangoHud/assets/91484770/f39d1622-6cd9-4752-8e26-c9783f213db7)
![Screenshot from 2024-03-31 22-46-00](https://github.com/flightlessmango/MangoHud/assets/91484770/87fe2d44-7b1e-4f01-aca2-ec8c9bd2445b)

**Comment by Potato-Waffles** [comment]
You are missing CMake, as signified by "Found CMake: NO". I've made that mistake before as well. You need to install it:
`sudo dnf install cmake`

I have not seen "catch2" as a requirement before, but the script is also missing it. Try rerunning ./build.sh build with CMake installed. If it still complains about catch2, you have to install it as well.

**Comment by flightlessmango** [comment]
This should be resolved in 5b233be for ubuntu/pop and fedora
Just make sure to do a `./build.sh clean` before building again if you're using the build script

**Comment by ChaosBlades** [comment]
Still failing to build on Pop!_OS 22.04 LTS x86_64 

https://gist.github.com/ChaosBlades/3058517c16118c520bc43c24c866f23c

If I install straight from the repo (0.6.5-2) I get this. So it seems that is broken now.

```
mangohud glxgears
can't get libdl.so
```

Was only able to get it installed and working by using the tar from releases.

**Comment by flightlessmango** [comment]
@ChaosBlades 0.6.5 is very out of date, you don't have to report issues with it.
As for your build error, can you try again with latest commit?

**Comment by ChaosBlades** [comment]
@flightlessmango I was just saying 0.6.5 used to work last time I installed Pop and it is even no longer an option.

Seems to of stopped at the same point still. 
https://gist.github.com/ChaosBlades/fc90c32a990c15d7257cb6942d8e5ed5

**Comment by flightlessmango** [comment]
@ChaosBlades I believe it should be fixed here cdd80434898d19b9515573734979a4851da49c2c

also this is another issue. continue in #1286 if you still have this issue
