### ISSUE TITLE
[Feature Request] Provide GPU_busy related metrics for benchmarking

### ISSUE THREAD

**Issue by november781** [flightlessmango/MangoHud#1267]
Fairly recently Intel added GPU_busy to presentmon which is a useful metric for finding bottlenecks in system performance and scoping in on possible hardware issues. From what I understand from looking into this metric, its mostly counting the time between the graphics engine present call and the GPU displaying the frame. Specifically [Nvidia Frameview calls this MsRenderPresentLatency ](https://www.nvidia.com/content/dam/en-zz/Solutions/GeForce/technologies/frameview/frameview-user-guide-1-1-web.pdf) 

I could be wrong in how GPU_busy is calculated since I haven't really had the time to dig into presentmon to find out just yet but that would be another very useful metric that the benchmarking applications on the windows side are unlikely to bring to linux. 

For anyone interested in looking into GPU_busy, presentmon's source is available [here](https://github.com/GameTechDev/PresentMon)

**Comment by flightlessmango** [comment]
You mean specifically for intel? this is already implemented

**Comment by november781** [comment]
No, I'm meaning for other GPUs, frankly I didn't know it was implemented for intel already. I'm unsure if its even possible tho (again I haven't had the time to look at this too much).

**Comment by flightlessmango** [comment]
This is just gpu utilization which we've always tracked

**Comment by november781** [comment]
> This is just gpu utilization which we've always tracked

then maybe I'm misunderstanding something here and need to re-word and re-think this. 

but on windows, Nvidia logs the time between engine present call and the GPU finishing work on that frame which is mostly what I'm interested in. Frameview offers this functionality for intel, Nvidia, and AMD GPUs.

**Comment by november781** [comment]
I'm gonna close this until I can find a better way to work it and explain exactly what it is I'm looking for

**Comment by rKsanu2MMYvypWePtQWM** [comment]
> I'm gonna close this until I can find a better way to work it and explain exactly what it is I'm looking for

GPU_busy shows how long the GPU was working for the current frame in milliseconds. afterwards you can compare this number with the overall frametime to see if GPU was working hard or it was waiting for CPU.

**Comment by JustCauseWhyNot** [comment]
This would be very nice to have to know when gpu throttled when both components are being heavily utilized.
