### ISSUE TITLE
autostart_log ignored when using no_display

### ISSUE THREAD

**Issue by HollyCeuin** [flightlessmango/MangoHud#1268]
I'm basically trying to pull framerate from log files into conky to display my framerate on a different screen, but `autostart_log` seems to be entirely ignored if `no_display` is used. Is there any way to adjust this?

**Comment by HollyCeuin** [comment]
While I'm at it, `autostart_log=1` appears to be entirely ignored when using `no_display", any way to change that?

**Comment by flightlessmango** [comment]
I can't repro this, it works with `no_display` on my end

**Comment by flightlessmango** [comment]
I don't see a reason why it wouldn't work so I'm closing this until more information can be provided
