### ISSUE TITLE
Unable to compile from source on fedora 39:

### ISSUE THREAD

**Issue by aloepker** [flightlessmango/MangoHud#1272]
**Describe the bug**
Multiple "failed" entries durring "./build.sh Build" step 

**List relevant hardware/software information**
- Linux Distribution - Fedora 39 Gnome Workstation Edition on a Dell Inspirion 15 5510
- MangoHud version - current from github
- GPU - Intel Iris XE w/11th Gen Intel® Core™ i5-11320H × 8

**To Reproduce**
After I installed many/most dependencies by hand, I was able to run the lines:
meson build
ninja -C build install

I then ran "./build.sh Build" in the terminal, here are the results:

adam@Orville:~/MangoHud$ ./build.sh build
Command: build 
ninja: Entering directory `build/meson64'
[1/2] Installing files.
Installing src/libMangoHud.so to /home/adam/MangoHud/build/release/usr/lib/mangohud/lib64
Installing src/libMangoHud_opengl.so to /home/adam/MangoHud/build/release/usr/lib/mangohud/lib64
Installing src/libMangoHud_dlsym.so to /home/adam/MangoHud/build/release/usr/lib/mangohud/lib64
Installing /home/adam/MangoHud/data/mangohud.1 to /home/adam/MangoHud/build/release/usr/share/man/man1
Installing /home/adam/MangoHud/build/meson64/src/MangoHud.x86_64.json to /home/adam/MangoHud/build/release/usr/share/vulkan/implicit_layer.d
Installing /home/adam/MangoHud/build/meson64/src/mangohud to /home/adam/MangoHud/build/release/usr/bin
Installing /home/adam/MangoHud/data/io.github.flightlessmango.mangohud.metainfo.xml to /home/adam/MangoHud/build/release/usr/share/metainfo
Installing /home/adam/MangoHud/data/io.github.flightlessmango.mangohud.svg to /home/adam/MangoHud/build/release/usr/share/icons/hicolor/scalable/apps
Installing /home/adam/MangoHud/data/MangoHud.conf to /home/adam/MangoHud/build/release/usr/share/doc/mangohud
Installing /home/adam/MangoHud/data/presets.conf to /home/adam/MangoHud/build/release/usr/share/doc/mangohud
Installing /home/adam/MangoHud/bin/mangoplot.py to /home/adam/MangoHud/build/release/usr/bin
ninja: Entering directory `build/meson32'
[2/5] Linking target src/libMangoHud_dlsym.so
FAILED: src/libMangoHud_dlsym.so 
g++ -m32  -o src/libMangoHud_dlsym.so src/libMangoHud_dlsym.so.p/elfhacks.cpp.o src/libMangoHud_dlsym.so.p/real_dlsym.cpp.o src/libMangoHud_dlsym.so.p/hook_dlsym.cpp.o -Wl,--as-needed -Wl,--no-undefined -Wl,-O1 -shared -fPIC -Wl,--start-group -Wl,-soname,libMangoHud_dlsym.so -Wl,-rpath,/usr/lib64 -Wl,-rpath-link,/usr/lib64 src/libMangoHud.a subprojects/imgui-1.89.9/libimgui.a subprojects/spdlog-1.13.0/src/libspdlog.a subprojects/implot-0.16/libimplot.a -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--exclude-libs,ALL -static-libstdc++ -Wl,--version-script,/home/adam/MangoHud/src/mangohud.version /usr/lib64/libwayland-client.so /usr/lib64/libxkbcommon.so -Wl,--end-group -pthread
/usr/bin/ld: /usr/lib64/libwayland-client.so: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
[3/5] Linking target src/libMangoHud.so
FAILED: src/libMangoHud.so 
g++ -m32  -o src/libMangoHud.so src/libMangoHud.a.p/vulkan.cpp.o src/libMangoHud.a.p/mesa_util_os_socket.c.o src/libMangoHud.a.p/mesa_util_os_time.c.o src/libMangoHud.a.p/hud_elements.cpp.o src/libMangoHud.a.p/overlay.cpp.o src/libMangoHud.a.p/overlay_params.cpp.o src/libMangoHud.a.p/font.cpp.o src/libMangoHud.a.p/keybinds.cpp.o src/libMangoHud.a.p/font_unispace.c.o src/libMangoHud.a.p/logging.cpp.o src/libMangoHud.a.p/config.cpp.o src/libMangoHud.a.p/gpu.cpp.o src/libMangoHud.a.p/blacklist.cpp.o src/libMangoHud.a.p/file_utils.cpp.o src/libMangoHud.a.p/cpu.cpp.o src/libMangoHud.a.p/memory.cpp.o src/libMangoHud.a.p/iostats.cpp.o src/libMangoHud.a.p/notify.cpp.o src/libMangoHud.a.p/elfhacks.cpp.o src/libMangoHud.a.p/real_dlsym.cpp.o src/libMangoHud.a.p/pci_ids.cpp.o src/libMangoHud.a.p/battery.cpp.o src/libMangoHud.a.p/control.cpp.o src/libMangoHud.a.p/device.cpp.o src/libMangoHud.a.p/amdgpu.cpp.o src/libMangoHud.a.p/intel.cpp.o src/libMangoHud.a.p/msm.cpp.o src/libMangoHud.a.p/nvml.cpp.o src/libMangoHud.a.p/loaders_loader_nvml.cpp.o src/libMangoHud.a.p/loaders_loader_nvctrl.cpp.o src/libMangoHud.a.p/nvctrl.cpp.o src/libMangoHud.a.p/loaders_loader_x11.cpp.o src/libMangoHud.a.p/shared_x11.cpp.o src/libMangoHud.a.p/wayland_hook.cpp.o src/libMangoHud.a.p/wayland_keybinds.cpp.o src/libMangoHud.a.p/dbus.cpp.o src/libMangoHud.a.p/loaders_loader_dbus.cpp.o src/libMangoHud.a.p/meson-generated_.._.._vk_enum_to_str.c.o -Wl,--as-needed -Wl,--no-undefined -Wl,-O1 -shared -fPIC -Wl,--start-group -Wl,-soname,libMangoHud.so -Wl,-rpath,/usr/lib64 -Wl,-rpath-link,/usr/lib64 src/libMangoHud.a subprojects/imgui-1.89.9/libimgui.a subprojects/spdlog-1.13.0/src/libspdlog.a subprojects/implot-0.16/libimplot.a -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--exclude-libs,ALL -static-libstdc++ -Wl,--version-script,/home/adam/MangoHud/src/mangohud.version /usr/lib64/libwayland-client.so /usr/lib64/libxkbcommon.so -Wl,--end-group -pthread
/usr/bin/ld: /usr/lib64/libwayland-client.so: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
[4/5] Linking target src/libMangoHud_opengl.so
FAILED: src/libMangoHud_opengl.so 
g++ -m32  -o src/libMangoHud_opengl.so src/libMangoHud_opengl.so.p/gl_glad.c.o src/libMangoHud_opengl.so.p/gl_gl_renderer.cpp.o src/libMangoHud_opengl.so.p/gl_gl_hud.cpp.o src/libMangoHud_opengl.so.p/gl_inject_egl.cpp.o src/libMangoHud_opengl.so.p/loaders_loader_glx.cpp.o src/libMangoHud_opengl.so.p/gl_inject_glx.cpp.o src/libMangoHud_opengl.so.p/hud_elements.cpp.o src/libMangoHud_opengl.so.p/overlay.cpp.o src/libMangoHud_opengl.so.p/overlay_params.cpp.o src/libMangoHud_opengl.so.p/font.cpp.o src/libMangoHud_opengl.so.p/keybinds.cpp.o src/libMangoHud_opengl.so.p/font_unispace.c.o src/libMangoHud_opengl.so.p/logging.cpp.o src/libMangoHud_opengl.so.p/config.cpp.o src/libMangoHud_opengl.so.p/gpu.cpp.o src/libMangoHud_opengl.so.p/blacklist.cpp.o src/libMangoHud_opengl.so.p/file_utils.cpp.o src/libMangoHud_opengl.so.p/cpu.cpp.o src/libMangoHud_opengl.so.p/memory.cpp.o src/libMangoHud_opengl.so.p/iostats.cpp.o src/libMangoHud_opengl.so.p/notify.cpp.o src/libMangoHud_opengl.so.p/elfhacks.cpp.o src/libMangoHud_opengl.so.p/real_dlsym.cpp.o src/libMangoHud_opengl.so.p/pci_ids.cpp.o src/libMangoHud_opengl.so.p/battery.cpp.o src/libMangoHud_opengl.so.p/control.cpp.o src/libMangoHud_opengl.so.p/device.cpp.o src/libMangoHud_opengl.so.p/amdgpu.cpp.o src/libMangoHud_opengl.so.p/intel.cpp.o src/libMangoHud_opengl.so.p/msm.cpp.o src/libMangoHud_opengl.so.p/nvml.cpp.o src/libMangoHud_opengl.so.p/loaders_loader_nvml.cpp.o src/libMangoHud_opengl.so.p/loaders_loader_nvctrl.cpp.o src/libMangoHud_opengl.so.p/nvctrl.cpp.o src/libMangoHud_opengl.so.p/loaders_loader_x11.cpp.o src/libMangoHud_opengl.so.p/shared_x11.cpp.o src/libMangoHud_opengl.so.p/wayland_hook.cpp.o src/libMangoHud_opengl.so.p/wayland_keybinds.cpp.o src/libMangoHud_opengl.so.p/dbus.cpp.o src/libMangoHud_opengl.so.p/loaders_loader_dbus.cpp.o src/libMangoHud_opengl.so.p/mesa_util_os_socket.c.o src/libMangoHud_opengl.so.p/mesa_util_os_time.c.o -Wl,--as-needed -Wl,--no-undefined -Wl,-O1 -shared -fPIC -Wl,--start-group -Wl,-soname,libMangoHud_opengl.so -Wl,-rpath,/usr/lib64 -Wl,-rpath-link,/usr/lib64 src/libMangoHud.a subprojects/imgui-1.89.9/libimgui.a subprojects/spdlog-1.13.0/src/libspdlog.a subprojects/implot-0.16/libimplot.a -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--exclude-libs,ALL -static-libstdc++ -Wl,--version-script,/home/adam/MangoHud/src/mangohud.version /usr/lib64/libwayland-client.so /usr/lib64/libxkbcommon.so -Wl,--end-group -pthread
/usr/bin/ld: /usr/lib64/libwayland-client.so: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

**Expected behavior**
I expected the program to build.

it seems there are issues with  src/libMangoHud_dlsym.so, src/libMangoHud.so, and src/libMangoHud_opengl.so

I have attempted solutions suggested on this thread with minimal luck: https://github.com/flightlessmango/MangoHud/issues/1083

**Screenshots**
![Screenshot from 2024-03-29 01-02-32](https://github.com/flightlessmango/MangoHud/assets/91484770/59fe41b5-bb86-4893-bdbf-dbd5a3317352)

**Additional context**
I previously attempted and uninstalled a flatpack version of MangoHud, that was able to run , but not in any game.

Thank you for your assistance.

**Comment by flightlessmango** [comment]
This is same issue as #1265
namely `/usr/bin/ld: /usr/lib64/libwayland-client.so: error adding symbols: file in wrong format`
continue in that thread
