### ISSUE TITLE
Mangohud does work only in "Celeste"

### ISSUE THREAD

**Issue by Even749** [flightlessmango/MangoHud#1273]
**Describe the bug**
Mangohud works only in Celeste of all Steam games i've tried (including Hades Vulkan, Dredge, Path of Exile, BG3)

**List relevant hardware/software information**
- Pop!_OS 22.04 LTS
- runtime/org.freedesktop.Platform.VulkanLayer.MangoHud/x86_64/23.08
- GTX 2080 Super

**To Reproduce**
1. mangohud %command% as launch option
2. start the game, the overlay does not show up

**Expected behavior**
overlay visualization

**Additional context**
Both steam and mangohud are as flatpaks.
Also tried running : MANGOHUD=1 ENABLE_VKBASALT=1 %command% ; MANGOHUD=1 ; mangohud --dlsym %command%

**Comment by flightlessmango** [comment]
Likely this issue https://github.com/ValveSoftware/steam-runtime/issues/662
