### ISSUE TITLE
Unable to install x32 package on ubuntu via apt.

### ISSUE THREAD

**Issue by bloock-w** [flightlessmango/MangoHud#1274]
**Describe the bug**
Unable to install x32 package due to it missing, apparently.

**List relevant hardware/software information**
- Ubuntu 22.04.4 LTS
- 0.6.5-2
- gtx 1060 6gb

**To Reproduce**
1. Go into terminal.
2. Type "sudo apt install mangohud:i386", press enter.
3. error occures: "E: Unable to locate package mangohud:i386".

**Expected behavior**
x32 package getting installed.

**Comment by flightlessmango** [comment]
Ubuntu doesn't make 32bit package available by default, you have to enable it.
But the mangohud package in apt is extremely out of date, you're likely going to encounter issues using it.
Instead follow the directions in readme on how to install the latest release
