### ISSUE TITLE
Flatpak MangoHud Issue: Inconsistent Functionality Across Games

### ISSUE THREAD

**Issue by fagnerpatricio** [flightlessmango/MangoHud#1275]
#### Problem Description

Hello, I'm having an issue with MangoHud, in the Flatpak version. I've tested it so far on 2 games and in one of them it works normally, but not in the other.

#### Hardware and Software Environment List

- Operating System: Debian GNU/Linux 12
  
- KDE Plasma Version: 5.27.5
  
- KDE Frameworks Version: 5.103.0
  
- Qt Version: 5.15.8
  
- Kernel Version: 6.1.0-18-amd64 (64-bit)
  
- Graphics Platform: Wayland
  
- Processors: 12 × 11th Gen Intel® Core™ i5-11400 @ 2.60GHz
  
- Memory: 15.4 GiB of RAM
  
- Graphics Processor: AMD Radeon RX 6700 XT
  
- Manufacturer: Micro-Star International Co., Ltd.
  
- Product Name: MS-7D19
  
- System Version: 1.0
  

#### Command to Install Flatpaks

```
flatpak install flathub com.valvesoftware.Steam com.valvesoftware.Steam.CompatibilityTool.Boxtron com.github.Matoking.protontricks com.valvesoftware.SteamLink org.freedesktop.Platform.VulkanLayer.MangoHud org.freedesktop.Platform.VulkanLayer.vkBasalt org.freedesktop.Platform.VulkanLayer.gamescope
```

I followed the tutorial from this page with some updates:

> [Comunidade Steam :: Guia :: Using Steam in a Flatpak](https://steamcommunity.com/sharedfiles/filedetails/?l=brazilian&id=2615011323&searchtext=Search+Steam+for+Linux+Guides)

#### Tested Games

1. Highway Blossoms ([Highway Blossoms no Steam](https://store.steampowered.com/app/451760/Highway_Blossoms/))
  
2. Far Cry® 6 ([Far Cry® 6 no Steam](https://store.steampowered.com/app/2369390/Far_Cry_6/))
  
#### Proton Versions Tested

1. GE-Proton9-2
2. Proton Experimental
3. Proton 9.0 (Beta)
4. Proton 8.0-5

#### Command Used to Start the Games

```
mangohud %command%
```

It only works like this; using MANGOHUD=1 or globally using the command below doesn't work.

```
flatpak override --user --env=MANGOHUD=1 com.valvesoftware.Steam
```

The MangoHud.conf file is located at:

> ~/.var/app/com.valvesoftware.Steam/.config/MangoHud/MangoHud.conf

I'm using the unmodified file located at:

> https://raw.githubusercontent.com/flightlessmango/MangoHud/master/data/MangoHud.conf

#### Steps to Reproduce the Problem:

1. Install the Flatpaks with the above command.
2. Install the mentioned games.
3. Run with the command "mangohud %command%".

![2024-03-30_23-39](https://github.com/flightlessmango/MangoHud/assets/1405203/91a4982d-54c8-4068-bb17-83ae2828fe3f)
![20240330232623_1](https://github.com/flightlessmango/MangoHud/assets/1405203/e9121a4c-373f-4a73-97a7-6bd3f508977f)

**Comment by Leopard1907** [comment]
https://github.com/ValveSoftware/steam-runtime/issues/662

Not a Mangohud issue.

**Comment by fagnerpatricio** [comment]
Thank you, I will follow this other topic.
