### ISSUE TITLE
MangoHud not working with Minecraft Java

### ISSUE THREAD

**Issue by Letus252** [flightlessmango/MangoHud#1277]
**Describe the bug**
I'm trying to run MangoHud with Minecraft, but I can't get it to work. I've tried "mangohud --dlsym minecraft-launcher" but it does not show the overlay, and "MANGOHUD_DLSYM=1 mangohud minecraft-launcher" throws a wall of errors (and launcher is just a white box). I also tired using mangohud with steam (CS2) and it does work correctly.

**List relevant hardware/software information**
- Arch KDE plasma 6.0.3
- MangoHud version v0.7.1
- GPU RX 6700 XT
- OpenGL version string: 4.6 (Compatibility Profile) Mesa 24.0.3-arch1.2

I'm using default Minecraft client (downloaded using yay). I added screenshot of the errors made by the second command (they seem to repeat infinity).

![mangohuderror](https://github.com/flightlessmango/MangoHud/assets/117117674/0a801719-58be-4de2-8056-e0b3a8e581fc)

**Comment by zastrixarundell** [comment]
Shouldn't you set MangoHud on the game level instead of the launcher level?

**Comment by Letus252** [comment]
> Shouldn't you set MangoHud on the game level instead of the launcher level?

I don't know how would you do that. I saw reddit post about this topic, but the guy was using cracked launcher. In the post there was also this command: "mangohud --dlsym java -jar launcher.jar" but I have no idea what "launcher.jar" refers to. (And you can't just launch jar from 'version' folder).

**Comment by flightlessmango** [comment]
Should be fixed here 3f0ecf769de461ddd99be536b64e4626a6f83770 and minecraft appears to require `--dlsym`

**Comment by flightlessmango** [comment]
Yes it's going to look a bit wonky as the fix I implemented is just a hack.
Hopefully someone can resolve this better in the future, but for now that is expected
