### ISSUE TITLE
Feature Request: Show GPU Performance mode

### ISSUE THREAD

**Issue by ItzSelenux** [flightlessmango/MangoHud#1279]
I know and already have "`exec=echo -n "$(</sys/class/drm/card0/device/power_dpm_force_performance_level) performance`" in my MangoHud configuration. However, when playing games with Proton, I can't see the performance level. I think it's useful to know and care about the performance level because:

In lightweight games, switching to low-performance mode can help lower temperatures.
If a game runs with a low framerate, checking if the performance is not set to low performance mode could be beneficial.
![Untitled](https://github.com/flightlessmango/MangoHud/assets/74371741/5553adb1-4aee-46b7-a556-81f715c020f3)

**Comment by flightlessmango** [comment]
This should work under proton now, reopen if not
