### ISSUE TITLE
NVidia Optimus missing GPU stats NVML / XNVCtrl

### ISSUE THREAD

**Issue by VortexAcherontic** [flightlessmango/MangoHud#128]
As suggested by @flightlessmango over in #114  I'll create a new issue regarding this.

It seems that on Optimus Notebooks which do not have support for NVML there are some GPU stats Missing:

- GPU Core utilizaiton
- GPU Clock
- VRAM clock

Specs:

- dGPU: NVidia GT 730M (440.86)
- iGPU: Intel HD 3000 (not used, disabled by suse-prime)
- OS: openSUSE Tumbleweed
- Optimus support by: Optimus Manager (aka. suse-prime / prime-select)

I also already tried to set the PCI device without success using:

lspci -D
````
0000:00:00.0 Host bridge: Intel Corporation 3rd Gen Core processor DRAM Controller (rev 09)
0000:00:01.0 PCI bridge: Intel Corporation Xeon E3-1200 v2/3rd Gen Core processor PCI Express Root Port (rev 09)
0000:00:01.1 PCI bridge: Intel Corporation Xeon E3-1200 v2/3rd Gen Core processor PCI Express Root Port (rev 09)
0000:00:02.0 VGA compatible controller: Intel Corporation 3rd Gen Core processor Graphics Controller (rev 09)
0000:00:14.0 USB controller: Intel Corporation 7 Series/C210 Series Chipset Family USB xHCI Host Controller (rev 04)
0000:00:16.0 Communication controller: Intel Corporation 7 Series/C216 Chipset Family MEI Controller #1 (rev 04)
0000:00:1a.0 USB controller: Intel Corporation 7 Series/C216 Chipset Family USB Enhanced Host Controller #2 (rev 04)
0000:00:1b.0 Audio device: Intel Corporation 7 Series/C216 Chipset Family High Definition Audio Controller (rev 04)
0000:00:1c.0 PCI bridge: Intel Corporation 7 Series/C216 Chipset Family PCI Express Root Port 1 (rev c4)
0000:00:1c.3 PCI bridge: Intel Corporation 7 Series/C216 Chipset Family PCI Express Root Port 4 (rev c4)
0000:00:1d.0 USB controller: Intel Corporation 7 Series/C216 Chipset Family USB Enhanced Host Controller #1 (rev 04)
0000:00:1f.0 ISA bridge: Intel Corporation HM76 Express Chipset LPC Controller (rev 04)
0000:00:1f.2 SATA controller: Intel Corporation 7 Series Chipset Family 6-port SATA Controller [AHCI mode] (rev 04)
0000:00:1f.3 SMBus: Intel Corporation 7 Series/C216 Chipset Family SMBus Controller (rev 04)
0000:01:00.0 3D controller: NVIDIA Corporation GK208M [GeForce GT 730M] (rev a1)
0000:03:00.0 Network controller: Intel Corporation Centrino Wireless-N 135 (rev c4)
0000:04:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 06)
````

-> `0000:01:00.0 3D controller: NVIDIA Corporation GK208M [GeForce GT 730M] (rev a1)`

`MANGOHUD_PCI_DEV=0000:01:00.0`

I tried the official 0.3.1 release as well as the latest development branch build

Also with the latest development branch build (while I write this issue) there are no GPU stats at all, not even those who where shown in the 0.3.1 release.

According to flightlessmango this might be an NVML / XNVCtrl issue since my GPU seem not to support NVML at all.

**Comment by VortexAcherontic** [comment]
0.3.5 fixed this than you very much @flightlessmango !

![Screenshot_20200504_135323](https://user-images.githubusercontent.com/11244092/80963176-ba081680-8e0e-11ea-941f-23367064fffa.png)

**Comment by NerosTie** [comment]
Not for me.

The error is still the same:
```MANGOHUD: XNVCtrl didn't find the correct display```

@VortexAcherontic That's because you're using "prime-select" and not the "official" way from Nvidia:

https://download.nvidia.com/XFree86/Linux-x86_64/435.17/README/primerenderoffload.html

**Comment by jackun** [comment]
Is it even possible to use XNVCtrl with plain prime? It checks for NVIDIA X extension and doubt these exist in Intel X session..

**Comment by NerosTie** [comment]
Tested with nvtop:

![Screenshot_20200504_142148](https://user-images.githubusercontent.com/4572452/80965336-a2329180-8e12-11ea-9c36-27895463fe1c.png)

It detects the memory usage, the temperature, but nothing else. So, maybe not?

If it's the case, would it be possible to use the same method as the hud from dxvk?

**Comment by NerosTie** [comment]
With 0.5.1, the issue is still here... @VortexAcherontic does it work for you?

**Comment by flightlessmango** [comment]
It's not possible to use the same method as dxvk hud. That is being calculated within the dxvk renderer, we do not have access to that information

**Comment by NerosTie** [comment]
So there is no way to display the GPU usage and the temperature with my configuration?
