### ISSUE TITLE
Mangoapp doesn't shut down after the running program/app closes

### ISSUE THREAD

**Issue by stele95** [flightlessmango/MangoHud#1284]
**Describe the bug**
After starting a mangoapp instance with ``gamescope -- sh -c "mangoapp& vkcube"`` or any other program in the same way and then closing that program/app, mangoapp instance remains running.

**List relevant hardware/software information**
- Linux Distribution: EndeavourOS
- MangoHud version: latest git installed from AUR mangohud-git package

**To Reproduce**
1. Run ``gamescope -- sh -c "mangoapp& vkcube"`` from the terminal
2. Close vkcube
3. Repeat steps 1. and 2. a couple times
4. Check running processes

**Expected behavior**
mangoapp should shut down after the program/app is closed

**Screenshots**
List of running processes after repeating reproduction steps 1. and 2. a couple of times
![Screenshot_20240407_111008](https://github.com/flightlessmango/MangoHud/assets/26225081/c31ccceb-9b3c-4ea4-9410-9c84eec3f5f6)

**Comment by flightlessmango** [comment]
use gamescopes `--mangoapp` argument instead

**Comment by stele95** [comment]
The behaviour is the same. Mangoapp still stays after shutting down gamescope instance.

Additional info that might be important, I'm on KDE Plasma 6 under Wayland.

**Comment by flightlessmango** [comment]
what's the full command you're using?

**Comment by stele95** [comment]
``gamescope --mangoapp -- vkcube``

**Comment by flightlessmango** [comment]
What git version of mangohud and gamescope are you using?

**Comment by flightlessmango** [comment]
Since they are git versions they install whatever is the latest commit when you decided to install, which means only you know what git version it actually is.
With some luck `pacman -Q mangohud gamescope` should tell us which commit it is
or you can reinstall both packages and check which commit was latest at the time

**Comment by stele95** [comment]
mangohud-git 0.7.2.rc2.r22.g1e13c38-1
gamescope-git 3.14.2.r97.g41389f7-1

**Comment by MacharaStormwing** [comment]
I have a similar issue but with steam:
When I add mangohud &command% to the launch parameters of the steam game, the game remains in memory and running in background (no gui seen).
I use mangohud v0.7.1 in nobara linux 39.

**Comment by flightlessmango** [comment]
@MacharaStormwing this is likely a completely different issue, please create a new issue for it

**Comment by kodemeister** [comment]
I had the same issue on `gamescope` 3.14.3 from Arch repos. Installing `gamescope-git` package from AUR fixed stale `mangoapp` processes.

**Comment by flightlessmango** [comment]
While using `gamescope --mangoapp`, gamescope is handling starting and terminating mangoapp, so it should probably be reported there as well if it's still an issue

**Comment by flightlessmango** [comment]
This *should* be resolved by using `gamescope --mangoapp`
