### ISSUE TITLE
GPU Information Disappears Right After Launch

### ISSUE THREAD

**Issue by abogdanovich1** [flightlessmango/MangoHud#1287]
**Describe the bug**
After installing MangoHud, and setting Steam to launch the game with the `mangohud %command%` option in properties, the game launches with the HUD with the correct setup (GPU info top row, CPU info middle row, Frame info bottom row) but within 2 seconds max, the GPU information (% usage, temperature)  disappears, moving the rest of the rows up.

**List relevant hardware/software information**
- Linux Distribution: Pop!_OS 22.04 LTS (64 Bit) (Used NVIDIA preloaded install)
- Latest version of Steam
- MangoHud version: v0.7.1
- GPU: NVIDIA RTX4080

**To Reproduce**
1. Set launch options in steam to `mangohud %command%`
2. Set mangohud config to include "gpu_stats", "gpu_temp", "cpu_stats", "cpu_temp"
3. Launch a game with this configuration (I used Helldivers 2)

**Expected behavior**
Expect the GPU information to stay put, or not be displayed at all.

**Screenshots**
*Launch*

![IMG_0033](https://github.com/flightlessmango/MangoHud/assets/21229169/b1d2a353-55af-4ca2-b59f-59d525d6b21d)

*About a second or two after*
![IMG_0034](https://github.com/flightlessmango/MangoHud/assets/21229169/39d41fe0-56c9-43aa-b84b-059abb441289)

**Additional context**
Fairly fresh install of PopOS (less than a week old or so) with a similarly fresh install of Steam/Helldivers/Relevant proton stuff. Followed installation instructions in this repo's readme. I tried getting a screen recording of this but screen capture stops when game launches and wont get it on video. Took a video with my phone and can provide that/any logs when needed!

**Comment by flightlessmango** [comment]
Set `MANGOHUD_LOG_LEVEL=DEBUG` and `PROTON_LOG=1` then post the log here

**Comment by bakkkker** [comment]
@flightlessmango I have the same bug, here are my logs  [https://paste.gloriouseggroll.tv/?7a539a11812a5aec#DXU71SChx2BnBVhEhoxSScLEaPdio7975wt6yDUSeBnk](url)

**Comment by bakkkker** [comment]
[steam-553850.log](https://github.com/flightlessmango/MangoHud/files/15109738/steam-553850.log)

**Comment by gort818** [comment]
Possible it is trying to read from the IGPU for some reason?

**Comment by zastrixarundell** [comment]
Most likely that. I have a similar issue, albeit not this one and it's reporting the wrong value for Metro Exodus. I'll try to disable my iGPU and retest it

**Comment by flightlessmango** [comment]
I believe this is fixed in 0.7.2, reopen if it's still an issue
