### ISSUE TITLE
Minecraft crashes on logging hotkey

### ISSUE THREAD

**Issue by holybaechu** [flightlessmango/MangoHud#1289]
**Describe the bug**
When I press logging hotkey(I set it to Shift_L+F4), It crashes the game

**List relevant hardware/software information**
- Linux Distribution: 6.8.4-zen1-1-zen Arch Linux
- MangoHud version: 0.7.1-1
- GPU: NVIDIA GeForce RTX 3060 Lite Hash Rate

**To Reproduce**
1. Install Minecraft 1.19.2 with Java 17/21 in Prism Launcher
2. Enable MangoHud option in Prism Launcher settings
3. Play Minecraft
4. Hit logging hotkey you have set to
5. Crashes

**Expected behavior**
Should start logging the game

**Screenshots**
No screenshot provided

**Additional context**
Minecraft Logs: https://mclo.gs/PhTfr7v

**Comment by holybaechu** [comment]
It looks like this only happens when hotkey is set to "Shift_L+F4"

**Comment by flightlessmango** [comment]
This is because Shift_L+F4 is assigned by default to reloading the config, you're reloading the config and starting/stopping a benchmark at the same time which is causing the crash.
Now the crash is a bug that can be fixed, but you probably also didn't intend this behavior of doing two functions
