### ISSUE TITLE
Monado XR runtime segfaults when hooked by mangohud

### ISSUE THREAD

**Issue by SpookySkeletons** [flightlessmango/MangoHud#1295]
**Describe the bug**
Mangohud appears to try and hook the actual monado direct mode VR compositor and this results in a pretty nasty segfault code 139.

**To Reproduce**
1. Enable mangohud globally through etc environment 
2. Start monado-service

**Expected behavior**
Mangohud should ignore the VR compositor of Monado

Can we quirk out the VR compositor here?

**Comment by Leopard1907** [comment]
You can try blacklisting that process.

https://github.com/flightlessmango/MangoHud/blob/master/src/blacklist.cpp#L32

**Comment by flightlessmango** [comment]
should be fixed here #1296

**Comment by SpookySkeletons** [comment]
Thanks for the quick turnaround on the PR!
