### ISSUE TITLE
Shift_R+F10 no longer switches presets

### ISSUE THREAD

**Issue by kakra** [flightlessmango/MangoHud#1298]
**Describe the bug**
Since at least version 0.7, cycling presets via hotkey no longer works. Most likely, the problem already existed in 0.6.x because when I noticed the problem, I updated to 0.7 to see if it is fixed. I haven't used MangoHud in a while before this so I cannot exactly name the first affected version.

I never used any custom config files, `~/.config/MangoHud/` is empty. I'm installing from git sources with `ninja -C build install`.

**List relevant hardware/software information**
- Gentoo Linux
- MangoHud 0.7.2-rc3 (and also any other 0.7.x version, probably most recent 0.6.x)
- NVIDIA RTX 3080 Ti
- games exclusively run through Steam (and Proton for that matter)

**To Reproduce**
1. Clear configs in `~/.config/MangoHud/`
2. Set `MANGOHUD_CONFIG="fps_limit=60+30+0,fps_limit_method=early"`
3. Start a game, the default preset will show up in the upper left corner
4. Press Shift_R+F10 to cycle through the presets

**Expected behavior**
As before some 0.6.x version, I expected Shift_R+F10 to cycle presets. The corner hotkey still works, Shift_R+F12 still works.

**Observed behavior**
Shift_R+F10 no longer cycles presets. It just causes a short lag spike each time I press the key. According to the source code it ships with a set of default presets, and I wouldn't expect setting fps limiter via env variable changing anything about it. Still, there seems to be just one preset since some version I upgraded to.

**Additional context**
There's nothing special. I'm using MangoHud mostly as a very well working FPS limiter for smooth gameplay (using `MANGOHUD_CONFIG` as shown above), and I use the frametime graph to verify this, or adjust game quality settings until gameplay is smooth.

**Comment by flightlessmango** [comment]
Can you try with an up to date version of mangohud? I don't want to chase bugs that have already been fixed. Preferably you try with latest git or 0.7.2-rc3

**Comment by kakra** [comment]
> Can you try with an up to date version of mangohud? I don't want to chase bugs that have already been fixed. Preferably you try with latest git or 0.7.2-rc3

I did... Just before the report, I checked out the latest git and installed it. See:

> * MangoHud 0.7.2-rc3

**Comment by gort818** [comment]
I can confirm the issue, It is only present when using `MANGOHUD_CONFIG` to set options.
