### ISSUE TITLE
Help with OpenGL, I'm not even sure.

### ISSUE THREAD

**Issue by LupusEtFlos** [flightlessmango/MangoHud#1299]
I'm running my games from Heroic Games Launcher, and sometimes using Lutris for Ubisoft's launcher. In some instances, I cannot use Vulkan, because my iGPU doesn't have full support. I merely want to use MangoHUD as an FPS cap, but it won't work for those titles, regardless of what launch parameters or arguments I use. I may be doing it all wrong, please provide some guidance if possible, I'm not sure if this is even the right place...

- Manjaro Linux
- MangoHud 0.7.2-rc3, but it never worked for me like I said
- Intel HD 4400

Thanks, as well as apologies in advance, but I really have no idea what else to try, and I've been debating whether to come here to ask for help or give up, given my past experiences when asking for help were met with disdain or debauchery. I really  just want to cap my FPS to 30 because my iGPU can't keep 60 in most games I try, which is what I am able to do if the games work with Vulkan only, so far.

**Comment by flightlessmango** [comment]
What games aren't working?

**Comment by LupusEtFlos** [comment]
Ziggurat from GOG, which has a native Linux build by the way, but I chose to run the Windows one because said native build was all broken for me. If I attempt to use DXVK, then it's even worse.

Far Cry 3 from Ubisoft's launcher, same deal, using DXVK causes severe stuttering and missing graphics, but at least the overlay worked.

Dead Island Riptide while using its native build, Guns N' Boxes while using the Windows version because the native build is abandoned, and possibly more I haven't yet tested. 

So far, only glxgears and Darkest Dungeon from EGS have a working OpenGL overlay for me without any further tinkering. 

![LkZ5Szg](https://github.com/flightlessmango/MangoHud/assets/95597028/717a94ed-82cd-4afb-8dce-ce255dc89854)

**Comment by Leopard1907** [comment]
Did you try with `mangohud --dlsym` or just `mangohud` ?

**Comment by LupusEtFlos** [comment]
I may be fairly new to this, or I'm just confused as to where do those arguments, but I run them through the Heroic launcher as mentioned. There's a field that reads "Game Arguments (To run after the command)", it's where I've tried both options you've suggested, I've also tried using the environment table MANGOHUD_DLSYM=1 to no success. 

I also forgot to mention, but OpenGL overlay also works on emulators such as Dolphin just fine. I wonder if this is an issue with these games? Perhaps the Proton version I use?  I use Proton 7.0 or a GE version close to that, as most titles fail to boot otherwise on my setup.

Thank you for the replies, by the way.

**Comment by tinkerpunktheprol** [comment]
I came here to solve this problem myself. I'm not really sure why this hasn't been worked out already and included in the wiki of at least one of these tools. MangoHUD and Heroic Launcher have been around for a while, and are both commonly used for GOG games.

Anyways, I'm not sure if you have tried this but it worked for me:

> Go into the settings for the game (where you entered all this stuff) there is a "table" near the bottom where you can enter environment variables. You have to enter 'MANGOHUD' for the variable and '1' for the value and press the plus button to add it.

Your mention of trying the environment variables helped me work it out. When you try to type them into the 'game arguments' box, it tells you about the table.

**Comment by Lassebq** [comment]
Why would you use DXVK on an igpu without vulkan support? Use WineD3D. It translates DirectX to OpenGL, which your would be accelerated in your case.
For Proton append `PROTON_USE_WINED3D11=1` environment variable
And for regular wineprefix you can change library overrides in winecfg for permanent WineD3D or `WINEDLLOVERRIDES="d3d9,d3d10,d3d10_1,d3d10core,d3d11,dxgi=b"` environment variable for a single game.
Also `MANGOHUD_DLSYM=1` is needed for mangohud to show up at all on WineD3D.
