### ISSUE TITLE
HUD displayed by default, and incorrectly on SteamPlay games

### ISSUE THREAD

**Issue by Zeioth** [flightlessmango/MangoHud#13]
When MangoHUD is being installed into the system, games running with SteamPlay will display dxvk hud by default. If you add MANGOHUD=1, then both huds are displayed at the same time.

**HOW TO REPRODUCE**

* Open Steam for Linux, and enable SteamPlay.
* Install Quake Champions, or any other DXVK game.
* Open the game
![2](https://user-images.githubusercontent.com/3357792/73857981-fd66df00-4837-11ea-8722-c6a2140b4611.png)
If you add the env var MONGOHUD=1, it will show both HUDS at the same time.
![3](https://user-images.githubusercontent.com/3357792/73857979-fc35b200-4837-11ea-9dc7-665ff2e042b4.png)

**WHAT WORKS FINE**
Running the game with wine and steam for windows and adding the env var MONGOHUD=1.
![1](https://user-images.githubusercontent.com/3357792/73858026-0eafeb80-4838-11ea-939b-9f4ddec7708d.png)

**Comment by Zeioth** [comment]
**Monkeypatch**
The issue is solved by running the game with both env vars:

    DXVK_HUD=1
    MANGOHUD=1

**Comment by guihkx** [comment]
>games running with SteamPlay will display dxvk hud by default.

The DXVK HUD is **definitely** not enabled by default in Proton/Steam Play. You must have `DXVK_HUD=1` set somewhere.

**Comment by Zeioth** [comment]
Shit, I had it enabled in my user_settings.sample.py under ~/.local/share/Steam/steamapps/common/Proton 4.11

Closing Issue. Thank you guihkx!
