### ISSUE TITLE
MangoHUD causes Vulkan SDK validation layer error

### ISSUE THREAD

**Issue by enveeed** [flightlessmango/MangoHud#130]
I have noticed this while trying out my own vulkan project with MangoHUD and for a while I believed the issue was on my side, but I found out that it is probably caused by the MangoHUD vulkan layer because `vkcube` (from the Vulkan SDK) shows the exact same behavior.

The easiest way to reproduce this is by running `vkcube --validate`  which does not report any validation layer messages, and after that `MANGOHUD=1 vkcube --validate` which outputs the following validation error on each frame:

```
ERROR : VALIDATION - Message Id Number: 307231540 | Message Id Name: VUID-VkImageMemoryBarrier-oldLayout-01197
	Validation Error: [ VUID-VkImageMemoryBarrier-oldLayout-01197 ] Object 0: handle = 0x562396b35780, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x124ffb34 | For VkImage 0x1a000000001a[] you cannot transition the layout of aspect=1 level=0 layer=0 from VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL when the previous known layout is VK_IMAGE_LAYOUT_PRESENT_SRC_KHR. The Vulkan spec states: oldLayout must be VK_IMAGE_LAYOUT_UNDEFINED or the current layout of the image subresources affected by the barrier (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkImageMemoryBarrier-oldLayout-01197)

	Objects - 1
		Object[0] - VK_OBJECT_TYPE_COMMAND_BUFFER, Handle 0x562396b35780
```

This is the interesting bit:

**`For VkImage 0x1a000000001a[] you cannot transition the layout of aspect=1 level=0 layer=0 from VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL when the previous known layout is VK_IMAGE_LAYOUT_PRESENT_SRC_KHR. The Vulkan spec states: oldLayout must be VK_IMAGE_LAYOUT_UNDEFINED or the current layout of the image subresources affected by the barrier`** ([see Vulkan specification](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkImageMemoryBarrier-oldLayout-01197))

This issue does not affect rendering or the functionality of neither the application nor the overlay itself but it is very annoying when trying to use MangoHUD during development of an application as well :)

**My setup:**
- Linux `5.3.0-46-generic` running X11
- Device: NVidia GeForce RTX 2060
- Device driver: NVidia `440.82`
- Vulkan SDK `1.2.135`

**Comment by jackun** [comment]
Doesn't make sense. It is the second layout change from VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL back to VK_IMAGE_LAYOUT_PRESENT_SRC_KHR.

**Comment by DadSchoorse** [comment]
I think I fixed that in upstream mesa: https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/3740

**Comment by jackun** [comment]
Should be fixed
