### ISSUE TITLE
Frame limiter causes freezing/unstable frametimes in The Witcher 3: Wild Hunt

### ISSUE THREAD

**Issue by RaduAvramescu** [flightlessmango/MangoHud#1302]
**Describe the bug**
Using Mangohud's frame limiter, I ran into 2 issues in the application. Here are the issues I faced:
1. The game can completely freeze in the menus (have to force close it).
2. After being in game for like 20 seconds or so, frametimes start fluctuating massively.

**List relevant hardware/software information**
- Linux Distribution: Fedora 40 Beta (KDE spin)
- Kernel: 6.8.7-300.fc40.x86_64
- Mesa: 24.1.0
- MangoHud version: mangohud-0.7.1-3.fc40.x86_64
- Steam: rpm
- Proton: GE-Proton9-4
- KDE Plasma Version: 6.0.3
- KDE Frameworks Version: 6.0.0
- Qt Version: 6.6.2
- Graphics Platform: Wayland
- GPU: AMD RX 7900 XTX

**To Reproduce**
1. Launch the application
2. Select DX12
3. Press "Play"
4. Wait in the main menu until the application completely freezes (should happen in under a minute)
5. For the other issue (the frametimes one), instead of point 4 load up a save game and simply wait for about a minute.

**Expected behavior**
The application should not freeze, and the frametimes should remain consistent and not start fluctuating after a short period.

**Screenshots**
![Screenshot_20240421_115305](https://github.com/flightlessmango/MangoHud/assets/71271545/a41aa01c-dffd-4cb4-a179-a44fedb96568)

**Additional context**
Similar  issues were also reported here: https://github.com/ValveSoftware/Proton/issues/607#issuecomment-2027122530

**Comment by zastrixarundell** [comment]
I don't think that is MangoHud's issue. I have the same issue on KDE6. KDE5 could accept smoother frames which would fix this, KDE6 doesn't. Try to switch to Gnome and test it out. I didn't have this issue there.

**Comment by flightlessmango** [comment]
https://github.com/ValveSoftware/Proton/issues/607#issuecomment-2027803365
As per this comment it appears it's happening with gamescope frame limiter as well.
This makes me think it's probably a wine/proton issue rather than a mangohud one

**Comment by RaduAvramescu** [comment]
Thanks for the suggestion @zastrixarundell. I did a complete reinstall, this time choosing Fedora Workstation 40 instead of the KDE spin.

The Mangohud version is still v0.7.1, kernel is 6.8.8, and Mesa 24.0.6 (though I also tried mesa-git). I was unable to reproduce either of the issues, with Mangohud's framelimiter on. The frames were always smooth, and there was also no freeze regardless of how long I waited in the game's menus.

As such, I think @flightlessmango is correct and it's a Wine/Proton issue, or, more likely, KDE one. The fact that it happens with Gamescope's frame limiter also points in the direction that it's not Mangohud at fault.

I'm closing this issue and will refer to this comment on the Proton thread. Thanks to both of you!

**Comment by Mershl** [comment]
I've ran a few tests on GNOME (wayland) and while I don't see the freezes, I still "see" an unstable frametime graph.

1. Set an `fps_limit` in mangohud (97 in my case)
1. Start Witcher 3 (next-gen latest patch). Make sure it's the DX12 version and the game is in Fullscreen. (Tested Ultra preset, Vsync disabled)
1. Choose New Game -> "Blood and Wine Only" -> any difficulty
1. Ride slowly into the village just ahead of you
1. After 10 seconds mangohud's frame graph will show a jigsaw pattern ranging from 0.4ms to 27.0ms
1. The game feels perfectly fine and nothing like the graph suggests. Using ALT+TAB (while the game is still running) shows that gnome-shell itself is permanently stuttering - exactly like the frametime graph. Again: the gameplay does not show any stuttering and is perfectly smooth.

![image](https://github.com/flightlessmango/MangoHud/assets/520251/f6477cf6-ec46-4dfb-a134-feecd7e63b6f)

Tested on Fedora 40, Gnome 46.1, wayland session, 7900XTX. Issue is seen with and without VRR enabled.

**Comment by RaduAvramescu** [comment]
@Mershl Okay, this is interesting.

Actually, I have unstable frametimes after a while as well, but I get that regardless of VRR setting, and also I don't need to have a frame limit on. That said, just like you, there is no difference in terms of how smooth the game actually feels even after that point.

This was not my experience on KDE (the frametimes were both unstable and the game wasn't smooth, and of course the main issue there is that the game would freeze).

I don't think this is Mangohud related though, especially as it happens without limiting the frames for me.

**Comment by Mershl** [comment]
> I don't think this is Mangohud related though, especially as it happens without limiting the frames for me.

You're absolutely right. The issue is seen with and without framelimit. And with and without mangohud.

Still interesting that framegraph shows the stuttering of the shell, which is not perceived in gameplay.

**Comment by arthuralvesdev** [comment]
I am seeing a similar freeze in The Witcher 3 Next-Gen running in DX12 mode.

The image completely freezes, but the music continues playing. The `witcher3.exe` process remains alive. After alt-tabbing away from the frozen game, I observed no GPU activity from `witcher3.exe` across three consecutive `nvidia-smi
pmon` samples. The process was sleeping in `ntsync_schedule`. I found no NVIDIA Xid/NVRM error in the kernel log.

### System information

- Distribution: CachyOS
- Kernel: `7.2.2-1-cachyos`
- Desktop: KDE Plasma `6.7.4`
- Session: Wayland
- GPU: NVIDIA GeForce RTX 4070
- NVIDIA driver: `610.57.04`
- MangoHud: `0.8.4-1+`
- Proton: Experimental `11.0-20260826`
- Game renderer: DX12 / VKD3D-Proton
- Primary display: 1920x1080 at 143.98 Hz
- Secondary display: 1920x1080 at 60 Hz
- VRR: disabled

Relevant MangoHud configuration:

```ini
fps_limit_method=early
fps_limit=0,60
toggle_fps_limit=Control_L+z
show_fps_limit
 ```                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                            
 At this point I cannot confirm whether fps_limit_method=early specifically causes the freeze, or whether this is the broader KDE/Wayland/Proton frame-limiting issue discussed here. I also have not yet established a fully consistent    
 reproduction interval.                                                                                                                                                                                                                     
                                                                                                                                                                                                                                            
 The symptom does appear very similar to the original report: rendering stops completely while the game process and audio remain active.
