### ISSUE TITLE
[Feature Request] Add an option to shorten device names for battery reporting

### ISSUE THREAD

**Issue by CNR0706** [flightlessmango/MangoHud#1306]
Some devices have ridiculously long names that partly cover the actual battery indicator in MangoHud (looking at you Logitech).

It would be nice to have an option to shorten these or perhaps replace them with a customized name. Right now my MangoHud looks pretty messy because of this.

![image](https://github.com/flightlessmango/MangoHud/assets/133519510/ce4efc06-e2da-4764-8cd6-e1e268f3e057)

**Comment by gort818** [comment]
Yeah that looks bad, I might just set a character limit to truncate it. Or just stop using device name and replace with `Logitech Mouse`

**Comment by gort818** [comment]
Fixed here 7497b1da3f5874139839ecef562a015c49f4e400

I replaced the device name with `LOGI MOUSE/KB` until I find something more elegant.

**Comment by CNR0706** [comment]
Awesome, thank you!
