### ISSUE TITLE
Mangohud showing frozen cpu frequencies

### ISSUE THREAD

**Issue by robinustream** [flightlessmango/MangoHud#1308]
**Describe the bug**
CPU frequency clocks are frozen.

**List relevant hardware/software information**
- Distro: Solus KDE
- Version: 0.7.1
- GPU: 7800XT
- CPU: 5800X3D
- Motherboard: Gigabyte X470 Ultra Gaming with F64 bios.

**To Reproduce**
1. Open game with mangohud enabled.
2. Show mangohud.
3. See frozen clock frequency.

**Expected behavior**
Mangohud showing up to date cpu frequencies.

**Screenshots**
Example screenshot 1:
![Screenshot_20240425_184824](https://github.com/flightlessmango/MangoHud/assets/82940771/73b4eae5-1b1b-4e05-8f7e-95c5539b3f0c)

Example screenshot 2(made 5 seconds after screenshot 1):
![Screenshot_20240425_184844](https://github.com/flightlessmango/MangoHud/assets/82940771/8cce1c26-b1e1-4341-a24d-f72bee94e81b)

**Additional context**
It used to work before. I am unsure if the recent bios update broke it, latest kernel, latest mangohud etc. 
The same behavior is seen across multiple distros (tested with arch, bazzite as well).

**Comment by gort818** [comment]
Is the issue with Mangohud?
what does this show `watch grep MHz /proc/cpuinfo`

**Comment by robinustream** [comment]
![image](https://github.com/flightlessmango/MangoHud/assets/82940771/a3017dce-e693-4e69-83ba-218742506a9b)

**Comment by gort818** [comment]
hmm, what about `cat /proc/cpuinfo`

**Comment by robinustream** [comment]
I reset my CMOS and it seems to have been fixed. Closing

**Comment by robinustream** [comment]
I reset my CMOS and it seems to have been fixed. Closing
