### ISSUE TITLE
Steam launched game not displaying correct information

### ISSUE THREAD

**Issue by BNelson986** [flightlessmango/MangoHud#1311]
**Describe the bug**
When launching Helldivers 2 through Steam, GPU info is not available and 'gamemode' shows off even if "gamemoderun" is manually executed in a terminal. 

**List relevant hardware/software information**
- Linux Distribution - Pop!_OS 22.04
- MangoHud version - compiled from source
- GPU - NVIDIA RTX 4050 

**To Reproduce**
1. Go to 'Steam'
2. Click on 'Helldivers 2' -> 'Play'
3. Game loads correctly
4. See missing overlay information

**Expected behavior**
Expecting overlay output similar to what is displayed in image (2).

**Screenshots**
(1) In-game overlay
![Screenshot from 2024-04-27 21-56-19](https://github.com/flightlessmango/MangoHud/assets/106991381/27348c71-7ba3-4b34-bb7f-353a6db0dbfe)

(2) "mangohud vkcube" overlay:
![Screenshot from 2024-04-27 21-57-24](https://github.com/flightlessmango/MangoHud/assets/106991381/4039c784-6e61-43f5-8fc2-309fd29eddf0)

**Additional context**
Attempted placing custom config file in the following locations with the same results:
(1) "/home/username/.config/MangoHud/MangoHud.conf"
(2) "/home/username/.config/MangoHud/wine-helldivers2.conf"
(3) "${path_to_game_executable}/MangoHud.conf"

Attempted specifying environment variable "MANGOHUD_CONFIGFILE='.../MangoHud.conf'"

My config file created using GOverlay 
[MangoHud.conf.txt](https://github.com/flightlessmango/MangoHud/files/15140836/MangoHud.conf.txt)

**Comment by flightlessmango** [comment]
if you edit the config while the game is running, does that make GPU appear?
if it says that gamemode is off it's because gamemode has not been loaded into the process. it's a gamemode or steam runtime issue

**Comment by BNelson986** [comment]
GPU has appeared in game, now I have 2 instances of mangohud showing up though. The new issue does not occur with "mangohud glxgears" but does with "vkcube". I think I might just have an errant config being loaded causing the new issue, but I'm not too sure. I think my gamemode issue is something with steam rather than mangohud, as I discovered I could run "gamemoderun mangohud glxgears" and it shows gamemode is running. 

I'm gonna try to do some more debugging tomorrow. 

Thanks for the quick help! :)

**Comment by BNelson986** [comment]
Easy fix, noticed I also had the apt package installed along with git source. Uninstalled using "sudo ./build.sh uninstall" All is working good now.
