### ISSUE TITLE
No debug or FSR info for gamescope

### ISSUE THREAD

**Issue by nphalem** [flightlessmango/MangoHud#1320]
**Describe the bug**
When I enable `debug` or `fsr` flags, I don't get any information (related to gamescope) displayed.

**List relevant hardware/software information**
- Linux distribution: Arch Linux
- MangoHud version: v0.7.1
- GPU: Intel Alder Lake-P

**To Reproduce**
1. I start a game in Lutris with enabled MangoHud and Gamescope
2. Add env variable `MANGOHUD_CONFIG=resolution,fps_limit=60,debug,fsr`
3. Start game
4. Make sure game is fullscreened
5. Lower the game resolution to be lower then display resolution so the FSR is triggered
6. Make sure FSR is active by checking the resolution displayed in MangoHud
7. There is no information for debug or FSR inside MangoHud

**Expected behavior**
There should be information related to gamescope and FSR in MangoHud

From Lutris logs I found this, although I'm not sure if it's related:

```
Failed to initialize PMU! (Permission denied)

When running as a normal user CAP_PERFMON is required to access performance
monitoring. See "man 7 capabilities", "man 8 setcap", or contact your
distribution vendor for assistance.

More information can be found at 'Perf events and tool security' document:
https://www.kernel.org/doc/html/latest/admin-guide/perf-security.html
```

**Comment by flightlessmango** [comment]
These options only work with mangoapp
