### ISSUE TITLE
MangoHud causes freezes on wayland + nvidia

### ISSUE THREAD

**Issue by BeauTaapken** [flightlessmango/MangoHud#1324]
**Describe the bug**
When i start a game on steam with `mangohud %command%` in the launch options, it freezes the game on a black screen and a partially rendered but also frozen mangohud

**List relevant hardware/software information**
- Linux Distribution: Arch linux
- MangoHud version: 0.7.1
- GPU: NVIDIA RTX 4090 with driver 550.78

**To Reproduce**
1. Add `mangohud %command%` to any steam games launch options
2. start the game
3. Observe the freeze of the game (black screen with a partially rendered mangohud

**Expected behavior**
The game launches properly and shows mangohud as well, without freezing

**Additional context**
My MangoHud.conf:
```af=16
cpu_temp
gpu_temp
gpu_core_clock
gpu_mem_clock
cpu_mhz
# gamemode
round_corners=10
ram
vram
frame_timing=0
cpu_load_change
gpu_load_change
device_battery=gamepad
device_battery_icon
fps_limit=165
gpu_power
procmem
```

I also use gamemoderun and some other launch options, but even when removing them, the issue still happens.

The issue does not occur when running `mangohud glxgears` in the terminal, but i do get an error: `[MANGOHUD] [error] [nvctrl.cpp:56] XNVCtrl didn't find the correct display`

**Comment by flightlessmango** [comment]
Is it one specific game where it happens?

**Comment by flightlessmango** [comment]
This appears to be the same issue as #1314. Move discussion over there
