### ISSUE TITLE
Using FCAT

### ISSUE THREAD

**Issue by JustCauseWhyNot** [flightlessmango/MangoHud#1327]
How is one supposed to use fcat? Is the overlay just for high speed camera video recording, or is it supposed to be useful without doing that? Or is does it get included in the output logs which then you can view the fcat markers in a certain program? I don't know which one if any of these are correct. But my understanding is that fcat can allow me to tell where my screen is tearing, and that if I adjust my frame cap it might be able to alleviate the tearing.

Thank you for any clarification.

**Comment by flightlessmango** [comment]
We don't supply any method for actually using the fcat output.
You record the game with fcat running and then you need a software to analyze the video.
As for what existing software can do this, I have no idea

**Comment by JustCauseWhyNot** [comment]
Helpful reply thank you.
