### ISSUE TITLE
GPU load and temperature not showing when using DXVK

### ISSUE THREAD

**Issue by almaceleste** [flightlessmango/MangoHud#1328]
**Describe the bug**
In some Windows games, launched using `DXVK`, `mangohud` does not display GPU load and temperature data. 
For example, `Tomb Raider` or `World of Tanks Blitz`.
But in others, also launched using DXVK, the GPU data is displayed normally. 
For example, `BioShock` or `Cypher`.

**List relevant hardware/software information**
- Linux Distribution: Ubuntu Studio 23.10 x86_64 6.5.0-35-lowlatency
- MangoHud version: 0.7.1
- GPU: Nvidia RTX A5500

**To Reproduce**
1. Open Steam.
2. Run game that uses `DXVK`
3. See the HUD

**Expected behavior**
GPU load and temperature data showing.

**Screenshots**
`Tomb Raider`
![image](https://github.com/flightlessmango/MangoHud/assets/36765595/2674d884-f9c7-4987-984c-001d8670bafe)
`World of Tanks Blitz`
![image](https://github.com/flightlessmango/MangoHud/assets/36765595/3816341f-2b1a-4aad-9f65-4d6de1ddce51)
`BioShock`
![image](https://github.com/flightlessmango/MangoHud/assets/36765595/927c9329-55b8-4120-9788-ea3a0b1824b0)
`Cypher`
![image](https://github.com/flightlessmango/MangoHud/assets/36765595/7e92892b-bb72-4ffb-8761-600026772bcb)

**Additional context**
All these games are launched with the same version of Proton.

**Comment by flightlessmango** [comment]
If you save the config file while running, does GPU appear in the hud?

**Comment by almaceleste** [comment]
Yes, saving the config during the game works, GPU data appears.

**Comment by flightlessmango** [comment]
This is the same issue as #1301 and I've pushed a commit to fix this it there.
Continue in that issue if it's still an issue

**Comment by almaceleste** [comment]
I'm using a pre-built version of `mangohud`, and I don't have free time now to build it, thus unfortunately I can't test this patch.
So I'll wait for the new version, and in the meantime I'll use your workaround.
Thanks for your work.
