### ISSUE TITLE
Feature request: ability to optionally inherent/load the settings from MangoHud.conf in game-specific configs

### ISSUE THREAD

**Issue by Yasand123** [flightlessmango/MangoHud#1332]
If you have your default config tailored to how you want it, it would be nice to be able to load that file in a game-specific config file. This is useful because you can have many game-specific config files for various reasons. Currently, you have to: 1) copy-paste the default configuration settings in every file, and 2) keep updating every game profile individually in case you changed something in your main config file (`MangoHud.conf`).

Here's how it would look like for `wine-Minecraft.conf` for example, which I think is a more efficient approach:
```conf
# Load default settings
LOAD=MangoHud.conf

# Custom settings for this profile only, this would override anything from LOAD
fps_limit=120
```

**Comment by flightlessmango** [comment]
You can use presets for this
`~/.config/MangoHud/presets.conf`
```
[preset 1]
gpu_temp
cpu_temp
```
and then in the game specific config
```
preset=1
fps_limit=120
```

**Comment by 17314642** [comment]
`vram=0`?

**Comment by GenocideStomper** [comment]
> `vram=0`?

Thank you, that worked perfectly!
