### ISSUE TITLE
cpu power 0

### ISSUE THREAD

**Issue by JustCauseWhyNot** [flightlessmango/MangoHud#1333]
**Describe the bug**
cpu_power is displaying 0W

**List relevant hardware/software information**
- Gentoo
- 7.1
- RTX 4070 super
- R7 7800x3

**To Reproduce**
1. Enable cpu_power 
2. See error

**Expected behavior**
Wattage usage from cpu

**Screenshots**
![2024-05-22_18-05_1](https://github.com/flightlessmango/MangoHud/assets/58643844/a64494db-b821-490c-90ef-b9360f0d184e)

![2024-05-22_18-21](https://github.com/flightlessmango/MangoHud/assets/58643844/798dda00-ff32-445d-af9b-fca34016eff1)

**Comment by flightlessmango** [comment]
can you paste the output of `sensors` ?

**Comment by JustCauseWhyNot** [comment]
Despite zenpower being loaded it doesn't seem to show. I don't know if it's cause I'm using a zen4 cpu or not, but it uses the same kernel socket if my understanding is correct as k10temp which covers zen4.
![2024-05-23_22-24](https://github.com/flightlessmango/MangoHud/assets/58643844/637ab38f-482f-4db8-af56-e92ec75502bd)

**Comment by Etaash-mathamsetty** [comment]
> Despite zenpower being loaded it doesn't seem to show. I don't know if it's cause I'm using a zen4 cpu or not, but it uses the same kernel socket if my understanding is correct as k10temp which covers zen4.
> sensors
> 
> ```
> nvme-pci-0d00
> Adapter: PCI adapter
> Composite:    +26.9°C  (low  =  -0.1°C, high = +82.8°C)
>                        (crit = +83.8°C)
> Sensor 1:     +19.9°C  (low  = -273.1°C, high = +65261.8°C)
> Sensor 2:     +24.9°C  (low  = -273.1°C, high = +65261.8°C)
> 
> nct6799-isa-0290
> Adapter: ISA adapter
> in0:                     1.05 V  (min =  +0.00 V, max =  +1.74 V)
> in1:                     1.83 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
> in2:                     3.42 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
> in3:                     3.30 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
> in4:                     1.67 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
> in5:                     1.05 V  (min =  +0.00 V, max =  +0.00 V)
> in6:                     1.47 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
> in7:                     3.42 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
> in8:                     3.25 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
> in9:                     1.81 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
> in10:                    1.30 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
> in11:                    1.12 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
> in12:                    1.02 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
> in13:                  896.00 mV (min =  +0.00 V, max =  +0.00 V)  ALARM
> in14:                    1.36 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
> in15:                    1.12 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
> in16:                    1.81 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
> in17:                  184.00 mV (min =  +0.00 V, max =  +0.00 V)
> fan1:                     0 RPM  (min =    0 RPM)
> fan2:                  1066 RPM  (min =    0 RPM)
> fan3:                     0 RPM  (min =    0 RPM)
> fan4:                  1044 RPM  (min =    0 RPM)
> fan5:                  1498 RPM  (min =    0 RPM)
> fan7:                  1075 RPM  (min =    0 RPM)
> SYSTIN:                 +19.0°C  (high = +80.0°C, hyst = +75.0°C)
>                                  (crit = +127.0°C)  sensor = thermistor
> CPUTIN:                 +24.0°C  (high = +80.0°C, hyst = +75.0°C)
>                                  (crit = +80.0°C)  sensor = thermistor
> AUXTIN0:                 +1.0°C  (high = +127.0°C, hyst = +110.0°C)
>                                  (crit =  +0.0°C)  sensor = thermistor
> AUXTIN1:                +10.0°C  (high = +80.0°C, hyst = +75.0°C)
>                                  (crit = +80.0°C)  sensor = thermistor
> AUXTIN2:                +19.0°C  (high = +80.0°C, hyst = +75.0°C)
>                                  (crit = +80.0°C)  sensor = thermistor
> AUXTIN3:                 +7.0°C  (high = +80.0°C, hyst = +75.0°C)
>                                  (crit = +100.0°C)  sensor = thermistor
> SMBUSMASTER 0:          +41.5°C  (high = +80.0°C, hyst = +75.0°C)
> AUXTIN4:                +23.0°C  (high = +80.0°C, hyst = +75.0°C)
>                                  (crit = +80.0°C)
> AUXTIN5:               +113.0°C  
> PCH_CHIP_CPU_MAX_TEMP:   +0.0°C  
> PCH_CHIP_TEMP:           +0.0°C  
> PCH_CPU_TEMP:            +0.0°C  
> TSI0_TEMP:              +41.8°C  
> intrusion0:            ALARM
> intrusion1:            ALARM
> beep_enable:           disabled
> ```

use zenergy, not zenpower

**Comment by JustCauseWhyNot** [comment]
Ok I'll try. I was just using zenergy since there was an already existing ebuild for it.

**Comment by flightlessmango** [comment]
Reopen if this hasn't been resolved

**Comment by JustCauseWhyNot** [comment]
I've not tried to resolve. I'll reopen if it fails after I finally install zenergy.

**Comment by JustCauseWhyNot** [comment]
I couldn't resolve it after using zenstats
