### ISSUE TITLE
Valheim crash with mangohud %command%

### ISSUE THREAD

**Issue by StellarHarbour** [flightlessmango/MangoHud#1335]
**List relevant hardware/software information**
- Linux Distribution: Arch Linux
- MangoHud version: 0.7.1
- GPU: RX 6800M

**Comment by flightlessmango** [comment]
Is valheim the only game that doesn't start or the only game you've tried?

**Comment by StellarHarbour** [comment]
Tried Dead Cells too, same result, both of them have native version

**Comment by flightlessmango** [comment]
install the `vulkan-tools` and run `mangohud vkcube` in a terminal to see if it displays the hud correctly

**Comment by StellarHarbour** [comment]
I have goverlay and it shows the hud, should test your way too?

**Comment by flightlessmango** [comment]
Yes please

**Comment by StellarHarbour** [comment]
Still works, 
[2024-05-26 01:07:24.180] [MANGOHUD] [error] [overlay_params.cpp:1003] Failed to read presets file: '/home/stellarharbour/.config/MangoHud/presets.conf'
Selected GPU 0: AMD Radeon RX 6800M (RADV NAVI22), type: DiscreteGpu

**Comment by flightlessmango** [comment]
Is steam installed using flatpak?

**Comment by StellarHarbour** [comment]
Yes, Runtime crashing on Arch for some rason
