### ISSUE TITLE
The new version 0.7.2 displays version 0.7.1

### ISSUE THREAD

**Issue by minergenon** [flightlessmango/MangoHud#1336]
The new version 0.7.2 displays version 0.7.1

**Comment by flightlessmango** [comment]
Do you mean in the hud? It looks fine on my end

**Comment by AngryPenguinPL** [comment]
Hi @flightlessmango  I just downloaded archive with submodules and trying compile it for my distrubution but discovered that this source archive https://github.com/flightlessmango/MangoHud/releases/download/v0.7.2/MangoHud-v0.7.2-Source.tar.xz
is named as 0.7.2 but after upnacking it point to 0.7.1.
![Zrzut ekranu z 2024-05-26 20-24-01](https://github.com/flightlessmango/MangoHud/assets/3121142/20fc288f-05f5-4e9e-b12a-0597f5eacc17)

**Comment by flightlessmango** [comment]
It's probably because it takes the project version which still is 0.7.1, but everything else should point towards it being 0.7.2.
Don't know if this is worth a hotfix

**Comment by kloczek** [comment]
And https://github.com/flightlessmango/MangoHud/releases/download/v0.7.2/MangoHud-v0.7.2-Source.tar.xz dist tar ball has inside `MangoHud-v0.7.1/` base directory.

**Comment by flightlessmango** [comment]
I understand that it's labeled incorrectly, but is it causing any issues upstream or something?
If I just rename these and reupload them, is that sufficient for now?

**Comment by flightlessmango** [comment]
I've renamed it now, any other problem area?

**Comment by flightlessmango** [comment]
This should be resolved

**Comment by hashworks** [comment]
Looks like `meson.build` in `MangoHud-v0.7.2-Source.tar.xz` has `version : 'v0.7.1'`.

https://github.com/flightlessmango/MangoHud/blob/v0.7.2/meson.build#L3

**Comment by flightlessmango** [comment]
It does, but it should only be visible when running meson setup.
Does it have any actual consequences downstream?
I don't want to bump a hotfix for something that doesn't matter

**Comment by hashworks** [comment]
The ArchLinux package in extra uses that, which results in `v0.7.1` for `mangohud --version` (and in the HUD I guess), but no other consequences than that.
