### ISSUE TITLE
MangoHUD causing CS2 to crash?

### ISSUE THREAD

**Issue by PacketAuditor** [flightlessmango/MangoHud#1341]
**Describe the bug**
CS2 intermittently crashes upon startup or takes multiple attempts to start. When it does run, it crashes seemingly at random.

**List relevant hardware/software information**
- EndeavourOS
- MangoHud version: 0.7.2-1
- RTX 3080

**To Reproduce**
1. Open CS2 on Wayland with MangoHUD.
2. Crash

**Expected behavior**
No crash.

Steam logs:
```[MANGOHUD] [error] [nvctrl.cpp:56] XNVCtrl didn't find the correct display```

```/home/p/.local/share/Steam/steamapps/common/Counter-Strike Global Offensive/game/cs2.sh: line 118: 83140 Segmentation fault      (core dumped) ${STEAM_RUNTIME_PREFIX} ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"```

**Comment by flightlessmango** [comment]
What driver version are you on?

**Comment by PacketAuditor** [comment]
> What driver version are you on?

555.42.02

**Comment by Etaash-mathamsetty** [comment]
CS2 on wayland is pretty crashy as is

**Comment by flightlessmango** [comment]
@PacketAuditor Have tried to verify that it only crashes with mangohud?

**Comment by flightlessmango** [comment]
closing until more information is provided

**Comment by flightlessmango** [comment]
a full log with `MANGOHUD_LOG_LEVEL=debug` could be useful

**Comment by PacketAuditor** [comment]
I haven't been experiencing this lately. I am not sure if it was GPU driver related, Valve issue, or something else.

**Comment by laribA** [comment]
> a full log with `MANGOHUD_LOG_LEVEL=debug` could be useful

Unfortunately nothing new comes up in the log :(
```
Loaded /home/art/.local/share/Steam/steamapps/common/Counter-Strike Global Offensive/game/bin/linuxsteamrt64/libengine2.so, got 0x55a48fd81df0
Loaded libSDL3.so.0, got 0x55a48fea3f70
Loaded /home/art/.local/share/Steam/steamapps/common/Counter-Strike Global Offensive/game/bin/linuxsteamrt64/libtier0.so, got 0x55a48fd638e0
Loaded /home/art/.local/share/Steam/steamapps/common/Counter-Strike Global Offensive/game/bin/linuxsteamrt64/libfilesystem_stdio.so, got 0x55a48fee9870
Loaded /home/art/.local/share/Steam/steamapps/common/Counter-Strike Global Offensive/game/bin/linuxsteamrt64/libinputsystem.so, got 0x55a48fee1ed0
Loaded /home/art/.local/share/Steam/steamapps/common/Counter-Strike Global Offensive/game/bin/linuxsteamrt64/liblocalize.so, got 0x55a48ff2a620
Loaded /home/art/.local/share/Steam/steamapps/common/Counter-Strike Global Offensive/game/bin/linuxsteamrt64/librendersystemvulkan.so, got 0x55a48ff2ad50
Loaded /home/art/.local/share/Steam/steamapps/common/Counter-Strike Global Offensive/game/bin/linuxsteamrt64/libresourcesystem.so, got 0x55a48ff4fd00
Loaded /home/art/.local/share/Steam/steamapps/common/Counter-Strike Global Offensive/game/bin/linuxsteamrt64/libschemasystem.so, got 0x55a48ff62320
```

**Comment by flightlessmango** [comment]
@laribA it doesn't seem like you have the same issue as OP.
It would be best to start a new issue with all the information and repro cases etc
