### ISSUE TITLE
Doesn't work with Starsector

### ISSUE THREAD

**Issue by Mart-Bogdan** [flightlessmango/MangoHud#1343]
Doesn't show any HUD when launching [Starsector](https://fractalsoftworks.com/)

**List relevant hardware/software information**
- Linux Distribution: Manjaro Linux 
- MangoHud version: v0.7.1
- GPU: NVidia GTX3070 Mobile

**To Reproduce**
1. Go to 'Terminal'
2. `manghud starsector`  (I've installed it via AUR so didn't did manual download)
3. Begin play in a launcher

**Expected behavior**
Being able to see FPS counter.

**Screenshots**
Just regular play, without HUD being visible 

**Additional context**
AFAIK Starsector is using OpenGL and is writen in Java. It's using 64bit JVM.  

I'm currently using JRE 8. But same behavior with JRE 7  (which is budnled with a game)

**Comment by Mart-Bogdan** [comment]
Steam overlay and Steam's FPS counter works if game is added to Steam.

**Comment by gort818** [comment]
Did you try this https://github.com/flightlessmango/MangoHud?tab=readme-ov-file#opengl ?
`mangohud --dlsym `

**Comment by Mart-Bogdan** [comment]
I'll try it. Thanks.

**Comment by Mart-Bogdan** [comment]
This works. Thank you!
