### ISSUE TITLE
mangohud says gamemode is off

### ISSUE THREAD

**Issue by valfr68** [flightlessmango/MangoHud#1344]
Hello,

When I run my games with gamemode with gamemoderun %command% on steam and mangohud configured with goverlay, mangohud says that gamemode is off and gamemoded -s says that is on.
That means gamemode is inactive or that's a mistake ?

Thank you very much for your help

**List relevant hardware/software information**
- Manjaro
- MangoHud 0.7.2
- GPU : 6700 xt

**Comment by flightlessmango** [comment]
gamemode sets system wide settings, but it also sets application specific settings.
to set the app specific settings it has to preload into the app, this is what mangohud detects and `gamemoded -s` is not aware of.
It's not a mistake, gamemode is just not "fully" on

**Comment by valfr68** [comment]
> gamemode sets system wide settings, but it also sets application specific settings. to set the app specific settings it has to preload into the app, this is what mangohud detects and `gamemoded -s` is not aware of. It's not a mistake, gamemode is just not "fully" on

What can I do gamemode fully on ?

**Comment by flightlessmango** [comment]
You set `gamemoderun` like you already have. 
If it doesn't work there's probably something wrong with the steam runtime or gamemode

**Comment by flightlessmango** [comment]
@Tiagoquix like I explained, gamemode is not fully on. We shouldn't say it is when it's not

**Comment by valfr68** [comment]
When I do gamemoderun steam-runtime, I have that :

gamemodeauto:
gamemodeauto:
gamemodeauto:
gamemodeauto:
gamemodeauto:
gamemodeauto:
gamemodeauto:
gamemodeauto:
gamemodeauto:
gamemodeauto:
gamemodeauto:
gamemodeauto:
gamemodeauto:
gamemodeauto:
gamemodeauto:
gamemodeauto:
gamemodeauto:
gamemodeauto:
gamemodeauto:
gamemodeauto:
gamemodeauto:
gamemodeauto:
gamemodeauto:
gamemodeauto:
gamemodeauto:
gamemodeauto:
gamemodeauto:
gamemodeauto:
gamemodeauto:
gamemodeauto:
gamemodeauto:
gamemodeauto:
gamemodeauto:
gamemodeauto:
steam.sh[7876]: Running Steam on manjarolinux 24.0.1 64-bit
gamemodeauto:
gamemodeauto:
gamemodeauto:
gamemodeauto:
gamemodeauto:
steam.sh[7876]: STEAM_RUNTIME is enabled automatically
gamemodeauto:
gamemodeauto:
gamemodeauto:
setup.sh[7962]: Steam runtime environment up-to-date!
gamemodeauto:
gamemodeauto:
gamemodeauto:
gamemodeauto:
gamemodeauto:
steam.sh[7876]: Steam client's requirements are satisfied
[2024-06-09 23:13:23] Startup - updater built May 24 2024 20:46:19
[2024-06-09 23:13:23] Startup - Steam Client launched with: '/home/valentin/.local/share/Steam/ubuntu12_32/steam'
06/09 23:13:23 minidumps folder is set to /tmp/dumps
06/09 23:13:23 Init: Installing breakpad exception handler for appid(steam)/version(1716584667)/tid(8019)
[2024-06-09 23:13:23] Loading cached metrics from disk (/home/valentin/.local/share/Steam/package/steam_client_metrics.bin)
[2024-06-09 23:13:23] Using the following download hosts for Public, Realm steamglobal
[2024-06-09 23:13:23] 1. https://client-update.akamai.steamstatic.com/, /, Realm 'steamglobal', weight was 1000, source = 'update_hosts_cached.vdf'
[2024-06-09 23:13:23] 2. https://cdn.cloudflare.steamstatic.com/, /client/, Realm 'steamglobal', weight was 1, source = 'update_hosts_cached.vdf'
[2024-06-09 23:13:23] 3. https://cdn.steamstatic.com/, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
[2024-06-09 23:13:23] Vérification de l'installation…
[2024-06-09 23:13:23] Verification complete
UpdateUI: skip show logo
Steam logging initialized: directory: /home/valentin/.local/share/Steam/logs

/usr/share/themes/Breeze/gtk-2.0/widgets/entry:70: error: unexpected identifier 'direction', expected character '}'
/usr/share/themes/Breeze/gtk-2.0/widgets/styles:36: error: invalid string constant "combobox_entry", expected valid string constant
gamemodeauto:
XRRGetOutputInfo Workaround: initialized with override: 0 real: 0xeb8aadc0
XRRGetCrtcInfo Workaround: initialized with override: 0 real: 0xeb8a9500
gamemodeauto:
gamemodeauto:
gamemodeauto:
gamemodeauto:
steamwebhelper.sh[8052]: === dim. 09 juin 2024 23:13:24 CEST ===
gamemodeauto:
gamemodeauto:
steamwebhelper.sh[8052]: Starting steamwebhelper under bootstrap sniper steam runtime at /home/valentin/.local/share/Steam/ubuntu12_64/steam-runtime-sniper
gamemodeauto:
gamemodeauto:
CAppInfoCacheReadFromDiskThread took 172 milliseconds to initialize
Steam Runtime Launch Service: starting steam-runtime-launcher-service
Steam Runtime Launch Service: steam-runtime-launcher-service is running pid 8178
gamemodeauto:
bus_name=com.steampowered.PressureVessel.LaunchAlongsideSteam
gamemodeauto:
gamemodeauto:
gamemodeauto:
gamemodeauto:
gamemodeauto:
gamemodeauto:
gamemodeauto:
BRefreshApplicationsInLibrary 1: 206ms
gamemodeauto:
gamemodeauto:
gamemodeauto:
gamemodeauto:
gamemodeauto:
gamemodeauto:
gamemodeauto:
gamemodeauto:
gamemodeauto:
gamemodeauto:
dbus[8500]: arguments to dbus_pending_call_block() were incorrect, assertion "pending != NULL" failed in file dbus-pending-call.c line 766.
This is normally a bug in some application using the D-Bus library.

D-Bus not built with -rdynamic so unable to print a backtrace
dbus[8501]: arguments to dbus_pending_call_block() were incorrect, assertion "pending != NULL" failed in file dbus-pending-call.c line 766.
This is normally a bug in some application using the D-Bus library.

D-Bus not built with -rdynamic so unable to print a backtrace
gamemodeauto:
gamemodeauto:
dbus[8573]: arguments to dbus_pending_call_block() were incorrect, assertion "pending != NULL" failed in file dbus-pending-call.c line 766.
This is normally a bug in some application using the D-Bus library.

D-Bus not built with -rdynamic so unable to print a backtrace
dbus[8575]: arguments to dbus_pending_call_block() were incorrect, assertion "pending != NULL" failed in file dbus-pending-call.c line 766.
This is normally a bug in some application using the D-Bus library.

D-Bus not built with -rdynamic so unable to print a backtrace
gamemodeauto:
dbus[8621]: arguments to dbus_pending_call_block() were incorrect, assertion "pending != NULL" failed in file dbus-pending-call.c line 766.
This is normally a bug in some application using the D-Bus library.

D-Bus not built with -rdynamic so unable to print a backtrace
gamemodeauto:
dbus[8625]: arguments to dbus_pending_call_block() were incorrect, assertion "pending != NULL" failed in file dbus-pending-call.c line 766.
This is normally a bug in some application using the D-Bus library.

D-Bus not built with -rdynamic so unable to print a backtrace
gamemodeauto:
dbus[8651]: arguments to dbus_pending_call_block() were incorrect, assertion "pending != NULL" failed in file dbus-pending-call.c line 766.
This is normally a bug in some application using the D-Bus library.

D-Bus not built with -rdynamic so unable to print a backtrace
gamemodeauto:
dbus[8655]: arguments to dbus_pending_call_block() were incorrect, assertion "pending != NULL" failed in file dbus-pending-call.c line 766.
This is normally a bug in some application using the D-Bus library.

D-Bus not built with -rdynamic so unable to print a backtrace
gamemodeauto:
gamemodeauto:
dbus[8897]: arguments to dbus_pending_call_block() were incorrect, assertion "pending != NULL" failed in file dbus-pending-call.c line 766.
This is normally a bug in some application using the D-Bus library.

D-Bus not built with -rdynamic so unable to print a backtrace
gamemodeauto:
dbus[8903]: arguments to dbus_pending_call_block() were incorrect, assertion "pending != NULL" failed in file dbus-pending-call.c line 766.
This is normally a bug in some application using the D-Bus library.

D-Bus not built with -rdynamic so unable to print a backtrace
gamemodeauto:
gamemodeauto:
dbus[9131]: arguments to dbus_pending_call_block() were incorrect, assertion "pending != NULL" failed in file dbus-pending-call.c line 766.
This is normally a bug in some application using the D-Bus library.

D-Bus not built with -rdynamic so unable to print a backtrace
gamemodeauto:
dbus[9139]: arguments to dbus_pending_call_block() were incorrect, assertion "pending != NULL" failed in file dbus-pending-call.c line 766.
This is normally a bug in some application using the D-Bus library.

D-Bus not built with -rdynamic so unable to print a backtrace
gamemodeauto:
dbus[9399]: arguments to dbus_pending_call_block() were incorrect, assertion "pending != NULL" failed in file dbus-pending-call.c line 766.
This is normally a bug in some application using the D-Bus library.

D-Bus not built with -rdynamic so unable to print a backtrace
gamemodeauto:
dbus[9455]: arguments to dbus_pending_call_block() were incorrect, assertion "pending != NULL" failed in file dbus-pending-call.c line 766.
This is normally a bug in some application using the D-Bus library.

D-Bus not built with -rdynamic so unable to print a backtrace
gamemodeauto:
gamemodeauto:
dbus[9522]: arguments to dbus_pending_call_block() were incorrect, assertion "pending != NULL" failed in file dbus-pending-call.c line 766.
This is normally a bug in some application using the D-Bus library.

D-Bus not built with -rdynamic so unable to print a backtrace
gamemodeauto:
dbus[9533]: arguments to dbus_pending_call_block() were incorrect, assertion "pending != NULL" failed in file dbus-pending-call.c line 766.
This is normally a bug in some application using the D-Bus library.

D-Bus not built with -rdynamic so unable to print a backtrace
gamemodeauto:
gamemodeauto:
dbus[9544]: arguments to dbus_pending_call_block() were incorrect, assertion "pending != NULL" failed in file dbus-pending-call.c line 766.
This is normally a bug in some application using the D-Bus library.

D-Bus not built with -rdynamic so unable to print a backtrace
dbus[9546]: arguments to dbus_pending_call_block() were incorrect, assertion "pending != NULL" failed in file dbus-pending-call.c line 766.
This is normally a bug in some application using the D-Bus library.

D-Bus not built with -rdynamic so unable to print a backtrace
gamemodeauto:
dbus[9567]: arguments to dbus_pending_call_block() were incorrect, assertion "pending != NULL" failed in file dbus-pending-call.c line 766.
This is normally a bug in some application using the D-Bus library.

D-Bus not built with -rdynamic so unable to print a backtrace
gamemodeauto:
dbus[9579]: arguments to dbus_pending_call_block() were incorrect, assertion "pending != NULL" failed in file dbus-pending-call.c line 766.
This is normally a bug in some application using the D-Bus library.

D-Bus not built with -rdynamic so unable to print a backtrace
src/steamUI/webuitransportcontroller.cpp (206) : Failed to connect to websocket
src/steamUI/webuitransportcontroller.cpp (206) : Failed to connect to websocket
06/09 23:14:12 Init: Installing breakpad exception handler for appid(steam)/version(1716584667)/tid(8019)
assert_20240609231412_36.dmp[9599]: Uploading dump (out-of-process)
/tmp/dumps/assert_20240609231412_36.dmp
gamemodeauto:
BuildCompleteAppOverviewChange: 1279 apps
RegisterForAppOverview 1: 38ms
RegisterForAppOverview 2: 39ms
assert_20240609231412_36.dmp[9599]: Finished uploading minidump (out-of-process): success = yes
assert_20240609231412_36.dmp[9599]: response: CrashID=bp-a37d9d1a-cfea-4f85-a737-77de62240609
assert_20240609231412_36.dmp[9599]: file ''/tmp/dumps/assert_20240609231412_36.dmp'', upload yes: ''CrashID=bp-a37d9d1a-cfea-4f85-a737-77de62240609''
gamemodeauto:
gamemodeauto:
gamemodeauto:
dbus[9785]: arguments to dbus_pending_call_block() were incorrect, assertion "pending != NULL" failed in file dbus-pending-call.c line 766.
This is normally a bug in some application using the D-Bus library.

D-Bus not built with -rdynamic so unable to print a backtrace
gamemodeauto:
dbus[9796]: arguments to dbus_pending_call_block() were incorrect, assertion "pending != NULL" failed in file dbus-pending-call.c line 766.
This is normally a bug in some application using the D-Bus library.

D-Bus not built with -rdynamic so unable to print a backtrace
gamemodeauto:
dbus[9807]: arguments to dbus_pending_call_block() were incorrect, assertion "pending != NULL" failed in file dbus-pending-call.c line 766.
This is normally a bug in some application using the D-Bus library.

D-Bus not built with -rdynamic so unable to print a backtrace
gamemodeauto:
dbus[9819]: arguments to dbus_pending_call_block() were incorrect, assertion "pending != NULL" failed in file dbus-pending-call.c line 766.
This is normally a bug in some application using the D-Bus library.

D-Bus not built with -rdynamic so unable to print a backtrace
gamemodeauto:
dbus[9829]: arguments to dbus_pending_call_block() were incorrect, assertion "pending != NULL" failed in file dbus-pending-call.c line 766.
This is normally a bug in some application using the D-Bus library.

D-Bus not built with -rdynamic so unable to print a backtrace
gamemodeauto:
dbus[9840]: arguments to dbus_pending_call_block() were incorrect, assertion "pending != NULL" failed in file dbus-pending-call.c line 766.
This is normally a bug in some application using the D-Bus library.

D-Bus not built with -rdynamic so unable to print a backtrace
gamemodeauto:
dbus[9851]: arguments to dbus_pending_call_block() were incorrect, assertion "pending != NULL" failed in file dbus-pending-call.c line 766.
This is normally a bug in some application using the D-Bus library.

**Comment by flightlessmango** [comment]
> When I do gamemoderun steam-runtime

This is not proper usage, it should be in the launch option for the game

**Comment by valfr68** [comment]
With Sifu on Steam mangohud says active, and with ubiconnect games mangohud says too active, but with other games on Steam 
mangohud says inactive.

**Comment by valfr68** [comment]
I put LD_PRELOAD=/usr/lib32/libgamemode.so gamemoderun and that works for 32 bits games and for 64 bits games I put LD_PRELOAD=/usr/lib/libgamemode.so

**Comment by valfr68** [comment]
I put LD_PRELOAD=/usr/lib32/libgamemode.so gamemoderun and that works for 32 bits games and for 64 bits games I put LD_PRELOAD=/usr/lib/libgamemode.so

**Comment by JStrategic** [comment]
This could vary on your system it seems. The above mention files did not exist for me. I went to my /usr folder and I had lib and lib64. So I just went into the lib folder, and did:
`ls | grep gamemode`
 to find the file name that I needed for my 32 bit games, and then did the same thing in lib64 for my 64 bit games.Hope this helps!

**Comment by pyrotiger** [comment]
> I put LD_PRELOAD=/usr/lib32/libgamemode.so gamemoderun and that works for 32 bits games and for 64 bits games I put LD_PRELOAD=/usr/lib/libgamemode.so

-can verify same issue and same workaround resolves it for FFXVI using Steam, Goverlay

**Comment by flightlessmango** [comment]
If you need to manually preload 32bit libs, it means ld is failing to find the libs like it should.
Likely a packaging issue

**Comment by RedSnt** [comment]
> I put LD_PRELOAD=/usr/lib32/libgamemode.so gamemoderun and that works for 32 bits games and for 64 bits games I put LD_PRELOAD=/usr/lib/libgamemode.so

@valfr68 thanks for this tip. I improved it ever so slightly like this:  

`LD_PRELOAD=$LD_PRELOAD:/usr/lib32/libgamemode.so gamemoderun %command%`  
that way settings you set in steam like the steam overlay settings doesn't get overwritten but is appended instead.  
And of course, depending on distro the file might be called something different like libgamemod.so.0 on my Nobara installation.

**Comment by KFERMercer** [comment]
A more elegant solution is to use `LD_PRELOAD="$LD_PRELOAD:/usr/\$LIB/libgamemodeauto.so.0"` , this will automatically apply to both 32 bit and 64 bit games.

ref: https://github.com/FeralInteractive/gamemode?tab=readme-ov-file#requesting-gamemode
