### ISSUE TITLE
present_mode always says VSYNC ON for OpenGL

### ISSUE THREAD

**Issue by Lassebq** [flightlessmango/MangoHud#1347]
**Describe the bug**
Vsync state with `present_mode` config option always says ON
The only time it ever says OFF is when you force vsync off using `vsync` option

**List relevant hardware/software information**
- Arch Linux
- 0.7.2

**To Reproduce**
1. Enable `present_mode` config option
2. Run any game on OpenGL
3. VSYNC state displayed by HUD always says ON

**Expected behavior**
VSync state changes dynamically like how Present Mode does in Vulkan games.

**Screenshots**
My monitor's refresh rate is 75hz. So it's pretty obvious ~300 fps aren't synced
![image](https://github.com/flightlessmango/MangoHud/assets/68742864/efb4a9c2-4db2-486a-9009-802ec8687879)

**Comment by Lassebq** [comment]
Related to #1190.

**Comment by flightlessmango** [comment]
should be fixed here ed6cf225f10640bc37a6719610b923b7c746303a
