### ISSUE TITLE
MangoHUD reports average FPS higher than max. possible when soft-capped

### ISSUE THREAD

**Issue by Tiagoquix** [flightlessmango/MangoHud#1348]
**Describe the bug**
When a game has its FPS soft-capped (such as internal FPS cap via the game's settings menu or `DXVK_FRAME_RATE` env. variable), MangoHUD somehow reports avg. FPS higher than the max. allowed value (for example: it reports 70 FPS when max. is 60 due to soft-cap).

**List relevant hardware/software information**
- Linux Distribution: Fedora Linux 40 KDE
- MangoHud version: `0.7.2-2.fc40`
- GPU: NVIDIA GeForce GTX 1050 Ti

**To Reproduce**
Explained above.

**Expected behavior**
Explained above.

**Screenshots**
Wouldn't be too helpful.

**Additional context**
No additional context.

**Comment by flightlessmango** [comment]
When the app just starts there are a few frames that aren't limited by vsync etc, this can cause a higher average.
If you want to make sure the avg is representative of the session you can reset the metrics with Shift_R+F9

**Comment by flightlessmango** [comment]
No it shouldn't reset metrics
