### ISSUE TITLE
Flatpak: Nowhere to load the CONFIG-File from

### ISSUE THREAD

**Issue by g-dikdik** [flightlessmango/MangoHud#1351]
After installing the Flatpak there is no clear path on where to put the conf-file. I put the same one in all locations you listed and none applied, when starting any Game.

**Version**  
- ID: org.freedesktop.Platform.VulkanLayer.MangoHud
- Ref: runtime/org.freedesktop.Platform.VulkanLayer.MangoHud/x86_64/23.08
- Arch: x86_64
- Branch: 23.08
- Version: 0.7.2
- Origin: flathub
- Collection: org.flathub.Stable
- Installation: system
- Installed: 33,4 MB
**OS** — Linux Mint 21.2 Cinnamon – Kernel Version: 5.15.0-107-generic
**GPU** — NVIDIA GeForce RTX 2070 SUPER  

**To Reproduce**  
1. Open Terminal  
2. execute `flatpak install org.freedesktop.Platform.VulkanLayer.MangoHud -y`  
3. select 23.08 branch (the third option)  
4. Locate a valid path for the conf-file  

**Expected behaviour**  
Having a path where the conf-file is loaded from.  

**_TLDR_**
I would really like to set a global config for my gog games which i run through **Lutris**.

**Comment by flightlessmango** [comment]
https://github.com/flathub/org.freedesktop.Platform.VulkanLayer.MangoHud

I believe this readme should resolve the issue
