### ISSUE TITLE
[MANGOHUD] [error] [nvctrl.cpp:56] XNVCtrl didn't find the correct display

### ISSUE THREAD

**Issue by Hellmo-Luciferrari** [flightlessmango/MangoHud#1357]
**Describe the bug**
Mangohud not displaying over vkcube.
[MANGOHUD] [error] [nvctrl.cpp:56] XNVCtrl didn't find the correct display

getting 

**List relevant hardware/software information**
- Arch Linux
- mangohud 0.7.2-1
- EVGA Nvidia RTX 3090 using proprietary DKMS drivers
- Wayland
- KDE Plasma 6.0.5

**To Reproduce**
1. open terminal
2. run "mangohud vkcube"

or

1. open Goverlay

**Expected behavior**
Expected VKcube to show with the mangohud overlay like it did

**Screenshots**
https://ibb.co/pnzKZdd

**Additional context**
I have uninstalled mangohud, and goverlay multiple times and rebooted.
I have deleted these directories:
~/.config/MangoHud
 /usr/share/doc/mangohud

**Comment by flightlessmango** [comment]
This error has no consequence, it has been changed to debug as well.
Was mangohud or goverlay installed using flatpak?
You can't use flatpak mangohud with vkcube for example

**Comment by Virkkunen** [comment]
The vkcube not displaying with mangohud might be an issue with the 555 drivers. I've reverted back to 550.90-7 to test some unrelated things and vkcube correctly displays with mangohud without failing once.
  
![image](https://github.com/flightlessmango/MangoHud/assets/9111925/a5a4dffd-1d15-41c8-9a22-88c62f20667e)

**Comment by Hellmo-Luciferrari** [comment]
> This error has no consequence, it has been changed to debug as well. Was mangohud or goverlay installed using flatpak? You can't use flatpak mangohud with vkcube for example

I was not using flatpack. I installed with Pacman on Arch

**Comment by flightlessmango** [comment]
Doesn't seem to be a mangohud issue but an nvidia driver issue
