### ISSUE TITLE
Not possible to log cpu_power

### ISSUE THREAD

**Issue by Treym0n** [flightlessmango/MangoHud#1358]
I would like to measure the power consumption of the CPU and GPU of the Steam Deck via software.
By adjusting the MangoHud configuration file, the desired values can be displayed in the overlay in the game. 
However, I would like to not only display them, but also log them. 
When I create a log file, it currently provides the following values:
- fps
- frametime
- cpu_load
- gpu_load
- cpu_temp
- gpu_temp
- gpu_core_clock
- gpu_mem_clock
- gpu_vram_used
- gpu_power
- ram_used
- swap_used
- process_rss
- elapsed
The power consumption of the GPU is logged accordingly, but the power consumption of the CPU is missing.
I searched the MangoHud configuration file for a way to log additional parameters, but unfortunately found nothing.
I tried log_cpu_power as a test, but unfortunately this did not work.
Is there a way to customize the parameters that are recorded and saved by the log file?

**Comment by flightlessmango** [comment]
Added cpu power in this commit 193fdc7eef1b2935eebfa2512816318fcdcb49f5
