### ISSUE TITLE
Missing dependency on Ubuntu 20.04

### ISSUE THREAD

**Issue by genpfault** [flightlessmango/MangoHud#136]
Cloned today's 12a528b894 and did the `./build.sh build` per the README and eventually got:

    src/meson.build:21:0: ERROR: Program(s) ['glslangValidator'] not found or not executable

Installing `glslang-tools` fixed it for me.

**Comment by jackun** [comment]
How? It installs it to /usr/local/bin for Ubuntu variants :confused:

**Comment by flightlessmango** [comment]
> probably missing wget/unzip.

Most likely this, I just confirmed it working in a 20.04 docker

**Comment by stephanlachnit** [comment]
`sudo apt-get install glslang-tools` should fix it, I had to add it for the Debian package as well.

**Comment by flightlessmango** [comment]
This should be resolved, feel free to open up this issue again if it's not
