### ISSUE TITLE
MangoHud not updating config

### ISSUE THREAD

**Issue by Headedbranch225** [flightlessmango/MangoHud#1363]
**Describe the bug**

**List relevant hardware/software information**
- Pop!_OS 22.04 LTS x86_64 
- Intel i5-9400F
- NVIDIA GeForce GTX 1660
- MangoHud latest apt install

**To Reproduce**
1. install mangohud (from apt)
2. install GOverlay (from apt)
3. even when saving, the overlay remains the same

**Expected behavior**
seeing the edited config setup

**Screenshots**
![image](https://github.com/flightlessmango/MangoHud/assets/95239405/09f766d2-c436-483a-b908-e2e52a84369f)

**Additional context**
also doesn't work in games

**Comment by flightlessmango** [comment]
goverlay is not developed by us, you should make an issue there for goverlay issues https://github.com/benjamimgois/goverlay

>  also doesn't work in games
The version in ubuntu/pop repo is extremely old, you need to install the current version so we know that it's not an old bug that's already been fixed
