### ISSUE TITLE
Question about frame rate limiter

### ISSUE THREAD

**Issue by Tiagoquix** [flightlessmango/MangoHud#1368]
Hi there.

Does MangoHUD need to be visible for the frame rate limiter to work?

Also, is there any really visible/impactful difference from the two frame rater limiter modes aside from what's described in the README file?

Thanks in advance for your attention.

**Comment by Leopard1907** [comment]
I think you can try all of that on your end and find out the answer.

**Comment by flightlessmango** [comment]
nope and nope!
