### ISSUE TITLE
"Wrong ELF class" regardless of mangohud or mangohud.x86

### ISSUE THREAD

**Issue by jgabor** [flightlessmango/MangoHud#137]
[Creating an issue as requested](https://github.com/flightlessmango/MangoHud/issues/73#issuecomment-619524061), and from my understanding, the issue is related to the nvctrl implementation currently only being available in the develop branch.

**Comment by jgabor** [comment]
I updated to Lutris' DXVK 1.6.1 and Wine 5.7 runner to see if my issue with mangohud and SW:TOR might have been fixed, and mangohud now works again nicely with SW:TOR when ran with `mangohud.x86`!

But I still get "Wrong ELF class" errors when using the "right" mangohud version, so I updated this issue's title to reflect that instead.

So if I run it with `mangohud`:

``` 
ERROR: ld.so: object 'libMangoHud.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
``` 

And if I run it with `mangohud.x86`:

 ``` 
ERROR: ld.so: object 'libMangoHud.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
 ``` 
...and it spams a ton of Fontconfig warning's and error's, but that could be a local system issue.

I guess this could be related to the Wine prefix being 64-bit, but re-installing SW:TOR sometimes takes forever so I haven't been bothered enough to do that. Feel free to close issue if these are things that are deemed "normal" at this stage or not an actual issue with mangohud itself.

**Comment by jackun** [comment]
That seems to be normal. No point reinstalling swtor.

**Comment by jgabor** [comment]
Ok! I'll go ahead and close this issue.

One thing I did notice, and which perhaps was the culprit all along, is that I can trigger the wine page fault error by enabling "Prefer system libraries" in Lutris together with mangohud and/or vkbasalt. Disabling system libraries fixes it at least for mangohud.x86, and although I haven't yet tested it with vkbasalt, I expect it works fine as well. Just leaving it here, in case someone stumbles on this issue with similar problems.
