### ISSUE TITLE
UselessHud works only for ONE native linux game!!!

### ISSUE THREAD

**Issue by rado84-github** [flightlessmango/MangoHud#1370]
This tool is completely useless, I'd rather return to the ancient Nvidia OSD! It might be ugly but it works ALWAYS! The only game I ever managed to make UselessHud work for was ETS2 and ONLY after creating a matroska of bash scripts, otherwise - no working in the ways described in the "Code" page here!

A Windows game on Steam (World of Tanks Blitz) - no chance. I put all kinds of configs everywhere posslible: wotblitz.conf, proton-wotblitz.conf, wine-wotblitz.conf in the directory where the game exe is (in SteamLibrary path), as well as in ~/.config/MangoHud and still NO mangohud OSD when I launch the game! I also added mangohud %command% to launch options: no mangohud! "Mangohud=1 %command%" to launch options: no mangohud in the game!
I even went further and created a similar matroska of scripts, like with ETS2, in the hopes that the damn thing would appear in the game but it still wouldn't appear!

A Windows game outside of Steam (c*acked or actually free to play) - 10% to 0 chance for UselessHud to work.
A native game on and outside of Steam - no chance, unless you create the aforementioned matroska of bash scripts and even then there's no guarantee it will work!

Given the low number of games (or just one, really) that actually get a mangohud display, I'd suggest you do something better with your spare time and leave the programming of UselessHud to people who actually CAN code, plenty of those in the linux community, it's just not you!

**Comment by gort818** [comment]
PEBKAC
