### ISSUE TITLE
Load % always 0 for Intel Arc GPU

### ISSUE THREAD

**Issue by ToastedWookiee** [flightlessmango/MangoHud#1372]
I know mangohud no longer uses `intel_gpu_top` for metrics, but according to commit [#4cbcec3](https://github.com/flightlessmango/MangoHud/commit/4cbcec30b8f302fecfe3c5ef95f1d0861a649a5f) we should still be getting a load % value. 

My load is always at 0%, is there any logs, etc to check for this issue?

Thanks

**List relevant hardware/software information**
- EndeavourOS
- AUR mangohud-git: 0.7.2.r26.gc0afb84-1 (latest commit)
- Intel Arc a770

**Comment by flightlessmango** [comment]
Do you have an iGPU as well?

**Comment by ToastedWookiee** [comment]
Yes, there is an iGPU on Intel cpu as well.

**Comment by Leopard1907** [comment]
If your monitor is hooked to your dgpu, then do try with this on a title that will use Vulkan ( eg DXVK,vkd3d-proton or native )

https://docs.mesa3d.org/envvars.html#envvar-MESA_VK_DEVICE_SELECT_FORCE_DEFAULT_DEVICE

**Comment by ToastedWookiee** [comment]
Doesn't seem to make a difference either as part of a steam launch option, or set as an environment variable running mangohud with vkcube.

**Comment by exalented** [comment]
This happens with DXVK, vkd3d (https://github.com/HansKristian-Work/vkd3d-proton/commit/f37303b4933dc5e92f5f90e8d1812970e2736858) and native.

**Comment by n3thshan** [comment]
Happens to me too :(

**Comment by flightlessmango** [comment]
This *should* be fixed in latest git

**Comment by n3thshan** [comment]
@flightlessmango will u be making a new release anytime sooner which includes this commit? i can only test this with the flatpak build as i mainly game via flatpak apps such as bottles and prism launcher (minecraft)

**Comment by 17314642** [comment]
@n3thshan if you really need gpu usage, you can build flatpak yourself.

If you need further help, I can explain how to do it.

**Comment by exalented** [comment]
TY. Load % works great

**Comment by n3thshan** [comment]
> @n3thshan if you really need gpu usage, you can build flatpak yourself.
> 
> If you need further help, I can explain how to do it.
> 
> Also this might help: #1471

thanks for ur reply! and yes i will need some help figuring out how to build from the master branch because i did not understand what u have said in the linked issue :(

**Comment by flightlessmango** [comment]
closing as resolved
