### ISSUE TITLE
Will not load config file in games but loads it in vkcube

### ISSUE THREAD

**Issue by Mire01** [flightlessmango/MangoHud#1373]
I tried every fix that I could find for this but nothing helps. Mangohud in lutris games refuses to show anything other than the base config.
It does not matter what I try to do it will not load the config in any game installed over lutris. If I launch mangohud with vkcube it loads the config every time perfectly. 
I should mention that I tried to use goverlay and could not get it to recognize mangohud it kept saying it was not installed.

Latest distro of linux mint cinnamon and mangohud was installed with the instructions from "build from source". Any other info you need to try and help me just ask and I will give it.

**Comment by flightlessmango** [comment]
Are you mixing flatpak apps and native apps?
> I tried every fix that I could find

Like what? What paths have you tried for the config?

**Comment by flightlessmango** [comment]
closing for lack of information and inactivity
