### ISSUE TITLE
`engine_version=0` does not disable output text

### ISSUE THREAD

**Issue by saghm** [flightlessmango/MangoHud#1375]
**Describe the bug**

Setting the `engine_version=0` config option doesn't seem to affect the text `VULKAN` from displaying.

**List relevant hardware/software information**
- Linux Distribution: Arch Linux
- MangoHud version: 0.7.1
- GPU: AMD Radeon RX 6800M

**To Reproduce**
1. Run `mangohud vkcube` with no other options
2. Verify that the text `VULKAN` in is the HUD
3. Run `MANGOHUD_CONFIG='engine_version=0' mangohud vkcube`
4. Check if the engine version text is removed
(optional steps to help debugging)
5. Run `MANGOHUD_CONFIG='engine_version=0,engine_short_names=1' mangohud vkcube`
6. Verify that the engine version text is changed to `VK`
7. Run `MANGOHUD_CONFIG='engine_short_names=1' mangohud vkcube`
8. Verify that the output is unchanged
9. Run `MANGOHUD_CONFIG='engine_short_names=1,cpu_stats=0' mangohud vkcube`
10. Verify that the cpu info is removed as expected

**Expected behavior**

Setting `engine_version=0` should remove the engine version text from the HUD.

**Screenshots**

default settings (steps 1-2 above):
![image](https://github.com/flightlessmango/MangoHud/assets/5875560/2f6a064d-8f4d-403f-a421-7fb4d38390dc)

`MANGOHUD_CONFIG='engine_version=0' mangohud vkcube` (steps 3-4 above):
![image](https://github.com/flightlessmango/MangoHud/assets/5875560/585cee37-14f8-4ec6-a9e4-3f42a6e0e2c9)

`MANGOHUD_CONFIG='engine_version=0,engine_short_names=1' mangohud vkcube` (steps 5-6 above):
![image](https://github.com/flightlessmango/MangoHud/assets/5875560/dda8c813-4b24-4322-877d-a309e70a85b2)

`MANGOHUD_CONFIG='engine_short_names=1' mangohud vkcube` (steps 7-8 above):
![image](https://github.com/flightlessmango/MangoHud/assets/5875560/2101a18e-c0c6-4b4a-a501-fc757cb16c97)

`MANGOHUD_CONFIG='engine_short_names=1,cpu_stats=0' mangohud vkcube` (steps 9-10 above):
![image](https://github.com/flightlessmango/MangoHud/assets/5875560/aa60d5bf-ba00-468f-95cb-c1ebc5351db5)

**Additional context**
From taking a look at the code, I thought it might be due to `engine_settings` being missing from [`set_params_from_options`](https://github.com/flightlessmango/MangoHud/blob/bda2af47b032dcec810203d34a486562176afb0e/src/overlay_params.cpp#L591), but manually adding the line `params->enabled[OVERLAY_PARAM_ENABLED_engine_version] = 0;` and recompiling didn't help, and unfortunately it's been too long since I've done C++ for the amount of time it would take me to wrap my head around the logic there and in `src/hud_elements.cpp` to make the effort of looking into this myself feel worthwhile.

**Comment by StarTroop** [comment]
Does unsetting any other parameters work? I've been trying to configure some presets and so far I've found that I can't unset any parameters, and I assumed that was just the expected behaviour, as unintuitive as it seems. Could this potentially be a larger bug?

**Comment by flightlessmango** [comment]
![image](https://github.com/flightlessmango/MangoHud/assets/42713625/6180c4d5-ba80-4fbd-8eed-e1ecfce6e69b)
The version below vulkan is what `engine_version` is. If you want to remove "vulkan" it's `fps=0`

**Comment by saghm** [comment]
> Does unsetting any other parameters work? I've been trying to configure some presets and so far I've found that I can't unset any parameters, and I assumed that was just the expected behaviour, as unintuitive as it seems. Could this potentially be a larger bug?

I showed above that disabling the CPU info with the option `cpu_stats=0` works for me. I'm not sure if you mean something else or if that's not working for you.

> The version below vulkan is what engine_version is. If you want to remove "vulkan" it's fps=0

Ah okay, I thought it was its own entry, but I guess I misunderstood. My goal is to have the HUD only show the FPS info and the the time (without the label). So far, I've been able to use the following config to eliminate everything except the FPS info, the time (in a custom format), and the word "VULKAN":

```
legacy_layout=false

text_color=FFFFFF
position=bottom-right

fps
fps_limit_method=late
fps_color_change
fps_value=60,120

frametime=0

time
time_no_label
time_format=%l:%M:%S %p
```

![image](https://github.com/flightlessmango/MangoHud/assets/5875560/ab913e3d-d275-4353-8e22-de824256cd31)

Is it possible to eliminate the work `VULKAN` with options that currently exist? `fps_only` does remove it, but the width of the HUD itself seems to be truncated when I do that:

![image](https://github.com/flightlessmango/MangoHud/assets/5875560/495169f1-552b-4da1-b6f2-067a43196eaa)

I've tried setting `width` and `table_columns` to expand it, but neither seem to affect anything regardless of the value when `fps_only` is also set. `cellpadding_y` does seem to work to increase the height, but if there's a similar `cellpadding_x` setting, it doesn't seem to be changing anything for me (and doesn't seem to be listed in the [example conf](https://raw.githubusercontent.com/flightlessmango/MangoHud/master/data/MangoHud.conf), although I still tried it).

My suspicion is that this isn't possible right now and would require a dedicated setting like `fps_no_label`. If so, apologies for the confusion and I can close this issue.

**Comment by saghm** [comment]
To follow up, I was able to hack together basically what I was looking for with some trial and error, so I'll close this issue; if there's a need for a new option like I described, it probably would be cleaner to have a separate issue for it anyhow.

On the off chance someone wants something similar later and stumbles upon this thread, "solution" was to set the engine text color to the same as the background, disable the text outline, limit the number of columns to two (since I only wanted the FPS counter and the time) and then hardcoding the `width` and `cellpadding_y` to something that looked reasonable on my display:

```
cellpadding_y=0.1
table_columns=2
width=170

cpu_stats=0
gpu_stats=0

fps

frametime=0
frame_timing=0

time
time_no_label
time_format = %l:%M:%S %p

engine_short_names

text_outline=0
engine_color=191919
```

![image](https://github.com/flightlessmango/MangoHud/assets/5875560/84cc3c59-9e39-4ac0-b45a-4356ae6733ad)
