### ISSUE TITLE
Can't hide the graph

### ISSUE THREAD

**Issue by amithiel** [flightlessmango/MangoHud#138]
Hi there,

i'm sorry, probably just being dumb.. i'm not being able to hide the graph!
i mean, i want to disable the frametime and everything below.
in the conf file, tried to comment this line:

Display the frametime line graph
# frame_timing

but seems to have no effect

**Comment by flightlessmango** [comment]
It's not properly documented, but things that are enabled by default has to be explicitly disabled
`frame_timing=0`

**Comment by amithiel** [comment]
thanks so much! solved!
