### ISSUE TITLE
Is there a parameter to show the CPU Governor?

### ISSUE THREAD

**Issue by luisalvarado** [flightlessmango/MangoHud#1380]
This is just a question, not a bug. Is there a way to show the CPU Governor (performance, balance, powersafe), I ask because I have been recording a bunch of videos and just noticed today that the CPU governor has always been on powersafe, so I won't know the full FPS impact of this for each game recorded, but thought it would be a good idea to show it on MangoHUD so that for future reference I would know and be able to compare for a specific game the difference in performance between performance mode and powersafe mode.

**Comment by flightlessmango** [comment]
`exec=cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor`

something like that should work?

**Comment by luisalvarado** [comment]
@flightlessmango Yes that would work exactly. So then a parameter about cpu_governor or something, when enabled it shows the governor, might help others too when they did not know the governor was in powersave or to make sure future analysis of a recorded video shows in what mode they were.

**Comment by flightlessmango** [comment]
Since you can do this yourself with exec, I don't think it needs to be a param

**Comment by luisalvarado** [comment]
> Since you can do this yourself with exec, I don't think it needs to be a param

No, what I meant was to see the CPU Governor in the MangoHUD HUD. Don't know if I am explaining this right. Like an option in the visual HUD that says "CPU Governor: X" Where X is whatever was found in the system.

**Comment by flightlessmango** [comment]
I mean you can do this with the exec option in mangohud
```
custom_text=CPU Governor
exec=cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
```
No need to create a specific option for it

**Comment by luisalvarado** [comment]
Take me now lord. Wow, thank you buddy.

**Comment by flightlessmango** [comment]
How does that kill the purpose? You can show all the same things

**Comment by luisalvarado** [comment]
> How does that kill the purpose? You can show all the same things

Most likely bad way of putting it. I marked as solved to not create a bigger issue but I am doing a video for you to target all bugs here. I think that is much better, that way if I am doing it wrong you can also see that.

**Comment by luisalvarado** [comment]
@flightlessmango  Here you go friend - https://www.youtube.com/watch?v=bT1CmO3T8tk

**Comment by flightlessmango** [comment]
says the video is private.
But when you're using `legacy_layout=0` you need to specify each element and the order you want them to appear in.
for example
```
legacy_layout=0
gpu_stats
cpu_stats
vram
ram
fps
```

**Comment by luisalvarado** [comment]
Sorry @flightlessmango try the video link again. I will also test the comment left here.

**Comment by flightlessmango** [comment]
The way I explained it should resolve this issue

**Comment by luisalvarado** [comment]
You da man! @flightlessmango
