### ISSUE TITLE
MangoHUD misses showing several attributes until SHIFT+F10 is pressed.

### ISSUE THREAD

**Issue by luisalvarado** [flightlessmango/MangoHud#1381]
MangoHUD 0.7.2 (Compiled today) + Ubuntu 24.04

Whenever MangoHUD starts for a game it shows like this

![photo_2024-07-12_14-46-20](https://github.com/user-attachments/assets/f74131f3-890e-415c-8906-50b0646b67cd)

But if I press SHIFT + F10 it shows like this:

![photo_2024-07-12_14-47-27](https://github.com/user-attachments/assets/9eebbc83-25fb-494e-aa73-9bafba2f964a)

As you can see, for some reason, when it loads, the CPU Clock does not show, nor does the Power usage (although that one shows as 0.0W because I need to check some of my settings I believe).

Same for the GPU Power usage, it does not show, same for the VRAM clock speed.

**Comment by flightlessmango** [comment]
can you get a log with `PROTON_LOG=1 MANGOHUD_LOG_LEVEL=debug %command%` ?

**Comment by luisalvarado** [comment]
Here is the file. I made it into a ZIP File because OMG it was 20 MB for a 20 second moment.

[steam-750920.zip](https://github.com/user-attachments/files/16203311/steam-750920.zip)

I wanted to also add, is there a parameter where, when I start logging in a moment, meaning I press SHIFT + F2, it shows a little timer underneath the recording red icon? Meaning this

![2024-07-13_12-44](https://github.com/user-attachments/assets/26fb0d9d-d838-4fd9-824d-7ba82bd57c45)

when I start the recording, like a timer showing how long the logging in has been running (Instead of me having to grab the phone for example).

**Comment by flightlessmango** [comment]
No there is no option to show how long it's been recording

**Comment by luisalvarado** [comment]
@flightlessmango Thank you. No problem with the recording time. Do you need any more information for the issue with the SHIFT + F10  versus Default loading not showing certain parameters?

**Comment by luisalvarado** [comment]
Note that the values do show default if I enable them one by one, for example adding the cpu_mhz=1
 to the mangoHUD will reveal the mhz of the cpu by default, but again, pressing SHIFT+F10 still shows things that needed to be hidden away.

**Comment by flightlessmango** [comment]
> shows things that needed to be hidden away

I don't think I understand the issue?
Are you saying  that options that aren't in the config file is being shown?
What does the config file look like?

**Comment by luisalvarado** [comment]
@flightlessmango  Here you go friend - https://www.youtube.com/watch?v=bT1CmO3T8tk

**Comment by flightlessmango** [comment]
Okay I think I understand what's happening.
You're toggling through presets, eventually landing on the 3rd one which is pretty similar to your config.
Your config options override preset options, so when you set `cpu_mhz=0` it won't show cpu mhz in preset 3 even tho it's enabled by default in preset 3.

**Comment by luisalvarado** [comment]
Got it! So F10 is for presets, not just different layouts, but also presets that use those layouts. Thank you for solving the mystery and taking your time analyzing it.
