### ISSUE TITLE
CPU Power shows 0.0W still after changing permissions

### ISSUE THREAD

**Issue by luisalvarado** [flightlessmango/MangoHud#1382]
MangoHUD 0.7.2 (Compiled today) + Ubuntu 24.04 + 13900K CPU

I did follow the steps to read the CPU power, but still showed as 0.0w. When I checked all folders related to rapl I found this (if it helps):

![2024-07-12_14-54](https://github.com/user-attachments/assets/2f9148e5-80ce-471d-93c4-329204239262)

Showing you the content for both here if it helps:

![2024-07-12_14-56](https://github.com/user-attachments/assets/cfae4906-5475-42b8-aeaf-8c85a976feda)

Again, the command I rant was

`chmod o+r /sys/class/powercap/intel-rapl\:0/energy_uj`

**Comment by flightlessmango** [comment]
I can't repro this and I haven't heard of anyone else having this issue.
What does `ls -la /sys/class/powercap/intel-rapl\:0/energy_uj` return?

**Comment by luisalvarado** [comment]
I get this:

`-r-------- 1 root root 4096 Jul 27 15:10 /sys/class/powercap/intel-rapl:0/energy_uj`

**Comment by luisalvarado** [comment]
My next son will be named after you. I did a chmod on that specific fle and look at this:

![2024-07-27_19-22](https://github.com/user-attachments/assets/25ed1b32-f309-4b88-b0cb-9054c4cf3a48)

Of course the issue is that after rebooting it resets back to the r only for the owner. Thats my fault. Thank you for guiding me here.

**Comment by luisalvarado** [comment]
In case it helps, after rebooting several times for testing, at least on Ubuntu 24.04, I had to do it like this:

`chmod +r "/sys/class/powercap/intel-rapl:0/energy_uj"`

instead of

`chmod o+r /sys/class/powercap/intel-rapl\:0/energy_uj`

Because it would still not work.
