### ISSUE TITLE
MangoHud not changing the displayed stats

### ISSUE THREAD

**Issue by Headedbranch225** [flightlessmango/MangoHud#1384]
**Do not report issue for old MangoHud versions**

**Describe the bug**
Whenever I try and set the config for MangoHud, it always just defaults to 
![image](https://github.com/user-attachments/assets/4ec1d345-5335-431a-b7a9-6b8ee50e5f4b)

**List relevant hardware/software information**
- Pop!_OS latest
- latest Github release
- NVIDIA GTX 1660

**To Reproduce**
1. Install mangohud
2. not changing the display to the config file

**Expected behavior**
the settings change the display

**Screenshots**
already added above in describe section

**Additional context**
other things I have tried:
	Change the mangohud.conf file in /home/user/.config/MangoHud
	use the MANGOHUD_CONFIG env variable
	Try moving the config file to the game directory

**Comment by Headedbranch225** [comment]
![image](https://github.com/user-attachments/assets/7a863f9a-51d3-4ee4-ace0-8e1735f1e7b1)

**Comment by flightlessmango** [comment]
That looks correct yes
What does the inside of the config look like?

**Comment by Headedbranch225** [comment]
sorry for slow reply, but it is the example with some of the options uncommented so that I can check if it is working

**Comment by Headedbranch225** [comment]
I have found the issue but it doesn't seem to be cleared from export

**Comment by Headedbranch225** [comment]
I fixed by adding `unset MANGOHUD_CONFIG` to my .profile, my issue was that $MANGOHUD_CONFIG was set to the config folder for some reason
