### ISSUE TITLE
MangoHud does not work on Steam games on Ubuntu 24.04

### ISSUE THREAD

**Issue by brandon-dodds** [flightlessmango/MangoHud#1385]
**Describe the bug**
Using Ubuntu 24.04 and the latest release of MangoHud (0.7.2) steam proceeds to error out when mangohud is applied.

**List relevant hardware/software information**
- Ubuntu 24.04
- 0.7.2
- Radeon RX 6600

**To Reproduce**
1. Download MangoHud and install with the script command.
2. Find a game.
3. Launch with command parameters 'mangohud (with or without) --dlsym %command%'

**Logs**
`
chdir "/media/brandon/SSD/SteamLibrary/steamapps/common/MELTY BLOOD TYPE LUMINA"
ERROR: ld.so: object '/home/brandon/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/brandon/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Adding process 25184 for gameID 1372280
ERROR: ld.so: object '/home/brandon/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/brandon/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/brandon/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
/home/brandon/.local/share/Steam/ubuntu12_32/reaper: error while loading shared libraries: libxkbcommon.so.0: wrong ELF class: ELFCLASS64
Uploaded AppInterfaceStats to Steam
Game Recording - game stopped [gameid=1372280]
Removing process 25184 for gameID 1372280
`

**Comment by Leopard1907** [comment]
Make sure your Steam is not Snap or Flatpak.

**Comment by brandon-dodds** [comment]
![image](https://github.com/user-attachments/assets/2909cfc3-99c6-494c-a75e-7e37c58c011d)
This is what I get on Synaptic.

**Comment by brandon-dodds** [comment]
Solved by installing 32 bit drivers for libxkbcommon as follows:
`
sudo dpkg --add-architecture i386
sudo apt install libxkbcommon-x11-0:i386
`
