### ISSUE TITLE
Mangohud is not working for certain games(Starcraft 2,Heroes of the Storm)

### ISSUE THREAD

**Issue by RealMoosey** [flightlessmango/MangoHud#1388]
**Do not report issue for old MangoHud versions**

**Describe the bug**
Mangohud is not showing up in certain games

**List relevant hardware/software information**
- Linux Distribution - Pop!_OS 22.04
- MangoHud version - 0.7.2
- GPU - NVIDIA GeForce RTX 3060

**To Reproduce**
1. Install X game (some steam games too)
2. Input the command "mangohud" or "MANGOHUD=1" in the application command field(with the %command% end for steam games)
3. Launch the game
4. No mangohud 

**Additional context**
I am new to linux so there is possibly a good explenation why some games work and some games dont.
I got warcraft 3 reforged to work instantly but theese other ones are just not working.

**Comment by Headedbranch225** [comment]
Have you tried --dlsym added to the arguments, since they might need special hooking (I haven't played either so it might not work)

**Comment by RealMoosey** [comment]
Ok additional context for the problem; Warcraft 3 Reforged, Starcraft 2, Heroes of the Storm; are all installed using Lutris. 
And adding the "mangohud" command to the argument field inside the blizzard launcher did nothing.(tried with the --dlsym too but same problem)
Now i did find a post on reddit with the guide to add the value "MANGOHUD" to lutris (Properties-> System options ->Game execution) and set the value to 1. 
Now mangohud is there but the screen is black, and mangohud is spitting out some wierd values including "inf" on the DXVK ms field.

**Comment by flightlessmango** [comment]
Sounds like you've solved the issue
