### ISSUE TITLE
Mangohud not working in Assassin's Creed II steam

### ISSUE THREAD

**Issue by Kapy2003** [flightlessmango/MangoHud#1389]
I am on arch installed **steam and mangohud** using **pacman** every other game is working perfectly. Shockingly I forgot to provide launch option for some games like **THE FIRST DESCENDANTS**  but the mangohud overlay works fine so I don't mess with it until its gets frickked up. so my main problem is I recently installed **Assassin's Creed II** using steam and now the overlay doesn't work I tried:
1. mangohud %command% - **Game starts but doesn't show HUD**
2. mangohud.x86 %command% - **Game doesn't start**
3. MANGOHUD_DLSYM=1 mangohud %command% - **Game starts but doesn't show HUD**
4. MANGOHUD_DLSYM=1 mangohud.x86 %command% - **Game doesn't start**
5. MANGOHUD=1 %command% - **Game starts but doesn't show HUD**

what should I do now?

I did change the ubisoft game files to replace uplay launcher.

**Comment by flightlessmango** [comment]
Please issue the issue template.
Judging by `mangohud.x86` I assume you're using a very old version of mangohud

**Comment by Kapy2003** [comment]
everything is latest

**Comment by flightlessmango** [comment]
It's a 32bit game, do you have 32bit mangohud?

**Comment by flightlessmango** [comment]
> It's a 32bit game, do you have 32bit mangohud?

I assume you're missing 32bit as it works fine on my end
![image](https://github.com/user-attachments/assets/01d0207d-9426-4914-97f7-55927fd3a54d)
