### ISSUE TITLE
Skyrim SE on Steam

### ISSUE THREAD

**Issue by Ishavn13** [flightlessmango/MangoHud#1392]
So I was trying to get ManguHud up and running to see my stats in steam games. I was manly doing this for Skyrim since it's the only game I installed up to now.
I use Zorin OS, installed steam fron their "Software" and mangohud from the gz file available on github as well as by using `sudo apt install mangohud`. It wasn't working before or after and I was getting kind of annoyed so I don't know if it will cause any harm in the long run installing it both from file as well as via the terminal.

However, when trying to get mangohud started via
`mangohud %command%` in Skyrim under Launch Options, the **game simply isn't starting** at all. If I use 
`MANGOHUD=1 %command%` instead, the game starts but MangoHud is **not showing**.
Any suggestions? It seems I installed Steam as Flatpak. Does this mean I have to install MangoHud as flatpak too? How do I do that? Do I have to uninstall/purge the version I have right now before?

**Comment by Leopard1907** [comment]
Literally all info about that is written in this very Github page readme.

**Comment by Ishavn13** [comment]
Thank you for your comment, I read the readme, still have the issue.
I am not a Linux native, currently just trying my best to settle in. So any help is greatly appreciated.

**Comment by Leopard1907** [comment]
> Does this mean I have to install MangoHud as flatpak too? How do I do that?

https://github.com/flightlessmango/MangoHud?tab=readme-ov-file#flatpak
