### ISSUE TITLE
Inaccurate AVG and 1%

### ISSUE THREAD

**Issue by Faugus** [flightlessmango/MangoHud#1399]
Doing a comparison between Linux and Windows, I noticed that AVG and 1% are inaccurate.
Running the Returnal's benchmark, for example, the current FPS is higher on Windows most of the time, but the AVG and 1% are higher on Linux.

Arch Linux
mangohud 0.7.2-1
7800XT / 5700X3D

Comparison video:
https://youtu.be/5yJFjhqvt8g

![image](https://github.com/user-attachments/assets/49429d80-5cf0-4969-8cb7-8718288981c0)

**Comment by flightlessmango** [comment]
The 1% and avg metrics start recording when the app opens, so it's it's including frames that are not in the benchmark.
What you can do in mangohud is to reset the metrics when you start the benchmark `Shift_R+F9`, otherwise it will be collecting metrics for 10minutes backwards.

I don't know how afterburner handles this, or if they even have a way to reset the metrics, without insight it's difficult to adjust or justify adjusting.

Ultimately the best way to get a good comparison is to log the data in afterburner and mangohud and examine it

**Comment by Faugus** [comment]
Yes, I reset it with `Shift_R+F9` at the beginning of the benchmarks.
I did the same thing on MSI Afterburner.
I tried to reset both at the same time to get the most accurate comparison.

**Comment by flightlessmango** [comment]
> the current FPS is higher on Windows most of the time, but the AVG and 1% are higher on Linux.

You need a more objective measurement than just eyeballing it.
Create a log file at the same time and check if the avg and 1% in the hud are the same as the log file

**Comment by Faugus** [comment]
I started to log at the same time I reset the fps_metrics with `Shift_R+F9`.
Than I stopped the logging and at the same time I screenshotted.
AVG is a bit higher on fps_metrics. Maybe number rounding?

![Screenshot_20240810_143321](https://github.com/user-attachments/assets/7544fc8d-9af1-4f6a-a84d-d1be513c6e36)
[Cyberpunk2077_2024-08-10_14-32-18_summary.csv](https://github.com/user-attachments/files/16570419/Cyberpunk2077_2024-08-10_14-32-18_summary.csv)

**Comment by Faugus** [comment]
I did the same with Horizon Zero Dawn, which has a much longer benchmarking tool, so we can get more data.
![Screenshot_20240810_144705](https://github.com/user-attachments/assets/1120a39a-74c2-4854-8374-7ae8df8c13d7)
[HorizonZeroDawn_2024-08-10_14-44-14.csv](https://github.com/user-attachments/files/16570438/HorizonZeroDawn_2024-08-10_14-44-14.csv)

**Comment by flightlessmango** [comment]
The hud benchmark, the summary file and the fps_metrics option all had different ways of calculating the numbers, I've fixed this here 7fafed9cbacc8111362226a72a09baccde27a640

**Comment by Faugus** [comment]
I just compiled from source and tested it.
Looks like AVG is accurate now.
Thanks boss!
![Screenshot_20240814_224030](https://github.com/user-attachments/assets/7d196c78-307e-4858-987f-6067f1dcde94)
[HorizonZeroDawn_2024-08-14_22-37-43_summary.csv](https://github.com/user-attachments/files/16620491/HorizonZeroDawn_2024-08-14_22-37-43_summary.csv)

**Comment by Etaash-mathamsetty** [comment]
The Average FPS in Mangohud is calculated incorrectly is the conclusion I reached after doing some quick calculations (take with little bit of salt). 

let's take an example with the numbers presented in the video, the frametime spikes between 0.3 ms and 150 ms. 
fps_1 = 1000 / 0.3 = ~3000 fps
fps_2 = 1000 / 150 = ~6 fps

taking the average of these two we get ~1600 fps, which isn't quite right. 
Instead, I propose calculating it like this:

frametime_1 = 0.3 ms
frametime_2 = 150 ms

take the average, ~ 75 ms
1000 / 75 = ~ 13 fps, which is the expected result.

**Comment by flightlessmango** [comment]
It's been corrected here d102604291cfb6b5b18f6e51a6bc0ef85d188d9b
@Faugus let me know if it fixed the issue

**Comment by Faugus** [comment]
@flightlessmango now it's looking great!
https://drive.google.com/file/d/1gbJD7WRmaFPZz2mtujWFOUaRaGd_KsWs/view?usp=sharing

[b1-Win64-Shipping_2024-09-04_13-11-04_summary.csv](https://github.com/user-attachments/files/16873825/b1-Win64-Shipping_2024-09-04_13-11-04_summary.csv)

Thank you!
