### ISSUE TITLE
Issue with VRAM readings

### ISSUE THREAD

**Issue by ahmed-elsayed2017** [flightlessmango/MangoHud#14]
VRAM = 0  all the time, and it doesn't change at all.

**System information:**
**OS:** Kubuntu 19.10 - kernel: 5.3.0-29
**GPU:** AMD Radeon HD 8750M
**CPU:** Intel core I5 4200M
**Driver:** Mesa 20-devel (obiaf ppa)

**Comment by flightlessmango** [comment]
I think this is the same core issue as #7. It's more of a kernel issue, either they decided not to support older graphics cards or there is some inherent issue that makes it impossible. Either way we can't do anything about it here

**Comment by ahmed-elsayed2017** [comment]
`cat /sys/class/drm/card1/device/mem_info_vram_used` = 12288

**Comment by ahmed-elsayed2017** [comment]
I use `jackun_wip` branch, and this issue doesn't exist there. I don't know if this fix is pushed to master branch yet or not, but this issue is supposed to be fixed.

**Comment by ahmed-elsayed2017** [comment]
I build the master branch, and VRAM is working fine now.

This issue is fixed.

**Comment by ahmed-elsayed2017** [comment]
I went back to kernel 4.19, because of weird issues with my machine, and VRAM doesn't work any more.

**Comment by flightlessmango** [comment]
That is a kernel feature so it's possible it doesn't exist in that version, in that case there isn't much I can do
