### ISSUE TITLE
MangoHud crashes vulkaninfo on exit (Segmentation Fault)

### ISSUE THREAD

**Issue by FaelLiberatori** [flightlessmango/MangoHud#1401]
**Describe the bug**
When running vulkaninfo with MangoHud, it results in a segmentation fault.

**List relevant hardware/software information**
- Linux Distribution: Arch Linux
- MangoHud version: v0.7.2 
- GPU: NVIDIA GeForce RTX 3080

**To Reproduce**
1. Open a terminal emulator (my case, yakuake)
2. Run the "mangohud vulkaninfo" command
3. vulkaninfo is going to run as expected, but you are going to get a "Segmentation fault (core dumped)" error on exit.

**Expected behavior**
MangoHud should not crash on exit.

**Screenshots**
Not applicable.

**Additional context**
It seems similar to [#1198](https://github.com/flightlessmango/MangoHud/issues/1198), but I'm unable to reproduce the error using software other than vulkaninfo. Vkcube, glxgears, and games do not crash when exiting.

I identified this issue after seeking assistance on the [Arch Linux Forum](https://bbs.archlinux.org/viewtopic.php?pid=2189524). More detailed information and the core dump backtrace can be found in this topic.

**Comment by flightlessmango** [comment]
can't repro this on latest git. Please verify if it's still an issue

**Comment by FaelLiberatori** [comment]
It looks like the bug has been fixed. It's still a thing in the latest release (v0.7.1), but I can't reproduce this on latest git (v0.7.2-74). Thank you!
