### ISSUE TITLE
Command output plugin/feature

### ISSUE THREAD

**Issue by birdie-github** [flightlessmango/MangoHud#1405]
Please add the following feature: a command output.

The user specifies the program to run, and the library simply runs it at specified intervals and shows on the screen along with the specified prefix. So, it will be three things:
```
CommandX=command | to | run # I've included pipes to emphasize that it could be several commands 
TitleX=Title or Prefix to display on the screen
IntervalX=1.0 (with milliseconds precision)
```
Where X could be anything from 0 to infinity.

Of course, the command must be run in a separate thread to avoid any stalls for the main thread or the game.

This will instantly address/fix #1390 and allow people to monitor whatever they want without asking you to write code for it.

**Comment by flightlessmango** [comment]
look at `exec` and `custom_text`

**Comment by birdie-github** [comment]
Done that, I see no output at all:

![output](https://github.com/user-attachments/assets/f7c9c3ae-63fe-494f-bbf5-1f3933347b66)

[MangoHud.zip](https://github.com/user-attachments/files/16613241/MangoHud.zip)

**Comment by flightlessmango** [comment]
As documented, you have to use legacy_layout=0.
However I can't vouch for old mangohud versions

**Comment by birdie-github** [comment]
> As documented, you have to use legacy_layout=0.
> However I can't vouch for old mangohud versions

Thanks it works now!

Still, this is **not** articulated in the sample config file at all. Would be nice if you did not to deal with my reports like this one. It's working now as expected.

I would still love to see the options outlined above being implemented.

I've no idea how often `exec=` is being executed and I don't want it to run every frame or so.

**Comment by flightlessmango** [comment]
It update on the `fps_sampling_period` param which is 500ms by default

**Comment by birdie-github** [comment]
Thanks a ton.

Here's the final version that works as expected:

```bash
legacy_layout=0
fps_sampling_period=1000
## Display custom text
custom_text=Power
### Display output of Bash command in next column
exec=turbostat --quiet --num_iterations 1 --interval 0.99 --show PkgWatt --Summary | tail -1
```
