### ISSUE TITLE
What's the way to display frametime graph with legacy_layout=0?

### ISSUE THREAD

**Issue by shmerl** [flightlessmango/MangoHud#1407]
When using `legacy_layout=0`, you need to explicitly configure all elements. How can one display frametime graph that's shown by default when used without `legacy_layout=0`? Documentation doesn't mention any method.

**Comment by flightlessmango** [comment]
`frame_timing` is what you're looking for

**Comment by shmerl** [comment]
Ah, got it. Thanks. It would be neat to add it to the table since it's one of the major ones.

**Comment by shmerl** [comment]
And unrealted, but is there some way to turn some metric into a graph instead of a number? I've seen something like that in the past but not sure if that's a removed or still existing feature.

**Comment by shmerl** [comment]
I think I figured it out. I need to add this type of values inside my `MANGOHUD_CONFIG`:

```
...,graphs=cpu_load,graphs=gpu_load,...
```
