### ISSUE TITLE
I am new to linux and I dont know how to fix this

### ISSUE THREAD

**Issue by Eyeofona** [flightlessmango/MangoHud#1412]
[MANGOHUD] [error] [overlay_params.cpp:1018] Failed to read presets file

**Describe the bug**
(sh: line 1: intel_gpu_top: command not found)

**List relevant hardware/software information**
- Nobara 39
- Vulkan Instance Version: 1.3.280
- GPU - 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz

**Comment by flightlessmango** [comment]
You haven't described what is going wrong

**Comment by Eyeofona** [comment]
I got hacked
