### ISSUE TITLE
Mangohud shows wrong GPU

### ISSUE THREAD

**Issue by ghost** [flightlessmango/MangoHud#1413]
**Do not report issue for old MangoHud versions**

**Describe the bug**
MangoHud shows GPU load for iGPU instead of dGPU

**List relevant hardware/software information**
- arch
- MangoHud version
- RX 6800M + Ryzen 9 5900HX APU

**Screenshots**
![image](https://github.com/user-attachments/assets/fe5dd634-7851-4d85-99ae-c53955498432)
![image](https://github.com/user-attachments/assets/1e84f5b3-c7a5-4563-b655-182f2835951d)

**Comment by KhofeKat** [comment]
Same issue on

- Fedora 40
- Ryzen 5 7535HS
- AMD ATI Radeon RX 6400/6500 XT/6500M 
- AMD ATI Radeon 680M

![image](https://github.com/user-attachments/assets/cfbf9643-81b9-4b42-a826-9055bead258b)
![image](https://github.com/user-attachments/assets/b9b2d8bd-ed4b-4aa5-9be1-66b624482bdb)
![image](https://github.com/user-attachments/assets/335226d7-faef-4929-b5a0-e60d94134145)

**Comment by flightlessmango** [comment]
Should  be resolved in latest master
