### ISSUE TITLE
MangoHud not working for me on Beyond All Reason (works for other people)

### ISSUE THREAD

**Issue by ngraham20** [flightlessmango/MangoHud#1415]
**Do not report issue for old MangoHud versions**

**Describe the bug**
When attempting to use MangoHud with [Beyond All Reason](https://www.beyondallreason.info), it won't show up even with the `--dlsym` argument, and it doesn't seem to be limiting my FPS, so I believe it is not launching at all. No errors or outputs are printed to the console though.

**List relevant hardware/software information**
- Linux Distribution: Nobara 40
- MangoHud version: v0.7.2-11-gf8fb9aa
- GPU: AMD 7700S

**To Reproduce**
1. Download Beyond All Reason appimage
2. `mangohud --dlsym ./beyondallreason.appimage`
3. Start the game from the launcher
4. Mangohud does not show up

**Expected behavior**
Mangohud should show up

**Additional context**
`mangohud --dlsym ./beyondallreason.appimage` has worked for other people that I have asked to help me, so I am running into a bug that's specific to my system or setup

**Comment by ngraham20** [comment]
It turns out that for whatever reason AppImageLauncher was interfering with mangohud. Not sure why though, and I'm interested to see if there's a way to get mangohud to work through appimagelauncher

**Comment by flightlessmango** [comment]
> AppImageLauncher was interfering with mangohud

What makes you draw that conclusion?
Does mangohud work with vkcube and or glxgears?

**Comment by ngraham20** [comment]
> What makes you draw that conclusion? Does mangohud work with vkcube and or glxgears?

because when I uninstaled appimagelauncher, it suddenly worked

and yes, it works with both vkcube and glxgears just fine

**Comment by flightlessmango** [comment]
I would guess it's swallowing environment variables
I'll close this as it's not a mangohud issue
