### ISSUE TITLE
2 Mangohud instances on top of eachother

### ISSUE THREAD

**Issue by GitBingus** [flightlessmango/MangoHud#1416]
Hi all,

Whenever I launch a Steam game (I cannot replicate this elsewhere), 2 MangoHud instances show instead of just one.
(See above)

Any ideas?

**List relevant hardware/software information**
- Pop!_OS 22.04 LTS "Jammy"
- MangoHud version v0.7.2-42-g1d47ed8
- NVIDIA RTX 4060Ti 8GB

**Expected behavior**
I would have expected the game to have 1 MangoHud instance, not two overlayed atop each other.

**Screenshots**
![image](https://github.com/user-attachments/assets/1a3f4af7-9d98-4b88-a4e4-0854f2106da0)

**Additional context**
Heroic Launcher works as intended when I use the MangoHud option.

**Comment by Leopard1907** [comment]
That means you have two Mangohud's installed. Delete either one you got from repo or one you got from Github install script.

As for why Heroic does work correctly; probably Flatpak and you can't have two Mangohud's within Flatpak. So more user error resistant by nature.

**Comment by GitBingus** [comment]
> That means you have two Mangohud's installed. Delete either one you got from repo or one you got from Github install script.
> 
> 
> 
> As for why Heroic does work correctly; probably Flatpak and you can't have two Mangohud's within Flatpak. So more user error resistant by nature.

Wow. Seems i'm a bit stupid, bc that fixed it! Thank you!
