### ISSUE TITLE
OpenGL games stuttering on stat refresh only when mangohud GUI open

### ISSUE THREAD

**Issue by steveyh25** [flightlessmango/MangoHud#1420]
- Mint 22
- 0.7.2
- 3060Ti

Various OpenGL games are exhibiting stutter ONLY when the mangohud GUI is open. At precisely 500ms intervals I can see stutter in game that correlates to the frametime - this then resolves itself (i.e. no stutter) when the mangohud GUI is disabled. Upon re-opening the mangohud GUI after a few seconds, it appears as though the frametimes over the previous 1-2 seconds still show a stutter occurring, but this was not observable in game when the GUI was off (basically I can only see the stutter in game when the GUI is enabled).

Games confirmed this is an issue in:

Torchlight 2
Project Zomboid

This even occurs when without any global config being present

![stutter](https://github.com/user-attachments/assets/dbcda752-b5e9-4871-b866-24131bd350e6)

**Comment by flightlessmango** [comment]
What mangohud version?
Are you using either the `exec` option or `throttling_status` ?

**Comment by steveyh25** [comment]
v0.7.2 - exec no, throttling_status yes - isn't this on by default?

**Comment by steveyh25** [comment]
Apologies... I'll close this...

from the main page:

throttling_status - Show if GPU is throttling based on Power, current, temp or "other" (Only shows if throttling is currently happening). Currently disabled by default for Nvidia as it causes lag on 3000 series

I thought I retrieved a default MangoHud.conf from somewhere in this repository, but after turning off throttling_status the frametimes are now perfect again

Thanks for pointing out the throttling_status parameter
