### ISSUE TITLE
OSX Support?

### ISSUE THREAD

**Issue by hmaarrfk** [flightlessmango/MangoHud#1425]
**Do not report issue for old MangoHud versions**

**Describe the bug**

**List relevant hardware/software information**
Do you support OSX or plan to?

**To Reproduce**
I get errors that waiting for keypress is not defined on osx.

see build logs in: https://github.com/conda-forge/staged-recipes/pull/27526

**Comment by flightlessmango** [comment]
>  Do you support OSX or plan to?

Is it possible to do? Does vulkan exist on OSX?

**Comment by hmaarrfk** [comment]
I guess you gave me my answer.

 I use https://github.com/gfx-rs/wgpu and they claim to be able to use MoltenVK, but..... i never got it to work on conda-forge so i'm not so interested. I just wanted to understand your features.
