### ISSUE TITLE
Use NVML to get the fan speed???

### ISSUE THREAD

**Issue by hmaarrfk** [flightlessmango/MangoHud#1426]
I'm not entirely sure about the codepath, but I was looking at what features I might be missing without XNVCRT 
and it seems that it might be related to one fan query

https://github.com/flightlessmango/MangoHud/blob/feef6e395b6e824b7f12af127818e8ffbfc23305/src/gpu.cpp#L57

But elsewhere in your code, you actually use NVML to query a seemingly similar property
https://github.com/flightlessmango/MangoHud/blob/feef6e395b6e824b7f12af127818e8ffbfc23305/src/nvml.cpp#L71

Note that there is also nvmlDeviceGetFanSpeed_v2
https://docs.nvidia.com/deploy/nvml-api/group__nvmlDeviceQueries.html#group__nvmlDeviceQueries_1g888c927906705a639b1ac4bdf6b7bfef

**Comment by flightlessmango** [comment]
nvml can't report fan speed in rpm, that's why we prefer xnvctrl if available

**Comment by hmaarrfk** [comment]
hmm ok that is strange. 

i would have figured that xnvctrl would be a thin wrapper around nvml.

Their source somewhat indicates that too
https://github.com/NVIDIA/nvidia-settings/blob/a6e6c02447676a9e691cf79884fd5790afbe3e49/src/libXNVCtrlAttributes/NvCtrlAttributesNvml.c#L1368

but if you can read a meaninful number, then i believe you!

Thanks for a cool tool!
