### ISSUE TITLE
32bit version missing in Fedora package

### ISSUE THREAD

**Issue by SolidTux** [flightlessmango/MangoHud#143]
The Fedora package only contains the following files

```
➤ dnf repoquery --list mangohud
Letzte Prüfung auf abgelaufene Metadaten: vor 0:01:47 am So 03 Mai 2020 00:38:46 CEST.
/usr/bin/mangohud
/usr/lib/.build-id
/usr/lib/.build-id/62
/usr/lib/.build-id/62/dc0030957c28246f1e75be03d86509253113af
/usr/lib64/mangohud
/usr/lib64/mangohud/libMangoHud.so
/usr/share/doc/mangohud
/usr/share/doc/mangohud/MangoHud.conf
/usr/share/doc/mangohud/MangoHud.conf.example
/usr/share/doc/mangohud/README.md
/usr/share/licenses/mangohud
/usr/share/licenses/mangohud/LICENSE
/usr/share/vulkan/implicit_layer.d/MangoHud.x86_64.json
```

Is there a way to get the 32bit support without installing from source? There is no x86 package available any more as Fedora 31 dropped the 32bit support.

**Comment by flightlessmango** [comment]
You can use the release package [MangoHud-v0.3.5.tar.gz](https://github.com/flightlessmango/MangoHud/releases/download/v0.3.5/MangoHud-v0.3.5.tar.gz)

**Comment by h3o66** [comment]
maybe a alternative, but the packaged version is a bit older:
https://copr.fedorainfracloud.org/coprs/sentry/mangohud-i386/

**Comment by SolidTux** [comment]
Thanks! I don't know, why I didn't think of the release package ...
