### ISSUE TITLE
Large filler space after all label texts

### ISSUE THREAD

**Issue by ItsKipz** [flightlessmango/MangoHud#1439]
**Describe the bug**
On all presets and including a custom setting, there is a large amount of blank space after the label text and before the numbers. This is using the same presets as I was using yesterday, and only started happening after a SteamOS update and a subsequent restart.

**List relevant hardware/software information**
- OS: SteamOS 3.6.14 (beta)
- MangoHud Version: v7.0.2-rc3-11-g31f2ca5
- GPU: AMD Radeon Graphics 

**To Reproduce**
1. Use the software.

**Expected behavior**
Normal spacing after label text.

**Additional context**
Happens in every game, and again config is completely unchanged from yesterday when it worked as expected.

**Screenshots**
Screenshots are attached, all highlighted areas are spacing that was not present yesterday.

![screenshot_1](https://github.com/user-attachments/assets/b2333e8d-26c0-46e9-9eb1-22232f32454f)
![screenshot_2](https://github.com/user-attachments/assets/84232ce7-0df2-4981-95fd-ff13e25f2777)
![screenshot_3](https://github.com/user-attachments/assets/1543c2ad-65e3-489a-925b-ec795444e00a)
![screenshot](https://github.com/user-attachments/assets/d8f9435f-ba4f-4b00-8cc7-b789c2aa81b1)
 
Below is the config I am using in the final screenshot, if that helps.

horizontal
horizontal_stretch=0
cpu_stats=0
gpu_stats=0
frame_timing=0
frametime=0
fps
fps_text=.
fps_color_change
fps_value=30,60,90
time
time_format=%I:%M %p
time_no_label
width=110
legacy_layout=0
table_columns=2
engine_color=020202
battery_color=020202
text_outline=0

**Comment by ItsKipz** [comment]
Bumping as this issue is still present with a compile from source after the latest commit.

**Comment by flightlessmango** [comment]
I don't fully understand what the issue is, it looks normal to me.
The layout is a table and the metrics are aligned to the right.
A comparison showing how it was different before would be useful

**Comment by ItsKipz** [comment]
I sadly do not have any screenshots of how it functioned before, as I did not expect the sudden change in functionality. If the change is that the text is now aligned to the right (for instance, in the horizontal mode, having an arbitrary width for each column of the table and right-aligning it within that column), how do I revert back? I would like it ideally so that the only thing that shows is the FPS number, a divider, and then the time, but if there must be text then I would like the old functionality back of having no gap between the text and the number.

**Comment by flightlessmango** [comment]
Looking at the picture you've provided in horizontal mode, that's how it's always been.
Every value has space for 3 digits so that the entire hud doesn't have to change width every time a value goes from 9 to 10 for example

**Comment by ItsKipz** [comment]
That is understandable, but the problem is that after the text (which in this example I have set to a single period to make it as small as possible) there is more than 4 digits worth of space. Again, as of a few updates ago, the text was not taking up any space and there was ~3 digits worth of area between the left side and the center divider.

If this is working as intended with the text, how can I disable the text entirely?

**Comment by ItsKipz** [comment]
Resolved the issue. This can be worked around by ignoring the documentation and specifying "fps_only" alongside the other options, which in horizontal mode allows the other options to work fine while removing the FPS text and bugged filler space.
