### ISSUE TITLE
Appears to be tripping VAC

### ISSUE THREAD

**Issue by SaphiraKai** [flightlessmango/MangoHud#1442]
This is not a bug report, since it's almost certainly not a fixable MangoHud problem and rather an issue with VAC itself, but I figured I'd at least post it here to document the fact that I'm having this issue.

Recently, I've noticed I can't run CS2 with MangoHud enabled for longer than 10-15ish minutes before I get kicked from the game due to an "inconsistent connection to VAC servers" or something along those lines. After I receive that message I can no longer queue for matches, even after restarting, until I disable MangoHud, after which I can connect and play normally.

As I said, this is most likely not something MangoHud can fix, as I understand it requires hooking into the game process in a way that may look similar to a cheat. If anyone has any tips or tricks to get it working again, I'd love to hear them!

**Comment by flightlessmango** [comment]
This should be reported on the csgo github page

**Comment by SaphiraKai** [comment]
Didn't realize there was one. I'll post it there
