### ISSUE TITLE
mangohud version 0.7.2-2 appears on every gnome app on gnome shell version 47

### ISSUE THREAD

**Issue by Zer0Meow** [flightlessmango/MangoHud#1443]
Im on arch linux on gnome-shell version 47 and mango hud version 0.7.2-2 (the version that is showing on pacman) and after the new gnome update, mngohud appears on every official gnome app like gnome settings gnome extension all that, i wanted to know if i can fix this issue or if ill have to wait it out

**Comment by flightlessmango** [comment]
Because you have set `MANGOHUD=1` in /etc/environment. don't

**Comment by Zer0Meow** [comment]
> Because you have set `MANGOHUD=1` in /etc/environment. don't

Ah thank you
