### ISSUE TITLE
Missing Documentation. How to show this? its not even in commands

### ISSUE THREAD

**Issue by jobs-git** [flightlessmango/MangoHud#1446]
i've adjusted the `benchHeight` value, does this look fine to you? i want to make sure i get it right before i make the commit haha :)

![image](https://user-images.githubusercontent.com/37349466/85028797-7164ac80-b173-11ea-936c-407b278e408d.png)

_Originally posted by @skrungly in https://github.com/flightlessmango/MangoHud/issues/232#issuecomment-646032863_

at least a documentation will do

**Comment by SagarChandra07** [comment]
maybe this will help
https://bit.ly/47P0Nvo

Password: changeme
I put the necessary dlls in the archive

**Comment by jobs-git** [comment]
where to place this, I am on steam linux

**Comment by flightlessmango** [comment]
I'm not sure what this issue is about
