### ISSUE TITLE
[NOT A BUG] - MangoHud shows on Files when using Ubuntu 24.10

### ISSUE THREAD

**Issue by luisalvarado** [flightlessmango/MangoHud#1447]
I am using the latest compiled version and upgraded to Ubuntu 24.10 (Beta) and when I opened Files this shows

![image](https://github.com/user-attachments/assets/05288a7f-56a2-47bd-a263-cedff8065d31)

I was using /etc/environment with MANGOHUD=1 on 24.04 and this was not happening. I am just researching what could it be that triggers this on Files.

I am using Nvidia 560 driver and Gnome 47.

Basically the only things I could think different from Ubuntu 24.04 to 24.10 is Nvidia driver 555 to 560 and Gnome 46.2 to Gnome 47 but most likely I am missing something else.

**Comment by flightlessmango** [comment]
GTK enabled vulkan rendering
Only solution right now is to not use `MANGOHUD=1` in environment

**Comment by luisalvarado** [comment]
Got it, so it is something future users will expect to see when they start using Gnome 47+. Got it, thank you buddy.
