### ISSUE TITLE
New Feature: Show currently playing VLC track.

### ISSUE THREAD

**Issue by krem-Kalashnikov** [flightlessmango/MangoHud#145]
Love the inclusion of the Spotify track, it's a nice little feature that a lot of people will use. I prefer using VLC to listen to my music, is there a chance of VLC info being included? # #

**Comment by DominykasPetke** [comment]
Or, an easier change would be to show information from any MPRIS capable player (Spotify is one of them as well)

**Comment by jackun** [comment]
It already is

**Comment by krem-Kalashnikov** [comment]
For some reason I had to restart and add the media_player entry at the top of my configs for it to work, closing this now.

**Comment by plasticbomb1986** [comment]
Ahha, so thats why it wants to access spotify, havent seen that one. Can i disable it?

**Comment by flightlessmango** [comment]
@plasticbomb1986 it's not enabled by default, so I assume you're using the `full` param? You can probably do `MANGOHUD_CONFIG=full,media_player=0`
