### ISSUE TITLE
Playing Need for speed most wanted 2005 (32 bit) does not display GPU usage. It is always at 0%. 

### ISSUE THREAD

**Issue by n3thshan** [flightlessmango/MangoHud#1454]
**Describe the bug**
When playing nfs mw, frame rate works but GPU usage is always at 0%. I use mangohud with bottes and downloaded mangohud from the gnome store. No other games to test unfortunately. `flatpak override --filesystem=xdg-config/MangoHud:ro` command was applied. 

**List relevant hardware/software information**
- Fedora Silverblue 40/Project Bluefin stable branch
- MangoHud flathub 0.7.2
- Intel Arc Graphics that comes with intel core ultra 7 155h laptop SoC 

**To Reproduce**
1. Ensure "Monitor Performance" in bottles is toggled
2. Run NFSMW 2005 executable (speed.exe) 
3. Overlay will show GPU usage as 0%

**Expected behavior**
GPU usage needs to be displayed accurately.

**Screenshots**
![Screenshot from 2024-10-05 15-51-55](https://github.com/user-attachments/assets/12571e36-3027-40f8-87fb-89232334a99b)

**Comment by exalented** [comment]
https://github.com/flightlessmango/MangoHud/issues/1372

**Comment by n3thshan** [comment]
can mangohud still utilize intel_gpu_top? AFAIK they removed it right?

**Comment by flightlessmango** [comment]
flatpak doesn't have access to `/proc` by default, this is required to get GPU load on intel.
`--filesystem=host-etc` might help

**Comment by n3thshan** [comment]
> flatpak doesn't have access to `/proc` by default, this is required to get GPU load on intel. `--filesystem=host-etc` might help

this unfortunately didnt work. I also gave bottles those permissions as well. Anyway heres the list of commands i tried. I also restarted to see if it worked but unfortunately nope. Also mind you i have not installed intel_gpu_top (intel-gpu-tools).

The commands:
```
sudo flatpak override org.freedesktop.Platform.VulkanLayer.MangoHud --filesystem=host-etc 
flatpak override org.freedesktop.Platform.VulkanLayer.MangoHud --user --filesystem=host-etc 
```

**Comment by exalented** [comment]
This should be fixed in the next release.
