### ISSUE TITLE
Team Fortress 2 runs out of memory

### ISSUE THREAD

**Issue by marhkb** [flightlessmango/MangoHud#146]
When using mangohud in Team Fortress 2 it crashes approximately after 15 - 30 minutes with an out of memory error.

{lib32}-mangohud are installed from chaotic-aur Arch Linux repository. 

Systemifo
```
Distro Arch Linux
OGL: Mesa 20.0.5
GPU: Radeon RX 5700 XT
```

Steam-runtime is used instead of steam native.

**Comment by flightlessmango** [comment]
Could you see if this issue still appears with mangohud-git?
