### ISSUE TITLE
regression: Cpu temp is always 0 C

### ISSUE THREAD

**Issue by Leopard1907** [flightlessmango/MangoHud#1462]
**Describe the bug**

It was working with 0.7.2 and some few months old git, with latest git it always reports 0 C.

**List relevant hardware/software information**
- Linux Distribution: EndevaourOS ( Arch based )
- MangoHud version : master
- GPU : 7900XTX, igpu on 7800X3D

**To Reproduce**

Just build git.

**Expected behavior**

Cpu temp to be reported again.

**Comment by gort818** [comment]
Should be fixed here bef3a29f7142e10e6c6014d49d1ef7dc1aa0a20d
