### ISSUE TITLE
Texture issues in FFXIV when mangohud is enabled.

### ISSUE THREAD

**Issue by XNEP1** [flightlessmango/MangoHud#1465]
**Describe the bug**
Just as the title says, when I enable mangohud in Final Fantasy XIV I start having problems with blurry textures when they are far away or in oblique angle. The logo in the menu also becomes all pixelated during the animation.

**List relevant hardware/software information**
- Arch Linux 6.11
- MangoHud v0.7.1
- GPU 6750xt
- radv Mesa 24.2.5-arch1.1
- DXVK v2.4-73
- Proton 9.0-3

**To Reproduce**
1. set env MANGOHUD=1
2. launch the game
3. You can see it's wrong when the expansion logo in the intro is all pixelated. (Screen shot below shows how it looks and how it should be)

**Expected behavior**
Game graphics should not be affected when mangohud is enabled.

**Screenshots**
These two images demonstrate a problem with blurry textures when they are far away or oblique.
I drew red circles in the areas that are easier to see.

(with mangohud)
![ffdalamud](https://github.com/user-attachments/assets/3c5ddead-2e09-4653-a95f-5516a40228c4)

(without mangohud)
![ffsteam](https://github.com/user-attachments/assets/c1b0cc1d-ce56-475a-bea1-91726dfdbe41)

(with mangohud)
![fflogodalamud](https://github.com/user-attachments/assets/a844319f-095e-4557-b814-7723fa0bbc3b)

(without mangohud)
![fflogosteam](https://github.com/user-attachments/assets/7213b278-aba3-439c-a184-94d7ba888675)

**Comment by flightlessmango** [comment]
Don't use the `af`, `retro` or `picmip` options if you're experiencing graphical issues

**Comment by XNEP1** [comment]
Oh it worked.
I had no idea that MangoHud was capable of applying this kind of filter.

Thank you very much =)
