### ISSUE TITLE
[Feature Request]  Alternative overlays

### ISSUE THREAD

**Issue by undefinedactive** [flightlessmango/MangoHud#1468]
#### What does your feature request improve on?
The feature would allow a user to change the design of the overlay.

Example:

![example from CleanMeter project](https://private-user-images.githubusercontent.com/13068064/378096525-6c7bd91a-7e9a-4c38-a450-d6e2ce26bcd4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2OTI4MzYsIm5iZiI6MTcyOTY5MjUzNiwicGF0aCI6Ii8xMzA2ODA2NC8zNzgwOTY1MjUtNmM3YmQ5MWEtN2U5YS00YzM4LWE0NTAtZDZlMmNlMjZiY2Q0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDE0MDg1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3YWU1ZTYyZTBkMjY5YmJmZTQ2NzNiZGY1YTA0NzJkNDJlZjBkYjY2ZjM1N2FlNzkxZGIyZGU1NGQyNWU4YTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jY7EMhTsOS4B34OK3ECkuJeL9EGA8uVgWgvCb2Atvsg)

From [CleanMeter](https://github.com/Danil0v3s/CleanMeter)

**Comment by radiolamp** [comment]
That would be great.

**Comment by flightlessmango** [comment]
This is out of scope for this project
