### ISSUE TITLE
Is there a way to build a flatpak?

### ISSUE THREAD

**Issue by dramirezRT** [flightlessmango/MangoHud#1471]
Hey is there a script or something to build the flatpak for local install?

**Comment by 17314642** [comment]
Yes.

```
git clone --depth=1 "https://github.com/flathub/org.freedesktop.Platform.VulkanLayer.MangoHud"
flatpak-builder --install --user --force-clean build_dir org.freedesktop.Platform.VulkanLayer.MangoHud.yml
```

But beware, if you want to build master branch, you need to modify .yml to download and patch submodules. If you need that, I upload a patched .yml file.

**Comment by flightlessmango** [comment]
This discussion should be moved to the [flatpak repo](https://github.com/flathub/org.freedesktop.Platform.VulkanLayer.MangoHud)
