### ISSUE TITLE
[FEATURE REQUEST] TOGGLE CPU TURBO

### ISSUE THREAD

**Issue by LemuelDayrit** [flightlessmango/MangoHud#1472]
I dont know if its possible to add that for specific game that have mangohud like for the whole system the cpu turbo was enabled but you can disable the turbo for what game that has mangohud

**Comment by flightlessmango** [comment]
Not sure what you mean by turbo, like setting cpu governor to performance?
This is likely out of scope for mangohud, you'd want to look at something like gamemode instead
