### ISSUE TITLE
Does not let TF2 start

### ISSUE THREAD

**Issue by supervitu64** [flightlessmango/MangoHud#1474]
**Do not report issue for old MangoHud versions**

**Describe the bug**
Putting `mangohud %command%` on the launch options does not let TF2 start. I also have `gamemode %command%` but i don't know if that could possibly interfer with it.

**List relevant hardware/software information**
- Linux Distribution: Linux Mint 22 Wilma
- MangoHud version: Latest as of writing the issue
- GPU: Nvidia EVGA GT 730

**To Reproduce**
1. Put the command on the launch options.
2. Start TF2.
3. Instant crash.

**Expected behavior**
TF2 starts and shows the Mango HUD.

**Comment by flightlessmango** [comment]
Can you be more specific as to what mangohud version it is?

**Comment by supervitu64** [comment]
0.7.2

**Comment by supervitu64** [comment]
`wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
wine: could not load kernel32.dll, status c0000020
gamemodeauto: 
chdir "/home/super/.steam/debian-installation/steamapps/common/Team Fortress 2"
ERROR: ld.so: object '/home/super/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Game Recording - would start recording game 440, but recording for this game is disabled
Adding process 16654 for gameID 440
ERROR: ld.so: object '/home/super/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/super/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/super/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
gamemodeauto: 
Adding process 16655 for gameID 440
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/super/.steam/debian-installation/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/super/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/super/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Adding process 16667 for gameID 440
Adding process 16668 for gameID 440
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
pid 16783 != 16781, skipping destruction (fork without exec?)
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
Adding process 16781 for gameID 440
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
Adding process 16782 for gameID 440
Adding process 16784 for gameID 440
Adding process 16785 for gameID 440
command line too long, 512 max
Game Recording - game stopped [gameid=440]
Removing process 16785 for gameID 440
Removing process 16784 for gameID 440
Removing process 16782 for gameID 440
Removing process 16781 for gameID 440
Removing process 16668 for gameID 440
Removing process 16667 for gameID 440
Removing process 16655 for gameID 440
Removing process 16654 for gameID 440

`

**Comment by flightlessmango** [comment]
>  I also have gamemode %command%

Can you show your full launch option?

**Comment by supervitu64** [comment]
`gamemoderun %command% -novid -nojoy -nosteamcontroller -nohltv -particles 1 -precachefontchars -console -no_texture_stream +mat_phong 0 +mat_specular 0 +tf_time_loading_item_panels 0.1`

**Comment by flightlessmango** [comment]
And when you use mangohud as well?

**Comment by supervitu64** [comment]
only when i put `mangohud %command%` it does not work

**Comment by flightlessmango** [comment]
What I'm trying to see is if you're incorrectly adding mangohud and gamemode to the launch options.
There should only be one `%command%`, so for example `gamemoderun mangohud %command%` is correct usage

**Comment by supervitu64** [comment]
oooooohhh

**Comment by flightlessmango** [comment]
I assume this is resolved
