### ISSUE TITLE
Please change layer name to include architecture to prevent duplicates.

### ISSUE THREAD

**Issue by Venemo** [flightlessmango/MangoHud#1486]
Upon running this Vulkan CTS test: `dEQP-VK.info.instance_layers` the result is:

```
Test case 'dEQP-VK.info.instance_layers'..
  Fail (Duplicate layer: VK_LAYER_MANGOAPP_overlay)
```

To fix this, the 32 and 64 bit versions of mangohud should specify a different layer name.

**Comment by flightlessmango** [comment]
Decided to nuke mangoapp layer 8bd0b63
