### ISSUE TITLE
mangohud not working on source games with -vulkan

### ISSUE THREAD

**Issue by lucasdaweb95** [flightlessmango/MangoHud#1491]
**Do not report issue for old MangoHud versions**

**Describe the bug**
mangohud not working on source games with -vulkan

**List relevant hardware/software information**
- manjaro
- 0.7.2-2 from AUR
- GTX 1050 Ti

**To Reproduce**
run a source game (eg. tf2, portal, hl2) with vulkan, and mangohud %command%

**Expected behavior**
it to open at all

**Screenshots**

**Additional context**
vkBasalt also doesnt work

**Comment by flightlessmango** [comment]
Can you show your full launch option?

**Comment by lucasdaweb95** [comment]
`-gamepadui -vulkan -freq 60 mangohud %command%`
on portal 1

**Comment by 17314642** [comment]
@lucasdaweb95 this is wrong usage.

`mangohud %command% -gamepadui -vulkan -freq 60` this is the correct one
