### ISSUE TITLE
sed: can't read /home/user/.local/share/vulkan/implicit_layer.d/mangohud32.json and mangohud64.json

### ISSUE THREAD

**Issue by williamroge** [flightlessmango/MangoHud#15]
when I run the ./build.sh install errors out with:
sed: can't read /home/user/.local/share/vulkan/implicit_layer.d/mangohud32.json: No such file or directory
sed: can't read /home/user/.local/share/vulkan/implicit_layer.d/mangohud64.json: No such file or directory

*I replaced my home directory name with user.

**Comment by flightlessmango** [comment]
A quick fix would be to install the release first, then you should be able to build

**Comment by telans** [comment]
Are there any errors in ninja or meson? I don't have a catch for exiting, it just continues to the end (sed) and errors if the files don't exist (aren't built/copied)

**Comment by williamroge** [comment]
Well I run Zorin 15.1, someone else was having problems too, compiling and installing via meson and ninja didn't have any errors (other than dependencies which I installed), when manually using LD_PRELOAD=path to mangohud.so, I get segmentation fault error

**Comment by flightlessmango** [comment]
have you tried using the release package?

**Comment by williamroge** [comment]
Hmm.. I tried using the release build, nothing, before I tried this I wasn't even able to use mesa's default  vulkan hud, though vulkan is installed and working.

**Comment by guihkx** [comment]
@williamroge 

Can you replacing the following libraries in your `~/.local/share/MangoHud/`:

[mangohud-lts.zip](https://github.com/flightlessmango/MangoHud/files/4168378/mangohud-lts.zip)

**Comment by williamroge** [comment]
I missed this error, though ninja didn't complain, I don't have the vulkan headers installed (trying to figure out how to get them vulkan sdk maybe?)

meson.build:109:0: ERROR: Include dir modules/Vulkan-Headers/include does not exist.

**Comment by flightlessmango** [comment]
run `git submodule update --init --depth 50` in the mangohud cloned folder

**Comment by williamroge** [comment]
YOUR AWESOME THANKS ALL FOR THE HELP!
