### ISSUE TITLE
NVidia is not detected on Wayland, works on X11

### ISSUE THREAD

**Issue by QkiZMR** [flightlessmango/MangoHud#1506]
**Do not report issue for old MangoHud versions**

**Describe the bug**
Mangohud displays an error on startup when I'm using Wayland. 

```
XNVCtrl didn't find the correct display
```

Everything is ok when I'm working with X11.

**List relevant hardware/software information**
- Linux Distribution: Ubuntu 24.10
- MangoHud version: v0.7.1
- GPU: NVIDIA GeForce RTX 4060 Laptop GPU

**To Reproduce**
1. Start user session with Wayland.
2. Run `mangohud vkcube`.
3. Error `XNVCtrl didn't find the correct display` will appear.

**Expected behavior**
I'm expecting that Mangohud works the same as on X11. 

**Screenshots**
Wayland
![wayland](https://github.com/user-attachments/assets/7974cded-7309-4862-939b-4a88a963773a)
X11
![x11](https://github.com/user-attachments/assets/0e5e7383-963d-42c9-82e2-f37f06b4a585)

**Additional context**

**Comment by flightlessmango** [comment]
This is expected as the Ubuntu package comes from Debian which follows the DFSG guidelines.
As such it excludes NVML which is required on wayland to get NVIDIA info

**Comment by QkiZMR** [comment]
Its there any workaround for this?

**Comment by 17314642** [comment]
The workaround for this is rebuilding a package yourself or using flatpak

**Comment by 17314642** [comment]
You can do it like this:

1) add source code repository (https://askubuntu.com/a/1512043)
2) install packages for building packages: `apt install build-essential pbuilder`
3) download source for mangohud: `apt update && apt source mangohud`
4) download mangohud build dependencies: `apt build-dep mangohud`
5) enable nvml support: `cd mangohud-0.6.9.1 && nano debian/rules` 
6) build the package: `debuild -us -uc -b`
7) install custom mangohud: `cd ../ && apt install ./mangohud_0.6.9.1-2build1_amd64.deb`

**Comment by QkiZMR** [comment]
Thanks for the instructions. I successfully compiled and installed the fixed Mangohud package. One important thing to install before compiling: `sudo apt install libnvidia-ml-dev`.
