### ISSUE TITLE
GPU informations are just not showing (AMD GPU)

### ISSUE THREAD

**Issue by RalL64** [flightlessmango/MangoHud#1509]
**Do not report issue for old MangoHud versions**

**Describe the bug**
Any GPU information (AMD GPU) not showing, but other informations like CPU, RAM, CPU temps, frametime and etcetera, are normally showing.

**List relevant hardware/software information**
- Arch Linux with CachyOS kernel
- MangoHud version: v0.7.2-126-ge8f8406
- RX 6600 desktop

**To Reproduce**
1. Just set any GPU information to show.
2. Open the game or VkCube.

**Expected behavior**
See the GPU infos.

**Screenshots**
![Screenshot From 2024-12-22 22-08-42](https://github.com/user-attachments/assets/610aa458-a464-411e-b165-0c83c4513f6c)

**Additional context**
The issue happened out of nowhere, started the PC on the morning and it was just not showing GPU infos, other applications like LACT show all the informations normally.

**Comment by 17314642** [comment]
Launch mangohud with MANGOHUD_LOG_LEVEL=debug and send the output

**Comment by 17314642** [comment]
And check if you have `pci_dev` or `gpu_list` in your config and try to remove those.

**Comment by RalL64** [comment]
Solved after removing `pci_dev` from the mangohud config file generated by Goverlay. Thanks mate.

**Comment by flightlessmango** [comment]
@RalL64 I'm still interested why `pci_dev` stopped working.
Logs would be helpful

**Comment by 17314642** [comment]
@RalL64 how did your `pci_dev` setting look like?

**Comment by DonKatsu** [comment]
Not seeing GPU information as well with `pci_dev` set. Removing it from the conf shows GPU information again.
The only GPU in this system is a 6700XT.
No difference in mangohud log output besides pci_dev not being present in the parameter section of the latter.
Logs: [pci_dev set.txt](https://github.com/user-attachments/files/18269860/pci_dev.set.txt) [pci_dev unset.txt](https://github.com/user-attachments/files/18269861/pci_dev.unset.txt)

**Comment by 17314642** [comment]
@DonKatsu i sent patch fixing this. https://github.com/flightlessmango/MangoHud/pull/1515
