### ISSUE TITLE
Mangohud vkcube not open

### ISSUE THREAD

**Issue by cezaryn13** [flightlessmango/MangoHud#1510]
Hi, I installed mangohud via archlinux
and I tried to open vkcube, and from the following message.

env: 'vkcube': No such file or directory

how do I solve this.

**Comment by 17314642** [comment]
vkcube is unrelated to mangohud.

do `pacman -S vulkan-tools` to install vkcube

**Comment by gort818** [comment]
Do you have vkcube installed? On Arch it is included in the vulkan-tools package

**Comment by cezaryn13** [comment]
Thanks I work here
