### ISSUE TITLE
Toggle portion of hud

### ISSUE THREAD

**Issue by RickAndTired** [flightlessmango/MangoHud#155]
Suggestion:
Have an option to toggle a portion of the hud

Example:
Hotkey A will toggle `Hud`
Hotkey B will toggle `Time`
Hotkey C will toggle `Crosshair`
Hotkey D will toggle `Everything except FPS`

**Comment by flightlessmango** [comment]
I would encourage you to write a bash script to achieve this. Also crosshair is gone in the next release
