### ISSUE TITLE
Install for Solus OS

### ISSUE THREAD

**Issue by DrunkenAlcoholic** [flightlessmango/MangoHud#157]
Can'nt get this built and installed on Solus OS

`
drunkenalcoholic@thepub ~/Gits $ cd MangoHud/
drunkenalcoholic@thepub ~/Gits/MangoHud $ ./build.sh build
 Checking Dependencies
drunkenalcoholic@thepub ~/Gits/MangoHud $ ./build.sh package
 Checking Dependencies
drunkenalcoholic@thepub ~/Gits/MangoHud $ ./build.sh install
mkdir: created directory '/home/drunkenalcoholic/.config/MangoHud'
Password: 
/usr/bin/install: creating directory '/usr/lib/mangohud'
/usr/bin/install: creating directory '/usr/lib/mangohud/lib32'
/usr/bin/install: cannot stat './build/release/usr/lib/mangohud/lib32/libMangoHud.so': No such file or directory
drunkenalcoholic@thepub ~/Gits/MangoHud $ `
`

**Comment by flightlessmango** [comment]
You don't haft to build, you can use the pre-package binaries [MangoHud-v0.3.5.tar.gz](https://github.com/flightlessmango/MangoHud/releases/download/v0.3.5/MangoHud-v0.3.5.tar.gz)

**Comment by DrunkenAlcoholic** [comment]
yes I ended up installing from pre-packaged binaries, have you had any reports of it not working on Arma 3? I tested on Arma 3 and it showed during the intro then went away, this is the steam launch options I used

> mangohud gamemoderun RADV_PERFTEST=aco  -noLauncher -noSplash -mod=contact

**Comment by flightlessmango** [comment]
`RADV_PERFTEST=aco mangohud gamemoderun %command% -noLauncher -noSplash -mod=contact`
You want to write it like this, but that shouldn't help mangohud show any better, you could try `MANGOHUD_DLSYM=1`

`MANGOHUD_DLSYM=1 RADV_PERFTEST=aco mangohud gamemoderun %command% -noLauncher -noSplash -mod=contact`

**Comment by DrunkenAlcoholic** [comment]
That load ordered fixed the issue of the hud disappearing in Arma 3, Thank you. Also I just wanted to commend you on awesome job you are doing with this project and the help you give people with fast reply's, This project definitely needs to reach the masses and aknowledge the great job you are doing.
