### ISSUE TITLE
"Logging" label position needs to be based on the hud position

### ISSUE THREAD

**Issue by terencode** [flightlessmango/MangoHud#16]
Currently, the label seems to be hardcoded to be at the top right. However, if you move the hud with `MANGOHUD_CONFIG` to the top right, it will mask the label.

A solution is to move the label at the opposite of where the hud is:
- If the hud is top left, display it top right and vice-versa.
- If the hud is bottom left , display it bottom right and vice-versa.

**Comment by flightlessmango** [comment]
This is no longer an issues since it has been reworked, there is a red dot at the top right of the hud to indicate when logging is running instead
