### ISSUE TITLE
AMDGPU - Memory and Junction Temperature

### ISSUE THREAD

**Issue by EduFrazao** [flightlessmango/MangoHud#163]
Its possible to display the GPU Junction and Memory temperature?
This information is acessible and lm_sensors is able to display it, like:

amdgpu-pci-0a00
Adapter: PCI adapter
vddgfx:       +0.72 V  
fan1:           0 RPM  (min =    0 RPM, max = 3500 RPM)
edge:         +44.0°C  (crit = +118.0°C, hyst = -273.1°C)
                       (emerg = +99.0°C)
junction:     +44.0°C  (crit = +99.0°C, hyst = -273.1°C)
                       (emerg = +99.0°C)
mem:          +44.0°C  (crit = +99.0°C, hyst = -273.1°C)
                       (emerg = +99.0°C)
power1:       12.00 W  (cap = 220.00 W)

**Comment by flightlessmango** [comment]
I don't think this exists for Nvidia and therefor I would prefer not adding it

**Comment by AdelKS** [comment]
Why not though ? A quick look at MangoHud's code shows that it's not GPU agnostic: there is different pieces of code for each GPU vendor. Starting from that, only touching AMD's code to add it doesn't seem to drift apart from your code's philosophy ?

If you don't want to spend time on that that's perfectly understandable. Would you be okay with a PR though ?

**Comment by flightlessmango** [comment]
It's not so much about the code itself. If you activate a param on nvidia, it should also work on amd and vice versa

**Comment by AdelKS** [comment]
As I understand it's a matter of taste then, which I respect. 

Do keep in mind that your Hud is awesome and can be even more with those temperatures added : I think that gamers on Linux use (or will end up using) more AMD GPUs than Nvidia's (because open source driver). And those with navi ones (including me) would definitely love to be able to see those temperatures using your Hud. So please give it some second thoughts. Even if it is not useful for you, it is for us, and we are many.

Thanks!

**Comment by flightlessmango** [comment]
Let's say we add Memory and Junction temp, how would it be displayed on the hud exactly?

**Comment by AdelKS** [comment]
I would go for a three column display of GPU information like this: 

![MangoHud suggestion](https://user-images.githubusercontent.com/13605217/87030759-5de0ba80-c1e2-11ea-9db6-9f27bb5f54ca.png)

Now that I think of it, the "C" of Celsius could use some downsizing, or maybe get entirely removed. Or maybe you give the option of Fahrenheit ? 

I have a GIMP template with everything separated in layers if you want to play around with things. I attached it.
[MangoHud suggestion.zip](https://github.com/flightlessmango/MangoHud/files/4896238/MangoHud.suggestion.zip)

**Comment by AdelKS** [comment]
Any feedback on the idea ? :D

**Comment by flightlessmango** [comment]
This is a bit more complicated when it comes to writing the code, it looks pretty good in your suggestion but I don't think it will/can pan out like that

**Comment by AdelKS** [comment]
Does your answer mean you are willing to try to implement it ? 

If not, are you willing to accept a PR that adds it ? I am kinda hyped to try to implement it, I will learn quite a few stuff in the process, I would probably need your help explaining parts of the code: do you have a doc of your code ? Or something that explains the overall structure of it ? I suppose the main files that would need work are `overlay.h` and `overlay.cpp`.

Actually a middle ground can also be done, I do a WIP PR and we discuss there and I get your feedback, maybe you do some mods etc... What do you think ?

Anyway, I am willing to get my hands dirty.

**Comment by flightlessmango** [comment]
Yes a PR sounds like a good idea :ok_hand:

**Comment by KermitTheFrogerino** [comment]
@flightlessmango Or just stack the columns like the cpu^n layout:
![mangohud](https://user-images.githubusercontent.com/35975961/87932436-cdc92d80-ca8b-11ea-8ec2-bc1bfbe66979.png)

**Comment by AdelKS** [comment]
Yea that would be the easier first version. Then the layout change. The three columns are better because they don't make the HUD any bigger even with two additional temp reads. I haven't taken the time to start working on it yet.

**Comment by EduFrazao** [comment]
Hi @AdelKS . Did you make any progress in your research?

**Comment by AdelKS** [comment]
Hello @EduFrazao, this project fell down my priority list unfortunately. I haven't started anything in regards to this. I may pick it up soon since MangoHud is working now on my machine (a `DEVICE_NO_SELECT` issue with Mesa). If you want to pick it up yourself, feel free!

**Comment by EduFrazao** [comment]
@AdelKS unfortunatelly i'm just a regular user. I'm not a C/C++ Developer. But I can try to help with tests, if it helps anyway. I also had the "DEVICE_NO_SELECT" issue with mesa.
I hope that Memory and Junction temperature become supported in the future. I think that it is very important.
Thanks for your answer.
