### ISSUE TITLE
integer overflow for elapsedLog in logging.h

### ISSUE THREAD

**Issue by jazztickets** [flightlessmango/MangoHud#165]
in logging.h, elapsedLog should be changed to a 64 bit int. After about 21k lines of logging, it overflows:
> 21463: 98.9816,18,95,2147243512  
> 21464: 100.587,17,96,2147343567  
> 21465: 99.9494,17,96,2147443622  
> 21466: 98.6182,17,96,-2147423617  
> 21467: 98.595,17,96,-2147323561  
> 21468: 98.4237,17,96,-2147223503  
> 21469: 99.3266,16,90,-2147123445  
> 21470: 97.088,16,90,-2147023386

**Comment by flightlessmango** [comment]
fixed here 2e1861ea09196e35002165f46f52627c126df0eb
