### ISSUE TITLE
v0.3.5 OpenGL issues

### ISSUE THREAD

**Issue by HadetTheUndying** [flightlessmango/MangoHud#167]
So I can't seem to get the HUD to Overlay on any OpenGL games. It overlays fine in `glxgears` however which is really confusing me. It will not overlay in OpenArena, System Shock 2, Turok, or ioquake3.

It works fine with Vulkan games through steam too, but none of my OpenGL games on Steam will render the HUD

**Comment by flightlessmango** [comment]
are you using `mangohud` or `MANGOHUD=1`? have you tried `MANGOHUD_DLSYM=1` ?

**Comment by HadetTheUndying** [comment]
I'm using `mangohud` to launch locally compiled sourceports from my CLI. and `mangohud %command%` in Steam. Turok is now rendering the HUD correctly, System Shock 2 still fails to do so. I think maybe it has to do with some of the games starting as a small window and resizing themself?

running `mangohud` on tes3mp or openmw compiled locally for example is producing no HUD.

**Comment by HadetTheUndying** [comment]
To clarify as well, some of these applications were working fine with `mangohud /path/to/application/` in  v0.2.0 which is why I expected different behavior when updating to v0.3.5

**Comment by flightlessmango** [comment]
also to making sure we're on the same page, this is how you would use the dlsym env var `MANGOHUD_DLSYM=1 mangohud %command%`

**Comment by HadetTheUndying** [comment]
Correct. Still no dice on SystemShock 2 on steam. ioquake3 or openmw. Thanks for clarifying though, was wondering if i was doing it right. Sorry for the slow response.

**Comment by pholostan** [comment]
I had the same problem, stopped working for me in ogl games when I updated to 0.3.5

`MANGOHUD_DLSYM=1` made it work again for me in BattleTech (GOG version), yay!

Steam games seems to be hit or miss, No Oxygen Included seems to work but Borderlands 2 doesn't seem to work, dlsym set or not.

**Comment by rezzafr33** [comment]
For me The King of Fighter XIV Steam doesn't work with or without MANGOHUD_DLSYM=1, mangohud 0.3.5 installed from AUR.

**Comment by dpanter** [comment]
Confirmed problem with both x86 and x86_64 versions of 3dSenDemo beta 8 _(the 3D NES emulator, Unity engine)_
0.3.1 works for both versions.
0.3.5 does not work with any version. Tested `MANGOHUD_DLSYM=1` also.

0.3.1 and 0.3.5 - both work in glxgears and vkcube. 
0.3.5 - Horizon Chase Turbo (OpenGL) on Steam, with Steam Overlay enabled - MangoHud works.

0.3.5 - gzdoom OpenGL - does not work, even with `MANGOHUD_DLSYM=1`
0.3.5 - gzdoom Vulkan - works.

**Comment by rtentser** [comment]
Doesn't work with Deponia 3 (GOG version). Works with MANGOHUD_DLSYM=1.

**Comment by jackun** [comment]
gzdoom OpenGL works for me

**Comment by dpanter** [comment]
> gzdoom OpenGL works for me

With 0.3.5? If you could add system specs, it might help pinpoint the issue.
And after saying that, I just realized I haven't added system specs myself... oof.

My specs:
Siduction (Debian sid based)
KDE Plasma 5.17.5
5.6.15-towo.1-siduction-amd64 LLVM 10.0.0
Radeon VII
amdgpu 19.1.0-1
mesa-git 20.2.0~git20200530-1

**Comment by jackun** [comment]
Well...
```
System:    Host: fractal-d Kernel: 5.6.15-zen2-1-zen x86_64 bits: 64 compiler: gcc v: 10.1.0 Desktop: KDE Plasma 5.18.5 
           Distro: Arch Linux 
Machine:   Type: Desktop System: Gigabyte product: X570 AORUS ELITE v: -CF serial: <superuser/root required> 
           Mobo: Gigabyte model: X570 AORUS ELITE v: x.x serial: <superuser/root required> UEFI: American Megatrends v: F12f 
           date: 03/06/2020 
CPU:       Topology: 6-Core model: AMD Ryzen 5 3600 bits: 64 type: MT MCP arch: Zen 2 L2 cache: 3072 KiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm bogomips: 86241 
           Speed: 2563 MHz min/max: 2200/3600 MHz Core speeds (MHz): 1: 2563 2: 2040 3: 2505 4: 2173 5: 2538 6: 3866 7: 3671 
           8: 2380 9: 2993 10: 2075 11: 2131 12: 2386 
Graphics:  Device-1: Advanced Micro Devices [AMD/ATI] Vega 10 XL/XT [Radeon RX Vega 56/64] vendor: Gigabyte driver: amdgpu 
           v: kernel bus ID: 0a:00.0 
           Display: x11 server: X.Org 1.20.8 driver: amdgpu resolution: 2560x1440 
           OpenGL: renderer: Radeon RX Vega (VEGA10 DRM 3.36.0 5.6.15-zen2-1-zen LLVM 10.0.0) 
           v: 4.6 Mesa 20.2.0-devel (git-7e26a02e5f) direct render: Yes 

```

**Comment by HadetTheUndying** [comment]
Sure I'll post my Specs, but this appears to be a software issue as it was working properly in the 0.2.0 release.:
```CoreCtrl v1.0.8

==== Software ====
Kernel version: 5.6.16_1 (hadet@endurance) (gcc version 9.3.0 (GCC)) #1 SMP Thu Jun 4 18:28:01 UTC 2020
Mesa version: 20.0.7

==== [GPU 0] ====
BIOS version: 115-D050PIL-100
Device: Vega 10 XL/XT
Device ID: 687F
Device model ID: 0555
Driver: amdgpu
Memory: 8192MB
OpenGL version (compat): 4.6
OpenGL version (core): 4.6
PCI Slot: 0000:30:00.0
Revision: C3
Vendor: Advanced Micro Devices, Inc.
Vendor ID: 1002
Vendor model ID: 1043
Vulkan API version: 1.2.128

==== AMD Ryzen 7 2700X Eight-Core Processor [CPU 0] ====
Architecture: x86_64
Bogomips: 7399.33
Bugs: sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass
Byte order: Little Endian
CPU Family: 23
Cores: 8
Execution units: 16
Flags: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb hw_pstate sme ssbd sev ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 xsaves clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif overflow_recov succor smca
L1 cache (data): 256 KiB
L1 cache (instructions): 512 KiB
L2 cache: 4 MiB
L3 cache: 512 KB
Microcode version: 0x800820d
Model: 8
Model Name: AMD Ryzen 7 2700X Eight-Core Processor
Operation modes: 32-bit, 64-bit
Stepping: 2
Vendor ID: AuthenticAMD
Virtualization: AMD-V
```

**Comment by dpanter** [comment]
Updated results with 0.4.0, using `mangohud foo`


Both x86 and x86_64 versions of 3dSenDemo beta 10 _(the 3D NES emulator, Unity engine, OpenGL)_
Both versions - work, but needs `MANGOHUD_DLSYM=1`

glxgears and vkcube - both work.

Other games:
Horizon Chase Turbo (OpenGL) on Steam, with Steam Overlay enabled - works.
> 
gzdoom OpenGL - works, but needs `MANGOHUD_DLSYM=1`
gzdoom Vulkan - works.

**Comment by HadetTheUndying** [comment]
issues are fixed on my end with `MANGOHUD_DLSYM=1 mangohud`
