### ISSUE TITLE
Media Player features works erratically

### ISSUE THREAD

**Issue by hjri** [flightlessmango/MangoHud#168]
* Music info from Cantata didn't show up until i launched VLC and played some song with track info, it would use track info from Cantata and play/pause info from VLC
* Doesn't show track information if song is already is playing, even on track change, needs pause+unpause
* Doesn't show track info at all if paused? Makes sense to show "(paused)" there?
* Documentation calls it "Show music playing in SpotifyⓇ", no mention of MPRIS(2) or that other players being supported, coupled with issues above and log error "Failed to get initial Spotify metadata: The name org.mpris.MediaPlayer2.spotify was not provided by any .service files" it gives off an impression only spotify is supported

**Comment by jackun** [comment]
> only spotify is supported

You list these "issues" and then this :D

**Comment by hjri** [comment]
i mean i was about to make an angery comment how spotify is supported but FOSS players that aren't dependent on cloud servers aren't supported but it turned out to be not quite the case

**Comment by jackun** [comment]
Hmm, just having the mpris player "name" as a param might be fastest to add random "main" player support.

**Comment by jackun** [comment]
Check out  `develop` branch
