### ISSUE TITLE
FFXIV launcher not launching the game

### ISSUE THREAD

**Issue by jefferyrlc** [flightlessmango/MangoHud#169]
For whatever reason, trying to use MangoHud either by mangohud or MANGOHUD=1 for FFXIV causes the updater to fail and not launch the game, even if the game is already up to date. Using various builds of Proton, purging the game folder and the prefix folder doesn't rectify the issue.

Software
MangoHud 0.3.5.r7.gbeee2b0-1 via chaotic-aur repository.
Manjaro 20.0-1
Mesa 20.0.6-2

Hardware
AMD Ryzen 5 3600
16 GB Ram
AMD RX 570 8GB

Log file
https://drive.google.com/open?id=1lceNx6QLhpO_JVX3BPVp6vaZuCJk7YHh

**Comment by jackun** [comment]
Can you try this [mangohud-git.tar.gz](https://github.com/flightlessmango/MangoHud/files/4617518/mangohud-git.tar.gz)

**Comment by jefferyrlc** [comment]
![Screenshot_20200512_140722](https://user-images.githubusercontent.com/18264856/81729797-92422f80-945a-11ea-9ff7-90079829e6c9.png)
https://drive.google.com/open?id=1ibEh184BfMoM9rLNZHUAZgTIBdlQIx0K
Installed your packages and that's what I got

**Comment by jackun** [comment]
Yeah, it had a dum-dum error. Try this one 
[mangohud-git-r30.tar.gz](https://github.com/flightlessmango/MangoHud/files/4617749/mangohud-git-r30.tar.gz). But could be something else wrong there.

**Comment by jefferyrlc** [comment]
![Screenshot_20200512_145942](https://user-images.githubusercontent.com/18264856/81734303-4b0b6d00-9461-11ea-8f2c-2b361213c899.png)
