### ISSUE TITLE
Feature request: show current vsync option

### ISSUE THREAD

**Issue by guillaumezin** [flightlessmango/MangoHud#171]
Hello,

Thank you for this very convenient software. I use it to force vulkan mailbox vsync on Linux port of shadow of tomb raider. It would be handy if the HUD could show current vsync option, without changing it, to understand what's going on, and maybe open a support ticket with screen captures, to send to Feral or Nvidia support.

**Comment by flightlessmango** [comment]
All vsync options aren't supported on all devices/drivers, said vsync option might not be working as intended. so asserting that it is a specific vsync might be misleading

more information about vulkan vsync support https://vulkan.gpuinfo.org/listsurfacepresentmodes.php?platform=linux

**Comment by guillaumezin** [comment]
I'm not sure to understand your point. The idea would be te read the current presentation mode, for debug purpose, not all the supported presentation modes. But I'm not sure it is feasible, I didn't see current presentation mode readback function in documentation, but I had only a brief look.

**Comment by flightlessmango** [comment]
It's possible to say what presentation mode it is, but since the support is so spotty it's impossible to know if it's actually that or not. Possibly giving misleading information
