### ISSUE TITLE
Feature request: show current power draw in Watts

### ISSUE THREAD

**Issue by xcom169** [flightlessmango/MangoHud#172]
Can MangoHud show the current power draw for the GPU in Watts?

**Comment by flightlessmango** [comment]
This has been added in develop

**Comment by longusnickus** [comment]
whats the variable for power consumption?
i dont wanna use "full"

**Comment by flightlessmango** [comment]
it's `gpu_power` and it currently requires `gpu_core_clock` as well

**Comment by longusnickus** [comment]
I could have guessed that
thx

**Comment by xcom169** [comment]
> This has been added in develop

Thanks!
