### ISSUE TITLE
Feature request: Multiple FPS limits

### ISSUE THREAD

**Issue by jgabor** [flightlessmango/MangoHud#173]
When I was still on Windows, and after Nvidia added an FPS limiter to their drivers, I used to cap my FPS to 97 (100 Hz G-Sync monitor) in Nvidia's drivers and then have another cap in MSI Afterburner set to 30 fps that I could toggle on and off. 

I did this so that when I got distracted or had to leave the game for a moment, I could enable the FPS limit in MSI Afterburner, limiting my power draw and allowing the fans to throttle down to minimize noise when I'm not wearing my headset. It also meant I could avoid quitting the game and the hassle of logging back in again (e.g. most MMO's today), often with 2FA with my phone of course left in the other room...

Perhaps having something like `fps_limit` accept an array of values, a hotkey that steps through them, and the current fps_limit displayed in the overlay? I'm assuming the fps_limit can be changed on the fly, which might not be the case like with Nvidia's fps limiter that can only be set before you launch the game.

**Comment by flightlessmango** [comment]
Yes you can change the fps_limit on the fly, it will take effect if you change it in the config while running. This is something that could be implemented, but could also easily be achieved with a simple bash script. Although toggle limit on/off/secondary value sounds a bit interesting

**Comment by jgabor** [comment]
Ah, excellent! That would definitely be enough to solve my needs... I'll do that, thanks for the tip!

I think there might be other use cases where it could become useful, like troubleshooting for bottlenecks, or just trying to find the sweet spot where frame timings are stable at the highest possible fps. But... I'll leave that for you to decide if worth implementing!
