### ISSUE TITLE
AMD Ryzen 3 not showing GPU usage

### ISSUE THREAD

**Issue by nortuzar** [flightlessmango/MangoHud#174]
Hi, I built MangoHud using the github instructions. Running Ryzen 3 3200g on pop_os 20.4. Without GPU, just using internal GPU
Was able to set up and run it on steam using mangohud %command%
![image](https://user-images.githubusercontent.com/55258023/81962836-533ee600-95e2-11ea-945a-5d77f1e715a8.png)

But GPU usage always at 0% and CPU/GPU temp are always the same? could this be right?
Any advice?
Thanks for the great app

**Comment by flightlessmango** [comment]
About the GPU load, as far as I know it's just not supported on these iGPUs. There is nothing we can do on our end sadly.
For the temperatures, Could it be correct? Yes. You can check with the `sensors` command if they are giving different cpu/gpu temp values and if they differ from mangohud

**Comment by jackun** [comment]
Thought threre were already 101 issues about this, but it seems like an `amdgpu` issue. It just gives a read error when reading `gpu_busy_percent` file.

**Comment by nortuzar** [comment]
Sorry about that. True that cant read the file `gpu_busy_percent`
Should I leave this open for a future possible fix or closed?

**Comment by flightlessmango** [comment]
This can't be fixed by us, you would need to poke someone else
