### ISSUE TITLE
time reported by vulkan is different than opengl

### ISSUE THREAD

**Issue by LizziAS** [flightlessmango/MangoHud#175]
Posted about this issue with steam on github, with manjaro gaming help forums, with eso forums, with esoui for the issue with libdebuglogger... Someone has heard of this issue or knows what is causing it?

Vulkan in UTC rather than local time?
ESO - works great except for whn i used an addon called libdebuglogger
Steam AppID of the game:i dont know that 306130?

System Information
sudo inxi -Fxzmc0

System: Host: manjaroed Kernel: 5.6.13-1-MANJARO x86_64 bits: 64 compiler: gcc v: 10.1.0 Desktop: MATE 1.24.0
Distro: Manjaro Linux
Machine: Type: Desktop System: Gigabyte product: AB350M-DS3H v: N/A serial: N/A
Mobo: Gigabyte model: AB350M-DS3H-CF v: x.x serial: N/A UEFI [Legacy]: American Megatrends v: F50a date: 11/27/2019
Battery: Device-1: hidpp_battery_0 model: Logitech M570 charge: 90% status: Discharging
Device-2: hidpp_battery_1 model: Logitech Wireless Keyboard K360 charge: 55% (should be ignored)
status: Discharging
Memory: RAM: total: 15.65 GiB used: 2.92 GiB (18.7%)
Array-1: capacity: 128 GiB slots: 4 EC: None max module size: 32 GiB note: est.
Device-1: DIMM 0 size: No Module Installed
Device-2: DIMM 1 size: 8 GiB speed: 3000 MT/s type: DDR4
Device-3: DIMM 0 size: No Module Installed
Device-4: DIMM 1 size: 8 GiB speed: 3000 MT/s type: DDR4
CPU: Topology: Quad Core model: AMD Ryzen 5 2400G with Radeon Vega Graphics bits: 64 type: MT MCP arch: Zen
L2 cache: 2048 KiB
flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm bogomips: 57513
Speed: 1421 MHz min/max: 1600/3600 MHz Core speeds (MHz): 1: 1420 2: 1420 3: 1460 4: 1523 5: 1592 6: 1405 7: 1486
8: 1426
Graphics: Device-1: Advanced Micro Devices [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] vendor: ASRock
driver: amdgpu v: kernel bus ID: 01:00.0
Display: server: X.Org 1.20.8 driver: amdgpu,ati unloaded: modesetting resolution: 1920x1080~60Hz
OpenGL: renderer: Radeon RX 570 Series (POLARIS10 DRM 3.36.0 5.6.13-1-MANJARO LLVM 10.0.0) v: 4.6 Mesa 20.0.6
direct render: Yes
Audio: Device-1: AMD Ellesmere HDMI Audio [Radeon RX 470/480 / 570/580/590] vendor: ASRock driver: snd_hda_intel v: kernel
bus ID: 01:00.1
Device-2: Advanced Micro Devices [AMD] Family 17h HD Audio vendor: Gigabyte driver: snd_hda_intel v: kernel
bus ID: 0a:00.6
Sound Server: ALSA v: k5.6.13-1-MANJARO
Network: Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet vendor: Gigabyte driver: r8169 v: kernel
port: e000 bus ID: 05:00.0
IF: enp5s0 state: up speed: 1000 Mbps duplex: full mac:
Device-2: Intel Wi-Fi 6 AX200 driver: iwlwifi v: kernel port: e000 bus ID: 08:00.0
IF: wlp8s0 state: down mac:
Drives: Local Storage: total: 1.37 TiB used: 362.41 GiB (25.9%)
ID-1: /dev/nvme0n1 model: Sabrent Rocket Q size: 931.51 GiB
ID-2: /dev/sda vendor: SanDisk model: Ultra II 500GB size: 465.76 GiB
ID-3: /dev/sdb type: USB vendor: Generic model: Flash Disk size: 1.92 GiB
Partition: ID-1: / size: 48.97 GiB used: 26.20 GiB (53.5%) fs: ext4 dev: /dev/nvme0n1p3
ID-2: /boot size: 968.3 MiB used: 186.0 MiB (19.2%) fs: ext4 dev: /dev/nvme0n1p2
ID-3: /home size: 865.62 GiB used: 208.49 GiB (24.1%) fs: ext4 dev: /dev/nvme0n1p4
Sensors: System Temperatures: cpu: 43.0 C mobo: N/A gpu: amdgpu temp: 35 C
Fan Speeds (RPM): N/A gpu: amdgpu fan: 1495
Info: Processes: 331 Uptime: 8m Init: systemd Compilers: gcc: 10.1.0 clang: 10.0.0 Shell: bash v: 5.0.16 inxi: 3.0.37

I confirm:
that I haven't found an existing compatibility report for this game.
The game works.

that I have checked whether there are updates for my system available.
I am up to date with the latest version of the game and with proton and dxvk

Have no idea whgat that is

Symptoms
2 things. When playing with the addon libdebuglogger which is used for many other addons, the time in game shifts from my local system time to UTC

Also when trying to use mangohud Vulkan reports time in utc but opengl reports local system time

https://lh3.googleusercontent.com/UOJaNfyNyTg7ZNlrD6fCxK4kfHnZI5vabkITO2w2UN05zTGVL2NaAgnsppXXpusKfEo-Pwc8RWmt9POfP3CMxSH9IfTP9dUWmxsI0yeXfN4Mom-X3JW7q_Tenzh9fjdljsCdvr5mrg=w2400

https://lh3.googleusercontent.com/a36uOuiIpgi0iS1WHqysA3f9ikTfRh4mvbxnD05Z-yswLXa-08pEVc0uTHnMUuycZrP5OAVuy-8xCRbKlQZb7aT6Ng_S-ZKd9F37yTlhAOr2FgQBj_vrtAklhP4gLVEUvbhUgJpDvA=w2400

Something seems wonky with dxvk i think? but i dont know anyone else having this issue so maybe its something with my system hardware? i have the latest bios and the bios is on the correct local time.

I filed a request for for with libdebuglogger at esoui because something in that causes the in time game to shift from local to utc but it isnt just there. while running mangohud the time in vulkan driver is reported as utc? but in opengl it is local time?

https://www.twitch.tv/videos/620189454

someone even uderstands what is happening here because i do not... i tried to switch my rtc to local time and rebooted but no improvement...

**Comment by flightlessmango** [comment]
I don't see how this is a mangohud issue

**Comment by LizziAS** [comment]
Your program is reporting the wrong time and you dont see how that is a mangohud issue?

Would you please tell me who's issue it is because everyone is passing the buck.  steam play, aka proton says it's not their issue, dxvk says it's not their issue, you dont want to be bothered with it so who do i turn to for help please?

**Comment by jackun** [comment]
Game set locale to "C" what probably gives the UTC timezone. MangoHud has to hack around it an detect correct timezone somehow, probably manually parse `/etc/localtime`

**Comment by LizziAS** [comment]
Thanks for that clue!  I am asking now, where that config is located that set my game locale to C so that i might edit it properly.

**Comment by jackun** [comment]
I don't think there is one but you can try with LANG or LC_ALL like `LANG=en_US.UTF8 %command%` etc but this probably gets reset by game.

**Comment by LizziAS** [comment]
i looked in usersettings text that is in the documents folder but i saw nothing about location except for the server i'm using by default.  Here's a poastebin  https://pastebin.com/mChZH7ig

**Comment by LizziAS** [comment]
also i asked in the forums about how to edit that.  maybe someone knows and will say so?

**Comment by Zamundaaa** [comment]
> Game sets locale to "C" what probably gives the UTC timezone

I don't see how this could be a locale issue with that particular game if vkcube reports a different time than glxgears (have a look at that video on twitch). Those two apps should definitely not set the locale (and show the exact same non-UTC time on my machine).

**Comment by jackun** [comment]
Weird, it's the same timezone for me.

**Comment by Zamundaaa** [comment]
Yeah, that's why I redirected @LizziAS here. I'm pretty sure it has to be an issue with either MangoHUD or one of the libraries it uses, perhaps some unusual locale settings that get interpreted differently by the Vulkan and by the OGL path?

**Comment by jackun** [comment]
Wait, wth. On intel gpu, both are local time, on amdgpu desktop vkcube is UTC, but GTA5 with DXVK has been local time.

**Comment by Zamundaaa** [comment]
Huh, I'm using an AMD GPU (with Intel Vulkan drivers uninstalled) and it's all in local time for me. Just if you're able to use it, my locale:
<details>
<summary>$ locale</summary>
<pre>LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=de_DE.UTF-8
LC_TIME=de_DE.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=de_DE.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=de_DE.UTF-8
LC_NAME=de_DE.UTF-8
LC_ADDRESS=de_DE.UTF-8
LC_TELEPHONE=de_DE.UTF-8
LC_MEASUREMENT=de_DE.UTF-8
LC_IDENTIFICATION=de_DE.UTF-8
LC_ALL=
</pre>
</details>

**Comment by jackun** [comment]
Something sets TZ env
vkcube:
```
Old locale: C
TZ: GMT+0
```

glxgears:
```
Old locale: C
TZ: (null)
```

**Comment by LizziAS** [comment]
so if intel drivers are installed i should uninstall them?

**Comment by jackun** [comment]
No

**Comment by LizziAS** [comment]
Ok well it's almost Sabbath.  Thank you for being willing to look into this.  Happy Sabbath and goodnight!.  See you again after sabbath ends...

**Comment by jackun** [comment]
AMDVLK sets timezone to GMT+0 when vulkan loader just enumerates ICDs.

**Comment by LizziAS** [comment]
is that something i can manually edit if i build amdvlk from the aur?

**Comment by LizziAS** [comment]
That fixed the issue with  mangohub it seems but not with  eso...  no worries... i have mangohi=ub i can use for overlay clock in full screen mode..

**Comment by LizziAS** [comment]
Mango hud will not launch steam now

**Comment by LizziAS** [comment]
downgrading amdvlk to 2020.01.01 was able to launch game with mangohud
