### ISSUE TITLE
Is it possible to use the mangohud outside steam and lutris ?

### ISSUE THREAD

**Issue by ishan9299** [flightlessmango/MangoHud#177]
I am using the GZDoom from flathub I would like to use the mangohud for that game.
I tried the command 
`sudo flatpak override --env=MANGOHUD=1 org.zdoom.GZDoom`
but it doesn't work.

**Comment by flightlessmango** [comment]
Looks like GZDoom is OpenGL, `MANGOHUD=1` only works for vulkan.
You could try `--env=LD_PRELOAD=/usr/lib/mangohud/lib64/libMangoHud.so`, assuming you installed mangohud using the release package

**Comment by witchymary** [comment]
Tried `LD_PRELOAD=/usr/lib/mangohud/lib64/libMangoHud.so gzdoom` and it didn't work, neither does `mangohud gzdoom`. MangoHud just doesn't initialize with gzdoom for some reason.

**Comment by jackun** [comment]
@witchymary try `MANGOHUD_DLSYM=1 mangohud gzdoom`

**Comment by witchymary** [comment]
Oh, I wasn't aware of the new variable. Works as intended now.

**Comment by flightlessmango** [comment]
I don't think this is a mangohud issue, this is more of a "how to use flatpak" question
