### ISSUE TITLE
Usage inside Steam Linux Runtime

### ISSUE THREAD

**Issue by ranisalt** [flightlessmango/MangoHud#18]
I want to use this tool on Rise of the Tomb Raider, but I am on Arch Linux and this game requires some outdated libraries that only still ship on Ubuntu, so I run it through Steam Linux Runtime. I must point that I got to this solution after a month long chat with Feral support where they couldn't provide much help.

So, the SLR overlays the libraries over the host system, and this overlay hides mangohud library and the implicit_layer.d files. Because of that, the HUD is missing when running Vulkan games inside SLR. Is it possible to make the files visible under SLR so I can have the HUD?

**Comment by guihkx** [comment]
I don't own Rise of The Tomb Raider, but I tried running [Volcanoids](https://store.steampowered.com/app/951440/Volcanoids/) and [Unturned](https://store.steampowered.com/app/304930/Unturned/) using the Steam Linux Runtime, with Vulkan enabled (`-force-vulkan`), and MangoHud loaded just fine. Though Unturned crashed whilst loading the game assets, but that's a whole different issue, I guess.

Perhaps you could test it with Unturned as well, just to make sure this isn't somehow specific to ROTTR.

**Comment by jackun** [comment]
@ranisalt what library? I'm running it fine with steam-native.

**Comment by ranisalt** [comment]
> with Vulkan enabled

How can I be sure that these games are running Vulkan? I added `-force-vulkan` to the command line on Steam but it didn't change and I still can not see the mangohud.

**Comment by guihkx** [comment]
Try setting this in the launch options:

`VK_LOADER_DEBUG=all MANGOHUD=1 %command% -force-vulkan &> $HOME/unturned.log`

Then you could search for `vulkan` in `unturned.log`:

```
$ grep vulkan unturned.log
DEBUG: ReadDataFilesInSearchPaths: Searching the following paths for manifest files: /etc/xdg/vulkan/implicit_layer.d:/etc/vulkan/implicit_layer.d:/var/lib/flatpak/exports/share/vulkan/implicit_layer.d:/usr/local/share/vulkan/implicit_layer.d:/usr/share/vulkan/implicit_layer.d
INFO: Found manifest file /home/gui/.local/share/vulkan/implicit_layer.d/mangohud64.json, version "1.0.0"
[...]
```
```

**Comment by ranisalt** [comment]
The log comes empty after playing the entire tutorial.

**Comment by flightlessmango** [comment]
install the vulkan-tools package and run `MANGOHUD=1 vkcube` 
does mangohud show up then?

**Comment by ranisalt** [comment]
@flightlessmango yes, it shows up

**Comment by flightlessmango** [comment]
then it sounds pretty likely that the game is not running vulkan for whatever reason. what game are you trying to use mangohud in?

**Comment by guihkx** [comment]
>The log comes empty after playing the entire tutorial.

That's weird. What distro are you using? Was Steam installed "traditionally" or are you using Snap or Flatpak...? I would perhaps try launching Steam with `STEAM_RUNTIME=1`, if you aren't already.

**Comment by ranisalt** [comment]
@flightlessmango I tried a couple of games through Proton, then Rise of the Tomb Raider and Unturned, as suggested.

@guihkx I installed Steam through the package manager on Arch Linux, and I usually run it through [LSI](https://github.com/solus-project/linux-steam-integration), I didn't try using the Steam runtime as I prefer the native runtime, but I'll try right now.

**Comment by ranisalt** [comment]
Running with `STEAM_RUNTIME=1` does not solve for Unturned at least.

**Comment by guihkx** [comment]
>I usually run it through LSI

Oh, I wasn't aware of that project. The README mentions that while they don't directly modify the Steam installation, they do apply some workarounds. Did you try running Steam without such workarounds?

I find this kinda weird, because I'm running the regular `steam` package on Arch just like you are, and MangoHud loads just fine with the Steam Linux Runtime enabled, so I'm not really sure what it could be.

**Comment by ranisalt** [comment]
I nuked my Steam install with `steam --reset`, removed `steam-native-runtime` and `linux-steam-integration` and now the HUD works outsite the Steam Linux Runtime.

Just so we are in the same page, Steam Linux Runtime is not the STEAM_RUNTIME=1 thing, it's enabled by ticking "Force the use of a specific Steam Play compatibility tool" (the same used to enable Proton) and selecting it, and it containerizes the game to isolate the filesystem.

**Comment by guihkx** [comment]
Ah yes, absolutely. Check out this video if you can and see if I'm doing something different than you:

https://youtu.be/2cuml-tc2Po

In the video you can see I had to actually kill the game because it crashes in the loading page, but as you can see MangoHud loads just fine.

**Comment by ghtux** [comment]
I run steam directly with mangohud enabled. Did you try that? No need to set parameters for each game then.
