### ISSUE TITLE
Optional installation in user space

### ISSUE THREAD

**Issue by 0Xellos** [flightlessmango/MangoHud#180]
The install script always requires root access, but it shouldn't have to. I just installed it locally (Ubuntu 19.10).
- Pip can be installed locally and most dependencies exist as pip packages. Common system packages like gcc should be already installed.
- Instead of installing to /usr/, a better practice is setting a prefix variable. Without root permissions, the user can be offered the option to install to $HOME/.local instead, and setting the prefix manually as an env variable would simply override it.

Installing all possible dependencies through pip also decreases the chance that something breaks if the only package version offered by the package manager is incompatible. Versions can be frozen and updated.

The main problem is that I don't know how to connect games naturally with it like by just setting MANGOHUD=1.

**Comment by flightlessmango** [comment]
When we introduced OpenGL support we concluded that it would be most convenient for everyone to install in /usr. One of the reason being that we started shipping a shell script. Another part is that we're trying to cover a wide range of Distros and versions, not just Ubuntu 19.10

**Comment by 0Xellos** [comment]
I don't see how either is a counterpoint to my suggestion. Shipping the shell script is natural, I'm only talking about small changes to it. I only provided my OS version as an additional detail and an optional installation prefix is more distro-independent, not less.

Also I didn't notice you wanted it to be distro-independent and version-independent. You have casework for specific distros, don't distinguish between versions so a changed name of some dependency could break the installation and don't mention distro-independent build dependencies, forcing anyone on an unsupported distro to go through your shell script to figure out what they need to do.

I realise that's not the point of the library, but this isn't a random idea - I had to remove python3-pip, install pip from Anaconda repositories and then install mako through it to avoid some import error, obviously caused by Ubuntu's pip installing an incompatible version of mako. The whole problem is that doing everything under root overrode my local settings that bypass Ubuntu's outdated hell.

**Comment by flightlessmango** [comment]
I wasn't making a counterpoint, I just explained why things are the way they are.
This is not as easy as just adding an option for what prefix you'd want.
Could you outline how you would achieve this and make it work for all shells/distros?

The purpose of the script is to be an absurdly easy way for beginners to compile mangohud, it's the least preferable way, but the most convenient. Your suggestion do not fit with this.
