### ISSUE TITLE
Euro-Truck Simulator 2 won't start with MangoHud 

### ISSUE THREAD

**Issue by nutta-git** [flightlessmango/MangoHud#182]
Issue: 
        When running Euro-Truck Simulator 2 under Steam-Play Proton 5.0-7 with the launch command 
- `MANGOHUD=1 %command%`

The game will not launch. Steam will prompt its running, but then stop.

Current MangoHud Version 
- `mangohud.x86_64                                         0.3.5-1.fc32  `

[steam-227300.log](https://github.com/flightlessmango/MangoHud/files/4646989/steam-227300.log)

**Comment by nutta-git** [comment]
`mangohud %command%` solved the issue

**Comment by jackun** [comment]
That doesn't make sense indeed. Are you running  steam with its runtime or a "native" aka system libraries version?

**Comment by nutta-git** [comment]
@jackun looks like I am using steam runtime 
```
Running Steam on fedora 32 64-bit
STEAM_RUNTIME is enabled automatically
```

**Comment by flightlessmango** [comment]
While this is strange, It seems to only affects one game that we know and is solved by using the preferred way to use MangoHud. I would call this a non-issue

**Comment by Leopard1907** [comment]
It works here.

![Ekran Görüntüsü - 2020-05-22 16-03-57](https://user-images.githubusercontent.com/24878978/82739825-bdc2f500-9d4b-11ea-9cb4-ce101aaa58ad.png)
