### ISSUE TITLE
Cannot turn off frametime graph

### ISSUE THREAD

**Issue by X6205** [flightlessmango/MangoHud#183]
I have installed latest pre-compiled binary of MangoHud on Ubuntu 20.04 and tried to tweak appearance on screen with config file in my user profile ($HOME/.config/MangoHud/MangoHud.conf)
but it seem i cannot turn off frametime graph. By deafult is uncommented so i have commented it out with hashtag character, like on any other lines in config file, but nothing happens and frametime graph is still visible in game. Other setting i have tried to enable/disable seems to work as expected.

**Comment by flightlessmango** [comment]
params that are enabled by default has to be explicitly disabled `frame_timing=0`

**Comment by X6205** [comment]
True, it works. Sorry for spamming.
