### ISSUE TITLE
Feature request: Add option to disable engine version

### ISSUE THREAD

**Issue by jazztickets** [flightlessmango/MangoHud#184]
Currently OVERLAY_PARAM_ENABLED_fps is used to enable/disable the engine version section of the overlay. It'd be nice to separate that out into a new config option.

**Comment by egee-irl** [comment]
+1 this used to be configurable but for some reason it appears to be hardcoded in the config. My engine version is so long that it is truncated in the hud and looks ugly.

I'm curious why this was changed at all? If the engine version _must_ be shown to the user, surely there is a better way of displaying it?

**Comment by flightlessmango** [comment]
Added in develop 078617f99966afd98eac31735d8632a04f360111
