### ISSUE TITLE
Grand Theft Auto V - HUD closes after startup

### ISSUE THREAD

**Issue by squadramunter** [flightlessmango/MangoHud#185]
On my Grand Theft Auto V the HUD closes after Grand Theft Auto V launched. Is there a way to fix this?

My following launch options are these.

gamemoderun WINEDLLOVERRIDES=winedbg.exe=d vblank_mode=0 mangohud %command%

**Comment by flightlessmango** [comment]
Could it be that you pressed `F12`? It's the default key for toggling the hud

**Comment by squadramunter** [comment]
No this is just at te startup. When I have -fullscreen option enabled and alt + tab it works.

**Comment by flightlessmango** [comment]
I have not seen this issue before, could you give some more details?
os, gpu and mangohud version

Steps to reproduce is just run the game in fullscreen?

**Comment by squadramunter** [comment]
A quick overview using Neofetch. I have this issue on KDE Manjaro

OS: Manjaro Linux x86_64 
Host: MS-7B79 3.0  
Kernel: 5.6.12-1-MANJARO 
Uptime: 9 hours, 16 mins 
Packages: 1353 (pacman), 6 (flatpak), 4 (snap) 
Shell: bash 5.0.16 
Resolution: 2560x1440 
DE: Plasma 
WM: KWin 
WM Theme: McMojave 
Theme: McMojave [Plasma], Sierra-dark-alt [GTK2 
Icons: la-capitaine-icon-theme [Plasma], la-cap 
Terminal: konsole 
Terminal Font: Noto Mono 10 
CPU: AMD Ryzen 7 3700X (16) @ 3.600GHz 
GPU: AMD ATI Radeon RX 5600 OEM/5600 XT / 5700/ 
Memory: 10460MiB / 32124MiB

**Comment by Leopard1907** [comment]
Why you even use this?

`vblank_mode=0`

If you don't have vsync enabled in game that variable is unnecessary.

**Comment by jazztickets** [comment]
> If you don't have vsync enabled in game that variable is unnecessary.

Not necessarily. Running glxgears by itself on my machine (5700xt, opensource amdgpu drivers) results in automatic vsync. Not sure why though, since it's not explicitly set anywhere else. Maybe it's a mesa thing. Some games don't call the vsync function when it's turned off in-game (e.g. Door Kickers)  so it defaults to on with my system.

**Comment by squadramunter** [comment]
> Why you even use this?
> 
> `vblank_mode=0`
> 
> If you don't have vsync enabled in game that variable is unnecessary.

No vblank gives your framerate a boost. Without it I got lag

**Comment by squadramunter** [comment]
> I have not seen this issue before, could you give some more details?
> os, gpu and mangohud version
> 
> Steps to reproduce is just run the game in fullscreen?

Yes this only happens to me when I run the game on fullscreen. With 144hz and hottest resolution enabled. I don't know why but it only works when I alt+tab the game or change my resolution in game. I play as Windowed Borderless

**Comment by XRaTiX** [comment]
Still with the new 0.4.1 i have this problem still,anyone know what can cause this? Only happen when the game is in fullscreen.

**Comment by zany130** [comment]
this could be similar to my issue https://github.com/flightlessmango/MangoHud/issues/202. as mangohud does show up and then disappears after a while

**Comment by jackun** [comment]
[MangoHud-0.4.1.r50.gb098635.tar.gz](https://github.com/flightlessmango/MangoHud/files/4809048/MangoHud-0.4.1.r50.gb098635.tar.gz)
@squadramunter  @zany130  Shot in the dark but try this

**Comment by zany130** [comment]
I haven't been able to replicate this issue since I wiped manjaro and installed arch so idk.

**Comment by ArnaudDovi** [comment]
Same issue on Arch Linux, reproduce it 100% but only with GTA V yet.

OS: Arch Linux x86_64 
Kernel: 5.7.5-arch1-1 
Uptime: 2 hours 
Packages: 949 (pacman) 
Shell: bash 5.0.17 
Resolution: 1920x1080 
DE: Cinnamon 
WM: Mutter (Muffin) 
WM Theme: Mojave-dark (Mojave-dark) 
Theme: Mojave-dark [GTK2/3] 
Icons: McMojave-circle [GTK2/3] 
Terminal: guake 
CPU: Intel i7-4770K (8) @ 3.900GHz 
GPU: NVIDIA GeForce GTX 980 
GPU: NVIDIA GeForce GTX 980 
Memory: 6353MiB / 15944MiB

**Comment by flightlessmango** [comment]
Is this issue still reproducible?
