### ISSUE TITLE
FPS stuck at 60fps max

### ISSUE THREAD

**Issue by Danie10** [flightlessmango/MangoHud#186]
Hi, the HUD is working great for me except it keeps maxing only at 60fps. When I test it on say rFactor 2 it will blip once or twice to 61fps and 64fps and stays on 60. rFactor 2 normally clocks a good 140 to 190fps for me.

I've tried commenting out the fps limit from the config file as well as setting it to 200. I also tried GOverlay and set it to unlocked, unset, and custom=200.

Am I missing something?

**Comment by flightlessmango** [comment]
Have you set vsync in mangohud?

**Comment by Danie10** [comment]
It has GL VSync and Vulkan VSync as ON yes.

**Comment by flightlessmango** [comment]
Vsync limits the FPS to the screens refresh rate

**Comment by Danie10** [comment]
Ah perfect thanks that solved it. Seems GOverlay was defaulting to VSync on.
