### ISSUE TITLE
Minecraft support through MultiMC?

### ISSUE THREAD

**Issue by satyrnhub** [flightlessmango/MangoHud#187]
MultiMC has this feature, which allows you to set a wrapper command. I set this to `mangohud`, and launched MultiMC from a terminal through `MANGOHUD_DLSYM=1 multimc`. This generated an error:

`X Error of failed request:  BadDrawable (invalid Pixmap or Window parameter)
  Major opcode of failed request:  14 (X_GetGeometry)
  Resource id in failed request:  0x2400008
  Serial number of failed request:  162
  Current serial number in output stream:  162
Version: 4.6`

It will completely ignore the wrapper command if I don't run it from the terminal with that command. My hopes are high that this is fixable, and that MangoHUD will be able to run on Minecraft.

Any help?

**Comment by flightlessmango** [comment]
This has been fixed in the develop branch

**Comment by satyrnhub** [comment]
Works on develop branch, closing.

**Comment by ShaunTheQuietGamer** [comment]
Once again only works if you run multimc with that command from the terminal. mulltimc seems to ignore the wrapper command if run without the 'MANGOHUD_DLSYM=1 multimc'

**Comment by flightlessmango** [comment]
It's not that multimc is ignoring the mangohud command, it's that mangohud requires the DLSYM env var to work on minecraft
