### ISSUE TITLE
Cyrillic characters are shown incorrectly

### ISSUE THREAD

**Issue by Shished** [flightlessmango/MangoHud#188]
![12](https://user-images.githubusercontent.com/3143668/82752846-a296ca80-9dc9-11ea-9dab-3132da207b9c.png)

Cyrillic letters are shown as "?"
OS is Arch Linux, Mangohud is installed from the [mangohud](https://aur.archlinux.org/packages/mangohud/) AUR.

**Comment by jackun** [comment]
For quick fix try `mangohud-git` and set `font_file` in config file to some font that supports cyrillic like Roboto.

**Comment by Shished** [comment]
I tried mangohud-git with Noto-Regular and modded Unispace fonts, question marks still appearing.


![123](https://user-images.githubusercontent.com/3143668/82757007-5c9c2f80-9de6-11ea-9f83-e32cc4c585c2.png)

**Comment by jackun** [comment]
Strange, works for me.
![Screenshot_20200524_181859](https://user-images.githubusercontent.com/4328738/82757718-0c739c00-9deb-11ea-9cb0-71598c3e9853.png)

**Comment by Shished** [comment]
Text on my screenshots is from youtube (opened in chromium).

**Comment by jackun** [comment]
What's the actual package version? Should be about `r67` or more:
> pacman -Qi mangohud-git
> Name            : mangohud-git
> Version         : 0.3.5.r67.gc046584-1

**Comment by Shished** [comment]
0.3.5.r67.gc046584-1

**Comment by jackun** [comment]
Wait, the driver name layout is wrong. Seems it somehow loads older v0.3.5 still.

**Comment by Shished** [comment]
I should've reboot the PC before retesting. It works now.
![1234](https://user-images.githubusercontent.com/3143668/82758182-af2d1a00-9ded-11ea-844b-643576839391.png)

**Comment by Shished** [comment]
Default font should have cyrillic support.

**Comment by Shished** [comment]
Can you make Mangohud use 2 fonts - Unispace for main HUD and some other font with different languages support (like Noto) for metadata?

**Comment by flightlessmango** [comment]
it's possible, I don't know how practical it is. Do you wanna weigh in on this @jackun ?

**Comment by rtentser** [comment]
Most often it could be fixed with LANG=ru_RU.UTF-8 (if locale was generated). Works with cyrillic characters in OpenMW & wine. I didn't test it with mangohud, but if it works (it should), it's a locale problem, not mangohud's (i guess). @Shished, you play in russian, but which locale are you using as a system's?

**Comment by Shished** [comment]
@rtentser This problem is not related to locale. The problem is that the font that is used by default in Mangohud (Unispace) has only latin letters included, no cyrillic, arabic or CJK.
Right now I'm using modified version of Unispace that has cyrillic letters included, but that's not a solution because other alfabets are still not shown.

**Comment by jackun** [comment]
Currently two separate fonts should work in `develop`. `font_file` for whole hud or `font_file_text` for only metadata.
Unispace license seems iffy too (cannot embed?), maybe should replace it with something else.
