### ISSUE TITLE
How to change hotkeys?

### ISSUE THREAD

**Issue by kik4444** [flightlessmango/MangoHud#19]
How do you change the hotkeys such as F12 and F2? For me F12 is not very convenient because it conflicts with Yakuake.

**Comment by flightlessmango** [comment]
That Feature is planned, currently the only way is to change it in the source code

**Comment by guihkx** [comment]
If you are willing to change the code and compile it yourself, here's the bit you want to change:

https://github.com/flightlessmango/MangoHud/blob/4be6d4c748d6570e2e46102d86ff0eb0a2cf0270/src/overlay.cpp#L891

Replace `XK_F12` by whatever key code you want. The list of key codes are available [here](https://cgit.freedesktop.org/xorg/proto/x11proto/tree/keysymdef.h), or in `/usr/include/X11/keysymdef.h`. 

For example, if you want <kbd>Shift</kbd>+<kbd>Home</kbd> as your hotkey, you'd do:

```cpp
if (key_is_pressed(XK_Shift_L) && key_is_pressed(XK_Home)){
```

**Comment by flightlessmango** [comment]
I've added an easier way to change keys now using MANGOHUD_CONFIG.
ex: `MANGOHUD_CONFIG=toggle_hud=F10,toggle_logging=F3`
You can use other keys than the F1-12 keys

**Comment by murlakatamenka** [comment]
F12 is also default hotkey for making a screenshot in Steam.

Oh, the timing :)

**Comment by kik4444** [comment]
> I've added an easier way to change keys now using MANGOHUD_CONFIG.
> ex: `MANGOHUD_CONFIG=toggle_hud=F10,toggle_logging=F3`
> You can use other keys than the F1-12 keys

How do you use that to map multiple keys? E.g. I recompiled the project to use Shift + Caps Lock. What's the syntax for that here?

**Comment by flightlessmango** [comment]
You can't, I just wanted to squeeze this in since it's been a much requested feature. I will see what I can do with multiple keys later

**Comment by Danie10** [comment]
> I've added an easier way to change keys now using MANGOHUD_CONFIG.
> ex: `MANGOHUD_CONFIG=toggle_hud=F10,toggle_logging=F3`
> You can use other keys than the F1-12 keys

Just want to clarify two things here relating to this:
1. The setting is in the MangoHud.conf file? We replace the two separate lines (below) with this one new one as quoted above?
```
toggle_hud=F12
toggle_logging=F2
```
2. Single keys other than just F1 to F12 can now be used? Wondering if a capital letter P for example (SHIFT-P) will be recognised versus a small letter p? Or is it literally a single button press? Latter is not a train smash right now as no game uses every single button.

**Comment by jackun** [comment]
2. Seems to be single key. In https://cgit.freedesktop.org/xorg/proto/x11proto/tree/keysymdef.h
, even though XK_P and XK_p are separate, both work just pressing p. Like `XK_question`, question mark needs a shift on non-US keyboards but works without too.

**Comment by Danie10** [comment]
@jackun great thanks for the quick response. I'll test further with the parameters - good as can be set differently for different games.
