### ISSUE TITLE
Wrong API reported for Path of Exile

### ISSUE THREAD

**Issue by LiamDawe** [flightlessmango/MangoHud#191]
Testing out the Vulkan Beta in Path of Exile, MangoHud says it's "DXVK" still.

Edit: Actually it might be a bug with their switcher, switching between modes in the menu and now MangoHud does report Vulkan.

Can anyone else test to confirm?

**Comment by flightlessmango** [comment]
I tried it yesterday and switched back and forth in game and it worked. You could use DXVK_HUD to check if it actually is dxvk or vulkan

**Comment by LiamDawe** [comment]
Yeah I think their switch is just funky, nvm.
