### ISSUE TITLE
RPM build issues [Advice needed]

### ISSUE THREAD

**Issue by VortexAcherontic** [flightlessmango/MangoHud#192]
Hey there this is a rather unconventional sort of an issue.
Currently I try to add MangoHUD to the open build service infrastructure (build an openSUSE Tumbleweed RPM) and there for I have to deal with some parts of your build and meson scripts.

My very first issue was to remove all git related function calls since during the build process inside the OBS there is not available internet connection since due to their guidelines all packages need to be buildable offline. Not a problem because you can define all required dependencies in the rpm spec file:

````
#BuildRequires:  libXNVCtrl-devel
BuildRequires:   gcc-c++
BuildRequires:   gcc-c++-32bit
BuildRequires:   libpkgconf-devel
BuildRequires:   ninja
BuildRequires:   python3-pip
BuildRequires:   python3-Mako
BuildRequires:   libX11-devel
BuildRequires:   libX11-devel-32bit
BuildRequires:   glslang-devel
BuildRequires:   glibc-devel
BuildRequires:   glibc-32bit
BuildRequires:   glibc-devel-32bit
BuildRequires:   libstdc++-devel
BuildRequires:   libstdc++-devel-32bit
BuildRequires:   Mesa-libGL-devel
BuildRequires:   dbus-1-devel
BuildRequires:   meson
BuildRequires:   vulkan-headers
BuildRequires:   vulkan-devel
BuildRequires:   libglvnd-devel
BuildRequires:   libglvnd-devel-32bit
````

My issue currently is with your meson.build file at that point where it checks the vulkan dependencies:
`dep_vulkan = dependency('vulkan', required: get_option('use_system_vulkan'))`
and
`if dep_vulkan.found()`
It seems however to miss vulkan even if I ensured the dependencies in the spec file vulkan-headers as well as vulkan-devel (also tried libvulkan1 but no success)

My question is how I can ensure that meson will find the required dependencies?
Or if this is an issue of the git stuff I striped out since I noticed your scripts are downloading several submodules like the vulkan-header git repo from Khronos Group and there fore meson may search the vulkan stuff in the wrong directory.

Also I wonder how to utilize the `use_system_vulkan` switch for meson since I don't know if it is true or false in order to circumvent some issues here and to avoid any git related stuff like the subproject(vulkanheadres) parts which tries to access github for the vulkan-header repo of Khronos Group.

I must also say that this is also my first attempt to submit anything to the open build service at all and also that I have zero knowledge about meson beside the things I looked up while running into issues ^^"

What I did so far is:
- Translated the build.sh completely into the spec file at %prep %build and %install
- Added all dependencies I could find in you PKGBUILD, meson.build and build.sh files
- Modified PKGBUILD
  - Removed git related stuff
- And maybe some additional changes I do not recap right now.
- Removed occurrences of ./build.sh since the script wont work inside OBS anyway.

The latest spec file can be found [here](https://build.opensuse.org/package/view_file/home:VortexAcherontic/MangoHUD/mangohud.spec?expand=1) and the modified source [here](https://gitlab.com/z-ray-entertainment/mangohud-rpm)

**Comment by flightlessmango** [comment]
`use_system_vulkan` is disabled by default, so I guess you'd want to use `-Duse_system_vulkan=enabled`

**Comment by jackun** [comment]
Yeah, don't use build.sh for packaging. Maybe [fedora spec helps](https://src.fedoraproject.org/rpms/mangohud/blob/master/f/mangohud.spec)

**Comment by VortexAcherontic** [comment]
Thank you both of you that really helped me a lot!
Now I just need to properly understand how RPMs work :D

ty <3
