### ISSUE TITLE
MangoHud is HUD is working only for some games, or im doing something wrong..

### ISSUE THREAD

**Issue by ruthan** [flightlessmango/MangoHud#193]
Hello,
im new user, i used this tutorial for MangoHUD:
https://www.youtube.com/watch?v=97p2Ja5D1go

 with Mint 19.3, Cinnamon, Lightdm and Nvidia 1070 + 440 driver and Steam games (all native).

Working:
Metro Last Light Redux
Xcom remake (1)
Wasteland 2
FTL

Not working: - no HUD visible..
Half-Life 2
Dex
Dead Island
Bioshock infinite
Brutal Legend
Baldurus gate Enhanced edition
Witcher 2
Legend of Grimrock
Saint row: the Third
Serious Sam 3

Its there any chance to fix not working games?

**Comment by flightlessmango** [comment]
are you using `MANGOHUD=1` ? use `mangohud` instead

**Comment by ruthan** [comment]
Im using Lutris.
Mangohud=1 env variable and 
mangohud as preffix in advanced option.
  Both together. I also tried to add MANGOHUD_DLSYM=1 as enviroment variable.

  Here is picture:
![image](https://user-images.githubusercontent.com/1702944/83361181-18c99d00-a387-11ea-9b2e-931a339a92f2.png)

**Comment by flightlessmango** [comment]
Do not use DLSYM for every game, it will break some games.
`mangohud` env var is supposed to be all caps.
 You can't set command prefix or env vars for steam games, it doesn't work like that.
You need to set `mangohud %command%` in the launch option for the game

**Comment by ruthan** [comment]
DLSYM - ok, i used it after it not working without it, so my bug list was the same without it (nothing is failed because of it), BTW i tried couple of game no one of them broke.
  Mangohud - all the caps - i put it like that, but it changed by Lutris itseft.. but if it working with some games, i quess that it ok.

   Preffix.. Well on Github page is this:
_For Lutris games, go to the System options in Lutris (make sure that advanced options are enabled) and add this to the Command prefix setting:
   mangohud
   So i did exactly that set it globally for all games..
   
  So it has to be per individual game? And how it play with global variable? Its confusing.

  BTW is HUD working for you with my list of games (yeah you probably dont have all of them, but Half-Life 2 etc.. has everybody)? And if yes which GPU do you have?

**Comment by flightlessmango** [comment]
Lutris just sends a command to Steam, it's still Steam that's starts the game. Games that you've installed with lutris would work with the command prefix.

Yes you would need to set it per game for Steam games. There is no way to enable mangohud for all steam games.

I doubt there is an issue with mangohud and the games, I think it's just an error in the setup

**Comment by ruthan** [comment]
Ok, but i how its possible that with 3 games it is working about per game setup?

 What supposed to be proper setup?
 1) Can i let global mangohud variable in Lutris setup?
 2) Remove Lutrix preffix?
3) Add to Steam per launch option mangohud=1 or its better directly edit steam launcher and with mangohud "steam lauch command"?

**Comment by flightlessmango** [comment]
1. If you have the command prefix, there is no point in using the variable. Env var is only for vulkan, command is for both vulkan and opengl.
2. You can keep the command prefix in lutris.
3. Add `mangohud %command%` to launch options
if that doesn't work try these separately 
`mangohud.x86 %command%`
`MANGOHUD_DLSYM=1 mangohud %command%`
`MANGOHUD_DLSYM=1 mangohud.x86 %command%`

**Comment by ruthan** [comment]
Thanks, info one clarification.  By launch option you mean, Linux launcher edit (for example - steam steam://rungameid/8870 )? Or Steam game setting se launch option..?
This input box is usually empty, so there is not any %command%

  If its possible to set it in Steam GUI it would be better than make manually launcher for every game?

  To mangohud.x86 vs. mangohud is possible just make Mangohud more clever to detect of game is 32/64 bit automatically?

**Comment by ruthan** [comment]
I tried all combinations with Bioshock Infinite game and it still not working - Steam Overlay FPS counter is working..
  If im not wrong that  mangohud MANGOHUD_DLSYM=1 is right order. I have tried all of these in Launcher:
```
mangohud steam steam://rungameid/8870
mangohud.x86 steam steam://rungameid/8870
mangohud.x86 MANGOHUD_DLSYM=1 steam steam://rungameid/8870
mangohud MANGOHUD_DLSYM=1 steam steam://rungameid/8870
```

**Comment by jackun** [comment]
Nah, before: `MANGOHUD_DLSYM=1 mangohud`.

Probably should turn it into an script argument instead :thinking:

**Comment by flightlessmango** [comment]
I mean launch options in steam properties for the game, you're still effectively doing the exact same thing. You're sending a command to steam to start the game.
Just copy paste the lines I wrote in to the launch options in steam and you're done

**Comment by ruthan** [comment]
Hmm, today its not working even HUD for games where it worked.. I updated Steam. 
When i run game with MangoHUD.. i see additional error:
`ERROR: ld.so: object 'libMangoHud.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.`

  Thanks for examplation, you i expect some logic behind it.. that %command% means real command not exact such string, these things could be confusing..

**Comment by ruthan** [comment]
Great with mangohud.x86 %command% Half-life 2 is now working.

**Comment by lucifertdark** [comment]
mangohud %command% prevented Borderlands 2 from starting at all this morning, a quick change to mangohud.x86 %command% & the game runs again.

**Comment by rockerbacon** [comment]
> Yes you would need to set it per game for Steam games. There is no way to enable mangohud for all steam games.
> 
> I doubt there is an issue with mangohud and the games, I think it's just an error in the setup

I came here thinking I had a bug. I added `MANGOHUD=1` to my `~/.profile` according to the instructions on the README:

> For Steam games, you can add this as a launch option:
>
> `mangohud %command%`
>
> Or alternatively, add MANGOHUD=1 to your shell profile (Vulkan only).

Maybe this alternative should be removed from the instructions?

**Comment by flightlessmango** [comment]
As it says, it only works with Vulkan. I.e all openGL games will not work. I don't see how that is wrong or missleading

**Comment by rockerbacon** [comment]
I probably misinterpreted the comments on this issue then. I thought MANGOHUD=1 didn't work at all for any games and that's the behaviour I'm having, no games show the HUD unless I set the launch option on Steam.

When you say Vulkan, do you include DXVK or is it only native Vulkan games?

**Comment by flightlessmango** [comment]
Yes DXVK and VKD3D is Vulkan. If you can set `MANGOHUD=1 %command%` in launch options with a vulkan/dxvk game, then I would assume it's not being read in the .profile

**Comment by rockerbacon** [comment]
I doubled checked the profile and fixed a few things, everything is working now. Thanks a lot for the help!
