### ISSUE TITLE
Flatpak MangoHud not working with Lutris

### ISSUE THREAD

**Issue by aimforthebushes** [flightlessmango/MangoHud#194]
I've just installed the flatpak version of Mangohud and, following the instructions, I've added `mangohud` as a command prefix to the system options of the game on Lutris but it doesn't launch the game.

I've also tried `flatpak run  com.valvesoftware.Steam.Utility.MangoHud` just in case but I end up with the same results.

**Comment by flightlessmango** [comment]
Flatpak mangohud only works with flatpak steam, I would recommend using the release package instead

**Comment by aimforthebushes** [comment]
Thanks for the info
