### ISSUE TITLE
0,1 & 1 % Low FPS

### ISSUE THREAD

**Issue by kgudalov** [flightlessmango/MangoHud#195]
Is it possible to implement a monitoring function of 0.1 and 1 % Low FPS?

**Comment by flightlessmango** [comment]
In develop there is a new feature when you use the logging. It will display a window with some info of that logging session, including 1% lows. [example](https://cdn.discordapp.com/attachments/366023719199440908/717806164967948348/unknown.png)
Not exactly the same thing, but more than nothing

**Comment by jazztickets** [comment]
So tried that in 0.4.1, and a blank window appears for about 6-7 seconds:

![log1](https://user-images.githubusercontent.com/425930/84428068-15ce7800-abe3-11ea-88c2-df29d34fda7a.png)

Then, for about 1 second the information appears, then disappears:
![log2](https://user-images.githubusercontent.com/425930/84428094-1ff07680-abe3-11ea-9941-792f555299b2.png)

I imagine that information should be appearing the whole time, correct?

Here's the config i'm using:
```
cpu_temp=1
gpu_temp=1
vram=1
ram=1
frame_timing=0
background_alpha=0
font_size=15
position=bottom-right
offset_y=-180
toggle_hud=F8
toggle_logging=F6
reload_cfg=F5
output_file=/var/log/mango/drg
```

**Comment by flightlessmango** [comment]
@jazztickets 
Should be fixed in develop now
