### ISSUE TITLE
[Darkest Dungeon] MANGOHUD: XNVCtrl loader failed to load

### ISSUE THREAD

**Issue by rtentser** [flightlessmango/MangoHud#201]
I'm trying to run windows version of Darkest Dungeon (which is 32-bit & OpenGL game) in wine-staging 5.9. Mangohud (with MANGOHUD_DLSYM=1) works, but no gpu information, only CPU, OpenGL & frametime. Output:

```
MANGOHUD: libXNVCtrl.so.0 dlopen failed: libXNVCtrl.so.0: cannot open shared object file: No such file or directory
MANGOHUD: libXNVCtrl.so.0 dlopen failed: libXNVCtrl.so.0: cannot open shared object file: No such file or directory
MANGOHUD: XNVCtrl loader failed to load
Version: 4.6 
Version: 4.6 
Version: 4.6 
Version: 4.6 
Audio_LoadBankFiles - elapsed_sec=0.085948
Audio_LoadBankFiles - elapsed_sec=0.235825
```

MangoHud in Goodbye Deponia (also 32-bit, OpenGL, but native) works fine. So do windows version of "The Dwarves" (just tested it without dxvk... graphics are broken, but mangohud works fine).

**Comment by jackun** [comment]
> 32 bit

Did you actually use `mangohud.x86` then?

**Comment by rtentser** [comment]
> Did you actually use mangohud.x86 then?

No, i've used just mangohud. And use it now.

**Comment by jackun** [comment]
Nah, I can't read. It probably was correct because it printed opengl version. Maybe it fails to get drawable's size and just renders into a 0x0 pixel box.

**Comment by rtentser** [comment]
This is how it looks:
![mangohud](https://user-images.githubusercontent.com/34958119/83950474-35694780-a855-11ea-80fd-f97e02ee225c.png)

**Comment by flightlessmango** [comment]
You need 32bit xnvctrl libs for 32bit apps

**Comment by rtentser** [comment]
Yes, you right. lib32-libxnvctrl fixed the issue. Thanks!
