### ISSUE TITLE
Mango HUD breaks with directshow wine verb in Trails in the Sky SC directx9 version

### ISSUE THREAD

**Issue by zany130** [flightlessmango/MangoHud#202]
Like the title says if I run the d9 version with the DirectShow wineverb  and the other verbs needed for video playback in the game (Xvid and a program called lavfilters) mangohud will unload as soon as a video plays. This did not happen in a older version of mango hud from march (forgot what version its also possible that an update to another package maybe wine that caused this behavior). Mango Hud worked normally if you either disable video playback or don't install any of the winetricks ( in which case the game will black screen but mangohud will show) on the d8 version of the game which is being translated to OpenGL, mangohud loads normally even with the movies and the wine verbs enabled.

**Comment by flightlessmango** [comment]
is it possible to reproduce this in other games by adding these verbs?

**Comment by flightlessmango** [comment]
Is this still reproducible?
