### ISSUE TITLE
[Documentation] Log files - Where are they?

### ISSUE THREAD

**Issue by VortexAcherontic** [flightlessmango/MangoHud#206]
Hey there I struggle to find the location of the log files produces while logging a games performance.

I used the MANGOHUD_OUTPUT environment variable by either providing only a file name and also by adding /home/myuser/logfile as well as leaving the env out. But in all three cases I am unable to find the log file.

I followed the readme here and also saw the red dot while it is logging as well as got the final results presented inside the HUD. But I can not find the logfile itself.

Where are they located/stored?

MangoHUD version used: 0.3.5-103-g6d1ed97+

Tried a game providing both APIs OpenGL and Vulkan (No DXVK or VKD3D used) if this makes a difference at all :smile:

**Comment by luni3359** [comment]
Where are they saved by default when there's no option set in the configuration file? I can't find them anywhere
