### ISSUE TITLE
VRAM not showing

### ISSUE THREAD

**Issue by FurbyonSteroid** [flightlessmango/MangoHud#21]
I tried to make vram and ram show into the hud, but apparently it doesn't work on my system. The configuration is read (as you can see, no frame_timing and additional core_load) but ram and vram is ignored. Is there a way to get an output on why that is? Like, a log or something? I guess it simply can't find where to look for.

Here are my launch options:

> MANGOHUD_CONFIG=cpu_temp,gpu_temp,core_load,ram,vram,frame_timing=0 MANGOHUD=1 gamemoderun %command%

(Removing gamemoderun didn't change anything, so that's not the issue)

I'm using manjaro (latest version) with an RX580 with the latest mesa-version. 

![Screenshot](https://user-images.githubusercontent.com/24521712/74091260-c998ed00-4ab5-11ea-8bb9-d1eeb8dab920.png)

**Comment by telans** [comment]
Which version of MangoHud are you using? v0.1.0 from releases doesn't have this feature, but the master branch does.

**Comment by FurbyonSteroid** [comment]
Well, I guess I can try building it from master. Once done I'll update this issue (closing it or commenting)

**Comment by FurbyonSteroid** [comment]
Alright yea, turns out I'm just a idiot.. apologies.. closing.

Thank you for your fast response.
