### ISSUE TITLE
Failed to open 64bit libnvidia-ml.so.1

### ISSUE THREAD

**Issue by at46** [flightlessmango/MangoHud#212]
MangoHud 0.4.1 works fine for me but it always shows that it's missing libnvidia-ml.so.1. E.g.: 
```
at46@at46-desktop:~$ mangohud vkcube
MANGOHUD: Failed to open 64bit libnvidia-ml.so.1: libnvidia-ml.so.1: cannot open shared object file: No such file or directory
MANGOHUD: Failed to open 64bit libnvidia-ml.so.1: libnvidia-ml.so.1: cannot open shared object file: No such file or directory
MANGOHUD: Failed to open 64bit libnvidia-ml.so.1: libnvidia-ml.so.1: cannot open shared object file: No such file or directory
skipping config: /usr/bin/MangoHud.conf [ not found ]
skipping config: /home/at46/.config/MangoHud/vkcube.conf [ not found ]
skipping config: /home/at46/.config/MangoHud/MangoHud.conf [ not found ]
```
If I remember correctly 0.3.5 didn't show that. I'm not sure if this is considered as a bug but I'm always afraid there's something not working correctly if I see such messages. By the way I've an amd gpu (rx570).

**Comment by jackun** [comment]
>  is considered as a bug 
No. It maybe annoying but just bare with it for now until some better logging stuff gets added, someday.
