### ISSUE TITLE
mangohud thinks im using nvidia or something

### ISSUE THREAD

**Issue by bgkillas** [flightlessmango/MangoHud#226]
when ever i try to run mangohud with anything i get a ton of messages like

MANGOHUD: Failed to open 64bit libnvidia-ml.so.1: libnvidia-ml.so.1: cannot open shared object file: No such file or directory

is this something wrong with my install i reinstalled for reasons of few times and its still there im using arch linux xfce4 and a radeon 5500xt or what ever if it matters

**Comment by flightlessmango** [comment]
It's just a warning, has no effect
