### ISSUE TITLE
Support more advanced logging

### ISSUE THREAD

**Issue by larskraemer** [flightlessmango/MangoHud#229]
I would like to know what you think about extending the logging feature a bit. Currently, the only values that can be logged are FPS and CPU/GPU load. It would be nice to let the user configure what is logged, including options like CPU/GPU temps, RAM, clocks, etc.

**Comment by flightlessmango** [comment]
I don't see any problem with adding all the values to the log that are being monitored already. I think the question is what to do with them. Just logging the values is one thing, the question is what we do with them, are you envisioning a graph for every type of value?

**Comment by larskraemer** [comment]
That would probably be a bit cluttered in the end. I think adding just the values the user requests to the log, and then graphing those values would be better. This would obviously require an additional row in the log file which specifies what values _are_ being logged.

**Comment by mattlorimor** [comment]
@flightlessmango - re: this topic

You got a direct shout-out and some major praise from Linus and Anthony of Linus Tech Tips. Linus did mention, though, that he wished more values could be logged.

> Honestly, if it logged more information like CPU and GPU temperatures, we'd probably switch over to it instead of what we're using in Windows.

https://youtu.be/6T_-HMkgxt0?t=353
