### ISSUE TITLE
Option to start with hidden MangoHud

### ISSUE THREAD

**Issue by marhkb** [flightlessmango/MangoHud#23]
I really like how to toggle MangoHud with a hotkey.
Unfortunately, MangoHud must always be displayed on game startup before manually be toggled off.

In my use case, I'd like to start a game with MangoHud initially being hidden and only toggle it on on demand.
Any chance this can be implemented?

**Comment by flightlessmango** [comment]
I added this feature in this commit [d79d06](https://github.com/flightlessmango/MangoHud/commit/d79d06271fe921a57277621ec4d5f088972c4acd)
you can now use `MANGOHUD_CONFIG=no_display` to hide mangohud by default
