### ISSUE TITLE
 Ubuntu 17.04 on hp-530 (32 bits, 2Gb ram): "ninja: build stopped: subcommand failed."

### ISSUE THREAD

**Issue by enriqueortegagarcia** [flightlessmango/MangoHud#230]
~/git/MangoHud$ ./build.sh build
ninja: Entering directory `build/meson32'
[1/41] Generating overlay.frag.spv.h with a custom command
FAILED: src/overlay.frag.spv.h 
/usr/local/bin/glslangValidator -V -x -o src/overlay.frag.spv.h ../../src/overlay.frag
/usr/local/bin/glslangValidator: 1: /usr/local/bin/glslangValidator: ELF: not found
/usr/local/bin/glslangValidator: 2: /usr/local/bin/glslangValidator: N: not found
/usr/local/bin/glslangValidator: 3: /usr/local/bin/glslangValidator: Syntax error: "(" unexpected
/usr/local/bin/glslangValidator: 2: /usr/local/bin/glslangValidator: /usr/local/bin/glslangValidator: 2: /usr/local/bin/glslangValidator: N�: not found
I@�:R@8: not found
[2/41] Generating version.h with a custom command
ninja: build stopped: subcommand failed.

Ubuntu 17.04 on hp-530 (32 bits, 2Gb ram)

**Comment by flightlessmango** [comment]
We've made an assumption that the system MangoHud is being installed on is a 64bit multiarch one, yours is not. That's most likely where the problem stems from. As far as I can tell your cpu doesn't support 64bit so telling you to update to a 64bit OS is not really an option either. I don't know if it's reasonable for us to start supporting just 32bit either, it would be difficult to say the least and it's so old by now it's probably better left in the past

**Comment by pixelr0** [comment]
Ubuntu 17.04 is EOL (end of life) you will not get updates. Upgrade to at least 18.04
