### ISSUE TITLE
No GPU information

### ISSUE THREAD

**Issue by Scratchcat1** [flightlessmango/MangoHud#233]
Issue:
When running MangoHud all GPU stats are either 0 or blank (gpu_name). Other tools such as radeontop and lmsensors are able to find the correct values.
![image](https://user-images.githubusercontent.com/29149512/85030595-8c382080-b175-11ea-8355-e28eb4887d5f.png)

Attempted fixes:
Specifying `pci_dev = 0000:01:00.0`
Adding a symlink from `/usr/share/hwdata/pci.ids` to `/usr/share/misc/pci.ids` to fix `MANGOHUD: can't find file pci.ids`.

System information:
```
System:    Host: desktop Kernel: 5.6.0-2-amd64 x86_64 bits: 64 compiler: gcc v: 8.3.0 Desktop: Xfce 4.14.2 
           Distro: MX-19.2_x64 patito feo October 21  2019 base: Debian GNU/Linux 10 (buster) 
Memory:    RAM: total: 11.64 GiB used: 2.86 GiB (24.6%) 
           Array-1: capacity: 16 GiB slots: 2 EC: None max module size: 8 GiB note: est. 
           Device-1: ChannelA-DIMM0 size: 8 GiB speed: 1333 MT/s type: DDR3 
           Device-2: ChannelB-DIMM0 size: 4 GiB speed: 1333 MT/s type: DDR3 
CPU:       Topology: Quad Core model: Intel Core i5-4690K bits: 64 type: MCP arch: Haswell rev: 3 L2 cache: 6144 KiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 27984 
           Speed: 928 MHz min/max: 800/3900 MHz Core speeds (MHz): 1: 900 2: 899 3: 900 4: 900 
Graphics:  Device-1: Advanced Micro Devices [AMD/ATI] Hawaii PRO [Radeon R9 290/390] driver: radeon v: kernel bus ID: 01:00.0 
           Display: server: X.Org 1.20.4 driver: ati,radeon unloaded: fbdev,modesetting,vesa resolution: 1920x1080~60Hz 
           OpenGL: renderer: AMD HAWAII (DRM 2.50.0 5.6.0-2-amd64 LLVM 10.0.0) v: 4.5 Mesa 20.0.7 direct render: Yes 
Audio:     Device-1: Advanced Micro Devices [AMD/ATI] Hawaii HDMI Audio [Radeon R9 290/290X / 390/390X] driver: snd_hda_intel 
           v: kernel bus ID: 01:00.1 
           Sound Server: ALSA v: k5.6.0-2-amd64
```

**Comment by flightlessmango** [comment]
We're using `/sys/class/drm/card0/device/gpu_busy_percent` to get the GPU load for AMD cards, on older cards this file isn't accessible. Check if that's the case for you, if it is there isn't much we can do about it. Programs like radeontop requires sudo to get that information and that's not a viable option for MangoHud

**Comment by DadSchoorse** [comment]
> ```Device-1: Advanced Micro Devices [AMD/ATI] Hawaii PRO [Radeon R9 290/390] driver: radeon v: kernel bus ID: 01:00.0```

Are you really using the old radeon kernel driver instead of the newer amdgpu driver? If so, can you try using amdgpu by booting with the `radeon.cik_support=0 amdgpu.cik_support=1` kernel parameter?

**Comment by Scratchcat1** [comment]
@DadSchoorse Setting those parameters fixed it. Thanks!

**Comment by Tooniis** [comment]
> Programs like radeontop requires sudo to get that information and that's not a viable option for MangoHud

Not in my case. I can force it to read from `/dev/mem`, which then makes it require root

**Comment by flightlessmango** [comment]
It's a difference without a distinction, no?

**Comment by SleeplessSloth** [comment]
I'm using an R9 270X, so by definition it's an "older AMD card" but with the amdgpu kernel driver. In case of @Scratchcat1, using the amdpgu driver fixed the issue but not in my case. Reading from `/sys/class/drm/card0/device/gpu_busy_percent` results in "Invalid argument". Is there really no way to get the GPU usage info with my card? I mean, if radeontop shows the info, it should've gotten it from somewhere. If the driver doesn't provide `gpu_busy_percent` but the info can be gotten from elsewhere, then, I'm not really clarified to talk about this, theoretically, it should be possible to write/patch the driver to provide such info in 'gpu_busy_percent'. Am I wrong? Or is there some technical limitation?

**Comment by flightlessmango** [comment]
The problem is that every other way of getting it requires root access.. It might be useful if *someone* can reach out to the amdgpu devs to see why gpu_busy_percent is not working and if it can be fixed.

**Comment by fabiandrinksmilk** [comment]
> > Programs like radeontop requires sudo to get that information and that's not a viable option for MangoHud
> 
> Not in my case. I can force it to read from `/dev/mem`, which then makes it require root

How did you do that? I can't find how to force it to read from /dev/mem.

**Comment by Faalagorn** [comment]
> We're using `/sys/class/drm/card0/device/gpu_busy_percent` to get the GPU load for AMD cards, on older cards this file isn't accessible. Check if that's the case for you, if it is there isn't much we can do about it. Programs like radeontop requires sudo to get that information and that's not a viable option for MangoHud

Just a wild guess; wouldn't it be possible to run something as root in the background (like a systemd unit for example) and write that info to some file that can be read? Or possibly some easier way to do so. I may take a look at it when I reinstall the OS on some of my Terrascale PCs.

**Comment by leikareipa** [comment]
This issue pops up on a Google search. Has there been progress? I'm seeing no GPU info by default for a Radeon HD 5770 with the 'radeon' driver and kernel 5.15 in MangoHud 0.6.8.

I can see temperature and core clock info in the /sys/class/drm/ path, so I assume these would be displayable at least. I'm also seeing radeontop not requiring root access to get the GPU busy percent and VRAM usage - although the VRAM reading breaks and massively overflows if you saturate the memory capacity, but it seems to be a driver/kernel/whatever bug rather than radeontop.

For now I'm piping the radeontop readings into files for MangoHud to read from, but since this appears to be possible without root then I assume it would be possible natively in MangoHud.

**Comment by jobukkit** [comment]
I also have "GPU 0%" with my AMD Radeon RX 480. (And commenting out "gpu_stats" from the config doesn't seem to do anything, so I can't even hide it...)

**Comment by Faalagorn** [comment]
> I also have "GPU 0%" with my AMD Radeon RX 480. (And commenting out "gpu_stats" from the config doesn't seem to do anything, so I can't even hide it...)

480 shouldn't be affected; it's newer card (Polaris), it works just fine for me for RX 580 (basically the same card).
![screenshot_2023-09-09-084549](https://github.com/flightlessmango/MangoHud/assets/4951331/e024fbd0-4141-43bc-833b-9fef7d9bebf8)

Here's my MangoHud.conf file https://gist.github.com/Faalagorn/99a7b0b2471e06b16d8452e2736537f2 running on Arch with zen kernel.
