### ISSUE TITLE
Split up fps and frame_timing into multiple parameters

### ISSUE THREAD

**Issue by vyrus714** [flightlessmango/MangoHud#235]
Could these lines be split up so that their separate elements could be toggled independently? Something similar to how cpu_temp and gpu_temp can be toggled on the gpu_stats and cpu_stats lines.

The fps line just needs an extra parameter for the frame time, but it would also be nice to toggle the labels on the frame_timing graph so you have only the graph showing. If you're already showing the frame time in the fps line above it, it doesn't make much sense to have it displayed twice, and the graph label is just extra vertical space taken up for me.

You could actually take this a step further and split up everything, but that might be a separate issue. Say give each line a toggle as it is now, but every element on the line would only show up if its own property was enabled.
e.g. cpu_stats, cpu_label, cpu_load, cpu_temp

**Comment by flightlessmango** [comment]
There will most likely be a major overhaul of the config/params system in the future, making these small alterations obsolete
