### ISSUE TITLE
GPU Temp and VRAM don't working on Source Engine games.

### ISSUE THREAD

**Issue by Jovco** [flightlessmango/MangoHud#241]
Hello, i have a GTX 550 ti and i'm using the latest version of Pop.Os. I installed MangoHud yesterday and notice a weird bug that i didn't found on the internet. In some games all my MangoHud interface appears normal, in others the GPU Temp and VRAM doesn't show. I tested on Hearts of Iron 4 and everything appears ok. But on Source Engine games, the already told GPU Temp and Vram are missing. 

![Screenshot from 2020-06-19 15-34-18](https://user-images.githubusercontent.com/67165981/85169718-aa1f8700-b242-11ea-98f5-ccfc36dcbca4.png)
Hearts of Iron 4

![Screenshot from 2020-06-19 15-35-03](https://user-images.githubusercontent.com/67165981/85169755-b7d50c80-b242-11ea-8f02-6acdcc81dd8d.png)
Insurgency

![Screenshot from 2020-06-19 15-36-26](https://user-images.githubusercontent.com/67165981/85169772-c02d4780-b242-11ea-84b9-1abc0583114f.png)
Garry's Mod

The last two use the Source Engine and i think that is the reason of my problems.
Any help?

**Comment by jackun** [comment]
I think these are 32bit games? You'd need 32bit libxnvctrl.
Try `apt install libxnvctrl:i386` or something like that.

**Comment by Jovco** [comment]
> I think these are 32bit games? You'd need 32bit libxnvctrl.
> Try `apt install libxnvctrl:i386` or something like that.

Didn't locate the package.

**Comment by flightlessmango** [comment]
try `libxnvctrl-dev:i386`

**Comment by jackun** [comment]
Seems it's `libxnvctrl0`

**Comment by Jovco** [comment]
> try `libxnvctrl-dev:i386`

Thank You. It Worked.
![Screenshot from 2020-06-19 15-58-39](https://user-images.githubusercontent.com/67165981/85171637-c40e9900-b245-11ea-863a-0a3823b884ea.png)
