### ISSUE TITLE
Cant Configure for DXVK titles

### ISSUE THREAD

**Issue by HD-901** [flightlessmango/MangoHud#245]
i cant configure anything with DXVK games it works with openGL and Vulkan but when i try to use any DXVK i have tried making specific config files for DXVK games for example Nuclear Throne (wine-NuclearThrone.conf) and im sure it works because it works on openGL and vulkan games without program specific config files

**Comment by HD-901** [comment]
[message.txt](https://github.com/flightlessmango/MangoHud/files/4809014/message.txt)
my conf file

**Comment by jackun** [comment]
Create proton log with `PROTON_LOG=1 mangohud %command%`

**Comment by HD-901** [comment]
what would i name the proton log and where i know i need to put `PROTON_LOG=1 `but where

**Comment by jackun** [comment]
Wait, do you have it on Steam or? Otherwise just run it from terminal and copy the outputted text here.

**Comment by HD-901** [comment]
what do you mean i am running it on steam i am running and using mangohud on steam yes

**Comment by jackun** [comment]
* Right-click on the game title under the Library in Steam and select Properties.
* Under the General tab click the Set launch options... button, add `PROTON_LOG=1 mangohud %command%`
* Enter the launch options you wish to apply (be sure to separate each code with a space) and click OK.
* Close the game's Properties window and launch the game.

**Comment by HD-901** [comment]
nope neither `PROTON_LOG=1 mangohud %command%` or `PROTON_LOG=1 mangohud.x86` makes any of the things i changed in the conf file appear

**Comment by jackun** [comment]
Drag/drop the log from your home folder here, should be `steam-242680.log`

**Comment by HD-901** [comment]
i didnt get a steam-12345.log

**Comment by jackun** [comment]
Uh? Did you add it like this?
![Screenshot_20200621_130008](https://user-images.githubusercontent.com/4328738/85221748-2f2fab00-b3bf-11ea-9a18-cb7dde586564.png)

**Comment by HD-901** [comment]
yes just like that and i tried mango.x86 too because idk if Nuclear Throne is 32bit or 64 bit

**Comment by jackun** [comment]
The game has native linux version too. Sure it is windows version?

**Comment by HD-901** [comment]
yes i turned on steam play compatibillity when i wanted to use Nuclear Throne as a benchmark so Mango would work

**Comment by HD-901** [comment]
![Screenshot from 2020-06-21 05-05-50](https://user-images.githubusercontent.com/62722391/85221865-08e91b80-b37d-11ea-9f21-8bbe004154ea.png)

**Comment by HD-901** [comment]
<h2>are you there<h2>
