### ISSUE TITLE
feature request: RTSS scanline sync counterpart for fps limiter

### ISSUE THREAD

**Issue by aufkrawall** [flightlessmango/MangoHud#249]
Hello,
Riva Tuner Statistics Server for Windows offers a scanline sync feature:

From RTSS doc:
> 
> Added alternate framerate limiting mode, based on synchronization with display rasterizer position.
> Now you may synchronize the framerate to up to two independent scanline indices per refresh interval.
> Combining with power user configurable scanline wait timeout and graphics pipeline flushing options, those settings provide experienced users vendor agnostic ultra low input lag adaptive VSync, half VSync or double VSync functionality on any hardware

Would it be possible to extend MangoHud's fps limiter in this regard?
Thanks!

**Comment by aufkrawall** [comment]
It would appear Vulkan mailbox vsync of Mesa drivers works well when combined with an fps limiter. While I never found such hacks to work sufficiently well on Windows due to regular stutter each x seconds, it works surprisingly smoothly on Linux with Mesa. With libstrangle it's also possible to use fractions like 84.99fps. Not sure if this decreases latency further, as it's hard to not fool yourself with placebo without being able to toggle on the fly. Imho latency is still a bit higher than with scanline sync, but result is much more stable and usable, while latency is far lower than with fifo vsync modes.

**Comment by flightlessmango** [comment]
This is beyond me technical understand of things, I'm unsure if it's possible

**Comment by QmwJlHuSg9pa** [comment]
For anyone who comes across this issue in the future:
- Here's some technical information on a hypothetical implementation for Linux: https://forums.blurbusters.com/viewtopic.php?t=8019#p61764
- And, an open issue (with a US$500 bounty, to boot) over at libretro/RetroArch that includes Linux support in its scope: https://github.com/libretro/RetroArch/issues/6984
- Finally, the Scanline Sync master post: https://forums.blurbusters.com/viewtopic.php?t=4916
