### ISSUE TITLE
Use mangohud with Lutris

### ISSUE THREAD

**Issue by superbonaci** [flightlessmango/MangoHud#250]
Would like to know if it's possible to use MangoHud with Lutris games, using wine for example for Battle.net

**Comment by Leopard1907** [comment]
Please take a look at readme before opening an issue.

https://github.com/flightlessmango/MangoHud#normal-usage

**Comment by superbonaci** [comment]
Thanks did that, but the game does not enter the menu, or at least it's not displayed. Hitting Esc does not work, I have to hit Alt+F4 to close. It displays a black screen with mangohud on top.
The game is Overwatch. Screenshot is cropped original resolution is 1080p.

![Overwatch on Lutris with MangoHud](https://i.imgur.com/4tUTC8u.png)

**Comment by Leopard1907** [comment]
Game works without Mangohud but doesn't work with it?

**Comment by superbonaci** [comment]
More news, it happened the first 2 times, then tried a third time and now it works. Lucky me I gave it 3 chances didn't expect it to end up working.

By the way what does mean the 7.7 ms? How can I see the graph for FPS stability?

**Comment by flightlessmango** [comment]
You are more than welcome to join our discord and ask away

**Comment by superbonaci** [comment]
The 7.7ms is the result of 1/130FPS.
