### ISSUE TITLE
Show actually used OpenGL/Vulkan driver info

### ISSUE THREAD

**Issue by ripper81** [flightlessmango/MangoHud#251]
Besides showing information about DXVK,Vulkan,Feral3D it would be nice to see which driver is in use for the Vulkan api. For AMDGPU it would be good to see whether MESA or AMDVLK is in use. I have both drivers installed on my system but i don't know if a game picks MESA RADV or AMDVLK for rendering with Vulkan.

**Comment by flightlessmango** [comment]
use the `vulkan_driver` option

**Comment by ripper81** [comment]
Can i use this option as a launchoption for steam games ?

**Comment by flightlessmango** [comment]
Please check the readme before making an issue
You can use `MANGOHUD_CONFIG=vulkan_driver`

**Comment by ripper81** [comment]
Sorry for opening up a new issue. Would be nice to have this information displayed by default. Thank you for the great work you are doing with mangohud.
