### ISSUE TITLE
VRAM Frequency reading bug

### ISSUE THREAD

**Issue by CytronBR** [flightlessmango/MangoHud#252]
My GPU is a RX580 in which the VRAM I recently overclocked to 2250MHz, but it's showing in the hud as -2044MHz in all games that i tested. Tried recompiling the program and also using the latest precompiled version, same issue. I'm using Linux Mint 19.3.
![vram](https://user-images.githubusercontent.com/32803215/85436259-1cec7300-b55f-11ea-81b0-2ee717ae3b79.png)

**Comment by flightlessmango** [comment]
what do you get from `cat /sys/class/drm/card0/device/hwmon/hwmon0/freq2_input` at the same time?

**Comment by CytronBR** [comment]
I get this, -2044967296

**Comment by flightlessmango** [comment]
Doesn't seem to be anything wrong with mangohud then, sounds like a bug in libsensors maybe?

**Comment by CytronBR** [comment]
Idk, when I do " sudo cat /kernel/debug/dri/0/amdgpu_pm_info | grep '(MCLK)' " it shows the correct memory clock:" 2250 MHz (MCLK) "

**Comment by CytronBR** [comment]
sorry, I mean " sudo cat /sys/kernel/debug/dri/0/amdgpu_pm_info | grep '(MCLK)' "

**Comment by flightlessmango** [comment]
Yeah my guess is that it's a bug in libsensors then, you would need to bug lm-sensors about it

**Comment by CytronBR** [comment]
You're right, doesn't seen like a problem in mangohud itself, will continue troubleshooting  here and see what I can do, thanks for the help!

**Comment by jackun** [comment]
Hmm, not libsensors but amdgpu itself then?

**Comment by CytronBR** [comment]
I don't think so, cause as I said if I type " sudo cat /sys/kernel/debug/dri/0/amdgpu_pm_info | grep '(MCLK)' " (which I think is a amdgpu generated file), it returns the correct frequency.

**Comment by jackun** [comment]
https://www.kernel.org/doc/html/v5.0/gpu/amdgpu.html

**Comment by CytronBR** [comment]
could also be because I'm using a quite old version of amdgpu (or radv, don't really know how it's called), I'm using version 19.2.8

**Comment by Leopard1907** [comment]
Add this ppa to your system and Mesa update will appear on Update Manager.

https://launchpad.net/~kisak/+archive/ubuntu/kisak-mesa

And also update your kernel via Linux kernels section of update manager.

**Comment by CytronBR** [comment]
@Leopard1907 No luck on that either, unfortunately.
