### ISSUE TITLE
"MANGOHUD_CONFIG=full" gives "Failed to get initial media player metadata."

### ISSUE THREAD

**Issue by rtentser** [flightlessmango/MangoHud#254]
Arch Linux, "Vampire: The Masquerade - Bloodlines". Mangohud works, but gives this output:

```
MANGOHUD: The name org.mpris.MediaPlayer2.spotify was not provided by any .service files
MANGOHUD: Failed to get initial media player metadata.
MANGOHUD: Connected to D-Bus as ":1.148".
MANGOHUD: The name org.mpris.MediaPlayer2.spotify was not provided by any .service files
MANGOHUD: Failed to get initial media player metadata.
MANGOHUD: The name org.mpris.MediaPlayer2.spotify was not provided by any .service files
MANGOHUD: Failed to get initial media player metadata.
MANGOHUD: The name org.mpris.MediaPlayer2.spotify was not provided by any .service files
MANGOHUD: Failed to get initial media player metadata.
MANGOHUD: XNVCtrl is using display :0
MANGOHUD: The name org.mpris.MediaPlayer2.spotify was not provided by any .service files
MANGOHUD: Failed to get initial media player metadata.
MANGOHUD: The name org.mpris.MediaPlayer2.spotify was not provided by any .service files
MANGOHUD: Failed to get initial media player metadata.
MANGOHUD: The name org.mpris.MediaPlayer2.spotify was not provided by any .service files
MANGOHUD: Failed to get initial media player metadata.
MANGOHUD: The name org.mpris.MediaPlayer2.spotify was not provided by any .service files
MANGOHUD: Failed to get initial media player metadata.
MANGOHUD: The name org.mpris.MediaPlayer2.spotify was not provided by any .service files
MANGOHUD: Failed to get initial media player metadata.
MANGOHUD: The name org.mpris.MediaPlayer2.spotify was not provided by any .service files
MANGOHUD: Failed to get initial media player metadata.
```

Strangely (or not), `MANGOHUD_CONFIG=cpu_temp,gpu_temp,core_load,gpu_core_clock,gpu_mem_clock,ram,vram` doesn't give the same result.

**Comment by larskraemer** [comment]
Are you using `MANGOHUD_CONFIG=full` or similar? The warning appears because mangohud is trying to talk to a media player, but you don't appear to have one open.

**Comment by rtentser** [comment]
> Are you using MANGOHUD_CONFIG=full or similar?

Yes.

> but you don't appear to have one open.

Tried to run with opened vlc, nothing changed. Why is mangohud trying to talk with media player?

**Comment by larskraemer** [comment]
It has a built-in display for Songtitle etc, which you enabled by using `MANGOHUD_CONFIG=full`. The default player it will try to talk to is spotify, you can change that by using `media_player=something`.
It might be a good idea to try and auto-detect any media player, and provide the config option as an override

**Comment by flightlessmango** [comment]
It shouldn't stop a game from working either way

**Comment by larskraemer** [comment]
Yea, but `full` does not behave the way it is documented to behave in `README.md`.
That _is_ an issue, probably not a huge one though

**Comment by rtentser** [comment]
The game works. I agree with @larskraemer, the documentation is misleading in this case.

**Comment by flightlessmango** [comment]
It enables all boolean params, not sure how to write that in the readme and have people understand

**Comment by larskraemer** [comment]
In this case, it might actually be better to make the code match the documentation. Turn on only the display options and leave media_player stuff alone.
As for auto-detecting a media player, I think I may be able to write some code to let us do that, if you'd like.

**Comment by rtentser** [comment]
Or you can reorder parameters list so "Enables all of the above config options" (and only them) will be true.

**Comment by flightlessmango** [comment]
auto detection could be interesting, it would just need to be overwritten by the param for name
