### ISSUE TITLE
None of the Keybindings Work (So no Logging)

### ISSUE THREAD

**Issue by gardotd426** [flightlessmango/MangoHud#259]
As of about 3 weeks ago, neither the F12 nor F2 keybindings (to disable the HUD and start/stop logging, respectively) work. 

I thought at first this might be a config/parameters issue, like when the `output` parameter got changed to `output_file`, but no, even F12 doesn't work whatsoever. 

I've tried this in 3 games, + glxgears and vkcubepp. And it definitely worked as recently as the end of May (that's when my log files stop). 

I've tried both the current release version and the git version. 

I had an old `git clone` of this repo that I hadn't ran `git pull` on in about a month or so, since I started using the AUR packages (both release and git), and I just uninstalled the current AUR package I had, and installed the old repo version. Sure enough, the keypresses immediately started working again. 

So then, just to make sure that this wasn't because of something with the AUR builds (I've seen that happen before) I uninstalled that build, went to a different directory, and cloned the **current** repo. Ran the commands, installed it, and tried again. And sure enough, it doesn't work. 

It seems this is a clear example of a regression. 

Arch Linux
5.7.5-11-tkg-pds
RX 5700 XT

This issue is present with OpenGL and Vulkan.

**Comment by gardotd426** [comment]
Like I said above, the keybindings work on the old build, so it's not my config file. But here's my config, just in case you want to see it:

```
### MangoHud configuration file
### Uncomment any options you wish to enable. Default options are left uncommented
### Use some_parameter=0 to disable a parameter (only works with on/off parameters)
### Everything below can be used / overridden with the environment variable MANGOHUD_CONFIG instead

################ PERFORMANCE #################

### Limit the application FPS
# fps_limit=

### VSYNC [0-3] 0 = adaptive; 1 = off; 2 = mailbox; 3 = on
 vsync=1

################### VISUAL ###################

### Display the current CPU information
cpu_stats
# cpu_temp

### Display the current GPU information
gpu_stats
# gpu_temp

### Display the frametime line graph
frame_timing

### Display the current system time
# time

### Change the hud font size (default is 24)
font_size=24

### Change the hud position (default is top-left)
position=top-left

### Display the current CPU load & frequency for each core
# core_load

### Display system ram / vram usage
# ram
# vram

### Disable / hide the hud by deafult
# no_display

### Hud position offset
# offset_x=
# offset_y=

### Hud dimensions
# width=
# height=

### Hud transparency / alpha
background_alpha=0.5

### Crosshair overlay (default size is 30)
# crosshair
# crosshair_size=
# crosshair_color=RRGGBB

################## INTERACTION #################

### Change toggle keybinds for the hud & logging
toggle_hud=F12
toggle_logging=F2
```

**Comment by jackun** [comment]
Works for me/others. Run something from terminal and check if it complains about libX11.

**Comment by gardotd426** [comment]
@jackun like I said, it works with a previous build (since I've now installed since it works). 

But uninstalling that, and reinstalling the current AUR version, I only get errors about Nvidia stuff (I don't have an Nvidia card):

```
MANGOHUD: Failed to open 64bit libnvidia-ml.so.1: libnvidia-ml.so.1: cannot open shared object file: No such file or directory
MANGOHUD: Failed to open 64bit libnvidia-ml.so.1: libnvidia-ml.so.1: cannot open shared object file: No such file or directory
MANGOHUD: Failed to open 64bit libnvidia-ml.so.1: libnvidia-ml.so.1: cannot open shared object file: No such file or directory
```

**Comment by flightlessmango** [comment]
The default keybinds changed, see if shift_r+F12  works. Could be something wrong with the config parsing

**Comment by gardotd426** [comment]
Sure enough, R-Shift+F12 works. 

And also, there is an error with config stuff. 

So, for all these games I've mentioned (and for most of my testing with vkcube and whatnot), I've manually set output files with `MANGOHUD_CONFIG=cpu_temp,gpu_temp,output_file=/path/to/filename`, and because it's so difficult to figure out what to name a config file for each game (especially with wine games, what do I name them? wine.conf? or for Titanfall 2 for example,  Titanfall2.conf? titanfall2.conf? tf2.exe.conf? ???) and because creating a config file for every game sounds like a ton of work. But when I do that, it doesn't load my actual config file (`~/.config/MangoHud/MangoHud.conf`) which has my keybindings in it. But now I'm noticing that it's not even respecting those anyway (I've tried without setting any config options, just regular old `MANGOHUD=1 vkcubepp`). 


I tried R-Shift+F2 for logging, that didn't work, so I tried L-Shift+F2, and that did work (don't know if that's intended behavior or not). 


I'll go ahead and close this, but if you have any words of wisdom on how better to manage everything with what I'm talking about above, please let me know here, if you don't mind.

**Comment by jackun** [comment]
There's also `MANGOHUD_CONFIG=read_cfg,output_file=/path/to/filename` , reads `MangoHud.conf`

**Comment by gardotd426** [comment]
@jackun this is perfect. I just tried it, and it works (and with my old keybindings so I don't have to use the new ones). I was actually starting to stress worrying about having to create configs for every game and all that, thank you so much.
