### ISSUE TITLE
No MangoHud.conf file found anywhere

### ISSUE THREAD

**Issue by Viking8** [flightlessmango/MangoHud#26]
This seems strange, but I can't find the .conf file anywhere on my system. I've looked not only in the default location, but did a system wide search for it, but nothing was found. 
Could you add something to show how the .conf file is supposed to look so I can just create one?

Ryzen 5 2600x
16GB DDR4 3200
Sapphire Nitro+ RX580
Pop!_OS 19.04

**Comment by telans** [comment]
Sorry for the confusion, but the config file is only currently available on the `master` branch, as it was added after the release (assuming you're using the release). If you build MangoHud from master, the config file should be copied to your system.

If you don't wish to build, there should be a new release in a day or two.

**Comment by Viking8** [comment]
Thanks for the updated info. I will wait for the next release!
