### ISSUE TITLE
mangohud freezes winecfg

### ISSUE THREAD

**Issue by frostworx** [flightlessmango/MangoHud#261]
running on a amdgpu system - no idea if the same error occurs with a nvidia gpu.

Error: with MANGOHUD=1 creating a fresh WINEPREFIX with winecfg fails.

to reproduce:

**with MANGOHUD=0 this works** (WINEPREFIX is created and winecfg opens):

```
mkdir /tmp/wineMHoff
MANGOHUD=0 WINEPREFIX="/tmp/wineMHoff" winecfg
```
the first lines are:
```
002c:fixme:winediag:__wine_start_process Wine Staging 5.11 is a testing version containing experimental patches.
002c:fixme:winediag:__wine_start_process Please mention your exact version when filing bug reports on winehq.org.
WARNING: radv is not a conformant vulkan implementation, testing use only.
```

**with MANGOHUD=1 this doesn't work** (stalls)
```
mkdir /tmp/wineMHon
MANGOHUD=1 WINEPREFIX="/tmp/wineMHon" winecfg
```
the first lines are:
```
002c:fixme:winediag:__wine_start_process Wine Staging 5.11 is a testing version containing experimental patches.
002c:fixme:winediag:__wine_start_process Please mention your exact version when filing bug reports on winehq.org.
**MANGOHUD: Failed to open 64bit libnvidia-ml.so.1: libnvidia-ml.so.1: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden**
WARNING: radv is not a conformant vulkan implementation, testing use only.
```

I guess libnvidia-ml.so.1 shouldn't be required/loaded here
very likely my other issue has the same bug: 
https://github.com/flightlessmango/MangoHud/issues/258

**Comment by frostworx** [comment]
looks like https://github.com/flightlessmango/MangoHud/issues/212 is not just a cosmetical glitch in every usecase then

**Comment by flightlessmango** [comment]
I was not able to reproduce this on nvidia or amd

**Comment by frostworx** [comment]
thanks for testing! could it be mesa-git (20.2.0_devel.125338.99eecd3775d-1) related?

**Comment by flightlessmango** [comment]
I updated to `mesa-tkg-git-20.2.0_devel.125510.b1c16e52514`, but sadly no change

**Comment by frostworx** [comment]
damn, shouldn't have wasted your time, before trying myself - I'm sorry!
I just downgraded to mesa-20.1.2-1 and lib32-mesa-20.1.2-1 and
both
MANGOHUD=1 WINEPREFIX="/tmp/wineMHon" winecfg (here's llvm still default)
and
RADV_PERFTEST=aco MANGOHUD=1 WINEPREFIX="/tmp/wineMHon" winecfg

do work...

**Comment by frostworx** [comment]
fyi: made a diff between vulkaninfo output from previous vulkaninfo-mesa-git.txt and output from current stable:
[vulkaninfo.txt](https://github.com/flightlessmango/MangoHud/files/4842488/vulkaninfo.txt)

but as this probably isn't even a mangohud bug, maybe I should just close this issue?

**Comment by frostworx** [comment]
closing here, if there is interest in finding the source of the problem I'd be glad to help!
