### ISSUE TITLE
Double displayed hud with overlapping text

### ISSUE THREAD

**Issue by irneb** [flightlessmango/MangoHud#262]
I'm not sure this is a "bug", perhaps some setting file not mentioned in the documentation.
MangoHud itself worked perfectly fine up to the point when I used GOverlay to change the content. The display became unreadable as multiple lines of text would overlay over one another. I've tried several ways but it seems there's no fix.

Even when I delete all mango config files I still see it appear like this.
![image](https://user-images.githubusercontent.com/7736132/85942189-0e6bd600-b928-11ea-9a37-f1cab4b891ae.png)
As if MangoHud displays itself twice over, only at a slightly different positions and arrangement.

**Comment by jackun** [comment]
You have MangoHud installed twice somehow

**Comment by irneb** [comment]
Ok, yes. It seems I do have a 32bit and 64bit variant in the home local, not in the usr local though:
```
> ll /usr/share/vulkan/implicit_layer.d
total 8.0K
-rw-r--r--. 1 root root 583 Jun 11 15:46 MangoHud.x86_64.json
-rw-r--r--. 1 root root 472 Jun 10 20:03 VkLayer_MESA_device_select.json
> ll ~/.local/share/vulkan/implicit_layer.d                                            
total 24K
-rw-r--r--. 1 ibarnard ibarnard 446 Feb 17 11:30 mangohud32.json
-rw-r--r--. 1 ibarnard ibarnard 444 Feb 17 11:30 mangohud64.json
-rwxrwxr-x. 1 ibarnard ibarnard 481 Jun 27 22:20 steamfossilize_i386.json
-rwxrwxr-x. 1 ibarnard ibarnard 481 Jun 27 22:20 steamfossilize_x86_64.json
-rwxrwxr-x. 1 ibarnard ibarnard 463 Jun 27 22:20 steamoverlay_i386.json
-rwxrwxr-x. 1 ibarnard ibarnard 463 Jun 27 22:20 steamoverlay_x86_64.json
```
I've tried uninstalling both GOverlay and MangoHud. Deleteing those mangohud files from the home local. Re-installing only magohud, and finally adjusting the ~/.config/MangoHud/MagoHud.conf file. Works perfectly now thanks.
![image](https://user-images.githubusercontent.com/7736132/85945993-b93cbe00-b941-11ea-8547-d519f1794e01.png)

Is this a case of the 32bit version only showing up if a 32 bit game is played? Seems that home local doesn't contain any mangohud files now.
```
> ll ~/.local/share/vulkan/implicit_layer.d                                      
total 16K
-rwxrwxr-x. 1 ibarnard ibarnard 481 Jun 27 22:20 steamfossilize_i386.json
-rwxrwxr-x. 1 ibarnard ibarnard 481 Jun 27 22:20 steamfossilize_x86_64.json
-rwxrwxr-x. 1 ibarnard ibarnard 463 Jun 27 22:20 steamoverlay_i386.json
-rwxrwxr-x. 1 ibarnard ibarnard 463 Jun 27 22:20 steamoverlay_x86_64.json
> ll /usr/share/vulkan/implicit_layer.d                                      
total 8.0K
-rw-r--r--. 1 root root 583 Jun 11 15:46 MangoHud.x86_64.json
-rw-r--r--. 1 root root 472 Jun 10 20:03 VkLayer_MESA_device_select.json
```
Is it something about GOverlay perhaps?

I'm just asking, since if this is the case I might add some rm lines in the script I use to force the hud to appear in all games. ATM it seems unneeded.
