### ISSUE TITLE
'Unable to find distro information!' on Salient OS

### ISSUE THREAD

**Issue by baz8ka2th** [flightlessmango/MangoHud#265]
I had mangohud installed by default on this OS but it refused to work, GOverlay said restart for changes to take effect and upon restarting the global setting was switched off and all the changes I had made to the overlay were reversed. couldn't use it using MANGOHUD=1 in steam proton either.

That was using the AUR version, i've subsequently deleted it, GOverlay and all prerequisites to attempt to reinstall manually:
Now, what I get is errors while following the install instructions on the main page as follows:

baz8ka2th  baz8ka2th-LPTP  ~  $  git clone --recurse-submodules https://github.com/flightlessmango/MangoHud.git
Cloning into 'MangoHud'...
remote: Enumerating objects: 70, done.
remote: Counting objects: 100% (70/70), done.
remote: Compressing objects: 100% (55/55), done.
remote: Total 3972 (delta 36), reused 32 (delta 15), pack-reused 3902
Receiving objects: 100% (3972/3972), 41.22 MiB | 1.57 MiB/s, done.
Resolving deltas: 100% (2828/2828), done.
Submodule 'modules/ImGui/src' (https://github.com/flightlessmango/imgui.git) registered for path 'modules/ImGui/src'
Cloning into '/home/baz8ka2th/MangoHud/modules/ImGui/src'...
remote: Enumerating objects: 34193, done.
remote: Total 34193 (delta 0), reused 0 (delta 0), pack-reused 34193
Receiving objects: 100% (34193/34193), 52.98 MiB | 1.70 MiB/s, done.
Resolving deltas: 100% (25574/25574), done.
Submodule path 'modules/ImGui/src': checked out '1f02d240b38f445abb0381ade0867752d5d2bc7b'
baz8ka2th  baz8ka2th-LPTP  ~  $  cd MangoHud
/home/baz8ka2th/MangoHud
assets build.sh include libmangohud.conf.in meson.build modules README.md subprojects
bin build-source.sh libmangohud.conf LICENSE meson_options.txt PKGBUILD src version.h.in
baz8ka2th  baz8ka2th-LPTP  ~  MangoHud  master  $  ./build.sh build
Checking Dependencies
Unable to find distro information!
Attempting to build regardless
./build.sh: line 145: meson: command not found
baz8ka2th  baz8ka2th-LPTP  ~  MangoHud  master  $  ./build.sh package
Checking Dependencies
Unable to find distro information!
Attempting to build regardless
./build.sh: line 145: meson: command not found
baz8ka2th  baz8ka2th-LPTP  ~  MangoHud  master  $ 

**Comment by baz8ka2th** [comment]
I had mangohud installed by default on this OS but it refused to work, GOverlay said restart for changes to take effect and upon restarting the global setting was switched off and all the changes I had made to the overlay were reversed. couldn't use it using MANGOHUD=1 in steam proton either. 

That was using the AUR version, i've subsequently deleted it to reinstall manually:
Now, what I get is errors while following the install instructions on the main page as follows:

 baz8ka2th  baz8ka2th-LPTP  ~  $  git clone --recurse-submodules https://github.com/flightlessmango/MangoHud.git
Cloning into 'MangoHud'...
remote: Enumerating objects: 70, done.
remote: Counting objects: 100% (70/70), done.
remote: Compressing objects: 100% (55/55), done.
remote: Total 3972 (delta 36), reused 32 (delta 15), pack-reused 3902
Receiving objects: 100% (3972/3972), 41.22 MiB | 1.57 MiB/s, done.
Resolving deltas: 100% (2828/2828), done.
Submodule 'modules/ImGui/src' (https://github.com/flightlessmango/imgui.git) registered for path 'modules/ImGui/src'
Cloning into '/home/baz8ka2th/MangoHud/modules/ImGui/src'...
remote: Enumerating objects: 34193, done.        
remote: Total 34193 (delta 0), reused 0 (delta 0), pack-reused 34193        
Receiving objects: 100% (34193/34193), 52.98 MiB | 1.70 MiB/s, done.
Resolving deltas: 100% (25574/25574), done.
Submodule path 'modules/ImGui/src': checked out '1f02d240b38f445abb0381ade0867752d5d2bc7b'
 baz8ka2th  baz8ka2th-LPTP  ~  $  cd MangoHud
/home/baz8ka2th/MangoHud
assets  build.sh         include           libmangohud.conf.in  meson.build        modules   README.md  subprojects
bin     build-source.sh  libmangohud.conf  LICENSE              meson_options.txt  PKGBUILD  src        version.h.in
 baz8ka2th  baz8ka2th-LPTP  ~  MangoHud  master  $  ./build.sh build
# Checking Dependencies
# Unable to find distro information!
# Attempting to build regardless
./build.sh: line 145: meson: command not found
 baz8ka2th  baz8ka2th-LPTP  ~  MangoHud  master  $  ./build.sh package
# Checking Dependencies
# Unable to find distro information!
# Attempting to build regardless
./build.sh: line 145: meson: command not found
 baz8ka2th  baz8ka2th-LPTP  ~  MangoHud  master  $ 

**Comment by largewedge** [comment]
Try installing meson. Salient OS isn't one of the distros recognized by the function that checks for dependencies in build.sh, so it won't catch that you're missing some.

**Comment by flightlessmango** [comment]
Manually installing it shouldn't make a difference, I would recommend you try the AUR version again and see if it's still having issues.
