### ISSUE TITLE
"MANGOHUD: can't find file pci.ids" on MXLinux 19.2 ahs

### ISSUE THREAD

**Issue by ThrashMetalComputers** [flightlessmango/MangoHud#266]
Whenever I run mangohud 0.4.1 on MXLinux 19.2 ahs, the "MANGOHUD: can't find file pci.ids" message always appears in the terminal.

The `pci.ids` file is located here in MXLinux:
`/usr/share/misc/pci.ids`

I fixed the issue by editing the `src/pci_ids.cpp` file in a text editor and changed the `std::ifstream file("/usr/share/hwdata/pci.ids");` line to `std::ifstream file("/usr/share/misc/pci.ids");`. After I compiled from source, the message no longer appeared.

A minor issue, but just wanted to document it for other MXLinux users. Regardless of the message, mangohud still runs.

**Comment by flightlessmango** [comment]
This has already been fixed in develop 8f22ebae446feea45094ea938c30fa5e42db18b8

**Comment by ThrashMetalComputers** [comment]
Thank you very much for this amazing software and glad it has been fixed!
