### ISSUE TITLE
Windows Port

### ISSUE THREAD

**Issue by NoFuchsGavin** [flightlessmango/MangoHud#267]
What can I do to get this working on Windows 10?

**Comment by DadSchoorse** [comment]
The first step would be to check if someone had the same question. #222

**Comment by vesterlay** [comment]
Windows version is on the development stage.

**Comment by Lolihunter1337** [comment]
If you dont mind me asking @vesterlay is #222 locked or deleted? i cant see the issue because it throws 404

**Comment by vesterlay** [comment]
I can't access it either, if you wanted something from this issue you can access it through WBM tho http://web.archive.org/web/20200916075852/https://github.com/flightlessmango/MangoHud/issues/222

**Comment by Lolihunter1337** [comment]
alright thanks
