### ISSUE TITLE
Don't work with gamemoded!

### ISSUE THREAD

**Issue by Noman-Aziz** [flightlessmango/MangoHud#268]
So i'm trying to add mangohud with gamemoded in steam game's launch options.
In my launch options when i type "gamemoded %command% mangohud %command%" , mangohud does not appear in game but gamemoded is running.
When i try the other way "mangohud %command% gamemoded %command%", then mangohud is running in game but gamemoded is not running.
Am i doing something wrong or these two can not work together?

**Comment by wallcarpet40** [comment]
Does it work, if you try gamemoded mangohud %command%

**Comment by larskraemer** [comment]
Not sure if there would be an issue running both, but you need to have exactly one `%command%` in your launch args. Try `mangohud gamemoded %command%`

**Comment by Noman-Aziz** [comment]
> Not sure if there would be an issue running both, but you need to have exactly one `%command%` in your launch args. Try `mangohud gamemoded %command%`

By putting one %command% in the arguments, both works, thank you.

**Comment by Leopard1907** [comment]
Wasn't that `gamemoderun` ?

**Comment by wallcarpet40** [comment]
It is in fact `gamemoderun`. I just tried `gamemoded` and the game would not start for me on Steam.
