### ISSUE TITLE
GPU stats (sometimes) missing Nvidia + prime-select + Steam

### ISSUE THREAD

**Issue by VortexAcherontic** [flightlessmango/MangoHud#269]
Hey there I am using the latest commit version of MangoHud (a day ago from this comment) and noticed that somehow the GPU specs are missing entirely if a game is launched via Steam independent of being native or run via Proton + DXVK and also this is Vulkan and OpenGL independent.

My guess is, do anyone know if steam does some PCI device overrides on mobile GPUs?

## Applications I've tested:

Steam:
- Tomb Raider Anniversary (WineD3D and DXVK and Proton 5.0-9)
  - Launch options: `PROTON_USE_WINED3D=1 mangohud.x86 gamemoderun %command%`
  - Launch options: `MANGOHUD=1 gamemoderun %command%`
- Sky Rogue (Native/Open GL/Unity Engine)
 - Launch Options: `mangohud gamemoderun %command%`

Both (better all 3 cases) where missing the GPU stats in the overlay

Non Steam:
- GLXGears
  - Launched as: `mangohud gamemoderun glxgears`
- VKMark
  - Launched as: `MANGOHUD=1 gamemoderun vkmark -p immediate`

All stats where shown as expected

I did not tested the iGPU since it has limited GL (max 3.x or so) and incomplete Vulkan support anyway.

## MangoHUD config:

````
cpu_temp=1
gpu_temp=1
core_load=1
gpu_core_clock=1
gpu_mem_clock=1
ram=1
vram=1
io_read=1
io_write=1
arch=1
vulkan_driver=1
gpu_name=1
gpu_power=1
engine_version=1
toggle_hud=F10
position=top-right
io_read=1
io_write=1
````

## System specs:

- CPU i5-3230M
- GPU: GT 730M
  - Driver: 440.100
  - libXNVCtrl and libXNVCtrl0 are installed
  - Optimus support via: suse-prime-bbswitch (prime-select in the Ubuntu World / Prime Manager in the Arch World)

Do any one know if this is a Steam thing (which I assume since glxgears and vkmark do work fine) and how to solve it?

Edit: Running Alien Isolation (Native) via Steam shows all stats as expected too o.O

Launch Options: `mangohud gamemoderun %command%`

## Alien Isolation: Steam - Native - OpenGL
![AI](https://user-images.githubusercontent.com/11244092/86490759-c9e99b80-bd68-11ea-96da-13b5603e72b8.png)

## Sky Rogue: Steam - Native - OpenGL
![SR](https://user-images.githubusercontent.com/11244092/86490769-df5ec580-bd68-11ea-9a9c-c2bf4251b90e.png)

## Tomb Raider Anniversary: Steam - Proton - DXVK
![TRA-DXVK](https://user-images.githubusercontent.com/11244092/86491034-c7d40c80-bd69-11ea-9042-ae865bb5d41f.png)

## Tomb Raider Anniversary: Steam - Proton - WineD3D
![TRA-WineD3D](https://user-images.githubusercontent.com/11244092/86491040-cc98c080-bd69-11ea-9434-50f3bdb1db2e.png)

## GLXGears
![GLXGears](https://user-images.githubusercontent.com/11244092/86491070-e63a0800-bd69-11ea-8569-e5a074a6dace.png)

## VKMark
![VKMark](https://user-images.githubusercontent.com/11244092/86491092-01a51300-bd6a-11ea-87de-91c5ed6bf2e8.png)

**Comment by flightlessmango** [comment]
is this still an issue?
