### ISSUE TITLE
[Suggestion] not load Nvidia libs if running an AMD GPU

### ISSUE THREAD

**Issue by AdelKS** [flightlessmango/MangoHud#271]
Hello!

First of all, thank you for your awesome work. I am here to report on a small thing that has no real negative impact on anything. But would be nice to fix.

MangoHud is trying to open Nvidia shared libraries even though I don't have an Nvidia GPU, it shows an error message but the Hud itself works flawlessly.

> MANGOHUD: Failed to open 64bit libnvidia-ml.so.1: libnvidia-ml.so.1: cannot open shared object file: No such file or directory

Or maybe I am doing something wrong: I installed MangoHud with `install.sh` as described in `README.md`. 

Thanks!

#### Additional Information

CPU: Ryzen 3700X
GPU: AMD RX 5700 XT
Distro: Ubuntu

I will give any other information if needed.

**Comment by flightlessmango** [comment]
I'm not sure we can stop the execution of that code if we detect an amd gpu. What you could do is build with `with_nvml` and `with_xnvctrl` disabled. Either way it shouldn't have any effect on actual usage

**Comment by AdelKS** [comment]
I can confirm it has no negative on game performance as far as I know.

> What you could do is build with with_nvml and with_xnvctrl disabled. Either way it shouldn't have any effect on actual usage

I will try it out. If it works out then maybe it's possible to automatically do those disables from the build script ?

> I'm not sure we can stop the execution of that code if we detect an amd gpu.

There's the option I am suggesting above, though I should try it out first. I will report back.

Does the same happen with Nvidia drivers, MangoHud tries to load AMD stuff ? Or is it different because AMD is included in the kernel ?

**Comment by stephanlachnit** [comment]
I guess that warning could be suppressed by default, but that might not be a good idea. I think adjusting the warning message to something less critical sounding like:
`MANGOHUD: 64bit libnvidia-ml.so.1 not loaded`
is less distracting for AMD users (since it doesn't look like an error anymore), while still being clear enough for nvidia users.

**Comment by variemai** [comment]
Hello I am having a similar issue how do you build with "with_xnvctrl" disabled?

**Comment by jackun** [comment]
@variemai ugh, there is now "issue"

**Comment by variemai** [comment]
> @variemai ugh, there is now "issue"
> You can try `CONFIGURE_OPTS="-Dwith_xnvctrl=disabled -Dwith_nvml=disabled" ./build.sh clean build install`

Thank you that worked.

**Comment by f3ck4r** [comment]
@variemai ugh, there is no "issue"
You can try `CONFIGURE_OPTS="-Dwith_xnvctrl=disabled -Dwith_nvml=disabled" ./build.sh clean build install`

meson.build:1:0: ERROR: Compiler gcc -m32 can not compile programs.

**Comment by jackun** [comment]
In fcefc07966d1373cd56fa940e9e8022d6e7878a6
