### ISSUE TITLE
It's not showing up in Minecraft

### ISSUE THREAD

**Issue by tsndr** [flightlessmango/MangoHud#274]
I really like MangoHud, but for some reason it's not showing up in Minecraft (it works in all other games I've tested). I can't find a solution anywhere. What do I need to do to get it to work?

<details>
<summary><code>~/.config/MangoHud/MangoHud.conf</code></summary>

```
fps_limit=60
vsync=3
gl_vsync=1
cpu_stats
cpu_temp
gpu_stats
gpu_temp
gpu_core_clock
gpu_mem_clock
gpu_power
vulkan_driver
vram
ram
frame_timing=0
font_size=24
position=top-left
toggle_hud=Shift_R+F12
toggle_logging=Shift_L+F2
output_file=/home/tobi/mangohud_log_
```

</details>

<details>
<summary>System</summary>

```
OS: Arch Linux x86_64
Kernel: 5.7.7-arch1-1
Shell: bash 5.0.17
Resolution: 5120x2880
DE: Cinnamon
WM: Mutter (Muffin)
WM Theme: Adapta-Nokto
Theme: Adapta-Nokto [GTK2/3]
Icons: Papirus-Dark [GTK2/3]
Terminal: gnome-terminal
CPU: Intel i9-9900KS (16) @ 5.000GHz
GPU: NVIDIA GeForce RTX 2080 Ti Rev. A
Memory: 1872MiB / 15921MiB
```

</details>

**Comment by jackun** [comment]
From README.md

> OpenGL games may also need dlsym hooking. Add MANGOHUD_DLSYM=1 to your command like MANGOHUD_DLSYM=1 mangohud %command% for Steam.

But minecraft launcher may crash with some libstdc++ incompatibilities so you can try something like https://gitlab.com/JakobDev/minecraft-launcher-lib

**Comment by tsndr** [comment]
Thank you for the quick reply, I was able to get it to work using this command: `MANGOHUD_DLSYM=1 mangohud minecraft-launcher`. But is it possible to set DLSYM in the `~/.config/MangoHud/MangoHud.conf` file?

**Comment by jackun** [comment]
It sets [LD_PRELOAD](https://blog.fpmurphy.com/2012/09/all-about-ld_preload.html) which has to be done before anything else but `mangohud` script itself might be made aware to read some kind of conf file with presets.
