### ISSUE TITLE
GPU usage always 0% with AMD GPU

### ISSUE THREAD

**Issue by Tooniis** [flightlessmango/MangoHud#278]
Arch Linux, `mangohud 0.4.1-1`
AMD Radeon R5 M330, `amdgpu` kernel module, `mesa 20.1.3-1`

GPU usage always shows 0%. `radeontop` does work well so I think the issue is in mangohud.

**Comment by flightlessmango** [comment]
#233

**Comment by azrabrijer** [comment]
> #233 older amd cards and APU's do not work

this needs to be fixed ! I have the same problem!
