### ISSUE TITLE
MANGOHUD: Failed to open 64bit libXNVCtrl.so.0: libXNVCtrl.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by barfin** [flightlessmango/MangoHud#279]
![image](https://user-images.githubusercontent.com/37030489/87305685-22b8f100-c52c-11ea-89cc-ff004db04fe5.png)
mangohud works fine but it puts this line in terminal multiple times
the only related package to this library that i could fine was "libxvnc"
i installed it from AUR (on arch) but it keeps showing this error

**Comment by ThrashMetalComputers** [comment]
I am running Manjaro 20.0.3 with Intel 3000 graphics using the i915 drivers and I am not getting that error. I installed MangoHud 0.4.1 from source.

**Comment by ThrashMetalComputers** [comment]
Checking the AUR package here: [https://aur.archlinux.org/packages/mangohud](url) user Anty0 wrote:

> Package is probably missing dependency - libxnvctrl

They had the same error as you posted above, so the AUR repository version has an issue with installing the "libxnvctrl" package at the moment.

**Comment by jackun** [comment]
https://github.com/flightlessmango/MangoHud/issues/226

**Comment by barfin** [comment]
> Checking the AUR package here: [https://aur.archlinux.org/packages/mangohud](url) user Anty0 wrote:
> 
> > Package is probably missing dependency - libxnvctrl
> 
> They had the same error as you posted above, so the AUR repository version has an issue with installing the "libxnvctrl" package at the moment.

looks like now it's fixed
