### ISSUE TITLE
Unable to use with MC

### ISSUE THREAD

**Issue by Aaronlikesmath** [flightlessmango/MangoHud#282]
Am trying to use the program with a standard install of Minecraft, but even though I found the path with PS and REALPATH (/usr/lib/jvm/java-11-openjdk-amd64/bin/java) It just gave me the output "Usage: java..."

**Comment by Leopard1907** [comment]
Try with something like `MANGOHUD_DLSYM=1 mangohud java -jar tlauncher.jar `

Obviously launcher part depends on which launcher you are using with this game.

**Comment by Aaronlikesmath** [comment]
So do add that to my parameters in my Launcher?
(I'm using the official launcher)

**Comment by KermitTheFrogerino** [comment]
> So do add that to my parameters in my Launcher?
> (I'm using the official launcher)
> Edit:
> Im getting that if I type in `Mangohud /usr/lib/jvm/java-11-openjdk-amd64/bin/java`

You can add it to the .desktop file in "/usr/share/applications/minecraft-launcher.desktop". Mine:

[Desktop Entry]
Type=Application
Version=1.0
Name=Minecraft Launcher
Comment=Official Minecraft Launcher
Exec=gamemoderun MANGOHUD_DLSYM=1 mangohud /opt/minecraft-launcher/minecraft-launcher
Path=/opt/minecraft-launcher/
Icon=minecraft-launcher
Terminal=false
Categories=Game;Application;
