### ISSUE TITLE
'-Dwith_xnvctrl=disabled' option does not work

### ISSUE THREAD

**Issue by r-a-sattarov** [flightlessmango/MangoHud#283]
./build.sh build -Dwith_xnvctrl=disabled

#Checking Dependencies
#Unable to find distro information!
#Attempting to build regardless
The Meson build system
Version: 0.51.1
Source dir: /home/user/MangoHud
Build dir: /home/user/MangoHud/build/meson64
Build type: native build
Project name: MangoHud
Project version: v0.4.0
C compiler for the build machine: cc (lcc 1.24.11 "lcc:1.24.11:May-26-2020:e2k-v4-linux")
C++ compiler for the build machine: c++ (lcc 1.24.11 "lcc:1.24.11:May-26-2020:e2k-v4-linux")
C compiler for the host machine: cc (lcc 1.24.11 "lcc:1.24.11:May-26-2020:e2k-v4-linux")
C++ compiler for the host machine: c++ (lcc 1.24.11 "lcc:1.24.11:May-26-2020:e2k-v4-linux")
Build machine cpu family: e2k
Build machine cpu: e8c
Program python3 found: YES (/usr/bin/python3)
Checking if "GCC atomic builtins" compiles: YES
Checking if "Supports timespec_get" compiles: YES
Checking for function "bswap32" : YES
Checking for function "bswap64" : YES
Checking for function "clz" : YES
Checking for function "clzll" : YES
Checking for function "ctz" : YES
Checking for function "expect" : YES
Checking for function "ffs" : YES
Checking for function "ffsll" : YES
Checking for function "popcount" : YES
Checking for function "popcountll" : YES
Checking for function "unreachable" : YES
Found pkg-config: /usr/bin/pkg-config (0.29)
Run-time dependency x11 found: YES 1.6.4
Dependency wayland-client skipped: feature with_wayland disabled
Dependency vulkan skipped: feature use_system_vulkan disabled
Run-time dependency threads found: YES
Run-time dependency dbus-1 found: YES 1.12.16
Compiler for C supports arguments -Werror=implicit-function-declaration: YES
Compiler for C supports arguments -Werror=missing-prototypes: YES
Compiler for C supports arguments -Werror=return-type: YES
Compiler for C supports arguments -Werror=incompatible-pointer-types: NO
Compiler for C supports arguments -fno-math-errno: YES
Compiler for C supports arguments -fno-trapping-math: YES
Compiler for C supports arguments -Qunused-arguments: NO
Compiler for C supports arguments -Wmissing-field-initializers: YES
Compiler for C supports arguments -Wformat-truncation: YES
Compiler for C supports arguments -fvisibility=hidden: YES
Compiler for C++ supports arguments -Werror=return-type: YES
Compiler for C++ supports arguments -fno-math-errno: YES
Compiler for C++ supports arguments -fno-trapping-math: YES
Compiler for C++ supports arguments -Qunused-arguments: NO
Compiler for C++ supports arguments -Wnon-virtual-dtor: YES
Compiler for C++ supports arguments -Wmissing-field-initializers: YES
Compiler for C++ supports arguments -Wformat-truncation: YES
Compiler for C supports arguments -Woverride-init: YES
Compiler for C supports arguments -Winitializer-overrides: NO
Compiler for C++ supports arguments -fvisibility=hidden: YES
Checking for function "dlopen" : NO
Library dl found: YES

|Executing subproject vulkan-headers method meson
|
|Project name: vulkan-headers
|Project version: 1.2.142
|C compiler for the build machine: cc (lcc 1.24.11 "lcc:1.24.11:May-26-2020:e2k-v4-linux")
|C compiler for the host machine: cc (lcc 1.24.11 "lcc:1.24.11:May-26-2020:e2k-v4-linux")
|Build targets in project: 1
|Subproject vulkan-headers finished.

Checking for size of "void*" : 8
Program glslangValidator found: YES (/usr/bin/glslangValidator)
Has header "NVCtrl/NVCtrl.h" : NO

src/meson.build:74:4: ERROR: Problem encountered: NVCtrl.h was not found. Disable with '-Dwith_xnvctrl=disabled' if gpu stats by XNVCtrl is not needed.

**Comment by jackun** [comment]
It's a bit arhaic at the moment, `CONFIGURE_OPTS=" -Dwith_xnvctrl=disabled" ./build.sh build`

**Comment by r-a-sattarov** [comment]
> It's a bit archaic at the moment, `CONFIGURE_OPTS=" -Dwith_xnvctrl=disabled" ./build.sh build`

Thanks a lot! This way works well.
