### ISSUE TITLE
FPS logging format is undocumented

### ISSUE THREAD

**Issue by baryluk** [flightlessmango/MangoHud#287]
Well, it looks like csv-like, which is easy to figure out, but some columns are obscure and not documented.

```
os,cpu,gpu,ram,kernel,driver
Debian GNU/Linux bullseye/sid,AMD Ryzen Threadripper 2950X 16-Core Processor,,131894576,5.6.0-1-amd64,4.6$ Mesa$ 20.1.2
88.3473,12,100,169
88.1573,12,100,100229
88.2238,12,100,200286
87.6796,13,100,300346
88.6116,13,100,400425
```

I am not sure what the 12 and 100 is? I am not sure what 88.3473 is exactly either.

Also I don't see any frame time information in the log. The 88.3473 looks like a frames per second maybe (but why it has 6 significant digits? This is silly, my random guess is that a default `%f` formatting was used, which is well, not a good idea), but is it just inverse of frame time, or there is some smoothing, averaging done before or not? Also the last column is unclear, is it time stamp from the start of logging in microseconds maybe? I am not sure. If it is is in microseconds, then it looks the consecutive lines looks to be spaced every 100ms, which would suggest the fps columns (if it is fps column), is already some kind of inverse of total (average), or average of inverse, or some smoothing was done in general. It suggests it is useless for more advanced analysis (like histograms, for jitter and spike detection, or for precise benchmark comparisons).

It would be nice for the log file to be documented, and what each number actually is exactly.

If my above deductions are correct, it would be also helfpul for the option to turn per-frame logging, that is output frame time of every frame, and also annotate extra things in the file, like absolute timestamp (seconds science epoch with microseconds, i.e. in the header), and maybe other stuff that mangohud is already measuring (vram, cpu and gpu temperature, etc).

**Comment by flightlessmango** [comment]
There has already been some progress on this in develop branch, it's documented in the log file what each column is for
https://github.com/flightlessmango/MangoHud/blob/5ce6bcb79cb0dd1de41c79fcfa8a410d0dde645e/src/logging.cpp#L62

Per frame logging also exists in develop branch by setting the `log_interval` to 0, it defaults to 100ms.
However per frame logging won't work very well with the flightlessmango website, a single log probably works but multiple might get messy

**Comment by baryluk** [comment]
This appears still not be fixed.

The log format is not documented.

**Comment by flightlessmango** [comment]
![image](https://user-images.githubusercontent.com/42713625/100423522-67cd6200-308c-11eb-8019-f518a5d47556.png)
I think it's been fixed at least somewhat, are you using `develop` branch ?

**Comment by baryluk** [comment]
The csv header is a nice thing. But it is unclear what units the `gpu_vram_used` ,`ram_used` and elapsed are.

I am not sure if vram and ram are in '%' or in MiB for example.

For the `elapsed` I assume it is in microseconds. But that is just a guess.

**Comment by baryluk** [comment]
Hmm. I think it is actually in nanoseconds.

I am pretty sure it was microseconds before!

Kind  of seems documenting the format might be a valid concern then.

**Comment by baryluk** [comment]
I think I will do a digging, and add a section at the bottom of README about format and units.

**Comment by flightlessmango** [comment]
Yes it's in nanoseconds
https://github.com/flightlessmango/MangoHud/blob/509fc72daae6c388390e99fb37f185f7129419ec/src/logging.cpp#L77
