### ISSUE TITLE
Beyond a Steel Sky (Steam native vulkan) crashes when MangoHUD is invoked.

### ISSUE THREAD

**Issue by lavadrop** [flightlessmango/MangoHud#289]
Just like the title says.
Tested with both native runtime and non native. HUD works if ran with Proton.

Here's a brief log:

Starting app 1146310
>>> Adding process 41393 for game ID 1146310
GameAction [AppID 1146310, ActionID 6] : LaunchApp changed task to WaitingGameWindow with ""
ERROR: ld.so: object '/home/lavadrop/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
GameAction [AppID 1146310, ActionID 6] : LaunchApp changed task to Completed with ""
ERROR: ld.so: object '/home/lavadrop/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/lavadrop/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/lavadrop/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 41397 for game ID 1146310
>>> Adding process 41398 for game ID 1146310
>>> Adding process 41399 for game ID 1146310
>>> Adding process 41400 for game ID 1146310
>>> Adding process 41401 for game ID 1146310
4.24.3-11590370+++UE4.24-Rev 518 0
Disabling core dumps.
MANGOHUD: Failed to open 64bit libnvidia-ml.so.1: libnvidia-ml.so.1: cannot open shared object file: No such file or directory
WARNING: Experimental compiler backend enabled. Here be dragons! Incorrect rendering, GPU hangs and/or resets are likely
WARNING: Experimental compiler backend enabled. Here be dragons! Incorrect rendering, GPU hangs and/or resets are likely
skipping config: /home/lavadrop/.local/share/Steam/steamapps/common/Beyond a Steel Sky/BASS2/Binaries/Linux/MangoHud.conf [ not found ]
skipping config: /home/lavadrop/.config/MangoHud/BASS2-Linux-Shipping.conf [ not found ]
parsing config: /home/lavadrop/.config/MangoHud/MangoHud.conf [ ok ]
Fossilize INFO: Overriding serialization path: "/home/lavadrop/.local/share/Steam/steamapps/shadercache/1146310/fozpipelinesv4/steamapprun_pipeline_cache".
Signal 11 caught.
Malloc Size=65538 LargeMemoryPoolOffset=65554 
CommonUnixCrashHandler: Signal=11
Malloc Size=65535 LargeMemoryPoolOffset=131119 
Malloc Size=127232 LargeMemoryPoolOffset=258368 
Engine crash handling finished; re-raising signal 11 for the default handler. Good bye.
/home/lavadrop/.local/share/Steam/steamapps/common/Beyond a Steel Sky/BASS2.sh: line 5: 41401 Segmentation fault      "$UE4_PROJECT_ROOT/BASS2/Binaries/Linux/BASS2-Linux-Shipping" BASS2 $@
Game removed: AppID 1146310 "", ProcID 41393 
Uploaded AppInterfaceStats to Steam
Exiting app 1146310

**Comment by MegWATTT** [comment]
Hello, I have the same issue with the same game.
It also affect all others Unreal Engine 4 samples I have. It may be a regression as I remember using Mangohud with these samples before.

Here is the log of one of these sample:

> [2020.08.10-01.46.14:254][  0]LogCore: === Critical error: ===
> Unhandled Exception: SIGSEGV: invalid attempt to read memory at address 0x0000000000000009
> 
> [2020.08.10-01.46.14:254][  0]LogCore: Fatal error!
> 
> 0x00007f3e8852e2e2 libstdc++.so.6!_ZNK10__cxxabiv120__si_class_type_info12__do_dyncastElNS_17__class_type_info10__sub_kindEPKS1_PKvS4_S6_RNS1_16__dyncast_resultE(+0x22)
> 0x0000000006c2929d UE4Game!UnknownFunction(0x6a2929c)
> 0x0000000006c41c0a UE4Game!UnknownFunction(0x6a41c09)
> 0x0000000006c41777 UE4Game!__gxx_personality_v0(+0xd6)
> 0x00007f3e88e380b6 libgcc_s.so.1!_Unwind_RaiseException(+0x165)
> 0x0000000006c2ad27 UE4Game!__cxa_throw(+0x66)
> 0x00007f3e88524d30 libstdc++.so.6!_ZSt19__throw_ios_failurePKci(+0xa4)
> 0x00007f3e8858d87d libstdc++.so.6!_ZNSt13basic_filebufIcSt11char_traitsIcEE9underflowEv(+0x43c)
> 0x00007f3e8854751a libstdc++.so.6!_ZSt7getlineIcSt11char_traitsIcESaIcEERSt13basic_istreamIT_T0_ES7_RNSt7__cxx1112basic_stringIS4_S5_T1_EES4_(+0x2c9)
> 0x00007f3e5c1505c0 libMangoHud.so!UnknownFunction(0x515bf)
> 0x00007f3e5c121d13 libMangoHud.so!UnknownFunction(0x22d12)
> 0x00007f3e5c128155 libMangoHud.so!UnknownFunction(0x29154)
> 0x00007f3e6087dca1 libvulkan.so.1!UnknownFunction(0x29ca0)
> 0x00007f3e6087e8ea libvulkan.so.1!UnknownFunction(0x2a8e9)
> 0x00007f3e60881963 libvulkan.so.1!vkCreateDevice(+0x42)
> 0x0000000004174aa8 UE4Game!UnknownFunction(0x3f74aa7)
> 0x000000000417902a UE4Game!UnknownFunction(0x3f79029)
> 0x00000000041b8b26 UE4Game!UnknownFunction(0x3fb8b25)
> 0x00000000041b6797 UE4Game!UnknownFunction(0x3fb6796)
> 0x00000000041b63eb UE4Game!UnknownFunction(0x3fb63ea)
> 0x00000000042b1b34 UE4Game!UnknownFunction(0x40b1b33)
> 0x00000000025a10fb UE4Game!UnknownFunction(0x23a10fa)
> 0x000000000259af5c UE4Game!UnknownFunction(0x239af5b)
> 0x0000000005d5619d UE4Game!UnknownFunction(0x5b5619c)
> 0x00007f3e88e6b0b3 libc.so.6!__libc_start_main(+0xf2)
> 0x000000000258e029 UE4Game!UnknownFunction(0x238e028)
> 
> [2020.08.10-01.46.14:316][  0]LogExit: Executing StaticShutdownAfterError
> Malloc Size=66398 LargeMemoryPoolOffset=325918 
> Engine crash handling finished; re-raising signal 11 for the default handler. Good bye.
> Segmentation fault (core dumped)

**Comment by MegWATTT** [comment]
It's indeed a regression.
I've bisected and the commit which cause the crash is 14f738e24d76001dce37837b3571299bcf98

```
commit a2cc14f738e24d76001dce37837b3571299bcf98
Author: FlightlessMango <flightlessmangoyt@gmail.com>
Date:   Sun May 10 01:36:09 2020 +0200

    Get deviceID

 src/nvctrl.cpp  | 13 ++++++++++++-
 src/nvml.cpp    |  5 +++++
 src/overlay.cpp |  4 +++-
 src/overlay.h   |  1 +
 4 files changed, 21 insertions(+), 2 deletions(-)
```

Unreal Engine demos and "Beyond a Steel Sky" no longer crashes when removing those 2 lines in src/overlay.cpp : 
```
         string device = read_line(path + "/device/device");
         deviceID = strtol(device.c_str(), NULL, 16);
```
At line 621 and 622.

**Comment by jackun** [comment]
And it won't be the last. It is the stoopid libstdc++ that suddenly doesn't know how to read `char`'s into a std::string.

**Comment by jackun** [comment]
Does _imbue_'ing make any difference?

[file_imbue.diff.txt](https://github.com/flightlessmango/MangoHud/files/5060552/file_imbue.diff.txt)

**Comment by MegWATTT** [comment]
Unfortunately, no. Still have a crash.

**Comment by flightlessmango** [comment]
is this still reproducible?

**Comment by MegWATTT** [comment]
Yes, still an issue with latest git revision (96bf79775ce68d94f78f926bc6bc6c9aaa6d5db2)
Do you need an UE4 demo to reproduce this? (I can upload one but it will take some time)

**Comment by jackun** [comment]
Try these built with Steam SDKs: 
[MangoHud-0.5.1.r101.g5511fab_soldier-0.20201022.1.tar.gz](https://github.com/flightlessmango/MangoHud/files/5541526/MangoHud-0.5.1.r101.g5511fab_soldier-0.20201022.1.tar.gz)
[MangoHud-0.5.1.r101.g5511fab_scout-0.20201104.0.tar.gz](https://github.com/flightlessmango/MangoHud/files/5541527/MangoHud-0.5.1.r101.g5511fab_scout-0.20201104.0.tar.gz)

Scout crashed with dbus for me right now though it worked before :thinking:

**Comment by lavadrop** [comment]
This is still an issue
