### ISSUE TITLE
Building for pinebook pro

### ISSUE THREAD

**Issue by e8johan** [flightlessmango/MangoHud#290]
This is not as much as a bug report, as a status report from trying to build MangoHud for a non-x86 target.

I'm trying to build MangoHud for the PineBook Pro (https://wiki.pine64.org/index.php/Pinebook_Pro) running the official Manjaro ARM build.

What I had to do to get through the build was to:

1. Add the distro "Manjaro-ARM" in the dependencies function of build.sh.
2. Realize that the packages `lib32-libglvnd` and `libxnvctrl` do not exist on Manjaro ARM.
3. Add the line `CONFIGURE_OPTS=-Dwith_xnvctrl=disabled` at the top of build.sh.
4. Remove the `-m32` argument to gcc and g++ in build.sh.
5. Remove references to `x86` and `x86_64` and replace them with `aarch64` in build.sh.
6. Realize that for some reason only `mangohud.aarch64` is built, but not `mangohud`.

Then, when trying to run it (with the godot editor, built from the 3.2.2-stable tag, as target - see https://godotengine.org/) I end up in the following:

```$ mangohud.aarch64 ./godot.x11.tools.64 
ERROR: ld.so: object 'libMangoHud.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
MANGOHUD: Failed to open 64bit libnvidia-ml.so.1: libnvidia-ml.so.1: cannot open shared object file: No such file or directory
Godot Engine v3.2.2.stable.custom_build.6a9fbafcb - https://godotengine.org
X Error of failed request:  GLXBadFBConfig
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  34 ()
  Serial number of failed request:  28
  Current serial number in output stream:  25
X Error of failed request:  GLXBadFBConfig
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  34 ()
  Serial number of failed request:  28
  Current serial number in output stream:  25
ERROR: initialize: Condition "ctxErrorOccurred || !p->glx_context" is true. Returned: ERR_UNCONFIGURED
   At: platform/x11/context_gl_x11.cpp:190.
skipping config: /home/e8johan/projects/godot/godot/bin/MangoHud.conf [ not found ]
skipping config: /home/e8johan/.config/MangoHud/godot.x11.tools.64.conf [ not found ]
skipping config: /home/e8johan/.config/MangoHud/MangoHud.conf [ not found ]
sh: glxinfo: command not found
MANGOHUD: Could not find cpu temp sensor location
MANGOHUD: Failed to load NVML
Version: 2.1 
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
MANGOHUD: Failed to open 64bit libnvidia-ml.so.1: libnvidia-ml.so.1: cannot open shared object file: No such file or directory
[1] linux-vdso.so.1(__kernel_rt_sigreturn+0) [0xffff8a89b578] (??:0)
-- END OF BACKTRACE --
Aborted (core dumped)```

Debugging this goes beyond what I can engage myself in at the moment, but I'm happy to do test runs and provide hardware access (via ssh) if that does help.

**Comment by akien-mga** [comment]
Does it work with a simpler OpenGL app, like `glxspheres` or `glxgears`?

**Comment by e8johan** [comment]
This is godot running without MangoHud:

```$ ./godot.x11.tools.64 
Godot Engine v3.2.2.stable.custom_build.6a9fbafcb - https://godotengine.org
X Error of failed request:  GLXBadFBConfig
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  34 ()
  Serial number of failed request:  28
  Current serial number in output stream:  25
X Error of failed request:  GLXBadFBConfig
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  34 ()
  Serial number of failed request:  28
  Current serial number in output stream:  25
ERROR: initialize: Condition "ctxErrorOccurred || !p->glx_context" is true. Returned: ERR_UNCONFIGURED
   At: platform/x11/context_gl_x11.cpp:190.
OpenGL ES 2.0 Renderer: Mali T860 (Panfrost)
OpenGL ES 2.0 Batching: ON```

This is glxgears running without MangoHud:

```$ glxgears
Running synchronized to the vertical refresh.  The framerate should be
approximately the same as the monitor refresh rate.
305 frames in 5.0 seconds = 60.926 FPS
XIO:  fatal IO error 62 (Timer expired) on X server ":0"
      after 625 requests (54 known processed) with 0 events remaining.```

This is glxgears running with MangoHud:

```$ mangohud.aarch64 glxgears
ERROR: ld.so: object 'libMangoHud.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
MANGOHUD: Failed to open 64bit libnvidia-ml.so.1: libnvidia-ml.so.1: cannot open shared object file: No such file or directory
skipping config: /usr/bin/MangoHud.conf [ not found ]
skipping config: /home/e8johan/.config/MangoHud/glxgears.conf [ not found ]
skipping config: /home/e8johan/.config/MangoHud/MangoHud.conf [ not found ]
MANGOHUD: Could not find cpu temp sensor location
MANGOHUD: Failed to load NVML
Version: 2.1 
Running synchronized to the vertical refresh.  The framerate should be
approximately the same as the monitor refresh rate.
ERROR: ImGui_ImplOpenGL3_CreateDeviceObjects: failed to compile vertex shader!
0:1(10): error: GLSL 1.30 is not supported. Supported versions are: 1.10, 1.20, and 1.00 ES

ERROR: ImGui_ImplOpenGL3_CreateDeviceObjects: failed to compile fragment shader!
0:1(10): error: GLSL 1.30 is not supported. Supported versions are: 1.10, 1.20, and 1.00 ES

ERROR: ImGui_ImplOpenGL3_CreateDeviceObjects: failed to link shader program! (with GLSL '#version 130
')
error: linking with uncompiled/unspecialized shadererror: linking with uncompiled/unspecialized shader
^C```

I get one frame from glxgears with MangoHud, then it freezes. The Ctrl+C still works, so I return to the console.

**Comment by flightlessmango** [comment]
We had someone with a similar issue that compiled on a switch console, there is a bug with the frame limit. Try develop branch instead it should be fixed there

**Comment by jackun** [comment]
>  error: GLSL 1.30 is not supported. Supported versions are: 1.10, 1.20, and 1.00 ES

Probably have to edit shader version from `#version 130` to `#version 120` too. The logic currently sets 1.30 as minimum though even 1.10 _should_ work.

**Comment by stephanlachnit** [comment]
>     6\. Realize that for some reason only `mangohud.aarch64` is built, but not `mangohud`.

At least that should be solved with [ld-preload-2](https://github.com/flightlessmango/MangoHud/tree/ld-preload-2) when building via Meson.

**Comment by e8johan** [comment]
I just moved to the `develop` branch, changed the shader to `#version 110`. Now glxgears work - see https://twitter.com/e8johan/status/1286312673433595904 .

Seems like we can move this issue to godot.

**Comment by e8johan** [comment]
> > ```
> > 6\. Realize that for some reason only `mangohud.aarch64` is built, but not `mangohud`.
> > ```
> 
> At least that should be solved with [ld-preload-2](https://github.com/flightlessmango/MangoHud/tree/ld-preload-2) when building via Meson.

I did not try this. Would this fix the json-files refering to the architecture as well?

**Comment by stephanlachnit** [comment]
> I did not try this. Would this fix the json-files refering to the architecture as well?

Yep. Instead of creating separate json files for amd64 and x86 it uses a dynamic path to look up the libraries depending on the binary you want to load it into. This will work on any cpu arch with any kind of program (on Debian with QEMU, it's even possible on an ARM machine to load the amd64 library if the program is amd64).

It's not merged yet but it should work.

**Comment by flightlessmango** [comment]
is this still an issue?
