### ISSUE TITLE
Feature request: prevent hud display from being drawn in child windows

### ISSUE THREAD

**Issue by ale-novo** [flightlessmango/MangoHud#292]
Hi, i absolutely love mango hud. Ive been looking for a fraps hud replacement for linux for years. additionally it supports vulkan. Its been a keeper.

I use X-Plane , a Opengl/Vulkan flight simulator.
I want to have Mangohud in the main window, which is working fine. 
However X-Plane has the ability to create child 3d "windows". Mainly to draw aircraft instruments and maps in separate windows/ monitors.
Mangohud is being drawn as well in these child windows, covering many of the important data.
I would like to have the ability of preventing Mangohud from being drawn in secondary or child windows, and keep it only in the main window.

thanks again for the work.

**Comment by jackun** [comment]
There might not be any solid way to know what is "main" window. If it is a literal X11 window then maybe some sort of blacklisting by some window parameter could be implemented but don't know.

**Comment by ale-novo** [comment]
What about a counter were mango hud is displayed on the first x11 window but not subsequent ones?
Let me know if there is any command i could run to find out more about these windows. Thanks

**Comment by flightlessmango** [comment]
output of ` wmctrl -l` could be interesting, while the game is running

**Comment by ale-novo** [comment]
sure, here with only one window:

`alejandro@Desktop:~$ wmctrl -l
0x01400006 -1 Desktop x-caja-desktop
0x0384f640  3 Desktop alejandro@Desktop: ~/video_postprocess
0x0385183b  3 Desktop alejandro@Desktop: ~/Videos/vuelo1/cam2
0x00c00007 -1 Desktop Top Panel
0x00c00017 -1 Desktop Bottom Panel
0x014f0413  3 Desktop cam2
0x03c00001  0 Desktop Ubuntu Manpage: wmctrl - interact with a EWMH/NetWM compatible X Window Manager. - Google Chrome
0x04600007  3 Desktop System Monitor
0x015134a2  0 Desktop vulkan-default
0x01513abd  0 Desktop X-Plane_11
0x0151c5fc  0 Desktop plugins
0x04c00024  0 Desktop XTerm
0x05200005  0     N/A X-System
0x03978332  0 Desktop alejandro@Desktop: ~
0x0397839d  0 Desktop alejandro@Desktop: ~
`
this is the one:

`
0x05200005  0     N/A X-System
`

2 windows:

`alejandro@Desktop:~$ wmctrl -l
0x01400006 -1 Desktop x-caja-desktop
0x0384f640  3 Desktop alejandro@Desktop: ~/video_postprocess
0x0385183b  3 Desktop alejandro@Desktop: ~/Videos/vuelo1/cam2
0x00c00007 -1 Desktop Top Panel
0x00c00017 -1 Desktop Bottom Panel
0x014f0413  3 Desktop cam2
0x03c00001  0 Desktop Ubuntu Manpage: wmctrl - interact with a EWMH/NetWM compatible X Window Manager. - Google Chrome
0x04600007  3 Desktop System Monitor
0x015134a2  0 Desktop vulkan-default
0x01513abd  0 Desktop X-Plane_11
0x0151c5fc  0 Desktop plugins
0x04c00024  0 Desktop XTerm
0x05200005  0     N/A X-System
0x03978332  0 Desktop alejandro@Desktop: ~
0x0397839d  0 Desktop alejandro@Desktop: ~
0x0520006a  0     N/A Captain PFD
`
`
0x05200005  0     N/A X-System
0x0520006a  0     N/A Captain PFD
`
2 other windows:

`alejandro@Desktop:~$ wmctrl -l
0x01400006 -1 Desktop x-caja-desktop
0x0384f640  3 Desktop alejandro@Desktop: ~/video_postprocess
0x0385183b  3 Desktop alejandro@Desktop: ~/Videos/vuelo1/cam2
0x00c00007 -1 Desktop Top Panel
0x00c00017 -1 Desktop Bottom Panel
0x014f0413  3 Desktop cam2
0x03c00001  0 Desktop Ubuntu Manpage: wmctrl - interact with a EWMH/NetWM compatible X Window Manager. - Google Chrome
0x04600007  3 Desktop System Monitor
0x015134a2  0 Desktop vulkan-default
0x01513abd  0 Desktop X-Plane_11
0x0151c5fc  0 Desktop plugins
0x04c00024  0 Desktop XTerm
0x05200005  0     N/A X-System
0x03978332  0 Desktop alejandro@Desktop: ~
0x0397839d  0 Desktop alejandro@Desktop: ~
0x0520006f  0     N/A X-System
`

`
0x05200005  0     N/A X-System
0x0520006f  0     N/A X-System
`

**Comment by flightlessmango** [comment]
Closing as I don't think there is a solution to this
