### ISSUE TITLE
Nvidia driver 450.56.02 broke forced mailbox vsync mode

### ISSUE THREAD

**Issue by aufkrawall** [flightlessmango/MangoHud#293]
Nvidia driver 450.56.02 includes a fix for fifo triple buffered vsync. But it seems in return, it broke mailbox vsync mode of mangohud (vsync=2), it makes every application freeze. I wonder if this can be fixed in mangohud (I've checked with latest git-master)?

**Comment by DadSchoorse** [comment]
Nvidia does not support mailbox, and never did before (only fifo, fifo_relaxed and immediate). So setting mangohud to use that is totally undefined behavior.

**Comment by aufkrawall** [comment]
Yeah, I suspected that way since the TearFree option you implemented in DXVK has no effect on Nvidia.
A bit shocking to see Nvidia refuse to implement this, afair it's even offered in the graphics menu of Doom Eternal and their Windows driver doesn't offer FastSync for Vulkan.

Still it would be nice if the hack in MangoHUD could be made working again, it can also be used to get lower latency vsync when setting backbuffer queue 2 in DXVK (caps at refresh rate then). I really "need" this functionality in Heroes of the Storm.

**Comment by flightlessmango** [comment]
It was never really a "hack", the effect it had before was probably never the intended effect since it's not supported in the driver. I think this is way beyond the scope of mangohud

**Comment by aufkrawall** [comment]
Alright. Though it indeed did work like TearFree with backbuffer queue length of 3, no tearing and unlocked fps. If it's out of scope, feel free to close. Thanks anyway. :)
