### ISSUE TITLE
More config loading locations

### ISSUE THREAD

**Issue by stephanlachnit** [flightlessmango/MangoHud#295]
Currently the example config file is not loaded. This means that users without a config will get three outputs of non-loaded config. I think this is a bit annoying. Instead it should show which config are loaded, that is more helpful IMHO.

I propose to install the example config file to `/usr/share/mangohud/` (instead of `/usr/share/doc/mangohud/`) and add this path as the first search paths for the configs. It's probably a good idea to uncomment the settings in there that would be equivalent if no config would be loaded.

A second path that might be interesting would be `/etc/mangohud/`, so that one can set a system wide configs.

I. e. all search paths in order:
```
/usr/share/mangohud/MangoHud.conf
/etc/mangohud/MangoHud.conf
/etc/mangohud/{application_name}.conf
/path/to/application/dir/MangoHud.conf
$XDG_CONFIG_HOME/MangoHud/MangoHud.conf
$XDG_CONFIG_HOME/MangoHud/{application_name}.conf
```

I'm also not a big fan of `/path/to/application/dir/MangoHud.conf`, since that alters the folder of the application which I'm not a huge fan of. With `/etc/mangohud/{application_name}.conf`, it also wouldn't be really necessary.

I will probably write a PR for this in the next couple of weeks, any feedback is appreciated.

/cc @flightlessmango @jackun

PS: regarding Windows support, Meson can replace `/etc` with `get_option('sysconfdir')`, so that shouldn't limit this.

**Comment by flightlessmango** [comment]
> since that alters the folder of the application

What do you mean by that exactly?

**Comment by stephanlachnit** [comment]
> > since that alters the folder of the application
> 
> What do you mean by that exactly?

For example, if I have SuperTuxKart installed via `apt`, the binary is `/usr/games/supertuxkart`.
But putting a config `/usr/games/` just doesn't feel right as it is designed for binaries only.

Btw I said I would do a PR soon, but I'm kinda short on time so I probably won't before chirstmas.

**Comment by jackun** [comment]
> For example, if I have SuperTuxKart installed via apt, the binary is /usr/games/supertuxkart.

That's not meant for that though. More for crap in $HOME like ~/some_game or wine games.

**Comment by stephanlachnit** [comment]
> > For example, if I have SuperTuxKart installed via apt, the binary is /usr/games/supertuxkart.
> 
> That's not meant for that though. More for stuff in $HOME like ~/some_game or wine games.

Sure, but it still alters the folder of the game. Anyway, not wanting to remove it, this is mostly about `/etc`.
