### ISSUE TITLE
MangoHud stopped displaying and even stopped Lutris games from opening.

### ISSUE THREAD

**Issue by ManofGod1000** [flightlessmango/MangoHud#299]
Now mind you, I want to start out by saying that I do not know exactly why this started happening. However, when I attempt to run anything from Lutris and MANGODHUD 1 environment variable setup, the program will not open. Also, when I attempt to open a Steam Game with mangohud %command%, MangoHud will initially display but then disappear after a few seconds.

I am running Ubuntu 20.04 with the latest Mesa drivers and ACO installed on an RX 5700. A week ago, everything was working fine but now, not so much. I do appreciate the program and figuring perhaps something was updated and broke MangoHud? Thanks.

**Comment by jackun** [comment]
Try this: 
[MangoHud-0.4.1.r89.g1f41652.tar.gz](https://github.com/flightlessmango/MangoHud/files/4990522/MangoHud-0.4.1.r89.g1f41652.tar.gz)

**Comment by ManofGod1000** [comment]
Thanks, I will give it a swing tonight and let you know what happens. 🙂

________________________________

**Comment by nutta-git** [comment]
#https://github.com/Frogging-Family/wine-tkg-git/issues/79
related?

**Comment by ManofGod1000** [comment]
I will try using a different version of proton and see what happens, both in Steam and Lutris. I do not believe I am using the TKG version but, I will look, just in case, thanks.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by nutta-git** [comment]
I was suggesting that the issue we are both facing maybe an upstream issue with mangohud, thus linking an issue that showing similar traits to your issue @ManofGod1000

**Comment by Archon97** [comment]
I have the same problem. It only affects wine games and native ones run fine. It's not just because of mangohud; running games with either mangohud command prefix or using fps limiter inside lutris system options prevent the games from launching.

**Comment by ManofGod1000** [comment]
Thanks. I have not put much time into in the last few days but, I am going to finally, leave that computer with Ubuntu 20.04 on Ubuntu. :)

________________________________

**Comment by mrazster** [comment]
> Try this:
> [MangoHud-0.4.1.r89.g1f41652.tar.gz](https://github.com/flightlessmango/MangoHud/files/4990522/MangoHud-0.4.1.r89.g1f41652.tar.gz)

I had similar problem as ManofGod1000 with games run on DXVK and one opengl. I´m on arch and tried both the git version and the "none git" versions in aur but none of them worked. Also when trying to use Goverlay on any of thoose, it failed, "Missing Mangohud". But when I built from your supplied tar file it all works in all games in both steam and lutris and with Goverlay.

So thnx a bunch, much appreciated !

**Comment by AbrarSL** [comment]
I have a similar issue. I'm running Linux Mint 20 with an RX 460 on kisak-mesa 20.1.5

Steam games work fine with MangoHud 0.5.1 whether they are native or running through Proton. Lutris (GoG Witcher 3) however doesn't start at all with MANGOHUD 1 set in the environment variable field. Game runs fine without MangoHud and also runs fine with DXVK_HUD. Reverting back to MH 0.4.1 fixed everything though so it does seem to be an issue specific to this new release.

**Comment by flightlessmango** [comment]
Is this still an issue?

**Comment by ettmetal** [comment]
This is still an issue for me, with latest MangoHUD + any 5.x wine via Lutris

Pop!_OS, NVIDIA 455

**Comment by jackun** [comment]
@ettmetal try that: https://github.com/flightlessmango/MangoHud/issues/394#issuecomment-727620263

**Comment by ettmetal** [comment]
Adding `NODEVICE_SELECT=1` allows the game to run, and shows MangoHUD. Can that be a symptom of another issue?

**Comment by jackun** [comment]
It's a ongoing issue with  [MESA device select layer](https://gitlab.freedesktop.org/mesa/mesa/-/issues/3801) and wine vulkan and so.

**Comment by Meister1593** [comment]
> It's an ongoing issue with [MESA device select layer](https://gitlab.freedesktop.org/mesa/mesa/-/issues/3801) and wine vulkan and so on.

Isn't NVIDIA uses something else than MESA?

**Comment by Leopard1907** [comment]
Afaik Mesa device selection layer is driver and vendor agnostic.

http://us.download.nvidia.com/XFree86/Linux-x86_64/455.38/README/primerenderoffload.html

What you said is this , which i use personally on my laptop. Never had that Mangohud issue tho.

Maybe it somehow mitigates the issue or i'm just lucky in that regard.

**Comment by bossbob88** [comment]
Hello everyone,

Linux mint 20 + 5.9.12 Kernel user here.

I still have this issue. If I enable mangohud for DXVK (GTA V & World War Z through epic store) or native Vulkan (recent War Thudner) games in lutris (as a command prefix), the game simply doesn't start. Mangohud works only if I add NODEVICE_SELECT=1 as an evironmental variable.

@ettmetal : thank you for the hint!

**Comment by patonoide** [comment]
Can confirm that adding NODEVICE_SELECT = 1 solves the problem. 
Running Wine lutris-5.21 DXVK 1.7.2L-5ca255d 
Ubuntu 20.10
Mesa 20.2.1
MangoHud 0.6.1

**Comment by Merrit** [comment]
Also confirm this is still an issue, and `NODEVICE_SELECT=1` resolves it.

Lutris / Steam / Wine / Proton same difference
Fresh install of Kubuntu 20.10
Kernel 5.8.0-33-generic
Mesa 20.3.2 - kisak-mesa
MangoHud 0.6.1
AMD 580 RX 8GB GPU
