### ISSUE TITLE
Consider using libXNVCtrl instead of NVML?

### ISSUE THREAD

**Issue by guihkx** [flightlessmango/MangoHud#3]
Hello,

I don't know if this happens only in older GPUs from NVIDIA, but MangoHud can't report GPU usage ~~properly~~ at all.

That's because [`nvmlDeviceGetUtilizationRates()`](https://github.com/flightlessmango/MangoHud/blob/dacfe111ccf27566af9ae459414f13c5b267737a/src/nvml.c#L15) currently returns `NVML_ERROR_NOT_SUPPORTED` on my GTX 660. It's also observable when using `nvidia-smi`:

```
$ nvidia-smi --query-gpu=utilization.gpu --format=csv,noheader
[Not Supported]
```

Which I find weird, because the [documentation](https://docs.nvidia.com/deploy/nvml-api/group__nvmlDeviceQueries.html#group__nvmlDeviceQueries_1g540824faa6cef45500e0d1dc2f50b321) for that function clearly states:

>**Description**
>Retrieves the current utilization rates for the device's major subsystems.
>
>FERMI_OR_NEWER%

Well, the GTX 660 has a Kepler-based architecture, which is the successor of Fermi, so it should be working...

Not everything is lost, though. The `nvidia-settings` utility is able to actually report GPU usage (percentage):

```
$ nvidia-settings -tq '[gpu:0]/GPUUtilization'
graphics=8, memory=4, video=0, PCIe=0
```

Of course it's not ideal for MangoHud to keep calling `nvidia-settings` to query these values. For that, there is a C library called libXNVCtrl, developed by NVIDIA:

https://github.com/NVIDIA/nvidia-settings/tree/master/src/libXNVCtrl

Sample codes are available as well:

https://github.com/NVIDIA/nvidia-settings/tree/master/samples

P.S.: I'm not entirely sure if libXNVCtrl could fully replace all the NVML bits you guys are using, but it's definitely worth taking a look.

Thanks!

**Comment by flightlessmango** [comment]
We're currently using nvml to get load and temperature, I also plan on adding vram. And all of those seem to be possible to get with libXNVCtrl. I don't see any real reason not to use this so we get some more compatibility with older Nvidia devices

**Comment by flightlessmango** [comment]
XNVCtrl is now in develop branch, if the gpu is unsupport by NVML it falls back to XNVCtrl. you can test it here [MangoHud-latest](https://flightlessmango.com/MangoHud-latest.tar.gz). It's gonna require the XNVctrl package on your respective distros.
`libxnvctrl-dev` on Ubuntu etc, `libxnvctrl` on arch

**Comment by CorruptCommit** [comment]
With 0.3.1, I was getting 0% GPU with my 700 series card.  With MangoHud-latest, I am getting correct GPU % information. :fireworks:

**Comment by NerosTie** [comment]
With my 740M, it works too! :)

![Screenshot_20200324_133529](https://user-images.githubusercontent.com/4572452/77426211-57196d80-6dd4-11ea-8857-32a6fe607f60.png)

But what "1.2.133" means?

**Comment by jackun** [comment]
> But what does "1.2.133" mean?
Driver's supported vulkan version

**Comment by NerosTie** [comment]
Thanks! Great idea!

**Comment by guihkx** [comment]
Did a quick test with vkcube, it works! Thank you.

Waiting for the next release :)
