### ISSUE TITLE
Issue with configuration files

### ISSUE THREAD

**Issue by Ahmed-E-86** [flightlessmango/MangoHud#30]
Putting `MangoHud.conf` inside the folder of the game, or using `MANGOHUD_CONFIG=` doesn't overwrite the configurations inside `~/.config/MangoHud/MangoHud.conf`

**Comment by ahmed-elsayed2017** [comment]
```
parsing config: /home/ahmed/.local/share/MangoHud/MangoHud.conf [ ok ]
parsing config: /home/ahmed/.config/MangoHud/MangoHud.conf [ ok ]
skipping config: /home/ahmed/.config/MangoHud/wine64-preloader.conf
skipping config: /home/ahmed/Downloads/wine2/bin/MangoHud.conf
skipping config: /home/ahmed/.config/MangoHud/wine-Control_DX11.conf
```

**Comment by ahmed-elsayed2017** [comment]
I opened that game with: MANGOHUD=1 MANGOHUD=1 MANGOHUD_CONFIG=time,cpu_temp,gpu_temp from the terminal, but that is how it deals with configurations:

parsing config: /home/ahmed/.local/share/MangoHud/MangoHud.conf [ ok ]
parsing config: /home/ahmed/.config/MangoHud/MangoHud.conf [ ok ]
skipping config: /home/ahmed/.config/MangoHud/wine64-preloader.conf
skipping config: /home/ahmed/Downloads/wine2/bin/MangoHud.conf
skipping config: /home/ahmed/.config/MangoHud/wine-Control_DX11.conf

Aparrantly to be able to use the name of the game I have to add wine- before the game as what appears in the last line:

skipping config: /home/ahmed/.config/MangoHud/wine-Control_DX11.conf

**Comment by ahmed-elsayed2017** [comment]
I think that I got what the issue is, MangoHud looks inside the folder of the custom WINE folder that I use to open the game with that is why it listed these configuration files.

**Comment by ahmed-elsayed2017** [comment]
Actually using `MANGOHUD=1 MANGOHUD=1 MANGOHUD_CONFIG=time,cpu_temp,gpu_temp wine ./Control_DX11.exe` didn't make any difference, MangoHud still looks for config files inside WINE installation folder `/opt/wine-staging/bin`

```
parsing config: /home/myname/.local/share/MangoHud/MangoHud.conf [ ok ]
parsing config: /home/myname/.config/MangoHud/MangoHud.conf [ ok ]
skipping config: /home/myname/.config/MangoHud/wine64-preloader.conf
skipping config: /opt/wine-staging/bin/MangoHud.conf
skipping config: /home/myname/.config/MangoHud/wine-Control_DX11.conf
```

**Comment by Ahmed-E-86** [comment]
Adding `Control_DX11.conf` inside `~/.config/MangoHud/` didn't work as I suspected it. Adding `wine-Control_DX11.conf` works, so that is the only way now to make a config file per a game.

$HOME/.config/MangoHud/**wine-**{application_name}.conf

**Comment by Ahmed-E-86** [comment]
**To sum up my issue:**

>     /path/to/application/dir/MangoHud.conf

That doesn't work.

>     $HOME/.config/MangoHud/{application_name}.conf

That works only if I add `wine- ` before the application_name.

> MANGOHUD_CONFIG environment varianble

That doesn't work either.

**Comment by jackun** [comment]
Don't isn't meant to work. Yet, anyway.

**Comment by Ahmed-E-86** [comment]
> That isn't meant to work. Yet, anyway. MANGOHUD_CONFIG should though...

No, it doesn't work. I don't know why you closed the issue when it is not fixed. Do you want me to stop commenting?!

**Comment by jackun** [comment]
What doesn't "work"?

**Comment by Ahmed-E-86** [comment]
> What doesn't "work"?

`MANGOHUD_CONFIG` doesn't work, MangoHud uses the configurations inside `~/.config/MangoHud/MangoHud.conf `

**Comment by Ahmed-E-86** [comment]
> What doesn't "work"? If you mean MANGOHUD_CONFIG doesnt override, then currently yeah. It is added together. Might be useful to make MANGOHUD_CONFIG override everything else.

Thanks. That will be useful.

**Comment by jackun** [comment]
Try this branch https://github.com/flightlessmango/MangoHud/tree/envvar

**Comment by Ahmed-E-86** [comment]
MANGOHUD_CONFIG works fine with That branch. Thanks.
