### ISSUE TITLE
MangoHud not working with Opus Magnum

### ISSUE THREAD

**Issue by at46** [flightlessmango/MangoHud#300]
Neither `mangohud %command%` nor `MANGOHUD_DLSYM=1 mangohud %command%` with steam nor `MANGOHUD_DLSYM=1 mangohud /mnt/spiele/steamapps/common/Opus\ Magnum/Lightning.bin.x86_64` is working for me. 
I get a lot of 

> MANGOHUD: Failed to open 64bit libnvidia-ml.so.1: libnvidia-ml.so.1: cannot open shared object file: No such file or directory

 and one 

> MANGOHUD: Failed to open 32bit libXNVCtrl.so.0: libXNVCtrl.so.0: wrong ELF class: ELFCLASS64

MangoHud version is 0.4.1 and my GPU is an amd rx 570. Galliumhud is working fine btw.

**Comment by flightlessmango** [comment]
The warnings have no impact. Is this the only OpenGL game that magnohud doesn't work with? does `glxgears` work with mangohud?

**Comment by at46** [comment]
Opus Magnum is the only OpenGL game MangoHud doesn't work with for me so far. `mangohud glxgears` works fine.

**Comment by jackun** [comment]
Launcher script overwrites LD_LIBRARY_PATH. Either comment it out for now or modify `mangohud` script so LD_PRELOAD contains absolute paths instead just `libMangoHud.so` etc.

But idk if my current build but labels' text is broken :confused:

**Comment by at46** [comment]
> Launcher script overwrites LD_LIBRARY_PATH. Either comment it out for now or modify `mangohud` script so LD_PRELOAD contains absolute paths instead of just `libMangoHud.so` etc.
> 
> ~But idk if my current build but labels' text is broken confused~ e: my build it seems

Thanks @jackun After commenting out `export LD_LIBRARY_PATH=$STEAM_LD_LIBRARY_PATH` in the start script MagnoHud shows up and everything seems to work fine.
