### ISSUE TITLE
Missing CPU temp

### ISSUE THREAD

**Issue by Daxot** [flightlessmango/MangoHud#301]
MangoHud doesn't display my CPU temperature

![MangoHud](https://user-images.githubusercontent.com/37917854/89088121-5e164500-d39f-11ea-8233-aa94c94a48ca.png)

Here cpu_temp is enabled in my MangoHud.conf
![MangoHud.conf](https://user-images.githubusercontent.com/37917854/89088141-7d14d700-d39f-11ea-88a2-ddf2f634362e.png)

And there is my lm_sensors
![lm_sensors](https://user-images.githubusercontent.com/37917854/89088161-93229780-d39f-11ea-8d61-ad4ff67e17d0.png)

**Comment by jackun** [comment]
Arch? Try mangohud-git if not already.

**Comment by Daxot** [comment]
Yeah, git version fixed this problem, thank you!
