### ISSUE TITLE
Arma 3/Proton 5.0 Cannot disable MangoHud

### ISSUE THREAD

**Issue by ShaunTheQuietGamer** [flightlessmango/MangoHud#303]
I enabled Mangohud through steam as a launch option. I am troubleshooting another issue with proton, but when i removing mangohud from the launch options, it continues to launch. i've even reinstalled arma, and it didn't do anything to help. the only way i've been able to disable Mangohud is uninstall it, and even then, after reinstalling, it comes back.

**Comment by flightlessmango** [comment]
Check if mangohud is enabled in `~/.profile` and check the proton config

**Comment by ShaunTheQuietGamer** [comment]
the contents of ~/.profile are `export MANGOHUD=1` and the launch options for proton 5.0 are empty.

**Comment by flightlessmango** [comment]
`export MANGOHUD=1` in `.profile` would start mangohud on any vulkan app automatically, so I assume that's the thing

**Comment by ShaunTheQuietGamer** [comment]
So should i change that to `export MANGOHUD=0` to stop that?

**Comment by flightlessmango** [comment]
or remove/comment it out. You will most likely need a reboot after that as well

**Comment by ShaunTheQuietGamer** [comment]
Yup, that fixed it. the strange thing is that i most certainly did not make that file, or line. it must have automatically been added somehow.

**Comment by flightlessmango** [comment]
I would guess that you pressed "global enable" at some point in GOverlay

**Comment by ShaunTheQuietGamer** [comment]
oooohhh, yeah. probably.
