### ISSUE TITLE
MangoHud blocks Steam Overlay when using NVIDIA PRIME Render Offload

### ISSUE THREAD

**Issue by solbero** [flightlessmango/MangoHud#304]
### Problem
I have a problem where MangoHud blocks the Steam Overlay when using Steam with NVIDIA Prime Render Offload. This results my controllers not working since Steam Overlay needs to run for Steam Input to manage the controllers

This is the command used to launch Steam which results in this behavior: `$ __NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia __VK_LAYER_NV_optimus=NVIDIA_only mangohud steam`. Setting `mangohud` as a command prefix in Lutris (as explained in the documentation) o in the same behavior as using the command above. The problem persist both when offloading the dGPU and when just using the iGPU.

MangoHud and Steam Overlay works as expected when added as a command prefix in Steam using `mangohud %command%`.

### Logs
* [Steam terminal output (PRIME Render Offload on dGPU)](https://gist.githubusercontent.com/solbero/23be79550abeaced60a962203c924437/raw/88e5a13de481f55528314ede950ecb3da0a72d34/gistfile1.txt)
* [Steam terminal output (PRIME Render Offload on iGPU)](https://gist.githubusercontent.com/solbero/ad97a950472f2d0abbe3c1e3e64362b0/raw/fcda95d383f1930546f8320613c5a5a7f3e47e8d/gistfile1.txt)

### System
* [System information reported by Steam (NVIDIA PRIME Offload on dGPU)](https://gist.githubusercontent.com/solbero/c7d601612d7692ace19af23b107944aa/raw/5e93fe172119703b3a0ca92e6c0bc253e2abbb99/gistfile1.txt)

### How to reproduce
1. Install latest NVIDIA driver
2. Enable NVIDIA (On-demand) in `nvidia-settings`
3. Install latest release of MangoHud
3. Launch Steam with  ` __NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia __VK_LAYER_NV_optimus=NVIDIA_only` and `mangohud` as a command prefixes
4. Start a game and try to load the Steam Overlay using `shift+tab`

**Comment by flightlessmango** [comment]
Easy solution is to not start steam with `mangohud`, beyond that I don't know if there is something we can do about it

**Comment by solbero** [comment]
The problem described above persists when running without NVIDIA PRIME Offload. I enabled NVIDIA (Performance Mode) in `nvidia-settings` which just enables the dGPU and disables the iGPU. I will try to disable the iGPU in BIOS and see if there is still a problem.

**Comment by flightlessmango** [comment]
Yes? I didn't say there was anything wrong with the prime offloading. The problem is start steam using `mangohud`

**Comment by solbero** [comment]
Sorry, I didn't see your first reply while typing up my previous reply. So it seems my options are to either adding `mangohud %command%` manually as a a command prefix in Steam or use the environment variable, but only get the hud for Vulkan/DXVK.

**Comment by solbero** [comment]
I consider this issue solved, then.
