### ISSUE TITLE
Custom MangoHud.conf ignored for DX9 games

### ISSUE THREAD

**Issue by LeJimster** [flightlessmango/MangoHud#305]
Whenever I try to load any of my DX9 games in Steam it ignores the custom settings I've saved in  `~/.config/MangoHud/MangoHud.conf` and just shows the default settings. 
If I try any DX11 game my custom settings work fine.

Running latest build 0.4.1

**Comment by flightlessmango** [comment]
Double check that you don't have `MANGOHUD_CONFIG` in launch options for the dx9 games, also what games are we talking about so I can try and replicate?

**Comment by LeJimster** [comment]
I tried 4 or 5 different titles, made sure to remove all other options and ran with
`mangohud %command%`
Alan Wake (not a good test case as it crashes a lot lately)
Bayonetta
Darksiders II
Deadlight
Left 4 Dead

When I switch to a DX11 title my custom config works...
Grim Dawn
Path of Exile
Prey

**Comment by LeJimster** [comment]
Ahhhhh....  OK, So it doesn't appear to be related to DX9/11.  But rather 32bit or 64bit.

Most DX9 games are 32bit..

Grim dawn has 3 versions, DX11 32bit, DX11 64bit and DX9 32bit...  The 32bit versions of the game aren't working with the custom config.  64bit no problem.

**Comment by LeJimster** [comment]
GAHHHH!! I'm sorry for wasting your time, I've been updating the 64bit mangohud package and totally forgot about the 32bit version I had installed is really old.  Not a bug, **user stupidty**!!
