### ISSUE TITLE
Error when trying to build locally

### ISSUE THREAD

**Issue by omegahack0** [flightlessmango/MangoHud#306]
This is the terminal output I got, when trying to build locally. I am on PopOS 20
Command: build 
ninja: Entering directory `build/meson32'
[1/36] Generating vk_enum_to_str with a custom command
FAILED: vk_enum_to_str.c vk_enum_to_str.h 
/home/m/anaconda3/bin/python3 ../../bin/gen_enum_to_str.py --xml ../../subprojects/Vulkan-Headers-1.2.142/registry/vk.xml --outdir /home/m/Repos/MangoHud/build/meson32
Traceback (most recent call last):
  File "../../bin/gen_enum_to_str.py", line 30, in <module>
    from mako.template import Template
ModuleNotFoundError: No module named 'mako'
[2/36] Generating version.h with a custom command
ninja: build stopped: subcommand failed.

**Comment by flightlessmango** [comment]
`ModuleNotFoundError: No module named 'mako'`
I assume that's the problem, it should get installed with pip3
try `sudo pip3 install mako` to see if it's already installed or it failed for some reason

**Comment by omegahack0** [comment]
I am getting a Requirement already Satisfied return when I tried to install mako.

**Comment by jackun** [comment]
Something messing with python paths? pip can install to system folders or to user's $HOME. Try just `pip3 install mako` and don't use sudo with build.sh

**Comment by flightlessmango** [comment]
Is this still an issue?

**Comment by arturbac** [comment]
I have same problem on Linux gentoo

`sh ./build.sh build -Dwith_xnvctrl=disabled
Command: build -Dwith_xnvctrl=disabled
ninja: Entering directory `build/meson32'
[3/40] Generating vk_enum_to_str with a custom command
FAILED: vk_enum_to_str.c vk_enum_to_str.h 
/usr/bin/python3 ../../bin/gen_enum_to_str.py --xml ../../subprojects/Vulkan-Headers-1.2.142/registry/vk.xml --outdir /home/artur/packages/MangoHud/build/meson32
Traceback (most recent call last):
  File "/home/artur/packages/MangoHud/build/meson32/../../bin/gen_enum_to_str.py", line 30, in <module>
    from mako.template import Template
ModuleNotFoundError: No module named 'mako'
[4/40] Generating version.h with a custom com`
`

`
pip3 install mako --user
Requirement already satisfied: mako in /usr/lib/python3.7/site-packages (1.1.3)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/lib/python3.7/site-packages (from mako) (1.1.1)
`

**Comment by jackun** [comment]
You check with pip3 but what version is `/usr/bin/python` itself?

**Comment by arturbac** [comment]
Thanks for advice ! SOLVED.

`
 # eselect python list
Available Python interpreters, in order of preference:
  [1]   python3.9
  [2]   python3.8 (fallback)
  [3]   python3.7 (fallback)
  [4]   python3.6 (fallback)
  [5]   python2.7 (fallback)
# eselect python set 3
# eselect python list
Available Python interpreters, in order of preference:
  [1]   python3.7
  [2]   python3.9
  [3]   python3.8 (fallback)
  [4]   python3.6 (fallback)
  [5]   python2.7 (fallback)
# python --version
Python 3.7.9
#./build.sh build -Dwith_xnvctrl=disabled

Command: build -Dwith_xnvctrl=disabled
ninja: Entering directory `build/meson32'
[37/38] Installing files.
Installing src/libMangoHud.so to /home/artur/packages/MangoHud/build/release/usr/lib/mangohud/lib32
Installing src/libMangoHud_dlsym.so to /home/artur/packages/MangoHud/build/release/usr/lib/mangohud/lib32
Installing /home/artur/packages/MangoHud/data/mangohud.1 to /home/artur/packages/MangoHud/build/release/usr/share/man/man1
Installing /home/artur/packages/MangoHud/build/meson32/src/MangoHud.json to /home/artur/packages/MangoHud/build/release/usr/share/vulkan/implicit_layer.d
Installing /home/artur/packages/MangoHud/build/meson32/src/mangohud to /home/artur/packages/MangoHud/build/release/usr/bin
Installing /home/artur/packages/MangoHud/src/../bin/MangoHud.conf to /home/artur/packages/MangoHud/build/release/usr/share/doc/mangohud
ninja: Entering directory `build/meson64'
[37/38] Installing files.
Installing src/libMangoHud.so to /home/artur/packages/MangoHud/build/release/usr/lib/mangohud/lib
Installing src/libMangoHud_dlsym.so to /home/artur/packages/MangoHud/build/release/usr/lib/mangohud/lib
Installing /home/artur/packages/MangoHud/data/mangohud.1 to /home/artur/packages/MangoHud/build/release/usr/share/man/man1
Installing /home/artur/packages/MangoHud/build/meson64/src/MangoHud.json to /home/artur/packages/MangoHud/build/release/usr/share/vulkan/implicit_layer.d
Installing /home/artur/packages/MangoHud/build/meson64/src/mangohud to /home/artur/packages/MangoHud/build/release/usr/bin
Installing /home/artur/packages/MangoHud/src/../bin/MangoHud.conf to /home/artur/packages/MangoHud/build/release/usr/share/doc/mangohud
`
