### ISSUE TITLE
Mangohud requires libnvidia-ml.so.1

### ISSUE THREAD

**Issue by vuurvoske** [flightlessmango/MangoHud#307]
Hi,

Since today i am using the Lutris-wine 5.7-8 runner. And mangohud (updated until august 4th). When i start the battle.net client (for world of warcraft) This combination gives me the following errors (see below). (This however, does not occur in lutris wine 5.7-5, where it works perfectly)

My graphics card is a Sapphire Pulse 5700XT
These are the wine packages i use:
```
dxvk-wine32-development/focal,now 1.5.4+ds1-2 i386 [installed,automatic]
dxvk-wine64-development/focal,now 1.5.4+ds1-2 amd64 [installed,automatic]
fonts-wine/focal,focal,now 5.0-3ubuntu1 all [installed,automatic]
libwine-development/focal,now 5.5-3ubuntu1 amd64 [installed,automatic]
libwine-development/focal,now 5.5-3ubuntu1 i386 [installed,automatic]
wine-devel-amd64/focal,now 5.14~focal amd64 [installed,automatic]
wine-devel-i386/focal,now 5.14~focal i386 [installed,automatic]
wine-devel/focal,now 5.14~focal amd64 [installed,automatic]
winehq-devel/focal,now 5.14~focal amd64 [installed]
winetricks/focal,focal,now 0.0+20200412-1 all [installed]
```

Lutris version: 0.5.7.1
Lutris-wine runner: 5.7-8

Vulkan / mesa drivers:
```
libegl-mesa0/focal,now 20.3~git2008110730.3d6e4a~oibaf~f amd64 [installed,automatic]
libgl1-mesa-dri/focal,now 20.3~git2008110730.3d6e4a~oibaf~f amd64 [installed]
libgl1-mesa-dri/focal,now 20.3~git2008110730.3d6e4a~oibaf~f i386 [installed]
libglapi-mesa/focal,now 20.3~git2008110730.3d6e4a~oibaf~f amd64 [installed]
libglapi-mesa/focal,now 20.3~git2008110730.3d6e4a~oibaf~f i386 [installed,automatic]
libglu1-mesa/focal,now 9.0.1-1build1 amd64 [installed,automatic]
libglu1-mesa/focal,now 9.0.1-1build1 i386 [installed,automatic]
libglx-mesa0/focal,now 20.3~git2008110730.3d6e4a~oibaf~f amd64 [installed,automatic]
libglx-mesa0/focal,now 20.3~git2008110730.3d6e4a~oibaf~f i386 [installed,automatic]
libosmesa6/focal,now 20.3~git2008110730.3d6e4a~oibaf~f amd64 [installed,automatic]
libosmesa6/focal,now 20.3~git2008110730.3d6e4a~oibaf~f i386 [installed,automatic]
mesa-utils/focal,now 8.4.0-1build1 amd64 [installed,automatic]
mesa-vulkan-drivers/focal,now 20.3~git2008110730.3d6e4a~oibaf~f amd64 [installed]
mesa-vulkan-drivers/focal,now 20.3~git2008110730.3d6e4a~oibaf~f i386 [installed]
```

```
AMDGPU drivers:
libdrm-amdgpu1/focal,now 2.4.102+git2007100630.669e10~oibaf~f amd64 [installed,automatic]
libdrm-amdgpu1/focal,now 2.4.102+git2007100630.669e10~oibaf~f i386 [installed,automatic]
xserver-xorg-video-amdgpu/focal,now 19.1.0-1 amd64 [installed,automatic]
```

Error messages:
```
MANGOHUD: Failed to open 64bit libnvidia-ml.so.1: libnvidia-ml.so.1: cannot open shared object file: No such file or directory
002e:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
002e:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
002e:err:winediag:nodrv_CreateWindow The explorer process failed to start.
002e:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFA, 0032FE9C
```
###
```
ntlm_auth: /home/vuurvoske/.local/share/lutris/runtime/lib64/libp11-kit.so.0: no version information available (required by /lib/x86_64-linux-gnu/libgnutls.so.30)
MANGOHUD: Failed to open 64bit libnvidia-ml.so.1: libnvidia-ml.so.1: cannot open shared object file: No such file or directory
0009:fixme:advapi:OpenEventLogW ((null),L"System") stub
0009:fixme:advapi:ReadEventLogA (0xcafe4242,0x00000009,0x00000000,0x8e8168,0x00010000,0x32eacc,0x32ead0) stub
0009:fixme:advapi:CloseEventLog (0xcafe4242) stub
ERROR: ld.so: object '/usr/$LIB/libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
MANGOHUD: Failed to open 32bit libnvidia-ml.so.1: libnvidia-ml.so.1: cannot open shared object file: No such file or directory
MANGOHUD: Failed to open 32bit libXNVCtrl.so.0: libXNVCtrl.so.0: cannot open shared object file: No such file or directory
```

Link to complete log @ pastebin: [https://pastebin.pl/view/37c260aa](url)

**Comment by flightlessmango** [comment]
The mangohud output is not an error, it doesn't do anything. What is the actual issues you're having? the game crashes if you use mangohud?

**Comment by vuurvoske** [comment]
The actual issue is that my game (world of warcraft won start). Also when toying around in lutris with settings regarding wine, sometimes it does work. However if i remove 'mangohud' from the command prefix. My game launches each time without issues.

**Comment by HanFox** [comment]
I've actually also had issues when the MangoHUD overlay has been enabled, except I'm using Proton-5.9-GE-5-ST with Green Hell. Someone else on the GE Discord also stated they had issues with MangoHUD and RAGE 2 on the same Proton.

I assume it's a change in GE that caused the issue quite possibly a patch that's been included that's causing MangoHUD to freak out? Maybe the same patch is in Lutris? Both projects changelogs don't really give much away in that regard.

**Comment by flightlessmango** [comment]
I was not able to replicate this with lutris-5.7-8, I am however on Nvidia if that could make a difference. @HanFox what GPU are you using?

**Comment by HanFox** [comment]
I'm using an AMD 5700 XT.

**Comment by flightlessmango** [comment]
Tested with with a Vega 56, still can't replicate sadly

**Comment by gort818** [comment]
I have had similar issues running Star Citizen with MangoHud and certain wine versions and lutris.. no one can seem to replicate it. The issue did not occur in earlier wine builds. The game will not start most of the time.. but once in a while it does work.. race condition? Unfortunately no error is written to output.

I am using a Vega 56.

So I tried running it without lutris and using 'export MANGOHUD=1' and it works 100% of the time.
Here is a bash script I made that works with all wine versions I have tested which were many.

https://gist.github.com/gort818/296456edfb7ad9a6ed578bc53c4392b4

**Comment by ananace** [comment]
I can replicate this 100% of the time using a default Lutris runner by just creating a wine prefix with it, and then trying to open the control panel.

I'm using a RX580 - with a Ryzen 9 3900X if that matters

```console
$ WINEPREFIX=/tmp/exampleprefix ~/.local/share/lutris/runners/wine/lutris-5.7-9-x86_64/bin/wineboot
...
wine: configuration in L"/tmp/exampleprefix" has been updated.
$ MANGOHUD=1 WINEPREFIX=/tmp/exampleprefix ~/.local/share/lutris/runners/wine/lutris-5.7-9-x86_64/bin/wine control
000b:fixme:winediag:__wine_start_process Wine TkG 5.7 is a testing version containing experimental patches.
000b:fixme:winediag:__wine_start_process Please don't report bugs about it on winehq.org and use https://github.com/Frogging-Family/wine-tkg-git/issues instead.
MANGOHUD: Failed to open 64bit libnvidia-ml.so.1: libnvidia-ml.so.1: cannot open shared object file: No such file or directory
0014:fixme:seh:dwarf_get_ptr unsupported encoding 9b
0014:fixme:seh:dwarf_get_ptr unsupported encoding 4d
0014:fixme:seh:dwarf_get_ptr unsupported encoding 0d
0014:fixme:seh:dwarf_get_ptr unsupported encoding d9
0014:fixme:seh:dwarf_get_ptr unsupported encoding 9b
... Repeat many hundred of times
0014:fixme:seh:dwarf_get_ptr unsupported encoding d9
0009:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0009:err:winediag:nodrv_CreateWindow The explorer process failed to start.
```

**Comment by gort818** [comment]
@ananace Can you try setting this env variable and report back `NODEVICE_SELECT=1`

**Comment by HanFox** [comment]
> @ananace Can you try setting this env variable and report back `NODEVICE_SELECT=1`

That let's mangohud work for me, and I've been trying it on and off with no luck since I last posted here.

**Comment by ananace** [comment]
And amusingly enough, while going through and doing further testing this, I also recompiled mangohud 0.5.1 as well as 0.4.1, and now I can no longer replicate the issue on either version...
Guessing I've upgraded my compiler since I built 0.5.1 last, and that must've done something?

**Comment by jackun** [comment]
Pretty sure there's something icky going on with libstdc++ making threads in wine to crash. Do you get "thread stuck for 60 secs" etc mesages?

**Comment by HanFox** [comment]
@jackun I've not noticed any timeout messages. Either when Steam is run via console or in the Proton log.

I'm also kind of confused now... since using NODEVICE_SELECT=1 once on Proton 5.0.10rc4 now all games that use that Proton work w/o the parameter. I didn't notice any Proton updates so that's pretty weird.

However, if I use Proton-5.9-GE-ST5 it always needs the parameter.

**Comment by Philippe734** [comment]
On my side, this issue came since I jumped mesa 20.0 to 20.3 that's why I'm sure there a link with mesa and proton.

**Comment by flightlessmango** [comment]
It seems like it only affect AMD card as well, so that's possible
