### ISSUE TITLE
GPU Usage Showing 100% When FPS Limit is On

### ISSUE THREAD

**Issue by titan-91** [flightlessmango/MangoHud#308]
OS: Linux Mint 20 x64
CPU: Ryzen 7 3700x stock
GPU: MSI Radeon RX 580 8GB
Motherboard: Asus ROG Strix GL10DH
Memory: 16GB PC4-2600
Linux version: 5.4.0-42-generic
Mesa version: 20.0.8
LLVM version: 10.0.0

When testing the FPS limit option in multiple games, the GPU usage shows very high. The actual GPU utilization is not high as my temperatures and fans do not ramp up as they would with actual high utilization. Tested in Planet Coaster and Crash Bandicoot N. Sane Trilogy. Happens at multiple resolutions and multiple limited frame rates at 60 or below.

Screenshots of both games with FPS limit turned off vs. turned on:

https://imgur.com/a/1ohABNc

**Comment by flightlessmango** [comment]
It would be good if you could verify that it's actually incorrect
