### ISSUE TITLE
Mangohud overwriting application's vsync setting (Vulkan)

### ISSUE THREAD

**Issue by warriormaster12** [flightlessmango/MangoHud#309]
So this is something that I noticed when I was writing my own Vulkan renderer. At some point I started to wonder, why on my Nvidia hardware the application always stuttered when ever I didn't use mangohud? 

Well it seems that when ever I turn on mangohud, it decides to change the vsync setting from locked to unlocked. If I for example use steam's own fps counter then I get locked 60fps as it should be.

Here's the project that I used to find the bug: https://github.com/warriormaster12/SpeedEngineVk

Edit: changing in Goverlay Fps limit from Off to unset fixes the issue but still I don't get the reason why off means that "let's overwrite application setting"

**Comment by flightlessmango** [comment]
And you haven't set the vsync option in mangohud?

**Comment by flightlessmango** [comment]
I'm not following what you're doing and what you're expecting to happen. You say you're unlocking the fps and vsync and then you're surprised that it's unlocked in the app? are you setting vsync in mangohud or in your app? what vsync exactly are you using?

**Comment by warriormaster12** [comment]
In my application VK_PRESENT_MODE is set to FIFO_KHR, which should mean vsync enabled right? When in mangohud I set fps limit to unlocked and Vulkan Vsync to unlocked(through front-end Goverlay ) and I run my application again, then it unlocks fps of the appliaction.

I expected unlocked to mean that the application renders frames as fast as possible as long as vsync is disabled inside the application.

**Comment by flightlessmango** [comment]
It sounds like your issue is with Goverlay instead, if you don't set vulkan vsync it automatically sets vsync to 1, overriding the applications vsync to off (IMMEDIATE_KHR)

**Comment by warriormaster12** [comment]
@flightlessmango but isn't Goverlay just a front-end for mangohud? So shouldn't this bug be in the mangohud itself since all of the changes that you do in Goverlay are saved to a mangohud config?

**Comment by flightlessmango** [comment]
MangoHud is working as intended, but Goverlay is not. Setting vsync to off in mangohud should override the vsync of the app, but Goverlay shouldn't set `vsync=1` by default

**Comment by warriormaster12** [comment]
Alright, I'll report this to Goverlay devs. Thanks for clarification :D
