### ISSUE TITLE
Change default libdir path

### ISSUE THREAD

**Issue by tim77** [flightlessmango/MangoHud#31]
Hello. We trying to package MangoHud for official Fedora repos and guidelines[1] requires `.so` name versioning for libraries but in same time since this is not shared library so maybe we can install it into `PREFIX/libdir/MangoHud/`?

[1] https://docs.fedoraproject.org/en-US/packaging-guidelines/#_downstream_so_name_versioning

**Comment by flightlessmango** [comment]
has this resolved it self at this point? I don't fully understand how to fix this

**Comment by tim77** [comment]
We solved [this](https://src.fedoraproject.org/rpms/mangohud/blob/master/f/mangohud.spec#_54), but in pretty ugly way. This is not canonical place for libs.

**Comment by gasinvein** [comment]
@flightlessmango In order to fully comply packaging guidelines, `libMangoHud.so` should be either
- versioned, e.g. the file named `libMangoHud.so.0.2.0`
- installed under a subdir of the libdir, e.g. `mangohud/libMangoHud.so`

**Comment by xvitaly** [comment]
> has this resolved it self at this point? I don't fully understand how to fix this

1. You project is not a typical shared library. This is a plugin for dxvk, so it cannot be stored in a default $LD_LIBRARY_PATH. You should move it into a subdirectory.
2. If you still want to install it into LIBDIR directly, you must add soname and soversion and track for ABI changes.

**Comment by flightlessmango** [comment]
Is this just fedora packaging guidelines or are these pretty universal? I don't fully understand why this needs intervention on my part, can't the packagers set libdir path themselves?

**Comment by xvitaly** [comment]
> Is this just fedora packaging guidelines or are these pretty universal?

For all GNU/Linux distributions. Your library exports nothing, so it cannot be stored in a default $LD_LIBRARY_PATH.

> I don't fully understand why this needs intervention on my part, can't the packagers set libdir path themselves?

Downstream should stay with upstream.

**Comment by flightlessmango** [comment]
@xvitaly Thank you for the clarification. If I understand correctly, lib32 and lib64 should have their own subdir of mangohud with the .so in it? and it does not need to be versioned?

**Comment by xvitaly** [comment]
> If I understand correctly, lib32 and lib64 should have their own subdir of mangohud with the .so in it?

Distributions with multilib support will automatically install it (eg. `/usr/lib64` for 64-bit and `/usr/lib` for 32-bit).

> and it does not need to be versioned?

If you will install plugin into a subdirectory, you don't need to add soname+soversion.

**Comment by flightlessmango** [comment]
a1eafc3403f10248352a6593856d3e5e548fe86d is this sufficient to solve this issue?

**Comment by xvitaly** [comment]
> is this sufficient to solve this issue?

mangohud.json now need to be fixed.

I suggest to use [Meson configure generator](https://mesonbuild.com/Configuration.html). It can automatically set correct installation path.

**Comment by flightlessmango** [comment]
So this has been rather complicated so far. At this point the .so files are installed into subdirs and I can configure the .json to point to the .so file. however this way it would require two different .json files, one for 32 and one for 64. Now I'm thinking if it would be easier to do versioning instead, but I don't quite understand what that entails.

**Comment by xvitaly** [comment]
> Now I'm thinking if it would be easier to do versioning instead, but I don't quite understand what that entails.

No, please don't.

**Comment by flightlessmango** [comment]
There are two problems that I don't know how to solve
` configuration : { 'libdir_mangohud' : get_option('libdir'), 'mangohud') }`
this sets the path to `lib/mangohud/libMangoHud.so` which isn't quite right, I could prepend `/usr/` but I don't know if that's a safe assumption to make. is there a better way to solve this?

second problem is creating two .json files, normally they would be named like `mangohud64.json` etc, but I don't know how to check if it's a 32 or 64bit session

**Comment by xvitaly** [comment]
You can check [this PR](https://github.com/DadSchoorse/vkBasalt/pull/62/files#diff-5e150ddb4a68170e60fb13f1050a1361R7) with correct fix.

**Comment by flightlessmango** [comment]
how does this look? 859948403282f50ac28c419162cc3048782761b8

**Comment by xvitaly** [comment]
> how does this look?

LGTM now. Thank you.

**Comment by flightlessmango** [comment]
would it be bad to use a ld.so.conf.d file?

**Comment by xvitaly** [comment]
> would it be bad to use a ld.so.conf.d file?

Yes. Using ld overrides is strictly forbidden by the most of GNU/Linux distributions.

**Comment by jackun** [comment]
Ok, so it configures jsons with libdirs and launcher script sets LD_LIBRARY_PATH for OpenGL? Looks good? Only that what to do with duplicate /usr/share/doc/mangohud folders?

**Comment by xvitaly** [comment]
> Ok, so it configures jsons with libdirs and launcher script sets LD_LIBRARY_PATH for OpenGL?

JSON file is enough. You don't need to override LD_LIBRARY_PATH at all.

> Only that what to do with duplicate /usr/share/doc/mangohud folders?

This is okay. Multiarch RPM package will automatically skip duplicates.

**Comment by jackun** [comment]
>  You don't need to override LD_LIBRARY_PATH at all.

Eh? Some fedora magic?

**Comment by xvitaly** [comment]
> Some fedora magic? I think OpenGL HUD needs it still.

Vulkan will get path to library from JSON file.

**Comment by jackun** [comment]
Yeah, I just think you missed that MangoHud (kind of) supports OpenGL too now :D

**Comment by xvitaly** [comment]
Now you tagged broken release. JSON file does not contains absolute path to library.

**Comment by flightlessmango** [comment]
for me it links to `prefix/lib/mangohud/libMangoHud.so`, is that not correct?

**Comment by xvitaly** [comment]
Sorry, LGTM now. Checked out incorrect tag.

**Comment by flightlessmango** [comment]
@tim77 These changes are in master now, is this issue resolved?

**Comment by tim77** [comment]
> @tim77 These changes are in master now, is this issue resolved?

Seems like we can close this now. Fixed in `0.3.0` version. Thank you!
