### ISSUE TITLE
Space engineers with plugin and mangohud

### ISSUE THREAD

**Issue by LordKael9** [flightlessmango/MangoHud#310]
Not an issue, but on Space Engineers I already have a launch option for a plugin,how can i set the option for mangohud????

**Comment by flightlessmango** [comment]
it depends on what your launch options already look like

**Comment by LordKael9** [comment]
-plugin "../Plugins/SEWorldGenPlugin.dll

**Comment by flightlessmango** [comment]
try `mangohud %command% -plugin "PATH/Plugins/SEWorldGenPlugin.dll"`

**Comment by LordKael9** [comment]
ty! that solved my probelm... 
i had tried :
-plugin "PATH/Plugins/SEWorldGenPlugin.dll" mangohud %command%
-plugin "PATH/Plugins/SEWorldGenPlugin.dll" -mangohud %command%
-mangohud %command%-plugin "PATH/Plugins/SEWorldGenPlugin.dll" 

but not your solution.... TY!
