### ISSUE TITLE
Support for Intel graphics

### ISSUE THREAD

**Issue by rhysperry111** [flightlessmango/MangoHud#311]
Hi, my laptop only has Intel UHD 630 graphics.

Are you thinking of supporting this?

**Comment by flightlessmango** [comment]
Does MangoHud not work with that IGPU? It would only be specific features that wouldn't be supported, but as a whole it should work

**Comment by rhysperry111** [comment]
MangoHud does work (runs) but it does not show any stats about the GPU

**Comment by flightlessmango** [comment]
We can't access that information without using root, so for now there is no viable solution for to support intel GPUs stats in MangoHud
