### ISSUE TITLE
Failed to open 64bit libnvidia-ml.so.1

### ISSUE THREAD

**Issue by pdelarosa2004** [flightlessmango/MangoHud#312]
I try to enable MangoHud and I have some Nvidia issues, but I'm with an AMD Vega 8 GPU (amdgpu drivers and I run Arch Linux):

$ mangohud /home/myuser/.tlauncher

MANGOHUD: Failed to open 64bit libnvidia-ml.so.1: libnvidia-ml.so.1: cannot open shared object file: No such file or directory

MANGOHUD: Failed to open 64bit libnvidia-ml.so.1: libnvidia-ml.so.1: cannot open shared object file: No such file or directory

env: «/home/myuser/.tlauncher»: Denied permission

**Comment by flightlessmango** [comment]
The message doesn't do anything, it's merely telling you that you don't have the nvidia library. which is fine since you're on AMD. I don't understand what you're trying to do exactly, is `.tlauncher` a folder or a program?

**Comment by pdelarosa2004** [comment]
TLauncher is a folder with a .jar game in it (Minecraft Java 8).

**Comment by flightlessmango** [comment]
I assume that normally you would start `tlauncher` to run minecraft and since it's opengl you probably need dlsym as well, so I think you want to do `MANGOHUD_DLSYM=1 mangohud tlauncher`

**Comment by pdelarosa2004** [comment]
$ MANGOHUD_DLSYM=1 mangohud /home/myuser/.tlauncher/TLauncher-2.69.jar

MANGOHUD: Failed to open 64bit libnvidia-ml.so.1: libnvidia-ml.so.1: cannot open shared object file: No such file or directory

MANGOHUD: Failed to open 64bit libnvidia-ml.so.1: libnvidia-ml.so.1: cannot open shared object file: No such file or directory

env: «/home/myuser/.tlauncher/TLauncher-2.69.jar»: Denied permission

**Comment by flightlessmango** [comment]
how do you normally start tlauncher?

**Comment by pdelarosa2004** [comment]
As a .desktop script, it's like a normal desktop app.

**Comment by flightlessmango** [comment]
you're trying to run a jar file without java `MANGOHUD_DLSYM=1 mangohud java -jar /home/myuser/.tlauncher/TLauncher-2.69.jar`

**Comment by pdelarosa2004** [comment]
It worked, thank you! Great job ; )
