### ISSUE TITLE
No GPU usage and no background

### ISSUE THREAD

**Issue by pdelarosa2004** [flightlessmango/MangoHud#313]
No GPU usage in game (Vega 8, latest amdgpu drivers on Arch) and no black/grey background.

![Screenshot_20200815_174315](https://user-images.githubusercontent.com/53822200/90316281-6cc53600-df21-11ea-909b-9de0d711d3b7.png)
![Screenshot_20200815_175053](https://user-images.githubusercontent.com/53822200/90316282-6d5dcc80-df21-11ea-8dbe-dd7caff6fe2a.png)
![Screenshot_20200815_175114](https://user-images.githubusercontent.com/53822200/90316283-6df66300-df21-11ea-859a-f696818eaf68.png)

**Comment by jackun** [comment]
APU Vegas don't seem to support gpu usage, at least through hwmon. Check `background_alpha` in  `~/.config/MangoHud/MangoHud.conf`, could be Goverlay bug.

**Comment by pdelarosa2004** [comment]
It was already enabled : (

![Screenshot_20200815_182016](https://user-images.githubusercontent.com/53822200/90316684-08f03c80-df24-11ea-81ca-aaf02188d2f7.png)

**Comment by jackun** [comment]
Ah, yeah, there's some kind of bug in opengl. I recall fixing it but apparently not.

**Comment by pdelarosa2004** [comment]
0k, just black and done for the moment. Thanks!

**Comment by jackun** [comment]
Oh right, it might be the floating point parsing error. If your HUD keeps displaying values with commas like "33,5%" instead "33.5%". Try copying `MangoHud.conf` to `java.conf` and setting `background_alpha=0,5` . Should be fixed in next release.

**Comment by jackun** [comment]
I think it was the floating point parsing error, closing for now.
