### ISSUE TITLE
Feature Request(?): Log on Startup

### ISSUE THREAD

**Issue by berglh** [flightlessmango/MangoHud#314]
I've played around with the logging options, I can't seem to find any documentation/option to enable logging on launch application. I'm looking to capture logging output using scripted benchmarks.

**Comment by flightlessmango** [comment]
I don't see a major problem with implementing that, I'm just curious what the full scope is. How do you plan to stop the log? currently the log is saved to memory so if the application closes before the log is stopped it's lost

**Comment by berglh** [comment]
@flightlessmango That is a great question, unfortunately I don't quite understand how mangohud stops upon the the child process terminating. Not sure if you can catch the sig term and then handle this during graceful shutdown (if logging on, then write out before exit). Excuse my naivety with how this works.

The other option would be buffered write outs to the log file at some frequency as a multiple of the stat collection interval. The main concern with writing the logging to file on the fly with a buffered write would be that if the application quit then and mangohud just shutdown as it does now, then you would lose the ability to write the benchmark_percentiles. Sorry I'm not much help with this.

I really just want a consistent way to be able to launch some application/game in benchmark mode and then capture the logging. Currently if I were to start a benchmark, there would be variations in the time of me toggling the logging on and off which would impact the overall averages.

I'm basically looking at generating some benchmarks to test various system configurations of my Ryzen 3900X system on Ubuntu 20.04. With stock, CPU and RAM tuned configurations as well as my alternate cooling configuration (AIO and GPU cooling configuration changes). Is mangohud the right tool for monitoring the frame rate data in this context?

I'm currently writing a rough and ready tool to collect other metrics using golang, so I'm going to learn an awful lot about this particular child spawned process stuff pretty soon.

**Comment by berglh** [comment]
To be honest, I'm not even sure if any of the applications will actually exit after I execute the benchmark mode anyway. So, this request may in fact be moot. I should really give an example you are able to test yourself before making a request like this.

**Comment by flightlessmango** [comment]
There is an option to set the amount of time it's logging for so it stops after X seconds, that might be sufficient for what you want to do. On current master MangoHud saves fps, gpu load, cpu load, cpu temp, gpu temp, gpu core clock, gpu mem clock, vram, ram and the time since start. Not all of these would show up on the website, at least not yet. But they are being logged if you were planning on parsing the data yourself. I also don't see a problem with adding more values if they are of interest.

Yes an example would be very useful

**Comment by berglh** [comment]
@flightlessmango I plan on passing the data myself using a Jupyter Notebook and a python kernel to produce some Plotly (js) plots I can ultimately embed in some blog post.

I actually like your idea of stopping the logging after a set time, if I have a predictable run time, I can set the logging time in MangoHud on launch.

So I just ran Rise of the Tomb Raider using the launch options: `mangohud %command% -benchmark` and then manually pressed the logging toggle as soon as the launch screen appeared. As soon as the benchmark finished, I toggled the logging off. Here is the output, looks like it ran for about 100 seconds.
[mangohud_log2020-08-16_10-52-55.log](https://github.com/flightlessmango/MangoHud/files/5079812/mangohud_log2020-08-16_10-52-55.log)

**Comment by berglh** [comment]
Hmm.. Just removed the previous version, built and installed the latest version from master, got the latest example config and modified it. Disabled upload to flighlessmango.com and it doesn't appear to be writing out to file I specified when I toggle the logging off.

**Comment by berglh** [comment]
berg@zen:~$ mangohud vkcube
skipping config: /usr/bin/MangoHud.conf [ not found ]
skipping config: /home/berg/.config/MangoHud/vkcube.conf [ not found ]
parsing config: /home/berg/.config/MangoHud/MangoHud.conf [ ok ]
Unknown option 'output_file'
MANGOHUD: Uploading is disabled (permit_upload = 0)

**Comment by flightlessmango** [comment]
Ah yes sorry we're in the middle of new release so it's not fully documented yet. `output_file` is replaced by `output_folder`. The files will be automatically named now after the programs executable

**Comment by berglh** [comment]
That is a much better solution, thanks for letting me know.

**Comment by flightlessmango** [comment]
Is this still of interest?

**Comment by berglh** [comment]
@flightlessmango I'm still keen to have this feature, I've been busy working on a logging tool for other system metrics in golang sorry for the slow response. The logging wasn't working for me, I'll need to look at the latest builds.

**Comment by berglh** [comment]
Latest build was logging to dir just fine :] I like the idea of using this option with the timeout feature to get a consistent run value.

**Comment by flightlessmango** [comment]
https://github.com/flightlessmango/MangoHud/commit/b085c56375ccc26a6130e2f11ecbb0c4446ec10f I just added this feature to develop. You set `autostart_log=5` to start it automatically after 5secs. setting it to 0 doesn't make it instant, it's just off
