### ISSUE TITLE
Apparently MangoHud dont take "wine/proton" individual config files

### ISSUE THREAD

**Issue by tonehrk** [flightlessmango/MangoHud#315]
In` $HOME/.config/MangoHud` I added config files for some games that I run through Proton Steam... but no file its seems to works. 
At first i thought that is a problem with ".exe" processes names, but (for ex.) Beyond Two Souls runs with "BeyondTwoSouls_" process name... and mangohud don't take its configuration file... works under "MangoHud.conf" config file.

It's something that does not happen with native games

### This screenshots shows "preview" mango hud should be ... show and the name of process
![ksnip_20200815-191234](https://user-images.githubusercontent.com/7997842/90323806-cb8fad00-df2b-11ea-8cd2-7b944f1cc55d.png)
##### Process name
![ksnip_20200815-191556](https://user-images.githubusercontent.com/7997842/90323800-c894bc80-df2b-11ea-8738-79ac6e9b99ea.png)

#### file BeyondTwoSouls_.conf exist
![ksnip_20200815-191333](https://user-images.githubusercontent.com/7997842/90323805-caf71680-df2b-11ea-9335-1a12793f8d52.png)
#### But config its MangoHud.conf not BeyondTwoSouls_.conf
![ksnip_20200815-191508](https://user-images.githubusercontent.com/7997842/90323801-c92d5300-df2b-11ea-949c-96290f4ed724.png)

### Native game
![ksnip_20200815-192619](https://user-images.githubusercontent.com/7997842/90323900-4a391a00-df2d-11ea-9de0-af097e856839.png)
![ksnip_20200815-192647](https://user-images.githubusercontent.com/7997842/90323899-49a08380-df2d-11ea-8c66-1a7ff9adb539.png)

I don't know if it only affects me, but I still report it

Have a nice day!

PD: "client.exe" and "GRIS.exe" don't work too

**Comment by flightlessmango** [comment]
I don't know why it's not documented in the readme but wine/proton games configs are `wine-application_name.conf`

**Comment by tonehrk** [comment]
Thank you!
Works fine. 
Just add that the ".exe" should not be included. 

from `BeyondTwoSouls_Steam.exe` to `wine-BeyondTwoSouls_Steam`

client.exe > wine-client
GRIS.exe > wine-GRIS

PD: KSysGuard dont show me the full name of Beyond Two Souls hahaha

Nice day!
