### ISSUE TITLE
MangoHud vanishes on Black Ice when in-game

### ISSUE THREAD

**Issue by LiamDawe** [flightlessmango/MangoHud#317]
Trying out MangoHud with the FPS game Black Ice, it works fine in the menu but as soon as you get in-game it vanishes.

Not sure what other details to supply, I run it with this:
`MANGOHUD_DLSYM=1 mangohud '/media/storage/SteamLibrary/steamapps/common/Black Ice/Black Ice.x86_64'`

Doesn't give an errors and does work fine in the menu.

**Comment by flightlessmango** [comment]
What API is it? OpenGL?

**Comment by LiamDawe** [comment]
Yup, OpenGL.

**Comment by jackun** [comment]
This makes it work for me https://github.com/flightlessmango/MangoHud/commit/ba6346110c5fd1396d5b3fa244fbc8b43be00d4e

**Comment by flightlessmango** [comment]
here is a test build [MangoHud-0.5.1.r1.gba63461.tar.gz](https://flightlessmango.com/MangoHud-0.5.1.r1.gba63461.tar.gz)

**Comment by LiamDawe** [comment]
Okay, what's the easiest way to run just that build for this to test?

**Comment by flightlessmango** [comment]
If you're using AUR you can just install `mangohud-git` to try it. If you normally install it with the release, install this one like a release and then you can install which ever version again
