### ISSUE TITLE
FR: Vsync Half Refresh Rate

### ISSUE THREAD

**Issue by tim77** [flightlessmango/MangoHud#32]
Would be nice to add `Vsync Half Refresh Rate` feature similar to NVIDIA's[1] `Adaptive Half Refresh Rate Vsync`. `libstrangle`[2] have this feaure as well (n - Sync to refresh rate / n).

- [1] http://i.imgur.com/DPTWVqA.png
  https://steamcommunity.com/app/234670/discussions/0/810939350992635448/
- [2] https://gitlab.com/torkel104/libstrangle#vsync

**Comment by jackun** [comment]
Seems to be an OpenGL thing. Maybe could be simulated by v-sync and limiting fps to half of refresh rate.

**Comment by flightlessmango** [comment]
This is implemented in OpenGL, I don't think there is a way to do it in Vulkan. Correct me if I'm wrong but I don't think this is solvable
