### ISSUE TITLE
gpu_name parameter show nothing

### ISSUE THREAD

**Issue by waquwex** [flightlessmango/MangoHud#320]
```
$ inxi -SMGxx
System:    Host: waquwex Kernel: 5.4.0-42-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 Desktop: Gnome 3.36.4 wm: gnome-shell 
           dm: GDM3 Distro: Ubuntu 20.04.1 LTS (Focal Fossa) 
Machine:   Type: Laptop System: Dell product: Inspiron 3580 v: N/A serial: <superuser/root required> Chassis: type: 10 
           serial: <superuser/root required> 
           Mobo: Dell model: 02G1KD v: A00 serial: <superuser/root required> UEFI: Dell v: 1.0.0 date: 11/19/2018 
Graphics:  Device-1: Intel UHD Graphics 620 vendor: Dell driver: i915 v: kernel bus ID: 00:02.0 chip ID: 8086:3ea0 
           Device-2: AMD Jet PRO [Radeon R5 M230 / R7 M260DX / Radeon 520 Mobile] vendor: Dell driver: amdgpu v: kernel 
           bus ID: 01:00.0 chip ID: 1002:6665 
           Display: x11 server: X.Org 1.20.8 driver: amdgpu compositor: gnome-shell resolution: 1920x1080~60Hz 
           OpenGL: renderer: Mesa Intel UHD Graphics 620 (WHL GT2) v: 4.6 Mesa 20.1.5 - kisak-mesa PPA direct render: Yes
```
I launch mangohud with this command: DRI_PRIME=1 mangohud glxgears

**Comment by jackun** [comment]
Does it not complain about not finding `pci.ids`?

**Comment by waquwex** [comment]
This is the terminal texts:`skipping config: /usr/bin/MangoHud.conf [ not found ]
skipping config: /home/waquwex/.config/MangoHud/glxgears.conf [ not found ]
parsing config: /home/waquwex/.config/MangoHud/MangoHud.conf [ ok ]
MANGOHUD: Uploading is disabled (permit_upload = 0)
Version: 4.6 
Running synchronized to the vertical refresh.  The framerate should be
approximately the same as the monitor refresh rate.
305 frames in 5.0 seconds = 60.953 FPS
301 frames in 5.0 seconds = 60.018 FPS
301 frames in 5.0 seconds = 60.014 FPS
301 frames in 5.0 seconds = 60.006 FPS
`

**Comment by Translator5** [comment]
For me GPU is not even listed.
My command: `MANGOHUD_DLSYM=1 mangohud DRI_PRIME=1 ./start.sh`

**Comment by Orochikyocr** [comment]
Tested these both GPUs, Saphire Radeon HD 7750 and AMD R4/R5 Mullins integrated with CPU AMD A8  and I also receive zero values in GPU clock, GPU load, and VRAM. Ubuntu 20.04.1, Mesa 20.1.5.

**Comment by flightlessmango** [comment]
@Translator5 that command is incorrect, you can't use a environment variable after the mangohud script. This is however unrelated to this issue, please open up a new issue if this is still a problem.
@Orochikyocr I think that GPU is too old and not supported, it's not fixable on our end.
