### ISSUE TITLE
power and temp limit feature?

### ISSUE THREAD

**Issue by min-xu-ai** [flightlessmango/MangoHud#322]
Hi, I am really happy that there is a linux tool like this. In afterburner, a very useful feature is that it displays power and temp limit of the GPU when it happens. Is that something can be done under linux with mangohud as well? Thanks a lot!

**Comment by flightlessmango** [comment]
> when it happens

What do you mean exactly? when it hits the limit?

**Comment by min-xu-ai** [comment]
yeah, it would display something like the following:

"no load" text when GPU has no load
"temp" text when GPU is hitting the temp limit and throttling
"power" text when GPU is hitting the power limit (I don't know what exactly does it mean though, maybe core freq maxed out?)
