### ISSUE TITLE
Mangohud version is always v0.4.0

### ISSUE THREAD

**Issue by xcom169** [flightlessmango/MangoHud#323]
Mangohud version is always v0.4.0 on the HUD however I have v0.5.1 from Manjaro repo. 
I tried to reinstall several times.

**Comment by danfe** [comment]
> Oops, meson's version was not updated, but it should be using git to generate it anyways.

Typically downstream packagers build software in pristine environment where Git is not available (or they might not have it installed at all), so the checked out sources should provide correct default version (as of the time of the tag).

Thanks for fixing it in 8b1feef.
