### ISSUE TITLE
Doesn't work in Native Vulkan,OpenGL and DirectxVK games

### ISSUE THREAD

**Issue by Toadfield** [flightlessmango/MangoHud#326]
I did changed my settings to the things I like in Goverlay and then did "MANGOHUD=1" in the launch options of System Shock (directxVK with steam proton),cs:go (with openGL) and Dota 2 (with Vulkan),I tried all of them out and if I press my hotkey to activate mangohud,then it doesn't work.

**Comment by flightlessmango** [comment]
verify that mangohud is actually installed by typing `mangohud` in a terminal, then try something simple like vkcube `mangohud vkcube`

**Comment by Toadfield** [comment]
If I do "mangohud" in the terminal,then "ERROR: No program supplied" and "Usage: mangohud <program>".
If I do "mangohud vkcube",then this shows up "env: ‘vkcube’: No such file or directory".
I tried it with both ways of installing,compiling it exactly like on your github page or installing the packages from the aur,on bith installations it behaves the same.
I use Manjaro.

**Comment by flightlessmango** [comment]
what exactly do you have in the launch option?

**Comment by Toadfield** [comment]
If you mean in the launch options for the steam games,I have "MANGOHUD=1" in all the 3 games that I mentioned.

**Comment by flightlessmango** [comment]
`MANGOHUD=1` is not sufficient and only works for vulkan, try `mangohud %command%`

**Comment by Toadfield** [comment]
thanks,that command works on all games.

**Comment by dagolinuxoid** [comment]
BTW you have to place other options like `-novid` *after* the `mongohud %command%` since putting it in front may cause the game to prevent from launching.
