### ISSUE TITLE
Is mangohud.x86 missing?

### ISSUE THREAD

**Issue by VortexAcherontic** [flightlessmango/MangoHud#328]
Hey there,

I noticed that in the latest 0.5.1 release and also in the compiled from source version mangohud.x86 isn't available anymore.
Was it removed on purpose and it is not required anymore or is there another way to get mangohud in 32bit OpenGL games now?

In the General Usage section I only found the old mangohud.x86 part for 32bit applications.

**Comment by jackun** [comment]
>  it is not required anymore

That's the plan but if it doesn't load with the _release_ package check that the 32bit arch "triplet" that the distro uses is symlinked to `lib32` in `/usr/lib/mangohud/[lib]`. There should be a bunch already though.

**Comment by flightlessmango** [comment]
You don't need to use `mangohud.x86` anymore as it's been baked into `mangohud`
