### ISSUE TITLE
Incorrect GPU usage

### ISSUE THREAD

**Issue by Kron4ek** [flightlessmango/MangoHud#329]
Hi,

MangoHud almost always shows 100% GPU usage, even when CPU bottlenecked and real GPU utilization is low, which can also be seen in power usage.

As shown in the screenshots, MangoHud shows 100% GPU usage even when DXVK shows 50% and power draw is not at max. When my GPU usage is max it consumes 24 W.

![kcd_1](https://user-images.githubusercontent.com/13851877/91281568-b1629400-e7a1-11ea-8a5a-f419963b42b4.jpg)
![kcd_2](https://user-images.githubusercontent.com/13851877/91281571-b293c100-e7a1-11ea-9d3e-2bbeab439926.jpg)
![kcd_3](https://user-images.githubusercontent.com/13851877/91281573-b32c5780-e7a1-11ea-9d3b-01a2004f74de.jpg)
![kcd_4](https://user-images.githubusercontent.com/13851877/91286773-4b2d3f80-e7a8-11ea-95b0-3485a8e5e49d.jpg)

Also, as you can see, it sometimes shows usage below 100%, but that's only for a half a second or so, then it again shows 100%.

OS: Arch Linux
Mesa 20.1.6
DXVK 1.7.1
GPU: AMD RX 560
Kernel: 5.4.59
MangoHud version: 0.5.1 (binaries from the releases page)

**Comment by jackun** [comment]
Then it's amdgpu issue. Run `watch -n1 cat /sys/class/hwmon/hwmon*/device/gpu_busy_percent `

**Comment by flightlessmango** [comment]
in both issues kernel 5.4 is used, probably worth trying a newer version

**Comment by Kron4ek** [comment]
I tried 5.8.3 kernel and the behavior is the same, but it's not a MangoHud issue indeed.

    watch -n1 cat /sys/class/hwmon/hwmon*/device/gpu_busy_percent

Shows random numbers from 0 to 100 (most of the time 100) regardless of real GPU usage.
