### ISSUE TITLE
Flatpak package (for using with Steam)

### ISSUE THREAD

**Issue by gasinvein** [flightlessmango/MangoHud#33]
First, thank you for creating this nice HUD!

While it's currently impossible to package a vulkan layer so that it would work with all flatpaks at once, MangoHud can be packaged as a flatpak extension for Steam flatpak app, for which it's probably the most useful.

I've submitted it here flathub/flathub#1371. If you'd like to (co)maintain the MangoHud flatpak (which is totally welcome), please let Flathub admins know (in that PR).

**Comment by flightlessmango** [comment]
I don't know that much about flatpak so I don't have a lot to add, but It sounds like a good thing so, cool! :+1:

**Comment by gasinvein** [comment]
MangoHud extension for Steam flatpak is now available from Flathub.
