### ISSUE TITLE
Benchmark Logs

### ISSUE THREAD

**Issue by Scarlet-Beard** [flightlessmango/MangoHud#331]
How's it going guys? MangoHud recently stopped outputting log files for my benchmarks. Below is my MangoHud.conf file and it's saved in /home/user/.config/MangoHud/

MangoHud Version: 0.5.1-3
Operating System: Manjaro Linux
KDE Plasma Version: 5.19.4
KDE Frameworks Version: 5.73.0
Qt Version: 5.15.0
Kernel Version: 5.8.1-3-MANJARO
OS Type: 64-bit

> ################### File Generated by GOverlay ###################
> #fps_limit=
> vsync=1
> gl_vsync=0
> cpu_stats
> cpu_temp
> core_load
> cpu_color=2e97cb
> cpu_text=CPU
> gpu_stats
> gpu_temp
> gpu_core_clock
> gpu_mem_clock
> gpu_color=2e9762
> gpu_text=GPU
> vram
> vram_color=ad64c1
> ram
> ram_color=c26693
> io_color=a491d3
> frame_timing=1
> frametime_color=00ff00
> background_alpha=0.4
> font_size=24
> background_color=020202
> position=top-left
> text_color=ffffff
> toggle_hud=Shift_R+F12
> toggle_logging=Shift_L+F2
> output_file=/home/user/Games/MangoHud Logs/
> media_player_name=spotify

**Comment by flightlessmango** [comment]
from 0.5.1 release notes
`output_file` is now replaced by `output_folder`, the files are automatically named after the programs executable

**Comment by Scarlet-Beard** [comment]
Thank you so much! Can't believe I missed that.
