### ISSUE TITLE
How to start MangoHud in Wine/PlayOnLinux

### ISSUE THREAD

**Issue by TobiasNeuhauser** [flightlessmango/MangoHud#332]
Hi, I like the idea of your program a lot. Unfortunately I have some problems to setup MangoHud 0.5.1 correctly. Hopefully you can help me? When I start a scroll shooter on Debian Testing with "MANGOHUD_DLSYM=1 mangohud chromium-bsu", it works. But I get the following error: 'libMangoHud_dlsym.so' (and 'libMangoHud.so') from LD_PRELOAD cannot be preloaded. Adding a "LD_PRELOAD=/usr/lib/mangohud/lib" to the command does not help.
Configuration file is also been ignored by the program. I copied /usr/share/doc/mangohud/MangoHud.conf.example to ~/.config/MangoHud/MangoHud.conf and /usr/games/, but although I disabled stuffs (#cpu_stats, #gpu_stats, #frame_timing) inside the configuration file, they are all still shown. Did I missed something?
I tried to run a wine game with MangoHud, therefore I was putting "MANGOHUD_DLSYM=1 mangohud" under "PlayOnLinux configuration" - "miscellaneous" - "command to exec before running the program", but MangoHud does not show up. Starting wine manually does not work either with for instance:
"LD_PRELOAD=/usr/lib/mangohud/lib/ MANGOHUD_DLSYM=1 mangohud WINEPREFIX=/home/user/.PlayOnLinux/wineprefix/Fallout3 wine-development /home/user/.PlayOnLinux/wineprefix/Fallout3/drive_c/Mod\ Organizer\ 1\ Legacy-6194-1-3-15/ModOrganizer.exe". Thank you.

**Comment by flightlessmango** [comment]
I don't know much about PlayOnLinux, but the wine command is not correct `mangohud` is not an env variable, but you have it inbetween env vars anyway. `mangohud` should go right before wine, which I guess in this case is `wine-development`
LD_PRELOAD is handled by the `mangohud` script so that's not needed
