### ISSUE TITLE
Can't see/run any game via Lutris if i use MangoHud

### ISSUE THREAD

**Issue by ObscureXwing** [flightlessmango/MangoHud#333]
hello, please help me solve one problem, have a nice day to those who read this text!

The problem is that the games and winecfg in Lutris seem to be trying to start (wine processes as well as .exe files of the game appear in the task manager, game processes do not consume more than 18-20 megabytes of RAM and no longer consume), but at the same time on the screen I see only the desktop and my running programs, I tried using the MANGOHUD env variable and set the key to "1", and also specify "mangohud" in the command prefix in Lutris, and none of this helps, at the same time without using MangoHud the games runs and works wonderfully! Even more interesting is that glxgears runs fine and works with MangoHud, but not work with games(simply games don't start)

my pc configuration :
CPU : Intel Xeon E5 2689
GPU : RX 480 4GB
RAM : 16 GB DDR3 1600 MHz
OS : Arch Linux
KERNEL : 5.8.3-xanmod2-2-xanmod
DRIVERS : Mesa 20.1.6-1 / xf86-video-amdgpu 19.1.0-2
OTHER : also used feral game mode and ACO shader compiler
System wine version is : wine-5.15 (Staging) / Lutris wine version is : lutris-5.7.8-x86_64

If use "Run in terminal" into Lutris and run the game (Metro Exodus i used as example) i got this : 
`/home/obscurexwing/.cache/lutris/run_in_term.sh: line 5: export: «=»: is not a valid identifier
lutris-wrapper: Metro Exodus
Running gamemoderun mangohud /home/obscurexwing/.local/share/lutris/runners/wine/lutris-5.7-8-x86_64/bin/wine /home/obscurexwing/.wine/drive_c/Games/Metro Exodus/MetroExodus.exe
Initial process has started with pid 14660
Game is considered started.
gamemodeauto: 
gamemodeauto: 
gamemodeauto: 
gamemodeauto: 
fsync: warning: a previous shm file /wine-26619e9-fsync was not properly removed
fsync: up and running.
WARNING: Experimental compiler backend enabled. Here be dragons! Incorrect rendering, GPU hangs and/or resets are likely`

then I opened the same file that was located here : "/home/obscurexwing/.cache/lutris/run_in_term.sh" and got the 5th line, this is just `export =""`

i tried to install MangoHud in every possible way, i used git to clone from :
1) [https://github.com/flightlessmango/MangoHud/blob/master/PKGBUILD](url)
3) [https://aur.archlinux.org/mangohud.git](url) and [https://aur.archlinux.org/mangohud-git.git](url)

I tried to build packages using build.sh, two versions, 0.5.1 and 0.4.1, no errors, everything is installed, the same with makepkg, but it does not work anywhere except glxgears, help me please make this work !

**Comment by flightlessmango** [comment]
#307 it's probably this issue, try using an older wine version and see if that fixes it

**Comment by ObscureXwing** [comment]
> #307 it's probably this issue, try using an older wine version and see if that fixes it

Changed wine version to lutris-5.6.5-x86_64 and now it work fine ! thank you very much for help
![Снимок экрана в 2020-08-28 03-34-07](https://user-images.githubusercontent.com/66114622/91492108-9593e680-e8a4-11ea-989a-861664510777.png)
