### ISSUE TITLE
Launching Steam with mangohud causes all web page contents to be black

### ISSUE THREAD

**Issue by siphomateke** [flightlessmango/MangoHud#334]
- **MangoHud Version**: 0.5.1
- **Steam Version**: Jul 31 2020, at 09:12:33
- **Distribution**: Kubuntu 20.04

Launching steam using the `mangohud` command (specifically `mangohud steam -tcp` in my case) causes all of Steam's web page contents to be black. I know now that you aren't really supposed to launch Steam like this but I didn't want to add `mangohud %command%` to all my games' launch options and it was working on version 0.4.1. I just thought I would report it in case it was indeed a bug to be handled or in case anybody else was trying to figure out why their Steam suddenly went black.

**Comment by flightlessmango** [comment]
I would say this is outside the intended use, at least for now
