### ISSUE TITLE
Screen tearing with full screen apps using gnome-3.34 using both intel-ddx and modesetting driver.

### ISSUE THREAD

**Issue by arabcian** [flightlessmango/MangoHud#335]
Today i realized when i run a fullscreen opengl game while vsync on i get screen tearing even tho ive enabled vsync and frame limiter from MangoHud.conf looks like gnome while unredirecting fullscreen windows. force disables vsync of both X config and MangoHud. I even tried enabling tearfree with intel-ddx driver without luck.

**Comment by flightlessmango** [comment]
I don't fully understand what you're saying but it doesn't sound like an issue with MangoHud

**Comment by arabcian** [comment]
I mean Mangohud's vsync doesnt work with fullscreen apps under gnome using i915

**Comment by flightlessmango** [comment]
I don't think it's a MangoHud issue, I would guess that it's the driver or wm that is incapable of changing vsync for whatever reason
