### ISSUE TITLE
Can I set Mangohud as a Environment Variable in Lutris,so I don't have to apply it in the steam game launch options?

### ISSUE THREAD

**Issue by Toadfield** [flightlessmango/MangoHud#336]
I set MANGOHUD=1 into the environment variables for steam in lutris like this:https://i.imgur.com/7GxjGcM.png
It didn't work and vkbasalt didn't work too,so is there any way to use it like this?

**Comment by NerosTie** [comment]
Can you try to add `MANGOHUD_DLSYM=1`?

**Comment by Toadfield** [comment]
thanks,I tried that,but that doesn't work either.

**Comment by flightlessmango** [comment]
You can't change the environment variables of a program that's already running. When you start a steam game in lutris with mangohud var it would basically run `MANGOHUD=1 steam --applaunch gameid`. Since steam is already running, the env var has no effect.

**Comment by Toadfield** [comment]
It works if I start the game while steam is not running,but is there no way to use the mangohud environment variable without exiting out of steam before?

**Comment by flightlessmango** [comment]
No, you can't. Someone like this might be in the right direction for what you want https://github.com/frostworx/steamtinkerlaunch

**Comment by Toadfield** [comment]
thanks,stl is cool but I wanted to get sure if it's impossible to do that directly in lutris,so I will use stl.
