### ISSUE TITLE
Mangohud crashes Crusader Kings III

### ISSUE THREAD

**Issue by tpurde** [flightlessmango/MangoHud#338]
There isn't an issue template, so I don't know what to attach here. Sorry.

Mangohud causes Crusader Kings III to crash on startup. I was able to play the game by removing `mangohud %command%` from the launch parameters.

**Comment by flightlessmango** [comment]
I assume you're talking about the Linux version? some general information like os/gpu/kernel/mangohud version could be useful

**Comment by tpurde** [comment]
> I assume you're talking about the Linux version? some general information like os/gpu/kernel/mangohud version could be useful

Yes, I am talking about the Linux version.

Distribution: Arch Linux
GPU: GeForce GTX 1050ti
CPU: Intel i5 7400 @ 3.00 GHz, turbo up to 3.50
Kernel: Linux 5.8.5-8 TK-Glitch (linux-tkg-pds)
Mangohud Version: 0.5.1-3

 I did some customizations with GOverlay, but I don't think that should effect anything.

**Comment by maritz** [comment]
For me it doesn't crash but also doesn't show up. Tried starting directly via command line, with MANGOHUD_DLSYM=1, through steam. Nothing. With Dota 2 mangohud works flawlessly for me, so in general it works on my system.

Distribution: Manjaro (Arch derivative)
GPU: Geforce 1070
Kernel: 5.8.6-1-MANJARO
GPU driver: Nvidia 440.100
Mangohud version: 0.5.1-3

**Comment by variemai** [comment]
> For me it doesn't crash but also doesn't show up. Tried starting directly via command line, with MANGOHUD_DLSYM=1, through steam. Nothing. With Dota 2 mangohud works flawlessly for me, so in general it works on my system.
> 
> Distribution: Manjaro (Arch derivative)
> GPU: Geforce 1070
> Kernel: 5.8.6-1-MANJARO
> GPU driver: Nvidia 440.100
> Mangohud version: 0.5.1-3

Exactly the same for me, it does not crash but it does not show up. 
Distribution: Gentoo Linux
GPU: AMD Radeon RX 5700XT
Kernel: 5.8.9
GPU Driver: Navi 10
 Mangohud version: 0.5.1-3

**Comment by jackun** [comment]
Try with default settings aka `MANGOHUD_CONFIG= mangohud %command%` . Even if it then boots, it probably doesn't render anything anyway for some reason but at least then the issue is maybe the same i'm seeing with *cough* GOG version * cough*: old friend std::check_facet nullptr assert.

**Comment by madIlama** [comment]
I can confirm can reproduce this
have been try all suggestion, ld preload mangohud lib, libstdc++, using dlsym, nothing shows up

Distribution: Arch Linux
GPU: AMD RX 460
Kernel: 5.6.10-xanmod
GPU Driver: amdgpu 4.6 Mesa 20.1.8 
Mangohud version: 0.5.1-3

**Comment by BigBadWeirdo** [comment]
I have also tried everything, and unfortunately I can't get the HUD to show up for the life of me.

**Comment by jackun** [comment]
It's a weird, haven't found yet what it needs. It renders the game as if it were using DirectX and then flips it vertically. Might be messing with MangoHud's vertex position/projection.

**Comment by jcstryker** [comment]
Distribution: Arch Linux
I only see mangohud on the launcher, disappears once the game loads.

Distribution: Arch Linux
GPU: Quadro RTX 5000
Kernel: 5.10.7
GPU Driver: NVIDIA 460.32.03
Mangohud version: 0.6.1

**Comment by wallena3** [comment]
> Distribution: Arch Linux
> I only see mangohud on the launcher, disappears once the game loads.
> 
> Distribution: Arch Linux
> GPU: Quadro RTX 5000
> Kernel: 5.10.7
> GPU Driver: NVIDIA 460.32.03
> Mangohud version: 0.6.1

Same, but I don't know it is mangohud's problem or Crusader Kings III's.

**Comment by jackun** [comment]
CK3 does a "draw-like-it-is-direct3d-and-flip-it-for-opengl" to second frame-buffer.
Dunno if it's good to blanket flip it back to 0 but adventurous people can try this patch:
```
diff --git a/src/gl/imgui_impl_opengl3.cpp b/src/gl/imgui_impl_opengl3.cpp
index beb85e7..5bc7a52 100644
--- a/src/gl/imgui_impl_opengl3.cpp
+++ b/src/gl/imgui_impl_opengl3.cpp
@@ -501,6 +501,8 @@ void    ImGui_ImplOpenGL3_NewFrame()
 static void ImGui_ImplOpenGL3_SetupRenderState(ImDrawData* draw_data, int fb_width, int fb_height, GLuint vertex_array_object)
 {
     // Setup render state: alpha-blending enabled, no face culling, no depth testing, scissor enabled, polygon fill
+    if (g_GlVersion >= 300)
+        glBindFramebuffer(GL_DRAW_FRAMEBUFFER, 0);
     glEnable(GL_BLEND);
     glBlendEquation(GL_FUNC_ADD);
     glBlendFuncSeparate(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA, GL_ONE, GL_ONE_MINUS_SRC_ALPHA);

```

**Comment by Archon97** [comment]
My issue is the same as everyone, that the HUD doesn't show up. This is the error it shows when launching through terminal, in case it help diagnose the problem:
MANGOHUD: Uploading is disabled (permit_upload = 0)
Version: 4.6

**Comment by jackun** [comment]
_Should_ be fixed already, just enable "workaround"

```
### (Re)bind given framebuffer before MangoHud gets drawn. Helps with Crusader Kings III
gl_bind_framebuffer=0
```

**Comment by Archon97** [comment]
> _Should_ be fixed already, just enable "workaround"
> 
> ```
> ### (Re)bind given framebuffer before MangoHud gets drawn. Helps with Crusader Kings III
> gl_bind_framebuffer=0
> ```

Yes, it works! Thank you so much.
