### ISSUE TITLE
I can't get it to work on TF2

### ISSUE THREAD

**Issue by bkdwt** [flightlessmango/MangoHud#339]
Hi. Mangohud is working using DXVK or Vulkan nativelly, but I can't make this work with TF2 (OpenGL). 

This is the TF2 run setup: `MANGOHUD_DLSYM=1 mangohud gamemoderun %command%`

The hud does not appear as I also do not receive any error messages. Thanks in advance! :+1: 

PS: I using OpenSUSE Tumbleweed.

**Comment by jackun** [comment]
Missing 32bit mangohud?

**Comment by bkdwt** [comment]
> Missing 32bit mangohud?

Uninstalled the compiled version, installed the release version but the problem persists.

**Comment by at46** [comment]
Maybe https://github.com/FeralInteractive/gamemode/issues/277

**Comment by FrozenPigs** [comment]
I got the same problem, using the release version and `MANGOHUD_DLSYM=1 mangohud %command%` or `mangohud --dlsym %command%`.

**Comment by flightlessmango** [comment]
I think this is the same issue as #340, what distribution are you guys using?

**Comment by FrozenPigs** [comment]
> I think this is the same issue as #340, what distribution are you guys using?

I'm on gentoo, and I believe TF2 runs natively in Linux, not through proton or any other compatibility layer.

**Comment by flightlessmango** [comment]
I believe the common thread here is a failure to find/load the 32bit mangohud libs

**Comment by Freeman310** [comment]
> I believe the common thread here is a failure to find/load the 32bit mangohud libs

mangohud 0.4.0 works great. why doesn't 0.5.1 and 0.5.0 work.?

**Comment by flightlessmango** [comment]
I *think* the problem stems from this commit d712d35aaf5d548f23cc1e1596646cbafc4004a3, it doesn't play well with some distros

**Comment by Freeman310** [comment]
> I _think_ the problem stems from this commit [d712d35](https://github.com/flightlessmango/MangoHud/commit/d712d35aaf5d548f23cc1e1596646cbafc4004a3), it doesn't play well with some distros

echo $LIB gives no results

**Comment by Freeman310** [comment]
how to overcome this problem?

**Comment by jackun** [comment]
@Freeman310 run `steam 2>&1 | tee -a ~/steam.log ` from terminal and try adding `LD_DEBUG=libs mangohud %command%` to launch options, launch TF, close it and attach ~/steam.log here

**Comment by Freeman310** [comment]
[mango.log](https://github.com/flightlessmango/MangoHud/files/5204934/mango.log)

**Comment by jackun** [comment]
@Freeman310 Run `ln -sv /usr/lib/mangohud/lib/i686 ../lib32` . Fedora/OpenSUSE expect that any `.../lib` folder contains 32bit libs.

**Comment by Freeman310** [comment]
> Run `ln -sv ../lib32 /usr/lib/mangohud/lib/i686` . Fedora/OpenSUSE expect that any `.../lib` folder contains 32bit libs.

the LD_PRELOAD error is gone. but mangohud never showed up.

**Comment by Freeman310** [comment]
MangoHud started working. but, for some reason, it does not work in all games in Wine. checked. Works in Watch_dogs, The Witcher 3, Kingdoms of Amalur: Re Rekoning. does not work in Far Cry 3. Splinter Cell Conviction. The most interesting thing is that I run wach_dogs and Far Cry 3 from the same place.

**Comment by Leopard1907** [comment]
@Freeman310 Games you listed as not working are 32 bit.

Do you have Mangohud installed as 64 bit only?

**Comment by Freeman310** [comment]
@Leopard1907 I have MangoHud x32 libraries. there is no mangohud.x86 script itself.

**Comment by jackun** [comment]
Ohio2 commented
> ## **So... i don't know how this fails to work... but it doesen't**
> OS: Arch Linux x86_64
> Host: Precision T1500 00
> Kernel: 5.8.13-zen1-2-zen
> Uptime: 3 hours, 1 min
> Packages: 1409 (pacman)
> Shell: zsh 5.8
> Resolution: 1920x1080
> DE: Plasma
> WM: KWin
> Theme: Breeze Dark [Plasma], Breeze-Dark [GTK2], Breeze [GTK3]
> Icons: breeze-dark [Plasma], breeze-dark [GTK2/3]
> Terminal: konsole
> Terminal Font: MesloLGS NF 9
> CPU: Intel i5 750 (4) @ 2.548GHz
> GPU: NVIDIA GeForce GTX 1050
> Memory: 2753MiB / 15968MiB
> 
> _Installed with yet another yogurt_ (YAY)

**Comment by flightlessmango** [comment]
Might be fixed in develop branch, re-open if still an issue

**Comment by kajlando** [comment]
Still an issue. Just turn on global enable and then you can turn it off.

**Comment by kajlando** [comment]
I still have this issue. Just turn on global enable.

**Comment by Zabijak05** [comment]
Anyone found a solution to this? Seems weird that tf2 isn't working, but cs:go another source game is lol...

**Comment by Toni500github** [comment]
soo, i'm having the same issue with geomtry dash running through wine, some others wine games, and with tf2 and Counter Strike: Source. only works on CS:GO as i saw
