### ISSUE TITLE
doesn't work with wine

### ISSUE THREAD

**Issue by Freeman310** [flightlessmango/MangoHud#340]
when adding a command to run with wine, I get this terminal output: 

`ERROR: ld.so: object 'libMangoHud.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.`

**Comment by flightlessmango** [comment]
The error doesn't affect anything, it's just saying that it's trying to load 64bit mangohud as well, but it doesn't apply in this specific case.
In what way doesn't it work? doesn't show up? crashes the app?

**Comment by Freeman310** [comment]
> The error doesn't affect anything, it's just saying that it's trying to load 64bit mangohud as well, but it doesn't apply in this specific case.
> In what way doesn't it work? doesn't show up? crashes the app?

the application works. however, MANGOHUD does not work. how to defeat this?

**Comment by flightlessmango** [comment]
Is mangohud 32bit installed?

**Comment by Freeman310** [comment]
> Is mangohud 32bit installed?

mangohud is installed according to the instructions in the README.md file

**Comment by flightlessmango** [comment]
Which one exactly? There are multiple ways of installing

**Comment by Freeman310** [comment]
installed in this way:
./build.sh build
./build.sh package
./build.sh install

**Comment by flightlessmango** [comment]
Does mangohud work with vkcube or glxgears?

**Comment by Freeman310** [comment]
> Does mangohud work with vkcube or glxgears?

its work
![Screenshot_20200908_223456](https://user-images.githubusercontent.com/49587058/92520071-b43e9980-f223-11ea-9d89-3a825e792406.png)
![Screenshot_20200908_223426](https://user-images.githubusercontent.com/49587058/92520073-b6085d00-f223-11ea-95e5-ab6f04236071.png)

**Comment by flightlessmango** [comment]
What game is it? If it's opengl or you're not using DXVK you may need to use dlsym. `mangohud --dlsym`

**Comment by Freeman310** [comment]
> What game is it? If it's opengl or you're not using DXVK you may need to use dlsym. `mangohud --dlsym`

Its FarCry 3. DXVK/Vulkan. previously everything worked fine. before reinstalling the system.

**Comment by flightlessmango** [comment]
What distribution are you using?

**Comment by Freeman310** [comment]
OpenSUSE Tumbleweed

**Comment by Freeman310** [comment]
mangohud 0.4.0 works. but the versions above do not work with wine.

**Comment by flightlessmango** [comment]
I'm fairly sure that it's not that it doesn't work with wine, the problem is that he can't find the 32bit mangohud libs. I'm gonna ping @jackun who understands this issue better

**Comment by Freeman310** [comment]
because version 0.4.0 works. and it works fine. i compiled mangohud under amd and it worked. but versions above 0.4.0 do not work with wine specifically. vkcube, glxgears, steam and native games work with mangohud. only wine does not work

**Comment by jackun** [comment]
Just rename the far cry exe so it always loads 64bit :P

**Comment by Freeman310** [comment]
> Just rename the far cry exe so it always loads 64bit :P

it didn't work.

**Comment by MR-Diamond** [comment]
Same here on Manjaro and wine-staging 5.18.
MangoHud works ok with vkcube and glxgears but not with wine (and DXVK 1.7.1):

`mangohud wine gta_sa.exe` results in

```
ERROR: ld.so: object 'libMangoHud.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libMangoHud.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.

```

**Comment by jackun** [comment]
@MR-Diamond  Do you have `lib32-mangohud[-git]` installed? Otherwise run `LD_DEBUG=libs mangohud wine gta_sa.exe 2>&1 | grep -i mangohud.so`

**Comment by MR-Diamond** [comment]
@jackun 
Yeah: I installed it now (still from AUR) and works as expected!
Thank you!

**Comment by flightlessmango** [comment]
Seems solved?
