### ISSUE TITLE
Please remove unused #include <sys/sysinfo.h> in src/overlay_params.cpp

### ISSUE THREAD

**Issue by danfe** [flightlessmango/MangoHud#343]
Since the `get_nprocs()` call was removed in 12ba4f9, the `#include <sys/sysinfo.h>` line should also be removed.  This is required to unbreak the build on FreeBSD.

To further elaborate, `get_nprocs()` is part of the non-standard GNU extentions and should not be used in portable code. Here's more correct, POSIX-friendly way to obtain the CPU information:
```
np = sysconf(_SC_NPROCESSORS_CONF);     /* processors configured */
np = sysconf(_SC_NPROCESSORS_ONLN);     /* processors available */
```

**Comment by jackun** [comment]
Should be in a6dc259ea4ca8c9b7ac13f6db1db0889a6cc082f

**Comment by danfe** [comment]
Awesome, thank you!
