### ISSUE TITLE
Is there a way to use mangohud for games that use their own api?

### ISSUE THREAD

**Issue by Toadfield** [flightlessmango/MangoHud#345]
I downloaded a game,MangoHud didn't work,so I looked on the site of the game,and if I looked correctly,then the game uses it's own api.
I'm pretty sure that on windows with msi afterburner or something it's possible to show fps on games with their own api,so I wonder if that's possible on MangoHud or if I need another program.

**Comment by flightlessmango** [comment]
What game are we talking about?

**Comment by Toadfield** [comment]
I mean Elderscrolls Daggerfall Unity.

**Comment by flightlessmango** [comment]
"API" doesn't only refer to Graphics APIs, It's not really a thing that people make their own graphics API for their game. There isn't anything technical stopping it from working on mangohud

**Comment by Toadfield** [comment]
that's strange,because if I set Mangohud=1 in the Lutris options for the game,then it doesn't work.

**Comment by flightlessmango** [comment]
`MANGOHUD=1` only works for vulkan. try setting `mangohud` in command prefix in lutris instead and if that doesn't work, add `MANGOHUD_DLSYM=1`

**Comment by Toadfield** [comment]
I tried both and it didn't work

**Comment by flightlessmango** [comment]
seems to work fine here. not using lutris tho, just downloaded manually
![image](https://user-images.githubusercontent.com/42713625/93177287-e1fb7500-f732-11ea-911e-62c2262241e2.png)

**Comment by Toadfield** [comment]
I tried it Mangohud with gmod because it's OpenGL,but it didn't work,so I assume that Mangohud doesn't work for all OpenGL for me,for some reason.
I did "MANGOHUD=1 MANGOHUD_DLSYM=1 %command%" in the launch options.

**Comment by flightlessmango** [comment]
As I stated before, don't use `MANGOHUD=1` as it only works with vulkan. try `mangohud %command%`.
There is also an ongoing issue where some distros can't find the 32bit libs, what distro are you on?

**Comment by Toadfield** [comment]
`mangohud %command%` doesn't work.
I use Manjaro.

**Comment by flightlessmango** [comment]
Launch options? weren't you using lutris for this?

**Comment by Toadfield** [comment]
Yes,I used Lutris for that game,I call that Environment Variable Tab in Lutris "Launch Options" for no reason.
Btw I tested "MANGOHUD_DLSYM=1 %command%" in gmod and it didn't work there.

**Comment by flightlessmango** [comment]
in lutris you need to add `mangohud` as a command prefix for opengl to work, not in in environment variables. When using the dlsym env var you also need mangohud, `MANGOHUD_DLSYM=1 mangohud %command%` for steam launch options. However if you want to use dlsym in lutris, you add `mangohud` as command prefix and add `MANGOHUD_DLSYM=1` in environment variables

**Comment by Toadfield** [comment]
That works
