### ISSUE TITLE
Is there a way to drastically reduce fontsize while maintaining legibility?

### ISSUE THREAD

**Issue by txtsd** [flightlessmango/MangoHud#346]
I'd like to be able to use pixel fonts if possible to minimize the size of the HUD, however pixel fonts don't look good at lower scales and font sizes. See screenshots for reference.

Even the default font at `font_scale=0.5` looks bad
![default-50](https://user-images.githubusercontent.com/768728/93479652-2f860680-f91a-11ea-99df-8175f6ece96a.png)
minecraft font at `font_scale=0.5`
![minecraft-50](https://user-images.githubusercontent.com/768728/93479656-30b73380-f91a-11ea-9efa-9cdf64d45ad1.png)
minecraft font at `font_scale=1`
![minecraft-100](https://user-images.githubusercontent.com/768728/93479659-314fca00-f91a-11ea-8066-1383dd4a2332.png)
PF Arma 5 font at `font_scale=0.5`
![pfarma50](https://user-images.githubusercontent.com/768728/93479664-31e86080-f91a-11ea-99d4-c78e054c65be.png)
PF Arma 5 font at `font_scale=1`
![pfarma100](https://user-images.githubusercontent.com/768728/93479668-3280f700-f91a-11ea-8f6c-8986cadb8fa0.png)

**Comment by flightlessmango** [comment]
Try using `font_size` instead of scale, default font_size is 24

**Comment by txtsd** [comment]
Looks like there's some anti-aliasing going on, and something is very wrong with the line heights.

`font_scale=1` and `font_size=10` PF Arma 5 font
![2020-09-17-194810_640x351_scrot](https://user-images.githubusercontent.com/768728/93483822-d8366500-f91e-11ea-9db9-56a0c2fb02ee.png)
`font_scale=1` and `font_size=10` Minecraft font
![2020-09-17-194820_640x351_scrot](https://user-images.githubusercontent.com/768728/93483827-d9679200-f91e-11ea-9c4e-2cc70e20acd4.png)
`font_scale=1` and `font_size=10` Default font
![2020-09-17-194831_640x351_scrot](https://user-images.githubusercontent.com/768728/93483830-da002880-f91e-11ea-809c-84bfcaede514.png)

**Comment by flightlessmango** [comment]
The problem is that the y cellpadding is a static value, I'm not sure how to make it scale well and maintain the current look
https://github.com/flightlessmango/MangoHud/blob/63b50abeded5099910f3a70df820266628d3fac6/src/vulkan.cpp#L2106

**Comment by txtsd** [comment]
How about 2 modes? One for the default look, and one for a single font size HUD whose cellpadding scales with the font.

**Comment by flightlessmango** [comment]
This should work better, pushed to develop branch
https://github.com/flightlessmango/MangoHud/blob/e25ffbafe0ea5faa1df968a2824e2f854f3085e5/src/vulkan.cpp#L2106

**Comment by txtsd** [comment]
The lineheights look much better now, however, the first two lines in the minecraft font are still overlapping.

I played around a bit and found the lowest legible font sizes for the Minecraft and PF Arma 5 fonts. Anything lower looks blurred beyond recognition like the last few lines in the HUD.

All I need now is for the fontsizes to match so I can use PF Arma 5 at `11` and be able to read everything.


PF Arma 5 at `font_size=11`.  The gap between the first 2 lines in this one is much better than the larger gaps between lines imo.
![2020-09-17-220847_640x351_scrot](https://user-images.githubusercontent.com/768728/93501074-91eb0100-f932-11ea-9899-8ff1c70c5beb.png)
Minecraft at `font_size=12`
![2020-09-17-220901_640x351_scrot](https://user-images.githubusercontent.com/768728/93501078-931c2e00-f932-11ea-8e15-5c9eeb8916cd.png)

**Comment by flightlessmango** [comment]
This should fix time and version overlapping 8b4df2a9a3a36f372eda44e0ba98c625a0b98247

**Comment by txtsd** [comment]
Excellent!
![2020-09-22-183221_640x351_scrot](https://user-images.githubusercontent.com/768728/93885671-0db5c680-fd02-11ea-839a-b1e54c29f8fa.png)


![2020-09-22-183113_640x351_scrot](https://user-images.githubusercontent.com/768728/93885514-d7784700-fd01-11ea-8911-fe87210afb9f.png)

Now let's talk about the half-sized bits and how we can make that legible.

**Comment by flightlessmango** [comment]
any difference using font_size vs font_scale?

might `sdf` branch help with this @jackun?

**Comment by txtsd** [comment]
Uh there's a linespacing difference actually.

`font_size=11`
![2020-09-22-183113_640x351_scrot](https://user-images.githubusercontent.com/768728/93887914-eb717800-fd04-11ea-83c0-d8f95e89bd6e.png)
`font_scale=0.45`
![2020-09-22-185323_640x351_scrot](https://user-images.githubusercontent.com/768728/93887918-eca2a500-fd04-11ea-8837-48f4fcd50cfc.png)

**Comment by flightlessmango** [comment]
This should fix the difference between font_size and font_scale cb8d992bfebe3e4d7827db57c2468f3300a570da

**Comment by txtsd** [comment]
Linespacing is the same now. 

`font_size=11`
![2020-09-23-181159_640x351_scrot](https://user-images.githubusercontent.com/768728/94013898-6780c400-fdc8-11ea-82fd-9458afc516a9.png)

`font_scale=0.45`
![2020-09-23-181219_640x351_scrot](https://user-images.githubusercontent.com/768728/94013900-68b1f100-fdc8-11ea-9c57-d83dc4f8a4ae.png)

I'm still looking to get the `FPS`, `GB`, `ms`, and wine and dxvk details etc readable.

**Comment by flightlessmango** [comment]
I *think* it's just too small, a "fix" would be not use the "small" font when it's this tiny or ever with custom fonts or something

**Comment by txtsd** [comment]
I think a toggle in the config would be better than trying to automatically determine when to not use the "small" font.

**Comment by flightlessmango** [comment]
`no_small_font` param was added a little while back, you can try it out in develop

**Comment by txtsd** [comment]
Excellent! Thanks a lot for doing this!

![2020-11-27-194115_640x351_scrot](https://user-images.githubusercontent.com/768728/100457750-9e38ca80-30e8-11eb-9dbb-414a0eb3836a.png)
![2020-11-27-194131_640x351_scrot](https://user-images.githubusercontent.com/768728/100457759-a264e800-30e8-11eb-89d7-f0f4b1ef3877.png)
