### ISSUE TITLE
Not displaying the GPU info with hybrid Intel/Nvidia GPU

### ISSUE THREAD

**Issue by ranplayer** [flightlessmango/MangoHud#347]
Hello,

I've been trying to use MangoHud on my notebook using the Prime render offload mode of its hybrid GPU (Intel/Nvidia), but the GPU info is not displayed on the hud. It works if only the Nvidia GPU driver is loaded. Among the vkcube logs I could find this message that probably is related to the issue: `MANGOHUD: XNVCtrl didn't find the correct display`. (I've attached the full log here [vkcube_log.tar.gz](https://github.com/flightlessmango/MangoHud/files/5245601/vkcube_log.tar.gz))

My specs:
- O.S: Manjaro
- Nvidia driver: 450.66
- Installed packages: mangohud (0.5.1-3), lib32-mangohud (0.5.1-3), libxnvctrl (450.66), lib32-libxnvctrl (450.66)

P.S: I'm using the [optimus-manager](https://github.com/Askannz/optimus-manager) package to manage the GPU modes.

**Comment by jackun** [comment]
I don't think xnvctrl even works with prime, only NVML. If nvidia package didn't already install NVML (libnvidia-ml.so) then check some cuda packages.

**Comment by ranplayer** [comment]
NVML is installed as well. I'm going to have a look at the cuda packages.

**Comment by jackun** [comment]
On manjaro/arch it's in nvidia-utils, but it's weird it doesn't print anything about nvml failing, just goes straight to xnvctrl.

**Comment by magiruuvelvet** [comment]
GPU info is only displayed when using `primerun mangohud something` and only works on NVIDIA. No need to install xnvctrl, it just bricks mangohud for Mesa/Intel. Running `mangohud something` shows the Intel stats, but Intel iGPUs are weird, you can't get GPU usage and VRAM of Intel GPUs.

So in short:\
**Intel**: basically just CPU/RAM and Engine\
**NVIDIA**: everything

I made a custom patch for myself just for that so when running mangohud on mesa doesn't show useless clutter. https://github.com/magiruuvelvet/gentoo-portage-config/blob/master/patches/x11-misc/mangohud/seperate-configs-per-gpu.patch

With this patch I now have `MangoHud-mesa.conf` and `MangoHud-nvidia.conf` based on the PRIME render offload environment variable.

**Comment by ranplayer** [comment]
I've just compiled mangohud without **xnvctrl** as well, but no lucky yet. It is just displaying the CPU usage.

**Comment by jackun** [comment]
> I compiled mangohud WITHOUT xnvctrl as it causes problems for mesa.

Uh? What problems?

**Comment by magiruuvelvet** [comment]
@jackun mangohud compiled with xnvctrl makes mangohud only work on the nvidia gpu when using primerun, and breaks it on mesa/intel. the overlay doesn't load at all. looking at the meson build it seems like enabling xnvctrl doesn't compile the other code working on both nvidia and mesa, but only compiles the xnvctrl parts which obviously don't work on mesa

what is xnvctrl even used for when mangohud works just fine without it on nvidia?

**Comment by jackun** [comment]
> breaks it on mesa/intel

Can you be more specific? There's only X11 display check that could affect it in anyway.

**Comment by magiruuvelvet** [comment]
so now this is weird i recompiled `libxnvctrl` and now it works on both mesa and nvidia. i think i made a mistake the first time. on the previous version i compiled there was an X11 `NV-GLX` error though as far as i can remember. using prime render offload the nvidia x11 extensions are always available but should only be used with primerun

**Comment by jackun** [comment]
Hmm, haven't seen it AMD only system but guess it _could_ go to x11 crash handler. Maybe set our own handler when checking for xnvctrl.

**Comment by ranplayer** [comment]
I've found out the reason. The nvidia opencl libraries were not installed (**lib32-opencl-nvidia-450xx** and **opencl-nvidia-450xx**). Now it is working as expected. Thank you all for the help.
