### ISSUE TITLE
MangoHud causes Among Us to fail to launch

### ISSUE THREAD

**Issue by LiquidPL** [flightlessmango/MangoHud#348]
With MangoHud enabled, the game window never shows up, it doesn't seem to crash though, as Steam keeps thinking the game is running despite everything.

Setting `MANGOHUD=0 %command%` as the launch options makes the game start normally.

The game is running through proton so here's a proton log as well: [steam-945360.log](https://github.com/flightlessmango/MangoHud/files/5248032/steam-945360.log).

**Comment by flightlessmango** [comment]
Try adding `NODEVICE_SELECT=1` before mangohud in the launch options

**Comment by LiquidPL** [comment]
Doesn't seem to fix it sadly.

**Comment by Caffe1neAdd1ct** [comment]
Might be unrelated but i've been trying to track down a bug with wine+vulkan+libstrangle for a while... launching any wine application with `strangle 30 wine %command%` stopped working after wine version 5.9.

Just tried mangoHud and exactly the same issue, games will only launch if you run either wineboot or winecfg first, then lunch through mangohud.

However adding `NODEVICE_SELECT=1` launches the games/applications straight away and FPS limiting is working nicely. 

Further reading and the commit which seems to have caused the issue in wine:

- https://gitlab.com/torkel104/libstrangle/-/issues/39
- https://github.com/wine-mirror/wine/commit/145cfce1135a7e59cc4c89cd05b572403f188161
- https://bugs.winehq.org/show_bug.cgi?id=49441

Took 6 hours of compiling wine 32+64bit together with git bisect to get this far, so hope it helps narrow down this issue too :)
