### ISSUE TITLE
Disabling the frame timing graph has no effect

### ISSUE THREAD

**Issue by fls2018** [flightlessmango/MangoHud#35]
I've disabled it via the config file:

![frametime](https://user-images.githubusercontent.com/43592670/74566768-25f38500-4f6c-11ea-9ded-ea817dad112a.png)

Yet in game it still displays:

![20200214204946_1](https://user-images.githubusercontent.com/43592670/74566806-3e639f80-4f6c-11ea-8b2e-28e7a7a75c97.jpg)

**Comment by telans** [comment]
It should be `frame_timing=0`. That goes for any option, adding a 0 will disable it. I will make it more clear though

**Comment by fls2018** [comment]
> It should be `frame_timing=0`. That goes for any option, adding a 0 will disable it. I will make it more clear though

That works just as I want, thanks.

**Comment by telans** [comment]
Well, adding a 0 works for any *default* option

**Comment by axet** [comment]
@flightlessmango  Can this change be reflected in README.md? Which currently suggest to use `frametime=0`

**Comment by jackun** [comment]
where does it suggest what? `frametime` and `frame_timing` are two separate things

**Comment by axet** [comment]
@jackun I did't notice it is different options. But when I first start looking for "frametime" hud item, i found frametime option, which is not working. Probably, clarifying this confusing options in comment would be nice.

**Comment by kubad9** [comment]
100% gpu usage in No Man Sky? `GG`
