### ISSUE TITLE
[Feature request] Add option to changing color of output depending on load.

### ISSUE THREAD

**Issue by r-a-sattarov** [flightlessmango/MangoHud#350]
@flightlessmango thanks for such a useful program!

It is possible to add an option to MangoHud to change output color depending on load or value?

Examples:
- 2 colors for displaying the CPU load: up to 90% show load in white, and after 90% change color of load to red.
- 3 colors for displaying the GPU load: up to 60% show load in green (or white), from 60% to 90% show in yellow, and from 90% change color of load to red.

Also, change color not only depending on load, but also when a certain value is reached (for example, when game starts to use more than 4 GB of RAM).

How difficult is it to implement and is it possible (without losing performance)?

**Comment by flightlessmango** [comment]
This is doable, but I think the major problem is consensus of what constitutes "red levels".
I think it would require that you can also customize what is "critical" etc

**Comment by r-a-sattarov** [comment]
> This is doable, but I think the major problem is consensus of what constitutes "red levels".
> I think it would require that you can also customize what is "critical" etc

It is possible to make some default settings for this new option?
For example, "gpu_load_color=default" will show only default white color for GPU load value.

And be able to customize such display levels, of course 😄
For example, "gpu_load_color=0-90:default;90-100:red" or "gpu_load_color=0-90:default;90-100:RRGGBB". Or something like that.

**Comment by gort818** [comment]
I might give this a go if no one else is working on it

**Comment by rawfoxDE** [comment]
> I might give this a go if no one else is working on it

ya nice, hack it down, ill help you testing it 
\m/

**Comment by gort818** [comment]
if you guys want to test (still working on it) so far I have gpu load.. here you go https://github.com/gort818/MangoHud/tree/load_color

config options so far are

`gpu_load_change=1` to turn it on
`gpu_load_high= e.g. 90 ` set the high amount of gpu load
`gpu_load_med= e.g.60` set the medium amout of gpu load
`gpu_load_high_color` set the color of high
`gpu_load_med_color` set the color of med
`gpu_load_low_color` set the color of low`

**Comment by gort818** [comment]
![mango](https://user-images.githubusercontent.com/9098121/94513921-c4b7b380-01d4-11eb-8d83-3e4c7a4d3bf3.gif)

**Comment by flightlessmango** [comment]
This is now added in develop, see #358 and #380
