### ISSUE TITLE
MangoHud causes FFXIV to freeze

### ISSUE THREAD

**Issue by adih2001** [flightlessmango/MangoHud#352]
As the title says when I run FFXIV (the demo version if it matters) on Steam on Proton 5.0-9 with the launch option `mangohud %command%` after the game launches mangohud does show up and seems to work normally but if I click on Configuration option in the menu the game freezes and a error appears on screen.

I am on Arch Linux and I am running the latest mangohud-git package pulled from AUR at the time of writing this (mangohud-git-0.5.1.r18.g9391822-1).

Here is the log I got by running steam in terminal if it helps: [https://pastebin.com/Rj211fHt](https://pastebin.com/Rj211fHt)

**Comment by adih2001** [comment]
Forgot to mention that I also do have `lib32-mangohud-git` installed from AUR too (mangohud-git-0.5.1.r18.g9391822-1) and that also I am on a NVIDIA RTX2060 Super, driver version 450.56.11.

**Comment by gort818** [comment]
Interesting bit from the log `ERROR: Could Not Get Primary Adapter Handle.` seems to be a wine issue.

and if you do not use MangoHud the game works fine?

**Comment by adih2001** [comment]
> Interesting bit from the log `ERROR: Could Not Get Primary Adapter Handle.` seems to be a wine issue.
> 
> and if you do not use MangoHud the game works fine?

Yes the game works with no issues without it. But a interesting bit is that error also appears without mangohud but everything works fine. Here is the log of the game without mangohud: https://pastebin.com/5suFDWHv
Here is the error btw that appears on screen when using mangohud (that I mentioned in the first post): https://imgur.com/a/YCnnX6Q

One thing I forgot to mention is that in this PC I have another GPU in the second slot (a RX580) but I have no drivers and monitors attached to it so I don't see why it could affect mangohud.

Btw even with mangohud if I were to not go in to configuration in the menu or in-game, the game seems to run fine with no issues but once I click on configuration game freezes with the error above in the pic.

**Comment by adih2001** [comment]
Wanted to mention that I was told on the mangohud discord to run the game with `NODEVICE_SELECT=1` but it still does freeze.

**Comment by gort818** [comment]
Yeah that is only applicable if using mesa for AMD cards. Are you sure don't have drivers for the rx580?

**Comment by adih2001** [comment]
It seems that I only have `mesa` and `lib32-mesa` installed and that's it and nothing else from the list of packages needed to get a amd gpu running mentioned here [https://wiki.archlinux.org/index.php/AMDGPU#Installation](https://wiki.archlinux.org/index.php/AMDGPU#Installation). Also not sure if I've mentioned but not only I don't have anything connected to the AMD gpu but also that I generated an X config using `nvidia-settings` so it should never attempt to even use the amd gpu.

**Comment by adih2001** [comment]
So after some more testing, I found out that using the enviroment variable instead of the mangohud command on Steam like this `MANGOHUD=1 %command%` does not cause the game to freeze in the configuration menu but using the mangohud command to launch the game (`mangohud %command%`) does make the game freeze.
