### ISSUE TITLE
[Feature Request] Keybinding to toggle fps_limit

### ISSUE THREAD

**Issue by Mershl** [flightlessmango/MangoHud#359]
Hello,

MSI Afterburner provides a keybinding to toggle the frame limiter which is really handy. Would this be possible with the current implementation of MangoHud?

**Comment by flightlessmango** [comment]
This feature has already been implemented in develop branch. It will show up in next release or you can build from develop now.
Default keybind is `Shift_L+F1` and you set it limits with `toggle_fps_limit` param

**Comment by Mershl** [comment]
Thanks for the lightning fast response! Will give it a try later today. Thank you!
