### ISSUE TITLE
Not working in Half Life

### ISSUE THREAD

**Issue by HassanZahin** [flightlessmango/MangoHud#360]
I have tried to use mangohud with Half Life (DVD) like this:
`MANGOHUD_DLSYM=1 mangohud wine ~/.PlayOnLinux/wineprefix/hl_blue_shift/drive_c/Sierra/Half-Life/hl.exe`

It gives an error and doesn't do anything.

> skipping config: /usr/lib/wine/MangoHud.conf [ not found ]
> skipping config: /home/zahin/.config/MangoHud/wine.conf [ not found ]
> parsing config: /home/zahin/.config/MangoHud/MangoHud.conf [ ok ]
> MANGOHUD: Failed to open 32bit libnvidia-ml.so.1: libnvidia-ml.so.1: cannot open shared object file: No such file or directory
> MANGOHUD: Failed to load NVML
> MANGOHUD: Failed to open 32bit libXNVCtrl.so.0: libXNVCtrl.so.0: cannot open shared object file: No such file or directory
> MANGOHUD: XNVCtrl loader failed to load
> MANGOHUD: Uploading is disabled (permit_upload = 0)
> Version: 2.1 
> 
>

**Comment by HassanZahin** [comment]
I am wondering why it is looking for nvidia libraries even though I don't have one.

**Comment by jackun** [comment]
> I am wondering why it is looking for nvidia libraries even though I don't have one.

Doesn't matter. You seem to have old version, v0.5.x shouldn't print that anymore.

I don't think you're launching it correctly. At the very least `cd` into `~/.PlayOnLinux/wineprefix/hl_blue_shift/drive_c/Sierra/Half-Life/` as `hl2.exe` probably can't find its files from current directory which if launched like that is your $HOME.

**Comment by HassanZahin** [comment]
> ~/.PlayOnLinux/wineprefix/hl_blue_shift/drive_c/Sierra/Half-Life/

Half life starts without any problem though.

**Comment by HassanZahin** [comment]
Built from the source. Now It's showing a bit different error massage. Ignore the `0009:err:d3d:wined3d_adapter_find_polyoffset_scale PolygonOffset scale factor detection failed, using fallback value 2^23.` warning. It always shows but doesn't effect anything. Last few lines seems interesting.

#@#:~/.PlayOnLinux/wineprefix/hl_blue_shift/drive_c/Sierra/Half-Life$ mangohud --dlsym  wine ./hl.exe                                                               
000f:err:service:process_send_command receiving command result timed out
skipping config: /usr/lib/wine/MangoHud.conf [ not found ]
skipping config: /home/zahin/.config/MangoHud/wine.conf [ not found ]
parsing config: /home/zahin/.config/MangoHud/MangoHud.conf [ ok ]
MANGOHUD: Failed to open 32bit libnvidia-ml.so.1: libnvidia-ml.so.1: cannot open shared object file: No such file or directory
MANGOHUD: Failed to load NVML
MANGOHUD: Failed to open 32bit libXNVCtrl.so.0: libXNVCtrl.so.0: cannot open shared object file: No such file or directory
MANGOHUD: XNVCtrl loader failed to load
MANGOHUD: Uploading is disabled (permit_upload = 0)
Version: 2.1 
0009:err:d3d:wined3d_adapter_find_polyoffset_scale PolygonOffset scale factor detection failed, using fallback value 2^23.
0009:err:d3d:wined3d_adapter_find_polyoffset_scale PolygonOffset scale factor detection failed, using fallback value 2^23.
0009:err:d3d:wined3d_adapter_find_polyoffset_scale PolygonOffset scale factor detection failed, using fallback value 2^23.
0009:err:d3d:wined3d_adapter_find_polyoffset_scale PolygonOffset scale factor detection failed, using fallback value 2^23.
0009:err:d3d:wined3d_adapter_find_polyoffset_scale PolygonOffset scale factor detection failed, using fallback value 2^23.
0009:err:d3d:wined3d_adapter_find_polyoffset_scale PolygonOffset scale factor detection failed, using fallback value 2^23.
0009:err:d3d:wined3d_adapter_find_polyoffset_scale PolygonOffset scale factor detection failed, using fallback value 2^23.
0009:err:d3d:wined3d_adapter_find_polyoffset_scale PolygonOffset scale factor detection failed, using fallback value 2^23.
0009:err:d3d:wined3d_adapter_find_polyoffset_scale PolygonOffset scale factor detection failed, using fallback value 2^23.
0009:err:d3d:wined3d_adapter_find_polyoffset_scale PolygonOffset scale factor detection failed, using fallback value 2^23.
0009:err:d3d:wined3d_adapter_find_polyoffset_scale PolygonOffset scale factor detection failed, using fallback value 2^23.
0009:err:d3d:wined3d_adapter_find_polyoffset_scale PolygonOffset scale factor detection failed, using fallback value 2^23.
0009:err:d3d:wined3d_adapter_find_polyoffset_scale PolygonOffset scale factor detection failed, using fallback value 2^23.
0009:err:d3d:wined3d_adapter_find_polyoffset_scale PolygonOffset scale factor detection failed, using fallback value 2^23.
0009:err:d3d:wined3d_adapter_find_polyoffset_scale PolygonOffset scale factor detection failed, using fallback value 2^23.
0009:err:d3d:wined3d_adapter_find_polyoffset_scale PolygonOffset scale factor detection failed, using fallback value 2^23.
0009:err:d3d:wined3d_adapter_find_polyoffset_scale PolygonOffset scale factor detection failed, using fallback value 2^23.
0009:err:d3d:wined3d_adapter_find_polyoffset_scale PolygonOffset scale factor detection failed, using fallback value 2^23.
0009:err:d3d:wined3d_adapter_find_polyoffset_scale PolygonOffset scale factor detection failed, using fallback value 2^23.
0009:err:d3d:wined3d_adapter_find_polyoffset_scale PolygonOffset scale factor detection failed, using fallback value 2^23.
0009:err:d3d:wined3d_adapter_find_polyoffset_scale PolygonOffset scale factor detection failed, using fallback value 2^23.
0009:err:d3d:wined3d_adapter_find_polyoffset_scale PolygonOffset scale factor detection failed, using fallback value 2^23.
0009:err:d3d:wined3d_adapter_find_polyoffset_scale PolygonOffset scale factor detection failed, using fallback value 2^23.
0009:err:d3d:wined3d_adapter_find_polyoffset_scale PolygonOffset scale factor detection failed, using fallback value 2^23.
0009:err:d3d:wined3d_adapter_find_polyoffset_scale PolygonOffset scale factor detection failed, using fallback value 2^23.
0009:err:d3d:wined3d_adapter_find_polyoffset_scale PolygonOffset scale factor detection failed, using fallback value 2^23.
0009:err:d3d:wined3d_adapter_find_polyoffset_scale PolygonOffset scale factor detection failed, using fallback value 2^23.
0009:err:d3d:wined3d_adapter_find_polyoffset_scale PolygonOffset scale factor detection failed, using fallback value 2^23.
0009:err:d3d:wined3d_adapter_find_polyoffset_scale PolygonOffset scale factor detection failed, using fallback value 2^23.
0009:err:d3d:wined3d_adapter_find_polyoffset_scale PolygonOffset scale factor detection failed, using fallback value 2^23.
002e:err:clipboard:convert_selection Timed out waiting for SelectionNotify event
002e:err:clipboard:convert_selection Timed out waiting for SelectionNotify event
ERROR: ImGui_ImplOpenGL3_CreateDeviceObjects: failed to compile vertex shader!
0:1(10): error: GLSL 1.30 is not supported. Supported versions are: 1.10, 1.20, and 1.00 ES

ERROR: ImGui_ImplOpenGL3_CreateDeviceObjects: failed to compile fragment shader!
0:1(10): error: GLSL 1.30 is not supported. Supported versions are: 1.10, 1.20, and 1.00 ES

ERROR: ImGui_ImplOpenGL3_CreateDeviceObjects: failed to link shader program! (with GLSL '#version 130
')
error: linking with uncompiled/unspecialized shadererror: linking with uncompiled/unspecialized shader

**Comment by jackun** [comment]
MESA_GLSL_VERSION_OVERRIDE=130 _maybe help_ or
try changing any 130 to 120 or even 110: https://github.com/flightlessmango/MangoHud/blob/96bf79775ce68d94f78f926bc6bc6c9aaa6d5db2/src/gl/imgui_impl_opengl3.cpp#L425

**Comment by HassanZahin** [comment]
> MESA_GLSL_VERSION_OVERRIDE=130

Where should I add this?

**Comment by jackun** [comment]
Ok, I limited glsl version to 1.20. Hopefully it now compiles with OpenGL 2.1 context.
Rebuild and install `develop` branch or your distro's MangoHud  "git" package, if any.

**Comment by HassanZahin** [comment]
Ok, I'll try that. Thank you

**Comment by HassanZahin** [comment]
Now it throws this:

mangohud --dlsym  wine ~/.PlayOnLinux/wineprefix/hl_blue_shift/drive_c/Sierra/Half-Life/hl.exe 
ERROR: ld.so: object 'libMangoHud_dlsym.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libMangoHud.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libMangoHud_dlsym.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libMangoHud.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libMangoHud_dlsym.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libMangoHud.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libMangoHud_dlsym.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libMangoHud.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libMangoHud_dlsym.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libMangoHud.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libMangoHud_dlsym.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libMangoHud.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libMangoHud_dlsym.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libMangoHud.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libMangoHud_dlsym.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libMangoHud.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libMangoHud_dlsym.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libMangoHud.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libMangoHud_dlsym.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libMangoHud.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libMangoHud_dlsym.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libMangoHud.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libMangoHud_dlsym.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libMangoHud.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libMangoHud_dlsym.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libMangoHud.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.

**Comment by jackun** [comment]
What distro and did you manually build with  `build.sh` ? Try `./build.sh clean build install` just in case.
If that doesn't work, check where it tries to load it with:
`LD_DEBUG=libs mangohud glxgears 2>&1 | grep -i mangohud.so`

Or replace `glxgears` with some other opengl program if it is not installed.

**Comment by HassanZahin** [comment]
> What distro and did you manually build with `build.sh` ? Try `./build.sh clean build install` just in case.
> If that doesn't work, check where it tries to load it with:
> `LD_DEBUG=libs mangohud glxgears 2>&1 | grep -i mangohud.so`
> 
> Or replace `glxgears` with some other opengl program if it is not installed.

KDE Neon. Yes, I built with build.sh.

**Comment by jackun** [comment]
> x86_64-linux-gnu
Ugh, just has to insert it into $LIB doesn't it...
For quick fix try `ln -sv lib /usr/lib/mangohud/lib/x86_64-linux-gnu/` for 64bit and probably `ln -sv lib /usr/lib/mangohud/lib/i686-linux-gnu/` for 32bit or whatever it was.

**Comment by flightlessmango** [comment]
Might be fixed in develop, please check if it's still reproducible

**Comment by gravisxv** [comment]
Doesn't work in hl2
