### ISSUE TITLE
Divinity Original Sin Enhanced Edition ( native GL ) - Mangohud doesn't work with it

### ISSUE THREAD

**Issue by Leopard1907** [flightlessmango/MangoHud#364]
As described in the title , Mangohud is not able to show up with this game.

Apitrace:

https://drive.google.com/file/d/1e4OhmI8jF0WZJDMrENr6hIg-9SutN4Aj/view?usp=sharing

I've tried to get a rdc capture also but wasn't able to do it.

**Comment by jackun** [comment]
Hmm, with apitrace itself MangoHud works for me.

**Comment by Leopard1907** [comment]
Sadly it doesn't for me. Latest develop branch.

![Ekran Görüntüsü - 2020-10-07 09-29-05](https://user-images.githubusercontent.com/24878978/95295390-a65e5180-087f-11eb-86cf-370d282ecad0.png)

**Comment by Leopard1907** [comment]
> Sadly it doesn't for me. Latest develop branch. Both with and without dlsym.
> 
> ![Ekran Görüntüsü - 2020-10-07 09-29-05](https://user-images.githubusercontent.com/24878978/95295390-a65e5180-087f-11eb-86cf-370d282ecad0.png)

**Comment by Leopard1907** [comment]
Fixed with MangoHud 0.6.0. Closing.

https://github.com/flightlessmango/MangoHud/commit/6a5cd38127ae330c79bc61d2a433bdb84061bc5b
