### ISSUE TITLE
Wrong GPU Stats shown with DRI_PRIME=1

### ISSUE THREAD

**Issue by Krutonium** [flightlessmango/MangoHud#365]
My Desktop has two AMD GPU's in it and for experimentation reasons, I ran a game with `DRI_PRIME=1` - specifically Satisfactory.

The two GPU's in question are an R9 390 and an RX 5600XT.

When using the 390 via prime, MangoHud will correctly identify the GPU in use by name, but will show statistics for the primary GPU, the 5600XT.
![DRI_Prime](https://user-images.githubusercontent.com/3945538/95314900-d7c72500-085f-11eb-9085-9fed5a19f31e.png)

**Comment by Krutonium** [comment]
![No_DRI](https://user-images.githubusercontent.com/3945538/95315165-2674bf00-0860-11eb-9153-11de7f782081.png)

The same game in roughly the same spot, without `DRI_PRIME=1`.

**Comment by plasticbomb1986** [comment]
try it with the pci_dev option, i have two vega64 on my system, and it was never able to tell, which gpu a vulkan game is using,  and it always shown the secondary gpu (for me thats the secondary slot, in  pcie address e0 while the primary is in b0), so to make it work i have to use that optiopn in mangohud config, plus to make it sure, the game runs on the primary gpu and not on the secondary, im using vkdevicechooser vulkan layer, to tell vulkan which one to use. 

Vulkan supposedly randomly assing gpu ids to the gpus, so it shouldnt work, except if the gpus are different type of gpus, like igp and dgpu, but in my system vulkan always assign the same gpus to the same gpu_ids, like my secondary gets GPU_ID=0 while the primary gets GPU_ID=1
