### ISSUE TITLE
No Man's Sky. Not showing gpu loads/vram usage

### ISSUE THREAD

**Issue by Galcian79** [flightlessmango/MangoHud#366]
Important to notice now No Man's Sky uses Vulkan API. This is the first game i encountered this strange issue. Only cpu loads and ram usage get showed.

**Comment by flightlessmango** [comment]
Can you give some more details? system specs, os, mangohud version etc

**Comment by Galcian79** [comment]
> Can you give some more details? system specs, os, mangohud version etc

My specs:
OS Manjaro linux
Kernel  Linux 5.4.70-tkg
Cpu Ryzen 5 2600
16 GB RAM
GPU GTX 1060 6GB
Proton 5.0.9 (now 5.13-1)
mangohud, lib32-mangohud 0.5.1-3

I have to correct my previous report. Vram loads are showed and reports 0.0GB

**Comment by TheFeelTrain** [comment]
Same issue here.

Arch Linux 
Kernel is 5.8.14-zen
Ryzen 9 3900X
NVIDIA GTX 1080 8GB

GPU usage and temperature does not show, and VRAM is always 0.00. I have not looked into but it might have something to do with that NVIDIA GPU Vulkan workaround.

**Comment by jeisoncp** [comment]
Same issue here, playing GTA V over Proton GE 6.0.
