### ISSUE TITLE
How can I use it in Steam OpenGL games?

### ISSUE THREAD

**Issue by Toadfield** [flightlessmango/MangoHud#368]
I tried to do "MANGOHUD_DLSYM=1",but that doesn't work,and the game I tested doesn't start.

**Comment by h3o66** [comment]
In the steam command options you can set it like the following:
`MANGOHUD_DLSYM=1 mangohud %command%`

See also the start page of this project:
https://github.com/flightlessmango/MangoHud#opengl

**Comment by psofiterol** [comment]
As of 0.5.1 `mangohud --dlsym %command%` works too.

**Comment by Toadfield** [comment]
thanks
