### ISSUE TITLE
Not XDG compliant

### ISSUE THREAD

**Issue by SolitudeSF** [flightlessmango/MangoHud#37]
Install script and config handling should use `XDG_CONFIG_HOME` and `XDG_DATA_HOME` with fallback to current values.

**Comment by telans** [comment]
Half of this is done, unless you can find any issues with the scripts. `config.cpp` just needs to be updated now

**Comment by jackun** [comment]
Who even sets it?

**Comment by SolitudeSF** [comment]
not relevant to this issue, but issue with scripts is `/bin/bash` shebang instead of `/usr/bin/env bash`. or you could use plain `/bin/sh` since you dont use any useful bashisms.

**Comment by SolitudeSF** [comment]
fixed in master

**Comment by gasinvein** [comment]
Is there any ETA for a new release that would include this fixes?
