### ISSUE TITLE
mangohud_config does not work with the fps_limit toggle

### ISSUE THREAD

**Issue by bgkillas** [flightlessmango/MangoHud#371]
it seems that using MANGOHUD_CONFIG="fps_limit=0,30,60" does not work because the comma is meant to separate each config in the development branch

**Comment by flightlessmango** [comment]
I think you would need to write it like so `MANGOHUD_CONFIG=fps_limit="0,30,60"`

**Comment by bgkillas** [comment]
![image](https://user-images.githubusercontent.com/55570525/97067341-6d65f280-158a-11eb-95f3-06e9cb6a1410.png)
still persists

**Comment by jackun** [comment]
Use either `MANGOHUD_CONFIG=fps_limit='0\,30\,60'` or `MANGOHUD_CONFIG=fps_limit=0\\,30\\,60` so shell doesn't remove backslash escape.
