### ISSUE TITLE
Missing libdl-2.31.so

### ISSUE THREAD

**Issue by cow-killer** [flightlessmango/MangoHud#373]
Pop!_OS 20.10. Running `./build.sh build` results in this:
```ninja: Entering directory `build/meson32'
ninja: error: '/usr/lib32/libdl-2.31.so', needed by 'src/libMangoHud.so', missing and no known rule to make it```

**Comment by flightlessmango** [comment]
It's saying that you're missing a required library, my guess would be that you haven't enable 32bit packages for your distro
