### ISSUE TITLE
mangohud on metro exodusdx12

### ISSUE THREAD

**Issue by pipes80-collab** [flightlessmango/MangoHud#374]
I have try this good software for osd and work with mtro exodus and protonge on steam but when select dx12 game version in options game and restart, the hud no work more

**Comment by flightlessmango** [comment]
As long as it's actually using VKD3D it shouldn't have any issues. You could try to run with `mangohud --dlsym %command%` in case it's falling back to WINED3D. Other than that I would recommend that you look over the readme again
