### ISSUE TITLE
How does it work for Vulkan application/games

### ISSUE THREAD

**Issue by kadogo** [flightlessmango/MangoHud#375]
Hello,
Sorry the issue is maybe a bit outside the use of MangoHud alone.

I'm trying to make an AppImage so that it can be used easily without the need to install the binaries (but also a bit for the learning process). I have an AppImage that is working for glxgears and a native linux game (Baba is you); But when I use it on a Proton game or on vkcube it doesn't work.

I did all the symlinks and the libraries load with LD_PRELOAD and LD_LIBRARY_PATH so I think that I must miss something about Vulkan.

Thanks for your help and advice.
Cheers.

**Comment by flightlessmango** [comment]
Is this actually related to mangohud or is this a separate project?

The vulkan loader uses these json manifests for injecting layers
[mangohud.json.in](https://github.com/flightlessmango/MangoHud/blob/master/src/mangohud.json.in)

**Comment by kadogo** [comment]
It's a separate project I just found the environnement variable sorry to have bother you with that.

My project is having a way to build it easily and having an "executable" (https://github.com/kadogo/easy-builder).
There are surely ways to make it proper but I just tested and it was working.

The goal of that is because I started to use https://github.com/frostworx/steamtinkerlaunch that have many features but because I use Debian Buster it can be hard to have access to all the applications so I thought it could be a way to make it work.

For me you may close the issue because it's now working.
