### ISSUE TITLE
Doesn't work without using it with steam or Lutris for opengl

### ISSUE THREAD

**Issue by Toadfield** [flightlessmango/MangoHud#377]
I set the MangoHud things as global environment variables,and if I do "export" in terminal,it shows up correctly I think:
`declare -x MANGOHUD="1"
declare -x MANGOHUD_DLSYM="1"`
But I tried some OpenGL games that would work with MangoHud if I set it in Lutris,but they don't work with MangoHud without Lutris.
I don't have many vulkan games that aren't on steam,so I can't test that.

**Comment by flightlessmango** [comment]
the `MANGOHUD` variable is only for vulkan, you need to use  the `mangohud`command for OpenGL

**Comment by Toadfield** [comment]
I forgot that every time.So do I have to add a environment variable named "mangohud=1" or how can I use the command without Lutris?

**Comment by flightlessmango** [comment]
You add `mangohud` as a command prefix in lutris

**Comment by Toadfield** [comment]
How can I do that without Lutris?

**Comment by flightlessmango** [comment]
`mangohud %command%` in launch options for steam
or `mangohud --dlsym %command%` if dlsym is needed

**Comment by Toadfield** [comment]
So do I need o run the game through Lutris or steam?
Because what I want to do is using MangoHud globaly without needing to add the games to steam/lutris

**Comment by flightlessmango** [comment]
There is no good way to globally enable MangoHud that I know of

**Comment by gort818** [comment]
@Toadfield you do not need lutris or steam to run mangohud.. just prepend `mangohud` ./your_game_exe

**Comment by Toadfield** [comment]
@gort818 What do you mean?
Do you mean that I have to create a folder for every game that has "mangohud" in it and place it in every game folder,or did I understand it wrong?

**Comment by gort818** [comment]
No, nothing to do with folders.. you need to add `mangohud` before the exe name. How are running these opengl games that are not using lutris or steam? Running from the command line or from a shortcut like a .desktop file?

**Comment by Toadfield** [comment]
I run them with desktop shortcuts.

**Comment by gort818** [comment]
Ok so you can just edit the shortcuts and add `mangohud` before the exe

**Comment by Toadfield** [comment]
By edit,do you mean open it in a text editor?
If so,where do I have to put it exactly?

**Comment by Toadfield** [comment]
I will close that issue,it doesn't have anything to do with mangohud
