### ISSUE TITLE
MangoHud doesn't work on Outlast (Native OpenGL, Steam version)

### ISSUE THREAD

**Issue by jmissao** [flightlessmango/MangoHud#378]
Using an updated ArchLinux. Kernel 5.9.3
MangoHud version 0.5.1

Trying to start the game directly from Steam. The Hud actually appears on the first splash screen before the game, but it disappears in the second logo window (!), and does not show on the game itself.
The launch commands I used were `mangohud %command%` and `mangohud --dlsym %command%`.
There is no MANGOHUD=1 set in my .profile or anywhere.

Also tried messing with LD_PRELOAD:

```
$ LD_PRELOAD=/usr/lib/libMangoHud.so mangohud ~/.local/share/Steam/ubuntu12_32/steam steam://run/238320
ERROR: ld.so: object '/usr/lib/libMangoHud.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
INFO: process steam is blacklisted in MangoHud
$ LD_PRELOAD=/usr/lib/libMangoHud.so mangohud --dlsym ~/.local/share/Steam/ubuntu12_32/steam steam://run/238320
ERROR: ld.so: object '/usr/lib/libMangoHud.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
INFO: process steam is blacklisted in MangoHud
```
In both those cases the behavior is the same, MangoHud appears in the first window, then it doesn't show up again.

Also tried preloading the 32 version by itself and together with the 64 version, also to no avail.
I tried executing the game binary directly, but it requires a bunch of steam libraries loaded. Also I couldn't find a standalone script to run the game.

**Comment by plasticbomb1986** [comment]
Instead of simple mangohud try with mangohud.x86 option.

**Comment by jackun** [comment]
Got it working? Seems to work with v0.5.1 and current `develop` for me.
