### ISSUE TITLE
32-bit games work with the HUD, but not 64-bit Games.

### ISSUE THREAD

**Issue by dribbleondo** [flightlessmango/MangoHud#38]
An odd bug is happening where, no matter what I try, the loader for HUD will work on 32bit games (Sonic Mania, Borderlands 2, even Source Filmmaker!), but not on 64-bit games (A Hat In Time, Shadow of the Tomb Raider, The Witcher III: Wild Hunt, HITMAN 2). I tried different Proton versions, I opted out of the steam beta. I even compiled it myself, with the exact same issues. Sonic Mania works, but Hitman 2 does not. 

There seems to be a 64-bit library that Steam isn't loading that does not load the HUD, and i can't quite put my finger on what. Any help would be greatly appreciated!

**Comment by flightlessmango** [comment]
What distro are you?

**Comment by dribbleondo** [comment]
Linux Mint 19.3, using the 5.4.8 Kernel.

**Comment by flightlessmango** [comment]
install vulkan-tools and see if it works with vkcube `MANGOHUD=1 vkcube`

**Comment by dribbleondo** [comment]
Already did, and It works with VKCube (I'll post screenshots of it when I get onto Linux later)

**Comment by flightlessmango** [comment]
you could try and build MangoHud from source, sometimes that works

**Comment by dribbleondo** [comment]
I did. I said In my original post that I tried compiling it, with no success: 

> I tried different Proton versions, I opted out of the steam beta. I even compiled it myself, with the exact same issues.

I compiled it earlier today to see if anything changed, no dice.

**Comment by flightlessmango** [comment]
I'm gonna need some logs to see what's happening. just a plain one where the hud doesn't show and one with gdb could be useful

**Comment by dribbleondo** [comment]
I'll see what I can do.

**Comment by flightlessmango** [comment]
I did not think about that. I don't know either how to do it with steam, since it needs some input. I guess just a normal log is better than nothing. It's a shame that vkcube works since it's 64-bit and would be easy to test with

**Comment by dribbleondo** [comment]
I updated to a newer version of Vulkan tools that was 64-bit (for some reason vulkan-tools installs as 32-bit by default). And MangoHUD no longer appears. This is very weird.

Curiouser and Curiouser....
![image](https://user-images.githubusercontent.com/9034161/74644555-5b67c080-516e-11ea-8c23-c6647e95aac5.png)

Here's the Steam Log for Hitman 2 (though i'll doubt it'll be of any use)
[Uploading steam-863550.log…]()

and here's the steam log for Sonic Mania.
[steam-584400.log](https://github.com/flightlessmango/MangoHud/files/4213071/steam-584400.log)

**Comment by flightlessmango** [comment]
Well that's good, can you send me a log with gdb and vkcube?

**Comment by jackun** [comment]
@dribbleondo can you run vkcube with `VK_LOADER_DEBUG=all` instead just debug?

**Comment by dribbleondo** [comment]
I'll get on that.

**Comment by jackun** [comment]
Hm, why is there a mangohud*.json in /usr/share/vulkan/icd.d

**Comment by dribbleondo** [comment]
Here's the log for it.
[log vkcube.txt](https://github.com/flightlessmango/MangoHud/files/4220554/log.vkcube.txt)

**Comment by jackun** [comment]
You forgot MANGOHUD=1 :) But while you're at it, maybe paste what `ldd ~/.local/share/MangoHud/libMangoHud.so` says too.

**Comment by dribbleondo** [comment]
:man_facepalming:  BRB.

[log vkcube.txt](https://github.com/flightlessmango/MangoHud/files/4220658/log.vkcube.txt)


also, to answer THAT question, I had the foresight to do that yesterday back.
![Screenshot from 2020-02-17 10-20-50](https://user-images.githubusercontent.com/9034161/74760504-69066e80-5272-11ea-9806-78eb520071b3.png)

**Comment by jackun** [comment]
Installer screwed up the path for some reason
`ERROR: /home/dribbleondo/.local/share/MangoHud//home/dribbleondo/.local/share/MangoHud/libMangoHud.so: cannot open shared object file: No such file or directory`

Fix the path manually in ~/.local/share/MangoHud/mangohud64.json

**Comment by dribbleondo** [comment]
Do you want me to edit the .json file to point to the .so? Because otherwise I don't know what that means. Just making sure.

**Comment by jackun** [comment]
Yeah

**Comment by dribbleondo** [comment]
There's only one folder in that location with that name, As soon as I delete it, neither work.

**Comment by jackun** [comment]
I meant open the `~/.local/share/vulkan/implicit_layer.d/mangohud64.json` in text editor and delete the extra path but now you can run the installer again :D

**Comment by dribbleondo** [comment]
I did a deep dive into my filesystem to see if my OS copied the .json files anywhere else. AND I FOUND THE ISSUE:
![image](https://user-images.githubusercontent.com/9034161/74765568-c5ba5700-527b-11ea-9518-08e095a0e5f3.png)

For reasons I cannot fathom, this was the blocker.
