### ISSUE TITLE
The build script requires superuser permissions 

### ISSUE THREAD

**Issue by DDzwiedziu** [flightlessmango/MangoHud#381]
I'm running Ubuntu 20.10 and `./build.sh build` asks me for superuser permissions. Which is a instant ^C.

Offenders are (in my case):

-  https://github.com/flightlessmango/MangoHud/blob/master/build.sh#L79
-  https://github.com/flightlessmango/MangoHud/blob/master/build.sh#L84

1. Do not prompt for the root password while running a build script. Throw an error, list the packages to install, ask for manual install.
2. `pip3` can install the packages in the user directory
3. `meson` and `mako` are packaged in Ubuntu since 16.04,
4. `glslangValidator` is packaged in `glslang-tools`, additionally the script looks for the executable instead of the package, _additionally_ the script looks for it in `/usr/local/bin/` while the packaged version would be installed in `/usr/bin/`.
    - Looking for the package is a minor gripe, as it's available packaged since 20.04 only,
    - also if it's really needed then the executable should be checked by `whereis` or scanning `$PATH`,
    - also-also each `build.sh` run downloads a new copy of `glslang-master-linux-Release.zip`.

**Comment by flightlessmango** [comment]
the meson and mako versions package in ubuntu 18.04 was too old, that's why we were getting them from pip. glslangValidator also needed to be downloaded separately for 18.04. 
I view it as a tool to help less experienced users, you can absolutely install mangohud without touching the build script

**Comment by flightlessmango** [comment]
I don't consider this an issue, if you would like to help us improve the script you are more than welcome to submit a PR
