### ISSUE TITLE
version `GLIBCXX_3.4.2x' not found

### ISSUE THREAD

**Issue by Desmo5574** [flightlessmango/MangoHud#383]
I'm able to complile successfully from source without any problems but I can't seem to get past this error. It shows up for every game when trying to launch via Lutris. It always complains about GLIBCXX_3.4.22 & 26. 
When issuing the command:

_strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBC_

I can see that both versions are listed. I checked and both libstdc++.so.6 & libstdc++.so.6-dev are installed. 
Below is the output I get when trying to launch any game. 

Running Steam on neon 20.04 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Warning: An unexpected error occurred while executing "/sbin/ldconfig -XNv", the exit status was 139
grep: /home/kh/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /usr/lib/mangohud/lib/x86_64-linux-gnu/x86_64/x86_64/libMangoHud.so)
grep: /home/kh/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /usr/lib/mangohud/lib/x86_64-linux-gnu/x86_64/x86_64/libMangoHud.so)
grep: /home/kh/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /usr/lib/mangohud/lib/x86_64-linux-gnu/x86_64/x86_64/libMangoHud.so)
grep: /home/kh/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /usr/lib/mangohud/lib/x86_64-linux-gnu/x86_64/x86_64/libMangoHud.so)
awk: /home/kh/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /usr/lib/mangohud/lib/x86_64-linux-gnu/x86_64/x86_64/libMangoHud.so)
awk: /home/kh/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /usr/lib/mangohud/lib/x86_64-linux-gnu/x86_64/x86_64/libMangoHud.so)
grep: /home/kh/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /usr/lib/mangohud/lib/x86_64-linux-gnu/x86_64/x86_64/libMangoHud.so)
grep: /home/kh/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /usr/lib/mangohud/lib/x86_64-linux-gnu/x86_64/x86_64/libMangoHud.so)
/home/kh/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/bin/steam-runtime-check-requirements: /home/kh/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /usr/lib/mangohud/lib/x86_64-linux-gnu/x86_64/x86_64/libMangoHud.so)
/home/kh/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/bin/steam-runtime-check-requirements: /home/kh/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /usr/lib/mangohud/lib/x86_64-linux-gnu/x86_64/x86_64/libMangoHud.so)
steam-runtime-check-requirements failed with an unexpected nonzero exit status. Trying to continue
/home/kh/.local/share/Steam/ubuntu12_32/steam steam://rungameid/234140
/home/kh/.local/share/Steam/ubuntu12_32/steam: /home/kh/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /usr/lib/mangohud/lib/i386-linux-gnu/libMangoHud.so)
/home/kh/.local/share/Steam/ubuntu12_32/steam: /home/kh/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /usr/lib/mangohud/lib/i386-linux-gnu/libMangoHud.so)

**Comment by flightlessmango** [comment]
Which Ubuntu version is this?

**Comment by Desmo5574** [comment]
KDE Neon 20.04 with mesa oibaf ppa

**Comment by jackun** [comment]
Steam runtime is too old, newest it has is GLIBCXX_3.4.21. Run without it or compile with gcc-4/gcc-5.
Or build in steamrt_scout_amd64 docker with `build-srt.sh`

**Comment by Desmo5574** [comment]
Is this a problem with linux steam in general when wanting to use MangoHud via Lutris or only particular to my machine? I've searched and it seems like I'm the only one to post about this.

**Comment by jackun** [comment]
It's general issue with steam linux runtime. Some functions use newer versions of them than they are in srt.

**Comment by StefanLobbenmeier** [comment]
> or only particular to my machine

I wanted to add that I also get this problem when launching through lutris, but not when launching through steam directly. I installed mangohud from aur: 
```
➜  ~ yay -Q mangohud
mangohud 0.6.1-2
```

**Comment by StefanLobbenmeier** [comment]
> Just needs a recompile with gcc-5.

can you clarify, do we have to recompile with gcc-5 to get rid of the mangohud dependency, or does valve need to recompile so we can use it?

**Comment by jackun** [comment]
Recompile mangohud with gcc-5 (see build-with-srt-docker.sh) or don't run steam with runtime enabled.

**Comment by jackun** [comment]
Try this built with [Steam's soldier SDK.](https://github.com/flightlessmango/MangoHud/releases/download/v0.6.1/Steam_runtime_MangoHud-0.6.1.r0.g079f67a_soldier-0.20201022.1.tar.gz)

**Comment by Desmo5574** [comment]
Thanks jackun...I get a different error now.

Warning: An unexpected error occurred while executing "/sbin/ldconfig -XNv", the exit status was 139
grep: symbol lookup error: /usr/lib/mangohud/lib/x86_64-linux-gnu/tls/x86_64/x86_64/libMangoHud.so: undefined symbol: _ZTVNSt7__cxx1119basic_istringstreamIcSt11char_traitsIcESaIcEEE, version GLIBCXX_3.4.21
grep: symbol lookup error: /usr/lib/mangohud/lib/x86_64-linux-gnu/tls/x86_64/x86_64/libMangoHud.so: undefined symbol: _ZTVNSt7__cxx1119basic_istringstreamIcSt11char_traitsIcESaIcEEE, version GLIBCXX_3.4.21
awk: symbol lookup error: /usr/lib/mangohud/lib/x86_64-linux-gnu/tls/x86_64/x86_64/libMangoHud.so: undefined symbol: _ZTVNSt7__cxx1119basic_istringstreamIcSt11char_traitsIcESaIcEEE, version GLIBCXX_3.4.21
grep: symbol lookup error: /usr/lib/mangohud/lib/x86_64-linux-gnu/tls/x86_64/x86_64/libMangoHud.so: undefined symbol: _ZTVNSt7__cxx1119basic_istringstreamIcSt11char_traitsIcESaIcEEE, version GLIBCXX_3.4.21
/home/kh/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/bin/steam-runtime-check-requirements: symbol lookup error: /usr/lib/mangohud/lib/x86_64-linux-gnu/tls/x86_64/x86_64/libMangoHud.so: undefined symbol: _ZTVNSt7__cxx1119basic_istringstreamIcSt11char_traitsIcESaIcEEE, version GLIBCXX_3.4.21
steam-runtime-check-requirements failed with an unexpected nonzero exit status. Trying to continue
/home/kh/.local/share/Steam/ubuntu12_32/steam steam://rungameid/514900
/home/kh/.local/share/Steam/ubuntu12_32/steam: symbol lookup error: /usr/lib/mangohud/lib/i386-linux-gnu/libMangoHud.so: undefined symbol: _ZTVNSt7__cxx1119basic_istringstreamIcSt11char_traitsIcESaIcEEE, version GLIBCXX_3.4.21

**Comment by jackun** [comment]
@Desmo5574 hmm, try this one then
[MangoHud-0.6.1.r1.ge71fb3d_soldier-0.20201022.1.tar.gz](https://github.com/flightlessmango/MangoHud/files/5641279/MangoHud-0.6.1.r1.ge71fb3d_soldier-0.20201022.1.tar.gz)

Some [ABI problems](https://wiki.debian.org/GCC5#Roadmap_for_libstdc.2B-.2B-) maybe...

**Comment by Desmo5574** [comment]
Hey jackun, 

Still no dice...no sweat though. I've been playing with Mangohud disabled. I'm using the Steam client soldier beta. 

Running Steam on neon 20.04 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Warning: An unexpected error occurred while executing "/sbin/ldconfig -XNv", the exit status was 139
grep: symbol lookup error: /usr/lib/mangohud/lib/x86_64-linux-gnu/tls/x86_64/x86_64/libMangoHud.so: undefined symbol: _ZTVNSt7__cxx1119basic_istringstreamIcSt11char_traitsIcESaIcEEE, version GLIBCXX_3.4.21
grep: symbol lookup error: /usr/lib/mangohud/lib/x86_64-linux-gnu/tls/x86_64/x86_64/libMangoHud.so: undefined symbol: _ZTVNSt7__cxx1119basic_istringstreamIcSt11char_traitsIcESaIcEEE, version GLIBCXX_3.4.21
awk: symbol lookup error: /usr/lib/mangohud/lib/x86_64-linux-gnu/tls/x86_64/x86_64/libMangoHud.so: undefined symbol: _ZTVNSt7__cxx1119basic_istringstreamIcSt11char_traitsIcESaIcEEE, version GLIBCXX_3.4.21
grep: symbol lookup error: /usr/lib/mangohud/lib/x86_64-linux-gnu/tls/x86_64/x86_64/libMangoHud.so: undefined symbol: _ZTVNSt7__cxx1119basic_istringstreamIcSt11char_traitsIcESaIcEEE, version GLIBCXX_3.4.21
/home/kh/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/bin/steam-runtime-check-requirements: symbol lookup error: /usr/lib/mangohud/lib/x86_64-linux-gnu/tls/x86_64/x86_64/libMangoHud.so: undefined symbol: _ZTVNSt7__cxx1119basic_istringstreamIcSt11char_traitsIcESaIcEEE, version GLIBCXX_3.4.21
steam-runtime-check-requirements failed with an unexpected nonzero exit status. Trying to continue
/home/kh/.local/share/Steam/ubuntu12_32/steam steam://rungameid/268870
/home/kh/.local/share/Steam/ubuntu12_32/steam: symbol lookup error: /usr/lib/mangohud/lib/i386-linux-gnu/libMangoHud.so: undefined symbol: _ZTVNSt7__cxx1119basic_istringstreamIcSt11char_traitsIcESaIcEEE, version GLIBCXX_3.4.21

**Comment by Desmo5574** [comment]
BTW, I've tried disabling the steam runtime and while the games launch after complaining about 32bit libraries, I don't ever see the Mangohud overlay.

**Comment by jackun** [comment]
Sure it installed correctly? I don't see it importing `__cxx11`  functions :P

**Comment by Desmo5574** [comment]
I'm pretty sure...I've tried both versions and this is the output of the one I just installed:

./mangohud-setup.sh install                                                                                                                                                                                                                                                                                                                                              ─╯
You can use the example configuration file from
/usr/share/doc/mangohud/MangoHud.conf.example
as a starting point by copying it to
/home/kh/.config/MangoHud/MangoHud.conf

install: creating directory '/usr/lib/mangohud'
install: creating directory '/usr/lib/mangohud/lib32'
'./usr/lib/mangohud/lib32/libMangoHud.so' -> '/usr/lib/mangohud/lib32/libMangoHud.so'
'./usr/lib/mangohud/lib32/libMangoHud_dlsym.so' -> '/usr/lib/mangohud/lib32/libMangoHud_dlsym.so'
install: creating directory '/usr/lib/mangohud/lib'
'./usr/lib/mangohud/lib/libMangoHud.so' -> '/usr/lib/mangohud/lib/libMangoHud.so'
'./usr/lib/mangohud/lib/libMangoHud_dlsym.so' -> '/usr/lib/mangohud/lib/libMangoHud_dlsym.so'
'./usr/share/vulkan/implicit_layer.d/MangoHud.json' -> '/usr/share/vulkan/implicit_layer.d/MangoHud.json'
install: creating directory '/usr/share/doc/mangohud'
'./usr/share/doc/mangohud/MangoHud.conf.example' -> '/usr/share/doc/mangohud/MangoHud.conf.example'
'./usr/share/man/man1/mangohud.1' -> '/usr/share/man/man1/mangohud.1'
'./usr/bin/mangohud' -> '/usr/bin/mangohud'
'/usr/lib/mangohud/tls/x86_64' -> '../lib'
'/usr/lib/mangohud/tls/i686' -> '../lib32'
'/usr/lib/mangohud/lib/i686-linux-gnu' -> '.'
'/usr/lib/mangohud/lib/x86_64-linux-gnu' -> '.'
'/usr/lib/mangohud/lib/tls' -> '../tls'
'/usr/lib/mangohud/lib64' -> 'lib'
'/usr/lib/mangohud/x86_64' -> 'lib'
'/usr/lib/mangohud/x86_64-linux-gnu' -> 'lib'
'/usr/lib/mangohud/lib/x86_64' -> '.'
'/usr/lib/mangohud/i686' -> 'lib32'
'/usr/lib/mangohud/i386-linux-gnu' -> 'lib32'
'/usr/lib/mangohud/lib/i386-linux-gnu' -> '../lib32'
'/usr/lib/mangohud/i686-linux-gnu' -> 'lib32'
'/usr/lib/mangohud/lib/i686-linux-gnu/lib32' -> '../lib32'
MangoHud Installed

**Comment by Desmo5574** [comment]
bizarre...oh well. Thanks for all your help and taking the time to help me troubleshoot. 
I'll try it again in 6 months time. Hopefully Valve has made some progress by then.
