### ISSUE TITLE
With Aion MMO mangohud does not load

### ISSUE THREAD

**Issue by plasticbomb1986** [flightlessmango/MangoHud#384]
Just recompiled it to check, its working with everything else i tried. The error i see in protonlog:

`ERROR: ld.so: object 'libMangoHud.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.`

Im not sure, what is it exactly meaning, what shared object it cant open with this game, but works with others?

**Comment by flightlessmango** [comment]
What graphics API is Aion and what launch options are you using?

**Comment by plasticbomb1986** [comment]
> What graphics API is Aion and what launch options are you using?
Its DX9 i think (maybe 10?), its using CryEngine, but im actually not sure which DX version its using. DXVK_HUD works.
PROTON_LOG=1 ENABLE_DEVICE_CHOOSER_LAYER=1 VULKAN_DEVICE_INDEX=1 %command%

This part (ENABLE_DEVICE_CHOOSER_LAYER=1 VULKAN_DEVICE_INDEX=1) is a vulkan device selector because i have two vega64 in my system, and almost not a single vulkan game render on my primary gpu, but always on the secondary, by default, and with this, i can override it.

**Comment by plasticbomb1986** [comment]
So, today tested with TK-Glitch custom proton build, with that, mangohud loads up (but the game lose mouse activity, cant click on anything), deleted the pfx and recreated it with proton 5.13.1, mangohud does not load.

[steam-261430.log](https://github.com/flightlessmango/MangoHud/files/5517287/steam-261430.log)

**Comment by flightlessmango** [comment]
Proton 5.13 has a known issue where MangoHud will not work by default #369

**Comment by plasticbomb1986** [comment]
> Proton 5.13 has a known issue where MangoHud will not work by default #369

Sorry, ive been editing that post for a while, adding more info, logs, and chrome sent it in at that state...

**Comment by flightlessmango** [comment]
To clarify, you're saying that if you use mangohud with proton-ge in this game, you get a system freeze?

**Comment by plasticbomb1986** [comment]
> To clarify, you're saying that if you use mangohud with proton-ge in this game, you get a system freeze?

OKay, you made me realise, i missed out something. Got so much used to mangoHUD, forgot to test those customs without it. Both of them freezing, not system freeze, but with both the game goes unresponsive. Gonna head over to them gits now.

**Comment by flightlessmango** [comment]
Closing this for now
