### ISSUE TITLE
How can I set that mangohud will be displayed by pressing meta?

### ISSUE THREAD

**Issue by Toadfield** [flightlessmango/MangoHud#386]
Maybe dumb question,but if I set `toggle_hud=SUPER+M`or `toggle_hud=META+M`it doesn't open with "META+M",but with only pressing M and that's not what I want.

**Comment by flightlessmango** [comment]
It's `Meta_L`/`Meta_R` and `Super_L`/`Super_R`

**Comment by Toadfield** [comment]
that works
