### ISSUE TITLE
Is there a way to enable mangohud globally for every opengl application?

### ISSUE THREAD

**Issue by Toadfield** [flightlessmango/MangoHud#387]
I can enable it globally for vulkan by setting the environment variables for mangohud in profile.d,but for opengl I need to start it with "mangohud" in front of the name (if I want to open in terminal) or adding it as a command prefix Lutris (and add all games to Lutris ) or adding it to all krunner and desktop shortcuts to make it work and I'm to lazy to do that and I want use it on most games/programs anyway.

**Comment by flightlessmango** [comment]
There is no way that I know of to globally enable for OpenGL
