### ISSUE TITLE
Not showing up with The King Of Fighters XIV - Steam Edition

### ISSUE THREAD

**Issue by ranplayer** [flightlessmango/MangoHud#389]
Hello,

mangohud works fine on my end with several titles, apis (OpenGL, Vulkan) and architectures (32, 64). I'm only having issues with the [The King Of Fighters XIV (Steam Edition)](https://store.steampowered.com/app/571260/THE_KING_OF_FIGHTERS_XIV_STEAM_EDITION/). The hud is not showing up.

I've tried to execute it with: `mangohud %command%` and `mangohud --dlsym %command%` (the game uses the OpenGL 4.3 API).

Do you know what might be wrong ? If any log file is required for analysis, let me know.

More info about the game at: https://www.pcgamingwiki.com/wiki/The_King_of_Fighters_XIV#Other_information

**Comment by flightlessmango** [comment]
Try again with MangoHud 0.6.1 please

**Comment by ranplayer** [comment]
I've tried again with 0.6.1, but the issue persists. Other games are working fine.

**Comment by Leopard1907** [comment]
Can you capture a frame of it with renderdoc?

**Comment by ranplayer** [comment]
I'm not familiar with this tool, but I'm going to try here.

**Comment by Leopard1907** [comment]
You can also try apitrace.

https://github.com/apitrace/apitrace

https://github.com/apitrace/apitrace/wiki/Steam#linux

**Comment by ranplayer** [comment]
Hi,

I've just captured the apitrace and uploaded to my Mega account. Here is the link: https://mega.nz/file/0st1mI6Q#YsaW-t1-YD4SBlRreLEXfWUq7TkrolSoAi6uEe3jPQk

**Comment by jackun** [comment]
@ranplayer can try the patch at https://github.com/flightlessmango/MangoHud/issues/338#issuecomment-803656893
Seems to work with apitrace replay.

**Comment by flightlessmango** [comment]
Reopen if still an issue
