### ISSUE TITLE
hotkey ignores #comment

### ISSUE THREAD

**Issue by arrowgent** [flightlessmango/MangoHud#39]
```
### Change toggle keybinds for the hud & logging
# toggle_hud=F12
# toggle_logging=F2
```

F12 is default screenshot button.
pressing F12 still toggles the hud on and off....
setting =0 does disable it
```
toggle_hud=0
toggle_logging=0
```
i have by default to hide the hud.
```
### Disable / hide the hud by deafult
no_display
```

**Comment by flightlessmango** [comment]
in what location is this config file?

**Comment by arrowgent** [comment]
default installed file

/home/catbox/.config/MangoHud/MangoHud.conf

**Comment by flightlessmango** [comment]
does it work if you set it manually with the environment variable? `MANGOHUD=toggle_hud=0,toggle_logging=0`

**Comment by arrowgent** [comment]
```MANGOHUD=1 MANGOHUD_CONFIG=toggle_hud=0,toggle_logging=0 %command%```
steam proton 5.02
launch option

Nvidia 440.59
Vulkan Instance Version: 1.2.131
apiVersion     = 4198519 (1.1.119)

seems to work

earlier the HUD came back and all i did was exit to the menu
wierd

**Comment by flightlessmango** [comment]
it sounds like the file is being overridden by another config file or it's not being read, if you run `MANGOHUD=1 vkcube` he should print some info about configs in console. Can you paste that here?

**Comment by arrowgent** [comment]
parsing config: /home/catbox/.local/share/MangoHud/MangoHud.conf [ ok ]
parsing config: /home/catbox/.config/MangoHud/MangoHud.conf [ ok ]
skipping config: /home/catbox/.config/MangoHud/vkcube.conf
skipping config: /usr/bin/MangoHud.conf
cat: /etc/upstream-release: Is a directory

ahh i see, its in .local also hmm
maybe i should create a syslink

**Comment by arrowgent** [comment]
although my settings in .config override the other

**Comment by arrowgent** [comment]
mv .local to MangoHud.conf.bak

skipping config: /home/catbox/.local/share/MangoHud/MangoHud.conf
parsing config: /home/catbox/.config/MangoHud/MangoHud.conf [ ok ]
skipping config: /home/catbox/.config/MangoHud/vkcube.conf
skipping config: /usr/bin/MangoHud.conf
cat: /etc/upstream-release: Is a directory


symlink .config to .local
~/.local/share/MangoHud $ ln -s ~/.config/MangoHud.conf

seems to skip it also

MANGOHUD=1 vkcube
skipping config: /home/catbox/.local/share/MangoHud/MangoHud.conf
parsing config: /home/catbox/.config/MangoHud/MangoHud.conf [ ok ]
skipping config: /home/catbox/.config/MangoHud/vkcube.conf
skipping config: /usr/bin/MangoHud.conf
cat: /etc/upstream-release: Is a directory

**Comment by arrowgent** [comment]
yeah so the problem being seems to be pulling multiple .conf files and doesnt set a priority for which rules to follow

thanks a lot!  that helps track down some further config setup
