### ISSUE TITLE
src/meson.build:1:0: ERROR:  Program(s) ['glslangValidator'] not found or not executable

### ISSUE THREAD

**Issue by munish259272** [flightlessmango/MangoHud#391]
[msingh@localhost MangoHud]$ ./build.sh build
Command: build 
# Checking Dependencies
# Unable to find distro information!
# Attempting to build regardless
The Meson build system
Version: 0.49.2
Source dir: /home/msingh/Extrasoftware/MangoHud
Build dir: /home/msingh/Extrasoftware/MangoHud/build/meson64
Build type: native build
Project name: MangoHud
Project version: v0.5.1
Native C compiler: cc (gcc 8.3.1 "cc (GCC) 8.3.1 20191121 (Red Hat 8.3.1-5)")
Native C++ compiler: c++ (gcc 8.3.1 "c++ (GCC) 8.3.1 20191121 (Red Hat 8.3.1-5)")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Checking if "GCC atomic builtins" compiles: YES
Checking if "Supports timespec_get" compiles: YES
Checking for function "bswap32" : YES
Checking for function "bswap64" : YES
Checking for function "clz" : YES
Checking for function "clzll" : YES
Checking for function "ctz" : YES
Checking for function "expect" : YES
Checking for function "ffs" : YES
Checking for function "ffsll" : YES
Checking for function "popcount" : YES
Checking for function "popcountll" : YES
Checking for function "unreachable" : YES
Found pkg-config: /usr/bin/pkg-config (1.4.2)
Dependency x11 found: YES 1.6.8
Dependency wayland-client skipped: feature with_wayland disabled
Dependency vulkan skipped: feature use_system_vulkan disabled
Dependency threads found: YES 
Dependency dbus-1 found: YES 1.12.8
Compiler for C supports arguments -Werror=implicit-function-declaration: YES
Compiler for C supports arguments -Werror=missing-prototypes: YES
Compiler for C supports arguments -Werror=return-type: YES
Compiler for C supports arguments -Werror=incompatible-pointer-types: YES
Compiler for C supports arguments -fno-math-errno: YES
Compiler for C supports arguments -fno-trapping-math: YES
Compiler for C supports arguments -Qunused-arguments: NO
Compiler for C supports arguments -Wmissing-field-initializers: YES
Compiler for C supports arguments -Wformat-truncation: YES
Compiler for C++ supports arguments -Werror=return-type: YES
Compiler for C++ supports arguments -fno-math-errno: YES
Compiler for C++ supports arguments -fno-trapping-math: YES
Compiler for C++ supports arguments -Qunused-arguments: NO
Compiler for C++ supports arguments -Wnon-virtual-dtor: YES
Compiler for C++ supports arguments -Wmissing-field-initializers: YES
Compiler for C++ supports arguments -Wformat-truncation: YES
Compiler for C supports arguments -Woverride-init: YES
Compiler for C supports arguments -Winitializer-overrides: NO
Checking for function "dlopen" : NO
Library dl found: YES
Checking for function "clock_gettime" : YES
Downloading vulkan-headers source from https://github.com/KhronosGroup/Vulkan-Headers/archive/v1.2.142.tar.gz
Downloading file of unknown size.
Downloading vulkan-headers patch from https://wrapdb.mesonbuild.com/v1/projects/vulkan-headers/1.2.142/1/get_zip
Download size: 1106
Downloading: ..........

|
|Executing subproject vulkan-headers 
|
|Project name: vulkan-headers
|Project version: 1.2.142
|Native C compiler: cc (gcc 8.3.1 "cc (GCC) 8.3.1 20191121 (Red Hat 8.3.1-5)")
|Build targets in project: 1
|
|Subproject vulkan-headers finished.
Checking for size of "void*" : 8

|
|Executing subproject dearimgui 
|
|Project name: Dear ImGui core library
|Project version: 1.78-WIP-tables-fe3637fa607257ff83bf61092d2173f83b311527
|Native C++ compiler: c++ (gcc 8.3.1 "c++ (GCC) 8.3.1 20191121 (Red Hat 8.3.1-5)")
|Build targets in project: 3
|
|Subproject dearimgui finished.
Program glslangValidator found: NO

src/meson.build:1:0: ERROR:  Program(s) ['glslangValidator'] not found or not executable

A full log can be found at /home/msingh/Extrasoftware/MangoHud/build/meson64/meson-logs/meson-log.txt

[
[meson-log.txt](https://github.com/flightlessmango/MangoHud/files/5529669/meson-log.txt)
](url)

The build is failing

**Comment by stephanlachnit** [comment]
Distro?

**Comment by munish259272** [comment]
Centos 8 : 

Now i tried by downloading the tar file and that one also does not work

[msingh@localhost bin]$ ./mangohud-setup.sh install
You can use the example configuration file from
/usr/share/doc/mangohud/MangoHud.conf.example
as a starting point by copying it to
/home/msingh/.config/MangoHud/MangoHud.conf

tar: MangoHud-package.tar: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
[sudo] password for msingh: 
removed directory '/usr/lib/mangohud/lib32'
removed '/usr/lib/mangohud/lib/x86_64'
removed '/usr/lib/mangohud/lib/x86_64-linux-gnu'
removed '/usr/lib/mangohud/lib/i386-linux-gnu'
removed '/usr/lib/mangohud/lib/i686-linux-gnu'
removed directory '/usr/lib/mangohud/lib'
removed '/usr/lib/mangohud/lib64'
removed '/usr/lib/mangohud/x86_64'
removed '/usr/lib/mangohud/x86_64-linux-gnu'
removed '/usr/lib/mangohud/i686'
removed '/usr/lib/mangohud/i386-linux-gnu'
removed '/usr/lib/mangohud/i686-linux-gnu'
removed directory '/usr/lib/mangohud'
removed directory '/usr/share/doc/mangohud'
install: creating directory '/usr/lib/mangohud'
install: creating directory '/usr/lib/mangohud/lib32'
install: cannot stat './usr/lib/mangohud/lib32/libMangoHud.so': No such file or directory
install: cannot stat './usr/lib/mangohud/lib32/libMangoHud_dlsym.so': No such file or directory
install: creating directory '/usr/lib/mangohud/lib'
install: cannot stat './usr/lib/mangohud/lib/libMangoHud.so': No such file or directory
install: cannot stat './usr/lib/mangohud/lib/libMangoHud_dlsym.so': No such file or directory
install: cannot stat './usr/share/vulkan/implicit_layer.d/MangoHud.json': No such file or directory
install: creating directory '/usr/share/doc/mangohud'
install: cannot stat './usr/share/doc/mangohud/MangoHud.conf.example': No such file or directory
install: cannot stat './usr/share/man/man1/mangohud.1': No such file or directory
install: cannot stat './usr/bin/mangohud': No such file or directory
'/usr/lib/mangohud/lib64' -> 'lib'
'/usr/lib/mangohud/x86_64' -> 'lib'
'/usr/lib/mangohud/x86_64-linux-gnu' -> 'lib'
'/usr/lib/mangohud/lib/x86_64' -> '.'
'/usr/lib/mangohud/lib/x86_64-linux-gnu' -> '.'
'/usr/lib/mangohud/i686' -> 'lib32'
'/usr/lib/mangohud/i386-linux-gnu' -> 'lib32'
'/usr/lib/mangohud/lib/i386-linux-gnu' -> '../lib32'
'/usr/lib/mangohud/i686-linux-gnu' -> 'lib32'
'/usr/lib/mangohud/lib/i686-linux-gnu' -> '../lib32'
MangoHud Installed

**Comment by flightlessmango** [comment]
You will need to install all the dependencies required to build. I don't consider this a MangoHud Issue, I would recommend you jump in on discord and ask for help instead
