### ISSUE TITLE
All wine apps stops working after installing mangohud

### ISSUE THREAD

**Issue by Meister1593** [flightlessmango/MangoHud#394]
**System:**
Arch linux, 5.9.8-zen1 kernel (same issue goes for all kernels from official repos)
Gpu: AMD XFX RX 480 4 GB
Mangohud is from AUR (both [mangohud](https://aur.archlinux.org/packages/mangohud/) and [mangohud-git](https://aur.archlinux.org/packages/mangohud-git/) versions tested)

**Explanation:**
Basically, after installation, any game launched from any wine (including proton) in system becomes broken
Every wine app (including usual apps, not games) launches with small amount of ram and does nothing.
After removing mangohud, all wine apps starts working just fine.

**Comment by gort818** [comment]
Just installing mangohud makes your wine programs not work?

**Comment by Meister1593** [comment]
> Just installing mangohud makes your wine programs not work?

Exactly, there's no useful logging with default wine debug settings, but with `all` it outputs alot, ALOT of text after about 5-10 second it stops with this text at the end:
`000d: select() = PENDING { call={APC_NONE}, apc_handle=0000, context={} }`
It can do that multiple times and then again stop with this: `0030: *killed* exit_code=0`
but app is still *running*

As far as i can see it somehow makes launching for wine either really, REALLY slow, or affects it in another way

**Comment by flightlessmango** [comment]
What about native apps? does vkcube work and if it does, does it work with mangohud?

**Comment by Meister1593** [comment]
> What about native apps? does vkcube work and if it does, does it work with mangohud?

vkcube works
![image](https://user-images.githubusercontent.com/7141787/99182342-e1d91f00-274d-11eb-83b1-30e60b3ab350.png)

**Comment by flightlessmango** [comment]
MangoHud doesn't start without being enabled, check your `~/.profile`, `/etc/environment ` etc

**Comment by Meister1593** [comment]
> MangoHud doesn't start without being enabled, check your `~/.profile`, `/etc/environment ` etc

It turns out that i had `export MANGOHUD=1` in .profile whole time.
Not even sure that i created this by myself, but whatever i guess, one issue solved.
It seems that any game that runs with mangohud doesn't start.

**Comment by gort818** [comment]
Can you try setting `NODEVICE_SELECT=1`

**Comment by Meister1593** [comment]
> Can you try setting `NODEVICE_SELECT=1`

Game runs after that, what it does?

**Comment by flightlessmango** [comment]
Could you try if the mesa overlay works without this workaround?

**Comment by Meister1593** [comment]
> Could you try if the mesa overlay works without this workaround?

It seems that after setting `VK_INSTANCE_LAYERS=VK_LAYER_MESA_overlay` (mesa overlay) apps stops working exactly like with mangohud.

**Comment by flightlessmango** [comment]
Mesa issue related to this
https://gitlab.freedesktop.org/mesa/mesa/-/issues/3801
