### ISSUE TITLE
Does mangohud change how a 3D application starts and renders? How?

### ISSUE THREAD

**Issue by Ashe** [flightlessmango/MangoHud#397]
Hey there,

I don't really know how Mangohud works, all I know is that I love it. I use it when testing all my projects and is incredibly useful. 

I started a new project lately, and I'm trying to get it to work with mangohud. For some reason, my project crashes whenever I try to use mangohud, but is perfectly fine without. I wanted to ask why this is the case, and whether there's actually some issue with my work, or whether it's just a snag when using mangohud.

The error I'm having is a divide by 0 error, and occurs during glfw's `create window` function. I'm suspecting that the way mangohud injects itself might have an adverse effect somehow, and I'd just like some advice on what could be going on if that's okay. Here's the full error along with the command I used:

```lisp
❯ LD_PRELOAD=/usr/lib/libMangoHud_dlsym.so mangohud ./build/tides
skipping config: /home/ashe/Documents/tides/build/MangoHud.conf [ not found ]
skipping config: /home/ashe/.config/MangoHud/tides.conf [ not found ]
parsing config: /home/ashe/.config/MangoHud/MangoHud.conf [ ok ]

debugger invoked on a DIVISION-BY-ZERO in thread
#<THREAD "main thread" RUNNING {1000C380D3}>:
  arithmetic error DIVISION-BY-ZERO signalled

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [STOP ] Stop the task.
  1: [ABORT] Exit from the current thread.

("bogus stack frame")
0] BACKTRACE 10

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1000C380D3}>
0: ("bogus stack frame")
1: (CL-GLFW3:CREATE-WINDOW :WIDTH 600 :HEIGHT 400 :TITLE "Tides" :MONITOR NIL :SHARED NIL :RESIZABLE T :VISIBLE T :DECORATED T :RED-BITS 8 :GREEN-BITS 8 :BLUE-BITS 8 :ALPHA-BITS 8 :DEPTH-BITS 24 :STENCIL-BITS 8 :ACCUM-RED-BITS 0 :ACCUM-GREEN-BITS 0 :ACCUM-BLUE-BITS 0 :ACCUM-ALPHA-BITS 0 :AUX-BUFFERS 0 :SAMPLES 0 :REFRESH-RATE 0 :STEREO NIL :SRGB-CAPABLE NIL :CLIENT-API :OPENGL-API :CONTEXT-VERSION-MAJOR 1 :CONTEXT-VERSION-MINOR 0 :CONTEXT-ROBUSTNESS :NO-ROBUSTNESS :OPENGL-FORWARD-COMPAT NIL :OPENGL-DEBUG-CONTEXT NIL :OPENGL-PROFILE :OPENGL-ANY-PROFILE)
2: ((LAMBDA NIL :IN TIDES:MAIN))
3: ((:METHOD SIMPLE-TASKS:RUN-TASK (SIMPLE-TASKS:CALL-TASK)) #<SIMPLE-TASKS:CALL-TASK :FUNC #<FUNCTION (LAMBDA NIL :IN TIDES:MAIN) {521E30CB}> :STATUS :ERRORED {1002E05713}>) [fast-method]
4: ((:METHOD SIMPLE-TASKS:RUN-TASK :AROUND (SIMPLE-TASKS:TASK)) #<SIMPLE-TASKS:CALL-TASK :FUNC #<FUNCTION (LAMBDA NIL :IN TIDES:MAIN) {521E30CB}> :STATUS :ERRORED {1002E05713}>) [fast-method]
5: ((:METHOD SIMPLE-TASKS:SCHEDULE-TASK (T SIMPLE-TASKS:RUNNER)) #<SIMPLE-TASKS:CALL-TASK :FUNC #<FUNCTION (LAMBDA NIL :IN TIDES:MAIN) {521E30CB}> :STATUS :ERRORED {1002E05713}> #<unused argument>) [fast-method]
6: ((SB-PCL::EMF SIMPLE-TASKS:SCHEDULE-TASK) #<unused argument> #<unused argument> #<SIMPLE-TASKS:CALL-TASK :FUNC #<FUNCTION (LAMBDA NIL :IN TIDES:MAIN) {521E30CB}> :STATUS :ERRORED {1002E05713}> #<SIMPLE-TASKS:RUNNER :STATUS :RUNNING {1001514AD3}>)
7: (SIMPLE-TASKS:CALL-AS-TASK #<FUNCTION (LAMBDA NIL :IN TIDES:MAIN) {521E30CB}> #<SIMPLE-TASKS:RUNNER :STATUS :RUNNING {1001514AD3}> SIMPLE-TASKS:CALL-TASK)
8: ((FLET SB-UNIX::BODY :IN SB-IMPL::START-LISP))
9: ((FLET "WITHOUT-INTERRUPTS-BODY-1" :IN SB-IMPL::START-LISP))
```

Here's the locals of GLFW 3 at the time of creating the window (not that I can see anything wrong with any of them?):
```
#:.DEFAULTING-TEMP.  =  NIL
#:.DEFAULTING-TEMP.#1  =  NIL
#:.DEFAULTING-TEMP.#2  =  :OPENGL-API
#:.DEFAULTING-TEMP.#3  =  :NO-ROBUSTNESS
#:.DEFAULTING-TEMP.#4  =  :OPENGL-ANY-PROFILE
CL-GLFW3::ACCUM-ALPHA-BITS  =  0
CL-GLFW3::ACCUM-BLUE-BITS  =  0
CL-GLFW3::ACCUM-GREEN-BITS  =  0
CL-GLFW3::ACCUM-RED-BITS  =  0
CL-GLFW3::ALPHA-BITS  =  8
CL-GLFW3::AUX-BUFFERS  =  0
CL-GLFW3::BLUE-BITS  =  8
CL-GLFW3::CONTEXT-VERSION-MAJOR  =  1
CL-GLFW3::CONTEXT-VERSION-MINOR  =  0
CL-GLFW3::DECORATED  =  T
CL-GLFW3::DEPTH-BITS  =  24
CL-GLFW3::GREEN-BITS  =  8
CL-GLFW3::HEIGHT  =  400
#:N-SUPPLIED-0  =  0
#:N-SUPPLIED-1  =  0
CL-GLFW3::OPENGL-DEBUG-CONTEXT  =  NIL
CL-GLFW3::OPENGL-FORWARD-COMPAT  =  NIL
CL-GLFW3::RED-BITS  =  8
CL-GLFW3::REFRESH-RATE  =  0
CL-GLFW3::RESIZABLE  =  T
CL-GLFW3::SAMPLES  =  0
CL-GLFW3::SRGB-CAPABLE  =  NIL
CL-GLFW3::STENCIL-BITS  =  8
CL-GLFW3::STEREO  =  NIL
CL-GLFW3::TITLE  =  "Tides"
CL-GLFW3::VISIBLE  =  T
CL-GLFW3::WIDTH  =  600
```

Snippets of (common lisp) source code is available on request since this repo is still private for now, however I don't really know how it could go wrong since it's fine without mangohud.

I look forward to understanding mangohud's usage a little more, and perhaps this issue will help others in the future using mangohud for development :)

**Comment by jackun** [comment]
> arithmetic error DIVISION-BY-ZERO signalled

FPS/frametime calculation probably relies too much on div-by-zero exception being disabled

**Comment by baryluk** [comment]
Do you know if this is integer or floating point division by zero?

By default most programming languages default to not trap on floating point division by zero, and return +inf, -inf, or NaN.

Integer division on most architectures always traps. It there is integer division, then it is a bug in mangohud.

**Comment by flightlessmango** [comment]
https://github.com/flightlessmango/MangoHud/blob/96bf79775ce68d94f78f926bc6bc6c9aaa6d5db2/src/overlay.cpp#L1442
Assuming this is what we're talking about, `data.fps` is a double

**Comment by baryluk** [comment]
Yeah, it looks like SBCL do default to trapping floating point divide-by-zero and overflow exceptions.

My guess, the GLFW3 or OpenGL wrapper in SBCL doesn't properly set FPU exception handling flags on entry to C APIs.


@Ashe You can try doing:

```c
fenv_t envp;
fegetenv(&envp);
fesetenv(FE_DFL_ENV);

some_C_functions();

fesetenv(&envp);
```

Of course mangohud could add special handling for division by zero, but that is just a hack, and there might be hundredths of other places where this would show up. It is a not mangohud bug.

**Comment by Ashe** [comment]
> Yeah, it looks like SBCL do default to trapping floating point divide-by-zero and overflow exceptions.
> 
> My guess, the GLFW3 or OpenGL wrapper in SBCL doesn't properly set FPU exception handling flags on entry to C APIs.
> 
> @Ashe You can try doing:
> 
> ```c
> fenv_t envp;
> fegetenv(&envp);
> fesetenv(FE_DFL_ENV);
> 
> some_C_functions();
> 
> fesetenv(&envp);
> ```
> 
> Of course mangohud could add special handling for division by zero, but that is just a hack, and there might be hundredths of other places where this would show up. It is a not mangohud bug.

Thank you so much for everyone's responses, especially this one. I was able to fix my stuff thanks to your advice. I didn't really know what to do since it only occurred when using mangohud, but this was the answer. I hope someone in need finds this issue useful in the future :)
