### ISSUE TITLE
Is it possible to change Mangohud settings while the game is running?

### ISSUE THREAD

**Issue by Toadfield** [flightlessmango/MangoHud#399]
It would be cool to be able to change the settings in game instead of going out of the game and start it again.
I know it needs more performance,but it would be cool to be able to enable it.
Or is it already possible,but I'm to lost to use it?

**Comment by gort818** [comment]
A lot of settings can be changed while the game is running edit the config file and save it and it should reload.

**Comment by Toadfield** [comment]
I will try that later

**Comment by Toadfield** [comment]
Yeah,I can change all the things I want in game.
