### ISSUE TITLE
Issue with installing MangoHud

### ISSUE THREAD

**Issue by ahmed-elsayed2017** [flightlessmango/MangoHud#4]
I followed your install instruction, but **./build.sh install** ends up with this error message:
```
In file included from ../../src/mesa/util/hash_table.c:50:
../../src/mesa/util/../main/hash.h:36:10: fatal error: GL/gl.h: No such file or directory
   36 | #include <GL/gl.h>
      |          ^~~~~~~~~
compilation terminated.
[6/8] Compiling C++ object 'src/25a6634@@MangoHud@sha/cpu.cpp.o'.
ninja: build stopped: subcommand failed.
```
I use Kubuntu 19.10

**Comment by jackun** [comment]
build.sh should install it but try manually installing `mesa-common-dev` package.

**Comment by ahmed-elsayed2017** [comment]
> build.sh should install it but try manually installing `mesa-common-dev` package.

It is already installed. It will be nice to have releases with the ability to install directly instead of building first.

**Comment by telans** [comment]
I can't replicate this unfortunately. Does `gl.h` exist inside `/usr/include/GL/`?

**Comment by ahmed-elsayed2017** [comment]
> I can't replicate this unfortunately. Does `gl.h` exist inside `/usr/include/GL/`?

No, this file doesn't exist.

**Comment by telans** [comment]
It certainly should according to: https://packages.ubuntu.com/eoan/amd64/mesa-common-dev/filelist

Can you reinstall `mesa-common-dev`?

**Comment by ahmed-elsayed2017** [comment]
> It certainly should according to: https://packages.ubuntu.com/eoan/amd64/mesa-common-dev/filelist
> 
> Can you reinstall `mesa-common-dev`?

Reinstalling it does nothing, but I found that `mesa-common-dev` is installed from obiaf ppa that I use to upgrade Mesa, so I forced this package to be installed from Ubuntu main repository, and that solved this issue.

**Comment by jackun** [comment]
oibaf ppa has it in `libgl-dev`.

**Comment by ahmed-elsayed2017** [comment]
Thanks for your help, I have another issue with using MangoHud.

 https://github.com/flightlessmango/MangoHud/issues/5

**Comment by ahmed-elsayed2017** [comment]
> libgl-dev

This package can't be found.
