### ISSUE TITLE
MangoHud incompatible with EA Origin

### ISSUE THREAD

**Issue by gardotd426** [flightlessmango/MangoHud#40]
No matter what I do, on multiple different Wineprefixes for different games I have installed on EA Origin, MangoHud crashes Origin immediately after the window opens. The HUD shows up for a moment, the little thing starts spinning, and then it freezes, crashes, and the "Origin has experienced a problem and must close" window pops up, no matter what. I've tried it with both a manually-built install and just a release download install, on separate Wineprefixes with separate Origin installs for Jedi Fallen Order, Titanfall 2, and Battlefield V. None of them seem to work, and I didn't see an issue on the issues threads. Also, while typing this, I figured I'd try the AUR packages, and still got the same result. 
Distribution: Arch Linux
Kernel: 5.6.0-rc1-1-tkg-pds
mesa: mesa-tkg-git-20.1.0_devel
```
yay -Q | grep -ie vulkan -ie mesa
lib32-mesa-demos 8.4.0-1
lib32-mesa-tkg-git 20.1.0_devel.120191.a603822b2fc-1
lib32-vulkan-icd-loader 1.2.132-1
mesa-demos 8.4.0-2
mesa-tkg-git 20.1.0_devel.120191.a603822b2fc-1
vulkan-caps-viewer 2.03-2
vulkan-headers 1:1.2.132-1
vulkan-html-docs 1:1.2.132-1
vulkan-icd-loader 1.2.132-1
vulkan-tools 1.2.131.1-1
```

**Comment by flightlessmango** [comment]
MangoHud works fine otherwise? vkcube for example runs with MangoHud?

**Comment by gardotd426** [comment]
Yeah, it works, but in a rather weird way. It makes vkcubepp like, FLY. Like the speed at which vkcubepp spins with `MANGOHUD=1` set is insane. Like the cube spins like hundreds of times a second instead of like once a second like it does without MANGOHUD on. No idea why, but [here's what I mean](https://imgur.com/a/4nVG4bq). That's literally just like a 12 second imgur clip that shows me open up vkcubepp both with mangohud and without.

**Comment by Sporif** [comment]
I experience the same with origin unless I blacklist it with this [patch](https://gist.github.com/Sporif/a8b8ce94966b03810416bd3a9a06a2c0)

**Comment by Sporif** [comment]
@gardotd426 The fast spinning is due to the high framerate which itself is because vsync is being disabled by mangohud. So what you see is expected if you have `vsync=1` (i.e off) in your mangohud config.

**Comment by gardotd426** [comment]
Ah okay, yeah I have vsync off, I didn't think about that. Okay then yes,
in that case it's working as expected in vkcubepp. I'm cloning a fresh git
right now to test the patch you mentioned.

**Comment by gardotd426** [comment]
Somethings wrong with the whole thing now. It clones the repo and submodules apparently without error, but it doesn't include everything, and it fails to build with numerous errors about build files not existing as they should. Not only that, but the patch doesn't work (it seems to already have been applied):
```
git clone --recurse-submodules https://github.com/flightlessmango/MangoHud.git

Cloning into 'MangoHud'...
remote: Enumerating objects: 99, done.
remote: Counting objects: 100% (99/99), done.
remote: Compressing objects: 100% (66/66), done.
remote: Total 889 (delta 51), reused 68 (delta 32), pack-reused 790
Receiving objects: 100% (889/889), 39.98 MiB | 581.00 KiB/s, done.
Resolving deltas: 100% (569/569), done.
Submodule 'modules/ImGui/src' (https://github.com/flightlessmango/ImGui.git) registered for path 'modules/ImGui/src'
Cloning into '/home/matt/MangoHud/modules/ImGui/src'...
remote: Enumerating objects: 32588, done.
remote: Total 32588 (delta 0), reused 0 (delta 0), pack-reused 32588
Receiving objects: 100% (32588/32588), 48.91 MiB | 1.06 MiB/s, done.
Resolving deltas: 100% (24358/24358), done.
Submodule path 'modules/ImGui/src': checked out '6c1a73774dabd2be64f85543b1286e44632d1905'
```
After copying the patch into the MangoHud directory and cd-ing into it:
```
patch -Np1 -i origin.patch
patching file src/overlay.cpp
Hunk #1 succeeded at 2661 with fuzz 1.
patching file src/overlay.cpp
Reversed (or previously applied) patch detected!  Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file src/overlay.cpp.rej
```
Trying to run ./build.sh install: (I'll just add the end the rest will be [here](https://pastebin.com/AqxsVw8k) )
```
[23/25] Compiling C++ object 's...oHud@sha/overlay_params.cpp.o'
ninja: build stopped: subcommand failed.
cp: cannot stat 'build/release/usr/lib32/libMangoHud.so': No such file or directory
cp: cannot stat 'build/release/usr/lib64/libMangoHud.so': No such file or directory
cp: cannot stat 'build/release/usr/share/vulkan/implicit_layer.d/mangohud.json': No such file or directory
cp: cannot stat 'build/release/usr/share/vulkan/implicit_layer.d/mangohud.json': No such file or directory
sed: can't read build/package/MangoHud/.local/share/vulkan/implicit_layer.d/mangohud32.json: No such file or directory
```

**Comment by Sporif** [comment]
@gardotd426 Try adding a newline to the end of the patch file, it seems I missed adding one when I copied into the gist.

**Comment by gardotd426** [comment]
@Sporif I'm sorry but I have no idea what you're talking about man, I know how to apply patches but I have no idea what's supposed to be in this newline, sorry I'm not a developer and I try but I can't learn anything without being told or being able to find for myself what something is. I added `\n` at the end but obviously that's not it. But that was the only thing I could find for C, which is what the program is written in and since I obviously have no idea what I'm doing that was the only thing I could go on.

**Comment by Sporif** [comment]
@gardotd426 I simply mean to press enter at the end of the file i.e one extra empty line. And I updated the gist so you can just re-download it instead.

**Comment by gardotd426** [comment]
I thought that's what you meant, but then I was like "wait, he said
'newline' and not 'new line', and I know 'newline' is actually a specific
character in a lot of programming languages, so what do I do?????" but
alright I'll try again.

**Comment by gardotd426** [comment]
Now it just flat-out fails to patch (and yes, I downloaded your patch as opposed to adding a new line myself):
```
patch -Np1 -i ~/blacklist.patch
patching file src/overlay.cpp
Hunk #1 FAILED at 2661.
1 out of 1 hunk FAILED -- saving rejects to file src/overlay.cpp.rej
```

**Comment by Sporif** [comment]
@gardotd426 Did you reset the git repo? Otherwise I have no idea what's wrong because I just re-downloaded it and patched without problems.

**Comment by gardotd426** [comment]
Yeah I cloned a fresh git repo and it finally worked. Thanks man

**Comment by jackun** [comment]
@Sporif [blacklist](https://github.com/flightlessmango/MangoHud/tree/blacklist) support

**Comment by Sporif** [comment]
@jackun Thanks. Maybe the blacklist should be checked for the layer specific stuff in `overlay_CreateInstance` and `overlay_CreateDevice`. And a config option to specify blacklisted and/or whitelisted programs would be nice, I will try to implement it myself.

**Comment by jackun** [comment]
Oops, the fonts got destroyed. Should be working now even without blacklist, but it would be nice to not render the hud on Origin etc.

**Comment by flightlessmango** [comment]
Seems to be fixed in master

**Comment by DanielRios549** [comment]
This was fixed in master, but there is no release for it, the latest version still not working, still showing up and crashing Origin. Maybe a continuous release with latest changes could be a great option
