### ISSUE TITLE
Provide additional env variables to control Vulkan and OpenGL separately

### ISSUE THREAD

**Issue by baryluk** [flightlessmango/MangoHud#402]
Hi,

I am testing Mesa Zink, which implements OpenGL using Mesa Gallium framework, on top of Vulkan, usually Mesa Vulkan drivers. It just got to the point where many benchmarks can be run running at a very good performance levels. So I want to run a bunch of comparisson between Zink and native OpenGL drivers. I am particularly interested of performance between radeonsi OpenGL and zink+radv-aco.

So, the problem is, when one enables zink (`MESA_LOADER_DRIVER_OVERRIDE=zink` usually does the trick, you might want to disable `GALLIUM_HUD` if you use one), an app would technically use both OpenGL and Vulkan in a sense.

I would like to be able to either load just Vulkan, or just OpenGL mangohud, so I can look at overheads and frametimes at separate levels.

A set of per-Vulkan and per-OpenGL environment variables, that do default to the non-specific ones, if not provided manually, would be really useful.

As a bonus I would like to be able to load both at the same time, but gather statistics independently and log to separate files, then correlate things using timestamps and frame counters. (I usually analyse these things in gnuplot, or using custom `awk` or `python3` scripts).

**Comment by flightlessmango** [comment]
`MANGOHUD=1` only loads the Vulkan mangohud
For OpenGL you can `LD_PRELOAD` the library

**Comment by baryluk** [comment]
@flightlessmango Oh. I will take a look at this and report. Should I do mess around with `VK_INSTANCE_LAYERS` maybe?

**Comment by flightlessmango** [comment]
you can also use `VK_INSTANCE_LAYERS`. but I'm pretty sure it's basically identical to using `MANGOHUD=1`

**Comment by baryluk** [comment]
It does appear to be working in `glxgears`, but I am not sure which layer it is intercepting exactly at the moment. It does say "OpenGL 3.0" in the HUD, so I assume it intercepted OpenGL stuff.

However, in Unigine Heaven 4.0 (64-bit version), it is different story:

`user@debian:~/Downloads/h/Unigine_Heaven-4.0/bin$ MESA_LOADER_DRIVER_OVERRIDE=zink  RADV_PERFTEST= GALLIUM_HUD= LD_LIBRARY_PATH="./x64:/home/user/MangoHud/build/release/usr/lib/mangohud/lib/" vblank_mode=0 MANGOHUD_CONFIG=time,output_folder=/tmp/mangohud-output,log_interval=0,log_duration=1000 MANGOHUD=1 LD_PRELOAD=libMangoHud_dlsym.so:libMangoHud.so NODEVICE_SELECT=1  ./heaven_x64 -project_name Heaven -data_path ../ -engine_config ../data/heaven_4.0.cfg -system_script heaven/unigine.cpp -sound_app openal -video_app opengl -video_multisample 3 -video_fullscreen 0 -video_mode 5 -extern_define ,RELEASE,LANGUAGE_EN,QUALITY_ULTRA,TESSELLATION_EXTREME -extern_plugin ,GPUMonitor
`

```
Loading "/home/user/.Heaven/heaven_4.0.cfg"...
Loading "libGPUMonitor_x64.so"...
Loading "libGL.so.1"...
Loading "libopenal.so.1"...
Set 1600x900 windowed video mode
ATTENTION: default value of option vblank_mode overridden by environment.
ATTENTION: default value of option vblank_mode overridden by environment.
MANGOHUD: Uploading is disabled (permit_upload = 0)
Version: 3.0 
X Error of failed request:  GLXBadFBConfig
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  34 ()
  Serial number of failed request:  66
  Current serial number in output stream:  65
```

then exits.


Without `zink` it does work in `glxgears` and in `heaven_x64` (I am using local paths to `/home/user/MangoHud`, as I didn't install it system wide).

**Comment by baryluk** [comment]
`LD_LIBRARY_PATH="/home/user/MangoHud/build/release/usr/lib/mangohud/lib/" MANGOHUD_CONFIG=time,output_folder=/tmp/mangohud-output,log_interval=0,log_duration=1000,vulkan_driver,engine_version  DEVICE_SELECT=1 VK_LAYER_PATH=/home/user/MangoHud/build/release/usr/share/vulkan/implicit_layer.d VK_INSTANCE_LAYERS=VK_LAYER_MANGOHUD_overlay vkcube`

does load, but take very long to start up. There is about 15 second delay, compared to normal startup.

`MESA_LOADER_DRIVER_OVERRIDE=zink LD_LIBRARY_PATH="/home/user/MangoHud/build/release/usr/lib/mangohud/lib/" MANGOHUD_CONFIG=time,output_folder=/tmp/mangohud-output,log_interval=0,log_duration=1000,vulkan_driver,engine_version  DEVICE_SELECT=1 VK_LAYER_PATH=/home/user/MangoHud/build/release/usr/share/vulkan/implicit_layer.d VK_INSTANCE_LAYERS=VK_LAYER_MANGOHUD_overlay glxgears`

appears to load the Vulkan layer, there is similar 16 second startup delay, and there is a `MANGOHUD: Uploading is disabled (permit_upload = 0)` message, but no HUD rendered in the rendered buffer. I would blame that on weird zink interactions with X11 and DRI layer tho. However, if I press `Shift+F2` nothing happens. No log files are produced, so there is probably more things to be figured out.

The same 15 seconds delay is observed even when doing `vulkaninfo`. In fact multiple times, as vulkaninfo opens instance, and then devices.

Observing the `strace -f`, I see a lot of threads being created. Like thousends of them.

PS. I manually modified the `/home/user/MangoHud/build/release/usr/share/vulkan/implicit_layer.d/MangoHud.json` to just use the basename of the library, not absolute path into `/usr`. (i.e. `"library_path": "libMangoHud.so",`). Putting there an absolute path to proper location doesn't change anything. The layer is loaded (it is also listed in vulkaninfo), and well, it works in vkcube (after delay), so it does work after all.
