### ISSUE TITLE
Option to start logging immiedietly at program start or with delay

### ISSUE THREAD

**Issue by baryluk** [flightlessmango/MangoHud#403]
Maybe, I am blind, but is there a way to start fps logging as soon as possible after initializing mangohud library to file without pressing the key switch?

**Comment by flightlessmango** [comment]
It does not exist yet, but it has been mentioned already #314

**Comment by flightlessmango** [comment]
https://github.com/flightlessmango/MangoHud/issues/314#issuecomment-734834910

**Comment by baryluk** [comment]
@flightlessmango Thank you!
