### ISSUE TITLE
Argument "configuration" is not of type configuration_data

### ISSUE THREAD

**Issue by JW6677** [flightlessmango/MangoHud#405]
I previously had a pre-packaged version of mango hud and today it randomly stopped working so I uninstalled it through the script and tried to build it on my machine with the error "Argument "configuration" is not of type configuration_data" when running "./build.sh build"
![Screenshot from 2020-11-27 17-25-11](https://user-images.githubusercontent.com/17951453/100473112-86a41680-30d5-11eb-83bd-4b7b05c4d581.png)
Here is the build log:
[meson-log.txt](https://github.com/flightlessmango/MangoHud/files/5609034/meson-log.txt)

**Comment by jackun** [comment]
pip install meson version>=0.52 , maybe even 0.54
