### ISSUE TITLE
Horizon Zero Dawn Not Working

### ISSUE THREAD

**Issue by JW6677** [flightlessmango/MangoHud#410]
I've tried mangohud %command%, MANGOHUD=1 %command%, MANGOHUD_DLSYM=1 mangohud %command% and nothing works. Is this just an issue of DX12 not fully supported yet? It's annoying that over half of the games I've tried don't work. Doom was one of the few I got to work.

**Comment by gort818** [comment]
mangohud with Death Stranding works fine which is also DX12.

What proton version?

**Comment by JW6677** [comment]
I found the issue. Thanks for the quick response!
