### ISSUE TITLE
0.6.0 shows as v0.5.1 in HUD

### ISSUE THREAD

**Issue by tim77** [flightlessmango/MangoHud#411]
![Снимок экрана от 2020-11-29 00-00-18](https://user-images.githubusercontent.com/5614476/100539275-1533a780-323e-11eb-92de-f9f892184c04.png)

**Comment by Faalagorn** [comment]
Same here, though I stopped using the `version` string for that reason. I believe it was an issue in the past as well

**Comment by flightlessmango** [comment]
I do not have this issue on the release or when building from master, it goes by git tag so unless you're building from the wrong tag it *should* work

**Comment by tim77** [comment]
@flightlessmango thanks for respond. Can we safely sed'ing this [here](https://github.com/flightlessmango/MangoHud/blob/master/version.h.in#L3)?

**Comment by flightlessmango** [comment]
I'm not sure what you mean

**Comment by tim77** [comment]
I mean [this](https://src.fedoraproject.org/rpms/mangohud/blob/master/f/mangohud.spec#_42). I believe nothing bad will happen there and i believe nothing bad will happen as well if i ask upstream about this. Downstream changes discouraged in Fedora.

**Comment by Faalagorn** [comment]
I think it's related to how mangohud is packaged on Arch? Not 100% sure though, I'll try to install it from a freshly cloned repo.

**Comment by tim77** [comment]
@Faalagorn can confirm, mine v0.6.1 build now shows proper version in HUD without sed'ing. Thanks for hint!

**Comment by tim77** [comment]
Just to clarify things better and why bothering upstream is still a good idea: here is an opposite [example](https://github.com/kovidgoyal/kitty/issues/2471#issuecomment-603296851) where upstream against sed'ing and not for no reason. So at least nice to have approval from upstream or even better to automate this and fix entirely since meson/cmake support this. 😋

**Comment by flightlessmango** [comment]
Isn't this automated already? I messed up in 0.6.0 by not bumping the meson build, but otherwise it already works yeah?

**Comment by tim77** [comment]
Ah, seems like yes. @flightlessmango thanks, we can close this then.
