### ISSUE TITLE
New > 0.6.0 version causing vulkandriverquery segfault on start (Steam)

### ISSUE THREAD

**Issue by tim77** [flightlessmango/MangoHud#415]
After mangohud update every time when launching Steam i've got segfault. Attached coredump [vulkandriverquery.zip](https://github.com/flathub/com.valvesoftware.Steam.Utility.MangoHud/files/5612900/vulkandriverquery.zip).

- OS: Fedora 33
- GPU: GTX 1060
- nvidia: 455.45.01
- mangohud: 0.6.1 (https://github.com/flathub/com.valvesoftware.Steam.Utility.MangoHud)

User env override for Steam app: `MANGOHUD=1` and `full` option enabled in `MangoHud.conf` config file. Previous version doesn't have this issue. But mangohud works fine, just this segfault every time.

```log
systemd-coredump[10393]: Process 10391 (vulkandriverque) of user 1000 dumped core.
                                               
Stack trace of thread 223:
#0  0x0000000000000000 n/a (n/a + 0x0)
#1  0x00000000f065ab57 n/a (/app/utils/MangoHud/lib/i386-linux-gnu/libMangoHud.so + 0x74b57)
#2  0x00000000f060f830 n/a (/app/utils/MangoHud/lib/i386-linux-gnu/libMangoHud.so + 0x29830)
#3  0x00000000f06236a1 n/a (/app/utils/MangoHud/lib/i386-linux-gnu/libMangoHud.so + 0x3d6a1)
#4  0x00000000f7a03ad7 n/a (/app/lib/i386-linux-gnu/libvulkan.so.1.2.154 + 0x29ad7)
```

Note: on the same machine and system i doesn't have https://github.com/flightlessmango/MangoHud/issues/412 in RPM build.

**Comment by tim77** [comment]
It turns out that this bug happens in non-flatpak build as well. More specifically `media_player` option cause it.

How to reproduce:
```
env MANGOHUD=1 MANGOHUD_CONFIG=media_player /path/to/steam-location/data/Steam/ubuntu12_64/vulkandriverquery
```

**Comment by jackun** [comment]
Ah, dbus should also be "blacklisted out"

**Comment by jackun** [comment]
Seems like this probably, even just a simple std::thread crashes.  https://gcc.gnu.org/bugzilla/show_bug.cgi?id=67791
