### ISSUE TITLE
[Feature Request] Being able to run MangoHud in a seperate window

### ISSUE THREAD

**Issue by SlushThorsten** [flightlessmango/MangoHud#416]
It would be cool to be able to open MangoHud in a separate window instead of displaying it in the game.
It doesn't really affect me,cause I'm a single monitor user,but it would make MangoHud better.

**Comment by Bumbadawg** [comment]
It could be extended in the UNIX φ : piped into IPC, ready to get displayed in console or GUI. Going with IPC, say in json, it could even receive commands. Which would be great to automate performance capture remotely on multiple machines.

**Comment by flightlessmango** [comment]
At the moment there are no plans for this

**Comment by isorropisths** [comment]
That would be great for a 2nd monitor, having it on top of the game obstructs the game's UI elements, while the 2nd screen just sits 'AFK'. Using other tools to monitor the hardware is not preferred.
