### ISSUE TITLE
[Feature Request] Display Current Display Resolution

### ISSUE THREAD

**Issue by Seviraf** [flightlessmango/MangoHud#417]
For example games that you don't know the resolution it is running as and plus it works with fps.
Checked MangoHud / bin / MangoHud.conf and didn't find it.

**Comment by flightlessmango** [comment]
Added here https://github.com/flightlessmango/MangoHud/commit/c8d68be4764e7b985325a05460acf79af2d66a59
only works with `legacy_layout=false`
