### ISSUE TITLE
Overlay on Minecraft: Java Edition?

### ISSUE THREAD

**Issue by stoiiciism** [flightlessmango/MangoHud#425]
Is it possible to have the MangoHud overlay appear on _Minecraft: Java Edition_?

I've tried using this command line but it doesn't work. (I even have the lib32-mangohud AUR package installed.)
`mangohud minecraft-launcher`

**OS**: Arch Linux x86_64
**DE**: GNOME 3.38.2
**CPU**: Intel i5-4570 (4) @ 3.600GHz
**GPU**: Intel HD Graphics

**Comment by flightlessmango** [comment]
`mangohud --dlsym minecraft-launcher`

**Comment by stoiiciism** [comment]
It worked! Thank you very much!
