### ISSUE TITLE
Work around to get mangoHUD working on new proton versions breaks cyberpunk

### ISSUE THREAD

**Issue by JW6677** [flightlessmango/MangoHud#426]
If you edit proton to allow cyberpunk to work on new proton versions mentioned [here](https://github.com/flightlessmango/MangoHud/issues/369) breaks cyberpunk 2077 and makes it instant fail.
When you click play it will show the stop button then it crashes and goes back to the play button. No error message nothing...
I think I've seen prople with it working but I can't get it work.

**Comment by Leopard1907** [comment]
No , issue comes from something else. Use `MANGOHUD=1 %command%` with game when runtime is disabled , `mangohud %command%` hangs the game at CDPR logo.

I play this game with runtime disabled and Mangohud on with `MANGOHUD=1`

**Comment by JW6677** [comment]
Sorry, Forgot to close. Thanks for the help on discord!

**Comment by aqxa1** [comment]
This affects Arkham Knight as well, for the record (with the same workaround). It looks to be a regression, since the issue is not evident with mangohud-0.5.1. I'll continue doing a bisect if the issue is not already known.
