### ISSUE TITLE
Framerate issues in Satisfactory

### ISSUE THREAD

**Issue by TheHooly** [flightlessmango/MangoHud#427]
OS:
Arch Linux (regular update channels)

MangoHUD v0.6.1 from the chaotic-aur, also tested with the git-version.

Satisfactory recently added an option to apply an FPS limit. Since then, using MangoHUD in Satisfactory leads to unplayable framerates (10-20FPS).

I've tried multiple combinations of settings: Unlimiting it ingame and limiting it via MangoHUD, vice versa, and un/limiting it with both settings.

The only way to get to a playable state again was deactivating MangoHUD completely.

**Comment by flightlessmango** [comment]
Can you add some more information like hardware, proton version, dxvk or wined3d

**Comment by TheHooly** [comment]
Curious, I just tried it again with both 5.0-10 and 5.9-GE-8-ST and now the issue no longer persists in 5.9. I can remember that yesterday the issue occurred in both Proton versions. The game received an update in the meantime, maybe that solved it?

CPU: Ryzen 7 3800X
GPU: RX 5700XT
Kernel: linux-tkg-pds-zen2-5.9.13-98 from the chaotic-aur
Proton 5.0-10: issue present, 5.9-GE-8-ST: issue no longer present,
Proton 5.13-4 and 5.21-GE-1: the game does not start at all

Launch options: "gamemoderun mangohud %command%"
