### ISSUE TITLE
[Feature request] Show if Feral Gamemode is active or not

### ISSUE THREAD

**Issue by VortexAcherontic** [flightlessmango/MangoHud#436]
Hey there you beautiful people!

Just thought about that it would be nice to be able to display if Feral Gamemode is running in the HUD.
I know there is the command line way to do so by using:

````
gamemoded -s
````
Which respond like:
````
gamemode is active
gamemode is inactive
````

Would it be possible to display it in the HUD or is there even already an option for the config to turn this information on/off I am just not aware of?

Thank you in advance,
Votex

**Comment by flightlessmango** [comment]
I feel like the interesting part isn't if gamemode is running or not, but rather if gamemoderun has attached the library to the game?

**Comment by flightlessmango** [comment]
Added params for gamemode and vkbasalt 05cf9fc5d6ed52630e5969a9e259758eade0a595

**Comment by VortexAcherontic** [comment]
Awesome, thank you :)
