### ISSUE TITLE
steam中MANGOHUD_CONFIG怎么设置？

### ISSUE THREAD

**Issue by sjkhsl** [flightlessmango/MangoHud#437]
steam中MANGOHUD_CONFIG怎么设置？需要CPU,显卡温度等！

**Comment by gort818** [comment]
For Steam games, you can add this as a launch option:

mangohud %command%

**Comment by gort818** [comment]
Create a config file here `$HOME/.config/MangoHud/MangoHud.conf`

and look at all the options available here https://github.com/flightlessmango/MangoHud#mangohud_config-and-mangohud_configfile-environment-variables

**Comment by PiecePaperCode** [comment]
`mangohud %command%`
linux machine ubuntu 20.10
adding this to proton run games wont work. native steam games work on linux

**Comment by flightlessmango** [comment]
@PiecePaperCode is it an AMD gpu? try setting `NODEVICE_SELECT=1 mangohud %command%`

**Comment by sjkhsl** [comment]
> 在此处创建配置文件 `$HOME/.config/MangoHud/MangoHud.conf`
> 
> 并查看此处提供的所有选项https://github.com/flightlessmango/MangoHud#mangohud_config-and-mangohud_configfile-environment-variables


创建文件添加内容没有反应，和之前一样！

**Comment by gort818** [comment]
@sjkhsl so what exactly is the issue? MangoHud is not showing? are you using it with native linux games or proton? What does your config file look like?

**Comment by sjkhsl** [comment]
> @sjkhsl那么究竟是什么问题？MangoHud没有显示？您是否将其与本地linux游戏或质子一起使用？您的配置文件是什么样的？

通过GOverlay设置成功了，lutris可以使用mangohud吗？怎么使用？

**Comment by gort818** [comment]
For Lutris games, go to the System options in Lutris (make sure that advanced options are enabled) and add this to the Command prefix setting: `mangohud`

**Comment by PiecePaperCode** [comment]
> `mangohud %command%`
> linux machine ubuntu 20.10
> adding this to proton run games wont work. native steam games work on linux

I am Using Intel with Geforce
https://github.com/flightlessmango/MangoHud/issues/369#issuecomment-709902078
This resolved my issue. The Readme should be updatet to point out that Proton Games would have this issue of not displaying the HUD. This is the **workaround** that worked for me now.
