### ISSUE TITLE
Disabling SMT crashes mangohud and game

### ISSUE THREAD

**Issue by bezirg** [flightlessmango/MangoHud#438]
Specs:
CPU: amd 4800u 8cores/ 16threads SMT
Steam Beta running games as `mangohud %command%`
Games tested:  Mad Max, Dirt 4

First of all, Mangohud and the game run fine when SMT is on (the default):

```
$ cat /sys/devices/system/cpu/smt/active
1
```

If I switch the SMT off at runtime with:

```
$ echo off > /sys/devices/system/cpu/smt/control
$ cat /sys/devices/system/cpu/smt/active
0
```

then , the `mangohud %command%` on the aforementioned games crash immediately upon launch with a steam log output error:

```
CPU id '10' is out of bounds
```

Note that these games work fine when launched plain without mangohud, regardless of SMT on/off

**Comment by jackun** [comment]
Ick, off-by-one. Should be fixed in ae410f01e73cc9ca11022ef23ab3914bba8b1144. Made it reinit if core count changes too.

**Comment by bezirg** [comment]
Seems that the crash is fixed. The only downside, however, is that when SMT is off the CPU usage is not shown in the HUD. I don't know if this is intentional or not, and certainly it does not bother me; I thought to let you know.

**Comment by jackun** [comment]
:thinking: Works for me on intel and ryzen 3600.
