### ISSUE TITLE
Media player info not showing

### ISSUE THREAD

**Issue by MichaelLawton** [flightlessmango/MangoHud#439]
MangoHud v0.6.1

I get the standard MANGOHUD: info messages in the terminal but no warnings or errors. I can confirm that the org.mpris.MediaPlayer2 objects exist for the media players I've tried.

Is there a way to enable debug output?

**Comment by gort818** [comment]
What media player related options do you have in your config file?

**Comment by MichaelLawton** [comment]
I have the following:
```yml
media_player
media_player_color=ffffff
media_player_name="" #(also tried ="vlc" or commenting out the line)
```

I have also tried `MANGOHUD_CONFIG=full`

**Comment by jackun** [comment]
Is the game 32bit and do you have 32bit dbus libs installed?

**Comment by MichaelLawton** [comment]
It's the same with any 32 or 64 bit app and I do have 32bit dbus libs.

**Comment by jackun** [comment]
> Is there a way to enable debug output?

Weird. Run from command line with vkcube/glxgears etc. Hopefully spits out something about dbus.

**Comment by MichaelLawton** [comment]
Turns out that all the files I was testing with had no track name/artist info.  They were showing up on my desktop's dbus driven media info but tile and artist were "unknown".

**Comment by jackun** [comment]
Should probably add support for showing base file name for these then, maybe.
