### ISSUE TITLE
Getting NVIDIA Xid error on Skyrim Special Edition when 'gpu_timing' is enabled

### ISSUE THREAD

**Issue by guihkx** [flightlessmango/MangoHud#44]
My info:

**CPU**: Intel i5 3570k
**GPU**: NVIDIA GTX 660
**RAM**: 8 GB

Software: 

**NVIDIA Driver**: 440.59
**MangoHud**: v0.2.0
**Runtime**: Flatpak
**Steam**: Beta Update (Feb 18, 2020)
**Proton**: 5.0-2

Launch options for Skyrim Special Edition:

```
PROTON_LOG=1 MANGOHUD=1 MANGOHUD_CONFIG=gpu_timing WINEDLLOVERRIDES="xaudio2_7=n,b" %command%
```

This is the [Xid message](https://docs.nvidia.com/deploy/xid-errors/index.html#topic_5_3) that pops up in `dmesg` after you click the **PLAY** button in the game's launcher:

```
[ 3252.896909] NVRM: Xid (PCI:0000:01:00): 32, pid=16176, Channel ID 00000055 intr1 00000008 HCE_DBG0 00000110 HCE_DBG1 00000000
```

This crash also occurs if I set `MANGOHUD_CONFIG=full` instead, but after narrowing them down, I found out that the option crashing the game is `gpu_timing`. 

The proton log file shows the following message too, which is probably the root cause:

```
[...]
Command buffer submitted multiple times before present.
This could lead to invalid data.
[...]
```

Full log file: [steam-489830.log](https://gist.github.com/guihkx/2d76d3724612257b782464de8978a38b/raw/85144c487a345afe96a760fb73cd344a021f4d0b/steam-489830.log)

**Comment by gasinvein** [comment]
I guess this might be not specific to Skyrim SE but to DXVK in general.

**Comment by guihkx** [comment]
FWIW, I've tried reproducing this on Terraria, GTA:SA and Volcanoids (native Vulkan), but this crash only occurred on Skyrim SE.

**Comment by gasinvein** [comment]
I was able to reproduce it at least with Unigine Superposition benchmark.

**Comment by guihkx** [comment]
Yeah, actually, I take that back.

I don't know why it was working before, but I just tested with GTA:SA and Terraria and I get the same  Xid error.

Oddly enough, Terraria still launches and works, though.

**Comment by gasinvein** [comment]
Yes, both native Vulkan and DX12 via libvkd3d work fine for me, but DX9-11 via DXVK has the issue.

**Comment by gasinvein** [comment]
Something very strange going on here. If I enable all the options listed in the readme, namely `cpu_temp`, `gpu_temp`, `core_load`, `ram` and `vram`, everything works fine. But if I enable `full` HUD (it should do the same, right?) - the app hangs and this `NVRM: Xid ...` error appears.

**Comment by guihkx** [comment]
I thought of that too. But when you use `MANGOHUD_CONFIG=full`, it also enables [some other options](https://github.com/flightlessmango/MangoHud/blob/v0.2.0/src/overlay_params.h#L37-L50) other than `cpu_temp,gpu_temp,core_load,ram,vram`. They just happen to be undocumented as of now. That's how I discovered `gpu_timing`.

**Comment by todoexelent** [comment]
AMDGPU HD7000 series - Mesa Drive 20.1
is not showing GPU usage, keeping like 0%.

**Comment by guihkx** [comment]
@todoexelent I believe your issue is not related to this one. Perhaps related to #7.

**Comment by gasinvein** [comment]
@guihkx What `gpu_timing` should do? AFAICT, the HUD looks exactly the same with either all listed above options set manually, or with `full` option (where it works).

**Comment by guihkx** [comment]
I have no idea since I don't know anything about this graphics stuff...

You could guess by searching for references of that option, though:

https://github.com/flightlessmango/MangoHud/blob/v0.2.0/src/overlay.cpp#L1250-L1251

https://github.com/flightlessmango/MangoHud/blob/v0.2.0/src/overlay.cpp#L2208-L2210

https://github.com/flightlessmango/MangoHud/blob/v0.2.0/src/overlay.cpp#L2394-L2405

Maybe a dev can answer that.

**Comment by jackun** [comment]
Did you build from master on still on 0.2.0?

**Comment by gasinvein** [comment]
@jackun Just tried build from master - the issue is still present.

**Comment by jackun** [comment]
Strange. I would think it would crash even without `gpu_timing` becuase the only think it does is write timestamps to command buffer :thinking:

**Comment by gasinvein** [comment]
At least for me it doesn't crash, it hangs, so I have to kill the wine processes. 
Tried all options listed in the readme - seems like only either `gpu_timing` or `full` causes this.

**Comment by guihkx** [comment]
Yes, the process hangs for me too. I have to alt+tab and `SIGKILL` the `.exe` process of the game.
