### ISSUE TITLE
MPRIS media details never updates

### ISSUE THREAD

**Issue by JustAnotherStrange** [flightlessmango/MangoHud#441]
Intel i5-10400f, kernel 5.9.14 on endeavouros (arch based), amd rx5600 on open source drivers (probably doesn't matter but whatever). Installed through AUR package "mangohud"
If no song is playing when I boot mangohud, then it never shows any details, and if a song is playing while I boot mangohud, it stays infinitely on showing that song's info even if the song changes. Seems as if it doesn't check periodically to see if the song data updated. 
Every other part of mangohud works fine.

**Comment by JustAnotherStrange** [comment]
This seems to be related to #439, but they didn't notice that if you have the song playing while you open mangohud it does show the info.

**Comment by jackun** [comment]
Can't repro, what player?

**Comment by JustAnotherStrange** [comment]
Alright, my fault for not mentioning: I am using spotifyd https://github.com/Spotifyd/spotifyd. When I use the standard spotify client, it works great -- seems to be an issue with spotifyd. I think I can close this now and send an issue to spotifyd because it seems to be its fault.

**Comment by jackun** [comment]
Ok. But one issue seems to be still if you force it to listen to just spotify but then unset `media_player_name` it still ignores other players :(
