### ISSUE TITLE
No Man's Sky crashes with mangohud

### ISSUE THREAD

**Issue by lavadrop** [flightlessmango/MangoHud#442]
I can't even get Steam to write a log.
This is all I have from terminal.

[error NMS.txt](https://github.com/flightlessmango/MangoHud/files/5720645/error.NMS.txt)

**Comment by lavadrop** [comment]
I found the log.
[steam-275850.log](https://github.com/flightlessmango/MangoHud/files/5721247/steam-275850.log)

**Comment by EduFrazao** [comment]
I'm running just fine here. Can you try using this env var?

NODEVICE_SELECT=1

**Comment by lavadrop** [comment]
Thanks. Didn't work. Crashed again.

**Comment by biggles5107** [comment]
I've found that I need to use Proton 5.0 with No Man's Sky. I haven't had outright crashing but I've had other strange issues.

**Comment by flightlessmango** [comment]
Reopen if still an issue
