### ISSUE TITLE
CPU temp displays 0

### ISSUE THREAD

**Issue by shag00** [flightlessmango/MangoHud#447]
I have taken the example conf file and saved it in ~/.config/mangohud.conf, changed display location to top-centre and removed the # at the beginning of CPU & GPU temps. Of the 3 changes only CPU temp is not working. 

Following is my output (extract) of sensors:
SYSTIN:        +39.0°C  (high = +80.0°C, hyst = +75.0°C)  sensor = CPU diode
CPUTIN:        +33.0°C  (high = +108.0°C, hyst = +90.0°C)  sensor = thermistor
AUXTIN0:       +38.5°C  (high = +108.0°C, hyst = +90.0°C)  sensor = thermistor
AUXTIN1:      -128.0°C    sensor = thermistor
AUXTIN2:       +59.0°C    sensor = thermistor
AUXTIN3:        -1.0°C    sensor = thermistor
Virtual_TEMP:  +38.0°C  
Virtual_TEMP:  +38.0°C  
Virtual_TEMP:  +38.0°C  
Virtual_TEMP:  +38.0°C

k10temp-pci-00c3
Adapter: PCI adapter
temp1:         +0.0°C  (high = +70.0°C)

Am I correct in assuming mango takes it's temp from k10temp-pci-00c3? 

I have a AMD Ryzon 5700X on a MSI X570 mother board.

Can mango use another sensor until the new kernel, which I understand fixes this issue, is available?

**Comment by flightlessmango** [comment]
That config location and naming is not correct, it needs to be camelcase and in a `MangoHud` folder inside `~/.config`.
We don't have an option to manually set sensors at the moment. What is the background to this issue exactly? I would like to evaluate the actual situation before I implement a temporary fix

**Comment by shag00** [comment]
Oops, and right you are, it really is ~/.config/MangoHud/MangoHud.conf  I also mis-stated the CPU, it is a 5800X.

I upgraded my CPU (only released last month) in the last week and installed mango and CPU temp is 0. The 3000 series AMD processors only had k10 temps included in the kernel from (I think) ver 5.6 and as it appears to be an active issue I expect the kernel will support 5000 series processors quickly. I trust this is the background you were after.

There is always the possibility that I have done something incorrectly that for some reason masks the k10 temp.

**Comment by flightlessmango** [comment]
I think this might have been fixed in develop branch, can you check?

**Comment by SimoFiuz** [comment]
On a x570 motherboard with a 3600X CPU I too am unable to see CPU temps. Only the GPU works.
_sensors_ works and any other application reading CPU temps too.
Motherboard is an Asrock X570M Pro4.

`$ inxi -Fza --no-host

System:    Kernel: 5.10.15-1-MANJARO x86_64 bits: 64 compiler: gcc v: 10.2.1 
           parameters: BOOT_IMAGE=/boot/vmlinuz-5.10-x86_64 root=UUID=a44a98fb-e14a-4b83-aecf-3e2404122429 rw quiet apparmor=1 
           security=apparmor resume=UUID=4cca951a-83f0-41a8-8c12-c312236dd54a udev.log_priority=3 
           Desktop: Xfce 4.16.0 tk: Gtk 3.24.24 info: xfce4-panel wm: xfwm4 dm: LightDM 1.30.0 Distro: Manjaro Linux 
Machine:   Type: Desktop Mobo: ASRock model: X570M Pro4 serial: <filter> UEFI: American Megatrends v: P3.30 date: 12/01/2020 
CPU:       Info: 6-Core model: AMD Ryzen 5 3600X bits: 64 type: MT MCP arch: Zen 2 family: 17 (23) model-id: 71 (113) 
           stepping: N/A microcode: 8701021 L2 cache: 3 MiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm bogomips: 91067 
           Speed: 2196 MHz min/max: 2200/3800 MHz boost: enabled Core speeds (MHz): 1: 2196 2: 2196 3: 2196 4: 2196 5: 2196 
           6: 2196 7: 2196 8: 2196 9: 2196 10: 2196 11: 2196 12: 2196 
           Vulnerabilities: Type: itlb_multihit status: Not affected 
           Type: l1tf status: Not affected 
           Type: mds status: Not affected 
           Type: meltdown status: Not affected 
           Type: spec_store_bypass mitigation: Speculative Store Bypass disabled via prctl and seccomp 
           Type: spectre_v1 mitigation: usercopy/swapgs barriers and __user pointer sanitization 
           Type: spectre_v2 mitigation: Full AMD retpoline, IBPB: conditional, STIBP: conditional, RSB filling 
           Type: srbds status: Not affected 
           Type: tsx_async_abort status: Not affected 
Graphics:  Device-1: NVIDIA TU106 [GeForce RTX 2060 Rev. A] vendor: Gigabyte driver: nvidia v: 460.39 
           alternate: nouveau,nvidia_drm bus ID: 09:00.0 chip ID: 10de:1f08 class ID: 0300 
           Display: x11 server: X.Org 1.20.10 driver: loaded: nvidia display ID: :0.0 screens: 1 
           Screen-1: 0 s-res: 2560x1440 s-dpi: 96 s-size: 677x381mm (26.7x15.0") s-diag: 777mm (30.6") 
           Monitor-1: DP-4 res: 2560x1440 dpi: 109 size: 598x336mm (23.5x13.2") diag: 686mm (27") 
           OpenGL: renderer: GeForce RTX 2060/PCIe/SSE2 v: 4.6.0 NVIDIA 460.39 direct render: Yes 
Audio:     Device-1: NVIDIA TU106 High Definition Audio vendor: Gigabyte driver: snd_hda_intel v: kernel bus ID: 09:00.1 
           chip ID: 10de:10f9 class ID: 0403 
           Device-2: Advanced Micro Devices [AMD] Starship/Matisse HD Audio vendor: ASRock driver: snd_hda_intel v: kernel 
           bus ID: 0b:00.4 chip ID: 1022:1487 class ID: 0403 
           Device-3: Texas Instruments PCM2902 Audio Codec type: USB driver: hid-generic,snd-usb-audio,usbhid bus ID: 7-3.4:5 
           chip ID: 08bb:2902 class ID: 0300 
           Sound Server: ALSA v: k5.10.15-1-MANJARO 
Network:   Device-1: Intel 82574L Gigabit Network driver: e1000e v: kernel port: d000 bus ID: 04:00.0 chip ID: 8086:10d3 
           class ID: 0200 
           IF: enp4s0 state: up speed: 1000 Mbps duplex: full mac: <filter> 
           Device-2: Intel I211 Gigabit Network vendor: ASRock driver: igb v: kernel port: c000 bus ID: 05:00.0 
           chip ID: 8086:1539 class ID: 0200 
           IF: enp5s0 state: down mac: <filter> 
Bluetooth: Device-1: Broadcom BCM20702A0 Bluetooth 4.0 type: USB driver: btusb v: 0.8 bus ID: 7-3.3.4:10 chip ID: 0a5c:21e8 
           class ID: fe01 serial: <filter> 
           Message: Required tool hciconfig not installed. Check --recommends 
Drives:    Local Storage: total: 1.7 TiB used: 297.44 GiB (17.1%) 
           SMART Message: Unable to run smartctl. Root privileges required. 
           ID-1: /dev/nvme0n1 maj-min: 259:0 vendor: Samsung model: MZVPV128HDGM-00000 size: 119.24 GiB block size: 
           physical: 512 B logical: 512 B speed: 31.6 Gb/s lanes: 4 rotation: SSD serial: <filter> rev: BXW7300Q temp: 44.9 C 
           scheme: GPT 
           ID-2: /dev/sda maj-min: 8:0 vendor: SanDisk model: SDSSDA240G size: 223.57 GiB block size: physical: 512 B 
           logical: 512 B speed: 6.0 Gb/s rotation: SSD serial: <filter> rev: 00RL scheme: GPT 
           ID-3: /dev/sdb maj-min: 8:16 vendor: Crucial model: CT1000BX500SSD1 size: 931.51 GiB block size: physical: 512 B 
           logical: 512 B speed: 6.0 Gb/s rotation: SSD serial: <filter> rev: 030 scheme: GPT 
           ID-4: /dev/sdc maj-min: 8:32 vendor: Samsung model: SSD 860 EVO 500GB size: 465.76 GiB block size: physical: 512 B 
           logical: 512 B speed: 6.0 Gb/s rotation: SSD serial: <filter> rev: 1B6Q scheme: GPT 
Partition: ID-1: / raw size: 206.12 GiB size: 201.89 GiB (97.95%) used: 45.71 GiB (22.6%) fs: ext4 dev: /dev/sda2 maj-min: 8:2 
           ID-2: /boot/efi raw size: 300 MiB size: 299.4 MiB (99.80%) used: 280 KiB (0.1%) fs: vfat dev: /dev/sda1 
           maj-min: 8:1 
           ID-3: /home raw size: 931.51 GiB size: 915.89 GiB (98.32%) used: 48.6 GiB (5.3%) fs: ext4 dev: /dev/sdb1 
           maj-min: 8:17 
Swap:      Kernel: swappiness: 10 (default 60) cache pressure: 100 (default) 
           ID-1: swap-1 type: partition size: 17.15 GiB used: 0 KiB (0.0%) priority: -2 dev: /dev/sda3 maj-min: 8:3 
Sensors:   System Temperatures: cpu: 36.0 C mobo: 41.0 C gpu: nvidia temp: 47 C 
           Fan Speeds (RPM): fan-1: 530 fan-2: 910 fan-3: 0 fan-4: 0 fan-5: 302 fan-6: 3846 fan-7: 0 gpu: nvidia fan: 0% 
Info:      Processes: 405 Uptime: 2h 54m wakeups: 0 Memory: 31.28 GiB used: 5.69 GiB (18.2%) Init: systemd v: 247 Compilers: 
           gcc: 10.2.0 clang: 11.0.1 Packages: pacman: 1859 lib: 449 flatpak: 0 Shell: Bash v: 5.1.0 running in: server 
           inxi: 3.3.01 
`

**Comment by flightlessmango** [comment]
@SimoFiuz Did you try develop branch?

**Comment by SimoFiuz** [comment]
I will and report here!

**Comment by SimoFiuz** [comment]
Hello @flightlessmango 
switched to the develop branch, cloned in local, ran ./build.sh build and then ./build.sh install.
I still can't see the CPU temps. The rest works fine!
Just tell me if you need anything else such as logs or whatever!

**Comment by jackun** [comment]
@SimoFiuz can you paste `sensors` output? And if you manage to build MangoHud as debug build (`./build.sh build --buildtype=debug install` ) then run something simple from terminal and paste that output too.

**Comment by SimoFiuz** [comment]
IIRC I don't have the k10temp kernel module installed. I'll try with zenpower as you suggest.

sensors:

```
nvme-pci-0300
Adapter: PCI adapter
Composite:    +44.9°C  

nct6798-isa-0290
Adapter: ISA adapter
in0:                   600.00 mV (min =  +0.00 V, max =  +1.74 V)
in1:                     1.66 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in2:                     3.44 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in3:                     3.36 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in4:                     1.81 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in5:                     1.09 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in6:                     1.34 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in7:                     3.44 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in8:                     3.30 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in9:                     1.69 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in10:                    1.02 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in11:                  624.00 mV (min =  +0.00 V, max =  +0.00 V)  ALARM
in12:                    1.03 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in13:                  920.00 mV (min =  +0.00 V, max =  +0.00 V)  ALARM
in14:                  904.00 mV (min =  +0.00 V, max =  +0.00 V)  ALARM
fan1:                   569 RPM  (min =    0 RPM)
fan2:                   920 RPM  (min =    0 RPM)
fan3:                     0 RPM  (min =    0 RPM)
fan4:                     0 RPM  (min =    0 RPM)
fan5:                     0 RPM  (min =    0 RPM)
fan6:                  3534 RPM  (min =    0 RPM)
fan7:                     0 RPM  (min =    0 RPM)
SYSTIN:                 +43.0°C    sensor = thermistor
CPUTIN:                 +38.0°C  (high = +80.0°C, hyst = +75.0°C)  sensor = thermistor
AUXTIN0:                 +8.0°C    sensor = thermistor
AUXTIN1:                -62.0°C    sensor = thermistor
AUXTIN2:                +13.0°C    sensor = thermistor
AUXTIN3:                +31.0°C    sensor = thermistor
SMBUSMASTER 1:          +62.0°C  (high = +105.0°C, hyst = +95.0°C)
SMBUSMASTER 0:          +46.5°C  
PCH_CHIP_CPU_MAX_TEMP:   +0.0°C  
PCH_CHIP_TEMP:           +0.0°C  
intrusion0:            ALARM
intrusion1:            ALARM
beep_enable:           disabled

```

**Comment by jackun** [comment]
Probably should add `CPUTIN` as a fallback sensors as well.
