### ISSUE TITLE
[Feature request] Showing OBS recording activity

### ISSUE THREAD

**Issue by headlesscyborg** [flightlessmango/MangoHud#448]
Hi, I want to ask if it would be possible to implement some way of detection of OBS recording? I often do some recording and having the option to see when I'm recording and when I'm not would be awesome. It already can show Spotify, VLC etc. so I thought this could be a nice addition.

**Comment by flightlessmango** [comment]
I don't know of anyway to query obs for recording status, or anything for that matter

**Comment by baryluk** [comment]
I see. That is an interesting idea.

In fact, I myself had this issue in the past. Where I would be recording in OBS, but needing to switch between the game and OBS periodically, to make sure everything is ok, disk space is fine, etc. Displaying some OBS info (Streaming ON/OFF, Recording ON/OFF and time they were on, OBS CPU usage, latency, remaining disk space), would be interesting.

OBS do have a well documented remote API, with network access to OBS I believe. It is based on JSON, and it can be used for both querying many things in OBS, as well changing things (i.e. changing volumes, audio, video settings, changing scenes, etc, etc).

With, work on a MangoHud rpc and server, it shouldn't be hard to make it a plugin, that lives in the GUI or server, instead in overlay. My prototype already supports sending arbitrary custom strings to overlay in agnostic way.

**Comment by 8836290** [comment]
How about assign a visual indicator for when a shortcut key is pressed? Then assign the same key that starts OBS recording as a shortcut key for displaying that is pressed on MangoHud. So pressing the key for both applicaitons on one it starts recording and on the second provides visual indicator. What I have done already is assign i.e. F9 to show/hide MangoHud and startstop OBS recording, so when i press F9 and see MangoHud I know recording has started if in the background OBS is active.

**Comment by azadad96** [comment]
It is possible to query OBS for recording status, however, you would need to use a plugin. Which may require some more setup.
This one claims to only work on Windows, but I'm certain there are alternatives: [jfoster/obs-rtss](https://github.com/jfoster/obs-rtss)

Another option would be to do it like Discord: Just detect if OBS is running, and if it is, start a "streamer mode".
I could create a function to detect if OBS is running, but I'd need someone else to actually show an indicator in the HUD.

**Comment by azadad96** [comment]
Implemented methods to check if a process is running in pull request #724.
`process_running("obs")` will return `true`, if a running process' command contains the string `"obs"` (case-insensitive), which can be used to detect if OBS is running.
Now someone just needs to implement a visual cue for the user to actually see it.

**Comment by flightlessmango** [comment]
I don't think this is reasonable for mangohud
