### ISSUE TITLE
hud not resizing correctly in borderless windows games

### ISSUE THREAD

**Issue by zany130** [flightlessmango/MangoHud#45]
the hud does not size correctly when running games in borderless window switching to fullscreen then back to borderless fixes it also starting the game in fullscreen works as well. I'm using a font size of 48
![Screenshot_20200220_200553](https://user-images.githubusercontent.com/25832539/74994680-b6264400-541c-11ea-805f-fcf986159d6a.png)

**Comment by flightlessmango** [comment]
Are you using master or the latest release?

**Comment by zany130** [comment]
master i belive im installing from the aur which i think gets  the master

**Comment by flightlessmango** [comment]
there are two packages in aur, the `mangohud-git` one gets master and the other one gets latest release
also some steps to reproduce would be good

**Comment by zany130** [comment]
this was on the latest git after starting trails in the sky second chapter in borderless window with mangohud. pressing alt-enter to switch to full screen fixed it and i could even switch back again with alt-enter to borderless and it would be sized correctly

**Comment by zany130** [comment]
i can no longer reporduce this issue which is werid so i guees ill close it
