### ISSUE TITLE
It doesn't work if I use it with Gamescope

### ISSUE THREAD

**Issue by Toadfield** [flightlessmango/MangoHud#450]
If I only use Mangohud,with "MANGOHUD=1" or "gamescope -w 3840 -h 2160 -- " by itself it works,but combined,so it is "MANGOHUD=1 gamescope -w 3840 -h 2160 -- " it doesn't launch the game.
I use Manjaro Kde.
I already reportet it on the Gamescope Github site ([here](https://github.com/Plagman/gamescope/issues/137)).

**Comment by jackun** [comment]
Try adding `ENABLE_VKBASALT=1` even if you don't use vkBasalt. Gamescope tries to use compute queues only and has a workaround if vkBasalt is "enabled".

**Comment by flightlessmango** [comment]
correct usage in steam should look something like `gamescope -w 3840 -h 2160 --  mangohud %command%`
