### ISSUE TITLE
No errors or anything when the output log dir doesn't exist. And the recording gets lost

### ISSUE THREAD

**Issue by legendofmiracles** [flightlessmango/MangoHud#451]
Likely a issue with the code, and it not handling such situations.
An error or automatically creating the directory would be nice...
Especially frustrating because the default configuration has it's output dir in ~/mangologs, which on 99% of the systems doesn't exist *yet*.

**Comment by flightlessmango** [comment]
Added a check before writing config (in develop) abe45c74856edfc48459c1bdfd5ffc5d7e5a8d8f
