### ISSUE TITLE
fps_limit doesn't work

### ISSUE THREAD

**Issue by RenanRischiotto** [flightlessmango/MangoHud#452]
Hi, I'm trying to limit the fps for Batman Arkham Origins. The option in the file to limit the fps doesn't do anything.

![Screenshot from 2020-12-31 19-30-41](https://user-images.githubusercontent.com/6877322/103427282-b6e04880-4b9e-11eb-91b0-f61f9b973bbb.png)

Linux Mint 20 Cinnamon
GTX 970
Proton 5.13-4

**Comment by jackun** [comment]
> ~/MangoHud/bin/

Copy it `~/.config/MangoHud/MangoHud.conf`

**Comment by RenanRischiotto** [comment]
Thanks, it worked.

Dang, the Linux performance on this game is so bad, the game oscilates a lot even locking the fps to 32. When opening doors, pretty much kills the fps.
