### ISSUE TITLE
GPU info doesn't show up on No Man's Sky

### ISSUE THREAD

**Issue by biggles5107** [flightlessmango/MangoHud#453]
![Screenshot_20201231_183239](https://user-images.githubusercontent.com/7585954/103431545-32d69280-4b97-11eb-942a-6e26f4bca638.png)

Nvidia driver and Proton versions are shown in the screenshot. (No, I'm not using the latest Proton 5.13 because most textures don't fully load in, but 5.0 has worked well for me. Custom versions of Proton have caused the game to crash.)

GPU info seems to have been broken since the No Man's Sky Origins update. It did work before that (GPU usage etc. showed up and VRAM usage reported correctly).

My MangoHud.conf: [Pastebin](https://pastebin.com/axi3mtDb)

Running on an up-to-date Ubuntu 20.04 installation with KDE (though it doesn't work on my Xubuntu 20.10 machine either).

I can try to get console output if that's helpful but I haven't had good luck seeing as it's a Proton game. If anyone has suggestions on that front, it would be appreciated.

EDIT: tried both with master and with 0.6.1 release binary, same result.

**Comment by jackun** [comment]
Run with `PROTON_LOG=1 LD_DEBUG=libs`, maybe for some reason it fails to load `libnvidia-ml.so.1` or `libXNVCtrl.so.0`

**Comment by biggles5107** [comment]
[steam-275850.log](https://github.com/flightlessmango/MangoHud/files/5863667/steam-275850.log)

Here you be.

**Comment by jackun** [comment]
It also spams amdgpu, do you have a secondary card or a Vega APU? Seems it launches on AMD first but then it should at least show amdgpu stats. Does `amdgpu` expose `gpu_busy_percentage`? Check `cat /sys/class/drm/card*/device/gpu_busy_percent`

**Comment by biggles5107** [comment]
Will try that. My GPU is a GTX 1660 Super, and my CPU is an Intel, so I'm not sure why it would be trying to load amdgpu. I can try that when I get the chance.

**Comment by biggles5107** [comment]
```
$ cat /sys/class/drm/card*/device/gpu_busy_percent
zsh: no matches found: /sys/class/drm/card*/device/gpu_busy_percent
```

> Could try with `VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json mangohud %command%` (or wherever that json lives) to force it only detect nvidia card.

No dice. The path is correct, but the result is the same.

**Comment by IroAlexis** [comment]
You use the GOG version with Proton is it ? On my side, it is my problem on the GOG version (and with Wine TkG). While the steam game version with Proton gives me the GPU info

**Comment by biggles5107** [comment]
Nope this is on Steam
