### ISSUE TITLE
All games fail to start when I use Mango Hud.

### ISSUE THREAD

**Issue by PythonCow** [flightlessmango/MangoHud#454]
I am using Arch Linux. At first I was using the mangohud package from the AUR, but this also happened when I cloned the repository and built and installed MangoHud myself. The problem seemed to start when I started using the experimental mesa drivers (version on my computer is 21.0.0_devel.132788.9f213238b87-1) instead of the stable ones. 

Log from trying to start DOOM Eternal (launch options are "mangohud PROTON_LOG=1 %command%"):
[steam-782330.log](https://github.com/flightlessmango/MangoHud/files/5759834/steam-782330.log)

Log from trying to start Horizon Zero Dawn (same launch options):
[steam-1151640.log](https://github.com/flightlessmango/MangoHud/files/5759840/steam-1151640.log)

**Comment by flightlessmango** [comment]
try `NODEVICE_SELECT=1 mangohud %command%`

**Comment by PythonCow** [comment]
Thank you that worked :)
