### ISSUE TITLE
Not working on Ubuntu 20.04

### ISSUE THREAD

**Issue by RenanRischiotto** [flightlessmango/MangoHud#455]
So I decided to install Ubuntu because Linux Mint is bugged. The hud is not working on any game. I installed correctly.

https://pastebin.pl/view/89252320

**Comment by flgx16** [comment]
What games are you testing it on? On Steam? If so, does MangoHud work on non-steam programs/games?

**Comment by RenanRischiotto** [comment]
> What games are you trying to use it on? Steam games? If so, does MangoHud work on non-steam programs/games?

Yeah Steam games. I don't have non-steam games to test.

**Comment by flgx16** [comment]
If you have an AMD GPU or an Intel GPU in your system try setting launch options to `NODEVICE_SELECT=1 mangohud %command%` instead of `mangohud %command%`.

If you are running the game through steam proton it may be a problem (#369), which you can workaround with: https://github.com/flightlessmango/MangoHud/issues/369#issuecomment-709902078

**Comment by flightlessmango** [comment]
It helps to problem solve if you give more details like, what method did you use to install mangohud? do you have nvidia or amd gpu? which exact game are you testing with?

**Comment by RenanRischiotto** [comment]
> It helps to problem solve if you give more details like, what method did you use to install mangohud? do you have nvidia or amd gpu? which exact game are you testing with?

The method is in the link I posted. I have NVIDIA GTX 970. Batman Arkham Origins and Among Us.

**Comment by RenanRischiotto** [comment]
> Try setting launch options to `NODEVICE_SELECT=1 mangohud %command%` instead of `mangohud %command%`.
> 
> If you are running the game through Steam's Proton it may be a problem (#369), which you can workaround with: [#369 (comment)](https://github.com/flightlessmango/MangoHud/issues/369#issuecomment-709902078)

It worked. Thanks.
Linux is very funny. On Linux Mint it worked normally. But I had to change, it was bugging my nvidia driver.
