### ISSUE TITLE
How to display MangoHud on a running game??

### ISSUE THREAD

**Issue by Angell1993** [flightlessmango/MangoHud#456]
Very useful..

Seeing when I Launch games through Legendary, I can't use the mangohud launch option..
Mostly related to OpenGL..

I use auto global hook with Vulkan, works like a charm..

**Comment by baryluk** [comment]
For questions and help, I recommend going to a Discord channel.

**Comment by Angell1993** [comment]
Where would I find, a discord channel for MangoHUD??

**Comment by Leopard1907** [comment]
![Screenshot_20210108-141511_Samsung Internet](https://user-images.githubusercontent.com/24878978/104009392-05539f80-51bc-11eb-8a9e-de2a18dc8321.jpg)

Literally linked on this Github page which where you created this issue also.

Never too late for an eyesight check...

**Comment by Angell1993** [comment]
Actually I can't find it on the desktop version of the github page..
Maybe I can get lucky to find it on the mobile page, just like you did..

**Comment by flightlessmango** [comment]
https://discordapp.com/invite/Gj5YmBb

**Comment by Angell1993** [comment]
Well, I did find it, after I refreshed the page a few time, looks like it wasn't loaded in with all the other text for some reason..
