### ISSUE TITLE
Mangohud not working in Manjaro

### ISSUE THREAD

**Issue by JulioSordi** [flightlessmango/MangoHud#457]
Mangohud doesn't work in any of my games in Steam and Lutris, Mangohud only works through terminal commands such as mangohud vkcube, it doesn't work in any of my games regardless of Proton and Wine version.

**Comment by flightlessmango** [comment]
`NODEVICE_SELECT=1 mangohud %command%`

**Comment by JulioSordi** [comment]
> `NODEVICE_SELECT=1 mangohud %command%`

Didn't make any difference, Mangohud still won't display anything

**Comment by flightlessmango** [comment]
Yes the hud should work on Intel, but gpu information won't. Do you have 32bit mangohud installed?

**Comment by JulioSordi** [comment]
> Yes the hud should work on Intel, but gpu information won't. Do you have 32bit mangohud installed?

If you refer to lib32 yes i do

**Comment by flightlessmango** [comment]
might be related to this https://github.com/flightlessmango/MangoHud/issues/369#issuecomment-709902078

**Comment by JulioSordi** [comment]
> might be related to this [#369 (comment)](https://github.com/flightlessmango/MangoHud/issues/369#issuecomment-709902078)

Does it only affect Proton 5.13? my Mangohud doesn't work with any version of Proton, doesn't work in native Linux games like CS GO, Dota2 and Stardew Valley either

**Comment by shpinog** [comment]
Not working for dota2
