### ISSUE TITLE
Can't find the MangoHud folder on Manjaro

### ISSUE THREAD

**Issue by RenanRischiotto** [flightlessmango/MangoHud#458]
MangoHud is installed, however there's no folder for me to mess with the config file. Where is it?

![Screenshot_2021-01-10_15-01-45](https://user-images.githubusercontent.com/6877322/104131405-d6bcfc80-5354-11eb-81b4-c937c41238b8.png)
![Screenshot_2021-01-10_15-02-01](https://user-images.githubusercontent.com/6877322/104131409-d9b7ed00-5354-11eb-8154-9eb9c6a2de14.png)

**Comment by Leopard1907** [comment]
Check `/usr/share/doc/mangohud` directory and copy the example from there to your `.config/MangoHud` directory. Delete `.example` part of example config ofc.

**Comment by flightlessmango** [comment]
The folder is not automatically created, you can just create it yourself
