### ISSUE TITLE
[Feature Request] That you can enable it globally for OpenGL Games

### ISSUE THREAD

**Issue by Toadfield** [flightlessmango/MangoHud#461]
It doesn't work for OpenGL globally if you set it in .profile and that's a problem.
We have to change that,cause it is annoying to only be able to use it globally for vulkan Games.

**Comment by Angell1993** [comment]
FlightlessMango once told me, it wasn't exactly possible at this time.. OpenGL is too Tricky to get it working globally.. I've asked this before..

**Comment by flightlessmango** [comment]
On windows you would do a dll injection to achieve this, however on Linux there is no proper method to do that. I believe this is mostly due to security reasons and would require changes in the kernel. This makes it way outside the scope of mangohud
