### ISSUE TITLE
Vega/Raven APU can't get busyness correctly. GPU usage always 0 

### ISSUE THREAD

**Issue by SparkyCandle** [flightlessmango/MangoHud#464]
Using an Vega 8 (r3 2200g) and `AMDGPU` driver
From what i found is that mangohud uses and ancient way to get the GPU usage/busyness. It always reports 0 as GPU usage.
This is that ancient command im talking about:

`/sys/class/drm/card0/device/gpu_busy_percent`

but it returns `Invalid argument` if i run:

`cat /sys/class/drm/card0/device/gpu_busy_percent
cat: /sys/class/drm/card0/device/gpu_busy_percent: Invalid argument`

That also mean that the GPU usage reported in mangohud is always 0.
This problem is not limited only on Manjaro, i also had Opensuse Tumbleweed , some ubuntu based distros and they still have this very problem.

I also did a thread on Manjaro forum wich they said is a problem with mangohud itself and how it gets the gpu usage.

`radeontop` seems to be fine. I heard that `.../gpu_busy_precent` is the only way to get the GPU usage without root but radeontop works without root.

Also this screenshot is a summary of what i typed if github allows me to put screenshots:
![Screenshot from 2021-01-23 00-09-09](https://user-images.githubusercontent.com/68326282/105606739-ce78ae80-5da3-11eb-957e-bf701ca6068c.png)

**Comment by baryluk** [comment]
There are two mechanisms to get GPU usage. There were in the past 3 methods.

1) One is via `gpu_busy_percent`. Not sure why it doesn't work for you. Maybe just the path is incorrect. Do you have multiple GPUs in the system? For example integrated Intel and separate AMD GPU? If so, can you share the output of `ls -lh /sys/class/drm/`

2) Another is by using AMDGPU DRM ioctl's. It doesn't require root, and is what radeontop 1.3 uses now.

3) Old way is by directly talking to PCIe bus and card registers. This is what radeontop 1.2 used, and that required a root. The radeontop 1.3 still can do it, but it is no longer a default way of doing things.

Internally all these methods do basically the same thing, but the `gpu_busy_percent` does return slightly different figures because it calculates it differently that what the radeontop is doing.

**Comment by SparkyCandle** [comment]
>  ... Do you have multiple GPUs in the system? For example integrated Intel and separate AMD GPU? If so, can you share the output of `ls -lh /sys/class/drm/`. Also please share `sudo lspci`.

The only GPU is the only i mentioned in the issue: Vega 8 (integrated with the r3 2200g)
```
% ls -lh /sys/class/drm/ 
total 0
lrwxrwxrwx 1 root root    0 Jan 23 21:58 card0 -> ../../devices/pci0000:00/0000:00:08.1/0000:0a:00.0/drm/card0
lrwxrwxrwx 1 root root    0 Jan 23 21:58 card0-DP-1 -> ../../devices/pci0000:00/0000:00:08.1/0000:0a:00.0/drm/card0/card0-DP-1
lrwxrwxrwx 1 root root    0 Jan 23 21:58 card0-DP-2 -> ../../devices/pci0000:00/0000:00:08.1/0000:0a:00.0/drm/card0/card0-DP-2
lrwxrwxrwx 1 root root    0 Jan 23 21:58 card0-HDMI-A-1 -> ../../devices/pci0000:00/0000:00:08.1/0000:0a:00.0/drm/card0/card0-HDMI-A-1
lrwxrwxrwx 1 root root    0 Jan 23 21:58 card0-HDMI-A-2 -> ../../devices/pci0000:00/0000:00:08.1/0000:0a:00.0/drm/card0/card0-HDMI-A-2
lrwxrwxrwx 1 root root    0 Jan 23 21:58 renderD128 -> ../../devices/pci0000:00/0000:00:08.1/0000:0a:00.0/drm/renderD128
lrwxrwxrwx 1 root root    0 Jan 23 21:58 ttm -> ../../devices/virtual/drm/ttm
-r--r--r-- 1 root root 4.0K Jan 23 21:58 version
```
for some reasons displayport-1 is a VGA port but whatever
```
% sudo lspci
[sudo] password for mihai: 
00:00.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Raven/Raven2 Root Complex
00:00.2 IOMMU: Advanced Micro Devices, Inc. [AMD] Raven/Raven2 IOMMU
00:01.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 00h-1fh) PCIe Dummy Host Bridge
00:01.2 PCI bridge: Advanced Micro Devices, Inc. [AMD] Raven/Raven2 PCIe GPP Bridge [6:0]
00:08.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 00h-1fh) PCIe Dummy Host Bridge
00:08.1 PCI bridge: Advanced Micro Devices, Inc. [AMD] Raven/Raven2 Internal PCIe GPP Bridge 0 to Bus A
00:08.2 PCI bridge: Advanced Micro Devices, Inc. [AMD] Raven/Raven2 Internal PCIe GPP Bridge 0 to Bus B
00:14.0 SMBus: Advanced Micro Devices, Inc. [AMD] FCH SMBus Controller (rev 61)
00:14.3 ISA bridge: Advanced Micro Devices, Inc. [AMD] FCH LPC Bridge (rev 51)
00:18.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Raven/Raven2 Device 24: Function 0
00:18.1 Host bridge: Advanced Micro Devices, Inc. [AMD] Raven/Raven2 Device 24: Function 1
00:18.2 Host bridge: Advanced Micro Devices, Inc. [AMD] Raven/Raven2 Device 24: Function 2
00:18.3 Host bridge: Advanced Micro Devices, Inc. [AMD] Raven/Raven2 Device 24: Function 3
00:18.4 Host bridge: Advanced Micro Devices, Inc. [AMD] Raven/Raven2 Device 24: Function 4
00:18.5 Host bridge: Advanced Micro Devices, Inc. [AMD] Raven/Raven2 Device 24: Function 5
00:18.6 Host bridge: Advanced Micro Devices, Inc. [AMD] Raven/Raven2 Device 24: Function 6
00:18.7 Host bridge: Advanced Micro Devices, Inc. [AMD] Raven/Raven2 Device 24: Function 7
01:00.0 USB controller: Advanced Micro Devices, Inc. [AMD] 400 Series Chipset USB 3.1 XHCI Controller (rev 01)
01:00.1 SATA controller: Advanced Micro Devices, Inc. [AMD] 400 Series Chipset SATA Controller (rev 01)
01:00.2 PCI bridge: Advanced Micro Devices, Inc. [AMD] 400 Series Chipset PCIe Bridge (rev 01)
02:00.0 PCI bridge: Advanced Micro Devices, Inc. [AMD] 400 Series Chipset PCIe Port (rev 01)
02:01.0 PCI bridge: Advanced Micro Devices, Inc. [AMD] 400 Series Chipset PCIe Port (rev 01)
02:04.0 PCI bridge: Advanced Micro Devices, Inc. [AMD] 400 Series Chipset PCIe Port (rev 01)
02:05.0 PCI bridge: Advanced Micro Devices, Inc. [AMD] 400 Series Chipset PCIe Port (rev 01)
02:06.0 PCI bridge: Advanced Micro Devices, Inc. [AMD] 400 Series Chipset PCIe Port (rev 01)
02:07.0 PCI bridge: Advanced Micro Devices, Inc. [AMD] 400 Series Chipset PCIe Port (rev 01)
07:00.0 PCI bridge: Integrated Technology Express, Inc. IT8893E PCIe to PCI Bridge (rev 41)
09:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 0c)
0a:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Raven Ridge [Radeon Vega Series / Radeon Vega Mobile Series] (rev c8)
0a:00.1 Audio device: Advanced Micro Devices, Inc. [AMD/ATI] Raven/Raven2/Fenghuang HDMI/DP Audio Controller
0a:00.2 Encryption controller: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 10h-1fh) Platform Security Processor
0a:00.3 USB controller: Advanced Micro Devices, Inc. [AMD] Raven USB 3.1
0a:00.4 USB controller: Advanced Micro Devices, Inc. [AMD] Raven USB 3.1
0a:00.5 Multimedia controller: Advanced Micro Devices, Inc. [AMD] Raven/Raven2/FireFlight/Renoir Audio Processor
0a:00.6 Audio device: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 10h-1fh) HD Audio Controller
0b:00.0 SATA controller: Advanced Micro Devices, Inc. [AMD] FCH SATA Controller [AHCI mode] (rev 61)

```

>     2. Another is by using AMDGPU DRM ioctl's. It doesn't require root, and is what radeontop 1.3 uses now.
Well if the default way to get the busyness fails couln't this be implemented as a backup?

>     3. Old way is by directly talking to PCIe bus and card registers. This is what radeontop 1.2 used, and that required a root. The radeontop 1.3 still can do it, but it is no longer a default way of doing things.
Maybe this is what i heard about getting the bussynes with root.
> 
> Internally all these methods do basically the same thing, but the `gpu_busy_percent` does return slightly different figures because it calculates it differently that what the radeontop is doing.

**Comment by baryluk** [comment]
> Well if the default way to get the busyness fails couln't this be implemented as a backup?
Sure, it just is harder to implement, and we would need to look how radeontop does it, possibly reimplement it. It is just more work.

Do you maybe have a `/sys/class/drm/card0/device/gpu_busy` instead (without `_percent`) ?

**Comment by SparkyCandle** [comment]
> Do you maybe have a `/sys/class/drm/card0/device/gpu_busy` instead (without `_percent`) ?\

```
% cat /sys/class/drm/card0/device/gpu_busy
cat: /sys/class/drm/card0/device/gpu_busy: No such file or directory

```
> Also what is the kernel version, please share output of `uname -a`.
`Linux manjaro 5.9.16-1-MANJARO #1 SMP PREEMPT Mon Dec 21 22:00:46 UTC 2020 x86_64 GNU/Linux`

sorry for being late i refreshed like 100 times and just now appeared your reply

**Comment by SparkyCandle** [comment]
Changed kernels from 5.9 -> 5.10 -> 5.11. Same result

**Comment by jackun** [comment]
Use the search Luke. Vega APUs don't work with `gpu_busy_percent` for some reason. Probably have to check out `umr` if its method is supported/usable.

**Comment by SparkyCandle** [comment]
> Use the search Luke.
What does this mean "Luke"? I searched in the AUR and official repos and found nothing related. just some X terminals.

> Probably have to check out `umr `if its method is supported/usable.
Had to compile it manually. I searched the arguments and it seems to result this:

```
sudo umr --config
	asic.instance == 0
	asic.devname == 0000:0a:00.0

	asic.gtt_size == 3221225472
	asic.vis_vram_size == 1073741824
	asic.vram_size == 1073741824


	umr.version == 8bf83aea7465

	vbios.version == 113-RAVEN-107

	fw.VCE == .feature==0 .firmware==0x00000000
	fw.UVD == .feature==0 .firmware==0x00000000
	fw.MC == .feature==0 .firmware==0x00000000
	fw.ME == .feature==49 .firmware==0x000000a3
	fw.PFP == .feature==49 .firmware==0x000000bb
	fw.CE == .feature==49 .firmware==0x0000004f
	fw.RLC == .feature==1 .firmware==0x00000213
	fw.RLC == .feature==0 .firmware==0x00000000
	fw.RLC == .feature==0 .firmware==0x00000000
	fw.RLC == .feature==0 .firmware==0x00000000
	fw.MEC == .feature==49 .firmware==0x000001b4
	fw.MEC2 == .feature==49 .firmware==0x000001b4
	fw.SOS == .feature==0 .firmware==0x00000000
	fw.ASD == .feature==0 .firmware==0x21000039
	fw.TA == .feature==0 .firmware==0x00000000
	fw.TA == .feature==0 .firmware==0x00000000
	fw.TA == .feature==0 .firmware==0x00000000
	fw.TA == .feature==0 .firmware==0x00000000
	fw.SMC == .feature==0 .firmware==0x00001e48
	fw.SDMA0 == .feature==41 .firmware==0x000000a9
	fw.VCN == .feature==0 .firmware==0x0210c001
	fw.DMCU == .feature==0 .firmware==0x00000000
	fw.DMCUB == .feature==0 .firmware==0x00000000
	fw.TOC == .feature==0 .firmware==0x00000000
	fw.VBIOS == .feature==0 .firmware==0x00000000


	gfx.max_shader_engines == 1
	gfx.max_tile_pipes == 4
	gfx.max_cu_per_sh == 11
	gfx.max_sh_per_se == 1
	gfx.max_backends_per_se == 2
	gfx.max_texture_channel_caches == 4
	gfx.max_gprs == 256
	gfx.max_gs_threads == 32
	gfx.max_hw_contexts == 8
	gfx.sc_prim_fifo_size_frontend == 32
	gfx.sc_prim_fifo_size_backend == 256
	gfx.sc_hiz_tile_fifo_size == 48
	gfx.sc_earlyz_tile_fifo_size == 1216
	gfx.num_tile_pipes == 0
	gfx.backend_enable_mask == 3
	gfx.mem_max_burst_length_bytes == 0
	gfx.mem_row_size_in_kb == 0
	gfx.shader_engine_tile_size == 0
	gfx.num_gpus == 0
	gfx.multi_gpu_tile_size == 0
	gfx.mc_arb_ramcfg == 0
	gfx.gb_addr_config == 603979842
	gfx.num_rbs == 2
	gfx.family = 142, Raven
	gfx.rev_id == 00000001
	gfx.external_rev_id == 00000021
	gfx.cg_flags == 017d9fcf
		AMD_CG_SUPPORT_GFX_MGCG
		AMD_CG_SUPPORT_GFX_MGLS
		AMD_CG_SUPPORT_GFX_CGCG
		AMD_CG_SUPPORT_GFX_CGLS
		AMD_CG_SUPPORT_GFX_CP_LS
		AMD_CG_SUPPORT_GFX_RLC_LS
		AMD_CG_SUPPORT_MC_LS
		AMD_CG_SUPPORT_MC_MGCG
		AMD_CG_SUPPORT_SDMA_LS
		AMD_CG_SUPPORT_SDMA_MGCG
		AMD_CG_SUPPORT_BIF_LS
		AMD_CG_SUPPORT_HDP_LS
		AMD_CG_SUPPORT_HDP_MGCG
		AMD_CG_SUPPORT_DRM_LS
		AMD_CG_SUPPORT_BIF_MGCG
		AMD_CG_SUPPORT_GFX_3D_CGCG
		AMD_CG_SUPPORT_GFX_3D_CGLS
		AMD_CG_SUPPORT_DRM_MGCG
		AMD_CG_SUPPORT_VCN_MGCG
	gfx.pg_flags == 000041a1
		AMD_PG_SUPPORT_GFX_PG
		AMD_PG_SUPPORT_CP
		AMD_PG_SUPPORT_RLC_SMU_HS
		AMD_PG_SUPPORT_SDMA
		AMD_PG_SUPPORT_VCN
```

**Comment by SparkyCandle** [comment]
Title edited due possibile wrong understanding of the problem.

**Comment by jackun** [comment]
As per #463 , see if `umr --top` returns anything usable.

**Comment by SparkyCandle** [comment]
> As per #463 , see if `umr --top` returns anything usable. Probably in the flags already, but I'm unfamiliar with umr :P

![image](https://user-images.githubusercontent.com/68326282/105632055-ffb3b600-5e59-11eb-90a5-fb72d445f4e0.png)

**Comment by baryluk** [comment]
That is interesting indeed. It might be worth doing a search on https://gitlab.freedesktop.org/drm/amd/-/issues about this , or if nothing is there, opening a bug report about this.

**Comment by SparkyCandle** [comment]
This issue should stay open (unless im wrong) till either amd driver developers fix this somehow or mangohud developers implement to get GPU usage with AMDGPU DRM ioctl's.

> That is interesting indeed. It might be worth doing a search on ... about this , or if nothing is there, opening a bug report about this.

Just found a bug on their gitlab about unstable measurements that are unstable and constantly goes to 0. My problem is it's always 0. I did open a issue there so i will check later if there are any solution.

**Comment by flgx16** [comment]
@SparkyCandle I tried with AMDGPU DRM IOCTLs and it still doesn't work on my Vega 11.
It looks like `gpu_busy_percent` also uses IOCTLs.

**Comment by flgx16** [comment]
Pushed to https://github.com/flgx16/MangoHud/tree/amdgpu-ioctl

**Comment by SparkyCandle** [comment]
@flgx16 I compiled your patched version seems to do nothing at all.

**Comment by flgx16** [comment]
> @flgx16 I compiled your patched version seems to do nothing at all in the meaning of getting gpu busyess.

Yeah, that's what I said

**Comment by SparkyCandle** [comment]
This is a possibile problem with Vega APU or the driver from them. I will investigate more

**Comment by flgx16** [comment]
Radeontop doesn't seem to use IOCTLs

**Comment by SparkyCandle** [comment]
From https://gitlab.freedesktop.org/drm/amd/-/issues/1453.
>Some older versions of the sbios did not support this interface on Raven.  You might try an updated sbios.
I will do a BIOS update .This stays open till i flash and check if it's working.

**Comment by SparkyCandle** [comment]
_**No solution found**_. I updated my BIOS to the lasted from LENOVO site. Issue will be closed

**Comment by txtsd** [comment]
So this will never work?

**Comment by Trollimpo** [comment]
I am using a Ryzen 3 3200g and mangohud provided by GOverlay and now GPU usage works!

**Comment by txtsd** [comment]
> I am using a Ryzen 3 3200g and mangohud provided by GOverlay and now GPU usage works!

How? Nothing has changed.

**Comment by SparkyCandle** [comment]
Seems that version 6.6-1 fixed it somehow

**Comment by SparkyCandle** [comment]
This (hopefully) confirms that 6.6-1 fixes it
![Screenshot_20220116_211403](https://user-images.githubusercontent.com/68326282/149674458-9ef7abfe-cf7d-468d-bc22-8ff53f105820.png)

**Comment by 0ibaba** [comment]
@SparkyCandle Does it still work for you?
I'm on version 0.6.8-1 and it's still showing up as 0%


![image](https://user-images.githubusercontent.com/69052158/191437602-46de878b-2f1c-4b34-8b7f-4bc738ff4202.png)
