### ISSUE TITLE
MangoHud doesn't work at lower resolutions than 1080p.

### ISSUE THREAD

**Issue by ghost** [flightlessmango/MangoHud#467]
I'm using Lutris to play a native 64-bit OpenGL game called SkillWarz.
MangoHud works on 1080p but whenever I lower the resolution it doesn't appear anymore.
Distro: Pop!_OS
Using built-in Lutris option: FPS Counter (MangoHud)  Enabled (OpenGL).

**Comment by utherbone** [comment]
I downloaded the version for native Linux (I didn't use Lutris) and it doesn't display MangoHud doesn't matter in what resolution, nor even in the terminal it shows that it loaded.
It is something that needs to be investigated!

**Comment by jackun** [comment]
Running manually with `mangohud --dlsym ./skillwarz.x86_64` seems to work with v0.6.4
