### ISSUE TITLE
Log is not exported

### ISSUE THREAD

**Issue by FabioSedia** [flightlessmango/MangoHud#472]
Toggling log on VKcube works fine, and i get the csv when i stop the logging at the folder i set it in mangohud.conf. However, this does not work with battlefield 1, as log starts and ends properly with the message "Logging finished: Duration etc..." but there's no file in the folder. no relevant log from lutris. Why this happens? I also have set MANGOHUD_CONFIG=output_file=/home/fabio/mangologs/bf1_mangohud in the lutris env vars. so what's the problem?

**Comment by flightlessmango** [comment]
`output_file` is deprecated, use `output_folder` instead

**Comment by FabioSedia** [comment]
> `output_file` is deprecated, use `output_folder` instead

Yes but even when not setting anything vkcube exports to home and battlefield does not. Is this a known difference and the env var is required on lutris, or the problem still exists and this is just a workaround?

**Comment by flightlessmango** [comment]
If you don't set `output_folder`, no log file is created. It must be in a config file that you're unaware of
