### ISSUE TITLE
Causes flicker when in full screen

### ISSUE THREAD

**Issue by dtmoodie** [flightlessmango/MangoHud#473]
On ubuntu 20.04 with an i3 window manager and nvidia binary drivers 460.32.03 I run into really bad flickering in any GPU accelerated application when put into full screen.
IE the screen goes black for 2 - 4 seconds then renders correctly for about half a second.
The issue is not present in windowed mode.  This issue becomes apparent even when not explicitly launching an application with mangohud.
Uninstalling mangohud completely resolved my issue immediately.
I'm using the binary version 0.6.1 from the releases page.
The issue is also even present on a full screen google chrome window.

**Comment by flightlessmango** [comment]
Do you have mangohud "globally enabled"? i.e added to ~/.profile or the like
Unless enabled MangoHud shouldn't/wouldn't interact with any application

**Comment by dtmoodie** [comment]
Hello, my apologize my issue was not caused by mangohud.  It was all just a coincidence.
