### ISSUE TITLE
Different installing from source than in README.md explained

### ISSUE THREAD

**Issue by freddii** [flightlessmango/MangoHud#475]
Same as in README.md:
git clone --recurse-submodules https://github.com/flightlessmango/MangoHud.git
cd MangoHud
./build.sh build
./build.sh package

Different installation:
cd build
../bin/mangohud-setup.sh install

Example to run after install:
mangohud glxgears

**Comment by flightlessmango** [comment]
I don't understand the motivation for why and this wouldn't work
