### ISSUE TITLE
MangoHUD doesn't work with native Wayland OpenGL games

### ISSUE THREAD

**Issue by TheComputerGuy96** [flightlessmango/MangoHud#477]
When I try to launch a native Wayland game with MangoHUD (with and without dlsym), the overlay doesn't show up and there's no console output of any kind (even with debug build type and glibcxx asserts enabled), although the MangoHUD debug variables work (like MANGOHUD_HOOK_DLSYM) and show console output

I'm using the develop branch of MangoHUD

The games I tested are SuperTuxKart (the Arch Linux package with SDL_VIDEODRIVER=wayland), Xonotic (the SDL version with the same info as SuperTuxKart) and Minecraft Java Edition (with MultiMC and some GLFW patches found at https://github.com/glfw/glfw/issues/1725)

Running the games with XWayland makes console output and overlay show up

vkcube compiled with Wayland support seems to work with MangoHUD, so this is probably a OpenGL-only issue

**Comment by utherbone** [comment]
Tried with 'glxgears' to see if MangoHUD's hud?

**Comment by TheComputerGuy96** [comment]
> Tried with 'glxgears' to see if MangoHUD's hud?

glxgears is a X11 application, so it obviously works fine

**Comment by utherbone** [comment]
Okay, please excuse me, I had no idea about that, I'm going to install a distro with wayland and do some tests.

**Comment by jackun** [comment]
Might work with https://github.com/flightlessmango/MangoHud/commit/3e77dd6e0bd9f282e1f1e2cbe1bb816114f7bcc2 now

**Comment by TheComputerGuy96** [comment]
I should've closed this issue a long time ago, but MangoHUD now works with native Wayland OpenGL games if you use the develop branch and enable compile-time Wayland support in MangoHUD

There's still an issue with shortcuts (like disabling the HUD) not working, but that's a different issue

Here are some screenshots:
![Xonotic with Wayland and MangoHUD](https://user-images.githubusercontent.com/19169000/111900825-5514d980-8a3d-11eb-95c2-e839cec84580.png)
![Minecraft with Wayland and MangoHUD](https://user-images.githubusercontent.com/19169000/111900883-a58c3700-8a3d-11eb-99fd-a94efc04db7f.png)

**Comment by Faalagorn** [comment]
@TheComputerGuy96 I stumbled on the same issue on https://github.com/flightlessmango/MangoHud/issues/572#issuecomment-899118646 now: MangoHud doesn't show for me on OpenGL games running Wayland, I tried recompiling it with ` -Dwith_wayland=enabled` for both 32- and 64-bit (the game is 32-bit though), but that seems to didn't help. I also made sure @jackun's commit is in there (it is), am I missing something? What options did you use in compile time? Here's mine (I added them to the pkgbuild https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=mangohud-git#n24

```
     arch-meson --wrap-mode=forcefallback \
     -Dappend_libdir_mangohud=false \
     -Dwith_wayland=enabled \
     -Duse_system_vulkan=enabled "$_pkgbase" build64

     arch-meson -Dappend_libdir_mangohud=false -Dwith_wayland=enabled -Duse_system_vulkan=enabled "$_pkgbase" build32 --libdir lib32
```

**Comment by TheComputerGuy96** [comment]
@Faalagorn Have you tried both no dlsym and dlsym with those 2 games? If yes, then can you get an apitrace?

**Comment by Faalagorn** [comment]
> @Faalagorn Have you tried both no dlsym and dlsym with those 2 games? If yes, then can you get an apitrace?

Yup, tried both variants. I'll try to make an apitrace when I get home!

**Comment by Faalagorn** [comment]
Here's the traces, one with dlysm and one without for both Dead Island and Spec Ops. https://we.tl/t-VG4vLj0AFz

Dead Island is launched with `-nologos` to skip into and Spec Ops is launched with both `-nostartupmovies -nosplash` to skip logo and splash screen.

**Comment by jackun** [comment]
Can't get these to draw anything, no *SwapBuffer calls and hang qapitrace. apitrace 8.0 doesn't at least hang. 
Spec Ops works for me :tm: on x11 and plasma wayland.

**Comment by Faalagorn** [comment]
> Set LD_PRELOAD manually and don't use $LD_PRELOAD so steam overlay doesn't get loaded. SDL etc keeps going directly through gameoverlayrenderer.so `dlsym` etc. though `glXGetProcAddress(ARB)` gets hooked.

I tried disabling overlay and running both of these games with `LD_PRELOADING` all the 32-bit and even 64-bit libraries (regular and dlysm), but no luck. Also worth noting that I'm on `steam-native-runtime`, I doubt it will change but let me try on regular steam.

**Comment by jackun** [comment]
Hmm, ok just to be 100% sure we're on the same page, command line I used 

`LD_PRELOAD=/usr/lib/mangohud/lib32/libMangoHud_dlsym.so:/usr/lib/mangohud/lib32/libMangoHud.so %command%`

(replace lib32 per distro package)

**Comment by Faalagorn** [comment]
> Hmm, ok just to be 100% sure we're on the same page, command line I used
> 
> `SDL_VIDEODRIVER=wayland LD_PRELOAD=/usr/lib/mangohud/lib32/libMangoHud_dlsym.so:/usr/lib/mangohud/lib32/libMangoHud.so %command%`
> 
> (replace lib32 per distro packaging)

Yup. I just didn't realize you were suppose to preload two files at once in case of dlysm, but it didn't help either. I also tried `LD_PRELOAD`ing glxgears to see if the approach is working (it is).
