### ISSUE TITLE
How do you set the logging directory?

### ISSUE THREAD

**Issue by AverytheFurry** [flightlessmango/MangoHud#479]
I have read the readme.md multiple times and I'm still confused. I tried typing `MANGOHUD_CONFIG=output_folder=/home/avery/MangoHud/` into the terminal, but it didn't do anything..

**Comment by utherbone** [comment]
Hi is correct use is: ` mangohud MANGOHUD_CONFIG=output_folder=/path_to_directory_you_prefer_with_out_bar_in _end_path app_run_with_mangohud`

For log press (L Shift) + (F2) to start and stop.

**Comment by AverytheFurry** [comment]
I typed `mangohud MANGOHUD_CONFIG=output_folder=/home/avery/mangologs` into console, nothing was outputted to the folder after hitting shift+f2 twice.

**Comment by flightlessmango** [comment]
@AverytheFurry use environment variables before the `mangohud` command and make sure the folder you're pointing to exists

**Comment by flightlessmango** [comment]
You haft to add the `MANGOHUD_CONFIG` part in the launch options as well

**Comment by AverytheFurry** [comment]
> You haft to add the `MANGOHUD_CONFIG` part in the launch options as well

Oh, alright, before or after `%command%`?

**Comment by AverytheFurry** [comment]
Oh, ok, thank you - `mangohud MANGOHUD_CONFIG=output_folder=/home/avery/mangologs %command%` worked!
