### ISSUE TITLE
Show GPU graphic and memory clock

### ISSUE THREAD

**Issue by terencode** [flightlessmango/MangoHud#48]

**Comment by flightlessmango** [comment]
This is now implemented in the gpuclocks branch
You can use this package to test these features if you don't want to compile
[MangoHud-0.2.0.r34.gbefa101.tar.gz](https://flightlessmango.com/MangoHud-0.2.0.r34.gbefa101.tar.gz)
`MANGOHUD_CONFIG=full` or `MANGOHUD_CONFIG=gpu_core_clock,gpu_mem_clock,vram`

I also need some opinions about the memory clock, it's currently doubled as that's how it's showed in nvidia-settings. But there seems to be some differing opinions on how it should be displayed, what do you guys think? how are overclocking softwares displaying it? how does afterburner handle it etc?
