### ISSUE TITLE
"MANGOHUD= 1 %command%", and "mangohud %command%" both cause my games to fail at starting.

### ISSUE THREAD

**Issue by lystrosaur** [flightlessmango/MangoHud#481]
when i put the mangohud command in, the game, which normally works just fine, turns off after a couple seconds of starting up.

**Comment by coffeecrisp** [comment]
Try
MANGOHUD_CONFIG=full mangohud %command%
and if that fails, then try
MANGOHUD_CONFIG=full mangohud.x86 %command%

**Comment by flightlessmango** [comment]
AMD gpu? try `NODEVICE_SELECT=1 mangohud %command%`

**Comment by lystrosaur** [comment]
Hello, turns out it just doesn't work with newest versions of proton. Sorry.

śr., 3 mar 2021, 02:26 użytkownik flightlessmango <notifications@github.com>
napisał:
