### ISSUE TITLE
validation errors when running Vulkan application with mangohud validation layers enabled on a ryzen laptop

### ISSUE THREAD

**Issue by warriormaster12** [flightlessmango/MangoHud#482]
So I get bombarded with validation errors when I execute my Vulkan application with validation layers enabled. I thought at first that it was my application that suffered from a bug but when I tried with my older project that used to work with mangohud no problem, I get the same result. 

This bug only accrues when on my laptop. 
Ryzen 5 2500 U 
8 gb ram 
Arch-linux  

here's the output that I get. It's a bit long but just scroll down till the end.
[output.log](https://github.com/flightlessmango/MangoHud/files/5984176/output.log)

**Comment by jackun** [comment]
Probably fixed with 6c737dc7349dc891da7a280e069e5c5a09b2d1f9
