### ISSUE TITLE
[Question] Why do we need to use the "mangohud" command to use it on opengl apps instead of just using the env var?

### ISSUE THREAD

**Issue by Toadfield** [flightlessmango/MangoHud#483]
I mean if I use just "MANGOHUD_DLSYM=1",then it doesn't work,it only works with "mangohud" and "MANGOHUD_DLSYM=1" at once.
Why is that do?

**Comment by jackun** [comment]
`MANGOHUD=1` tells vulkan loader (`libvulkan.so`) to also load MangoHud layer (libMangoHud.so) and hooks it into the chain of layers.
OpenGL doesn't have layers so it doesn't have a "layer loader" built-in so we have to override GL functions with preloading `libMangoHud.so` that contains GL functions we are interested in.
`MANGOHUD_DLSYM=1` or `--dlsym` tells `mangohud` to also preload `libMangoHud_dlsym.so`. See `LD_PRELOAD`.

**Comment by Toadfield** [comment]
But then,why does Gallium Hud not need a command to work?
I mean it only needs `GALLIUM_HUD=fps glxgears` to work afaik.

**Comment by tpalli** [comment]
Because Gallium HUD is part of the Mesa driver infrastructure/implementation, there is no need for preload or dynamically load an external library.

**Comment by Toadfield** [comment]
So if I got it right,then a OpenGL overlay that isn't implemented into Mesa can't work without a layer system?

**Comment by tpalli** [comment]
It is possible to implement such things by overriding functions via LD_PRELOAD (as described above) but not nearly as nice to implement as with Vulkan layers.

**Comment by Toadfield** [comment]
I did a feature request for mesa to add a OpenGL layer system,I hope they will add it.
Cause I hate it so much that I can't use a good overlay for OpenGL apps globally.
I don't wanna use gallium hud.

**Comment by Toadfield** [comment]
So I did that feature Request for OpenGL mesa,but a dev then said that it doesn't need a command to use LD_PRELOAD.
Is that right?
Cause then it could work with only env vars.
[(Full Discussion I had with the devs)](https://gitlab.freedesktop.org/mesa/mesa/-/issues/4146#note_809008)

**Comment by jackun** [comment]
> LD_PRELOAD

It's literally what the "command" does. Don't over think it.

**Comment by flightlessmango** [comment]
You can use `LD_PRELOAD=/path/to/mangohud.so` and add it to ~?.profile or how you're doing with `MANGOHUD=1`. This will have mangohud inject in to every app that is started, this is not how mangohud is intended to be used and is likely going to cause issues

**Comment by Toadfield** [comment]
So if I got it right,then I have to use `LD_PRELOAD=/path/to/mangohud.so` and `MANGOHUD_DLSYM=1` if I don't wanna use a command?
> mangohud inject in to every app that is started

So does that mean that this will also enable it for Vulkan?
> this is not how mangohud is intended to be used and is likely going to cause issues

What kind of issues?
And why does it have issues then?
I mean I thought that `LD_PRELOAD=/path/to/mangohud.so` is the same as using  the `mangohud` command but with a env var,so what did I understand wrong here?

**Comment by flightlessmango** [comment]
`LD_PRELOAD` will only work for OpenGL, not Vulkan. Also you have the issue of some games needing the dlsym `.so` files instead.

> What kind of issues?
I'd imagine it can crash a lot of programs, it's not tested or intended to be run with any app so it's not made for it / prepared for it. We don't know what could/would/should happen with any random app

**Comment by Toadfield** [comment]
> I'd imagine it can crash a lot of programs, it's not tested or intended to be run with any app so it's not made for it / prepared for it. We don't know what could/would/should happen with any random app

Then I will test it globally later,cause I really wanna use mangohud globally.
And also,can I report issues for that also here or does that not count as a real mangohud issue cause it isn't supposed to work like that?

**Comment by Toadfield** [comment]
Btw where is the mangohud.so located by default?

**Comment by flightlessmango** [comment]
You should find them in `/usr/lib/mangohud/`

**Comment by Toadfield** [comment]
ok

**Comment by Toadfield** [comment]
Btw is it a better idea to enable both,the normal libMangoHud.so and libMangoHud_dlsym.so or only one of them?
