### ISSUE TITLE
A few games fails to launch when using MangoHud

### ISSUE THREAD

**Issue by Ahmed-E-86** [flightlessmango/MangoHud#486]
Mafia Definitive Edition, Detroit Become Human, and Little Nightmares freezes during loading when using MangoHud, but launch successfully when I do not use it.

In the terminal I get errors like these:
```
0060:fixme:seh:virtual_unwind calling personality routine in system library not supported yet
0060:fixme:seh:virtual_unwind calling personality routine in system library not supported yet
0060:fixme:seh:virtual_unwind calling personality routine in system library not supported yet
0060:fixme:seh:virtual_unwind calling personality routine in system library not supported yet
0060:err:ole:start_rpcss Failed to start RpcSs service
003c:err:service:process_send_command service protocol error - failed to write pipe!
0024:err:environ:run_wineboot boot event wait timed out
```
Wine-Staging 6.2
MangoHud 0.6.1
DXVK 1.7.3
AMD Radeon HD 8750M
Mesa 20.3.4
Intel Core I5 4200M - 6gb of RAM

**Comment by flightlessmango** [comment]
Have you tried `NODEVICE_SELECT=1` ?

**Comment by Ahmed-E-86** [comment]
> Have you tried `NODEVICE_SELECT=1` ?

Thanks! I tested with Little Nightmares, and it loaded successfully, but I have never heard of it before. What does it do exactly?

**Comment by flightlessmango** [comment]
It's a vulkan layer for choosing which GPU should be used. However it currently breaks mangohud and the easiest workaround is to just disable it

**Comment by el1-x** [comment]
I didn't see the point in opening a new issue so I'll jump onto this one as I am having a similar issue.
For the last few years I have been using an Nvidia based GPU with MangoHUD from the AUR - no issues. 

I have recently moved to an AMD based GPU and I am unable to launch a game with MangoHUD 'enabled'.
I'm not exactly sure where to start.. I have the below config

AMD RX 6700XT
Kernel 5.12.11
Mesa/RadV  21.1.2
OpenGL 4.6
OpenGL ES 3.2

Installed packages:
```
lib32-vulkan-icd-loader 1.2.176-1
lib32-vulkan-radeon 21.1.2-1
vulkan-icd-loader 1.2.178-1
vulkan-radeon 21.1.2-1
vulkan-tools 1.2.172-1
```
```
lib32-libva-mesa-driver 21.1.2-1
lib32-mesa 21.1.2-1
libva-mesa-driver 21.1.2-1
mesa 21.1.2-1
mesa-demos 8.4.0-4
mesa-vdpau 21.1.2-1
```

At first I used the launch option `mangohud %command%` that I have always used. Additionally I have added `NODEVICE_SELECT=1` & `MANGOHUD=1` to the launch option without success. 

Where to next?

**Comment by flightlessmango** [comment]
Which game is it? try building from develop branch or use `mangohud-git`

**Comment by gort818** [comment]
@el1-x I have the same setup as you.. so no issue with your hardware/software setup. Yeah try out the develop branch as everything work for me as intended.

**Comment by el1-x** [comment]
At the moment I can say 'every' game that I tried, didn't work. But I've only attempted to launch two games. 
The first was Rocket League and the second Generation Zero.

**Comment by el1-x** [comment]
I removed MangoHUD from my system and rebuilt from the AUR using `magohud-git mangohud-common-git lib32-mangohub-git`
Thanks for the tip!

Any idea why the standard package/build was failing?
