### ISSUE TITLE
MangoHud is upside down on Ryujinx

### ISSUE THREAD

**Issue by Miepee** [flightlessmango/MangoHud#488]
MangoHud is rendered upside down on the Ryujinx Emulator.
Since Ryujinx only has OpenGL as it's Graphics API, it needs to be run like this: `MANGOHUD_DLSYM=1 mangohud ./Ryujinx`

Media:
![grafik](https://user-images.githubusercontent.com/38186597/108522148-c9d4e680-72cc-11eb-8a73-54bcdf7965af.png)
![grafik](https://user-images.githubusercontent.com/38186597/108522169-cf323100-72cc-11eb-82ea-a87d95b9e9f3.png)

This also seem to depend on the game being run. As seen in the media, Mario Kart 8 Deluxe and Clubhouse games have this issue, but according to some users, Mario Odyssey runs without that issue.
Tested on Arch Linux with an RX 570, an RX 580 and an GTX 1070Ti

**Comment by jackun** [comment]
Does this https://github.com/flightlessmango/MangoHud/commit/6f056da7fabd2a23c177488e93637439b7539dc9 fix it?

**Comment by Miepee** [comment]
Sorry for the really long delay.  
On all the above mentioned cards, Commit `76b571b` did not correct that behavior.
MangoHud when Ryujinx tried to load the game, but disappeared as soon the game displayed graphics.

**Comment by Miepee** [comment]
Correction:
I just found out, that disabling Ryujinx' Vsync causes Mangohud to dissapear.
Enabling it again still has it upside down, just as in the screenshots in the first post.

I tested `54d6a8e` as well, on there MangoHud is still upside down, but now fully in the down left corner, instead of floating a bit above.

**Comment by jackun** [comment]
91807bfb9819c19ba008fb503e4b016251fc75c8 feels hackish but have to do until someone comes up with something better. Try creating separate config and add `gl_size_query = viewport` and `gl_dont_flip = 1`

**Comment by Miepee** [comment]
Used commit `4ee9dcd`, but can confirm it works, as long as the parameters are provided.
Should I close the issue, or wait for a "proper" fix?

**Comment by Miepee** [comment]
After a bit more testing, it turns out that Mangohud causes some pretty heavy freezing.
Trying to start Smash Bros. Ultimate, or retrying time trials causes every application to freeze, I have to switch to a TTY and kill Ryujinx in order for everything to become normal again.
This *only* happens when I use Mangohud.

**Comment by jackun** [comment]
> pretty heavy freezing.

Ok, saw that too but suddenly hasn't hanged yet.
Anyway another hacky way for vsync flicker is to just store current framebuffer index, flip to default 0 and then back. (the frametime line doe...)
![image](https://user-images.githubusercontent.com/4328738/113068189-75276400-91c6-11eb-9e71-9ef10e50f94a.png)

**Comment by cow-killer** [comment]
Sorry to bump this...but what's the step-by-step process of fixing this?

**Comment by jackun** [comment]
Build and install `develop` branch, add `gl_bind_framebuffer=0` to config file. Iirc was enough.

**Comment by cow-killer** [comment]
@jackun I can confirm this works, thanks. I'm only getting the standard set of stats with MangoHUD, unlike the setup I have made with goverlay. Is it possible to customize the stats?

**Comment by jackun** [comment]
`cat MangoHud.conf >> Ryujinx.conf` ;)

Closing as "fixed for now".
`gl_bind_framebuffer = 0` could actually be done by default maybe...

**Comment by jduncanator** [comment]
What's the expected state the GL context is left in for MangoHud to "just work"? Ryujinx does many non-standard things you wouldn't usually see in a game, however if we can leave the GL context in a slightly more standard configuration that would make MangoHud work out of the box, I'd like to investigate what we can do to make that happen.

**Comment by jackun** [comment]
I think it's probably good enough right now, just need to enable checking/setting current frame buffer (glBindFramebuffer) by default. 
But suggestions are welcome.

**Comment by cow-killer** [comment]
MangoHUD actually works just fine using the [Vulkan build](https://github.com/Ryujinx/Ryujinx/pull/2518), just saying.

**Comment by Essasetic** [comment]
Update on this issue.

This PR fixes the issue entirely on OpenGL. [https://github.com/Ryujinx/Ryujinx/pull/3217](url)

Should be merged to master very soon.
