### ISSUE TITLE
MangoHud "Crashes" Lutris

### ISSUE THREAD

**Issue by supernova874** [flightlessmango/MangoHud#489]
I can't do anything in Lutris if i have the MangoHud installed , when i uninstall it then works without any issue , my System is Garuda Kde 5.21 with 5.10 zen kernel , also i have tried all other versions that provided through Pamac but most have the same effect and one of them crashes the wiine itself it worked without any issue before the latest update to 5.21

**Comment by flightlessmango** [comment]
try adding `NODEVICE_SELECT=1`

**Comment by supernova874** [comment]
Where do i add this?

**Comment by supernova874** [comment]
ok i created a custom shortcut with "NODEVICE SELECT=1 mangohud lutris %d" and it is working for the time been

thanks , anyway to add this directly to some lutris config file so it will work without my shortcut?

**Comment by gort818** [comment]
add it to the environmental variables section in Lutris

**Comment by supernova874** [comment]
As i said i created a shortcut on my desktop with "NODEVICE_SELECT=1 mangohud lutris %U" and now it works but if i can do that without the shortcut is a plus. Where is that environmental variables section ?

**Comment by supernova874** [comment]
My problem isn't with a game the lutris as a program halts and crashes with MangoHud installed , when i inserted the NODEVICE_SELECT=1 to a new shortcut running Lutris it worked but how can insert this parameter without the need of a shortcut?

**Comment by gort818** [comment]
Open Lutris, find your game and right click and chose configure, chose system options, scroll down to Environmental variables, and for key put `NODEVICE SELECT` and for value put `1`

**Comment by gort818** [comment]
why are you running `mangohud lutris ` ?

**Comment by supernova874** [comment]
if i dont give that command to the shortcut the lutris halts . Not crashing just can't click anywhere need to forced stop the app
