### ISSUE TITLE
Add Configuration Option for Changing HUD Text/Frametime Graph Color

### ISSUE THREAD

**Issue by durcor** [flightlessmango/MangoHud#49]
The ability to change the color of text objects and the frametime graph in the HUD via the config file would be nice.

**Comment by flightlessmango** [comment]
this is now implemented in the develop branch, it will be in the next release.

you can try it right now with this package [MangoHud-latest](https://flightlessmango.com/MangoHud-latest.tar.gz)

Installation now requires sudo, `sudo ./mangohud-setup.sh install`
