### ISSUE TITLE
MangoHUD showing higher CPU clock

### ISSUE THREAD

**Issue by TheHooly** [flightlessmango/MangoHud#491]
Both the regular release and the git-version report a higher CPU clock than expected, in my case it shows up to 5.2GHz while htop reports 4.7GHz at max.

OS: Arch Linux (linux-tkg-pds-zen2-5.11.1-127)
CPU: Ryzen 7 5800X (not OC)
GPU: RX 5700XT
RAM: 16GB DDR4-4000

It seems to be unrelated to the specific game, so far I've tested BF4 and Satisfactory, I will edit this post in the case that this does not occur on a different game.

**Comment by flgx16** [comment]
That's a bug with linux 5.11 afaik

**Comment by TheHooly** [comment]
But why does htop show the presumably correct clock, then?
Do they use a different method to read the clock rate?

**Comment by flgx16** [comment]
MangoHud uses `/proc/cpuinfo`, you can check what it outputs by: `cat /proc/cpuinfo | grep MHz`

**Comment by TheHooly** [comment]
That reports 5.7 GHz on three cores, jesus

Okay, closing this, because not a bug in MangoHUD.

**Comment by Leopard1907** [comment]
https://www.phoronix.com/scan.php?page=news_item&px=Linux-5.10.20-Fixes-Freq-Report
