### ISSUE TITLE
GPU stats (nvidia) not displaying in a game that's running via Proton...

### ISSUE THREAD

**Issue by bk201doesntexist** [flightlessmango/MangoHud#492]
...but they do display in a vulkan Linux native title. Arch Linux, linux-zen (5.11.2.zen1-1), Nvidia 1070 ti, 460.56, Steam (beta client), MangoHud 0.6.1

The games I tested this with were No Man's Sky (Proton 5.0-10), and Valheim (edit: and with AI War II as well). If further information or testing is required, please let me know, I'll try to assist the best I can.

Using Steam launch command:
Valheim: `ENABLE_VKBASALT=1 VKBASALT_CONFIG_FILE=/home/bk201/.config/vkBasalt/vkBasalt.valheim.conf mangohud %command%`
AI War II: `ENABLE_VKBASALT=1 VKBASALT_CONFIG_FILE=/home/bk201/.config/vkBasalt/vkBasalt.aiwar.conf mangohud %command%`
No Man's Sky: `ENABLE_VKBASALT=1 VKBASALT_CONFIG_FILE=/home/bk201/.config/vkBasalt/vkBasalt.conf mangohud %command%`

I have also tried with `MANGOHUD=1` and without vkBasalt.

$HOME/.config/MangoHud/MangoHud.conf (i tried adding pci_dev after the first test, but didn't produce different results; also, the HUD opacitiy is different in one of the screenshots because i changed the value between them, no worries there :))
```
pci_dev = 00000000:01:00.0
cpu_stats
cpu_temp
cpu_mhz
cpu_color=2e97cb
cpu_text=CPU
gpu_stats
gpu_temp
gpu_core_clock
gpu_mem_clock
gpu_power
gpu_color=2e9762
gpu_text=GPU
vram
vram_color=ad64c1
ram
ram_color=c26693
io_color=a491d3
frame_timing=0
frametime_color=00ff00
time
engine_version
wine_color=eb5b5b
engine_color=eb5b5b
media_player_color=ffffff
background_alpha=0.5
font_size=24
background_color=282828
position=bottom-right
text_color=ffffff
toggle_hud=Shift_R+F12
toggle_logging=Shift_L+F2
output_folder=/home/bk201/.logs/
```

![20210302140235_1](https://user-images.githubusercontent.com/793358/109661445-e50fe380-7b61-11eb-921f-d93e0a71d2e3.jpg)
![20210302143036_1](https://user-images.githubusercontent.com/793358/109663573-2dc89c00-7b64-11eb-848f-7ccb7bf06670.jpg)
![20210228160659_1](https://user-images.githubusercontent.com/793358/109661449-e6411080-7b61-11eb-99a4-ef7548e11f46.jpg)

Thanks in advance!

**Comment by bk201doesntexist** [comment]
I'm terribly sorry, I apologize for not having replied to the other issue already open.

**Comment by flightlessmango** [comment]
Can you check if a proton version before 5.13 makes it work?

**Comment by bk201doesntexist** [comment]
I'm already running 5.0-10; only thing I changed on it was changing the windows version of the proton prefix to windows 7 (it defaults to windows 10 on 5.0+ valve builds, including experimental - and this breaks multiplayer)
No Man's Sky 3.2 had this patch note in it: "Fixed an issue that could cause players using Windows 10 to incorrectly report a network disconnect." - I'm not sure if proton 5.0+ prefixes being set to windows 10 by default could benefit from this patch, i have not tested it yet.
Should I test with 4.11-13?

**Comment by bk201doesntexist** [comment]
![20210312165717_1](https://user-images.githubusercontent.com/793358/111031584-2fb21b00-8400-11eb-8a99-7a89f515e558.jpg)
Some more feedback: I've tested Path of Exile recently with Proton Experimental, and MangoHud was able to display gpu stats.

**Comment by bk201doesntexist** [comment]
Testing with Proton Experimental branch seems to work for No Man's Sky as well:
![nms_mangohud](https://user-images.githubusercontent.com/793358/112874747-3789e480-90bb-11eb-86bb-1e46f88f25fa.jpg)

**Comment by zagor** [comment]
I can confirm the same issue.

Game: Squad
Proton: 5.13-6 and experimental give the same result.
GPU: Nvidia GTX 1660 Super
Linux kernel 5.9.0

![squad-mango](https://user-images.githubusercontent.com/229360/130256287-20c7f00b-a3c2-439f-aa5c-5809c81f982c.jpg)

Let me know if there is any more information I can provide.

**Comment by Cavernosa** [comment]
I had the same issue with Hollow Knight in Proton 5.13-6, Proton 6.3-7 and Proton Experimental. Former proton versions work fine.  
vkcube works fine too

GPU: Nvidia GT 710
Kernel: 5.14.10-artix1-1

**Comment by Cavernosa** [comment]
> Can you also add `PROTON_LOG=1` and post the log file from home dir then.

Proton 6.3-7: [steam-367520.log](https://github.com/flightlessmango/MangoHud/files/7445010/steam-367520.log)
[pastebin](https://bin.snopyta.org/?458d6b4b8085b7a1#99BQW5zeaUKRpNovcLk7A1Eq9tGWEyksLoo6P875bg6Q)

Proton 5.13-6b: [steam-367520.log](https://github.com/flightlessmango/MangoHud/files/7445066/steam-367520.log)
[pastebin](https://bin.snopyta.org/?ccab7fc7b572d64f#4kRHbXMrLcnBYegwxsky8pmGprKtuUMcvVFhsRo7toVm)

Proton 5.0-10b (mangohud works fine): [steam-367520.log](https://github.com/flightlessmango/MangoHud/files/7445046/steam-367520.log)
[pastebin](https://bin.snopyta.org/?62d0e765d09746de#83tbUhxrskqwJZ6b1Po4byyUMLs2pSmwqyJbDSDPwN83)

It looks to be failing to load libxnvctrl
```
[2021-10-29 18:52:58.509] [MANGOHUD] [error] [loader_nvctrl.cpp:39] Failed to open 64bit libXNVCtrl.so.0: libXNVCtrl.so.0: cannot open shared object file: No such file or directory
[2021-10-29 18:52:58.509] [MANGOHUD] [error] [nvctrl.cpp:45] XNVCtrl loader failed to load
```

**Comment by redemption-forever** [comment]
i got same problem with no GPU info on steam proton newer than 5.0-10.
Tested on gtx 670, gtx 960 and gtx 1060 on 3 diffrent computers. Manjaro kernel 5.13, kernel 5.15 and Linux mint 20.2.
had no problem on lutris battle.net starcraft and diablo.
How to fix it on newer proton versions? on proton 5.0-10 i see GPU info

**Comment by Kopetan4egX** [comment]
Same problem. Proton 5.0-10 works fine, anything newer - no gpu info. Debian testing, kernel 5.15, gt1030, nvidia driver 470.94

**Comment by cpw** [comment]
I'm getting the "libXNVCtrl.so.0" error identified above. I have both 32 and 64 bit versions of libxnvctrl0 and libnvidia-ml1 installed on the machine. Is it possibly something to do with the steam soldier runtime?

I am using the nvidia 495.46 version of the driver, from debian's experimental repository, and the proton-7.1 proton version from glorious eggroll.

From the proton log. I can't find the output of MANGOHUD_DLSYM=1 anywhere.

```
fgrep -i mangohud steam-1366540.log 
skipping config: /home/cpw/.config/MangoHud/wine-explorer.conf [ not found ]
skipping config: /home/cpw/.steam/compatibilitytools.d/Proton-7.1-GE-2/files/bin/MangoHud.conf [ not found ]
skipping config: /home/cpw/.config/MangoHud/wine64-preloader.conf [ not found ]
parsing config: /home/cpw/.config/MangoHud/MangoHud.conf [ ok ]
skipping config: /home/cpw/.config/MangoHud/wine-explorer.conf [ not found ]
skipping config: /home/cpw/.steam/compatibilitytools.d/Proton-7.1-GE-2/files/bin/MangoHud.conf [ not found ]
skipping config: /home/cpw/.config/MangoHud/wine64-preloader.conf [ not found ]
parsing config: /home/cpw/.config/MangoHud/MangoHud.conf [ ok ]
ERROR: ld.so: object '/tmp/pressure-vessel-libs-7DG3G1/${PLATFORM}/libMangoHud_dlsym.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/tmp/pressure-vessel-libs-7DG3G1/${PLATFORM}/libMangoHud.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
skipping config: /home/cpw/.config/MangoHud/wine-DSPGAME.conf [ not found ]
skipping config: /home/cpw/.steam/compatibilitytools.d/Proton-7.1-GE-2/files/bin/MangoHud.conf [ not found ]
skipping config: /home/cpw/.config/MangoHud/wine64-preloader.conf [ not found ]
parsing config: /home/cpw/.config/MangoHud/MangoHud.conf [ ok ]
skipping config: /home/cpw/.config/MangoHud/wine-DSPGAME.conf [ not found ]
skipping config: /home/cpw/.steam/compatibilitytools.d/Proton-7.1-GE-2/files/bin/MangoHud.conf [ not found ]
skipping config: /home/cpw/.config/MangoHud/wine64-preloader.conf [ not found ]
parsing config: /home/cpw/.config/MangoHud/MangoHud.conf [ ok ]
skipping config: /home/cpw/.config/MangoHud/wine-DSPGAME.conf [ not found ]
skipping config: /home/cpw/.steam/compatibilitytools.d/Proton-7.1-GE-2/files/bin/MangoHud.conf [ not found ]
skipping config: /home/cpw/.config/MangoHud/wine64-preloader.conf [ not found ]
parsing config: /home/cpw/.config/MangoHud/MangoHud.conf [ ok ]
skipping config: /home/cpw/.config/MangoHud/wine-DSPGAME.conf [ not found ]
skipping config: /home/cpw/.steam/compatibilitytools.d/Proton-7.1-GE-2/files/bin/MangoHud.conf [ not found ]
skipping config: /home/cpw/.config/MangoHud/wine64-preloader.conf [ not found ]
parsing config: /home/cpw/.config/MangoHud/MangoHud.conf [ ok ]
MANGOHUD: recreating font image
MANGOHUD: Failed to open 64bit libXNVCtrl.so.0: libXNVCtrl.so.0: cannot open shared object file: No such file or directory
MANGOHUD: XNVCtrl loader failed to load
MANGOHUD: Uploading is disabled (permit_upload = 0)
MANGOHUD: recreating font image
MANGOHUD: XNVCtrl loader failed to load
MANGOHUD: Uploading is disabled (permit_upload = 0)
MANGOHUD: recreating font image
MANGOHUD: XNVCtrl loader failed to load
MANGOHUD: Uploading is disabled (permit_upload = 0)
MANGOHUD: recreating font image
MANGOHUD: XNVCtrl loader failed to load
MANGOHUD: Uploading is disabled (permit_upload = 0)
MANGOHUD: recreating font image
MANGOHUD: XNVCtrl loader failed to load
MANGOHUD: Uploading is disabled (permit_upload = 0)
MANGOHUD: recreating font image
MANGOHUD: XNVCtrl loader failed to load
MANGOHUD: Uploading is disabled (permit_upload = 0)
MANGOHUD: recreating font image
MANGOHUD: XNVCtrl loader failed to load
MANGOHUD: Uploading is disabled (permit_upload = 0)
MANGOHUD: recreating font image
MANGOHUD: XNVCtrl loader failed to load
MANGOHUD: Uploading is disabled (permit_upload = 0)
MANGOHUD: recreating font image
MANGOHUD: XNVCtrl loader failed to load
MANGOHUD: Uploading is disabled (permit_upload = 0)
```

**Comment by hitanol** [comment]
happening 2 me 2, the exact same problem.
```
# MANGOHUD: Failed to open 32bit libXNVCtrl.so.0: libXNVCtrl.so.0: no se puede abrir el fichero del objeto compartido: No existe el fichero o el directorio
# MANGOHUD: XNVCtrl loader failed to load
```

**Comment by flightlessmango** [comment]
xnvctrl is not yet included in the solider runtime, will make an issue later to address this.
This means that if nvml does not support your GPU then we're currently unable to get the information in proton.
It would be helpful if you guys can use this command to check if your GPU is supported: `nvidia-smi --format=csv,noheader --query-gpu=utilization.gpu`

**Comment by hitanol** [comment]
```
[mi@mi ~]$ nvidia-smi --format=csv,noheader --query-gpu=utilization.gpu
[N/A]

```

**Comment by flightlessmango** [comment]
@hitanol what gpu do you have?

**Comment by Kopetan4egX** [comment]
ASUS GT1030 (GT1030-2G-BRK)
nvidia-smi --format=csv,noheader --query-gpu=utilization.gpu
9 %

**Comment by hitanol** [comment]
NVIDIA GeForce GT 730 (GK208)

**Comment by jarettmillard** [comment]
I had this same problem using the mangohud package from the Pop_OS repo. Adding the PPA and updating to that version fixed it for me.

**Comment by Kopetan4egX** [comment]
> I had this same problem using the mangohud package from the Pop_OS repo. Adding the PPA and updating to that version fixed it for me.

Which version exactly is "that"? 5.0-10? Or are there new ones not having problem,  discussed in this topic.

**Comment by jarettmillard** [comment]
> > I had this same problem using the mangohud package from the Pop_OS repo. Adding the PPA and updating to that version fixed it for me.
> 
> Which version exactly is "that"? 5.0-10? Or are there new ones not having problem, discussed in this topic.

I upgraded from `0.6.1-1` in the Ubuntu impish repo to `0.6.5-1ubuntu0~impish1.0` in the PPA recommended in the MangoHud README: https://launchpad.net/~flexiondotorg/+archive/ubuntu/mangohud

I suspect it's less an issue of versions and more related to this tidbit from that PPA link:
> I've modified the packaging to use the NVML enabled version of MangoHud.

**Comment by Kopetan4egX** [comment]
> > > I had this same problem using the mangohud package from the Pop_OS repo. Adding the PPA and updating to that version fixed it for me.
> > 
> > 
> > Which version exactly is "that"? 5.0-10? Or are there new ones not having problem, discussed in this topic.
> 
> I upgraded from `0.6.1-1` in the Ubuntu impish repo to `0.6.5-1ubuntu0~impish1.0` in the PPA recommended in the MangoHud README: https://launchpad.net/~flexiondotorg/+archive/ubuntu/mangohud
> 
> I suspect it's less an issue of versions and more related to this tidbit from that PPA link:
> 
> > I've modified the packaging to use the NVML enabled version of MangoHud.

Thanks
I have 0.6.5-2 and it doesn't work.
