### ISSUE TITLE
enhancement- Support Linux on ARM/ARM64

### ISSUE THREAD

**Issue by Askmewho** [flightlessmango/MangoHud#494]
Hi, just what the title says. Great work! thanks! 
maybe an rpi4 is a good start. the thing is we test x86 games most of the time being emulated like this...

https://www.youtube.com/watch?v=BEYt5wzckvY

cheers

**Comment by coffeecrisp** [comment]
Hmmmm. Why is there a link to a youtube video in your post?

**Comment by Askmewho** [comment]
to show you how we execute x86 games on ARM Linux.

**Comment by Askmewho** [comment]
@coffeecrisp  here I used this project to compare a cheap x86 SBC with ARM Linux boards on x86 software https://www.youtube.com/watch?v=3hHlwupCwFQ

**Comment by stephanlachnit** [comment]
You can simply compile it for arm. Debian has packages for arm: https://packages.debian.org/bullseye/mangohud

**Comment by Askmewho** [comment]
It worked!

**Comment by Askmewho** [comment]
Closing

**Comment by Askmewho** [comment]
video of mangohud on linux on ARM :) : https://www.youtube.com/watch?v=MkL2x2r3zcY
