### ISSUE TITLE
Failed to load NVML on 32bit apps

### ISSUE THREAD

**Issue by vesterlay** [flightlessmango/MangoHud#499]
The output of vkcube32 

https://pastebin.com/b7XqmVxe

OS: Deepin 20.01

**Comment by TheComputerGuy96** [comment]
You need to install one library for that, so do this:
`sudo dpkg --add-architecture i386 && sudo apt-get update && sudo apt-get install libnvidia-ml1:i386`

**Comment by vesterlay** [comment]
@TheComputerGuy96 Thanks it worked. Why it was not installed by default? Should this be?
