### ISSUE TITLE
MangoHud doesn't work on Kubuntu 19.10

### ISSUE THREAD

**Issue by ahmed-elsayed2017** [flightlessmango/MangoHud#5]
I installed MangoHud on Kubuntu 19.10, and I checked to see if it is installed successfully, and I found these files:
~/.local/share/MangoHud/libMangoHud.so
~/.local/share/vulkan/implicit_layer.d/mangohud32.json
~/.local/share/vulkan/implicit_layer.d/mangohud64.json

but I can't find the file `libMangoHud32.so`, I don't know if this is related to Ubuntu dropping the support for 32bit packages from Ubuntu starting from version 19.10, or not.

Anyway, trying to run any 64bit game with MANGOHUD=1 freeze the game during loading, and I had to kill the game, otherwise, it will load forever.

**Comment by ahmed-elsayed2017** [comment]
Here is a log file of the terminal output of Darksiders Genisis GOG before killing it
[Darksiders Genesis.log](https://github.com/flightlessmango/MangoHud/files/4145483/Darksiders.Genesis.log)

**Comment by telans** [comment]
The only reason I could imagine it not copying that file is if it didn't build. Does you notice any errors when it builds? Assuming you have `vulkan-tools` installed, could you please run `MANGOHUD=` vkcube`. Does the hud show?

**Comment by ahmed-elsayed2017** [comment]
Running `MANGOHUD=1 vkcube` end up with this error:
`Segmentation fault (core dumped)`

**Comment by flightlessmango** [comment]
What graphic card are you using?

**Comment by ahmed-elsayed2017** [comment]
> What graphic card are you using?

AMD Radeon HD 8750M

**Comment by flightlessmango** [comment]
are you sure it's the vkcube from vuklan-tools? because other versions are known to crash

**Comment by ahmed-elsayed2017** [comment]
vulkan-tools is installed from universe (Ubuntu), and there is other versions to install.

**Comment by jackun** [comment]
I don't think AMD Radeon HD 8750M has vulkan support if it uses `radeon` module.

**Comment by ahmed-elsayed2017** [comment]
> I don't think AMD Radeon HD 8750M has vulkan support if it uses `radeon` module.

No, it has Vulkan support, 

> I don't think AMD Radeon HD 8750M has vulkan support if it uses `radeon` module. It seems it's actually even GCN 1.0. Google how to enable `amdgpu.si_support` if you haven't already.

I already did that long time ago. Here is Life Is Strange 2 (native/vulkan) running on my my machine:

![Life Is Strange 2](https://user-images.githubusercontent.com/29783425/73617506-1d27b880-4628-11ea-963c-3ce5c8e2c570.png)

**Comment by jackun** [comment]
@ahmed-elsayed2017 try now.

**Comment by ahmed-elsayed2017** [comment]
> @ahmed-elsayed2017 try now.

I removed MangoHud, then build it again. It gives me this error messages, before the game crashes during loading:

```
ls: cannot access '/sys/class/drm/card0/device/hwmon/': No such file or directory
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
003b:fixme:seh:dwarf_get_ptr unsupported encoding 9b
003b:fixme:seh:dwarf_get_ptr unsupported encoding 48
003b:fixme:seh:dwarf_get_ptr unsupported encoding 08
003b:fixme:seh:dwarf_get_ptr unsupported encoding cd
003b:fixme:seh:dwarf_get_ptr unsupported encoding 9b
003b:fixme:seh:dwarf_get_ptr unsupported encoding 48
003b:fixme:seh:dwarf_get_ptr unsupported encoding 08
003b:fixme:seh:dwarf_get_ptr unsupported encoding cd
003b:fixme:seh:dwarf_get_ptr unsupported encoding 9b
003b:fixme:seh:dwarf_get_ptr unsupported encoding f0
003b:fixme:seh:dwarf_get_ptr unsupported encoding 79
wine: Assertion failed at address 00007F5C66D413EB (thread 003b), starting debugger...
Unhandled exception: assertion failed in 64-bit code (0x00007f5c66d413eb).
```

**Comment by flightlessmango** [comment]
Do you have libsensors installed?

**Comment by ahmed-elsayed2017** [comment]
> Do you have libsensors installed?
It is installed.

![Screenshot_20200203_033628](https://user-images.githubusercontent.com/29783425/73619542-7d255b80-4636-11ea-8487-ced82dbe4598.png)

**Comment by flightlessmango** [comment]
Put this file in $HOME/.local/share/MangoHud and see if that fixes it
https://flightlessmango.com/libMangoHud.so

**Comment by ahmed-elsayed2017** [comment]
> Put this file in $HOME/.local/share/MangoHud and see if that fixes it
> https://flightlessmango.com/libMangoHud.so

It gives me now a different kind of error messages:

```
dbus[13906]: arguments to dbus_message_new_method_call() were incorrect, assertion "_dbus_check_is_valid_path (path)" failed in file ../../../dbus/dbus-message.c line 1366.
This is normally a bug in some application using the D-Bus library.

  D-Bus not built with -rdynamic so unable to print a backtrace
003b:fixme:seh:dwarf_get_ptr unsupported encoding 9b
003b:fixme:seh:dwarf_get_ptr unsupported encoding fe
003b:fixme:seh:dwarf_get_ptr unsupported encoding 0e
003b:fixme:seh:dwarf_get_ptr unsupported encoding bd
wine: Assertion failed at address 00007F22D59603EB (thread 003b), starting debugger...
Unhandled exception: assertion failed in 64-bit code (0x00007f22d59603eb).
```

**Comment by flightlessmango** [comment]
oh, I made a mistake. Download it again

**Comment by ahmed-elsayed2017** [comment]
> oh, I made a mistake. Download it again

I saw MangoHud working this time for 2 seconds, and it crashed again with a different kind of messages

```
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoi
003b:err:seh:segv_handler Got unexpected trap 0
Segmentation fault      (core dumped)
```

**Comment by flightlessmango** [comment]
Small sign of progress! try once more please

**Comment by ahmed-elsayed2017** [comment]
It worked for 2 seconds, and gave me the same error.

**Comment by flightlessmango** [comment]
Try again please

**Comment by ahmed-elsayed2017** [comment]
> Try again please

I tried with different games to see if there any difference from this game, and I get this error message:
```
vulkan: No DRI3 support detected - required for presentation
Note: you can probably enable DRI3 in your Xorg config
err:   Failed to create surface
```

**Comment by flightlessmango** [comment]
I believe you need to do what it says, enable DRI3 in your Xorg config
here is a link to the arch wiki on how to do that
https://wiki.archlinux.org/index.php/Vulkan#Error_-_vulkan:_No_DRI3_support

**Comment by ahmed-elsayed2017** [comment]
> I believe you need to do what it says, enable DRI3 in your Xorg config
> here is a link to the arch wiki on how to do that
> https://wiki.archlinux.org/index.php/Vulkan#Error_-_vulkan:_No_DRI3_support

I couldn't boot to my machine at all after doing that. I had to remove it again.

I can't even run any game now with, or without MangoHud. I guess amdgpu module is turned off, or the latest mesa update caused this issue.

**Comment by flightlessmango** [comment]
are you using your intel igpu for anything, if not can you turn it off in the bios? that might help

**Comment by ahmed-elsayed2017** [comment]
> are you using your intel igpu for anything, if not can you turn it off in the bios? that might help

I can turn off dGPU from the bios if I want, but I can't turn off iGPU.

**Comment by flightlessmango** [comment]
Could you join our discord? I think this might be easier over chat

**Comment by ahmed-elsayed2017** [comment]
> Could you join our discord? I think this might be easier over chat

I am sorry, I was trying something. How can I join?

**Comment by flightlessmango** [comment]
https://discordapp.com/invite/Gj5YmBb

**Comment by ahmed-elsayed2017** [comment]
This issue is fixed.
