### ISSUE TITLE
[BUG] "Wolfenstein II" application crash using "MANGOHUD=1"

### ISSUE THREAD

**Issue by mimattr** [flightlessmango/MangoHud#50]
Unfortunately the `MANGOHUD=1 %command%` launch option within Steam results in an application crash using **Wolfenstein II: The New Colossus**:

![Screenshot](https://i.imgur.com/GwRMI2x.png)

[steam-612880.log](https://github.com/ValveSoftware/Proton/files/4241073/steam-612880.log)

## System Information
- GPU: **RTX 2060**
- Driver/LLVM version: **NVIDIA 440.59**
- Kernel version: **5.3.0-40-generic**
- [Link to full system information report as Gist](https://gist.github.com/mimattr/b0b7f46366e31e254460b9593ce87e51)
- Proton version: **5.0-3**

As an aside **No Man's Sky** appears to work as expected with the same MangoHud configuration.

**Comment by flightlessmango** [comment]
I don't own the game so I can't try it myself, but there has been quite a few bugfixes since this issue was posted.

[MangoHud-latest](https://flightlessmango.com/MangoHud-latest.tar.gz)
this package is based on the develop branch, could you check if the problem still persist with this build?

**Comment by mimattr** [comment]
> there has been quite a few bugfixes since this issue was posted.
> could you check if the problem still persist with this build?

@flightlessmango The **Wolfenstein II** issue appears to be resolved with your [MangoHud-latest](https://flightlessmango.com/MangoHud-latest.tar.gz) build, many thanks.

As an aside will future **MangoHud** releases also require installation within the `/usr` system directory rather than `~/.local`?

**Comment by flightlessmango** [comment]
Yes it will, it's because opengl is being implemented. This was you will be able to type `mangohud` and be able to load both opengl and vulkan, if you downloaded the mangohud-latest package recently you can probably try out opengl right `mangohud glxgears`
