### ISSUE TITLE
how to get for windows? 

### ISSUE THREAD

**Issue by RevertedClock** [flightlessmango/MangoHud#501]
Making a new issue here because #222 is deleted. 
Conversation from #222
http://web.archive.org/web/20200916075852/https://github.com/flightlessmango/MangoHud/issues/222

**Comment by flightlessmango** [comment]
### The current status of MangoHud on windows
- It compiles with mingw or msvc
- It can hook dx11/12, opengl and vulkan
- GPU usage on NVIDIA and AMD
- CPU usage
- FPS + Frametime

The overlay is only implemented in the vulkan hook.
It's basically the bare minimum for logging and not much more

**Comment by Nyanekoy** [comment]
Is there any update on this? :/

**Comment by shikulja** [comment]
I would like to have an experimental option for windows, I hope there will be an assembly

**Comment by itsTyrion** [comment]
why not use MSI Afterburner and RTSS?

**Comment by kisoqual** [comment]
@itsTyrion because they not working properly in OBS

**Comment by itsTyrion** [comment]
> @itsTyrion because they not working properly in OBS

Works for me. Can you elaborate?

**Comment by kisoqual** [comment]
@itsTyrion nvm i just forgot to update the RTSS, so they working fine

**Comment by ayamasasaki** [comment]
im curios if i can change the steam fps counter to this like on arch linux steamdeck ui gamepad overlay fps

**Comment by flightlessmango** [comment]
> im curios if i can change the steam fps counter to this like on arch linux steamdeck ui gamepad overlay fps

It's not possible as it relies on gamescope, which is not available on windows

**Comment by theofficialgman** [comment]
What is the current status of this?
Any improvements to implementing the overlay on opengl and dx11/dx12?

**Comment by flightlessmango** [comment]
> What is the current status of this?

There are currently no plans to continue developing on the windows end

**Comment by ayamasasaki** [comment]
> > What is the current status of this?
> 
> There are currently no plans to continue developing on the windows end

That's a shame because it's more better than MSI Afterburner

**Comment by Skellybob56** [comment]
> > > What is the current status of this?
> > 
> > 
> > There are currently no plans to continue developing on the windows end
> 
> That's a shame because it's more better than MSI Afterburner

Agreed, never been able to get MSI Afterburner and RTSS working at all.

**Comment by Mario156090** [comment]
Sorry to hear this. :(

> > What is the current status of this?
> 
> There are currently no plans to continue developing on the windows end

**Comment by XhstormR** [comment]
+1 for windows
