### ISSUE TITLE
Lutris MangoHud wont show GPU Stats in HUD configured with Goverlay

### ISSUE THREAD

**Issue by Draguljche** [flightlessmango/MangoHud#505]
Hello, can someone help me with this issue, onlu GPU stats wont show mangohud? 

My GPU is Nvidia GTX1080 with non-free driver. Im on Debian Sid.

**Comment by vesterlay** [comment]
Is that by any means duplicate of #499, try to run `sudo dpkg --add-architecture i386 && sudo apt-get update && sudo apt-get install libnvidia-ml1:i386 libnvidia-ml1`

**Comment by Draguljche** [comment]
> Is that by any means duplicate of #499, try to run `sudo dpkg --add-architecture i386 && sudo apt-get update && sudo apt-get install libnvidia-ml1:i386 libnvidia-ml1`

Well big THANK YOU. it worked perfectly well.
