### ISSUE TITLE
Is mango hud's frame time math accurate? 

### ISSUE THREAD

**Issue by BuyMyMojo** [flightlessmango/MangoHud#506]
example:

fps | frametime
------------ | -------------
175.839 | 5185

how does 175.839/60 equal 5185(Microsecond?/5.185ms) at all and not 2.93065ms?

the first 60 fps of my test file:

fps | frametime
-- | --
175.839 | 5185
175.253 | 6322
177.03 | 6289
175.855 | 5595
172.04 | 6489
175.161 | 5410
176.187 | 5214
192.349 | 5216
196.313 | 4597
190.876 | 4869
192.375 | 6237
193.024 | 5051
190.728 | 5473
195.36 | 5063
195.88 | 5085
196.111 | 4857
195.991 | 4871
197.489 | 4972
177.469 | 7565
167.267 | 7404
163.766 | 7404
161.241 | 7420
148.142 | 7471
147.831 | 7319
147.857 | 5998
149.086 | 7113
149.197 | 8087
133.585 | 7794
144.569 | 8912
149.342 | 7113
150.171 | 7522
148.998 | 6822
150.602 | 6220
146.002 | 7303
150.428 | 5978
151.87 | 7192
151.555 | 6946
156.463 | 6017
158.257 | 5541
157.745 | 7314
158.121 | 6828
159.497 | 5353
167.38 | 6845
167.703 | 7554
167.321 | 5820
167.571 | 5479
166.988 | 5866
175.543 | 5221
172.691 | 5174
171.541 | 5182
166.399 | 9173
165.307 | 5405
168.505 | 5429
167.364 | 5579
167.427 | 5583
168.109 | 5552
168.671 | 5542

Averaging those microsecond values equals 160.64fps average which makes sense?

**Comment by flightlessmango** [comment]
First of all frametime is (1000 / fps = frametime)
But that still doesn't explain why fps and frametimes don't match up.
It's because frametime is the actual time since the last frame, but fps is the average fps since the last update interval

**Comment by BuyMyMojo** [comment]
you're right I got the math confused sorry about that.
And that makes sense, apologies for taking up your time
