### ISSUE TITLE
Whole PC hangs when MANGOHUD_CONFIG=full is used

### ISSUE THREAD

**Issue by Shished** [flightlessmango/MangoHud#51]
CPU: AMD Ryzen 5 2600
GPU: Nvidia GTX 1060 (440.59 driver)
OS: Arch
DE: Gnome 3.34.4/Xorg

So when a native or DXVK game is launched with `MANGOHUD=1 MANGOHUD_CONFIG=full` env variables, whole PC hangs - black screen, background audio stops, no reaction on pressing the  num/caps lock key. Only reset helps.
When `MANGOHUD_CONFIG` is set to `cpu_temp,gpu_temp,core_load,ram,vram` which is, supposedly, the same as `full`, this problem does not appears.

![20200225193234_1](https://user-images.githubusercontent.com/3143668/75272304-4b9f4a80-5806-11ea-9cf7-d05a0d180067.jpg)

**Comment by flightlessmango** [comment]
try using `MANGOHUD_CONFIG=full,gpu_timing=0`

**Comment by Shished** [comment]
This problem does not appears when `MANGOHUD_CONFIG=full,gpu_timing=0` is used.

**Comment by flightlessmango** [comment]
I think this has been resolved in master, you could try installing mangohud-git from the AUR and see if that still crashes with just `full`

**Comment by Shished** [comment]
Build from git does not causes crashes.
