### ISSUE TITLE
X4: Foundations hangs on startup with ManguHud

### ISSUE THREAD

**Issue by maritz** [flightlessmango/MangoHud#511]
Game: X4: Foundations (GOG version, patch 4.00 Hotfix 2 433914)
MangoHud 0.6.1-2 (from AUR)
Distribution: Manjaro
Kernel: 5.11.6-1-MANJARO

What happens:
Start the game via `mangohud ./X4` and it opens a window (X4 window title bar is visible, task bar disappears) and then immediately hangs, still kinda showing my Desktop but obviously with a window overlayed.

Starting the game by itself without MangoHud works and MangoHud works on other games on this system.

Tried starting it with `MANGOHUD=1` and tried `NODEVICE_SELECT=1` - neither fixed it.

flightlessmango was able to show me that the steam version works for them, so either there is some difference in the versions or maybe my system needs some change/fix.

I'd be happy to supply additional information, if I can.

**Comment by jkhsjdhjs** [comment]
I have a seemingly similar issue with Elder Scrolls Online, started via Lutris. It worked fine a few weeks ago, maybe this is because of the latest update of Elder Scrolls Online.

The Elder Scrolls Online Online window will appear, but completely transparent showing my desktop.

**Comment by SirBubbles** [comment]
Same issue. After a major Manjaro update, MangoHud is causing EVERY steam game to crash. Just steam. Everything outside of steam seems to work fine, but steam usage causes the game to crash when trying to start. Disabling or removing MangoHud resolves this. Please to fix, or I might have to find a better behaved alternative, and those are few and far between!

**Comment by flightlessmango** [comment]
@jkhsjdhjs @SirBubbles Neither of these sounds related to this issue. Please create new issues and supply information about your setups

**Comment by maritz** [comment]
Update as of 6.3.1: If I start it without any parameters, it does something slightly different. When I tab out from the bugged window to the terminal where I started the game from, the game window then shows completely black in the background and has the overlay (static) displayed. It still hangs then, but it seems like progress.

![image](https://user-images.githubusercontent.com/159633/121771768-ba2a2800-cb71-11eb-8a2c-f4e5856c2b00.png)

I've tried adding a few parameters and stuff to see what happens. When I add "full" it goes back to the old behavior where it doesn't even get to this stage of a black screen.  
When I compare how much CPU time the process has taken for each of those start methods (with full and without) the one where it gets to the black screen (without full) also uses a lot more (22s instead of ~1s) and spawns a lot more sub processes before not doing anything anymore. This leads me to believe it gets further in the startup process before it hangs.

**Comment by maritz** [comment]
Some more up2date information about my system:

Kernel: 5.12.8-1-MANJARO
GPU driver: 465.31 (the nvidia-dkms-performance package from AUR)
GPU: GTX 1070

Anything else I can provide or try? I know it's next to impossible for you to debug my problem, but maybe there's something I can try?

**Comment by maritz** [comment]
Small update: v0.6.4 didn't change anything afaict.

**Comment by maritz** [comment]
I haven't tested in a while, so I don't know what change made it work, but it now does! :partying_face: 

```
mangohud: 0.6.6-1
Kernel: 5.15.12-1-MANJARO
GPU driver: beta 510.39.01-1
X4: 4.20
```
