### ISSUE TITLE
MangoHUD fails to log Wine applications

### ISSUE THREAD

**Issue by oyvindsaether** [flightlessmango/MangoHud#515]
1) have MangoHUD
2) start some thing in Wine
3) start log
4) end log

there will be a on-screen message,  but there's no log showing up in the .config/MangoHud/MangoHud.conf  output_folder= folder. 

I hadn't tried logging with MangoHUD before I tried starting with Wine programs so I was about to write it off as broken trash when I give it one last shot with vkcube and it did log just fine. 

I am guessing it has to do with the way MangoHUD tries to name logs after the application executable. I manages to log Native Linux applications, but it fails to produce a log file for anything I run in Wine.

**Comment by flightlessmango** [comment]
Are you using an absolute path for `output_folder`?

**Comment by oyvindsaether** [comment]
Yes. It's an absolute path. And it works with everything other than Wine.

**Comment by flightlessmango** [comment]
With wine, are you talking about Proton in this case? Proton's solider runtime restricts access to most things outside of `~/`. Could that be part of the issue?

**Comment by oyvindsaether** [comment]
I don't have a proton. I use Wine 6.6 from WineHQ with the DXVK 1.8.1 from GitHub.

**Comment by gort818** [comment]
What is your `output_folder` set to?  I just tested on my end and no issues with wine applications

**Comment by oyvindsaether** [comment]
I don't know what to make of this bug after some further testing.

No longs are produced when I run fr-041_debris.exe and a few other in Wine.

Logs are produced when I run Asahi_by_Futuris.exe and a few others in Wine.

It doesn't make a difference if I set output_folder=/home/oyvinds/temp/MangoHudLogs/ or output_folder=/home/oyvinds/ or any other folder.

I'm open to any suggestions as to ways to figure out what goes wrong in a few Wine applications but not others on my box. I could try a git tree with some patch that spews out debug information to the console or a log if something like that exists (or could exist if it is easy).

What Wine applications MangoHud decides to save logs for and what it's content with showing a on-screen message about logging for seems a bit random, except that it's consistent (Running Asahi_by_Futuris.exe saves logs every time, running fr-041_debris.exe never produces a log).

It would perhaps help to know if MangoHud saves logs for  http://www.farbrausch.de/prod.py?which=2  on other machines or not; perhaps it's just mine or perhaps it's application-specific.

**Comment by jackun** [comment]
Works for me. Try building debug build with `./build.sh clean build --buildtype=debug install` and check what it writes to terminal when finishing recording. Should be something like `Writing log file [/home/jackun/mangohud//fr-041_debris_2021-04-19_20-30-26.csv], 44 entries`
