### ISSUE TITLE
./build.sh  install doesn't install

### ISSUE THREAD

**Issue by oyvindsaether** [flightlessmango/MangoHud#516]
1) use git. compile it. try to install
2) fail

```./build.sh  install``` produces
```
'./build/release/usr/lib/mangohud/lib32/libMangoHud.so' -> '/usr/lib/mangohud/lib32/libMangoHud.so'
/usr/bin/install: creating directory '/usr/lib/mangohud/lib'
/usr/bin/install: cannot stat './build/release/usr/lib/mangohud/lib/libMangoHud.so': No such file or directory
```
Building gives me a ./build/release/usr/lib/mangohud/lib64/libMangoHud.so and a ./build/release/usr/lib/mangohud/lib64/libMangoHud_dlsym.so 

These lines will obviously fail to install the libraries since they aren't there:

https://github.com/flightlessmango/MangoHud/blob/2afc03cc0362a8ea1f3aa5d3ec05907fb96900c2/build.sh#L207 and https://github.com/flightlessmango/MangoHud/blob/2afc03cc0362a8ea1f3aa5d3ec05907fb96900c2/build.sh#L209

Those lines should ask for /build/release/usr/lib/mangohud/lib64/ instead of /build/release/usr/lib/mangohud/lib/

How, concretely, any libraries installed into /usr/lib/mangohud/lib32/ and /usr/lib/mangohud/lib/ are supposed to be found without installing anything adding those paths to say /etc/ld.so.conf.d/mangohud.conf is another obvious question. That's a specially good question since Mangohud installs one, not two, files in /usr/share/vulkan/implicit_layer.d/MangoHud.json (it should be one for 32 and one for 64) and that file reads

```
      "library_path": "/usr/\$LIB/libMangoHud.so",
```

There's no /usr/\$LIB/ folder on my box. I don't have time to look further at this until next weekend, what I can say for sure is that it might be best to just throw the current install() {} function in build.sh in the trash and start over.

**Comment by jackun** [comment]
Clean (aka `rm -fr build` ) build dir with `./build.sh clean` and try again.

**Comment by oyvindsaether** [comment]
Tried removing /src/MangoHud and starting with a fresh git clone, that made it create 64 libraries in build/release/usr/lib/mangohud/lib/libMangoHud.so so it installs fine.

I still get 
```
      "library_path": "/usr/lib/mangohud/\$LIB/libMangoHud.so",
```

in
```
./build/release/usr/share/vulkan/implicit_layer.d/MangoHud.json
```

and therefore also the installed 

```/usr/share/vulkan/implicit_layer.d/MangoHud.json```

I have no idea how that's supposed to work, there's no $LIB variable set by anything so it's just seen as /usr/lib/mangohud//libMangoHud.so. That works with 64 bit programs but not 32 bit ones.

It works with 32 and 64 bit programs if I just cp /usr/share/vulkan/implicit_layer.d/MangoHud.json to /usr/share/vulkan/implicit_layer.d/MangoHud32.json and change both so they read
```
      "library_path": "/usr/lib/mangohud/lib/libMangoHud.so",
```

and

```
      "library_path": "/usr/lib/mangohud/lib32/libMangoHud.so",
```

That's not something you can expect end-users to figure out on their own. And neither is using meson to specify anything. This is something that could be done better. I'll just write that installing from git is broken right now and leave it at that and perhaps look at it again next weekend if I have time (I write for casual end-users with basic linux know-how, not developers).

**Comment by jackun** [comment]
It is not a variable per se.
https://man7.org/linux/man-pages/man8/ld.so.8.html

**Comment by oyvindsaether** [comment]
One other detail: The remove the build/ dir thing is something the installation script should handle.

If something is built with mkdir build;cd build;cmake .. or similar then I'd expect to have to remove the build directory myself because _I made it_. If the instructions say run build.sh then it's not reasonable to expect end-users magically know they have to clean up this and that directory between running build.sh.

**Comment by jackun** [comment]
But `build.sh clean` does... But yeah, meson doesn't seem to reconfigure automatically, needs `--reconfigure` explicitly.

**Comment by oyvindsaether** [comment]
> But `build.sh clean` does... But yeah, meson doesn't seem to reconfigure automatically, needs `--reconfigure` explicitly.

Please consider updating README.md to say there is a 
```
build.sh clean
```
option and that end-users should run it before building it if they haven't built it before. It does not mention that there is any such option.

**Comment by jackun** [comment]
Wait, you don't have to run it if you haven't built before. Hmm.

**Comment by oyvindsaether** [comment]
> Wait, you don't have to run it if you haven't built before. Hmm.
> Ah, `install`fucking it up, it should call `build` too.

I meant.. if you HAVE built it before. Sorry!! my stupid.

**Comment by jackun** [comment]
> Ah, `install` fucking it up, it should call `build` too.

Never mind, it already does. Can't repro either so probably wasn't a "clean" build dir. Script should check that and force meson to reconfigure probably. And probably add how to "manually" install to README.
