### ISSUE TITLE
glxgears - working, games - not working

### ISSUE THREAD

**Issue by jebbyk** [flightlessmango/MangoHud#518]
I'm sure Im doing something wrong but I haven't found any solution for this. 
I've installed GOverlay and configured Mangohud. When I press "Run" button in GOverlay two windows with glxgears and vulkan cube are appearing and I can see mangohud working. But I cant understand how to launch it with any other game. 
I've tried  'mangohud ./XRebirth' with my none steam game X Rebirth (native) 
Also I've tried an "MAGOHUD=1" / "MANGOHUD=1 %comand%" options with three of my steam games ("starwolves" via wine, "overcooked" - native and "starconflict" - native). No one of them are launched with mangohud. 
Please help me. 
I will be happy to provide  as much information as I can.

**Comment by jebbyk** [comment]
Ubuntu 20.04

**Comment by flightlessmango** [comment]
This is probably not a mangohud issue. I'd recommend you visit the discord and ask for help there instead
