### ISSUE TITLE
OSD is not working in X Rebirth

### ISSUE THREAD

**Issue by jebbyk** [flightlessmango/MangoHud#519]
Ubuntu 20.04 
OSD is invisible. 30 fps cap is working though 
![image](https://user-images.githubusercontent.com/40975486/116801570-0161d980-ab2d-11eb-8587-dcc00c1282b8.png)
![image](https://user-images.githubusercontent.com/40975486/116801550-e1cab100-ab2c-11eb-8292-2bc81f8d0770.png)
![image](https://user-images.githubusercontent.com/40975486/116801542-cd86b400-ab2c-11eb-9970-fd4f624dc0f9.png)

**Comment by jackun** [comment]
Try building `develop` branch and setting `gl_bind_framebuffer=0` in config file.

**Comment by jebbyk** [comment]
I haven't tried development branch yet but I've noticed that OSD can appear and stay on screen maybe for half of a second or less not updating itself in some specific situations while I'm doing something in a main game menu

**Comment by jebbyk** [comment]
> Try building `develop` branch and setting `gl_bind_framebuffer=0` in config file.

How can I install development version if mangohud was installed with GOverlay? Is there anything specific I  have to do or just purge mangohud and build from develpment source?

**Comment by jackun** [comment]
If mangohud was installed with your distro's package then uninstall it before as the file paths are probably a little different.

**Comment by jebbyk** [comment]
@jackun  Thank you. it helped me. Should I try to use development version without gl_bind_framebuffer=0?
