### ISSUE TITLE
Is it posible to display just time?

### ISSUE THREAD

**Issue by murlakatamenka** [flightlessmango/MangoHud#52]
That's how I used MSI Afterbunrer years ago on Windows.

Currently the HUD will still show renderer (DXVK and its version, for instance), FPS / frametime.

**Comment by flightlessmango** [comment]
`MANGOHUD_CONFIG=frame_timing=0,fps=0,gpu_stats=0,cpu_stats=0,background_alpha=0,time`
you can disabled the defaults like so, I also set the background alpha to 0 since it will be too long anyway.

**Comment by murlakatamenka** [comment]
Thanks, it (`fps=0`) works! The tip about background alpha is relevant here too.

`fps` isn't present in the config file of the latest release version (0.2), so I thought it's always shown in the HUD. You can add it there to show that it can be toggled off too, current README says the config has a complete list of parameters:

> See the config file for a complete list.

Thanks again :+1:
