### ISSUE TITLE
[Feature request] options to show per core stats & throttling status

### ISSUE THREAD

**Issue by kunver400** [flightlessmango/MangoHud#520]
Is it possible for Mangohud to show per core temperature and throttling status + reason?

**Comment by gort818** [comment]
Looks like in Linux 5.14 we might be able to report throttling status with AMD gpus https://lists.freedesktop.org/archives/amd-gfx/2021-June/065521.html

**Comment by Faalagorn** [comment]
The per-core temperature could be shown instead of MHz when enabled, as I suggested in #550 originally.
