### ISSUE TITLE
Failed to build latest version (0.6.1): "python3 is missing modules: mako"

### ISSUE THREAD

**Issue by KairanD** [flightlessmango/MangoHud#521]
Hello!

I'm trying to build the latest version. However, it's not completing, reporting this error:

`Program python3 (mako) found: NO
meson.build:10:0: ERROR: python3 is missing modules: mako`

When I try to install mako, the result is:

`sudo pip3 install mako
Requirement already satisfied: mako in /usr/lib/python3/dist-packages (1.1.3)`

`sudo apt install python3-mako
python3-mako is already the newest version (1.1.3+ds1-2).`

When trying to search for mako:

`pip3 show mako
WARNING: Package(s) not found: mako`

My operating system is Debian 11 - Bullseye. Anyone has an idea of what's happening? Thanks in advance!

![image](https://user-images.githubusercontent.com/64203293/117002852-7a426c00-acba-11eb-84e5-61b35e2e4ea1.png)

![image](https://user-images.githubusercontent.com/64203293/117002741-52eb9f00-acba-11eb-8d6c-ca004f62c267.png)

**Comment by KairanD** [comment]
Got it working. Just cleaned the mess made by Anaconda and then pip3 install mako worked.

**Comment by JPTIZ** [comment]
For future references: ensure you're not with a virtualenv activate (unless intended, of course), as `meson` searches for library installations in currently activated virtualenv. So I had `mako` installed system-wide, but not on one specific project's virtualenv.
