### ISSUE TITLE
Steam pressure vessel might be a futur problem for MangoHUD

### ISSUE THREAD

**Issue by class101** [flightlessmango/MangoHud#523]
Hello guys, 

Firstly, thank you for your work on MangoHUD this is a great project for the linux community :)

I wanted to have your attention on a possible issue, that you possibly haven't caught yet because it requires to run a Windows game under Proton of Steam for Linux, with the Steam Client Beta update with MangoHUD enabled.

I have opened the following issue here because I believe this is something the Valve's devs have to consider 

https://github.com/ValveSoftware/steam-runtime/issues/408

To resume briefly the problem, Steam's pressure vessel redirects every request made to the directory `/usr/bin/` to the following one `/pressure-vessel/usr/bin`

So any executable present in  `/usr/bin/` but NOT in `/pressure-vessel/usr/bin`, will fail the C/C++ call to `popen()`, for instance `glxinfo` but the issue does not limit only to this executable, taking into accounts that pressure vessel can do this can probably save you from futur problems

Let me know if you need much informations

**Comment by stephanlachnit** [comment]
The executable isn't the problem afaik.The problem are the Vulkan Layers and libraries.

**Comment by class101** [comment]
@stephanlachnit 

There should be some technical restrictions under this decision I understand.

Anyway, thank you for your feedback, I have renamed the ticket anyway now to make it more clear there is a bug in MangoHUD with Proton

Steps to reproduce :

- Install Steam
- In Steam settings, select Steam Client Beta
- In Steam settings, enable latest Proton 6.3-4 version for all games
- Add `PROTON_LOG=1 mangohud %command%` as launch option on a Windows game
- Run the Windows game
- Open at the file in /home/$USER/steam-APPID.log for reading

Notice the following error is shown

```
MANGOHUD: recreating font image
sh: 1: glxinfo: not found
```

Attempting to create a symbolic link of `/usr/bin/glxinfo` into `/home/${USER}/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/var/deploy-0.20210415.0/files/bin` produces the following error

```
MANGOHUD: recreating font image
sh: 1: glxinfo: Too many levels of symbolic links
```

The only way I have found to fix was to copy `/usr/bin/glxinfo` inside the SteamLinuxRuntime_soldier directory

**Comment by stephanlachnit** [comment]
If you use recent proton versions, you should use `MANGOHUD=1 %command%` and it should work fine. The executable won't work (and so do OpenGL games for that matter).

**Comment by class101** [comment]
Ho thank you I didn't know this trick :)
