### ISSUE TITLE
Mangohud causes weird graphical glitch with flash player projector

### ISSUE THREAD

**Issue by JustinSpedding** [flightlessmango/MangoHud#525]
When playing swf files with the adobe flash player projector, enabling mangohud causes very strange color glitches. See this thread: https://www.reddit.com/r/Ubuntu/comments/kd3clw/adobe_flash_player_projector_ubuntu_color_glitch/

I am having the same issue, and it only started after I installed mangohud.

I am on Linux Mint 20.1 with nvidia 460.73 drivers

**Comment by jackun** [comment]
How does disable vulkan layer for a app that does not use vulkan fix it? Nvidia magic....

**Comment by JustinSpedding** [comment]
Oh, I forgot about this issue. I "solved" it by disabling hardware acceleration in the flash player settings. That is not a true fix for whatever the underlying issue is, but I am not running any flash games with graphics intense enough not to work via CPU rendering. I'm pretty sure the root cause is buggy nvidia drivers.
