### ISSUE TITLE
Doesn't work with Red Alert 3 (Proton 6.3-4)

### ISSUE THREAD

**Issue by vanphong1310** [flightlessmango/MangoHud#527]
As the title. Mangohud run fine with all games (proton and native) except C&C Red Alert 3, game run fine, DXVK_HUD work but Mangohud doesn't show anything.
I installed mangohud 0.6.1 by release file.
Steam run command: gamemoderun %command%
Environment variable: export GAMEMODERUNEXEC="env __NV_PRIME_RENDER_OFFLOAD=1 env __VK_LAYER_NV_optimus=NVIDIA_only env __GLX_VENDOR_LIBRARY_NAME=nvidia env NODEVICE_SELECT=1 env MANGOHUD=1"

**Comment by flightlessmango** [comment]
Check that you have 32bit mangohud installed

**Comment by vanphong1310** [comment]
> Check that you have 32bit mangohud installed

How do I check it?

**Comment by flightlessmango** [comment]
what distro are you on and how did you install mangohud?

**Comment by vanphong1310** [comment]
I use Linux Mint and I install from release file of this repo.

**Comment by flightlessmango** [comment]
Install vulkan-tools with apt, try running `mangohud vkcube` and see if mangohud shows.

if that works then try this 32bit vkcube. unzip and give it execute permissions, then run `mangohud ./vkcube32` and see if mangohud shows

[vkcube32.zip](https://github.com/flightlessmango/MangoHud/files/6528118/vkcube32.zip)

**Comment by vanphong1310** [comment]
`mangohud vkcube` works fine.
But `mangohud ./vkcube32` does't work, it show error in terminal:
```
$ mangohud ./vkcube32
ERROR: ld.so: object 'libMangoHud.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
./vkcube32: error while loading shared libraries: libgbm.so.1: cannot open shared object file: No such file or directory
```

**Comment by vanphong1310** [comment]
After clean all mangohud and reinstall from release file, mangohud overlay is show up. It seem like I made mistakes somewhere.
But I still can't run vkcube32, it exit with error:
`./vkcube32: error while loading shared libraries: libgbm.so.1: cannot open shared object file: No such file or directory`
I installed libgbm-dev and libgbm1 packages.
