### ISSUE TITLE
Please save a text file with AVG 1% and 0.1%, as the last benchmark results that show at end of logging

### ISSUE THREAD

**Issue by binarydepth** [flightlessmango/MangoHud#528]
I am doing some testings and want that data for FPS stability. I have been screenshoting but it would me more convenient not having to do that and just files named accordingly with all the data. Either it could be last entry to the file or output a text fiel with corresponding name. I'm trying to find the formulas but not avail, using LibreOffice Calc to render a spreadsheet.

**Comment by gort818** [comment]
https://github.com/flightlessmango/MangoHud#mangohud-fps-logging

**Comment by binarydepth** [comment]
Ok TY for showing me this. I see the benchmarks don't present information in the same format. AVG 1% and 0.1% as [here](https://forum.garudalinux.org/t/my-benchmark-with-path-of-exile-zen-xanmod-and-tkg-bmq/8572/13)

**Comment by binarydepth** [comment]
Ok TY for showing me this. I see the benchmarks don't present information in the same format. AVG 1% and 0.1% as [here](https://forum.garudalinux.org/t/my-benchmark-with-path-of-exile-zen-xanmod-and-tkg-bmq/8572/13).

**Comment by flightlessmango** [comment]
A benchmark summary file was added a while ago
