### ISSUE TITLE
MangoHud doesn't work globally on Vulkan and OpenGL

### ISSUE THREAD

**Issue by Toadfield** [flightlessmango/MangoHud#529]
I asked on https://github.com/flightlessmango/MangoHud/issues/483 some weeks ago,if there is a way to do that,but then I forgot about it,but yesterday I wanted to try it out and it didn't work.
My .profile looks like this:
```
export LD_PRELOAD=/usr/lib/libMangoHud.so
export MANGOHUD_DLSYM=1
export MANGOHUD=1
export GTK_CSD=0
export LD_PRELOAD=/usr/lib/libgtk3-nocsd.so.0
export CLUTTER_BACKEND=wayland
export GTK_USE_PORTAL=1
```
and the relevant things are:
```
export LD_PRELOAD=/usr/lib/libMangoHud.so
export MANGOHUD_DLSYM=1
export MANGOHUD=1
```
I tried it with a vulkan game and that worked,but it doesn't with OpenGL games.
I am using arch kde,it doesn't work on xorg and wayland.
The games I tested work when I manually start them with "mangohud MANGOHUD_DLSYM=1 MANGOHUD=1".
So what do I do wrong?
Other LD_PRELOAD Env Vars work.

**Comment by flightlessmango** [comment]
Are you sure `/usr/lib/libMangoHud.so` is the correct path? If the game is 32bit, you would also need to preload the 32bit lib of mangohud

**Comment by Toadfield** [comment]
Do I need to enable both,the lib32 version of dlsym.so and the lib32 version of the normal mangohud.so or just the normal lib3 mangohud.so?

**Comment by jackun** [comment]
```
export LD_PRELOAD=/usr/lib/libMangoHud.so
...
export LD_PRELOAD=/usr/lib/libgtk3-nocsd.so.0
```

You're ovewriting. Also.. just don't.

**Comment by Toadfield** [comment]
> You're overwriting

So is it impossible to use multipe LD_PRELOAD env vars?

> Also.. just don't
Why?

**Comment by Toadfield** [comment]
My config file looks like this now:
```
export LD_PRELOAD=/usr/lib/libMangoHud.so /usr/lib32/libMangoHud.so /usr/lib/libgtk3-nocsd.so.0
export MANGOHUD_DLSYM=1
export MANGOHUD=1
export GTK_CSD=0
export CLUTTER_BACKEND=wayland
export GTK_USE_PORTAL=1

```
So what did I set wrongly?

**Comment by jackun** [comment]
> export LD_PRELOAD=/usr/lib/libMangoHud.so:/usr/lib32/libMangoHud.so:/usr/lib/libgtk3-nocsd.so.0

**Comment by Toadfield** [comment]
I now have
```
export LD_PRELOAD=/usr/lib/libMangoHud.so:/usr/lib32/libMangoHud.so:/usr/lib/libgtk3-nocsd.so.0
export MANGOHUD_DLSYM=1
export MANGOHUD=1
export GTK_CSD=0
export CLUTTER_BACKEND=wayland
export GTK_USE_PORTAL=1
```
But it still doesn't work

**Comment by Toadfield** [comment]
I tested it witch cs:go (OpenGL game) and it didn't work,and I also tested it with Prey 2017 (dxvk game) and that also didn't work.

**Comment by Toadfield** [comment]
I changed the title,cause it also doesn't work on Vulkan

**Comment by flightlessmango** [comment]
Currently there is no "safe" way of doing this. We don't recommend or support it at this time, hence I don't think it's appropriate for us to try and help people achieve this.

As for vulkan not working, it probably has to do with the preloading (which again we don't recommend/support)

**Comment by Toadfield** [comment]
> We don't recommend or support it at this time

But will you support this in the near future?
Cause this feature is really necassery.

**Comment by flightlessmango** [comment]
When and if someone figures out a reliable way of doing it, we can support it. Right now I'm not certain it's even possible to do on Linux

**Comment by Toadfield** [comment]
It already works on Windows to do things like that globally,so what exactly is the difference for linux?

**Comment by Toadfield** [comment]
Btw did anyone ever got it to work with LD_PRELOAD?
