### ISSUE TITLE
Vega 3 gets 0% use

### ISSUE THREAD

**Issue by BNandroid** [flightlessmango/MangoHud#53]
I use an AMD Athlon 200GE APU with Vega 3 Graphics and my gpu load is 0% :/

**Comment by jackun** [comment]
What does `cat /sys/class/drm/card*/device/gpu_busy_percent` output?

**Comment by BNandroid** [comment]
> What does `cat /sys/class/drm/card*/device/gpu_busy_percent` output?

Invalid Argument

Do I need to install any packages?

**Comment by jackun** [comment]
For some reason `gpu_busy_percent` doesn't support Vega 3 then. 
Can you try [radeon-profile](https://github.com/marazmista/radeon-profile) or radeontop? If these work then using ioctl instead might work.

**Comment by theron29** [comment]
I have exactly the same issue on my notebook with Vega10.
> cat /sys/class/drm/card*/device/gpu_busy_percent 
also returns Invalid Argument.

Using Oibaf drivers on Ubuntu 19.10 with ACO enabled.

**Comment by BNandroid** [comment]
> For some reason `gpu_busy_percent` doesn't support Vega 3 then.
> Can you try [radeon-profile](https://github.com/marazmista/radeon-profile) or radeontop? If these work then using ioctl instead might work.
> 
> Maybe adding amdgpu.ppfeaturemask to kernel command line might help like `amdgpu.ppfeaturemask=0xfffd7fff`

I will test this later, thanks 😁

**Comment by flightlessmango** [comment]
@BNandroid did you try it and if so did it work?

**Comment by ViNi-Arco** [comment]
hi, it happens to me too, I have Nvidia card, see does not show the use of the GPU nor the processor temperature:

![2020-03-09-163935_1440x900_scrot](https://user-images.githubusercontent.com/57958460/76463703-a28a4f80-63c2-11ea-9ea1-f5da9368047d.png)

**Comment by BNandroid** [comment]
> @BNandroid did you try it and if so did it work?

I tried everything, still 0%: /

**Comment by flightlessmango** [comment]
@ViNi-Arco your 0% gpu load is probably is probably because your Nvidia card is not supported in NVML, what GPU is it? why the cpu temp isn't showing I don't know, what CPU is it?

**Comment by ViNi-Arco** [comment]
Good morning @flightlessmango, I have an EVGA GTX 650, it has NVML support, because in MSI Afterburner I can see the GPU usage and the CPU Temp, my Processor is the E8400 rev.E0

**Comment by flightlessmango** [comment]
@ViNi-Arco is this command able to get the load %?
`nvidia-smi --query-gpu=utilization.gpu --format=csv,noheader`

**Comment by ViNi-Arco** [comment]
Hi, @flightlessmango, the terminal reports this:

![oie_ZzHHtdXWyUSJ](https://user-images.githubusercontent.com/57958460/76527559-37865a80-644e-11ea-8adf-dafd16bb0b6b.png)

Which is at least strange because on the Nvidia Panel you can see the GPU usage:

![FotoJet](https://user-images.githubusercontent.com/57958460/76528608-dbbcd100-644f-11ea-8d3e-38348f2387c3.png)

**Comment by flightlessmango** [comment]
Back to the actual issue were on, as far as I know I can't do anything to fix the AMD gpu load either, it's up to the amdgpu kernel devs to fix (I think)

@ViNi-Arco most likely that program uses libXNVCtrl instead, which does support older cards. libXNVCtrl has been mentioned as a possible replacement for NVML before, but I haven't had too much time to look into if it's a good idea or not. Either way! sadly you cannot view your gpu load with mangohud as of yet and we can't fix it right now at least

**Comment by CorruptCommit** [comment]
See #3 for libXNVCtrl discussion.
