### ISSUE TITLE
can't find cpu data on arm linux (rk3399)

### ISSUE THREAD

**Issue by Askmewho** [flightlessmango/MangoHud#530]
Hi, I know this program wasnt intended for arm linux.
the thing is that many stuff are missing. and it's odd bc while i dont know to code the
program seems to look for values on /sys/class/hwmon/
and for example, the temperature, that the program cant find.. its able to be find with
cat /sys/class/hwmon/hwmon0/temp1_input
so, maybe its just add other entries. 

I have other values to resolve like cpu frequency. but would be cool to at least get to display the temperature. 

thanks on advance

**Comment by jackun** [comment]
It's filtering by sensor name/label currently. For a quick fix you can try building MangoHud yourself, check the sensor name and label from `cat /sys/class/hwmon/hwmon0/{name,temp1_label}`, add it to `cpu.cpp`. _Should_ be obvious what to copy/paste in `CPUStats::GetCpuFile` function.
