### ISSUE TITLE
[REQUEST] fps_limit=auto?

### ISSUE THREAD

**Issue by kokoko3k** [flightlessmango/MangoHud#534]
Woiuld i t be techically possible to set fps_limit=auto and have it automagically limit the framerate to the current screen refresh rate?
It sould be handy for those who, like me, prefer 0 lag but don't want to have the cpu to 100% without reason.
I know it is possible to cycle the value, but still it would be handy ;)

**Comment by gort818** [comment]
Why not just use vsync?

**Comment by kokoko3k** [comment]
I wrote it, gort818, less lag.

**Comment by flightlessmango** [comment]
I can't see a good way of finding out the current refresh rate on xorg and wayland, making it a little difficult. I also don't see how this is useful, there's situations where you would change refresh rate in certain games or something?

**Comment by kokoko3k** [comment]
Well, my usecase is that i usually set the refresh rate to the average my rig (monitor included) can sustain for a game.
For example, i play sottr at 55hz, while borderlands 3 at 72hz

**Comment by flightlessmango** [comment]
Why change your refresh rate at all?

**Comment by kokoko3k** [comment]
Because when the  fps matches the refresh rate, you have no stuttering.
