### ISSUE TITLE
/bin/sh: error while loading shared libraries: libimgui.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by warriormaster12** [flightlessmango/MangoHud#538]
Basically after updating mangohud to the latest version, I can't launch any application due to this error in the title 

```
/bin/sh: error while loading shared libraries: libimgui.so: cannot open shared object file: No such file or directory
```

**Comment by flightlessmango** [comment]
Release package seems borked, I'm working on fixing it. Meanwhile it should work fine to build it manually

**Comment by flightlessmango** [comment]
Does this build work? https://github.com/flightlessmango/MangoHud/releases/download/v0.6.2/MangoHud-0.6.2.r1.g94dda24.tar.gz

**Comment by warriormaster12** [comment]
Yup, this one seems to work without any issues.

![image](https://user-images.githubusercontent.com/33091666/121741293-fbd1b900-cb06-11eb-872e-da46596747b6.png)

**Comment by flightlessmango** [comment]
Awesome!
