### ISSUE TITLE
Unknown option 'cpu_mhz' (and 'cpu_power' 'cpu_load_power')

### ISSUE THREAD

**Issue by gardotd426** [flightlessmango/MangoHud#539]
Updated to the latest release (0.6.3), and I saw that you guys have added a ton of awesome new config options. I added a couple, including `cpu_mhz`, `cpu_power`, and `cpu_load_power`). I added them to the config, literally just copying and pasting them from the MangoHud.conf.example file (without the comments obviously). 

But when I launch vkcube or glxgears to try and test the new stuff out, I get:

```
MANGOHUD=1 vkcube
skipping config: /usr/bin/MangoHud.conf [ not found ]
skipping config: /home/matt/.config/MangoHud/vkcube.conf [ not found ]
parsing config: /home/matt/.config/MangoHud/MangoHud.conf [ ok ]
Unknown option 'cpu_mhz'
Unknown option 'cpu_load_value'
Unknown option 'cpu_power'
Selected GPU 0: NVIDIA GeForce RTX 3090, type: 2
```

I thought that maybe it was just that some of your CPU stat options are Intel-only and I'm on a Ryzen 9 5900X, just like how `cpu_temp` won't work if using `zenpower-dkms` instead of `k10temp`, but when that was the case I would get a message like "could not find cpu temperature data" or something like that, not output literally saying the options themselves don't exist. 

The new GPU options I added like `gpu_mhz` and `gpu_power` are working as intended. 

I tried with both the AUR package (which was updated to 0.6.3 right after it released), and then a few minutes ago with building from source, and I got the same result. 

System Info:
Arch Linux
Ryzen 9 5900X (using k10temp)
RTX 3090 (driver version 465.31)
Kernel 5.13.0-rc5-tkg-cfs
Meson/Ninja and all that are up to date, I ran a system update before building MangoHud.

**Comment by gort818** [comment]
Can you trying doing a clean build `./build.sh clean` and then `./build.sh install`

**Comment by gardotd426** [comment]
That's what I did when I tried the manual build/install that I mentioned.

But just for the sake of completeness, I just did a completely fresh git clone in a new directory, ran `./build.sh clean` and then `./build.sh install`, and:

```
MANGOHUD=1 vkcube
skipping config: /usr/bin/MangoHud.conf [ not found ]
skipping config: /home/matt/.config/MangoHud/vkcube.conf [ not found ]
parsing config: /home/matt/.config/MangoHud/MangoHud.conf [ ok ]
Unknown option 'cpu_mhz'
Unknown option 'cpu_load_value'
Unknown option 'cpu_power'
Selected GPU 0: NVIDIA GeForce RTX 3090, type: 2
```

**Comment by gardotd426** [comment]
I'll also add that if I just use `MANGOHUD=cpu_mhz,cpu_power,cpu_load_value mangohud vkcube` (to bypass the config file) I get the same result.

**Comment by flightlessmango** [comment]
it's `MANGOHUD_CONFIG` for settings params with env var, but that shouldn't work eitherway. Can you check the version with the `version` param?

**Comment by gardotd426** [comment]
Uh, it says 0.4.0, what the hell?

Let me try completely removing it from my system and reinstalling, maybe a lib didn't get updated correctly or something? I'll report back

**Comment by gardotd426** [comment]
So, yeah after completely wiping everything but the ~/.config/MangoHud/MangoHud.conf file and reinstalling from scratch, I get version 0.6.3, and the new options work. 

However cpu_power doesn't work (at least for Zen 3). It just reports 0W. Temp reporting has always worked but it won't show wattage.

**Comment by jackun** [comment]
IIRC in-kernel sensor was deemed too inaccurate and got removed. You can try `zenpower`.
