### ISSUE TITLE
MPV segmentation fault

### ISSUE THREAD

**Issue by arrowgent** [flightlessmango/MangoHud#54]
```
0x00007fffc8fa8154 in overlay_CreateInstance(VkInstanceCreateInfo const*, VkAllocationCallbacks const*, VkInstance_T**) () from /home/catbox/.local/share/MangoHud/libMangoHud.so
(gdb) quit

```
checked with 

> gdb mpv

using mpv.conf
```
hwdec=vo_gpu
vo=gpu
# VULKAN
gpu-context=x11vk
gpu-api=vulkan
spirv-compiler=auto
```

this is my MangoHud.conf
```
### MangoHud configuration file
### Uncomment any options you wish to enable. Default options are left uncommented
### Use some_parameter=0 to disable a parameter (only works with on/off parameters)
### Everything below can be used / overridden with the environment variable MANGOHUD_CONFIG instead

### MANGOHUD=1 %command%

################ PERFORMANCE #################

### Limit the application FPS
fps_limit=60

### VSYNC [0-3] 0 = adaptive; 1 = off; 2 = mailbox; 3 = on
vsync=1

################### VISUAL ###################

### Display the current CPU information
cpu_stats
cpu_temp

### Display the current GPU information
gpu_stats
gpu_temp

### Display the frametime line graph
frame_timing=0

### Display the current system time
# time

### Change the hud font size (default is 24)
font_size=12

### Change the hud position (default is top-left)
position=top-left

### Display the current CPU load & frequency for each core
# core_load

### Display system ram / vram usage
ram
vram

### Disable / hide the hud by deafult
no_display

### Hud position offset
offset_x=0
offset_y=16

### Hud dimensions
width=133
height=69

### Hud transparency / alpha
background_alpha=0.01

### Crosshair overlay (default size is 30)
# crosshair
# crosshair_size=16
# crosshair_color=RRGGBB

################## INTERACTION #################

### Change toggle keybinds for the hud & logging
toggle_hud=F13
toggle_logging=F13
# toggle_hud=F12
# toggle_logging=F2
```

my ~/.profile
```
export MANGOHUD=1
```
mpv version
v0.32.0

vulkanapi version (vulkaninfo)
Vulkan Instance Version: 1.2.131
MangoHud 32/64bit (Vulkan Hud Overlay) Vulkan version 1.1.125

NVIDIA-SMI 440.59 

setting MANGOHUD=0 fixes the issue

**Comment by flightlessmango** [comment]
This should be fixed in the develop branch, can you confirm?

**Comment by arrowgent** [comment]
> modules/ImGui/meson.build:1:0: ERROR: File src/imgui.cpp does not exist.

**Comment by flightlessmango** [comment]
`git submodule update --init --depth 50` should fix it

**Comment by arrowgent** [comment]
i have no idea if this is pulling the -develop.git or not....

> git clone --single-branch --branch develop --recurse-submodules https://github.com/flightlessmango/MangoHud.git

also your git requires python3.7 or 3.8 not 3.6,  so i just set it to 3.8 for your compile

i still have to use python3.6 for literally everything else (apt included) because im using Ubuntu18.04

export MANGOHUD=1
gdb mpv
> Starting program: /usr/bin/mpv 
> [Thread debugging using libthread_db enabled]
> Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
> [New Thread 0x7fffe3644700 (LWP 31183)]
> [New Thread 0x7fffe2e43700 (LWP 31184)]
> [New Thread 0x7fffe2642700 (LWP 31185)]
> [New Thread 0x7fffe1e41700 (LWP 31186)]
> [New Thread 0x7fffe1640700 (LWP 31187)]
> [New Thread 0x7fffe0e3f700 (LWP 31188)]
> [New Thread 0x7fffcbfff700 (LWP 31189)]
> [New Thread 0x7fffcb7fe700 (LWP 31190)]
> [New Thread 0x7fffcaffd700 (LWP 31191)]
> skipping config: /usr/bin/MangoHud.conf
> skipping config: /home/catbox/.config/MangoHud/mpv.conf
> parsing config: /home/catbox/.config/MangoHud/MangoHud.conf [ ok ]
> [New Thread 0x7fffb8b4a700 (LWP 31192)]
> cat: /etc/upstream-release: Is a directory
> [no_osc] The 'tick' event is deprecated and will be removed.
> [New Thread 0x7fffb6589700 (LWP 31230)]
> [New Thread 0x7fffb5d88700 (LWP 31231)]
> [Thread 0x7fffb6589700 (LWP 31230) exited]
> [New Thread 0x7fffb6589700 (LWP 31232)]
> [New Thread 0x7fffb5587700 (LWP 31233)]
> [Thread 0x7fffb6589700 (LWP 31232) exited]
> [Thread 0x7fffb5587700 (LWP 31233) exited]
> [Thread 0x7fffb5d88700 (LWP 31231) exited]
> 

mpv opens and runs properly.

**Comment by SolitudeSF** [comment]
still segfaults for me with 0.3.5

**Comment by flightlessmango** [comment]
@SolitudeSF I have no issues on my end with opengl or vulkan with mpv. Can you give some more details? amd/nvidia, distro, opengl/vulkan etc

**Comment by SolitudeSF** [comment]
amd, void, vulkan.

**Comment by SolitudeSF** [comment]
actually, it works when launched with `mangohud mpv` regardless of opengl/vulkan mode.

**Comment by flightlessmango** [comment]
So the problem stems from globally enabled `MANGOHUD=1` env?

**Comment by SolitudeSF** [comment]
also, launched with just `MANGOHUD=1` it parses config files once before segfaulting 
```
skipping config: /usr/bin/MangoHud.conf [ not found ]
skipping config: /home/solitude/.local/etc/MangoHud/mpv.conf [ not found ]
parsing config: /home/solitude/.local/etc/MangoHud/MangoHud.conf [ ok ]
Exception: mpv killed by signal segmentation fault
```
but with `mangohud` prefixed it parses them twice
```
skipping config: /usr/bin/MangoHud.conf [ not found ]
skipping config: /home/solitude/.local/etc/MangoHud/mpv.conf [ not found ]
parsing config: /home/solitude/.local/etc/MangoHud/MangoHud.conf [ ok ]
skipping config: /usr/bin/MangoHud.conf [ not found ]
skipping config: /home/solitude/.local/etc/MangoHud/mpv.conf [ not found ]
parsing config: /home/solitude/.local/etc/MangoHud/MangoHud.conf [ ok ]
```

**Comment by SolitudeSF** [comment]
> So the problem stems from globally enabled MANGOHUD=1 env?
thats certainly the necessary condition.

**Comment by SolitudeSF** [comment]
just tried, crashes on arch the same way, so its not void specific.

**Comment by jackun** [comment]
@SolitudeSF search for `libMangoHud.so` seems like you have it installed twice

**Comment by SolitudeSF** [comment]
i installed it from aur.

**Comment by flightlessmango** [comment]
double check that you never installed mangohud with the release package

**Comment by SolitudeSF** [comment]
i did install, but im pretty sure i removed all traces of it.

**Comment by jackun** [comment]
Hmm, `mangohud` could just be using one parsing out put for openGL and second is for vulkan, but it just shows once for me.
