### ISSUE TITLE
Broken build when installing from AUR

### ISSUE THREAD

**Issue by mkrasnitski** [flightlessmango/MangoHud#540]
Installing the newest version from the AUR results in a failed build. Here's a log of the terminal output: https://pastebin.com/hDZ4AGXh

The build fails with error `AttributeError: module 'sys' has no attribute 'setcheckinterval'`. As far as I'm aware, this is a python2 exclusive feature and was renamed to `setswitchinterval` in python 3. On Arch at least, the `/usr/bin/python` binary points to python 3, so either the AUR package should rely on python2 instead, or a change should be made to the build scripts.

**Comment by Kron4ek** [comment]
I can't reproduce this, the AUR package builds without errors for me. Seems like you have [very old](https://github.com/tqdm/tqdm/commit/2189a2b291c1b550fe35f54267d088083b737712) python-tqdm version installed, could you please show the content of `/usr/lib/python3.9/site-packages/tqdm/_tqdm.py`?

**Comment by jackun** [comment]
Seems to be optional, update or uninstall `tqdm`.

**Comment by mkrasnitski** [comment]
Reinstalling tqdm fixed the issue. What's strange is that I was on the latest version of the library, so I don't know how python2-specific code got in there.
