### ISSUE TITLE
0.6.3: exec spawns endless rsstail processes

### ISSUE THREAD

**Issue by dpanter** [flightlessmango/MangoHud#544]
Trying to run `rsstail` (terminal RSS feed reader) to grab RSS feeds into MangoHud 0.6.3 on Debian sid.
`exec=rsstail -u http://rss.cnn.com/rss/cnn_latest.rss`

The feed is not displayed. System is immediately flooded with new rsstail processes, more than one per second, and they do not terminate when exiting the app using MangoHud. I used vkcube and glxgears to test, both show the same behavior.
Running the same command in a terminal starts only one process, as intended.

**Comment by flightlessmango** [comment]
`exec` excepts that the command gets an output and then quits. It would not be compatible with something that monitors, which I assume `rsstail` is doing

By default it runs the command every 0.5 seconds

**Comment by dpanter** [comment]
Alright, that would be useful to add to the documentation. :)

Here's a solution.
Run terminal RSS reader like rsstail and log to a file.
```rsstail -N -i 300 -u https://www.gamingonlinux.com/article_rss.php > /path/to/file/golrss.txt```

Tail the last line in your MangoHud config file.
```exec=tail -n 1 /path/to/file/golrss.txt```

![Screenshot_20210614_090602](https://user-images.githubusercontent.com/14197392/121853265-03ed4c80-ccf1-11eb-8055-8d39824a024a.png)


Original text in that RSS feed: _Prepare to smash blocks together as Petal Crash Online is out now in Beta_
As you can see, the text doesn't fit and having a really wide MangoHud window might not be desirable. Can we change font size specifically for the exec command output? Alternatively, allow line breaks?

**Comment by dpanter** [comment]
This question was lost in the edits. The issue can be closed, but I'd still like to know this:
Can we change font size specifically for the exec command output? Alternatively, allow line breaks?

**Comment by dpanter** [comment]
Closing since the original issue has a solution of sorts.
