### ISSUE TITLE
error: duplicate symbol: dlsym

### ISSUE THREAD

**Issue by AngryPenguinPL** [flightlessmango/MangoHud#545]
Hi.

When compiling MangoHud 0.6.3 with dlsym enabled I get error:
` error: duplicate symbol: dlsym`

Full build log: https://file-store.openmandriva.org/api/v1/file_stores/acbfc22f0e455bc677a42ea7985f40a986ce1952.log?show=true

OpenMandriva Cooker
Compiler: LLVM/Clang 12 
Linker: LLD
LTO enabled
arch: x86_64

Compilation without dlsym works fine.

**Comment by jackun** [comment]
`with_dlsym` is pretty much a left over. Should probably remove it until dlsym overloading stop breaking stuff.
