### ISSUE TITLE
MangoHud not showing GPU info

### ISSUE THREAD

**Issue by TheEpicNoobZilla** [flightlessmango/MangoHud#548]
I've just installed MangoHud 0.6.3 on Ubuntu 20.04 and when i edited example config to show cpu,ram, gpu and wine the program is not showing gpu info, says that VRAM is 0 GB (GPU have 1 GB of it) also terminal says that failed to upload and initialize CPU power data (hashed option).

PC specs:
CPU: Intel Core 2 Quad Q6600
GPU: Radeon HD 5570 1 GB (open source driver, proprietary works only on Ubuntu 14.04

**Comment by TheEpicNoobZilla** [comment]
Card pci:id is 1002:68d9

**Comment by TheEpicNoobZilla** [comment]
lshw output:

*-display                 
       description: VGA compatible controller
       product: Redwood PRO [Radeon HD 5550/5570/5630/6510/6610/7570]
       vendor: Advanced Micro Devices, Inc. [AMD/ATI]
       physical id: 0
       bus info: pci@0000:01:00.0
       version: 00
       width: 64 bits
       clock: 33MHz
       capabilities: pm pciexpress msi vga_controller bus_master cap_list rom
       configuration: driver=radeon latency=0
       resources: irq:32 memory:e0000000-efffffff memory:f1000000-f101ffff ioport:8000(size=256) memory:c0000-dffff

**Comment by TheEpicNoobZilla** [comment]
lspci output:
01:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Redwood PRO [Radeon HD 5550/5570/5630/6510/6610/7570] [1002:68d9] (prog-if 00 [VGA controller])
	Subsystem: PC Partner Limited / Sapphire Technology Radeon HD 5570 [174b:e142]
	Flags: bus master, fast devsel, latency 0, IRQ 32
	Memory at e0000000 (64-bit, prefetchable) [size=256M]
	Memory at f1000000 (64-bit, non-prefetchable) [size=128K]
	I/O ports at 8000 [size=256]
	Expansion ROM at 000c0000 [virtual] [disabled] [size=128K]
	Capabilities: [50] Power Management version 3
	Capabilities: [58] Express Legacy Endpoint, MSI 00
	Capabilities: [a0] MSI: Enable+ Count=1/1 Maskable- 64bit+
	Capabilities: [100] Vendor Specific Information: ID=0001 Rev=1 Len=010 <?>
	Capabilities: [150] Advanced Error Reporting
	Kernel driver in use: radeon
	Kernel modules: radeon

**Comment by jackun** [comment]
> Kernel driver in use: radeon

Mangohud primarily expects that you're using `amdgpu` as `radeon` doesn't support vulkan. But
