### ISSUE TITLE
Mangohud not working with wine

### ISSUE THREAD

**Issue by TheEpicNoobZilla** [flightlessmango/MangoHud#549]
Mangohud is not showing when using wine. Tried mangohud wine, wineprefix=/Path/to/prefix mangohud wine. --dlsym does not work either (OpenGL only GPU)

**Comment by Francehelder** [comment]
Try with NODEVICE_SELECT=1 environment variable

**Comment by TheEpicNoobZilla** [comment]
Not working

**Comment by flightlessmango** [comment]
Are you saying that mangohud does work with a previous version of wine?

**Comment by flightlessmango** [comment]
Assuming we're still talking about the `5570` GPU, it would be wined3d and wined3d requires dlsym. Please show full command you're using where mangohud does not show

**Comment by TheEpicNoobZilla** [comment]
Tried manghoud --dlsym wine ./CoD2SP.exe (tried also with sims 2 and X-wing alliance). I don't have access to this PC right now (not my main PC). Also i am using Gallium nine from iXit github repo, if this helps.

**Comment by jackun** [comment]
Gallium nine isn't opengl so there's nothing for MangoHud to hook.
