### ISSUE TITLE
Showing temperature of each CPU cores instead of MHz

### ISSUE THREAD

**Issue by Faalagorn** [flightlessmango/MangoHud#550]
Would it be possible to add an option to show the temperature instead of speed for each of the cores?

**Comment by jackun** [comment]
https://github.com/flightlessmango/MangoHud/issues/520

**Comment by Faalagorn** [comment]
For some reason it doesn't appear for me, but I see you tagged it in #520 which seems to be duplicate of my question, so I guess there's no point in keeping two opens, let carry the discussion there.
