### ISSUE TITLE
Mangohud stutters when battery monitoring is turned on

### ISSUE THREAD

**Issue by Trevonn** [flightlessmango/MangoHud#551]
I get spikes every few seconds when I add battery to my config file.

Here are some 15 second log files with the battery turned on and off
https://flightlessmango.com/games/8330/logs/1789
https://flightlessmango.com/games/8330/logs/1788

[MangoHud.txt](https://github.com/flightlessmango/MangoHud/files/6680680/MangoHud.txt)
I changed the file to txt as `.conf` are not allowed on github

**Comment by gort818** [comment]
Thanks for the report, i will look into this.

**Comment by gort818** [comment]
Can you test the latest develop branch and see if it fixes your issue?

**Comment by Trevonn** [comment]
It is fixed now thank you :)

**Comment by gort818** [comment]
fixed in 0bc6d33a24902d0a0c041a5d227155321fce6369
