### ISSUE TITLE
Lutris Not Running with latest Mangohud Version

### ISSUE THREAD

**Issue by supernova874** [flightlessmango/MangoHud#552]
Some time now from  my repository andf version 6.3-1 (chaotic-aur and from aur) on Garuda Linux the Lutris won't start but halts in Loading bar , so i used an older version installed via pamac the 6.3 r2 something i believe it was , and today it get the 6.3 r3.g0bc6d33-1 and has broken also , i needed to install and older version have dl from git to make it work. and i already have the enviroment setting NODEVICE... set from before

**Comment by flightlessmango** [comment]
You're starting lutris with mangohud? it's not designed to be used like that, as such I have no plans on fixing it

**Comment by supernova874** [comment]
With the 6.3 from git i get this:


# Checking Dependencies
# Unable to find distro information!
# Attempting to build regardless
./build.sh: line 145: meson: command not found


The version i use without any issue is the 6.1

**Comment by supernova874** [comment]
> You're starting lutris with mangohud? it's not designed to be used like that, as such I have no plans on fixing it

And how can i use it with lutris then?

**Comment by flightlessmango** [comment]
Under system options there is an option for `FPS counter (MangoHud)`. You can also add `mangohud` to "Command prefix", also under system options

**Comment by supernova874** [comment]
Yes thats how is use it , when the last version installed via the update (pacman) the lutris isn't starting at all , when i uninstall mangohud it worked fine so i installed the older 6.1 version and working like a charm and i will stay with that since there are many compatibility issues with mangohud and my Distro (Garuda) since in my Manjaro pc it working fine always...

Spyridon Pigkas
Sent from Mailspring, the best free email app for work & the best on Linux

E: ***@***.*** , ***@***.*** ***@***.***/0?redirect=mailto%3Asupernova%40mailo.com%20%2C%20supernova874%40protonmail.com&recipient=cmVwbHkrQUxCM1A0VUJYTFYzUlZHM0lRSkhHWjU2M1hRUlJFVkJOSEhET1JRM1Y0QHJlcGx5LmdpdGh1Yi5jb20%3D)

**Comment by flightlessmango** [comment]
It sounds like you have `MANGOHUD=1` in your `.profile` or something similar. Otherwise it shouldn't interact with lutris at all

**Comment by supernova874** [comment]
> It sounds like you have `MANGOHUD=1` in your `.profile` or something similar. Otherwise it shouldn't interact with lutris at all

the only "parameter" i have set was NODEVICE_SELECT=1 anyway as i said i will stay with 6.1 that works...
