### ISSUE TITLE
0.6.4 not correctly identifying VKD3D in games

### ISSUE THREAD

**Issue by jhu54** [flightlessmango/MangoHud#555]
release 0.6.2 will display VKD3D when running games using dx12 through Lutris or Steam. Upgrade to release 0.6.4 and all games show as DXVK regardless of whether dx12 is enabled or not. Uninstall 0.6.4 and install 0.6.2, correct graphics is shown in the HUD.

Great product.

**Comment by flightlessmango** [comment]
Can you try develop branch? Should be fixed there.

**Comment by jhu54** [comment]
Just tried develop branch and seems to be fine. One thing I struggle to get working is CPU power on Rocket Lake. Some times it displays other times it doesn't. Will install 5.13 and see if it works with that kernel.
