### ISSUE TITLE
Useless cat"s" ?

### ISSUE THREAD

**Issue by kokoko3k** [flightlessmango/MangoHud#557]
Hi,
I noticed that in several part of the code, there are something like "cat string1|grep string2"
Which can be easilly reduced to: "grep string2 string1"
Is there a reason for that?

**Comment by flightlessmango** [comment]
I don't think either should be in the code, it should be done with c/c++ instead of using programs

**Comment by gort818** [comment]
The only instances I could find where in vulkan.cpp
```
vulkan.cpp:      ram =  exec("cat /proc/meminfo | grep 'MemTotal' | awk '{print $2}'");
vulkan.cpp:      cpu =  exec("cat /proc/cpuinfo | grep 'model name' | tail -n1 | sed 's/^.*: //' | sed 's/([^)]*)/()/g' | tr -d '(/)'");
vulkan.cpp:      os = exec("cat /etc/*-release | grep 'PRETTY_NAME' | cut -d '=' -f 2-");
```

**Comment by kokoko3k** [comment]
...on top of that, i think that the rate at which some infos should be fetched should be lowered, or fetched just once.
It is not that i can switch distro on the fly or swap my cpu with a faster one  to frag more :-)

**Comment by flightlessmango** [comment]
Like what? the ones that are discussed here are only fetched once per instance

**Comment by kokoko3k** [comment]
Oh my, you're right (of course).
The whole point of this shameless bug was because for some reason i thought those infos were fetched continuously.
My sincere apologies.
