### ISSUE TITLE
Intel HD graphics not showing up

### ISSUE THREAD

**Issue by TheEpicNoobZilla** [flightlessmango/MangoHud#558]
I've installed MangoHud from Ubuntu 21.04 repo to monitor usage of CPU and GPU on some old games, but it's showing only CPU and RAM usage. I am using Intel HD 4000 (i3 3217U variant) with i915 driver (default mesa from repo). This card has partial support for Vulkan (enough to play vkQuake) and OpenGL 3.0.

Sys info:
Ubuntu MATE 21.04
i3 3217U 1,8 Ghz
Intel HD 4000
8 GB DDR3 RAM

**Comment by jackun** [comment]
Last time I checked, `i915` didn't export anything user readable or through hwmon etc. There's some stuff in /sys/kernel/debug/dri but that requires root access.

**Comment by birdie-github** [comment]
Nothing MangoHud can do, vote for https://gitlab.freedesktop.org/drm/intel/-/issues/5018

**Comment by flightlessmango** [comment]
Is being fixed here #877
