### ISSUE TITLE
Elementary OS

### ISSUE THREAD

**Issue by guschavez** [flightlessmango/MangoHud#56]
So I am using elementary os (hera) and when I try and install mangoHUD it says 

> ### # Checking Dependencies
> # Unable to find distro information!
> # Attempting to build regardless
> ./build.sh: line 112: meson: command not found
> ./build.sh: line 119: meson: command not found
> ./build.sh: line 127: ninja: command not found
> ./build.sh: line 128: ninja: command not found
> cp: cannot stat 'build/release/usr/lib32/libMangoHud.so': No such file or directory
> cp: cannot stat 'build/release/usr/lib64/libMangoHud.so': No such file or directory
> cp: cannot stat 'build/release/usr/share/vulkan/implicit_layer.d/mangohud.json': No such file or directory
> cp: cannot stat 'build/release/usr/share/vulkan/implicit_layer.d/mangohud.json': No such file or directory
> sed: can't read build/package/MangoHud/.local/share/vulkan/implicit_layer.d/mangohud32.json: No such file or directory
> sed: can't read /home/user/.local/share/vulkan/implicit_layer.d/mangohud32.json: No such file or directory
> sed: can't read /home/user/.local/share/vulkan/implicit_layer.d/mangohud64.json: No such file or directory

So it is not working and I am not sure what the dependncies are so I cant install them manually. How could I find that info?

**Comment by flightlessmango** [comment]
Since elementary is based on Ubuntu, it should have the same dependencies. you can see them in the build script under *buntu etc
https://github.com/flightlessmango/MangoHud/blob/907caa8887dde54585d2a52faf4b85d6d6f67815/build.sh#L62
