### ISSUE TITLE
Mangohud shows DXVK instead of VKD3D with Cyberpunk 2077

### ISSUE THREAD

**Issue by Ahmed-E-86** [flightlessmango/MangoHud#562]
Mangohud shows DXVK instead of VKD3D with Cyberpunk 2077. I use the latest build from master branch.

![Screenshot from 2021-06-30 01-47-46](https://user-images.githubusercontent.com/29783425/124807735-62a78e00-df5e-11eb-8598-5b70f7178445.png)

**Comment by flgx16** [comment]
Can you try with latest `develop` branch? It should be fixed there.

**Comment by Ahmed-E-86** [comment]
> Can you try building from `develop` branch? It should be fixed there.

That was quick! I will give it a try, and report back. Thanks for your reply.

**Comment by Ahmed-E-86** [comment]
> Can you try building from `develop` branch? It should be fixed there.

Develop branch works fine. Thanks for your reply.

**Comment by flgx16** [comment]
Should be fixed with MangoHud v0.6.5 release.

**Comment by Ahmed-E-86** [comment]
> Should be fixed with MangoHud v0.6.5 release.

Yes, it is fixed. Thanks!
