### ISSUE TITLE
Mangohud doesn't work for vulkan games anymore.

### ISSUE THREAD

**Issue by Toadfield** [flightlessmango/MangoHud#565]
I tried many vulkan games by starting them from steam via "MANGOHUD=1 %command%" and also non steam games,but it just doesn't work.
This is my system info:
![image](https://user-images.githubusercontent.com/68649672/125182958-be9a3d00-e212-11eb-9cfc-d67f76492764.png)

**Comment by Toadfield** [comment]
This is my mangohud config:
```
fps_limit=60
vsync=1
gl_vsync=0
legacy_layout=false
gpu_stats
gpu_temp
gpu_core_clock
gpu_mem_clock
gpu_power
gpu_text=GPU
cpu_stats
cpu_temp
core_load
cpu_power
cpu_mhz
cpu_color=2e97cb
cpu_text=CPU
io_stats
io_read
io_write
io_color=a491d3
vram
vram_color=ad64c1
ram
ram_color=c26693
fps
engine_color=eb5b5b
gpu_color=2e9762
wine_color=eb5b5b
frame_timing=0
frametime_color=00ff00
media_player_color=ffffff
no_display
background_alpha=0.4
font_size=24
background_color=020202
position=top-left
text_color=ffffff
toggle_hud=Meta_L+M
```

**Comment by Toadfield** [comment]
When I try to launch a game via "mangohud %command%" then it still doesn't work.

**Comment by flgx16** [comment]
Run `mangohud vkcube` and send the output. You need `vulkan-tools` package installed for `vkcube`.

**Comment by Toadfield** [comment]
The output is this:
```
skipping config: /usr/bin/MangoHud.conf [ not found ]
skipping config: /home/toadfield/.config/MangoHud/vkcube.conf [ not found ]
parsing config: /home/toadfield/.config/MangoHud/MangoHud.conf [ ok ]
Selected GPU 0: AMD RADV POLARIS10 (ACO), type: 2
MANGOHUD: recreating font image
sh: line 1: glxinfo: command not found
MANGOHUD: Uploading is disabled (permit_upload = 0)
MANGOHUD: recreating font image
sh: line 1: glxinfo: command not found
MANGOHUD: Uploading is disabled (permit_upload = 0)
```

**Comment by flightlessmango** [comment]
and it's not just that you have it set to be hidden when starting (`no_display`) ?

**Comment by Toadfield** [comment]
But when I press my shortcut to activate mangohud then I still can't see it,so `no_display` shouldn't be the problem.

**Comment by flightlessmango** [comment]
if it *should* be the problem or not, do the basic steps of troubleshooting and see if there's a bug there. Maybe the toggle doesn't work or something.

**Comment by Toadfield** [comment]
I deleted the mangohud config and created a new one with goverlay,when I do `mangohud vkcube` then the hud works,but when I try to start any game via `mangohud >name of the game<` then mangohud doesn't work.

**Comment by flightlessmango** [comment]
does `MANGOHUD_CONFIG=0 mangohud %command%` make it work?

**Comment by Toadfield** [comment]
no

**Comment by Toadfield** [comment]
Oh,I checked it,it works with steam games by just launching them via `mangohud %command%` now,but it doesn't work for non steam games.

**Comment by flgx16** [comment]
Try using `mangohud --dlsym` instead of `mangohud`.

**Comment by flightlessmango** [comment]
I don't think this is more than troubleshooting, there's something funky on your system. This is not what issues are for.

**Comment by guglovich** [comment]
It doesn't work with wine and steam on my Arch either. But for some reason it works with PortProton.
