### ISSUE TITLE
MangoHUD show crash with assasins creed liberation HD and IV (32bit apps - Wine 32bits prefix)

### ISSUE THREAD

**Issue by mrdeathjr28** [flightlessmango/MangoHud#567]
hi

MangoHUD show crash with assasins creed liberation HD and IV (32bit apps - Wine 32bits prefix)

however without mangohud both games work correctly

thanks

**Comment by jackun** [comment]
Can you check what the error is? Maybe something like "division by zero".

**Comment by mrdeathjr28** [comment]
> Can you check what the error is? Maybe something like "division by zero".

how?

thanks

**Comment by 241m** [comment]
I'm getting crashes with AC IV Black Flag too.

Couldn't get  autostart_log=1 to work, maybe the game crashes too early (it only shows the "intro" screen for a split second, then crashes)

I launch my steam games using a custom shell script wrapper where I set MANGOHUD=1 (plus other things). I log all output to file (linked below).

I think the relevant parts are: (around line 172)

```
--- snip ---
parsing config: /home/zaim/.config/gamehud/242050/mangohud.conf [ ok ]
sh: 1: glxinfo: not found
MANGOHUD: Uploading is disabled (permit_upload = 0)
Version: 4.6
V Black Flag\AC4BFSP.exe: ../MangoHud-0.6.5/subprojects/imgui/imgui.cpp:7056: void ImGui::ErrorCheckNewFrameSanityChecks(): Assertion `g.IO.Fonts->Fonts[0]->IsLoaded() && "Font Atlas not built. Did you call io.Fonts->GetTexDataAsRGBA32() / GetTexDataAsAlpha8()?"' failed.
wine: Assertion failed at address F7F9C549 (thread 03bc), starting debugger...
Unhandled exception: assertion failed in 32-bit code (0xf7f9c549).
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
 EIP:f7f9c549 ESP:0af7f3b0 EBP:0af7f3dc EFLAGS:00000286(   - --  I S - -P- )
 EAX:00000000 EBX:00000002 ECX:0af7f3dc EDX:00000000
 ESI:00000008 EDI:00000000
Stack dump:
0x0af7f3b0:  0af7f3dc 00000000 0af7f3dc f7be06e8
0x0af7f3c0:  00000000 f7dc9e70 00000000 f7d9be1c
0x0af7f3d0:  00010001 00000000 f7c2e945 00000000
0x0af7f3e0:  00000000 f3c00050 ffffffb0 00000000
0x0af7f3f0:  00000040 00000000 f3c00050 00000000
0x0af7f400:  f3c02d44 00000000 00000005 00000040
--- snip ---
```

Full log: [242050-1630773796.log](https://github.com/flightlessmango/MangoHud/files/7110197/242050-1630773796.log)

**Comment by jackun** [comment]
@241m do you have a custom font set in config file?

**Comment by 241m** [comment]
> @241m do you have a custom font set in config file?

Yes

**Comment by jackun** [comment]
It probably doesn't find it. Try to copy font file to $HOME somewhere or don't set.

**Comment by 241m** [comment]
Just to update: after trying to play another game, I realised this affected *all* my games, not just AC IV (was just coincidence that I saw this issue right after playing AC!)

It seems my issue might be related to #369. A game or steam update somehow changed something with the Steam Linux Runtime, I think? After using MangoHud 0.2.0 install method, everything seems to be okay.

So disregard my comments :)

Thanks!

**Comment by Leopard1907** [comment]
Mangohud works fine with runtime these days. No need to disable it or anything.

> After using MangoHud 0.2.0 install method, everything seems to be okay.

What do you mean by this? Can you elaborate?

**Comment by 241m** [comment]
Basically I did what #369 seem to suggest in point no. 5:

>  can confirm that MangoHud 0.2.0, with it's installation method, works under SLR.

So I browsed MangoHud source at v0.2.0 tag, and examined how it was installed:

1. Copy `/usr/lib/libMangoHud.so` -> `~/.local/share/MangoHud/libMangoHud.so`
2. Copy `/usr/lib32/libMangoHud.so` -> `~/.local/share/MangoHud/libMangoHud32.so`
3. Copy `/usr/share/vulkan/implicit_layer.d/MangoHud.json` -> `~/.local/share/vulkan/implicit_layer.d/mangohud{32,64}.json` (and change the value for `"library_path"` key to hardcode the respective .so file)

So my directories look like this:

```
/home/me/.local/share/MangoHud/
├── libMangoHud32.so
└── libMangoHud.so
```

```
/home/me/.local/share/vulkan/implicit_layer.d/
├── mangohud32.json
├── mangohud64.json
├── steamfossilize_i386.json
├── steamfossilize_x86_64.json
├── steamoverlay_i386.json
└── steamoverlay_x86_64.json
```

Another update: I re-tried playing some games with the above setup and they manage to launch properly, with some random crashes.

To clarify, everything was running okay previously. Issues only started when I installed and ran Assassin's Creed IV (hence me commenting on this issue).

**Comment by flightlessmango** [comment]
re-open if still an issue
