### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by wjfath** [flightlessmango/MangoHud#569]
While installing dependencies it failed here is the error I got.

Program glslangValidator found: YES (/usr/local/bin/glslangValidator)
Has header "NVCtrl/NVCtrl.h" : NO 

src/meson.build:121:6: ERROR: Problem encountered: NVCtrl.h was not found. Disable with '-Dwith_xnvctrl=disabled' if gpu stats by XNVCtrl is not needed.

**Comment by flightlessmango** [comment]
Which OS? Are you using the build script?

**Comment by ranzar** [comment]
I'm also encountering this problem. I'm using EndevourOS and I'm using the build.sh script.

**Comment by jackun** [comment]
`./build.sh clean build -Dwith_xnvctrl=disabled`

**Comment by ranzar** [comment]
Yep, that works. Much appreciated.
