### ISSUE TITLE
HUD looks like it is displayed twice

### ISSUE THREAD

**Issue by TheSyntox** [flightlessmango/MangoHud#570]
Hi and many thanks for this awesome tool.

I'm having some not critical problem here that after installing GOverlay, the HUD seems to display twice in Lutris. 
It looks like this:
![image](https://user-images.githubusercontent.com/18009352/126408133-7e8bdba6-4fd9-4c02-91a4-487c6096c559.png)

It works fine in Steam. It worked OK in Lutris before too. I reinstalled MangoHud, GOverlay I removed $HOME/.config/MangoHud/MangoHud.conf etc. I tried with and without MANGOHUD in Command prefix and MANGOHUD 1 in Environment Variables. It seemed to work fine just with FPS counter (MangoHud) option enabled.
I have no idea where else it takes the configuration from if the MangoHud.conf file is gone? I will appreciate any tips and help on this.
I use OpenSuse Tumbleweed and all apps are up to date.

Many thanks again.

**Comment by jackun** [comment]
Because you have mangohud installed twice.

**Comment by TheSyntox** [comment]
> Because you have mangohud installed twice i.e. you have two vulkan manifests in /usr/share/vulkan/implicit_layer.d/ and/or in ~/.local/share/vulkan/implicit_layer.d/

A gentleman and a scholar!

In /usr/share/vulkan/implicit_layer.d/ I had this:
MangoHud.json  MangoHud.x86_64.json.old  MangoHud.x86.json.old  vkBasalt.json  VkLayer_MESA_device_select.json
Removing MangoHud.x86_64.json and MangoHud.x86.json fixed the issue.

Many thanks!
