### ISSUE TITLE
AMD CPU speed and Power not showing correctly

### ISSUE THREAD

**Issue by damdam-kr** [flightlessmango/MangoHud#571]
Hello,
Is there a way to fix about the CPU clock speed? I manually OC'd my CPU (AMD 3900XT to 4.5 ghz) but mangohud only showing 3.8-3.9 Ghz. This is on both manual OC and stock settings.

Another one is CPU power usage is not showing at all. Only 0W.

Is there a way to fix? Thanks

**Comment by jackun** [comment]
It shows whatever is in `/proc/cpuinfo`. Try `zenpower` for power usage as default module got that feature removed iirc.

**Comment by damdam-kr** [comment]
> It shows whatever is in `/proc/cpuinfo`. Try `zenpower` for power usage as default module got that feature removed iirc. These may or may not be accurate though.

oh thanks
