### ISSUE TITLE
Detecting and showing Virtual Programming's eON

### ISSUE THREAD

**Issue by Faalagorn** [flightlessmango/MangoHud#572]
Since wrappers such as Feral's _Feral3D_ and Valve's _ToGL_ are detected, would it be possible to detect Virtual Programming's eON wrapper as well?

**Comment by gort818** [comment]
Which games use that wrapper?

**Comment by Faalagorn** [comment]
> Which games use that wrapper?

From the one I played, Spec Ops The Line, Witcher 2 and most likely all other Linux games they ported: https://www.pcgamingwiki.com/wiki/Company:Virtual_Programming#Games_ported_to_Linux

Some of the Mac games ported by them used it too, but sometimes a Linux version of said game might not use eON apparently (Dead Island: https://www.gamingonlinux.com/2014/10/dead-island-zombie-game-now-available-on-linux-for-some-updated).

**Comment by gort818** [comment]
Ok nice I have a few of those, I will see what I can do.

**Comment by gort818** [comment]
The only thing I could find common between most of the titles listed here  https://www.pcgamingwiki.com/wiki/Company:Virtual_Programming#Games_ported_to_Linux 

is `libopenal-eon.so.1` to check if it using eON. 

Unfortunately some of those games do not have anything mentioning eON.

Spec Ops, Witcher 2, Dirt, BioShock, Saints Row games seem to have it. Gravel and the ARMA games do not.

Here is the ARMA 3 Linux depot for example https://steamdb.info/depot/249507/

But anyway here is Spec Ops:

![Screenshot_20210724_202831](https://user-images.githubusercontent.com/9098121/126886833-2ea9df21-18c1-4bd4-a6c0-bfccbf974920.jpeg)

**Comment by Faalagorn** [comment]
> The only thing I could find common between most of the titles listed here https://www.pcgamingwiki.com/wiki/Company:Virtual_Programming#Games_ported_to_Linux
> 
> is `libopenal-eon.so.1` to check if it using eON.
> 
> Unfortunately some of those games do not have anything mentioning eON.
> 
> Spec Ops, Witcher 2, Dirt, BioShock, Saints Row games seem to have it. Gravel and the ARMA games do not.
> 
> Here is the ARMA 3 Linux depot for example https://steamdb.info/depot/249507/

It'd require some research, but honestly, it'd make sense if those games weren't eON. Both ARMAs and Gravel are their new ports, so maybe they stopped using eON, as it had it's limits when it comes to performance.

Either way, great work! Do you have the patch/fork with the patches so it can be tested? I could try to see how itworks for me this way.

**Comment by gort818** [comment]
Here is the patch.. based off the develop branch
[eon.patch.txt](https://github.com/flightlessmango/MangoHud/files/6889997/eon.patch.txt)

**Comment by Faalagorn** [comment]
> Here is the patch.. based off the develop branch
> [eon.patch.txt](https://github.com/flightlessmango/MangoHud/files/6889997/eon.patch.txt)

Took me a little to test it out, but it works for Spec Ops for me as well! I recently changed to apply `SDL_VIDEODRIVER=wayland` on start and for some reason, the mangohud wouldn't show until I put `SDL_VIDEODRIVER=x11` in front of the launch, but that's unrelated and deem for a different one I guess.

Here's the screenshot of eOS being detected in Spec Ops: The Line – do you want me to test anything else and if not, will you write a PR to include that in master since I guess it doesn't do any harm? @gort818 
![screenshot_2021-08-16-002411](https://user-images.githubusercontent.com/4951331/129494524-fad2f19a-b09f-4051-ab8f-cb5063bed4d3.png)

**Comment by kimjongal** [comment]
@gort818 hello i think it would be easy
the main thread/process in all eon games is always called E.runloop
