### ISSUE TITLE
pacman - not syncing repositories

### ISSUE THREAD

**Issue by PietJanHein** [flightlessmango/MangoHud#574]
First of all, this is a great project, I highly recommend this program. I noticed a little problem. While building MangoHud it had to install dependencies. All good but that failed because the repositories were out of sync. This happens a lot on Arch, in my particular case the install was only 2 days old, I synced the repositories in another instance of the terminal and the install could continue. I think that it would be a good idea to add `pacman -Syy`  to the script for Arch and then this would not be a problem anymore. Granted, this is first and foremost the user his responsibility, especially when he uses Arch, but it would help, especially for new users. At least the attempt to install the dependencies does time out and offer the install again if this problem occurs. Alternatively in the README on Github you could mention the dependencies at the beginning under the build-header.

**Comment by flightlessmango** [comment]
This should only be done by the user
