### ISSUE TITLE
Rise of the Tomb Raider - segmentation fault at launch but only if `mangohud %command%` added to launch options

### ISSUE THREAD

**Issue by PietJanHein** [flightlessmango/MangoHud#575]
I installed the game natively, I can run the game fine but when I try to run the game with MangoHud I get the error message which you can see in the attachment. 
![crash](https://user-images.githubusercontent.com/38538461/127052601-bf6fbd7a-a152-4e93-ba21-98b6dbd74403.png)
On this screenshot you see me also use gamemoderun, I tried it out with just `mangohud %command%` first.
Obviously I did verify that mangohud is working properly otherwise, when I launch other games then the game does start with MangoHud working.

**Comment by jackun** [comment]
Annoyingly, works for me :tm:  You could try `STEAM_RUNTIME=0 steam` or running the game with Steam Linux Runtime.


But afaik you don't need gamemoderun, newer Feral games already run with it itself.
