### ISSUE TITLE
MangoHud affecting Minecraft performance

### ISSUE THREAD

**Issue by Acvale** [flightlessmango/MangoHud#576]
Running Minecraft via Lunar Client with MangoHud enabled, through the command "mangohud --dlsym lunarclient", significantly reduces the framerate. In Low resolutions, the game reaches 1000+ FPS values without MangoHud, whereas with the tool, it doesn't go past 600 FPS.

System Specs:
Lenovo Ideapad 330
5.10.52-1-MANJARO Xfce
Intel i7 8550u
Nvidia GeForce MX150
Display Resolution - 1280 x 1024 (external monitor)

![mine1](https://user-images.githubusercontent.com/82143654/127069902-8c0717a2-8880-466e-b712-714e3a180041.png)
![3](https://user-images.githubusercontent.com/82143654/127070068-6640bc06-3e6a-40e3-b679-8632f683838c.png)

**Comment by jackun** [comment]
Try this:
[MangoHud-b20d249.tar.gz](https://github.com/flightlessmango/MangoHud/files/6910193/MangoHud-b20d249.tar.gz)

**Comment by flightlessmango** [comment]
This should be fixed
