### ISSUE TITLE
Some games only displaying x options

### ISSUE THREAD

**Issue by xamzy** [flightlessmango/MangoHud#578]
I don't think this is an issue with MangoHUD or Goverlay itself, but I thought it the best place to ask a question regarding it. 

It seems like certain games work just fine with it, displaying what I've asked it to display: 
GPU: Avg Load / Temp / VRAM/ Model 
CPU: Avg Load / Temp / RAM

However some other games only display the following: 
GPU: VRAM
CPU: Avg Load / Temp / RAM 
FPS & Frame times. 

However since it's not displaying the first set of things which I've selected, it makes me wonder if I'm just doing something wrong? 
Any tips much appreciated :)

**Comment by TheComputerGuy96** [comment]
@xamzy Are the games that display limited GPU info 32-bit?
