### ISSUE TITLE
Memory Leak: exec doesn't quit

### ISSUE THREAD

**Issue by sergen213** [flightlessmango/MangoHud#579]
Hello,
Thank you for creating this tool for Linux Gamers.
I couldn't decide where to submit this issue here or Goverlay but it has something to do with Distro info config. If I enable distro version in the config it causes a memory leak. It tries to get distro info with lsb_release -a command and task manager gets flooded with this command and filling all the ram with this command until there is none and crashes the game I couldn't take a screenshot of it because it freezes my PC but after disabling distro version config there is no issue. Should I submit it to Goverlay as well ?

Thanks

**Comment by sergen213** [comment]
![20210730225236_1](https://user-images.githubusercontent.com/20866366/127719206-86692fd0-17bd-4c3a-afcf-50d47d7750a1.jpg)
![Screenshot_2021-07-30_22-53-06](https://user-images.githubusercontent.com/20866366/127719209-746e9da8-f828-4a77-9b96-9a427a957825.png)
I was able to take a screenshot

**Comment by sergen213** [comment]
And this is without distro info

![20210730225850_1](https://user-images.githubusercontent.com/20866366/127719367-12d4ee0e-66f3-4173-9d55-2bd6d6f49f1c.jpg)
![Screenshot_2021-07-30_22-59-11](https://user-images.githubusercontent.com/20866366/127719372-65261b4d-46be-4597-a88e-ce3a6e6a48a8.png)

**Comment by gort818** [comment]
I do not use Goverlay, but can you disable those options and just add this to your MangoHud.conf file and see if you experience the same issue?
```
custom_text=Distro
exec=lsb_release -a | grep  Description | cut -c 14-26
```
I just tested and had no issues

**Comment by sergen213** [comment]
> I do not use Goverlay, but can you disable those options and just add this to your MangoHud.conf file and see if you experience the same issue?
> 
> ```
> custom_text=Distro
> exec=lsb_release -a | grep  Description | cut -c 14-26
> ```
> 
> I just tested and had no issues

Thank you for your reply but still same. I'll disable it. I was just using it for the screenshots.

![Screenshot_2021-07-31_11-22-44](https://user-images.githubusercontent.com/20866366/127738353-f10bd5ad-64ed-449e-9ae0-263377f43ede.png)

**Comment by jackun** [comment]
If you run that `lsb_release | grep` etc command manually, does it exit?

**Comment by sergen213** [comment]
![Screenshot_2021-07-31_12-30-42](https://user-images.githubusercontent.com/20866366/127739936-586d0300-4f06-445d-baca-fe5037b2caff.png)

Yeah it exits.

**Comment by flightlessmango** [comment]
This should be fixed in master
