### ISSUE TITLE
Not worked with Yuzu

### ISSUE THREAD

**Issue by varlesh** [flightlessmango/MangoHud#581]
I tried more versions, it's not worked. But Ryujinx worked fine.
LOG:
```
mangohud /home/alex/Applications/yuzu-20210730-cad9b5094_8b5e5deecf4588a9a3b30f8c87037c29.AppImage
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
```
Yuzu: 636-6736 (20210730)
MangoHud-0.6.2.r1.g94dda24
Ubuntu 20.04

Also, mostly emulators distributed as flatpak. Maybe it's will be possible use MangoHud for flatpak apps?
```
dolphin - flatpak, snap (not actual)
yuzu - flatpak, appimage
ryujinx - appimage
citra - flatpak, snap
snes9x - flatpak
melonDS - flatpak, snap
mgba - flatpak, snap
pcsx2 - flatpak
rpcs3 - flatpak, snap
xenia - compile from sources
```

**Comment by varlesh** [comment]
env variables `MANGOHUD_DLSYM=1` & `MANGOHUD=1` added on ~/.profile

**Comment by jackun** [comment]
Use vulkan backend. OpenGL "works", it loads and seems to render hud though it doesn't appear on screen :unamused:

**Comment by varlesh** [comment]
Yes, worked with vulkan. How about flatpak apps?

**Comment by Heath123** [comment]
> Use vulkan backend. OpenGL "works", it loads and seems to render hud though it doesn't appear on screen 😒

I get better performance with OpenGL

**Comment by ruizlenato** [comment]
same problem

**Comment by edubr029** [comment]
same problem on Arch Linux with **yuzu-early-access** AUR package, even with `MANGOHUD_DLSYM=1` or `mangohud --dlsym`, MangoHUD does not show up in OpenGL

**Comment by feliciaifu** [comment]
same problem

**Comment by bigoulours** [comment]
same here on arch, using yuzu-mainline-bin. Works fine with Vulkan but doesn't with OpenGL, even with --dlsym

**Comment by bigoulours** [comment]
I could fix this by uncommenting the line gl_bind_framebuffer=0 in the config file

**Comment by tuxtergames** [comment]
any fix for this? I have tested with MANGOHUD_DLSYM=1 & MANGOHUD=1 in ~/.bashrc for RPCS3, it works just if I ran from terminal, but emulator crash after a few time, any tips?

**Comment by lodgerz** [comment]
> I could fix this by uncommenting the line gl_bind_framebuffer=0 in the config file

it doesn't work. someone can fix it?

**Comment by flightlessmango** [comment]
![image](https://github.com/flightlessmango/MangoHud/assets/42713625/87b1116a-befb-45b2-ab51-b3481ebee5cc)
Works fine on my end on latest git
