### ISSUE TITLE
[Feature Request] Proton Version and FSR ON/OFF indicator

### ISSUE THREAD

**Issue by ekianjo** [flightlessmango/MangoHud#586]
Fairly explicit, would be useful when doing video capture to confirm whether or not FSR is activated.

**Comment by Mershl** [comment]
An FSR active/inactive indicator would be really helpful.

**Comment by gort818** [comment]
We already have proton version.. the parameter is `wine`.
For FSR are you talking about the experimental fshack patch  or the one included in games?

**Comment by ekianjo** [comment]
Sorry if I was not specific enough, I am talking about fshack that's been included in recent ProtonGE versions

**Comment by kajlamo** [comment]
+1Please.

**Comment by lukashoracek** [comment]
I'm not sure if MangoHud can detect the patched wine/proton's FSR. And even if it did MangoHud would also have to be able to detect games actually using FSR properly themselves

**Comment by kajlamo** [comment]
So currently the best way to check if FSR's working is to show the resolution using MangoHud which should display native and in-game lower should display also as native.

**Comment by flightlessmango** [comment]
> So currently the best way to check if FSR's working is to show the resolution using MangoHud which should display native and in-game lower should display as native
> Example:
> ![Untitled](https://user-images.githubusercontent.com/86540370/131346475-bea97b9c-3ac4-4208-b9be-1856d835697d.png)

How would you find out what the native resolution is?

**Comment by kajlamo** [comment]
In fullscreen MangoHud overlay shows me 1920p which is my native resolution and if FSR is running and the game is set to say 720p it shows up as native as resolution of my monitor (in-game) and it's then upscaled.
Without FSR my display resolution just switches to 720p and MangoHud shows that resolution instead.
https://youtu.be/xO4jG6pppTA?t=334

**Comment by lukashoracek** [comment]
Some games upscale frames themselves so wine/proton's FSR patch won't apply FSR. In that case in-game resolution can be different from display resolution and the frame won't be upscaled using FSR upscaling but rather using the game's built-in upscaling.

**Comment by Zeioth** [comment]
I just noticed SteamDeck forked mangohud and added this feature. Would it be too wild to bring it here?

**Comment by flightlessmango** [comment]
> I just noticed SteamDeck forked mangohud and added this feature. Would it be too wild to bring it here?

Steamdeck/steamos3 does not use a fork of mangohud, it uses an application called mangoapp which is developed here as well. 
Mangoapp and mangohud have different use-cases and different set of features. The main purpose of mangoapp is to act as a layer on top of gamescope and directly communicate with gamescope for it's frametimes and states like FSR (mangoapp can't detect proton fsr, just gamescope's fsr).
Since the FSR feature completely depends on gamescope it's not possible to add it to normal mangohud.

**Comment by flightlessmango** [comment]
wine/proton version option exists and FSR status is not possible outside of gamescope

**Comment by dcog989** [comment]
> the FSR feature completely depends on gamescope

Still true today, I presume? 

Would it be possible to disable / hide the feature in mangohud if not running gamescope? Might save others from spending an hour or so trying to get it to work! ... Happy to raise an issue if you want.

**Comment by flightlessmango** [comment]
We already hide the FSR status unless gamescope exposes the relevant information, unless I'm overlooking something

**Comment by dcog989** [comment]
Hi. I'm referring to the settings switch in goverlay > mangohud. Or is that specific to goverlay?

So, I check `FSR*` in goverlay > mangohud, I'm running FSR, but see no FSR indicator. That sent me on a goose chase and ended up here.

**Comment by flightlessmango** [comment]
That would be specific to goverlay, but goverlay can't know if you're going to use gamescope. You could ask them to add a warning tooltip for those options or something similar

**Comment by dcog989** [comment]
Got it. Thanks for clearing that up.
