### ISSUE TITLE
Doesn't work with Splitgate (UnrealEngine 4) game

### ISSUE THREAD

**Issue by iMonZ** [flightlessmango/MangoHud#589]
Operating System: Manjaro
Kernel: 5.13.8-1-MANJARO
Compositor: [Gamescope](https://github.com/Plagman/gamescope)
Display: [Wayland](https://wayland.freedesktop.org/)
Crashlog: https://pastebin.com/R85Dbrv1

**Comment by Azel04** [comment]
Same problem here
5.13.11-1-MANJARO

**Comment by loudan-arc** [comment]
Can attest to this still happening in Mangohud 0.65 Release on Pop! OS 20.10. I understand I can update to a newer version but currently do not have much plans yet. The game simply doesn't load when using "mangohud %command%" or any other variation of it.

**Comment by flightlessmango** [comment]
943403308333897cde5023f27cc0b2e4515e8cb2 this commit fixes splitgate for me
This seems to be AMD related in the mangohud code so I'm curious to if NVIDIA users are having this issue and if so I would be interested in further logs

**Comment by ishitatsuyuki** [comment]
Looking at the fix and the crash backtrace [this](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=66145) might be related.

I suspect it's a libstdc++ ABI issue.
