### ISSUE TITLE
 Doesn't work with Disney Classic Games: Aladdin and The Lion King (OpenGL 32 bit) game 

### ISSUE THREAD

**Issue by xcom169** [flightlessmango/MangoHud#590]
Hello!

I installed MangoHud on my system, but for this particular game the HUD doesn't show up. 
I use the latest stable official Proton to run it on my Ubuntu LTS 20.04 . 
It uses glew32.dll for openGL.
AppID: 1126190

**Comment by jackun** [comment]
Common issue, actually have 32bit MangoHud installed? :smiley_cat:

**Comment by xcom169** [comment]
I used mangohud.sh install  from the tarball. I think it installs both 32, 64 versions. 

Thanks I'll try gl_bind_framebuffer=0 .

**Comment by flightlessmango** [comment]
reopen if still an issue
