### ISSUE TITLE
Segfault on launch with Could not find cpu temp sensor location

### ISSUE THREAD

**Issue by dominalien** [flightlessmango/MangoHud#60]
Mangohud 0.3.0 downloaded from Releases, installed without problems. Ubuntu 19.10, MacBookPro 6,2, Core i7-620M, nVidia Geforce GT 330M driver 340.107. As you can see, there's no Vulkan here. I'm trying to run Mangohud with Doom 3 via dhewm3 in 64-bit mode. Doom itself runs fine.

After it failed the first time I installed lm-sensors and did sensors-detect and then modprobed coretemp, no improvement. Running sensors shows a bunch of temps.

I tried disabling cpu_stats in the config file but it didn't help.

Am I missing something or is this possibly a bug? I'll happily provide any and all info to help fix it. Thanks.

**Comment by flightlessmango** [comment]
can you run `gdb dhewm3` and press `r`, this output might shed some more light on what's going wrong

**Comment by dominalien** [comment]
Here you go:
`GNU gdb (Ubuntu 8.3-0ubuntu1) 8.3
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from dhewm3...
(No debugging symbols found in dhewm3)
(gdb) r
Starting program: /home/domin/Gry/Doom3/dhewm3 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff4e8e700 (LWP 7619)]
dhewm3 1.5.0.1304 linux-x86_64 Dec 15 2018 03:06:01 using SDL v2.0.10
WARNING: terminal type 'xterm-256color' is unknown. terminal support may not work correctly
terminal support enabled ( use +set in_tty 0 to disable )
pid: 7615
7888 MB System Memory
found interface lo - loopback
found interface wlp3s0b1 - 192.168.1.10/255.255.255.0
doom using MMX & SSE & SSE2 for SIMD processing
enabling Flush-To-Zero mode
enabling Denormals-Are-Zero mode
WARNING: base path '/usr/local/share/dhewm3' does not exist
WARNING: using path of executable: /home/domin/Gry/Doom3
----- Initializing File System -----
Loaded pk4 /home/domin/Gry/Doom3/base/pak000.pk4 with checksum 0x28d208f1
Loaded pk4 /home/domin/Gry/Doom3/base/pak001.pk4 with checksum 0x40244be0
Loaded pk4 /home/domin/Gry/Doom3/base/pak002.pk4 with checksum 0xc51ecdcd
Loaded pk4 /home/domin/Gry/Doom3/base/pak003.pk4 with checksum 0xcd79d028
Loaded pk4 /home/domin/Gry/Doom3/base/pak004.pk4 with checksum 0x765e4f8b
Loaded pk4 /home/domin/Gry/Doom3/base/pak005.pk4 with checksum 0x8ffc3621
Loaded pk4 /home/domin/Gry/Doom3/base/pak006.pk4 with checksum 0x95b65ab
Loaded pk4 /home/domin/Gry/Doom3/base/pak007.pk4 with checksum 0x666bdb3c
Loaded pk4 /home/domin/Gry/Doom3/base/pak008.pk4 with checksum 0x23ae5993
Current search path:
/home/domin/.config/dhewm3/base
/home/domin/.local/share/dhewm3/base
/home/domin/Gry/Doom3/base
/home/domin/Gry/Doom3/base/pak008.pk4 (3 files)
/home/domin/Gry/Doom3/base/pak007.pk4 (38 files)
/home/domin/Gry/Doom3/base/pak006.pk4 (48 files)
/home/domin/Gry/Doom3/base/pak005.pk4 (63 files)
/home/domin/Gry/Doom3/base/pak004.pk4 (5137 files)
/home/domin/Gry/Doom3/base/pak003.pk4 (4676 files)
/home/domin/Gry/Doom3/base/pak002.pk4 (6120 files)
/home/domin/Gry/Doom3/base/pak001.pk4 (8972 files)
/home/domin/Gry/Doom3/base/pak000.pk4 (2698 files)
Addon pk4s:
[New Thread 0x7ffff1253700 (LWP 7626)]
----- Initializing Decls -----
5206 strings read from strings/english.lang
Couldn't open journal files
execing editor.cfg
execing default.cfg
execing dhewm.cfg
couldn't exec autoexec.cfg
5206 strings read from strings/english.lang
----- Initializing OpenAL -----
Setup OpenAL device and context
[New Thread 0x7ffff0a09700 (LWP 7627)]
[Thread 0x7ffff0a09700 (LWP 7627) exited]
[New Thread 0x7ffff0988700 (LWP 7628)]
[Thread 0x7ffff0988700 (LWP 7628) exited]
[New Thread 0x7ffff0988700 (LWP 7629)]
OpenAL: found device 'Wbudowany dźwięk Analogowe stereo'
[Thread 0x7ffff0988700 (LWP 7629) exited]
[New Thread 0x7ffff0988700 (LWP 7630)]
[New Thread 0x7fffdbfff700 (LWP 7631)]
[New Thread 0x7fffdb5d7700 (LWP 7632)]
OpenAL vendor: OpenAL Community
OpenAL renderer: OpenAL Soft
OpenAL version: 1.1 ALSOFT 1.19.1
OpenAL: found EFX extension
OpenAL: found 256 hardware voices
----- Initializing OpenGL -----
Initializing OpenGL subsystem
Using 8 color bits, 24 depth, 8 stencil display
OpenGL vendor: NVIDIA Corporation
OpenGL renderer: GeForce GT 330M/PCIe/SSE2
OpenGL version: 3.3.0 NVIDIA 340.107
...using GL_ARB_multitexture
...using GL_ARB_texture_env_combine
...using GL_ARB_texture_cube_map
...using GL_ARB_texture_env_dot3
...using GL_ARB_texture_env_add
...using GL_ARB_texture_non_power_of_two
...using GL_ARB_texture_compression
...using GL_EXT_texture_compression_s3tc
...using GL_EXT_texture_filter_anisotropic
   maxTextureAnisotropy: 16.000000
...using GL_1.4_texture_lod_bias
X..GL_EXT_shared_texture_palette not found
...using GL_EXT_texture3D
...using GL_EXT_stencil_wrap
...using GL_EXT_stencil_two_side
...using GL_ARB_vertex_buffer_object
...using GL_ARB_vertex_program
...using GL_ARB_fragment_program
...using EXT_depth_bounds_test
ARB2 renderer: Available.
----- R_ReloadARBPrograms -----
glprogs/test.vfp
glprogs/test.vfp
glprogs/interaction.vfp
glprogs/interaction.vfp
glprogs/bumpyEnvironment.vfp
glprogs/bumpyEnvironment.vfp
glprogs/ambientLight.vfp
glprogs/ambientLight.vfp
glprogs/shadow.vp
glprogs/environment.vfp
glprogs/environment.vfp
glprogs/arbVP_glasswarp.txt: File not found
glprogs/arbFP_glasswarp.txt: File not found
using ARB_vertex_buffer_object memory
using ARB2 renderSystem
loaded game library '/home/domin/Gry/Doom3/base.so'.
game using MMX & SSE & SSE2 for SIMD processing
Flush-To-Zero mode is already enabled
Denormals-Are-Zero mode is already enabled
----- Initializing Game -----
gamename: baseDOOM-1
gamedate: Dec 15 2018
Initializing event system
...473 event definitions
Initializing class hierarchy
...142 classes, 764368 bytes for event callbacks
Initializing scripts
Compiled 'weapon_fists::GetFireAnim': 876 ms
----- Compile stats -----
Memory usage:
     Strings: 79, 13232 bytes
  Statements: 67875, 2715000 bytes
   Functions: 2109, 318020 bytes
   Variables: 170888 bytes
    Mem used: 4483712 bytes
 Static data: 4214344 bytes
   Allocated: 5768260 bytes
 Thread size: 14056 bytes
...6 aas types
----- Initializing Session -----
----- Warnings -----
during dhewm 3 initialization...
WARNING: base path '/usr/local/share/dhewm3' does not exist
WARNING: using path of executable: /home/domin/Gry/Doom3
2 warnings
----- Game Map Shutdown -----
Shutting down sound hardware
[Thread 0x7fffdb5d7700 (LWP 7632) exited]
[Thread 0x7fffdbfff700 (LWP 7631) exited]
idRenderSystem::Shutdown()
Shutting down OpenGL subsystem
----- Game Shutdown -----
----- Game Map Shutdown -----
Shutdown event system
[Thread 0x7ffff1253700 (LWP 7626) exited]
shutdown terminal support
[Thread 0x7ffff4e8e700 (LWP 7619) exited]
[Inferior 1 (process 7615) exited normally]`

This happens with a few games I've tried: Myth 2, Pillars of Eternity. None of them work. Pillars doesn't show the message about cpu tem sensor, but crashes right after starting. They all work without mangohud.

**Comment by jackun** [comment]
Did you also enable MangoHud? gdb log doesn't show anything crashing.

**Comment by dominalien** [comment]
As in mangohud gdb ./dhewm3? That's not what flightlessmango said, but here:
```
(gdb) r
Starting program: /home/domin/Gry/Doom3/dhewm3 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff4b60700 (LWP 11120)]
MANGOHUD: Could not find cpu temp sensor location

Thread 1 "dhewm3" received signal SIGSEGV, Segmentation fault.
0x00007ffff6c33a7d in __GI_rewind (fp=0x0) at rewind.c:34
34	rewind.c: Nie ma takiego pliku ani katalogu.
```
The last line says "no such file or directory". packages.ubuntu.com says there's no package that would contain a file rewind.c and mangohud seems to contain no file by that name either. I also don't have a file by that name on my computer.

**Comment by flightlessmango** [comment]
what distro are you on?

**Comment by dominalien** [comment]
Ubuntu 19.10

**Comment by flightlessmango** [comment]
https://flightlessmango.com/MangoHud-0.3.0.r15.g64a42df.tar.gz
see if this version still crashes

**Comment by dominalien** [comment]
```
MANGOHUD: Could not find cpu temp sensor location
skipping config: /home/domin/Gry/Doom3/MangoHud.conf [ not found ]
skipping config: /home/domin/.config/MangoHud/dhewm3.conf [ not found ]
parsing config: /home/domin/.config/MangoHud/MangoHud.conf [ ok ]
MANGOHUD: Failed to get function 'glCreateSyncFromCLeventARB'
```

**Comment by dominalien** [comment]
Pillars of Eternity:

```
domin@pupiaque3-ubuntu:~/GOG Games/Pillars of Eternity$ mangohud ./start.sh 
XIO:  fatal IO error 9 (Błędny deskryptor pliku) on X server ":1"
      after 8 requests (8 known processed) with 0 events remaining.
XIO:  fatal IO error 9 (Błędny deskryptor pliku) on X server ":1"
      after 8 requests (8 known processed) with 0 events remaining.
XIO:  fatal IO error 9 (Błędny deskryptor pliku) on X server ":1"
      after 8 requests (8 known processed) with 0 events remaining.
Running Pillars of Eternity
Set current directory to /home/domin/GOG Games/Pillars of Eternity/game
Found path: /home/domin/GOG Games/Pillars of Eternity/game/PillarsOfEternity
Mono path[0] = '/home/domin/GOG Games/Pillars of Eternity/game/PillarsOfEternity_Data/Managed'
Mono path[1] = '/home/domin/GOG Games/Pillars of Eternity/game/PillarsOfEternity_Data/Mono'
Mono config path = '/home/domin/GOG Games/Pillars of Eternity/game/PillarsOfEternity_Data/Mono/etc'
/dev/input/js0: driver version: 2.1.0 (20100)
/dev/input/js0: fd 4, buttons 0, axes 2, name applesmc
/dev/input/js0: axis  0: raw      0, mapped 0.000000
/dev/input/js0: axis  1: raw   -133, mapped 0.000000
XIO:  fatal IO error 0 (Sukces) on X server ":1"
      after 8 requests (8 known processed) with 0 events remaining.
```

The three errors at the top are "bad file descriptor"

**Comment by dominalien** [comment]
Pillars without mangohud:

```
domin@pupiaque3-ubuntu:~/GOG Games/Pillars of Eternity$ ./start.sh 
Running Pillars of Eternity
Set current directory to /home/domin/GOG Games/Pillars of Eternity/game
Found path: /home/domin/GOG Games/Pillars of Eternity/game/PillarsOfEternity
Mono path[0] = '/home/domin/GOG Games/Pillars of Eternity/game/PillarsOfEternity_Data/Managed'
Mono path[1] = '/home/domin/GOG Games/Pillars of Eternity/game/PillarsOfEternity_Data/Mono'
Mono config path = '/home/domin/GOG Games/Pillars of Eternity/game/PillarsOfEternity_Data/Mono/etc'
/dev/input/js0: driver version: 2.1.0 (20100)
/dev/input/js0: fd 3, buttons 0, axes 2, name applesmc
/dev/input/js0: axis  0: raw      0, mapped 0.000000
/dev/input/js0: axis  1: raw   -133, mapped 0.000000
```

**Comment by flightlessmango** [comment]
have you tried with just glxgears? `mangohud glxgears`

**Comment by dominalien** [comment]
It crashes just after opening the window:

```
domin@pupiaque3-ubuntu:~$ mangohud glxgears
MANGOHUD: Could not find cpu temp sensor location
skipping config: /usr/bin/MangoHud.conf [ not found ]
skipping config: /home/domin/.config/MangoHud/glxgears.conf [ not found ]
parsing config: /home/domin/.config/MangoHud/MangoHud.conf [ ok ]
MANGOHUD: Failed to get function 'glCreateSyncFromCLeventARB'

```

**Comment by dominalien** [comment]
Not much different with gdb:
```
domin@pupiaque3-ubuntu:~$ mangohud gdb glxgears
...
(gdb) r
Starting program: /usr/bin/glxgears 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
MANGOHUD: Could not find cpu temp sensor location
skipping config: /usr/bin/MangoHud.conf [ not found ]
skipping config: /home/domin/.config/MangoHud/glxgears.conf [ not found ]
parsing config: /home/domin/.config/MangoHud/MangoHud.conf [ ok ]
[Detaching after vfork from child process 6841]
[Detaching after vfork from child process 6845]
[Detaching after vfork from child process 6852]
[Detaching after vfork from child process 6854]
[Detaching after vfork from child process 6858]
[Detaching after vfork from child process 6865]
MANGOHUD: Failed to get function 'glCreateSyncFromCLeventARB'
[Inferior 1 (process 6837) exited with code 01]
```

**Comment by flightlessmango** [comment]
I'm pretty much grasping at straws here but, the card is very old and the drivers too. Would it make any difference if you changed to the Nouveau driver?

**Comment by dominalien** [comment]
I'm sure it would: I wouldn't be able to play any games. No matter, I'll just have to go without MangoHud. Thank you very much for your assistance. :-)

**Comment by Generator** [comment]
Same issue here: 
Tested with https://github.com/flightlessmango/PKGBUILDS
`pkgver=0.3.0.r22.g48697f5`

CPU: Core 2 Duo E7600

```
$ MANGOHUD=1 MANGOHUD_CONFIG=full gdb vkcube
...
Starting program: /usr/bin/vkcube 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
failed to initialize wayland, falling back to xcb
MANGOHUD: Could not find cpu temp sensor location

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7c23f2d in rewind () from /usr/lib/libc.so.6
```


No issues with MangoHUD<=0.2.0

**Comment by flightlessmango** [comment]
@Generator I think this has been fixed in the develop branch, try this package [MangoHud-latest.tar.gz](https://flightlessmango.com/MangoHud-latest.tar.gz)

**Comment by Generator** [comment]
I can confirm it, working with with develop branch
