### ISSUE TITLE
Mangohud all blank or not working.

### ISSUE THREAD

**Issue by jatin-cbs** [flightlessmango/MangoHud#602]
Distro - Arch Linux
Mangohud release - 0.6.5
GPU - 5700xt on mesa 21.2.1

I Installed mangohud from the AUR.. and in games it is only showing a blank rectangle - Proton Version - Proton-6.16-GE-1  in the top right -

![mangohud_glitch](https://user-images.githubusercontent.com/40650341/133041660-4c0e577b-507b-418e-99a4-27e509fec2e3.png)

Also in games like payday 2 it is not launching the game when the mangohud launch option is used. Maybe something specific to OpenGL games.

**Comment by jatin-cbs** [comment]
Fixed it (was some dependency issue.)

**Comment by jackun** [comment]
> dependency issue

Which was what? Should've at least shown default layout, weird.
