### ISSUE TITLE
Configuration files are not loaded if MangoHud folder is symlinked

### ISSUE THREAD

**Issue by arlyoneel** [flightlessmango/MangoHud#603]
Hi I found that If I use a symlink instead of a real folder  configuration files are not loaded

with symlink:
`skipping config: /home/<user>/.config/MangoHud/wine-fm.conf [ not found ]
`
without symlink:
`parsing config: /home/<user>/.config/MangoHud/wine-fm.conf [ ok ]
`
Why you want to symlink this folder?
I store custom configurations of everything in a private repository, I got many computers and I share many configurations to write just once.

**Comment by jackun** [comment]
Symbolic links are "weak" and lose meaning inside Steam's sandbox. Nothing MangoHud can do about it.
