### ISSUE TITLE
Ubuntu PPA does not offer 32-bit support and does not even mention it lacks support in the readme

### ISSUE THREAD

**Issue by ChaosBlades** [flightlessmango/MangoHud#606]
I had to spend some time trying to figure out why SWTOR was not working with MangoHud. Turns out MangoHud installed from the PPA does not offer 32-bit support. This does not seem to be mentioned anywhere except a couple of random reddit posts.

It would be nice if we could get this resolved and have the Ubuntu PPA install the 32-bit version along side the 64-bit one. 

In the short term we can at least mention on the readme you will need to download MangoHud from the releases tab and run `./mangohud-setup.sh install` in order to enable 32-bit support.

**Comment by flightlessmango** [comment]
We're not the maintainers of the PPA

**Comment by ChaosBlades** [comment]
But you are maintainers of the MangoHud readme that does not mention installing MangoHud via this method only provides 64-bit support.

**Comment by ChaosBlades** [comment]
I messaged Martin Wimpress via launchpad to hopefully get this resolved. Will update if I get anything back.

**Comment by ChaosBlades** [comment]
I did get a response from Martin...

> No, 32bit x86 is not a supported architecture in Ubuntu for some years now

Which makes me think he thought I asked for Ubuntu 32-Bit support and not MangoHud 32-bit support on 64-bit Ubuntu. I replied back as such, the reasons why we need 32-bit MangoHud support, and have not gotten a response back after 2 days. Which makes me think I have been ghosted.

@flightlessmango Can you add some text to the ReadMe that the Ubuntu PPA does not support MangoHud on any 32-bit games when installed via the PPA? Honestly I don't see the point in even putting the PPA in the ReadMe anymore as installing MangoHud from it would cause MangoHud to ramdomly not work on certain games while the user does not know why. Not sure how many games are still being published as 32-bit. I would not put it past some emulators and indie games. I guess it is your call on what you want to do.

**Comment by berglh** [comment]
I needed this build to fix Quake Champions to work with MangoHud, this didn't work with the APT repo version of MangoHud. Nevertheless, it was asking for `glslang` on `impish`, even though the `PKGBUILD` did have build dep variables for `impish`, not sure if there is a `makedeb -si` switch for specifying `impish` build instead of normal. Thanks.

**Comment by zocker-160** [comment]
@berglh this is sadly a bug in makedeb stable, please use `makedeb-beta` that should fix the dependency problem
if not then let me know.

**Comment by berglh** [comment]
> @berglh this is sadly a bug in makedeb stable, please use `makedeb-beta` that should fix the dependency problem if not then let me know.

Ah, that's all good. I shall wait for it to come into the main version, in the meantime I just changed the dependency to from `glslang` to `glslang-dev` and it built just fine. Thanks for the reply.

**Comment by flightlessmango** [comment]
we no longer link to the ppa

**Comment by wowpatrick** [comment]
If I'm not mistaken the `[master readme](https://github.com/flightlessmango/MangoHud?tab=readme-ov-file#debian-ubuntu)` still mentions the `mangohud:i386` PPA package which as discussed here isn't available. Wouldn't it be a good idea to remove that reference from the readme file?

**Comment by flightlessmango** [comment]
No that is not a reference to the PPA, it's in the official ubuntu and debian repos

**Comment by wowpatrick** [comment]
Thanks for the quick response and sorry for the confusion. On KDE neon 6.2 which is based on Ubuntu 24.04 the package does not seem to be available:
```
$ sudo apt install mangohud:i386
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package mangohud:i386
```
I ran `sudo dpkg --add-architecture i386` and `sudo apt update` beforehand.

**Comment by 17314642** [comment]
Yeah, it doesn't exist:

> [Some](https://packages.ubuntu.com/search?keywords=mangohud) results have not been displayed due to the search parameters.
>
>You have searched for packages that names contain mangohud in all suites, all sections, and architecture(s) i386.
>
>Sorry, your search gave no results

![Image](https://github.com/user-attachments/assets/8d327728-ec1d-411e-9846-da16dd908a0d)

**Comment by 17314642** [comment]
@EverydayLolicon what exactly do you want to be made easier?

flightlessmango is not responsible for package distribution. So you probably should open bug request on ubuntu's website.

**Comment by wowpatrick** [comment]
I think it may make sense to remove the `sudo apt install mangohud:i386` from the readme as the package is not available as discussed here.

**Comment by flightlessmango** [comment]
Removed from readme 7ad6215

**Comment by 17314642** [comment]
@EverydayLolicon

You can supply two commands to `mangohud-setup.sh` which is `install` and `uninstall`. No need to use `buuld.sh`
