### ISSUE TITLE
How can I use MangoHud (AUR) in Steam (Flatpak)? 

### ISSUE THREAD

**Issue by Monstanner** [flightlessmango/MangoHud#608]
Since com.valvesoftware.Steam.Utility.MangoHud is no longer being developed, I installed the normal version of MangoHud. Unfortunately the Flatpak version of Steam has a restriction to use the home directory or system settings. I've tried all sorts of things. Still, I can't find a way to use MangoHud from the AUR with the Flatpak version of Steam.

**Comment by flightlessmango** [comment]
Looks like they switched over to this package instead
https://github.com/flathub/org.freedesktop.Platform.VulkanLayer.MangoHud

**Comment by gasinvein** [comment]
Both of these issue should be resolved by now for Steam flatpak.

**Comment by Monstanner** [comment]
> Both of these issue should be resolved by now for Steam flatpak.

Thanks for the information. I have now switched to `org.freedesktop.Platform.VulkanLayer.MangoHud//21.08` without any problems. Everything works.

**Comment by csc-chicken** [comment]
@gasinvein hello although it's close, would you kindly explain why?? you said that **so they won't be able to use any libraries installed on host.** So is any flatpak app not able to use host library??

**Comment by csc-chicken** [comment]
OH! I see!!Just understand from the concept of docker and you explanation. thanks!!
