### ISSUE TITLE
Games Using Proton Crashes With 0.3.0

### ISSUE THREAD

**Issue by sputniktr02** [flightlessmango/MangoHud#61]
Vkcube and Glxgears works but none of the games I tried that is using proton is working.

Here is the log for Oblivion:
[steam-22330.log](https://github.com/flightlessmango/MangoHud/files/4333177/steam-22330.log)

My System:
OS: openSUSE Tumbleweed x86_64
CPU: Intel i7-4700MQ
GPU: NVIDIA GeForce GTX 860M (440.64)

**Comment by flightlessmango** [comment]
can you try using `mangohud.x86 %command%` ?

**Comment by sputniktr02** [comment]
Yes, none of them works.

**Comment by flightlessmango** [comment]
what other games have you tried?

**Comment by jackun** [comment]
Did you edit MangoHud.conf? It looks like it is about to load config files.
Other than that, I can't get it to even work with DXVK.

**Comment by sputniktr02** [comment]
@flightlessmango 
Batman Arkham Asylum
Batman Arkham City
Tomb Raider Legend
S.T.A.L.K.E.R Shadow of Chernobyl

and many others, basically all games running with proton are effected. Version 0.2.0 was working fine.

**Comment by sputniktr02** [comment]
@jackun yes I edited the config file and it loads fine for vkcube but prints some errors

![Screenshot_20200315_111833](https://user-images.githubusercontent.com/31340272/76698012-e9bc5d00-66ae-11ea-8177-87a67ddac168.jpg)

**Comment by sputniktr02** [comment]
@flightlessmango  Hi. Latest release seems to fixed my issue.

![Screenshot_20200319_121257](https://user-images.githubusercontent.com/31340272/77050737-41263a00-69db-11ea-9a75-f707c88ca359.jpg)

Thanks.

**Comment by flightlessmango** [comment]
great! :+1: thanks for reporting
