### ISSUE TITLE
Recommended Release for SteamOS 2.0 (Debian Jessie)

### ISSUE THREAD

**Issue by raedeus** [flightlessmango/MangoHud#610]
Trying to install for in SteamOS running over Debian Jessie. Looks like some glibc debendencies are outdated in the latest release. Which release would support the SteamOS version?

Thanks in advance.

- raedeus

**Comment by gardotd426** [comment]
Steam OS 2 hasn't been updated in a  year and a half and is effectively dead, and shouldn't be used by anyone, ever. Like ghost says, if you want an HTPC couch PC type OS, use Chimera or something similar.
