### ISSUE TITLE
The Long Dark won't start with "mangohud %command%" on steam

### ISSUE THREAD

**Issue by bkdwt** [flightlessmango/MangoHud#615]
Hi! I trying to play the long dark using mangohud on Fedora 35, but the game won't start when I put the flag "mangohud %command%" on steam.

```
/bin/sh\0-c\0mangohud  /home/botnet/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=305620 -- '/home/botnet/.local/share/Steam/steamapps/common/TheLongDark/tld.x86_64'\0
Game process added : AppID 305620 "mangohud  /home/botnet/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=305620 -- '/home/botnet/.local/share/Steam/steamapps/common/TheLongDark/tld.x86_64'", ProcID 9969, IP 0.0.0.0:0
ERROR: ld.so: object '/home/botnet/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
GameAction [AppID 305620, ActionID 1] : LaunchApp changed task to WaitingGameWindow with ""
ERROR: ld.so: object '/home/botnet/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/botnet/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
GameAction [AppID 305620, ActionID 1] : LaunchApp changed task to Completed with ""
ERROR: ld.so: object '/home/botnet/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/botnet/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Found path: /home/botnet/.local/share/Steam/steamapps/common/TheLongDark/tld.x86_64
Loading in SingleInstance mode
can't get dlopen()
Game process removed: AppID 305620 "mangohud  /home/botnet/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=305620 -- '/home/botnet/.local/share/Steam/steamapps/common/TheLongDark/tld.x86_64'", ProcID 9969 
Uploaded AppInterfaceStats to Steam
No cached sticky mapping in ActivateActionSet.Installing breakpad exception handler for appid(steam)/version(1634158817)
Installing breakpad exception handler for appid(steam)/version(1634158817)
```

mangohud --dlsym %command% has the same effect.

**Comment by jackun** [comment]
Are you on Ubuntu 21.xx? Install v0.6.6 or build from git.

**Comment by 7system7** [comment]
Same issue here.

**Comment by mrdeathjr28** [comment]
confirmed in my case fixed (xubuntu 22.04 jammy jellyfish) with lastest master aka 0.6.6

**Comment by flightlessmango** [comment]
Seems to work on my end, might be fixed in 943403308333897cde5023f27cc0b2e4515e8cb2

**Comment by bkdwt** [comment]
> Seems to work on my end, might be fixed in [9434033](https://github.com/flightlessmango/MangoHud/commit/943403308333897cde5023f27cc0b2e4515e8cb2)

Thanks, is fixed now but I still can't make mangohud works on opengl games. I really don't know what I need to do.

https://pastebin.com/TP6QHium

```
mangohud %command% 
mangohud --dlsym %command%
 LD_PRELOAD=$LD_PRELOAD:/usr/lib/mangohud/lib32/libMangoHud.so mangohud --dlsym %command%
```

None of these flags works for me. Please, can you give me a little help on this? Thanks in advance!

**Comment by jcbritobr** [comment]
> > Seems to work on my end, might be fixed in [9434033](https://github.com/flightlessmango/MangoHud/commit/943403308333897cde5023f27cc0b2e4515e8cb2)
> 
> Thanks, is fixed now but I still can't make mangohud works on opengl games. I really don't know what I need to do.
> 
> https://pastebin.com/TP6QHium
> 
> ```
> mangohud %command% 
> mangohud --dlsym %command%
>  LD_PRELOAD=$LD_PRELOAD:/usr/lib/mangohud/lib32/libMangoHud.so mangohud --dlsym %command%
> ```
> 
> None of these flags works for me. Please, can you give me a little help on this? Thanks in advance!
> 
> I'm using Fedora 35 with Xorg and the latest updates.

Not works also in pops 22.04 amd64.

If I pass mangohud=1 %command%, the game starts, but withour overlay.
Using the latest mangohud version

**Comment by jackun** [comment]
@jcbritobr if you're using flatpak then you'll need `/usr/lib/extensions/vulkan/MangoHud/bin/mangohud --dlsym %command%`  (unless it got fixed in the meantime and is in $PATH already).

Also, `MANGOHUD=1`, capitalization matters.

**Comment by jcbritobr** [comment]
> @jcbritobr if you're using flatpak then you'll need `/usr/lib/extensions/vulkan/MangoHud/bin/mangohud --dlsym %command%` (unless it got fixed in the meantime and is in $PATH already).
> 
> Also, `MANGOHUD=1`, capitalization matters.

Hello. Solved compiling the mangohud from master.

**Comment by Meister1593** [comment]
No overlay with MANGOHUD=1, `mangohud %command%` doesn't start the game and `/usr/lib/extensions/vulkan/MangoHud/bin/mangohud %command%` does too

**Comment by Meister1593** [comment]
> No overlay with `MANGOHUD=1`, `mangohud %command%` doesn't start the game and `/usr/lib/extensions/vulkan/MangoHud/bin/mangohud %command%` does too. Flatpak steam.

Nevermind, had wrong version of mangohud runtime (21.08 instead of 22.08 that was needed for steam)
