### ISSUE TITLE
csgo doesn't start with mangohud %command%

### ISSUE THREAD

**Issue by poopman97** [flightlessmango/MangoHud#617]
when i try to open csgo with mangohud %command% it just crashes

log:
`Game process removed: AppID 730 "mangohud /home/vidak/.steam/debian-installation/ubuntu12_32/reaper SteamLaunch AppId=730 -- '/home/vidak/.steam/debian-installation/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/home/vidak/.steam/debian-installation/steamapps/common/SteamLinuxRuntime'/scout-on-soldier-entry-point-v2 --  '/home/vidak/.steam/debian-installation/steamapps/common/Counter-Strike Global Offensive/csgo.sh' -steam", ProcID 72469 
Uploaded AppInterfaceStats to Steam
No cached sticky mapping in ActivateActionSet.Opted-in Controller Mask for AppId 0: 0
GameAction [AppID 730, ActionID 2] : LaunchApp changed task to UpdatingAppInfo with ""
Opted-in Controller Mask for AppId 730: 0
GameAction [AppID 730, ActionID 2] : LaunchApp changed task to ProcessingInstallScript with ""
GameAction [AppID 730, ActionID 2] : LaunchApp changed task to SynchronizingCloud with ""
GameAction [AppID 730, ActionID 2] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 730, ActionID 2] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 730, ActionID 2] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 730, ActionID 2] : LaunchApp continues with user response "CreatingProcess"
/bin/sh\0-c\0mangohud /home/vidak/.steam/debian-installation/ubuntu12_32/reaper SteamLaunch AppId=730 -- '/home/vidak/.steam/debian-installation/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/home/vidak/.steam/debian-installation/steamapps/common/SteamLinuxRuntime'/scout-on-soldier-entry-point-v2 --  '/home/vidak/.steam/debian-installation/steamapps/common/Counter-Strike Global Offensive/csgo.sh' -steam\0
Game process added : AppID 730 "mangohud /home/vidak/.steam/debian-installation/ubuntu12_32/reaper SteamLaunch AppId=730 -- '/home/vidak/.steam/debian-installation/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/home/vidak/.steam/debian-installation/steamapps/common/SteamLinuxRuntime'/scout-on-soldier-entry-point-v2 --  '/home/vidak/.steam/debian-installation/steamapps/common/Counter-Strike Global Offensive/csgo.sh' -steam", ProcID 72844, IP 0.0.0.0:0
ERROR: ld.so: object '/home/vidak/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
GameAction [AppID 730, ActionID 2] : LaunchApp changed task to WaitingGameWindow with ""
ERROR: ld.so: object '/home/vidak/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
GameAction [AppID 730, ActionID 2] : LaunchApp changed task to Completed with ""
ERROR: ld.so: object '/home/vidak/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/vidak/.steam/debian-installation/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/vidak/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/vidak/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/vidak/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 72849 != 72846, skipping destruction (fork without exec?)
pid 73121 != 73116, skipping destruction (fork without exec?)
pid 73162 != 73116, skipping destruction (fork without exec?)
can't get dlopen()
Game process removed: AppID 730 "mangohud /home/vidak/.steam/debian-installation/ubuntu12_32/reaper SteamLaunch AppId=730 -- '/home/vidak/.steam/debian-installation/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/home/vidak/.steam/debian-installation/steamapps/common/SteamLinuxRuntime'/scout-on-soldier-entry-point-v2 --  '/home/vidak/.steam/debian-installation/steamapps/common/Counter-Strike Global Offensive/csgo.sh' -steam", ProcID 72844 
Uploaded AppInterfaceStats to Steam
No cached sticky mapping in ActivateActionSet.`

**Comment by Alfenstein8** [comment]
I have the same issue

**Comment by romanstingler** [comment]
have you the latest 0.6.6 version??

**Comment by poopman97** [comment]
> have you the latest 0.6.6 version??

Yes.
