### ISSUE TITLE
Build failed for 3.0 release

### ISSUE THREAD

**Issue by dancaer69** [flightlessmango/MangoHud#62]
I cannot build mangohud latest release in ubuntu 18.04. 

`Found ninja-1.8.2 at /usr/bin/ninja
ninja: Entering directory `build/meson32'
[1/29] Generating overlay.vert.spv.h with a custom command.
../../src/overlay.vert
[2/29] Generating overlay.frag.spv.h with a custom command.
../../src/overlay.frag
[4/29] Generating vk_api_xml with a custom command.
Cloning into '/home/useful/MangoHud/MangoHud-v0.3.0/build/meson32/modules/Vulkan-Headers'...
[5/29] Generating vk_enum_to_str with a custom command.
FAILED: vk_enum_to_str.c vk_enum_to_str.h 
/usr/bin/python3 ../../bin/gen_enum_to_str.py --xml modules/Vulkan-Headers/vk.xml --outdir /home/useful/MangoHud/MangoHud-v0.3.0/build/meson32
Traceback (most recent call last):
  File "../../bin/gen_enum_to_str.py", line 30, in <module>
    from mako.template import Template
ModuleNotFoundError: No module named 'mako'
[7/29] Compiling C++ object 'modules/ImGui/f9cf425@@imgui_core@sta/src_imgui_widgets.cpp.o'.
ninja: build stopped: subcommand failed.
ninja: Entering directory `build/meson64'
[1/29] Generating overlay.frag.spv.h with a custom command.
../../src/overlay.frag
[2/29] Generating overlay.vert.spv.h with a custom command.
../../src/overlay.vert
[7/29] Generating vk_api_xml with a custom command.
Cloning into '/home/useful/MangoHud/MangoHud-v0.3.0/build/meson64/modules/Vulkan-Headers'...
[8/29] Generating vk_enum_to_str with a custom command.
FAILED: vk_enum_to_str.c vk_enum_to_str.h 
/usr/bin/python3 ../../bin/gen_enum_to_str.py --xml modules/Vulkan-Headers/vk.xml --outdir /home/useful/MangoHud/MangoHud-v0.3.0/build/meson64
Traceback (most recent call last):
  File "../../bin/gen_enum_to_str.py", line 30, in <module>
    from mako.template import Template
ModuleNotFoundError: No module named 'mako'
ninja: build stopped: subcommand failed.
`
any help?

**Comment by flightlessmango** [comment]
`ModuleNotFoundError: No module named 'mako'`
as it says, you need to install mako `sudo pip3 install mako`

**Comment by dancaer69** [comment]
I installed python-mako, I thought that this needed for ubuntu. 
Anyway with pip3 worked, thanks.

**Comment by Newbytee** [comment]
@dancaer69 python-mako refers to the Python2 package in Ubuntu. You would need to install python3-mako. 

See Python dependencies here: 
https://packages.ubuntu.com/bionic/python-mako
https://packages.ubuntu.com/bionic/python3-mako

**Comment by dancaer69** [comment]
You have right, I always forget that python means python2.

**Comment by Newbytee** [comment]
> You have right, I always forget that python means python2.

Sort of. In some distribution python means python2, but generally distributions are moving towards changing that to python meaning python3. Fedora and Arch are already doing so.

**Comment by jomarocas** [comment]
good day for me failed to install in ubuntu 20.04
sudo apt install python3-mako
python3-mako is already the newest version (1.1.0+ds1-1ubuntu2) 

sudo pip3 install mako
Requirement already satisfied: mako in /usr/lib/python3/dist-packages (1.1.0)

anymore, python2 also install but is no usable, i try to install latest version download from github and all packages but no, i use flatpack but install but i cannot get the latest version

**Comment by flightlessmango** [comment]
@jomarocas you haft to provide a log
