### ISSUE TITLE
Specific Config file

### ISSUE THREAD

**Issue by Monstanner** [flightlessmango/MangoHud#620]
Is it possible to create a specific config file for a Windows game in the Steam and MangoHud Flatpak versions? I've tried several times, but the game doesn't want to use the file.

Here's the problem:
I would like to use Windows games with MangoHud. This works with Linux and Windows games. I also put a special config file in `/.var/app/com.valvesoftware.Steam/config/MangoHud/` called `MangoHud.conf`. With Linux games, I know that if a game is supposed to use a specific file, I put it in the game's root directory. But how does this work with Windows games that run with Proton? I tried `$HOME/.config/MangoHud/wine-application_name.conf`. But then the game uses an unconfigured MangoHud file. At least that's what it looks like, as these are standard settings.

**Comment by gort818** [comment]
No problem, glad you got it working!
