### ISSUE TITLE
Custom Text / Custom Text Centred (Not Displaying) v0.6.6-1

### ISSUE THREAD

**Issue by berglh** [flightlessmango/MangoHud#621]
When using the new layout on v0.6.6-1, on Ubuntu, Proton Experimental and the New Layout, neither Custom Text or Custom Text Center is displayed when set in the config file. Changing the layout to Legacy shows the custom text, but the layout is undesirable.

In addition, I noticed that setting "height" has no effect. I was hoping to increase this might display it if it was squished by the configured cells, but this also had no affect. Width works correctly.

**Comment by berglh** [comment]
@flightlessmango With respect to your [comment](https://github.com/flightlessmango/MangoHud/issues/622#issuecomment-955666877), this issue #621 is also occurring for me in `vkcube` when setting the custom text settings.

```bash                                                                                         
custom_text_center=Flightless Mango
custom_text=Flightless Mango 
```
Neither of these appear:
![image](https://user-images.githubusercontent.com/12455338/139578259-f86142c4-ea99-4ecd-be05-51d1248ce14d.png)

Likewise, if I increase the height of the layout, it does not affect the mangohud. Is the configuration file expecting the option to be present in a particular place? These all just seem like key/value pairs, so it should matter. Many thanks.

**Comment by jackun** [comment]
> Neither of these appear:

You probably need `legacy_layout=0`

**Comment by berglh** [comment]
> You probably need `legacy_layout=0`

Hi @jackun, that did indeed work. I'm curious though, if I have this commented out, what is the default value? Setting it as true shows the legacy. In any event, perhaps this should either be fixed up in the argument defaults inside the argument parser or added as an explicit config option in the example configuration file?

Thanks for your help! :)

**Comment by jackun** [comment]
> what is the default value

Enabled. Default values should be in example config file but this seems to be flipped.

**Comment by berglh** [comment]
I'm happy to close this issue if you think there is nothing further to chase on this @jackun

**Comment by flightlessmango** [comment]
Reopen if still an issue on latest
