### ISSUE TITLE
Unable to run OpenGL application on openSUSE Tumbleweed x86_64, "can't get libdl.so".

### ISSUE THREAD

**Issue by ImBearChild** [flightlessmango/MangoHud#623]
I've been trying to launch glxgears with mangohud on openSUSE Tumbleweed, but I only got `can't get libdl.so` in return. 

```
> mangohud --dlsym glxgears
can't get libdl.so
> mangohud glxgears
can't get libdl.so
```

As far as I know, `libdl.so` is a part of glibc, and the file name of this so file on openSUSE is `libdl.​so.​2`. Maybe this issue is caused by the difference of file name.

------
Operating System: openSUSE Tumbleweed 20211016
KDE Plasma Version: 5.23.0
KDE Frameworks Version: 5.86.0
Qt Version: 5.15.2
Kernel Version: 5.14.11-1-default (64-bit)
Graphics Platform: X11
Memory: 15.2 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics 630

**Comment by VortexAcherontic** [comment]
@jackun is there a pull request for these fixes? I've been monitoring this issue (not exactly this one I am commenting right now tho :D ) since it came up and wanted to provide a patch file so the openSUSE package will at least start to work again. :)

**Comment by jackun** [comment]
In v0.6.6 already, just musl is still borked.

**Comment by VortexAcherontic** [comment]
Alright, guess will wait for the release of v 0.6.6 then. Thank you very much :)

**Comment by VortexAcherontic** [comment]
@ImBearChild I have temporarily brought 0.6.6-1 into OBS in my home repo. Currently it does not build for Leap but works fine on Tumbleweed. Tested with GLXGears.

You can get it from here for now: https://software.opensuse.org//download.html?project=home%3AVortexAcherontic%3Abranches%3Agames%3Atools&package=mangohud

**Comment by ImBearChild** [comment]
> @ImBearChild I have temporarily brought 0.6.6-1 into OBS in my home repo. Currently it does not build for Leap but works fine on Tumbleweed. Tested with GLXGears.
> 
> You can get it from here for now: https://software.opensuse.org//download.html?project=home%3AVortexAcherontic%3Abranches%3Agames%3Atools&package=mangohud

Thank you! It works on my machine!
