### ISSUE TITLE
No mangohud folder in .config (Pop!_OS 21.04)

### ISSUE THREAD

**Issue by THEHOMAK** [flightlessmango/MangoHud#624]
When I wanted to configure the colors for MangoHUD, because the one that are default aren't looking good in a dark game. However, when I follow the instructions, there is just no MangoHUD folder in config, but the HUD is working fine in games. 
installed through terminal following this:
"Ubuntu

User of Ubuntu 20.04 or newer can install a NVML enabled version of MangoHud from the MangoHud PPA maintained by Martin Wimpress:

sudo add-apt-repository ppa:flexiondotorg/mangohud
sudo apt update
sudo apt install mangohud

NOTE: Currently PPA has no 32-bit libraries"

Any help appreciated. Thanks!

**Comment by lukashoracek** [comment]
You have to create the `MangoHud` folder

**Comment by gort818** [comment]
Create the file and folder here `$HOME/.config/MangoHud/MangoHud.conf`
