### ISSUE TITLE
Man page for mangoapp

### ISSUE THREAD

**Issue by stephanlachnit** [flightlessmango/MangoHud#625]
Please provide a short man page for the binary `mangoapp`. Since it doesn't feature a `--help`, it's kinda hard to get what is for if one doesn't know it.
I can provide a PR if you give me two quick sentences how to use it (because tbh I also don't know it).

**Comment by flightlessmango** [comment]
Mangoapp is a transparent background opengl application with a built in mangohud. It's designed to be run inside a gamescope instance which will display mangoapp ontop of gamescopes output. It also takes frame information from gamescope. The purpose of this is to "easily" make mangohud compatible with any application, or at least any application that gamescope can run. This solves issues with some OpenGL games and certain ports that have stdc++ issues as it's no longer directly injected into the game

Typical usage would look like this:
Create a script like `run.sh` containing the app you want to run and mangoapp
```
vkcube&
mangoapp
```
then run it with `gamescope ./run.sh`

**Comment by VarLad** [comment]
@flightlessmango Is there an environment variable to set the options for mangoapp as well? 
If so, is there a list of options?
