### ISSUE TITLE
Invalid override value cpu_temp,gpu_temp

### ISSUE THREAD

**Issue by Aex12** [flightlessmango/MangoHud#632]
I'm trying to show cpu and gpu temps on MangoHud, however, after setting the env to MANGOHUD_CONFIG=cpu_temp,gpu_temp I get the "Invalid override value cpu_temp,gpu_temp" error and the HUD is not updated with temperature values.

I've checked on the README: https://github.com/flightlessmango/MangoHud#mangohud_config-and-mangohud_configfile-environment-variables and the values are okay. 

What is going wrong here?

**Comment by jackun** [comment]
What is printing "Invalid override value"? How and what are you trying to launch?

**Comment by Aex12** [comment]
@jacksun You are right. I accidentally put the env config on the incorrect Lutris setting. They seems so similar that I misplaced it.

Thank you for your answer, and sorry for opening up a non related issue. Have a nice day!
