### ISSUE TITLE
meson.build:1:0: ERROR: Meson version is 0.53.2 but project requires >=0.54.0

### ISSUE THREAD

**Issue by hex6b** [flightlessmango/MangoHud#634]
Using the installation guide I get an error when running `meson build`.

> meson.build:1:0: ERROR: Meson version is 0.53.2 but project requires >=0.54.0

Also, I'm unable to find the 0.54.0 version of mesa anywhere. Can only find https://ubuntu.pkgs.org/20.04/ubuntu-universe-amd64/meson_0.53.2-2ubuntu2_all.deb.html

Please help.

**Comment by flightlessmango** [comment]
This is not a mangohud issue
