### ISSUE TITLE
0.6.6* unusable for me

### ISSUE THREAD

**Issue by PiratePaprika** [flightlessmango/MangoHud#635]
When i start anything with MangoHud after couple seconds it drops FPS to ~2 and it stays there making app/game unusable.
0.6.5 works fine.
Not sure what else i need to provide im new to all of this.

Arch Linux
R9 390

**Comment by PiratePaprika** [comment]
I installed git version from AUR now it works fine, im guessing it's same as https://github.com/flightlessmango/MangoHud/issues/628

**Comment by jackun** [comment]
@PiratePaprika  If you got time, can you check what stat(s) cause this? Strange that it can't finish reading sysfs in 500ms (defualt fps_sampling_period).

**Comment by PiratePaprika** [comment]
Looks like it's **gpu_stats**, if i put **gpu_stats=0** works fine.
