### ISSUE TITLE
feature request: display what is limiting GPU performance like afterburner/RiviaTuner does

### ISSUE THREAD

**Issue by zany130** [flightlessmango/MangoHud#636]
you can check this info on nvidia with this command don't know about AMD though

```
nvidia-smi -q -d PERFORMANCE

==============NVSMI LOG==============

Timestamp                                 : Wed Nov 24 23:50:57 2021
Driver Version                            : 495.44
CUDA Version                              : 11.5

Attached GPUs                             : 1
GPU 00000000:0E:00.0
    Performance State                     : P0
    Clocks Throttle Reasons
        Idle                              : Active
        Applications Clocks Setting       : Not Active
        SW Power Cap                      : Not Active
        HW Slowdown                       : Not Active
            HW Thermal Slowdown           : Not Active
            HW Power Brake Slowdown       : Not Active
        Sync Boost                        : Not Active
        SW Thermal Slowdown               : Not Active
        Display Clock Setting             : Not Active

```
don't know how this can be implemented into mango though

I guess maybe it might be possible to write this into a file and then grep it?
i know you can loop it with
`--loop-ms=500`

EDIT:
able to do this by adding 
`exec=echo "Limiter:"&& nvidia-smi -q -d PERFORMANCE | grep -v "Not Active" | grep Active` to the mangohud config this shows what is causing the nvidia GPU to throttle. maybe an option can be created for this?

**Comment by zany130** [comment]
saw there been a recent commit https://github.com/flightlessmango/MangoHud/commit/f9cfdeb0804779a9957bcf956b9dfc63956a23b4  for adding this but its only for AMD right @flightlessmango

**Comment by flightlessmango** [comment]
> saw there been a recent commit [f9cfdeb](https://github.com/flightlessmango/MangoHud/commit/f9cfdeb0804779a9957bcf956b9dfc63956a23b4) for adding this but its only for AMD right

This is for nvidia as well (nvml), you enable it with throttling_status and it only shows up if there is throttling currently going on. So you need to create a throttled scenario to test it

**Comment by zany130** [comment]
Yup tried it in a game and it works as expected so i guess i can go ahead and close this
