### ISSUE TITLE
mangohud not loading for art of rally

### ISSUE THREAD

**Issue by Halvhjearne** [flightlessmango/MangoHud#641]
im not exactly sure what the problem is for this, cause it restarts the game and detaches from terminal when i try to start it:

$ mangohud ./artofrally.x64 
Set current directory to /home/halvhjearne/.steam/debian-installation/steamapps/common/artofrally
Found path: /home/halvhjearne/.steam/debian-installation/steamapps/common/artofrally/artofrally.x64
Loading in SingleInstance mode
Aborted (core dumped)

after this it will then detach and start the game from steam without mangohud.

Ubuntu 20.04.3 LTS

**Comment by flightlessmango** [comment]
I'm seeing the core dump with or without mangohud, however mangohud works just in this game on my system. Might be worth testing latest master

**Comment by Halvhjearne** [comment]
i tested latest with same result, no mangohud.
it works fine with lots of other games, just not art of rally.

**Comment by flightlessmango** [comment]
Since steam is starting the game it will be unaware of the `mangohud` from the terminal, you would need to add `mangohud %command%` to the launch options

**Comment by Halvhjearne** [comment]
i have that
![Screenshot from 2021-12-12 05-59-46](https://user-images.githubusercontent.com/6340219/145700940-0ea81db9-b813-4dfb-ae7f-eee8745ac7d0.png)

**Comment by Halvhjearne** [comment]
ok, so i think i figured out what the problem is here, when i was randomly messing with another game.
my desktop is set to 3840x2160, but i tend to run games in 1920x1080 and this seems to cause problems for mangohud sometimes.
today i tried setting game resolution to 3840x2160 and it turns out mangohud was running all along, but is for some reason set to show outside the screen, when game resolution is set to 1920x1080, as if the resolution was 3840x2160.
i assume mangohud for some reason thinks the resolution is same as desktop?
i also noticed in other games where mangohud does work, it will always say resolution is 3840x2160, no matter what resolution i set the game to run.
how can i fix this?

**Comment by flightlessmango** [comment]
same issue as #691
