### ISSUE TITLE
feature : custom stuff support

### ISSUE THREAD

**Issue by neofeo** [flightlessmango/MangoHud#643]
HI! for certain platforms it would be far easier to just add the support for custom or generic indicators, so we just add a command line on the config file and it just displays that instead of having to fork mangohud to mod it. 

for example, my cpu temperature isn't show on mangohud, bc I am on an ARM platform. it would require just to add a cmd line parameter on the config file if it had support for that...

**Comment by gort818** [comment]
try the `exec` config parameter. For example :
```
custom_text=/home
```
```
exec=df -h /home | tail -n 1. only works with legacy_layout=false
```

**Comment by gort818** [comment]
Did that work for you?
