### ISSUE TITLE
some config options are ignored

### ISSUE THREAD

**Issue by vasitzin** [flightlessmango/MangoHud#644]
So I've found some issues reported here about the config file but my issue is a bit different.

My config is located in /home/vasilis/.config/MangoHud/MangoHud.conf, I've checked from the cli as well just to be sure
`[2021-11-30 13:08:46.876] [MANGOHUD] [info] [config.cpp:119] parsing config: '/home/vasilis/.config/MangoHud/MangoHud.conf'`
and also set an env var $MANGOHUD_CONFIGFILE.

Most of the settings work fine, but some of them are ignored. For instance here is a sample from my config:
```
### FPS and frametime
# fps
# fps_sampling_period=500
# fps_color_change
# fps_value=30,60
# fps_color=B22222,FDFD09,39F900
frametime

### Display the frametime line graph
# frame_timing
# histogram
```
so I just want the frametime to be displayed, but here's what I get:
![20211130-132338](https://user-images.githubusercontent.com/95283684/144038867-2803fc6e-51b1-4bb9-9b36-622eb16e76e3.png)

In more detail, I can change the frametime graph to a histogram, but can't reomve the graph outright. Also the fps/frametime section is ignored completely no matter what I've set it to.

**Comment by jackun** [comment]
With how the files are parsed right now, default enabled stats have to be _explicitly disabled_ instead.

**Comment by vasitzin** [comment]
oh so it's not enough to just comment it out, ok my bad thanks for the quick response!

**Comment by jackun** [comment]
This seems to cause confusion fairly often so maybe MangoHud shouldn't set defaults when config file exists.

**Comment by vasitzin** [comment]
I think if it was better communicated in the MangoHud.conf.example in some way it would be fine.

anyway just comfirmed it works, although I can't keep just the frametime enabled and disable the fps as I wanted, I need to keep them both if I want to see the frametimes. Well that's a minor inconvenience, but I guess that's how mangohud works and it's fine.

thanks again @jackun!
