### ISSUE TITLE
MangoHud 0.6.6-1 not installing using the prepackaged binary

### ISSUE THREAD

**Issue by luni3359** [flightlessmango/MangoHud#645]
I think there's some problem during the installation, here's the output I'm getting:
https://gist.github.com/luni3359/9d1a231e7a763763c009f00cc0d5ae38

I can install the stable release without problems.

Distribution: KDE Neon 5.23
KDE Plasma: 5.23, X11
Kernel version: 5.11.0-40-generic (64-bit)

**Comment by jackun** [comment]
:man_facepalming:

**Comment by luni3359** [comment]
Thanks for fixing it, it works now!
