### ISSUE TITLE
procmem,procmem_shared,procmem_virt not working

### ISSUE THREAD

**Issue by abelsromero** [flightlessmango/MangoHud#646]
Just rebuild from source using build.sh script, and everything seems fine except for the mentioned options. RAM row shows 2 values, the total used RAM of the system (validated with htop) and another which is alwasys 0.

I just copied and added them to my `~/.config/MangoHud/MangoHud.conf`. Is there anything else required to run it?

![image](https://user-images.githubusercontent.com/5781153/144134869-bdafe2aa-130f-411a-8cb6-ac500fd69165.png)

**Comment by flightlessmango** [comment]
I believe pmem requires the `legacy_layout=false` param
