### ISSUE TITLE
Witcher1 mangohud not working!?

### ISSUE THREAD

**Issue by Uatschitchun** [flightlessmango/MangoHud#648]
Hi.
Bare with me, I'm new to mangohud.

Trying to run with Witcher1. Installed mangohud from Release page on *buntu 20.04, so 32bit should be installed.
Checked with installing vulkan-tools:i386 and mangohud is showing up.

With "The Witcher" I tried with and without --dlsym in steam option and with manghud & mangohud.x86 %command%

What else am I supposed to do to get it running?

**Comment by flightlessmango** [comment]
what is the game called exactly? having issues finding it

**Comment by gort818** [comment]
I would assume it is this https://store.steampowered.com/app/20900/The_Witcher_Enhanced_Edition_Directors_Cut/

**Comment by flightlessmango** [comment]
Running without issue here. You could double check that 32bit mangohud is working with `glxspheres32` from the 32bit `virtualgl` package

**Comment by Uatschitchun** [comment]
Yes, sorry. Thought "Witcher" is a well known game ;)
I've tested with `glxspheres` from `virtualgl32` package and `mangohud` is working well!

Within steam, no matter if I set launcher.exe or witcher.exe as target, neither
`mangohud %command%`
nor
`mangohud --dlsym %command%`
do work!?

**Comment by FireCulex** [comment]
I can confirm The Witcher: Enhanced Edition works out of the box with DXVK using master using build.sh.

**Comment by flightlessmango** [comment]
reopen if still an issue
