### ISSUE TITLE
Mangohud bug with lutris or wine

### ISSUE THREAD

**Issue by Modey2222** [flightlessmango/MangoHud#649]
hi i wanted to report this
if anything opened before lutris most of the games that i launch gives me error code 1280 after trying here and there removing mangohud and rebuilding lutris+wine fixes this issue
i do not know exactly what causes it but another work around while mangohud installed is if the error occur restarting the whole system with nothing launching at start up before lutris this fixes it temporarly untill the next restart

i have an nvidia GPU might be caused by nvidia's driver
sorry if my message was poorly understood my english is average

**Comment by flightlessmango** [comment]
reopen if still an issue with latest mangohud
