### ISSUE TITLE
No binary. command not found: mangohud

### ISSUE THREAD

**Issue by Tanath** [flightlessmango/MangoHud#65]
I followed these directions for Arch-based: `install mangohud and lib32-mangohud`.

`pacman -Ql mangohud` shows all the files installed:

```
mangohud /usr/
mangohud /usr/lib/
mangohud /usr/lib/libMangoHud.so
mangohud /usr/share/
mangohud /usr/share/doc/
mangohud /usr/share/doc/mangohud/
mangohud /usr/share/doc/mangohud/MangoHud.conf
mangohud /usr/share/licenses/
mangohud /usr/share/licenses/mangohud/
mangohud /usr/share/licenses/mangohud/LICENSE
mangohud /usr/share/vulkan/
mangohud /usr/share/vulkan/implicit_layer.d/
mangohud /usr/share/vulkan/implicit_layer.d/mangohud64.json
```
Similar output for lib32 version. There is no binary, and I haven't been able to get it working.

**Comment by flightlessmango** [comment]
The aur package is still `Flagged out-of-date (2020-03-14)`, meanwhile you can use this PKGBUILD
https://github.com/flightlessmango/PKGBUILDS/blob/master/mangohud/PKGBUILD
or you can use the chaotic-aur repo

**Comment by Tanath** [comment]
That works!

```
mangohud-git /usr/
mangohud-git /usr/bin/
mangohud-git /usr/bin/mangohud
mangohud-git /usr/lib/
mangohud-git /usr/lib/libMangoHud.so
mangohud-git /usr/share/
mangohud-git /usr/share/doc/
mangohud-git /usr/share/doc/mangohud/
mangohud-git /usr/share/doc/mangohud/MangoHud.conf.example
mangohud-git /usr/share/vulkan/
mangohud-git /usr/share/vulkan/implicit_layer.d/
mangohud-git /usr/share/vulkan/implicit_layer.d/MangoHud.x86_64.json
```

Running an app with `mangohud` shows the HUD, but the shortcut is still `F12` which conflicts. I changed it to `F7` in the config but it has no effect.

**Comment by flightlessmango** [comment]
if you just run `mangohud glxgears` it should tell you in the console what config file he's actually parsing, check that he's actually loading the one you're editing

**Comment by Tanath** [comment]
Oh, I see, thanks you. I had copied `/usr/share/doc/mangohud/MangoHud.conf.example` to `/usr/share/doc/mangohud/MangoHud.conf` and edited that.
