### ISSUE TITLE
MangoHud prevents Foundation to start 

### ISSUE THREAD

**Issue by leinardi** [flightlessmango/MangoHud#650]
I just found out that MangoHud prevents the game [Foundation](https://store.steampowered.com/app/690830/Foundation/) from starting.

I [reported the issue](https://github.com/ValveSoftware/Proton/issues/2318#issuecomment-991344255) also inside the official proton issue tracker, because the game developers used to post there as well, but I think that, since the game works without MangoHud, it could be an issue with this software and not with the game itself.

I was able to reproduce the issue with v0.6.1 and v0.6.5.

**Comment by Leopard1907** [comment]
Can you try with master?

**Comment by flightlessmango** [comment]
Works on master on my end

**Comment by leinardi** [comment]
@Leopard1907 just tested and I cannot reproduce the issue on `master` :+1:
