### ISSUE TITLE
Keybinds do not work when using mangohud on an accelerated terminal

### ISSUE THREAD

**Issue by fee1-dead** [flightlessmango/MangoHud#656]
I tried `mangohud --dlsym alacritty` and it looks like none of the keybinds work. I wanted to measure the performance of `alacritty` but it looks like logging is not possible with the currently released version.

**Comment by flightlessmango** [comment]
Works fine on my end, you could try building from master

**Comment by fee1-dead** [comment]
Just built master and still failed :( I think the problem is actually that I'm on wayland and not X11.

**Comment by flightlessmango** [comment]
Yes keybinds are not implemented on wayland

**Comment by flightlessmango** [comment]
feel free to create an issue / request for that feature
