### ISSUE TITLE
Keybinds do not work on Wayland

### ISSUE THREAD

**Issue by fee1-dead** [flightlessmango/MangoHud#658]

**Comment by bonscji1** [comment]
Hi folks, could i ask that description for shortcuts is updated to say this is not supported on wayland? I am a dummy and tried for some hours now to fix this perceived issue not realizing it is not implemented yet :D.

**Comment by nbass-tech** [comment]
I second fixing this, as Wayland is the future of desktop Linux, not X11.

**Comment by cyberconan** [comment]
+1 Please, fix keybinding in Wayland. Thanks!!!

**Comment by flightlessmango** [comment]
So far I'm unaware of a way to achieve this in Wayland. It almost seems to me like it's not doable by design

**Comment by soredake** [comment]
https://gitlab.freedesktop.org/wayland/wayland-protocols/-/issues/73
https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/56
Maybe related.

**Comment by zany130** [comment]
I was able to get around this with this script

```bash
File: Scripts/toggleMangoHud.sh
#!/bin/bash
config_file=/home/zany130/.config/MangoHud/MangoHud.conf
no_disp=$(grep -i 'no_display=' "$config_file" | awk '{ print $3 }')

if grep -q "no_display=0" "$config_file"; then
    sed -i 's/no_display=0/no_display=1/' "$config_file"
    notify-send "MangoHud was turned Off"
elif grep -q "no_display=1" "$config_file"; then
    sed -i 's/no_display=1/no_display=0/' "$config_file"
    notify-send "MangoHud was turned On"
else
    notify-send "ERROR value not found"
fi
```
and then adding it to kde shortcut settings 
![image](https://user-images.githubusercontent.com/25832539/173171406-d033e6ab-b51f-4e9e-a15c-943b91b6d2ae.png)

**Comment by jackun** [comment]
Git master can also use python script for some basic control in https://github.com/flightlessmango/MangoHud/tree/master/control

**Comment by orowith2os** [comment]
The global keybinds portal was merged in x-d-p 1.16, but it requires registering the appropriate keys and that might not be desired as it requires user interaction when the user only allows it one-time, and it can get repetitive.

Additionally keybinds seem to work just fine, it's just *global* keybinds that don't work, which doesn't seem like much of a loss, at least to me.

**Comment by Etaash-mathamsetty** [comment]
There is a way to achieve this under Wayland, it would work basically identically to the wayland keylogger project.

**Comment by orowith2os** [comment]
Via jadahl:
> create a .so file that has wl_display_connect() exported. in there, dlopen [libwayland-client.so](http://libwayland-client.so/) and find the correct wl_display_connect address. when you get called, call the "real" function, but store away a proxy wrapper of the return value. get your own registry, find the seat, get a wl_keyboard and start listening to events.

And a bit of a warning, if relevant, from Arnavion:
> Note that the LD_PRELOAD'ing to hook libwayland-client functions only works for processes that use libwayland-client
> Worst case you'll have to hook connect()

**Comment by flightlessmango** [comment]
This has been attempted before, might be worth to look at for reference
https://github.com/flightlessmango/MangoHud/commit/26c8d1dbdda16ae3af53c3aa7a71eaeb3ffd4acd

**Comment by Etaash-mathamsetty** [comment]
very initial version ready: https://github.com/flightlessmango/MangoHud/pull/1093

**Comment by Etaash-mathamsetty** [comment]
merged :)

**Comment by flightlessmango** [comment]
this has been resolved

**Comment by pollux78** [comment]
Was this for keybinds to work under xwayland games? as when i run any game with wayland enabled under proton-em, proton-cachyos, proton-ge i cant activate shortcuts that have been configured under goverlay with mangohud like the log key or hud toggle key, could this possibly be a goverlay issue?

**Comment by BananaWorks07** [comment]
> Was this for keybinds to work under xwayland games? as when i run any game with wayland enabled under proton-em, proton-cachyos, proton-ge i cant activate shortcuts that have been configured under goverlay with mangohud like the log key or hud toggle key, could this possibly be a goverlay issue?

no it is for wayland games. It doesn't work on the current mangohud stable release because the wrong library was being loaded (oops), so you have to use mangohud-git. It doesn't work on every game for now, but I will work on something that should resolve this in the future.

**Comment by pollux78** [comment]
> > Was this for keybinds to work under xwayland games? as when i run any game with wayland enabled under proton-em, proton-cachyos, proton-ge i cant activate shortcuts that have been configured under goverlay with mangohud like the log key or hud toggle key, could this possibly be a goverlay issue?
> 
> no it is for wayland games. It doesn't work on the current mangohud stable release because the wrong library was being loaded (oops), so you have to use mangohud-git. It doesn't work on every game for now, but I will work on something that should resolve this in the future.

Awesome, thanks for the information and the awesome work!
