### ISSUE TITLE
New feature: Show Vulkan and OpenGL versions

### ISSUE THREAD

**Issue by Faalagorn** [flightlessmango/MangoHud#66]
I mentioned it on Discord once, and apparently it is possible. Could a Vulkan and OpenGL version be shown in a way similar to how DXVK version is shown?

**Comment by Faalagorn** [comment]
Seems to be solved with 8aa0783b4ae9ac6b0e21434640c498b8dc6e3931 unless it's possible to add exlplicit Vulkan/OGL version used by the game/application or some other improvements are planned  (I'd love to see the version string at the same line as the name, preferably shortened to OGL4.6 or VK1.2.128, but that's for a different issue I guess)?

**Comment by flightlessmango** [comment]
I would say this issue is resolved. As for putting it next to the name, currently I don't think this will work well. But it could be it's own issue and we'll see if it becomes more feasible as the imgui tables api gets updated
