### ISSUE TITLE
MangoHud crashes Steam when used in launch options for games

### ISSUE THREAD

**Issue by Andy3153** [flightlessmango/MangoHud#660]
So, firstly, I'm using a more weird setup, since I also need PRIME render offloading (hybrid graphics, because it's a laptop), and I also want to use [GameMode](https://github.com/FeralInteractive/gamemode). So, that's why it's not just `mangohud %command%` for me, my entire launch options are:

```
GAMEMODERUNEXEC="env __NV_PRIME_RENDER_OFFLOAD=1 env __GLX_VENDOR_LIBRARY_NAME=nvidia env __VK_LAYER_NV_optimus=NVIDIA_only mangohud" gamemoderun %command%
```

But, I've seen one more person complain about this that had the normal setup on [Reddit](https://www.reddit.com/r/linux4noobs/comments/r8mjyo/mangohud_causing_steam_to_crash_in_the_background/), but with no solution.

This happened to me in all three games I tried playing with MangoHud: GTA 5, DiRT 4, and Chicken Invaders Universe (last one was just to test, and, so, we've got a Proton game, a native Linux game and a game that's not very graphically demanding).

So, the problem is the same across all games I tried: I launch the game, everything looks normal, then after some time the entire Steam client crashes in the background, and with GTA 5 and Chicken Invaders, the games crash along with it. DiRT seems to keep running but fails to save games apparently, makes sense if Steam is not running anymore.

About my system:

```
OS:     Arch Linux x86_64 
Host:   ASUS TUF Gaming F15 FX506HM
Kernel: 5.15.11-arch2-1
CPU:    11th Gen Intel i7-11800H
GPU:    NVIDIA GeForce RTX 3060 Mobile / Max-Q 
GPU:    Intel TigerLake-H GT1 [UHD Graphics] 
Memory: 15723MiB
```

**Comment by flightlessmango** [comment]
#639 sounds like this issue, seems to be fixed in master

**Comment by Andy3153** [comment]
Yeah, that might seem to be the case. I used GOverlay as well, like everyone else in there, and it defaulted to adding an empty "exec=" option, which, when removed, seems to work well now, but I've tested for only around 2-3 hours
