### ISSUE TITLE
No GPU Usage Statistics while running Intel Xe Graphics on Iris Driver.

### ISSUE THREAD

**Issue by Bens0** [flightlessmango/MangoHud#661]
Currently no GPU statistics like usage and temperature are being pulled and put onto the HUD. I am running OpenSUSE Tumbleweed.

**Comment by Leopard1907** [comment]
Gpu usage is known to be not working for any Intel gpu's on Mangohud. Iirc reading that value ( gpu 
usage ) without superuser access is not possible on Intel.

Gpu temp doesn't need such thing though, at least on my Kabylake igpu it doesn't.

**Comment by birdie-github** [comment]
Vote for https://gitlab.freedesktop.org/drm/intel/-/issues/5018

**Comment by flightlessmango** [comment]
Moving conversation to #1082

**Comment by cheako** [comment]
The error I get is: `(Kernel 4.16 or newer is required for i915 PMU support.)` different thing, still the error is wrong.
