### ISSUE TITLE
Feature Request: Per game fps limit

### ISSUE THREAD

**Issue by Trevonn** [flightlessmango/MangoHud#663]
Hello it would be nice if we could limit application FPS on a per game basis in a similar fashion to DXVK

```
[fallout4.exe]
fps_limit=60
```
As an example

**Comment by gort818** [comment]
You can do that https://github.com/flightlessmango/MangoHud#hud-configuration
Create a new .conf file
`wine-fallout4.conf`

**Comment by Trevonn** [comment]
Is it possible for that config file to inherit from the main config file? Or would I need to copy over from the main config file?

**Comment by gort818** [comment]
You need to create a new config file per application
