### ISSUE TITLE
Unable to compile MangoHud

### ISSUE THREAD

**Issue by peter099** [flightlessmango/MangoHud#668]
When i execute the command `ninja -C build install` i get this output:

```
$ ninja -C build install 
ninja: Entering directory `build'
[6/63] Generating src/overlay.frag.spv.h with a custom command
FAILED: src/overlay.frag.spv.h 
/usr/local/bin/glslangValidator -V -x -o src/overlay.frag.spv.h ../src/overlay.frag
/usr/local/bin/glslangValidator: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/local/bin/glslangValidator)
[15/63] Compiling C++ object subprojects/spdlog-1.8.5/src/libspdlog.a.p/fmt.cpp.o
ninja: build stopped: subcommand failed.
```

Why is this happening? I am using MX Linux.

**Comment by gort818** [comment]
`GLIBC_2.29' not found`
What version of gblic do you have?

**Comment by peter099** [comment]
I don't have `gblic` package installed, and i can't find such package in debian repository.

**Comment by gort818** [comment]
https://packages.debian.org/search?searchon=sourcenames&keywords=glibc

**Comment by peter099** [comment]
I have only these three packages which i installed but still getting the same error when trying to compile: `glibc-doc, glibc-doc-reference,  glibc-source`. I am using MX Linux 19 not MX Linux 21.

**Comment by gort818** [comment]
Well then your glibc package is too old.

**Comment by peter099** [comment]
So, it's not possible to install mangohud on MX Linux 19?

**Comment by jackun** [comment]
Build it glslValidator yourself: https://github.com/KhronosGroup/glslang
Don't know how annoying it will be so, good luck :P

**Comment by peter099** [comment]
I think i will wait and try to install mangohud when i upgrade to MX Linux 21. I need to upgrade anyway.
