### ISSUE TITLE
Mangohud not working with brawlhalla on pop os.

### ISSUE THREAD

**Issue by Darsh123Par** [flightlessmango/MangoHud#669]
Mangohud is not working in brawlhalla on pop os I have tried many different things like using lutris and changing the launch options I have also tried NODEVICE_SELECT=1. also when using --dlsym the game doesn't start but steam says it's running.
Plss tell me if there is a fix for this 
I also tried proton 6.3.8 and proton ge 7 but nothing worked still

**Comment by Darsh123Par** [comment]
What do you mean ??

**Comment by Leopard1907** [comment]
Building master branch ( latest ) of Mangohud on your own and trying with it. It works with master for me.

![Screenshot_20220114_180936](https://user-images.githubusercontent.com/24878978/149538249-b60f1e1a-8153-4aad-81c7-f8eab0ac0a87.png)

You can build like this (with this order,from terminal):

```git clone --recurse-submodules https://github.com/flightlessmango/MangoHud.git```

`cd MangoHud`

`./build.sh build`

`./build.sh package`

`./build.sh install`

**Comment by Darsh123Par** [comment]
I just used ./build.sh install on master branch

**Comment by Darsh123Par** [comment]
I built it from master and now it is working idk what the issue was so I am now closing this thread
