### ISSUE TITLE
New feature: Allow using modifiers for keybindings

### ISSUE THREAD

**Issue by Faalagorn** [flightlessmango/MangoHud#67]
Another issue that was being talked on Discord, is to allow to use modifiers (alt, shift, ctrl and preferably mod/windows key at least) for the keybindings – that would solve the issue of the MangoHud keybindings colliding with in-game ones.

**Comment by FaithLV** [comment]
Working on this. Almost complete, will make a PR soon.

**Comment by flightlessmango** [comment]
This has been added in develop 1afea91dab5a30bfd9e65968af038ceaf95d3c39
