### ISSUE TITLE
fps_only flag not working?

### ISSUE THREAD

**Issue by BaconCatBug** [flightlessmango/MangoHud#674]
When i use the fps_only flag, I get a blank black box with no info.  Using the latest manually compiled git version of MangoHud
`MANGOHUD_CONFIG=frame_timing=0,cpu_stats=0,gpu_stats=0,fps=1,fps_only`
![image](https://user-images.githubusercontent.com/4897163/150527834-8462e210-2dad-438e-ac55-41bbde131bc6.png)

`MANGOHUD_CONFIG=frame_timing=0,cpu_stats=0,gpu_stats=0,fps=1`
![image](https://user-images.githubusercontent.com/4897163/150528033-d4ebf8db-245c-4916-bc51-35bc1766ae0c.png)

Game: Warframe
Using Lutris with lutris-ge-7.0rc3-1-x86_64

**Comment by gort818** [comment]
Thanks for the report.
Can you try without setting `fps=1`.
I will look into this  later on today.

**Comment by BaconCatBug** [comment]
Hi there. it seems to work if I use a config file (though it's showing the frame timing as well) 
![image](https://user-images.githubusercontent.com/4897163/150549317-16e4c239-e250-4f6c-b227-683e3f30375c.png)

With `frame_timing=0,cpu_stats=0,gpu_stats=0,fps,fps_only`
![image](https://user-images.githubusercontent.com/4897163/150549664-fcc5ed9c-8905-472f-982e-e0f9c469165d.png)

With `frame_timing=0,cpu_stats=0,gpu_stats=0,fps_only` it's the same as `frame_timing=0,cpu_stats=0,gpu_stats=0,fps,fps_only`

**Comment by gort818** [comment]
Ok fixed, another way would be to do `MANGOHUD_CONFIG=frame_timing=0,cpu_stats=0,gpu_stats=0,fps=1,fps_only,legacy_layout=0`

And for the the frametime use `frametime=0`

**Comment by BaconCatBug** [comment]
Oh, fair enough, i didn't realise I was using the legacy elements.

**Comment by terrestrian** [comment]
When I try to use fps_only flag, I get this error.
`MANGOHUD_CONFIG=frame_timing=0,cpu_stats=0,gpu_stats=0,fps=1,fps_only,legacy_layout=0 mangohud glxgears
[2022-02-04 20:04:43.619] [MANGOHUD] [error] [overlay_params.cpp:535] Unknown option 'fps_only'
[2022-02-04 20:04:43.885] [MANGOHUD] [info] [overlay.cpp:678] Uploading is disabled (permit_upload = 0)
[2022-02-04 20:04:43.918] [MANGOHUD] [info] [imgui_impl_opengl3.cpp:418] GL version: 4.6
Running synchronized to the vertical refresh.  The framerate should be
approximately the same as the monitor refresh rate.
X connection to :0 broken (explicit kill or server shutdown).`

**Comment by gort818** [comment]
You need the latest master

**Comment by terrestrian** [comment]
> You need the latest master

Oh, my bad. Thanks.

**Comment by gort818** [comment]
change `background_alpha` or `width`
