### ISSUE TITLE
God of War crashing on startup

### ISSUE THREAD

**Issue by ppascher** [flightlessmango/MangoHud#675]
"God of War" crashes on startup since commit c50c815630752052e7ef6903757658a513e63267 right before the "Sony Interactive Entertainment presents" starts to fade. Rolling back one commit it works fine.

**Comment by gort818** [comment]
Thanks for the report, I can reproduce.

**Comment by ppascher** [comment]
Not sure if this helps or is related: My MangoHud frame limiter (0, 158, 60) gets reset to the first setting of 0 every now and then in this game after having it set to 158 in game. Could this be because a "new vulkan instance" is created as the commit message linked above mentions and this also happens during startup?

**Comment by phush0** [comment]
for me God of War is crashing with anything after `ba583552b5dd48ac3fe8cf271309942aa8197300` and for me it is crashing wineserver not game

**Comment by gort818** [comment]
Can you build the latest master and try again

**Comment by ppascher** [comment]
Works fine now with latest master. Thank you!
