### ISSUE TITLE
Intel GPU/iGPU support in MangoHud

### ISSUE THREAD

**Issue by birdie-github** [flightlessmango/MangoHud#678]
An Intel developer has asked you guys to contact him directly:

https://gitlab.freedesktop.org/drm/intel/-/issues/5018#note_1239562

Please do.

His email address is tvrtko dot ursulin AT intel.com

**Comment by parkerlreed** [comment]
Wait is this why it just freezes trying Vulkan or OpenGL with an iGPU?

![20220205_043104](https://user-images.githubusercontent.com/841440/152636347-53c7b56d-3fcf-4e85-add8-950d2687280b.jpg)
