### ISSUE TITLE
Mangohud Crashes Minecraft

### ISSUE THREAD

**Issue by IIpho3nix** [flightlessmango/MangoHud#681]
# Manghohud Crashes Minecraft's Java 16 and 17 runtime

## Hardware/Software Information

- OS: Arch Linux
- Kernel: 5.16.4-arch1-1
- CPU: Intel i7-7700HQ (8) @ 3.800GHz
- GPU: NVIDIA GeForce GTX 1050 Mobile
- GPU Driver: NVIDIA 510.47.03
- Graphics Platform: Wayland

### Way 1
Launch Minecraft 1.18.1 With Mangohud
#### Requires Minecrafts Built In Java 17 runtime To Be installed
Run The Command Below

`mangohud $HOME/.minecraft/runtime/java-runtime-beta/linux/java-runtime-beta/bin/java`

## Logs
[hs_err_pid10123.log](https://github.com/flightlessmango/MangoHud/files/7982821/hs_err_pid10123.log)

**Comment by jackun** [comment]
What's your system java? It's probably the same LD_LIBRARY_PATH screwing it up.

Try absolute paths:
`LD_PRELOAD=/usr/lib/libMangoHud_dlsym.so:/usr/lib/libMangoHud.so $HOME/.minecraft/runtime/java-runtime-beta/linux/java-runtime-beta/bin/java`

**Comment by IIpho3nix** [comment]
Hello My System Java is Openjdk 11 and using absolute paths seems to fix my issue Thanks!
