### ISSUE TITLE
Logging doesnt work in The Witcher 3 

### ISSUE THREAD

**Issue by Vaynyo** [flightlessmango/MangoHud#682]
MangoHud: 0.6.5 and 0.6.6
Game: The Witcher 3 Wild Hunt GOTY
OS: Ubuntu 20.04 focal
Kernel: x86_64 Linux 5.13.0-28-generic
DE: KDE 5.68.0 / Plasma 5.18.5
Nvidia driver: 470.86.0
Lutris: 0.5.9.1
Wine: 7.1
DXVK: 1.9.4

I open the game through lutris. On version MangoHud 0.6.5 from the repository at the end of the measurement there is only an inscription "Logging Finished". No data with benchmark 0.1%, 1%, 97%, AVG. File with data doesn't create.

On version 0.6.6 which I built from the last commit f61638c. At the end of the measurement I have only 0.1% and 1%. File with data doesn't create also.

<details>
<summary>My MangoHud config in user/.config/MangoHud</summary>

```
toggle_fps_limit=F1
legacy_layout=false
gpu_stats
gpu_temp
gpu_core_clock
gpu_mem_clock
gpu_power
gpu_load_change
gpu_load_value=50,90
gpu_load_color=FFFFFF,FF7800,CC0000
gpu_text=GPU
cpu_stats
cpu_temp
core_load
cpu_power
cpu_mhz
cpu_color=2e97cb
cpu_text=CPU
io_color=a491d3
vram
vram_color=ad64c1
ram
ram_color=c26693
fps
engine_version
engine_color=eb5b5b
gpu_name
gpu_color=2e9762
vulkan_driver
arch
wine
wine_color=eb5b5b
frame_timing=1
frametime_color=00ff00
resolution
vkbasalt
gamemode
custom_text=Session:
exec=printf x11
media_player_color=ffffff
version
background_alpha=0.4
font_size=24
background_color=020202
position=top-left
text_color=ffffff
toggle_hud=Shift_R+F12
toggle_logging=Shift_L+F2
output_folder=/home/pc

```
</details>

![1](https://user-images.githubusercontent.com/98951552/152336553-8318a833-78c9-4241-8184-dcc0c0b722a8.jpg)

I checked logging with this `MANGOHUD=1 vkcube`
And everything works there.

**Comment by laqyx** [comment]
bump, same issue here but with overwatch

**Comment by flightlessmango** [comment]
reopen if still an issue
