### ISSUE TITLE
How do I use MangoHUD with Lunar Client?

### ISSUE THREAD

**Issue by OscarThePupper** [flightlessmango/MangoHud#683]
Basically, the title.
I've not found any tutorial/forum post about this.

**Comment by yavko** [comment]
> Basically, the title. I've not found any tutorial/forum post about this.

I don't think you should be able to, but if it lets you set a wrapper command you should be able to.

**Comment by flightlessmango** [comment]
starting the client with `mangohud` worked fine for me, it's not a great solution but *should* work
