### ISSUE TITLE
Minecraft Crashes with graalvm jdk and mangohud

### ISSUE THREAD

**Issue by yavko** [flightlessmango/MangoHud#686]
When running minecraft with mango hud and the graalvm jdk distribution the game crashes

I have tested this with other jdk distributions and this behavior does not occur with them 

log:
```
Error: LinkageError occurred while loading main class org.multimc.EntryPoint
	java.lang.UnsatisfiedLinkError: /usr/lib/jvm/java-17-graalvm/lib/libnio.so: /usr/lib/jvm/java-17-graalvm/lib/libnio.so: undefined symbol: ipv6_available
```

**Comment by jackun** [comment]
Same https://github.com/flightlessmango/MangoHud/issues/681 ?

**Comment by yavko** [comment]
> Same #681 ?

I don't think but it could be, seems like that issue is on stock openjdk, but this doesn't happen in openjdk for me (and i have tested)

**Comment by jackun** [comment]
Nothing openjdk specific, it's LD_LIBRARY_PATH causing wrong libs being loaded.

**Comment by yavko** [comment]
well this is my wrapper command idk if this helps, this is with the LD preload thing from the other issue you mentioned, and still same error
```
env mesa_glthread=true env Dgallium-drivers=zink env MESA_LOADER_DRIVER_OVERRIDE=zink env env LD_PRELOAD=/usr/lib/libMangoHud_dlsym.so:/usr/lib/libMangoHud.so env MANGOHUD=1 env GAMEMODERUNEXEC=mangohud gamemoderun
```

**Comment by yavko** [comment]
> Remove `GAMEMODERUNEXEC=mangohud`. The issue seemed to be that because LD_LIBRARY_PATH, wrong libnet.so gets loaded, iirc. Also the first `env` is enough, no need to launch bazillion copies of it +1
> 
> `-Dgallium-drivers=zink` seems to be meson configuration option so no use here.

It works now but, how can i use it with zink? Zink gives me insane performance gains?

**Comment by jackun** [comment]
`MESA_LOADER_DRIVER_OVERRIDE=zink` should work if you are using open source mesa drivers. Not all distros build mesa with Zink enabled by default, iirc. Don't know if it helps with perf.

**Comment by yavko** [comment]
> `MESA_LOADER_DRIVER_OVERRIDE=zink` should work if you are using open source mesa drivers. Not all distros build mesa with Zink enabled by default, iirc. Don't know if it helps with perf.

ik zink works since it works, just crashes with mango

**Comment by yavko** [comment]
Resolved! turns out it was the `-Dgallium-drivers=zink` flag!
