### ISSUE TITLE
Knockout City won't run with MangoHud

### ISSUE THREAD

**Issue by LiamDawe** [flightlessmango/MangoHud#687]
Testing out the new Proton 7 with Knockout City and it will not run if using MangoHud, but it works fine without it.

It does produce the game window for a short moment, then quits to the desktop.

What logs / info do you need from me to help with this?

**Comment by LiamDawe** [comment]
Steam Log: https://gist.github.com/LiamDawe/71f56c42f1e286c7c1d608803633cbe2

This is with NVIDIA 2080Ti, driver 510.54

**Comment by flightlessmango** [comment]
The game runs and displays mangohud on my end
Reopen if still an issue
