### ISSUE TITLE
amdgpu.h not found.

### ISSUE THREAD

**Issue by andy155** [flightlessmango/MangoHud#689]
FAILED: src/libMangoHud.so.p/gpu.cpp.o 
ccache c++ -Isrc/libMangoHud.so.p -Isrc -I../../src -I../../include -Isubprojects/imgui-1.81 -I../../subprojects/imgui-1.81 -I../../subprojects/imgui-1.81/backends -I../../subprojects/spdlog-1.8.5/include -I../../subprojects/Vulkan-Headers-1.2.158/include -I. -I/usr/include/libdrm -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -fvisibility=hidden -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++14 -O3 -Werror=return-type -fno-math-errno -fno-trapping-math -Wno-non-virtual-dtor -Wno-missing-field-initializers -Wno-format-truncation -fPIC -pthread -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS '-DPACKAGE_VERSION="v0.6.6"' -DSPDLOG_COMPILED_LIB -DNDEBUG -DSPDLOG_ACTIVE_LEVEL=SPDLOG_LEVEL_INFO -D_GNU_SOURCE -DHAVE_PTHREAD -DUSE_GCC_ATOMIC_BUILTINS -DHAVE_TIMESPEC_GET -DHAVE___BUILTIN_BSWAP32 -DHAVE___BUILTIN_BSWAP64 -DHAVE___BUILTIN_CLZ -DHAVE___BUILTIN_CLZLL -DHAVE___BUILTIN_CTZ -DHAVE___BUILTIN_EXPECT -DHAVE___BUILTIN_FFS -DHAVE___BUILTIN_FFSLL -DHAVE___BUILTIN_POPCOUNT -DHAVE___BUILTIN_POPCOUNTLL -DHAVE___BUILTIN_UNREACHABLE '-DMANGOHUD_ARCH="64bit"' -DHAVE_NVML -DHAVE_XNVCTRL -DHAVE_X11 -DHAVE_DBUS -DHAVE_LIBDRM_AMDGPU -DVK_USE_PLATFORM_XLIB_KHR -MD -MQ src/libMangoHud.so.p/gpu.cpp.o -MF src/libMangoHud.so.p/gpu.cpp.o.d -o src/libMangoHud.so.p/gpu.cpp.o -c ../../src/gpu.cpp
../../src/gpu.cpp:18:10: schwerwiegender Fehler: libdrm/amdgpu.h: Datei oder Verzeichnis nicht gefunden
   18 | #include <libdrm/amdgpu.h>
      |          ^~~~~~~~~~~~~~~~~
Kompilierung beendet.

----libdrm/amdgpu.h: File or directory not found. This is obvious on an Nvidia system. How can I fix this ? 

x11-drivers/nvidia-drivers-510.54
Linux version 5.16.9-gentoo  (gcc (Gentoo 11.2.0 p1) 11.2.0, GNU ld (Gentoo 2.37_p1 p2) 2.37) #2 SMP PREEMPT Wed Feb 16 06:18:19 CET 2022

**Comment by jackun** [comment]
> #include <libdrm/amdgpu.h>

Install libdrm-dev or similar.

**Comment by thesamesam** [comment]
In future, if you hit a problem with Gentoo ebuilds, please file a bug in Gentoo so we can fix it! Thanks a bunch both. Reported downstream as https://bugs.gentoo.org/849749 and we'll get it sorted.

**Comment by andy155** [comment]
Sry at that time I had built the Git version directly, no ebuild ;)
