### ISSUE TITLE
[FEATURE REQUEST] Remember FPS limit per game

### ISSUE THREAD

**Issue by Khrona98** [flightlessmango/MangoHud#690]
I usually use 2 FPS limits so I can toggle between, these being 0 and 138 so I can cap the frame rate in games that doesn't have a FPS limiter or doesn't allow for granular control of the limit.

The problem is that having to toggle it every time I open a game is annoying and manually copying the config file and modifying it for a specific game is not ideal.

Would it possible to implement some way of making MangoHud remember the last used limit per game? Or at the very least make it remember the last one used so it keeps it the next time I open a game?

**Comment by pm4rcin** [comment]
Isn't it duplicate #663?

**Comment by Khrona98** [comment]
> Isn't it duplicate #663?
I didn't see that there were already a similar issue open, but I don't believe it is the same since the issue you mentioned is asking if it is possible to have different limits for each game, while the issue I opened is about having an automated way to do that.

**Comment by kindagoose** [comment]
You can already do that by just creating a separate config file for each app.

**Comment by Khrona98** [comment]
> You can already do that by just creating a separate config file for each app.

Sure, and I mentioned that in the issue, but what I'm asking here is for MangoHUD to remember the toggle I used per-game, so I don't need to manually create a file for every single game I play.

**Comment by kindagoose** [comment]
Oh, sorry. Well there is a temporal solution If you just want to be able to switch between profiles with a shortcut. You can do this by creating a simple script and assigning it to some key combinations in your wm.
Let's say you have two configs called 0 and 138, and have framelimit in each accordingly, then create a bash like this:
```
#!/usr/bin/env bash
case "$1" in
0)
    cp $HOME/.config/MangoHud/0.conf $HOME/.config/MangoHud/MangoHud.conf
;;
138)
    cp $HOME/.config/MangoHud/138.conf $HOME/.config/MangoHud/MangoHud.conf
;;
esac
```
Now set each case to a specific shortcut.

ps. I know this is not the place to discuss it, but I really don't want mangohud to become a mess like rivatuner osd settings. It is simple, beautiful and not bloated.

**Comment by jackun** [comment]
Or set it like `fps_limit=FPSLIIMIT`, then
```
...
sed "s/FPSLIMIT/$1/g"  $HOME/.config/MangoHud/TEMPLATE.conf > $HOME/.config/MangoHud/MangoHud.conf
...
```
(my _sed_ is not very good so ymmv ;)
