### ISSUE TITLE
MangoHUD not showing GPU info

### ISSUE THREAD

**Issue by slashgob** [flightlessmango/MangoHud#698]
New to Linux, running Pop-OS 21.10 with Nvidia 1080Ti with Nvidia 510.54 drivers

using GOverlay, I cannot see the GPU stats in No Mans Sky. 

I've Tried Proton Experimental, 7.0-1 and 5.13-6

Any help
![NMS MangHUD](https://user-images.githubusercontent.com/44810039/156381778-c31d7d7f-ab93-4c38-9335-f1bcc2ac053a.gif)
?

**Comment by Wolfgang0808** [comment]
Hey,
I had the same issue.
I resolved the issue by adding the ppa: sudo add-apt-repository ppa:flexiondotorg/mangohud
then sudo apt update & sudo apt install mangohud
And you should have the latest version installed (which is 0.6.5).

**Comment by slashgob** [comment]
Hey Wolfgang,

Many thanks, this solved the issue! But I first had to install the "add-apt-repository" command / script...

The add-apt-repository utility is included in the software-properties-common package. To install it run the following commands:

sudo apt update
sudo apt install software-properties-common
