### ISSUE TITLE
Issue with GPU load

### ISSUE THREAD

**Issue by ahmed-elsayed2017** [flightlessmango/MangoHud#7]
GPU load = 0% all the time, and it doesn't change at all.

![Darksiders_Genesis](https://user-images.githubusercontent.com/29783425/73702614-f59f2180-46f5-11ea-987a-6a50c90ff5fd.png)

**System information:**
**OS:** Kubuntu 19.10   -   **kernel:** 5.3.0-29
**GPU:** AMD Radeon HD 8750M
**CPU:** Intel core I5 4200M
**Driver:** Mesa 20-dev (obiaf ppa)

**Comment by flightlessmango** [comment]
The problem seems to be that /sys/class/drm/card1/device/gpu_busy_percent can't be read.
 `cat /sys/class/drm/card1/device/gpu_busy_percent`
`cat: /sys/class/drm/card1/device/gpu_busy_percent: Invalid argument`

**Comment by NerosTie** [comment]
In my case, it doesn't even exist.

`cat: /sys/class/drm/card1/device/gpu_busy_percent: No such file or directory`

I think it's a tool for AMD GPUs.

I have a Nvidia GPU + Optimus.

**Comment by jackun** [comment]
@NerosTie where did you get MangoHud? It should go so deep that it complains about gpu_busy_percent, hopefully.

**Comment by NerosTie** [comment]
From AUR on Arch.

**Comment by jackun** [comment]
Strange, did you install it just today?

**Comment by NerosTie** [comment]
Yes, like 1 hour ago.

**Comment by jackun** [comment]
Oof, which one? This https://aur.archlinux.org/packages/mangohud ?

**Comment by NerosTie** [comment]
This one and lib32-mangohud.

**Comment by jackun** [comment]
Bizarre. Only `cat` usage is 
`src/overlay.cpp:831:      ram =  exec("cat /proc/meminfo...
src/overlay.cpp:833:      cpu =  exec("cat /proc/cpuinfo...
src/overlay.cpp:837:      os = exec("cat /etc/*-release...`

**Comment by NerosTie** [comment]
Because it's a `fopen` command in a cpp code:
`amdGpuFile = fopen((path + "/device/gpu_busy_percent").c_str(), "r");`

But it's the case you have an AMD GPU.

For Nvidia:
```            if (device_data->gpu_stats) {
              // get gpu usage
              if (device_data->properties.vendorID == 0x10de)
                 pthread_create(&nvidiaSmiThread, NULL, &getNvidiaGpuInfo, NULL);
```

But I don't know how it works.

**Comment by jackun** [comment]
Check if `libnvidia-ml.so.1` exists. It should be somewhere in `/usr/lib/x86_64-linux-gnu/`. Could be installed by `libnvidia-compute` package.

**Comment by NerosTie** [comment]
```
whereis libnvidia-ml.so.1                                                
libnvidia-ml.so: /usr/lib/libnvidia-ml.so.1 /usr/lib/libnvidia-ml.so
```

**Comment by flightlessmango** [comment]
@NerosTie what nvidia GPU is it?

**Comment by NerosTie** [comment]
Geforce GT 730M

**Comment by flightlessmango** [comment]
@NerosTie I think your problem is actually related to #3. The gpu is too old and does not play well with NVML, the solution is probably to implement a separate branch that uses nvctrl instead of NVML

**Comment by ahmed-elsayed2017** [comment]
It is right there, why is it not working?

![Screenshot_20200206_173358](https://user-images.githubusercontent.com/29783425/73951908-f65ad200-4906-11ea-8521-bfab214068b5.png)

**Comment by flightlessmango** [comment]
I think this issue is more or less 'resolved' as the GPU is not supported. Feel free to open up the issue again if that's not correct
