### ISSUE TITLE
How do you mangohud with lunar client?

### ISSUE THREAD

**Issue by stealthekills** [flightlessmango/MangoHud#704]
As the title says how do i run mangohud with lunar client?

**Comment by jackun** [comment]
Seems, you don't. I couldn't find where you can add custom launch options to minecraft but maybe there is one.

**Comment by Freejack01** [comment]
There is instructions to do it with a launcher I have done it with ATLauncher. Do a google search for mangohud minecraft ATLauncher, it should give you the information.

**Comment by flightlessmango** [comment]
`mangohud --dlsym lunarclient` works just fine
