### ISSUE TITLE
breaks trails of cold steel 3

### ISSUE THREAD

**Issue by zany130** [flightlessmango/MangoHud#705]
using any recent git version (was able to reproduce on versions as far back as https://github.com/flightlessmango/MangoHud/commit/aab8730f69ba16b95d542650ab489e7b05d2d88d) prevents the game from even starting clicking play does nothing (even though if you try to hit play again steam says it is already running) using version 6.6 game loads normally but a previously mentioned issue happens on the version https://github.com/flightlessmango/MangoHud/issues/639

**Comment by zany130** [comment]
I got the game to start with proton 6.3-8 instead of 7.0-1 which does nothing but just black screens. Interestingly this always happens when I start the game from its launcher (by using the config play action in steam) and only sometimes happens when launching the game directly. In both cases, the issue is fixed by disabling mangohud. any ideas @flightlessmango ?

**Comment by flightlessmango** [comment]
runs fine here
![image](https://user-images.githubusercontent.com/42713625/158026169-5d5f792b-a4d8-4690-ba6d-95e65144e0af.png)

You could double check that this isn't the same #701

**Comment by zany130** [comment]
yeah was thinking that too but I'm on the latest git (which supposedly fix that right?) and disabled the game mode option in the mangohud config. Trying to get proton logs of with mangohud and blackscreen vs without mangohud and no blackscreen

**Comment by zany130** [comment]
may in fact be related to https://github.com/flightlessmango/MangoHud/issues/701 as removing `gamemoderun` from the steam launch commands (not the mangohud config) does allow the game to start up like normal consistently. I noticed @flightlessmango  weren't using game mode so that gave me the idea

**Comment by zany130** [comment]
so I have been able to reproduce this in several other games and even in vkcube by running
`gamemoderun mangohud vkcube` in a terminal

**Comment by zany130** [comment]
fixed in latest master. just tried upgrading dbus back to 1.14 and no issues here

**Comment by jackun** [comment]
Where did it hang with vkcube?

**Comment by zany130** [comment]
> Where did it hang with vkcube?

it just wouldn't run at all after entering `gamemoderun mangohud vkcube`  nothing would happen. works on latest git though but wasn't working as of the time I posted the above comment
