### ISSUE TITLE
FEATURE REQUEST: incremental frame counter overlay

### ISSUE THREAD

**Issue by WAZAAAAA0** [flightlessmango/MangoHud#708]
Requesting MangoHud to add a basic Framecounter to the overlay that updates by 1 every game frame.

Some of the possible use cases could be: manually inspecting your recordings frame-by-frame to detect frame drops, calculating the duration of in-game actions with ease, or maybe even acting as an accurate timer for "speedruns".
Such a function would benefit the most from being implemented into software that hooks into pretty much every game and graphic API, such as RTSS, MangoHud, Bandicam and the likes.

There's only 2 specific programs capable of achieving this already that I'm aware of:
libTAS https://giant.gfycat.com/DeterminedEmotionalHuia.webm
RenderDoc https://giant.gfycat.com/OptimalBronzeJackal.webm
libTAS has little compatibility with anything. RenderDoc is multi-platform but it doesn't really work on older OpenGL versions. And both can get pretty clunky to work with.

**Comment by jackun** [comment]
Don't know about the layout :confused:  but add `framecount` option to show: https://github.com/flightlessmango/MangoHud/tree/framecount

**Comment by WAZAAAAA0** [comment]
Looks good to me, nice. It's properly right-aligned. I tested the theoretical limit of the number for science and it seems to be 18446744073709551615 (max UInt64 integer), after which it overflows to 0 and continues as normal.

**Comment by WAZAAAAA0** [comment]
added with https://github.com/flightlessmango/MangoHud/pull/709
