### ISSUE TITLE
Is log_interval 0 the intended way to log every frame?

### ISSUE THREAD

**Issue by Kenajcrap** [flightlessmango/MangoHud#716]
I just wanted to make sure I'm not missing anything. I wanted to log frametime for every frame, and I was wondering if `log_interval 0` has that intended behavour or if that's not guaranteed.
I see from [this line](https://github.com/flightlessmango/MangoHud/blob/16a132a52477e7bc470905ebe08c3077ed81bcf3/src/logging.cpp#L197) that it might just make the program not sleep? But I'm not clear on if that is actually the case or if it causes any issues, as I'm not really a developer.
If it's the case, I think it would be helpful to mention that in README.md
Thank you for your work on this tool. It's super useful!

**Comment by flightlessmango** [comment]
Yes log_interval 0 is the intended way to log every frame, it takes a slightly different code path with no pause
