### ISSUE TITLE
GPU usage and temperature stuck at 0

### ISSUE THREAD

**Issue by nz0543** [flightlessmango/MangoHud#717]
![Screenshot_20220329_190109](https://user-images.githubusercontent.com/88095511/160608118-906547d5-372a-4071-a80d-7b75b9abc5c7.png)
I found this bug where the GPU usage and temperature doesn't update and is stuck at 0. I am using mangohud-git from the AUR, this issue does not occur when using mangohud from AUR. 
My hardware is: 
CPU: AMD Athlon Silver 3050U with Radeon Graphics
GPU: AMD ATI Radeon Vega Series / Radeon Vega Mobile Series
Linux Distro: Arch Linux

**Comment by jackun** [comment]
Does sysfs file `/sys/class/drm/card0/device/gpu_metrics` exist? Apparently it can give zero values for some devices.
How many gpu stats actually still work? Can you post igpu device id (`lspci -nn| grep VGA` or `cat /sys/class/drm/card*/device/device`)?

Also, seems APUs need to updated to [newer bioses](https://github.com/torvalds/linux/blob/d888c83fcec75194a8a48ccd283953bdba7b2550/drivers/gpu/drm/amd/pm/powerplay/hwmgr/smu10_hwmgr.c#L1291) for gpu load, at least.

**Comment by nz0543** [comment]
gpu_metrics file does exist, but it says it's an empty document. Is that normal?
![Screenshot_20220330_165513](https://user-images.githubusercontent.com/88095511/160804771-35c373a7-d5c4-472a-9225-86f84725f60c.png)

The device id's do show up: 
```
lspci -nn | grep VGA
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Picasso/Raven 2 [Radeon Vega Series / Radeon Vega Mobile Series] [1002:15d8] (rev cd)
```
```
cat /sys/class/drm/card0/device/device 
0x15d8
```

How can I update the bios?

**Comment by jackun** [comment]
> How can I update the bios?

If you have to ask, then I guess it's better if you don't :)

**Comment by nz0543** [comment]
```
cat /sys/class/drm/card0/device/gpu_metrics     
cat: /sys/class/drm/card0/device/gpu_metrics: Operation not supported
```
cat didn't work.

**Comment by jackun** [comment]
Do these work?  `cat /sys/class/drm/card*/gpu_busy_percent`  and `cat /sys/class/drm/card*/hwmon/hwmon*/freq*_input`

**Comment by nz0543** [comment]
They all end up with: No such file or directory

**Comment by jackun** [comment]
Oops, missing `/device/`.
 `cat /sys/class/drm/card*/device/gpu_busy_percent and cat /sys/class/drm/card*/device/hwmon/hwmon*/freq*_input, cat /sys/class/drm/card*/device/hwmon/hwmon*/temp*_input

**Comment by nz0543** [comment]
It works now:
```
cat /sys/class/drm/card0/device/gpu_busy_percent            
0
cat /sys/class/drm/card0/device/hwmon/hwmon5/freq1_input 
400000000
cat /sys/class/drm/card0/device/hwmon/hwmon5/temp1_input 
48000
```

**Comment by wael444** [comment]
currently having this same problem.
```
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU106 [GeForce RTX 2060 Rev. A] [10de:1f08] (rev a1)
```

**Comment by wael444** [comment]
Nevermind, as i figured out that my void linux templates have `-Dwith_nvml=disabled` as a argument to the build command. keeping it enabled works.
