### ISSUE TITLE
Multiple Overlapping HUD's

### ISSUE THREAD

**Issue by FireCulex** [flightlessmango/MangoHud#718]
![2022-03-29_19-19](https://user-images.githubusercontent.com/9983630/160737735-01577d81-b914-4a06-86a9-7b261749e897.png)
Trying with Satisfactory from the Epic Store version, adding it as a non steam game and the HUD is displayed twice. I use the toggle 3 times to get the HUD I want to display by itself. 

If I delete MangoHud.conf you can still see the 2 huds overlapping each other:
![2022-03-29_19-33](https://user-images.githubusercontent.com/9983630/160739430-dedef73a-934c-4c2d-bf55-a4b0852fc1f9.png)

Borderlands DXVK is also showing duplicate HUD's and its glitched  keeps refreshing to 0 fps 0% cpu usage...
![2022-03-29_19-28](https://user-images.githubusercontent.com/9983630/160738824-654c5523-ebb3-4f01-ab2e-4351e9193d9b.png)

F.EA.R on the other hand only shows the 1 HUD without all the extra information
![2022-03-29_19-31](https://user-images.githubusercontent.com/9983630/160739166-d2e5afed-eb50-479f-9371-215d75b68a09.png)

Ubuntu 20.04.4 LTS

edit: FEAR kind of gave me a clue. Somehow I also had /usr/bin/mangohud.x86 possibly from the PPA and once I manually removed it no more overlapping huds. its supposed to be /usr/local/bin/mangohud

suggestion: add a check to disallow multiple hooks? I just used the global enable from goverlay.

**Comment by flightlessmango** [comment]
> suggestion: add a check to disallow multiple hooks?

I think that would just lead to other issues, like people complaining that version X is being used but they installed another version. This issue is more recognizable imo

**Comment by FireCulex** [comment]
> I think that would just lead to other issues, like people complaining that version X is being used but they installed another version. This issue is more recognizable imo

Similar to how CapFrameX says "Multiple Processes Detected" could display "Multiple MangoHuds detected". This way the overlay isn't displayed at all instead of it displaying potentially the wrong version.

**Comment by flightlessmango** [comment]
This is usually caused by having multiple version of mangohud installed, I wouldn't say that a mangohud issue

**Comment by Kellsen** [comment]
I have to reopen this thread because I am now encountering the same behaviour and I'm 100% sure I have only 1 instance of MangoHud installed. It's a brand new install of LMDE 6 with current MangoHud Version 0.6.8-2 and goverlay 0.9.1-1 both apt-installed.
ATM I'm only playing 2 games, World of Tanks and Fallout 4 via Steam and it's doing it in both games with the "mangohud %command%" launch option. Any leads how I could track down the issue? It's weird because everything was working perfecty fine on the same machine with the same setup before I reinstalled the OS.

**Comment by flightlessmango** [comment]
> Edit: I did a "apt purge mangohud goverlay"

This does not guarantee that no other mangohud is installed, only mangohud installed with apt.
Generally this issue comes from installing with apt and without it.
Also mangohud 0.6.8 is very old and there's no point making issues on it

**Comment by Kellsen** [comment]
I did a thorough search and encountered that there were multiple instances of libMangoHud_dlsym.so and libMangoHud.so in /lib/mangohud and /lib/x86_64-linux-gnu/mangohud. Deleting the set in lib/mangohud resolved it for me. My suspicion atm is that doing the merge-usr script set something in motion. Dunno. It's sorted now.

**Comment by Kellsen** [comment]
Comment: I installed via apt because compiling it and screwing around made me install my OS anew in the first place :grin: 
Don't ask :wink: 
I don't know why the official Debian sources still only host such an old version. But it does the trick so I'll stick with it.

**Comment by q4a** [comment]
In my case there was additional mangohud folder in  `/usr/lib/mangohud` (most likely left over from installation from source code). So this commands helped me:
```
sudo apt purge mangohud
sudo rm -rf /usr/lib/mangohud
sudo apt install mangohud
```
