### ISSUE TITLE
Opengl vs vulkan vsync values

### ISSUE THREAD

**Issue by kokoko3k** [flightlessmango/MangoHud#72]
Maybe the new opengl vsync options could be cnahged to better reflect what was choosen for vulkan?

I mean... right now is this way:
Opengl
   -1 = Adaptive sync
    0 = Off
    1 = On
    n = Sync to refresh rate / n.

Vulkan
    0 = Adaptive VSync
    1 = Off
    2 = Mailbox (VSync with uncapped FPS)
    3 = On

... i propose to change opengl to:
0 = Adaptive VSync
1 = Off
2 = On
n>2 = Sync to refresh rate / (n-1).

What do you think?

Thanks for MangoHud!

**Comment by flightlessmango** [comment]
these values directly correlate with how it's programmed in OpenGL, I think it makes it unnecessarily complicated and messy to change them

**Comment by jgabor** [comment]
> these values directly correlate with how it's programmed in OpenGL, I think it makes it unnecessarily complicated and messy to change them

I don't disagree, but I'd guess that a big chunk mangohud's users are coming from the "I just switched to Linux and looking for Afterburner/RTSS" crowd, and not the OpenGL programming crowd. So they probably have no clue why these values are different between OpenGL and Vulkan, only that it's something related to their games and that they might need to tweak them.

So having easier-to-understand options might be a good idea, even if it's complicates things a bit in your end. It might even be beneficial as it will prevent these issues from regularly popping up, which I suspect they will as mangohud increases in popularity.

Just my 2 cents. I'm very happy with mangohud regardless, especially the added FPS limiter. It was the final missing piece needed for completing my transitioning to gaming on Linux. So a huge thanks to you, @flightlessmango! :)

**Comment by kokoko3k** [comment]
Anyhow my proposal has still a quirk not directly straightforward for users:
 "n>2 = Sync to refresh rate / **(n-1)**"

**Comment by flightlessmango** [comment]
So far I don't think this has satisfactory solution, I will leave it as is for now
