### ISSUE TITLE
Game resizing

### ISSUE THREAD

**Issue by cronyakatsuki** [flightlessmango/MangoHud#720]
When a game resizes window mangohud's content gets cutted out of view or it just dissapears completely.

System: arch
Version: mangohud-git

**Comment by jackun** [comment]
OpenGL? What game?
Try `gl_bind_framebuffer=0` and/or `gl_size_query=viewport`

**Comment by cronyakatsuki** [comment]
Not opengl, any wine games when changing the resolution. Which would be borderlands 2 and shadow warrior 2.

**Comment by jackun** [comment]
Ok, try reinstalling mangohud-git.

**Comment by cronyakatsuki** [comment]
Still happening.

**Comment by jackun** [comment]
Try reloading config (default Shift_L+F4)

**Comment by cronyakatsuki** [comment]
Reloading the config works.

**Comment by jackun** [comment]
Hmm, did it actually update, version show ...-213-..? If so, then there's some other issue too :weary:

**Comment by cronyakatsuki** [comment]
Yes it does.
Version: 0.6.6.1.r213.g1f90b0b-1

**Comment by cronyakatsuki** [comment]
It's fixed, everything now works as expected
