### ISSUE TITLE
Benchmark displaying incorrect values

### ISSUE THREAD

**Issue by FireCulex** [flightlessmango/MangoHud#722]
![2022-03-31_16-09](https://user-images.githubusercontent.com/9983630/161164303-06a8b138-eecb-472a-afa2-ea48170a562b.png)

I have a log_duration of 90s. I open the CSV, sort from worst to best, average the first 9 values, I get 42 fps. MangoHud's displays 60. The other reason I think this is rather unlikely is Windows shows 44 fps for the 1%.

Same with 5%, average 45 of the worst values gives me 62 fps. Exactly inline with Windows results, but MangoHUD display shows 80.

**Comment by flightlessmango** [comment]
The fps values are averaged in 0.6.6 and earlier, it's been changed in master

**Comment by FireCulex** [comment]
I assumed incorrectly I was on master, somehow I got switched onto develop. Thanks!
![2022-03-31_16-32](https://user-images.githubusercontent.com/9983630/161166514-07eabd10-02bb-4512-8b58-0b5d10133ee4.png)
Still displays bad 5% value, and if u notice when using using benchmark_percentiles= it shows 1% and 0.1% twice.

**Comment by flightlessmango** [comment]
Yeah I messed up a bit there, It will always show .1 and .01 percentiles, so you don't need to add those in the config. should be fixed either way.

are we sure the 5% value is incorrect? it's the 5th percentile, not 5 percent

**Comment by flightlessmango** [comment]
> and if u notice when using using benchmark_percentiles= it shows 1% and 0.1% twice.

I missed that you were not setting anything, that seems like a clear bug, I will look into it

**Comment by FireCulex** [comment]
> are we sure the 5% value is incorrect? it's the 5th percentile, not 5 percent

You are right, we want the 5th percentile, not the 5% low. 

Lets keep it simple. 100 seconds. 100ms interval. Sort A->Z. row 10 should be P1 and row 50 should be P5 yes?
![2022-03-31_20-19](https://user-images.githubusercontent.com/9983630/161188932-196e2d4e-f09d-4d07-9de5-fcef245a5315.png)

**Comment by flightlessmango** [comment]
Yes I think that's correct

**Comment by flightlessmango** [comment]
There has been changes to these parts a few times since, reopen if still an issue
