### ISSUE TITLE
Overlay Flatpak Opengl

### ISSUE THREAD

**Issue by TheDrifter363** [flightlessmango/MangoHud#726]
Hey guys,

I wasn't sure who to contact about the flatpak. So I installed the freedesktop flatpak, and I have mangohud working with vulkan games, but anything with opengl won't work. For example, I use polymc for minecraft, the flatpak, and I get no overlay. I have mangohud installed in Debian 11, on both my system and the flatpak. I'm not sure how to fix this, so I just thought I'd ask.

On another note, the flatpak overlay I don't know how to customize the config file. I use my Goverlay for my system and it create a MangoHud.conf in ~/.config/MangoHud/MangoHud.conf. That's fine for system applications, it doesn't work for flatpak.

Let me know if there's a way to fix this, I might just not be understanding the nuances of flatpak. I know stuff is sandboxed.

**Comment by jackun** [comment]
No idea, but seems you need to have your app built with 21.08 SDK which PolyMC luckily is.
In `Settings > Custom Commands`, set  `Wrapper command`  to `/usr/lib/extensions/vulkan/MangoHud/bin/mangohud --dlsym`.
Ideally just `mangohud --dlsym` could work too but doesn't seem to for me.

**Comment by TheDrifter363** [comment]
> 

Hey thanks so much this worked! So the config override works great with all my applications. I'm using flatseal. Thing is how would I do this /usr/lib/extensions thing with other applications. Like pcsx2, or dolphin, or yuzu, etc.

**Comment by jackun** [comment]
There's `---command` option for custom entrypoint, maybe something like `flatpak run --command="bash /usr/.../mangohud <actual executable>"`.

**Comment by TheDrifter363** [comment]
> There's `--command` option for custom entrypoint, maybe something like `flatpak run --command="bash /usr/.../mangohud <actual executable>"`. For vulkan just add `--env=MANGOHUD=1` override.

Hey jackun quick question, so you mentioned this command. Thing is how would I know where the executable is in the flatpak sandbox. So for example, I'm using the Ryujinx flatpak, a Switch emulator. Mangohud doesn't show up in the opengl backend. Could I chroot into the sandbox, and find out where the executable is? I know docker has a command that does that, docker exec.

**Comment by jackun** [comment]
Pretty noob about flatpaks myself, but well yeah, `--command=bash`. Seems it's the ["command" parameter in yaml](https://github.com/flathub/org.ryujinx.Ryujinx/blob/afdeb5e22afbec1ce37e8c3ea5ee5434076c4be5/org.ryujinx.Ryujinx.yml#L21) so `ryujinx-wrapper` for Ryujinx's flatpak.

**Comment by TheDrifter363** [comment]
> Pretty noob about flatpaks myself, but well yeah, `--command=bash`. Seems it's the ["command" parameter in yaml](https://github.com/flathub/org.ryujinx.Ryujinx/blob/afdeb5e22afbec1ce37e8c3ea5ee5434076c4be5/org.ryujinx.Ryujinx.yml#L21) so `ryujinx-wrapper` for Ryujinx's flatpak.

So I'm trying this command:
```flatpak run --branch=stable --arch=x86_64 --command="bash /usr/lib/extensions/vulkan/MangoHud/bin/mangohud ryujinx-wrapper" --file-forwarding org.ryujinx.Ryujinx @@ @@```

and it just not working. It's throwing out this error:
```bwrap: execvp bash /usr/lib/extensions/vulkan/MangoHud/bin/mangohud ryujinx-wrapper: No such file or directory```

This is, if I get rid of the bash and /usr/lib/extensions/*, and just have ryujinx-wrapper after command=, it works fine. So I don't know why this is happening. Any ideas?

**Comment by jackun** [comment]
Probably not setting PATH then, use absolute filename `/app/bin/ryujinx-wrapper`

**Comment by TheDrifter363** [comment]
> Maybe flatpak run --command="bash" org.ryujinx.Ryujinx /usr/lib/extensions/vulkan/MangoHud/bin/mangohud --dlsym /app/bin/ryujinx-wrapper

Sweet this actually works! Now why does it work this way, and not the other way you were telling me about. That's weird.

**Comment by jackun** [comment]
execvp thinks all of it is a single filename, instead the other way passes it as arguments to bash.

**Comment by Splarkszter** [comment]
I have mangohud both built and installed by flatpack... but PolyMC is still unable to either detect it or run it with a wrapper command.

I even updated the $PATH and nothing.

**Comment by Splarkszter** [comment]
installing the flathub vulkan layer solved it not being displayed on Minecraft

**Comment by Edgars-Cirulis** [comment]
> installing the right flathub vulkan layer solved it not being displayed on Minecraft (PolyMC still doesn't detect it, but i have the global enable option on the MangoHud config so it "works" then)

Use PrismLauncher..

**Comment by Splarkszter** [comment]
> Use PrismLauncher..
They are the same

**Comment by Edgars-Cirulis** [comment]
> > Use PrismLauncher.
> 
> They are the same

Nope, and never. PrismLauncher is fork of PolyMC / MultiMC.. PrismLauncher have original contributers from polymc now its dead.

https://github.com/PolyMC/PolyMC

https://github.com/PrismLauncher/PrismLauncher

^ a lot fixed bugs

and https://github.com/PrismLauncher/PrismLauncher/pull/965

**Comment by Jan200101** [comment]
Hello, I'm the person who wrote the MangoHud integration for PolyMC and PrismLauncher.

> I have mangohud both built and installed by flatpack... but PolyMC is still unable to either detect it or run it with a wrapper command.
> 
> I even updated the $PATH and nothing.

MangoHud support is broken on PolyMC due to a bugfix that I didn't know about.
Its been fixed in PrismLauncher, but PolyMC is unlikely to see a fix (despite the maintainers being informed how to fix it)

**Comment by Edgars-Cirulis** [comment]
> Hello, I'm the person who wrote the MangoHud integration for PolyMC and PrismLauncher.
> 
> > I have mangohud both built and installed by flatpack... but PolyMC is still unable to either detect it or run it with a wrapper command.
> > I even updated the $PATH and nothing.
> 
> MangoHud support is broken on PolyMC due to a bugfix that I didn't know about. Its been fixed in PrismLauncher, but PolyMC is unlikely to see a fix (despite the maintainers being informed how to fix it)

Never heard story of polymc? https://www.gamingonlinux.com/2022/10/if-you-use-polymc-for-minecraft-you-should-switch-away-now/ pretty sure it's no longer maintained.

**Comment by Splarkszter** [comment]
Oh, well i had it fixed anyway with the flathub vulkan layer thingy.
I only installed PolyMC to be able to download curseforge modpacks so i don't feel the need of switching away. As long as it works it's fine.

Kinda lazy of having to migrate all my configs and data to a new launcher for the 3rd time.

**Comment by Splarkszter** [comment]
> Kinda lazy of having to migrate all my configs and data to a new launcher for the 3rd time.

Update: I ended up switching to Prism :)

**Comment by Edgars-Cirulis** [comment]
> > Kinda lazy of having to migrate all my configs and data to a new launcher for the 3rd time.
> 
> Update: I ended up switching to Prism :)

Any thoughts about prism?

**Comment by Splarkszter** [comment]
> > > Kinda lazy of having to migrate all my configs and data to a new launcher for the 3rd time.
> > Update: I ended up switching to Prism :)
> Any thoughts about prism?

For now it just feels the same as PolyMC (i could say that's a good thing), so if the actual people that have maintained it are on the new one, yeah i think it was worth the trouble.

Only thing is that MangoHUD doesn't load the settings i have set with GOverlay when using the prism launcher. It worked fine while using the wrapper command until i clicked the "Enable MangoHUD" option inside the launcher settings(if it ain't broke don't fix it :/), now it just loads defaults even if i disable it. Any other game i open, loads the settings just fine, only when launching minecraft trough prism doesn't.

**Comment by Calinou** [comment]
See https://github.com/flathub/org.freedesktop.Platform.VulkanLayer.MangoHud/pull/23.

**Comment by flightlessmango** [comment]
I believe this better discussed over at the flatpak
