### ISSUE TITLE
GPU not showing in OpenGL or Vulkan, shows in DXVK

### ISSUE THREAD

**Issue by SteveHeist** [flightlessmango/MangoHud#732]
Using the same settings, in a master MangoHud.conf file, running any OpenGL or Vulkan title shows CPU and framerate, but not GPU. Meanwhile, DXVK shows GPU, CPU, and framerate.

MangoHud.txt is my MangoHud.conf, generated by GOverlay, converted to a text file so that GitHub would let me upload it. Renaming it "MangoHud.conf" should restore it as a configuration file.

[MangoHud.txt](https://github.com/flightlessmango/MangoHud/files/8494533/MangoHud.txt)

**Comment by flightlessmango** [comment]
Intel integrated gpu?

**Comment by SteveHeist** [comment]
I have an Intel iGPU, but at current I'm using a Sonnet eGPU RX 5700 (which DXVK seems to pick up fine but nothing else). Is there a way to manually point MangoHud at that GPU?

**Comment by flightlessmango** [comment]
`pci_dev` `domain:bus:slot:func`

example:
```
lspci | grep -i vga
02:00.0 VGA compatible controller: NVIDIA Corporation GM200 [GeForce GTX 980 Ti] (rev a1)
```
`pci_dev = 0000:02:00:0`

**Comment by SteveHeist** [comment]
That seems to have worked a bit, with the exception that I have to Shift-F4 immediately after launch to get the GPU to show up. It throws errors about missing libnvidia and libXNVCtrl but those are both Nvidia libraries and this is an AMD card. As a result I wouldn't think I'd *need* those?

I've attached a screenshot. The only change between the MangoHud.conf here and the version uploaded is the addition of the pci_dev flag.

[vkcube running](https://user-images.githubusercontent.com/42606649/163554696-60ffeefe-f405-4a16-8d83-75c8a89f52bf.png)
