### ISSUE TITLE
Black Ops 1 does not start when using MangoHud

### ISSUE THREAD

**Issue by ThatGuyAndyy** [flightlessmango/MangoHud#736]
Using Steam, the latest Proton GE or Proton experimental and latest Nvidia drivers to launch Black Ops 1 with Mangohud enabled causes it to instantly crash. When I remove Mangohud from the launch options the game launches without any issues.

**Comment by JuanBarlo** [comment]
NODEVICE_SELECT=1 mangohud %command% doesnt work either

**Comment by flightlessmango** [comment]
![image](https://github.com/flightlessmango/MangoHud/assets/42713625/cbbdb8c4-8557-4ff7-b375-a2a1885b4ee6)
Works fine here, reopen if still an issue
