### ISSUE TITLE
[BUG] Adding option to MANGOHUD_CONFIG overwrites entire MangoHud.conf

### ISSUE THREAD

**Issue by Generator** [flightlessmango/MangoHud#74]
### Description:
Adding custom options to `MANGOHUD_CONFIG` ignore all settings from `MangoHud.conf`

**Config:** `$HOME/.config/MangoHud/MangoHud.conf`
```
cpu_stats
gpu_stats=0
frame_timing=0
font_size=14
position=top-left
ram
vram
background_alpha=0.2
toggle_hud=F12
toggle_logging=F2
control=1
```

**Default:** `MANGOHUD=1 vkcube`
![mangohud-default](https://user-images.githubusercontent.com/44146/76707248-78e46780-66e5-11ea-889c-f895d1e31c35.png)

**Custom:** `MANGOHUD=1 MANGOHUD_CONFIG=gpu_stats=0 vkcube`
![mangohud-issue](https://user-images.githubusercontent.com/44146/76707279-a8936f80-66e5-11ea-8379-ebd2ac065bd7.png)

**Version:** b0f36fa

**NOTE:** Issue not present on >=v0.2.0

**Comment by flightlessmango** [comment]
This behavior is intended, if you want it to read the config file as well you can add `read_cfg` to the beginning of `MANGOHUD_CONFIG`

**Comment by Generator** [comment]
adding  `read_cfg` solved the issue
 `MANGOHUD_CONFIG=read_cfg,vram=0`
