### ISSUE TITLE
[Feature] Please add support LatencyFleX

### ISSUE THREAD

**Issue by guglovich** [flightlessmango/MangoHud#742]
At the end of the manual it says about the MangoHud fork with custom graphics support, but I'd like to see support in this major version as LFX is a promising library for players.

https://github.com/ishitatsuyuki/LatencyFleX#dxvk-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

**Comment by flightlessmango** [comment]
I'm not sure why @ishitatsuyuki hasn't PRd it here, but he's welcome to do so

**Comment by ishitatsuyuki** [comment]
My branch still has several hardcoded constants like min/max values and I haven't had the time to refine it until now. I'll try to get some time for an upstreaming PR in the future.

**Comment by ishitatsuyuki** [comment]
I don't have the time to work on right now, so I think maybe we close this for being too stale. I'll consider other approaches such as plumbing the latency value through NV's LL2 API in the future.
