### ISSUE TITLE
Wrong GPU name for OpenGL

### ISSUE THREAD

**Issue by Kzimir** [flightlessmango/MangoHud#744]
I have an issue with my Delta 15 laptop which have a Ryzen 5800H and Navi 6700M.
For Vulkan applications, it's always the 2nd GPU (6700M) which is used so DRI_PRIME is not useful. For OpenGL application, this env variable is needed.

About the issue, with "DRI_PRIME=1 glxgears", MangoHud shows "Cezanne" as GPU name instead of "6700/6800 etc...". The game is correctly launched with the 2nd GPU because i have the orange led on the keyboard (white led when the iGPU is used).

![VKCube and glxgears with dGPU](https://user-images.githubusercontent.com/3606036/166136529-b2c1bfae-492b-4bcf-a163-2501fa9a618f.png)

**Comment by Leopard1907** [comment]
Should be fixed with https://github.com/flightlessmango/MangoHud/commit/e61321717e3c053cf8b82d2ef0d0ae8dc82e2a88
