### ISSUE TITLE
Incorrect fps and frame latency in GTA 5 on "vsync half" setting 

### ISSUE THREAD

**Issue by TURING-V2** [flightlessmango/MangoHud#749]
GTA 5 dx11 on linux dxvk-async 1.10.1
 
### VSYNC ON:

![screenshot](https://user-images.githubusercontent.com/29421472/167218917-36430790-d0ab-400e-a85d-ff4faf8b4af9.png)
 

### VSYNC HALF:

![screenfvdvfshot](https://user-images.githubusercontent.com/29421472/167218978-e92d63f9-7210-4169-8f28-51f27268a227.png)
![screenshovfdvdt](https://user-images.githubusercontent.com/29421472/167218985-ef60da53-d20a-4e81-9a5f-7aa0e5f423d7.png)
![screenshvdfvdot](https://user-images.githubusercontent.com/29421472/167218987-1ae6b240-96e1-48ca-87ce-d44ac621b2ba.png)

System Info:
 CPU ; Ryzen 7 4800H
 GPU: Nvidia  1650 TI , driver 510.68.02
 RAM 16GB 3200mhz
 OS: Gentoo Linux , Kernel 5.17.5 , i3wm
 Mangohud Version : 0.6.7

**Comment by flightlessmango** [comment]
What fps does dxvk hud report in these cases?

**Comment by TURING-V2** [comment]
u can see the last three screenshots dxvk hud and gta 5 fps  difference is half

**Comment by flightlessmango** [comment]
No I don't see dxvk hud in those screenshots, I only see mangohud

**Comment by TURING-V2** [comment]
Here it is dxvk hud and mangohud off by half fps on vsync half setting only 

![screenshot](https://user-images.githubusercontent.com/29421472/167288260-034770c6-2c8f-4331-9005-c3bd2db29a2e.png)

**Comment by flightlessmango** [comment]
Had a conversation with the dxvk dev, while the value is incorrect it is working as intended. dxvk is sending multiple frames to get the correct behavior and mangohud can't and shouldn't try to work around that
