### ISSUE TITLE
MangoHud 0.6.7 seems to be causing framerate inconsistency

### ISSUE THREAD

**Issue by carxt** [flightlessmango/MangoHud#751]
When using MangoHud 0.6.7, graphical applications seem to get worse performance. Sometimes it dips to below 30. This behavior is independent of window manager, compositor, or Xorg/XWayland. The issue does not happen with 0.6.6-1.
Steps to reproduce:
* Use MANGOHUD_CONFIG=fps_limit=240 mangohud glxgears on 0.6.7 . The framerate will fluctuate well beyond margin of error, often up to 10 FPS less. glxgears will report the same.
With MangoHud 0.6.6-1, the framerate does not fluctuate beyond margin of error.

Relevant information:
Kernel 5.17.4-1 (openSUSE Tumbleweed)
AMD Ryzen 7 5700X
RTX 3070 (Using the propietary driver)
KDE Plasma 5.24.5 (Although tested on Openbox, IceWM, and Wayfire too)

**Comment by flightlessmango** [comment]
I believe this was fixed here 19fbd9bf9b37f31ab6360c9870e21789c99b5293

**Comment by carxt** [comment]
Works flawlessly, thanks.
Closing.
