### ISSUE TITLE
GOverlay wont open GUI since upgrading to Pop OS 22.04

### ISSUE THREAD

**Issue by InAUGral** [flightlessmango/MangoHud#755]
Since upgrading to Pop OS 22.04 I have noticed that GOverlay doesnt open the GUI anymore. It still runs in the background in every game I have but I was hoping to turn it off. A friend of mine who upgraded has also had this issue. Has anyone else noticed this or know a fix? Already tried reinstalling it to no avail, and as I said the app itself seems to work but just cant open the GUI.

OS: Pop!_OS 22.04 KERNEL: Linux 5.17.5-76051705-generic CPU: AMD Ryzen 9 5900X 12-Core GPU: AMD Radeon RX 6900 XT (sienna_cichlid, LLVM 13.0.1, DRM 3.44, 5.16.19-76051619-generic) GPU DRIVER: 4.6 Mesa 22.0.1 RAM: 32 GB

**Comment by flightlessmango** [comment]
GOverlay is a separate project, it would be better to file an issue over at their github https://github.com/benjamimgois-zz/goverlay
