### ISSUE TITLE
rootless install method?

### ISSUE THREAD

**Issue by hjri** [flightlessmango/MangoHud#76]
0.2.0 just used symlinks in user directory, pointing to built files  
0.3.0 wants root access to install everything systemwide  

so, 0.3.0 is practically unusable to me with absence of proper debian packages. Would be cool to still have rootless installation method around

**Comment by flightlessmango** [comment]
A debian package is being worked on #34 as we speak.
But other than that, you can quite easily just install 0.2.0 and replace the .so files in `~/.local/share/MangoHud` and then the vulkan layer should work. 
for opengl you would need to preload both or either of the 32/64bit libs 
`LD_PRELOAD=$HOME/.local/share/MangoHud/libMangoHud.so`
