### ISSUE TITLE
Blacklist Paradox Interactive Launcher

### ISSUE THREAD

**Issue by carif** [flightlessmango/MangoHud#763]
Games from Paradox usually start a launcher before launching the game. Would be nice if MangoHud blacklists that launcher.

**Comment by gort818** [comment]
What is the name of the executable?

**Comment by MinecraftPlaye** [comment]
> What is the name of the executable?

The files I found that start the launcher on double-click:

- bootstrapper-v2 _(within .paradoxlauncher)_
- Launcher  _(within .paradoxlauncher/launcher-v2.2022.7)_
- dowser _(within the Stellaris and Cities: Skylines Game folder)_

Tested for Stellaris and Cities: Skylines

**Comment by MinecraftPlaye** [comment]
> `Launcher` seems like the most obvious choice, can you add this to your conf file and see if it works? `blacklist=Launcher`

Works in Stellaris. 
Couldn't test it in Cities Skylines as I'm not sure how to add mangohud to the launch options as I'm already passing through custom resolution settings via the steam launch option.

**Comment by flightlessmango** [comment]
@gort818 can you fix and close this issue?

**Comment by gort818** [comment]
Not sure how I missed this one, Closed with d1d44f94c9b067a5b99099292822bcfc37d591a6
