### ISSUE TITLE
Feature request: -Duse_system_imgui

### ISSUE THREAD

**Issue by Atemu** [flightlessmango/MangoHud#764]
Hi there, we at Nixpkgs currently need to [hackily insert the imgui source into the build](https://github.com/NixOS/nixpkgs/blob/75021339971840c0f34b890e368dbfca10173d83/pkgs/tools/graphics/mangohud/default.nix#L32-L66) but we actually have it [packaged natively](https://github.com/NixOS/nixpkgs/blob/75021339971840c0f34b890e368dbfca10173d83/pkgs/development/libraries/imgui/default.nix).

Could you add a `-Duse_system_imgui` option like there is for spdlog? Thanks.

**Comment by Atemu** [comment]
On a second thought, it seems like imgui isn't discoverable by pkgconfig etc.

I really don't know enough about meson but I'd like to declare where a pre-built imgui can be found.

**Comment by eli-schwartz** [comment]
It looks like this nixpkgs recipe merely copies some *.cpp (as well as *.h) files to `{includedir}`, I wonder how that's supposed to work at all?

**Comment by flightlessmango** [comment]
Is this still relevant?

**Comment by Atemu** [comment]
We need to hack deps into place anyhow, so this doesn't present much complexity.

Header/source deps need to be streamlined in general though. Any sane packaging process restricts internet access during the build and that means we all need to get these sources in through other means beforehand.
