### ISSUE TITLE
MangoHud does not work with "Cities: Skylines"

### ISSUE THREAD

**Issue by MinecraftPlaye** [flightlessmango/MangoHud#765]
Using the following command in Steam:
`mangohud --dlsym %command% -screen-width 3840 -screen-height 1600 `
Also tested with:
`mangohud %command% -screen-width 3840 -screen-height 1600 `

MangoHud does not work with [Cities: Skylines](https://store.steampowered.com/app/255710/Cities_Skylines/). It sometimes pops up and immediately disappear afterwards (before the game has finished loading the main menu). Most of the time, it just doesn't work at all.

Steam is installed via **flatpak** and `org.freedesktop.Platform.VulkanLayer.MangoHud` is installed. (as well as mangohud-wayland and mangohud-common-wayland packages for **Manjaro**)

My configuration file:
```
################### File Generated by GOverlay ###################
fps_limit=144
toggle_fps_limit=F1


legacy_layout=false
gpu_stats
gpu_temp
gpu_load_change
gpu_load_value=50,90
gpu_load_color=FFFFFF,FFAA7F,CC0000
gpu_text=GPU
cpu_stats
cpu_temp
cpu_load_change
core_load_change
cpu_load_value=50,90
cpu_load_color=FFFFFF,FFAA7F,CC0000
cpu_color=2e97cb
cpu_text=CPU
io_color=a491d3
vram
vram_color=ad64c1
ram
ram_color=c26693
fps
engine_color=eb5b5b
gpu_color=2e9762
wine_color=eb5b5b
frame_timing=1
frametime_color=00ff00
media_player_color=ffffff
background_alpha=0.4
font_size=24

background_color=020202
position=top-left
text_color=ffffff
round_corners=0
#GOVERLAY_THEME=mangohuddefault
toggle_hud=Shift_R+F12
toggle_logging=Shift_L+F2
upload_log=F5
output_folder=/home/user
media_player_name=spotify

### Blacklist
blacklist=Launcher
```

**Comment by flightlessmango** [comment]
I assume native cities skyline uses opengl? flatpak mangohud can't do opengl, at least not yet

**Comment by MinecraftPlaye** [comment]
> I assume native cities skyline uses opengl? flatpak mangohud can't do opengl, at least not yet

From all I've found online, yes, it seems like Cities: Skylines is still using OpenGL.

**Comment by jackun** [comment]
Actually, check if this works, in Launch Options add:

`/usr/lib/extensions/vulkan/MangoHud/bin/mangohud --dlsym %command%`

**Comment by MinecraftPlaye** [comment]
> Actually, check if this works, in Launch Options add:
> 
> `/usr/lib/extensions/vulkan/MangoHud/bin/mangohud --dlsym %command%`

I don't have a folder called `extensions` within `/usr/lib`. I do have `libMangoHud.so` and `libMangoHud_dlsym.so` located under `/usr/lib/`.
But just adding `--dlsym` to the `mangohud` command does not work.

**Comment by jackun** [comment]
`extensions` is in flatpak runtime, not on your "main os".

**Comment by jackun** [comment]
I thought you already tested it but i confused it with another issue thread, you can try `gl_bind_framebuffer=0` param in config file

**Comment by MinecraftPlaye** [comment]
> I thought you already tested it but i confused it with another issue thread, you can try `gl_bind_framebuffer=0` param in config file.

That one works as long as I use the full path: `/usr/lib/extensions/vulkan/MangoHud/bin/mangohud --dlsym %command% -screen-width 3840 -screen-height 1600`
But it only works when adding it to the global config. Adding that parameter in a `cities.x64.conf` or `cities.conf` doesn't seem to work. (the executable of the game is, I believe, `Cities.x64`)

**Comment by jackun** [comment]
It's case-sensitive. My half-downloaded install has it as `Cities.x64`

**Comment by jackun** [comment]
Config files are case-sensitive.

**Comment by jackun** [comment]
Assuming you got it working...
