### ISSUE TITLE
No CPU power display (0W) for Ryzen 5600x 

### ISSUE THREAD

**Issue by Blocker696** [flightlessmango/MangoHud#766]
System specs:
- Solus Linux fully updated
- CPU Ryzen 5600x
- MB MSI MAG Mortar B550

Prior to version 0.6.7 the CPU power display worked for me, but only when "using" the INTEL RAPL power "fix" mentioned in the readme (chmod o+r /sys/class/powercap/intel-rapl\:0/energy_uj).
This is strange in itself, but it worked. Without that i would also get 0W display prior to version 0.6.7.

**Comment by deathxxx123** [comment]
I use this:
https://github.com/Ta180m/zenpower3
And all is working.

**Comment by Blocker696** [comment]
Sadly this does not look like an option for me, because Solus does not support dkms. Which means from my limited understanding at least that i cannot install the zenpower3 kernel module (i tried).

Just guessing here:
I suspect the unsupported lm-sensor controller chip "NUVOTON NCT6687-R" could be the problem as for that i do not get more "sensors" output as this:

k10temp-pci-00c3
Adapter: PCI adapter
Tctl:         +29.6°C  
Tccd1:      +29.2°C 

However it worked in version "0.6.6.1" maybe this approach could be a fallback?

**Comment by deathxxx123** [comment]
I was using Solus and i leave it, because they do not support alot things and never will be. For that i move to Manjaro and all problems are gone.
All is working with 5800X3D for me with MangoHud and also ZenMonitor GUI is showing all things for my CPU.

**Comment by stephanlachnit** [comment]
Is it still the only option? 5700X and don't get power consumption on stock kernel.

**Comment by gort818** [comment]
Yep, ever since this https://github.com/torvalds/linux/commit/0a4e668
