### ISSUE TITLE
Some games don't show/record 1.0 % and 0.1 % low, but -nan?

### ISSUE THREAD

**Issue by dataprolet** [flightlessmango/MangoHud#767]
I tried recording benchmarks for Cyberpunk 2077 and GTA 5, but the 1.0 % and 0.1 % always show "-nan" and no output file gets created. It's working for other Vulkan and OpenGL games though. Attached are my system specs:
[system.txt](https://github.com/flightlessmango/MangoHud/files/8721396/system.txt)

**Comment by flightlessmango** [comment]
Have you tried https://github.com/flightlessmango/MangoHud/releases/tag/v0.6.7-1 ?

**Comment by dataprolet** [comment]
Yes, I use Arch Linux and installed mangohud-x11 0.6.7.1-2, lib32-mangohud-x11 0.6.7.1-2 and mangohud-common-x11 0.6.7.1-2.

**Comment by flightlessmango** [comment]
I believe this likely fixed. Re-open if still an issue in 0.7.0
