### ISSUE TITLE
Multiple games freeze when logging data to file.

### ISSUE THREAD

**Issue by thesacredsin** [flightlessmango/MangoHud#768]
Borderlands 3 for instance, when i manually start logging it will crash when I manually stop logging.

**Comment by flightlessmango** [comment]
Should be fixed here 10e17b3153b18ea20ec32f2d58103a78abd8b0e3

**Comment by thesacredsin** [comment]
I am getting this in Borderlands 3(using Heroic launcher) and Red Dead Redemption 2(using Steam) for instance. I am manually starting the capture with F4 and when I stop it, it freezes the game. Video freezes, but audio still works. Had this issue previous on Linux Mint 20.3 and now on Fedora 36. I am on version 0.6.7.1. Is there a way to run them and gather logs for you?

**Comment by flightlessmango** [comment]
That commit is not in 0.6.7-1, you would need to build from master to test if it's fixed

**Comment by thesacredsin** [comment]
Thanks for the help. I tried this and now games no longer freeze, but the capture is not showing metrics just NaN and it seems it no longer outputs the .csv files.

**Comment by thesacredsin** [comment]
I see there is another issue for this: https://github.com/flightlessmango/MangoHud/issues/767
I am using Fedora 36 with Wayland btw, could this be related?

**Comment by thesacredsin** [comment]
So I tested x11 and Wayland and this seems unrelated. For Borderlands atleast, if I choose DX11 it uses DXVK, and captures are showing as expected, if I choose DX12 it uses VKD3D and then captures are showing NaN and no output csv is generated. Is this expected?

**Comment by kyle-mace** [comment]
I have the same issue on several games on my Steam Deck. The Witcher 3 and Monster Hunter Rise are the latest 2 I've found. 
Both are being run from Steam in Desktop mode, and many other games log perfectly fine without the "-NaN" issue.

**Comment by flightlessmango** [comment]
Reopen if still an issue
