### ISSUE TITLE
gamepad_battery always show the same, no precent shown(Xbox One S Controller)

### ISSUE THREAD

**Issue by deathxxx123** [flightlessmango/MangoHud#769]
It's showing only icon with almost full status and never changes, no matter if battery is full or on 20%.
Is there a way to get rid of this icon?
I need to read digital percentage of the battery charge.
I try:
gamepad_battery
and
gamepad_battery_icon

All is the same result. How to disable the icon?

**Comment by gort818** [comment]
What driver are you using for your controller?
Some drivers do not report percentages.
to remove the icon you can do this `gamepad_battery_icon=0` but it might just report `high` `normal` or `low`

**Comment by deathxxx123** [comment]
Its Linux with lastest Xpadneo driver.

**Comment by deathxxx123** [comment]
```
cat /sys/class/power_supply/xpadneo_battery_0/capacity_level
High
```
```
cat /sys/class/power_supply/xpadneo_battery_0/status
Discharging
```
There are no 'capacity' only.

**Comment by deathxxx123** [comment]
For comparison, there are outputs for my wireless Logitech mouse:
```
cat /sys/class/power_supply/hidpp_battery_0/uevent
POWER_SUPPLY_NAME=hidpp_battery_0
POWER_SUPPLY_TYPE=Battery
POWER_SUPPLY_ONLINE=1
POWER_SUPPLY_STATUS=Discharging
POWER_SUPPLY_SCOPE=Device
POWER_SUPPLY_MODEL_NAME=Wireless Mouse MX Master 3
POWER_SUPPLY_MANUFACTURER=Logitech
POWER_SUPPLY_SERIAL_NUMBER=4082-a1-de-f7-2c
POWER_SUPPLY_CAPACITY_LEVEL=Full
```

**Comment by gort818** [comment]
Yeah so it does not report battery percent only `high normal or low`. Mangohud will update with whatever is in `POWER_SUPPLY_CAPACITY_LEVEL=`

**Comment by deathxxx123** [comment]
Yes, if have that option will be more accurate.

**Comment by gort818** [comment]
Sorry, I don't quite understand. If you have what option?

**Comment by deathxxx123** [comment]
Instead mangohud give only battery icon, to alternative show: high, normal, low
for controller battery

**Comment by gort818** [comment]
Use `gamepad_battery_icon=0`

**Comment by deathxxx123** [comment]
Last time i used this, battery icon was still there. So this option has no effect.
Now i have this in config:
```
### Display battery information
# battery
# battery_icon
gamepad_battery
gamepad_battery_icon=0

```
Hmm it's show now: **High**
I swear last times maybe with lower version of mangohud there was still the icon.
Now is fixed. I don't even edit the config from last time.
Thank you for that.

**Comment by gort818** [comment]
Ok I have disabled the battery icon by default. If you want to enable it just add `gamepad_battery_icon` to your conf file.

**Comment by gort818** [comment]
Closing as I believe this issue is solved.
