### ISSUE TITLE
mangohud and lib32-mangohud update error from AUR

### ISSUE THREAD

**Issue by plasticbomb1986** [flightlessmango/MangoHud#77]
Im on Manjaro, currently on testing branch, and wanted to update mangohud.
Until now im usually install both the normal and 32bit packages (withe everything, not just mangohud), but this gave me a little bit of headache with this: 

error: failed to commit transaction (conflicting files)
/usr/share/doc/mangohud/MangoHud.conf.example exists in both 'lib32-mangohud' and 'mangohud'

first i thought a residue file, but after removing the existing packages and installing new, then looking through my drive where its symlink itself from, figured: its happening during install, and after the error, its gets deleted.

I might be wrong by installing both package, then, im sorry to wasting your time, but:
shouldnt the two package use different or symlinked conf or files?

PS: i love it! This hud is just what i wanted to see when im monitoring a game behaviour!

**Comment by flightlessmango** [comment]
If you're talking about https://aur.archlinux.org/packages/mangohud/ this package, then you can see in the comments that people have already noted that it's broken. I'm not the one who maintains that package so I can't do much about it, however you could try the mangohud-git package instead. It should work just fine

**Comment by plasticbomb1986** [comment]
> If you're talking about https://aur.archlinux.org/packages/mangohud/ this package, then you can see in the comments that people have already noted that it's broken. I'm not the one who maintains that package so I can't do much about it, however you could try the mangohud-git package instead. It should work just fine

Ouch. Havent checked the aur pack itself. Im sorry. :)
