### ISSUE TITLE
`vulkan_driver` is empty / no longer reports anything since 0.6.7 release

### ISSUE THREAD

**Issue by Saancreed** [flightlessmango/MangoHud#773]
On the example of `MANGOHUD_CONFIG=vulkan_driver prime-run vkcube`:

0.6.6-1:
![r16](https://user-images.githubusercontent.com/26201033/170797277-24f0b653-a344-46cb-b4a6-274380703bcb.png)

0.6.7:
![r17](https://user-images.githubusercontent.com/26201033/170797291-197f3ddb-9e47-4f51-a424-67b5cb8439d3.png)
 

`git bisect` reveals the following:

```
ac58c30bbc4d5014af957892c52bfec010a662d6 is the first bad commit
commit ac58c30bbc4d5014af957892c52bfec010a662d6
Author: FlightlessMango <flightlessmangoyt@gmail.com>
Date:   Mon Dec 13 14:20:38 2021 +0100

    Use driverInfo for driver name/version instead

 src/vulkan.cpp | 32 ++++----------------------------
 1 file changed, 4 insertions(+), 28 deletions(-)
```

Reverting that commit restores `vulkan_driver`'s functionality on my machine, even on latest `master`. Maybe we should keep that code path in one form or another as some sort of a fallback if `driverInfo` turns out to be useless?

**Comment by flightlessmango** [comment]
I believe this change was made because (at least on mesa) the version was incorrect. Also vkcube is probably one of the only places you will be able to observe this, since it's only vulkan 1.0 or something

**Comment by Saancreed** [comment]
Ah, okay, good to know. Initially I thought it's some more widespread problem because I've encountered a similar issue in one of the games I recently played but now it seems to be working again without any reverts required. So, whatever I saw back then is probably unrelated or just a one–off incident, but I'll try to pay more attention to this in case it happens again in the nearest future.

And if `vulkan_driver` not working on 1.0 instances is a known / wontfix issue, feel free to just close this.

**Comment by un-couteau** [comment]
> I believe this change was made because (at least on mesa) the version was incorrect. Also vkcube is probably one of the only places you will be able to observe this, since it's only vulkan 1.0 or something

![image](https://user-images.githubusercontent.com/65289168/192872411-bfec78d1-3b23-42e8-9e0e-8a575b3f6d00.png)
with forza horizon 4 and in gta 5 using proton-ge still does not show the name of the vulkan

**Comment by flightlessmango** [comment]
Seems to work on my end, re-open if this is still an issue
