### ISSUE TITLE
Doesn't work with MPV vulkan

### ISSUE THREAD

**Issue by Quackdoc** [flightlessmango/MangoHud#774]
Mangohud will not show up with mpv when using vulkan. it does however work when using opengl. 

it doesn't matter if using vo=gpu-next or vo=gpu,

**Comment by jackun** [comment]
Try if explicit "mode" works:

```
sudo cp -v /usr/share/vulkan/implicit_layer.d/MangoHud.json /usr/share/vulkan/explicit_layer.d/MangoHud.json

VK_INSTANCE_LAYERS=VK_LAYER_MANGOHUD_overlay mpv 
```

**Comment by Quackdoc** [comment]
doing either one seems to fix the issue Thanks! one question though, which should be the prefered method? or does it matter?

**Comment by jackun** [comment]
No difference much, afaik
