### ISSUE TITLE
MangoHud Completely Broken on Lutris since 0.6.7.1, Causing CTD of the entire Wine-Stack

### ISSUE THREAD

**Issue by TeusLollo** [flightlessmango/MangoHud#776]
Hi

Currently, MangoHud appears completely non-functional since v. 0.6.7.1 update on my system, causing CTDs. 
When trying to run a windows application on Lutris through Wine, with MangoHud enabled through the Lutris advanced interface, I get an output similar to this (My actual username was redacted and replaced with a generic "Username"), and subsequently a CTD of the entire Wine-Stack and Wine-Server:

lutris-wrapper: Tomb Raider II
Started initial process 6636 from mangohud /home/username/.local/share/lutris/runners/wine/lutris-6.21-6-x86_64/bin/wine /home/username/Games/Tomb Raider II/Tomb2.exe
Start monitoring process.
/home/username/.local/share/lutris/runners/wine/lutris-6.21-6-x86_64/bin/wine: symbol lookup error: /usr/lib32/mangohud/libMangoHud.so: undefined symbol: _ZN6spdlog5sinks18rotating_file_sinkISt5mutexEC1ENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEjjb
Monitored process exited.
Initial process has exited (return code: 32512)
All processes have quit
Exit with return code 32512

Although this output utilizes "Tomb2.exe", this happens with all kinds of windows applications relying upon Direct3D7-8-9-10-11, as far as I can test. Thus, all kinds of Direct3D applications seem to be affected (Don't have Direct3D12 applications to test). The "undefined symbol" seems also to vary depending on utilized .ext, but this is probably to be expected. 
This output also happens both with the generic WineD3D wrapper (When compatible with the executable), and with DXVK. Thus, wrappers seem not to affect output. 
Although the output mentions "lutris-6.21-6-x86_64" Wine version, I can confirm this happens also on lutris-7.2-x86_64 Wine version (Most recent Wine version on Lutris). Similarly, this also happens on older Lutris-Wine versions. Wine version thus seems not to affect output. 
No CTDs happen if MangoHud is disabled through the Lutris advanced interface.

Relevant specs are as follows:
OS: Void Linux
GPU Architecture: AMD Polaris 20 GPU on GCN 4.0 architecture
Kernel: Linux v. 5.15.41
Drivers: AMDGPU OpenSource + MESA RADV + AMD RADV OpenSource 
Libraries: Mesa 21.3.7, Mesa-Dri 21.3.7 Mesa-Vulkan-Radeon 21.3.7, Mesa-Vulkan-Overlay-Layer 21.3.7

Can confirm MangoHud-0.6.5_1 (Previous package installed on my system) was working perfectly. 

Although I could technically revert package version, I'll hold unto if developers need some further outputs. 
Only similar issues I could find is the following:

https://github.com/flightlessmango/MangoHud/issues/772

Except, compared to the aforementioned GitHub issue, MangoHud 0.6.7.1 is non-functional ALSO in Lutris on my end, and I'm away from my Steam machine, thus I can't test MangoHud with Steam. 

Kind Regards, and Thank You for your work

**Comment by jackun** [comment]
Someone built it with shared lib spdlog and you don't have 32bit spdlog.

**Comment by TeusLollo** [comment]
I also posted this into https://github.com/void-linux/void-packages/issues/37365, so let's wait for void developers to chime in.

**Comment by jackun** [comment]
Hmm, header ordering might bork stuff. Haven't really tested with external spdlog/fmt libs.

**Comment by TeusLollo** [comment]
Void Linux utilizes a rather modular external spdlog:

[] libspdlog-1.10.0_1 Fast C++ logging library - libraries
[-] spdlog-1.10.0_1 Fast C++ logging library
[] libspdlog-32bit-1.10.0_1 Fast C++ logging library - libraries (32bit)
[-] spdlog-32bit-1.10.0_1 Fast C++ logging library (32bit)

Packages with "[-]" are NOT installed. Yet, I should still have all the libraries, both 64-bit and 32-bit.
We need to wait for void developers to chime in. Probably just a dependency oversight, but it's my guess.

**Comment by TeusLollo** [comment]
> Hmm, header ordering might bork stuff. Haven't really tested with external spdlog/fmt libs.
> 
> e: works on arch

Then, I guess, it's really a dependency oversight. Please, don't close the issue until void linux developers can chime in. Sorry for bothering.

**Comment by Johnnynator** [comment]
The issue is/was that the MangoHud package in Void was not recompiled for the update to spldog 1.10, which did break the ABI without bumping the soname. https://github.com/gabime/spdlog/issues/2369 (And seemingly not caring about bumping it).

Can be closed.

**Comment by TeusLollo** [comment]
Can confirm it now works. Was indeed an issue relative to recompilation of MangoHud for the update to spldog 1.10, as suggested above. 
I'm closing this.
