### ISSUE TITLE
fps_only=1 makes overlay only 1 column wide

### ISSUE THREAD

**Issue by melzyy** [flightlessmango/MangoHud#777]
with the flag 
![image](https://user-images.githubusercontent.com/71926357/171195263-923e27b9-b171-4cfc-a0c2-91b4a076f26b.png)

without 
![image](https://user-images.githubusercontent.com/71926357/171195810-4657c9bf-bb32-4cb2-829f-ffdfd5125cb5.png)

config: http://ix.io/3Z1d

**Comment by flightlessmango** [comment]
That is intended, because it's intended use is to only show fps

**Comment by melzyy** [comment]
> That is intended, because it's intended use is to only show fps

are there any other ways to hide the game's rendering engine so it only shows FPS instead of ToGL or DXVK etc?

**Comment by ArTBoL** [comment]
> 

i am interested in that too

**Comment by jackun** [comment]
Needs  `legacy_layout=0`. Should maybe force it with fps_only :thinking:

**Comment by gort818** [comment]
Yeah not a bad idea, I will do that
