### ISSUE TITLE
Microstutters with mangohud fps limit

### ISSUE THREAD

**Issue by 1player** [flightlessmango/MangoHud#779]
Experienced in Hollow Knight (Proton/Vulkan).

This is a beefy desktop, it can render the game at 600 fps with no stuttering, as shown by Mangohud's frametime graph. Yet, when I enable mangohud's frame limiter to 58 fps, there's frequent microstutters that do not show up in the frametime graph. The `vsync` option is commented out.

It might only affect Vulkan applications, I've found similar reports of CSGO in Vulkan mode stuttering when mangohud is enabled: https://github.com/ValveSoftware/csgo-osx-linux/issues/2891#issuecomment-1016615173

**Comment by bunkbail** [comment]
If you're on Mesa drivers, it's probably related to this https://gitlab.freedesktop.org/drm/amd/-/issues/2066. Try the suggested workaround on [comment](https://gitlab.freedesktop.org/drm/amd/-/issues/2066#note_1445382).

**Comment by bunkbail** [comment]
Yeah I have a 6900XT myself and the bug drove me crazy before I tried the suggested workarounds on both bug reports. Anyways, I don't think the microstutters is related to mangohud at all.

**Comment by 1player** [comment]
I've been running with the **3D_FULL_SCREEN** profile as described above which eliminated the microstuttering due to frequency switching in all games, but enabling the FPS limiter in MangoHud still makes Hollow Knight stutter.

**Comment by flightlessmango** [comment]
reopen if still an issue
