### ISSUE TITLE
Wrong API displayed

### ISSUE THREAD

**Issue by VortexAcherontic** [flightlessmango/MangoHud#78]
I noticed that in some games (Lust from Beyond - Prologue, it's free) the HUD displays the wrong underlying API as you can see in the screenshot.
DXVK 1.5.5 is used with Direct3D 11 but MangoHUD claims it to be OpenGL.

I ran the game using Proton 5.0-4 via Steam and I am using MangoHUD: 0.3.0
Steam launch options: `DXVK_HUD=full MANGOHUD_CONFIG=position=top-right,cpu_temp,gpu_temp,ram,vram,frame_timing,toggle_hud=F10 PROTON_NO_ESYNC=1 gamemoderun mangohud %command%`

Can I submit more info to narrow down this strange behaviour?

Wrong:
![20200316184607_1](https://user-images.githubusercontent.com/11244092/76786515-a0a40000-67b7-11ea-89a4-3e3370f6450e.jpg)

Correct:
![20200316190229_1](https://user-images.githubusercontent.com/11244092/76787236-de555880-67b8-11ea-9b0e-8ebfe34af6a4.jpg)

Both games where run using Proton 5.0-4, DXVK 1.5.5 and according to DXVK_HUD are using the same version of DirectX 11.
Maybe a dumb question, but is it possible to use OpenGL instead of Direct3D in DirectX 11?

**Comment by jackun** [comment]
Should be fixed in `develop`

**Comment by flightlessmango** [comment]
You can use this package to try out develop [MangoHud-latest.tar.gz](https://flightlessmango.com/MangoHud-latest.tar.gz)

**Comment by VortexAcherontic** [comment]
Fixed in development! Thank you for the fast response :)

![20200316195000_1](https://user-images.githubusercontent.com/11244092/76790604-75bdaa00-67bf-11ea-93d1-b7b29259b0c0.jpg)

@jackun At least there is no option inside the setting menu of the game that it supports OpenGL too. Also the latest development build seems to fix this :)
