### ISSUE TITLE
How easy it is to use this as a library to render arbitrary OSD stuff

### ISSUE THREAD

**Issue by ozancaglayan** [flightlessmango/MangoHud#786]
Hello. Thanks for this nice project. I was able to compile and run the HUD flawlessly on my laptop. I have a project where I actually need to completely customise the content of the HUD to show a `text` which should be passed from another process through IPC mechanisms such as sockets/pipes. To concretise further, what I'm trying to achieve is very similar to a HUD showing the date & time with seconds-precision. How easy this is achievable from Python or C/C++?

Thanks!

**Comment by flightlessmango** [comment]
You can do this pretty easily.
MangoHud.conf
```
legacy_layout=0
exec=date
```
`legacy_layout` makes it so nothing is displayed by default
`exec` runs a bash command and shows the output in the hud

**Comment by ozancaglayan** [comment]
Oh nice. So is the command launched periodically in a tight loop? My logic would be to pass messages from another process. I think I could hack a binary that'll read bytes from a socket and call it with `exec` then.

**Comment by flightlessmango** [comment]
>So is the command launched periodically in a tight loop?

It get refreshed every half second

>Is there a way to launch a dummy app like this?
Yes you could do this, but it's out of scope for mangohud
