### ISSUE TITLE
log spamming

### ISSUE THREAD

**Issue by axet** [flightlessmango/MangoHud#789]
Hello again!

Here is no option to turn off console log spamming like most wine layers allow to do:

      export WINEDEBUG=-all
      export DXVK_LOG_LEVEL=none
      export VKD3D_DEBUG=none

Is here any option for mangohud to disable logging?

**Comment by jackun** [comment]
https://github.com/gabime/spdlog#load-log-levels-from-env-variable-or-from-argv

`SPDLOG_LEVEL=off`

**Comment by axet** [comment]
Thanks! Still showing:

```
WINE VERSION = wine-7.2-1-g29075a2e575 (Staging)
```

**Comment by axet** [comment]
yep. this is overlay.cpp spamming to std::out!!! not even std:err!

https://github.com/flightlessmango/MangoHud/blob/master/src/overlay.cpp#L818

**Comment by axet** [comment]
Maybe next major release having MANGOHUD_LOG variable would make much more sense and flexibility over SPDLOG.

**Comment by gort818** [comment]
I just pushed a commit to allow using `MANGOHUD_LOG_LEVEL` if you want to try it out

**Comment by axet** [comment]
looks fine.
