### ISSUE TITLE
is throttling  option not working correctly

### ISSUE THREAD

**Issue by zany130** [flightlessmango/MangoHud#790]
as  already reported [here](https://github.com/flightlessmango/MangoHud/issues/748) mangohud is always showing powering throttling
 (regardless of gpu core and power usage) also temp throttling randomly shows up to every now and then again regardless of actual temps (see attached images for example)
 
 ![20220618002840_1](https://user-images.githubusercontent.com/25832539/174423076-99b858c2-8d85-4215-be1e-2c1f5031fb72.jpg)
 
 ![20220616220644_1](https://user-images.githubusercontent.com/25832539/174423159-a7901e43-f579-431f-8e0d-6325fa9ea085.jpg)
 
![20220617214646_1](https://user-images.githubusercontent.com/25832539/174423170-3cdaac39-a227-407c-91ef-e94dd5275bbf.jpg)

**Comment by flightlessmango** [comment]
So far I don't have a reason to believe there is a mangohud bug here, we're just showing what the kernel driver is telling us.
I would need to see that the kernel driver output and mangohud output is not the same.
Until then I would assume that it's working correctly or there is a bug in amdgpu

**Comment by zany130** [comment]
how can I check the kernel driver output? I had a look in `/sys/class/drm/card0/device/` and couldn't find anything about throttling

**Comment by flightlessmango** [comment]
It comes from the `/sys/class/drm/card0/device/gpu_metrics` binary, specifically `indep_throttle_status`
You would need to compare the bits hit with this [Throttle map](https://elixir.bootlin.com/linux/latest/source/drivers/gpu/drm/amd/pm/swsmu/smu11/navi10_ppt.c#L240)

**Comment by zany130** [comment]
hmm well was googling a bit and found this which can decode that 
https://gist.github.com/leuc/e45f4dc64dc1db870e4bad1c436228bb

which show all this
```
./amdgpu_metrics.py /sys/class/drm/card0/device/gpu_metrics
/sys/class/drm/card0/device/gpu_metrics
> MetricsTableHeader
structure_size: 120
format_revision: 1
content_revision: 3
> GpuMetrics_v1_3
temperature_edge: 69
temperature_hotspot: 83
temperature_mem: 74
temperature_vrgfx: 72
temperature_vrsoc: 66
temperature_vrmem: 0
average_gfx_activity: 99
average_umc_activity: 18
average_mm_activity: 0
average_socket_power: 185
energy_accumulator: 5305615255852810240
system_clock_counter: 18446472425618014883
average_gfxclk_frequency: 995
average_socclk_frequency: 33
average_uclk_frequency: 33
average_vclk0_frequency: 0
average_dclk0_frequency: 0
average_vclk1_frequency: 2435
average_dclk1_frequency: 1200
current_gfxclk: 1000
current_socclk: 0
current_uclk: 0
current_vclk0: 0
current_dclk0: 0
current_vclk1: 5
current_dclk1: 0
throttle_status: 1050909
current_fan_speed: 80
pcie_link_width: 65535
pcie_link_speed: 65535
padding: 65535
gfx_activity_acc: 4294967295
mem_activity_acc: 4294967295
temperature_hbm: 65535
firmware_timestamp: 18446744073709551615
voltage_soc: 65535
voltage_gfx: 65535
voltage_mem: 1
padding1: 0
throttle_status_flags: PPT0, PPT2, PPT3, SPL, TDC_CVIP
```
but don't really know what to make of it

**Comment by flightlessmango** [comment]
>throttle_status_flags: PPT0, PPT2, PPT3, SPL, TDC_CVIP

Not sure what SPL and TDC_CVIP is, but I think PPT0-3 are power bits.
So according to this mangohud should show power throttling (assuming I remember correctly)

**Comment by zany130** [comment]
It seems like either there also a problem with the script I'm running or the driver is always reporting as power throttled as it always pretty much always shows the same thing as above it's hard to tell with the thermal throttling though as it appears randomly for about a second and goes away (temps never exceed 60c since i have a somewhat aggressive fan curve) so i don't think it should be thermal throttling.

**Comment by flightlessmango** [comment]
both mangohud and the script is reporting the same thing, so I'm gonna assume they are correct.
How do you verify that you're not power throttling?

**Comment by zany130** [comment]
well I'm just going buy if its hitting its max clocks (about 2600) and if the power usage is below the tdp of this card (230w I believe)  

The thing is like you said there are several cases that will trigger "power throtling"  being load limited meaning its saving on power because there is not enough load will also trigger "power throttling" (sidenote on nvidia smi this is reported as load limited not power) so when I test something like vkcube and get low clocks and "power throttling" its because of that case.

There is also the case when the GPU is running full tilt (consistently hitting around 2600mhz)  and drawing about 160w.  that is also being reported as a "power throttling" case 

both of these I guess are to be expected

where I am confused is it can be running at less than its max clock speed) but it does have a load (same game in this case trails of cold steel 3 but I have reproduced with others) and power usage is below 150w) this could be though because of AMD aggressive power-saving on Linux.

the thermal throttling case mangohud is showing I can't explain though and I'm not seeing anything related in the script I'm using to read `/sys/class/drm/card0/device/gpu_metrics`

**Comment by Daniel-Salvado** [comment]
It also reports power and thermal throttling at all times on my system. Which is not the case, especially the thermal throttling doesn't make sense when my card is sitting at room temperature and the fans are idle.

**Comment by flightlessmango** [comment]
> It also reports power and thermal throttling at all times on my system. Which is not the case, especially the thermal throttling doesn't make sense when my card is sitting at room temperature and the fans are idle.

As mentioned before in this thread, it seems that mangohud is reporting exactly what the source is, so this seems to be an amdgpu bug and should be reported upstream or it's intended behavior.
Power throttling for example is normal, your GPU should be power throttling when it doesn't need full power

**Comment by flightlessmango** [comment]
Moving discussion over to #747 since it's the same issue
