### ISSUE TITLE
[feature request] customize layout lines of hud (like amd software)

### ISSUE THREAD

**Issue by XDM-Inc** [flightlessmango/MangoHud#791]
i was wondering if it was possible to change how many lines the hud takes up. example in radeon software you can make all its hud elements span only across one line side by side or 2 lines or group some things together like ram and Vram or clock speeds of both cpu & gpu speed etc.

**Comment by flightlessmango** [comment]
It's still in development but you can do this with the `horizontal` option.

**Comment by XDM-Inc** [comment]
> It's still in development but you can do this with the `horizontal` option.

👍 Nice I'll give it a go.
