### ISSUE TITLE
GPU stats dissapears with Life Is Strange 2

### ISSUE THREAD

**Issue by ahmed-elsayed2017** [flightlessmango/MangoHud#8]
When I use `MangoHud` with `Life Is Strange 2`, GPU stats appears on the launcher, but as soon I press on Play, GPU stats dissapears

**Here is the launcher (GPU appears):**

![Life Is Strange_2](https://user-images.githubusercontent.com/29783425/73801509-50527f00-47c3-11ea-95a8-76d00c93d8d5.png)

**Here is the game itself (GPU disappears):**

![Life Is Strange 2](https://user-images.githubusercontent.com/29783425/73801558-75df8880-47c3-11ea-9d50-421372d2494e.png)

**Comment by jackun** [comment]
If you get a chance, try `jackun_wip` branch. I can test with Tomb Raider and Hitman games, probably behave similarly.

**Comment by ahmed-elsayed2017** [comment]
Building `jackun_wip` branch ends up with an error: `ModuleNotFoundError: No module named 'mako'`

**Comment by jackun** [comment]
Does `sudo pip3 install mako` fix it?

**Comment by ahmed-elsayed2017** [comment]
I don't have the same issue with `jackun_wip` branch.

**Comment by ahmed-elsayed2017** [comment]
Is this fix pushed to master branch?

**Comment by jackun** [comment]
Yep
