### ISSUE TITLE
[Feature Request] rebindable keyboard shortcuts

### ISSUE THREAD

**Issue by hellscyth142** [flightlessmango/MangoHud#804]
Is it possible to add some config options to rebind the keyaboard shortcuts? Right shift + right control is actually a shortcut I use for something. Also, two of the shortcuts are on left control, and one is on the right control. I would prefer to be able to make them all on one side.

**Comment by gort818** [comment]
The option exists already. `toggle_hud=`  key combo here

**Comment by hellscyth142** [comment]
I completely missed that, thanks.
