### ISSUE TITLE
Cannot poll mouse coordinates with xdotool when application is launched through Steam

### ISSUE THREAD

**Issue by aclist** [flightlessmango/MangoHud#805]
If I use the `exec` key to define a command like `exec=xdotool getmouselocation` and then invoke MangoHud directly against an X11 program, e.g., `mangohud glxgears`, the HUD updates with this information and will report the cursor position on the fly.

But when I pass these parameters through to an application launched by Steam (e.g. `MANGOHUD=1 MANGOHUD_CONFIG="custom_text=coords,exec=xdotool getmouselocation,legacy_layout=false" %command%` in the launch options), the label gets drawn, but the coordinates are not captured (also tried writing them to a file, but there was no output). Other one-off system commands work fine when passed through to Steam. 

If I instead launch the game through Steam but without MangoHud, poll xdotool in the background, and hover the cursor over the window, it does capture the coords correctly. So something (Steam overlay?) seems to be blocking MangoHud from permitting xdotool to poll screen space.

**Comment by jackun** [comment]
> sh: 1: xdotool: not found

I think it's running in soldier runtime and it just doesn't have it.
But running from debug script (`PROTON_DUMP_DEBUG_COMMANDS=1` and `/tmp/proton_<user>/run`) though somehow works...

**Comment by flightlessmango** [comment]
You don't have access to xdotool inside soldier runtime, you would need to petition the runtime devs to add it
