### ISSUE TITLE
Mangohud refuses to run on Dragon Age Origin

### ISSUE THREAD

**Issue by jarrard** [flightlessmango/MangoHud#807]
I have been messing with DAO lately and noticed Mangohud refusing to run no matter what I've tried.

First I tried everything in Lutris, no go. So I decided to use native .wine (OGL) in CLI with and without dlsym. I tried with DXVK, no luck.

Mangohud is 100% confirmed installed and working in all other titles tested.

DAO is DX9 but that shouldn't matter?  

Anyone know what might be going on here?

**Comment by flightlessmango** [comment]
32bit game so you might be missing 32bit mangohud.
You can probably try with this binary
[glxgears32](https://cdn.discordapp.com/attachments/641749996001296427/999724898995937371/glxgears32)

**Comment by jarrard** [comment]
Your probably right about the 32bit mangohud thing. Maybe it didn't install with the main package. I'll have to look into it. 

Also the prefix is 64bit but game 32bit so perhaps it gets confused? I'll have to see howto invoke 32bit mangohud.

Close this for now.
