### ISSUE TITLE
Apex Legends when using `exec` in mangohud.conf

### ISSUE THREAD

**Issue by Fijxu** [flightlessmango/MangoHud#809]
OS: Arch Linux, recently updated, nvidia-dkms, linux-zen, GE-Proton7-27
Tested with latest stable mangohud release and git release
Using steam runtime (not the native version)

When i try to open Apex Legends with `mangohud %command%` it just crashes, this happened after i formatted my drive to BTRFS and reinstalled the game, i though it was because i was using a BTRFS partition but i reinstalled (not moved) the game into a NTFS partition and the game crash anyways. I can use other commands like `strangle` and `gamemoderun` without any problems but not with `mangohud`

I tested other games like Fall Guys, Multiversus and BattleBit Remastered, they work well with mangohud

Video: https://ii.zzls.xyz/ZQSHFSV.mp4
systemd-coredump: https://paste.zzls.xyz/qonacozega.sql
coredumpctl: https://paste.zzls.xyz/gumeriqefe.apache
(The extensions of the files are like that because of HasteBin)

**(Edit) Old title of this issue**: "Apex Legends crash with `mangohud %command%`"

**Comment by jackun** [comment]
libstdc++ :-1: 
![image](https://user-images.githubusercontent.com/4328738/182025464-31d9fd25-f63d-42a1-8584-907a57c7d380.png)

**Comment by GloriousEggroll** [comment]
appears to happen due to exec= lines in MangoHud.conf (such as those added by Goverlay when retrieving the system information). Remove exec= lines and it works

**Comment by Fijxu** [comment]
> appears to happen due to exec= lines in MangoHud.conf (such as those added by Goverlay when retrieving the system information). Remove exec= lines and it works

You are correct! Apex only crashes when the mangohud configuration contains `exec` lines.
Thanks GE! 
_Also thanks for your work in Proton ;)_

**Comment by GloriousEggroll** [comment]
This needs to stay open -- the issue is with mangohud's exec= options not working properly.

I've submitted a PR to Goverlay which works around this issue with Goverlay's various check box options:
https://github.com/benjamimgois/goverlay/pull/12

However the actual exec= functionality on the mangohud side still needs to be fixed afaik

**Comment by Snaggly** [comment]
Hello, I still see the same issue however when having enabled "Session" on GOverlay, or having set 'exec=echo $XDG_SESSION_TYPE' in the config file. I don't think it seems to be related to Mangohud itself but libstdc++ ?

**Comment by flightlessmango** [comment]
@Snaggly and you have latest mangohud?
