### ISSUE TITLE
gzdoom vulkan hexen1 crashing with mango

### ISSUE THREAD

**Issue by axet** [flightlessmango/MangoHud#810]
Hello!

I'm experiencing crash within mango library and unable to debug it since gdb does not see the library.

I did report at gzdoom first, but seems like it is not an gzdoom issue:

* https://github.com/ZDoom/gzdoom/issues/1685

I tried to build debug version of mangohud, but gdb does not see it symbols nor see library is loaded.

**Comment by flightlessmango** [comment]
I'm not able to reproduce this, works fine here.
Would be great if you could get gdb output with debug mangohud.
You can use the build.sh script to build debug mangohud `./build.sh clean build_dbg`

**Comment by axet** [comment]
I did it already. gdb does not see libmangohud.so

https://pastebin.com/nt2tU0fL

**Comment by flightlessmango** [comment]
You can use `add-symbol-file` and specify the library, otherwise I don't think you have a debug version.
Make sure you use `./build.sh clean` if you already built before, otherwise it won't change to debug

**Comment by axet** [comment]
I did clean and rebuild. Size of the library is 18M. Release version 2.6M

```
axet@axet-laptop:/media/axet/128GB/source/MangoHud$ ll /usr/lib/x86_64-linux-gnu/mangohud/
total 18452
-rw-r--r-- 1 root root    42600 авг  1 08:11 libMangoHud_dlsym.so
-rw-r--r-- 1 root root 18849200 авг  1 08:11 libMangoHud.so
```

gdb does not show libMangoHud in 'info sharedlibraries' I can not explain that.

**Comment by flightlessmango** [comment]
Did you try the add-symbol-file command in gdb?

**Comment by axet** [comment]
Yes I did.

It seems like debian release of mango has issues. But when I rebuild a library it works fine. I guess I have to report to debian community.

Right now (this week upgrade) mangohud brakes in debian (bookworm).

symbol lookup error: /usr/lib/x86_64-linux-gnu/mangohud/libMangoHud.so: undefined symbol: _ZN6spdlog5sinks18rotating_file_sinkISt5mutexEC1ENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEmmb

I guess debian need to rebuild it anyway. And then try to find the crash if it still be here.

**Comment by axet** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1016209

**Comment by axet** [comment]
Recent release working fine!
