### ISSUE TITLE
AppData validation fails

### ISSUE THREAD

**Issue by tim77** [flightlessmango/MangoHud#812]
Appstream AppData validation tool fails due current icon suggested in: https://github.com/flightlessmango/MangoHud/commit/2dfdb9b584acaa1de129eaf5abdd75aa119c34db#diff-8fcb91ea99eea3a59b198b9eebceb6f45333d84ce73071cc1e1d866d02068549.
Probably due incorrect format which should have equal width and height of icon.

```
$ appstream-util validate-relax --nonet /builddir/build/BUILDROOT/mangohud-0.6.8-1.fc36.x86_64/usr/share/metainfo/io.github.flightlessmango.mangohud.metainfo.xml
/builddir/build/BUILDROOT/mangohud-0.6.8-1.fc36.x86_64/usr/share/metainfo/io.github.flightlessmango.mangohud.metainfo.xml: FAILED:
? tag-invalid           : stock icon is not valid [io.github.flightlessmango.mangohud]
Validation of files failed
```

**Comment by flightlessmango** [comment]
@stephanlachnit ^^

**Comment by stephanlachnit** [comment]
Ah, right.
`appstreamcli validate --strict --pedantic --explain  /usr/share/metainfo/io.github.flightlessmango.mangohud.metainfo.xml` does not fail, but I think it does not check the icon.
Sadly `stock icon is not valid` does not explain a lot. I made the icon square, it still reports it.

**Comment by jackun** [comment]
Might be the stock part in `type="stock"`?

**Comment by stephanlachnit** [comment]
> Might be the [stock](https://github.com/hughsie/appstream-glib/blob/master/libappstream-glib/as-stock-icons.txt) part in `type="stock"`? A.k.a only a whitelist is allowed.

That would be a bug of that tool afaik: https://www.freedesktop.org/software/appstream/docs/chap-CollectionData.html#tag-ct-icon

Stock Icons are just the default icon that would you e.g. also use in a .desktop file.

**Comment by stephanlachnit** [comment]
So yeah I check, this is definitely an issue of that tool: https://github.com/hughsie/appstream-glib/issues/360#issuecomment-633719458
Just ignore the failure, the XML fully complies with the standard.
