### ISSUE TITLE
All Steam games are not starting with mangohud (these are crashing).

### ISSUE THREAD

**Issue by starduxt** [flightlessmango/MangoHud#814]
.OS Debian 11 testing/bookworm (latest updated - 01-Aug-2022).
.Kernel 5.18.0-0.bpo.1-amd64
.GPU RX 5700 XT
.Mesa 22.0.5
.Mangohud version mangohud:amd64   0.6.7.1-1 (downloaded from official Debian 11 testing repository, no newer version than this is available at this time)
About 20 hours ago this was working with all games, strangely there was no system updated even occurred in between. Now all games are not launching at all as long as mangohud is included in commandline. goverlay is crashing with following error.

`/usr/libexec/goverlay: symbol lookup error: /usr/lib/x86_64-linux-gnu/mangohud/libMangoHud.so: undefined symbol: _ZN6spdlog5sinks18rotating_file_sinkISt5mutexEC1ENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEmmb`

-----------------------------------------------------------------------------------------

Following information may help you identify the problem:

command line "sudo apt depends mangohud" returns the following.
```
mangohud
  Depends: libc6 (>= 2.33)
  Depends: libfmt8 (>= 8.1.1+ds1)
  Depends: libgcc-s1 (>= 3.0)
  Depends: <libspdlog1-fmt8>
    libspdlog1
  Depends: libstdc++6 (>= 12)
  Recommends: <mangoctl>
  Suggests: libxnvctrl0
  Suggests: goverlay
```
  
  Here is the version of libraries on my currently updated OS.
  This version number is same for all variants of libraries if there are any (amd64,i386, x32 ...etc)
```
libc6    2.33-8
libfmt8    8.1.1+ds1-2
libgcc-s1    12.1.0-7
libspdlog1     1:1.10.0+ds-0.1
libstdc++6   12.1.0-7
goverlay     0.9-1
libxnvctrl0     470.129.06-1

```
mangoctl is not available for my distribution.

**Comment by gort818** [comment]
Probably related issue here #776

**Comment by starduxt** [comment]
Ah okay thanks, I guess I have to close this here.
