### ISSUE TITLE
i7-10750H cpu_power 0W

### ISSUE THREAD

**Issue by TicTac7x** [flightlessmango/MangoHud#815]
CPU power shows as 0W all the time. GPU power works shows as expected.

![image](https://user-images.githubusercontent.com/75637554/182975435-6752cc83-e2b4-4283-8dbe-32e2bedb9f8c.png)

![image](https://user-images.githubusercontent.com/75637554/182975122-9471ea3a-af82-4f42-a11d-a2875771186f.png)

MangoHud version: `aur/mangohud 0.6.8-1 (+176 9.96) (Installed)`

Output from `sensors`:
```shell
coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +67.0°C  (high = +100.0°C, crit = +100.0°C)
Core 0:        +59.0°C  (high = +100.0°C, crit = +100.0°C)
Core 1:        +57.0°C  (high = +100.0°C, crit = +100.0°C)
Core 2:        +57.0°C  (high = +100.0°C, crit = +100.0°C)
Core 3:        +59.0°C  (high = +100.0°C, crit = +100.0°C)
Core 4:        +58.0°C  (high = +100.0°C, crit = +100.0°C)
Core 5:        +68.0°C  (high = +100.0°C, crit = +100.0°C)

pch_cometlake-virtual-0
Adapter: Virtual device
temp1:        +48.0°C  

BAT0-acpi-0
Adapter: ACPI interface
in0:          12.79 V  

iwlwifi_1-virtual-0
Adapter: Virtual device
temp1:        +43.0°C  

hp-isa-0000
Adapter: ISA adapter
fan1:        2501 RPM
fan2:           0 RPM

nvme-pci-3b00
Adapter: PCI adapter
Composite:    +34.9°C  (low  = -20.1°C, high = +82.8°C)
                       (crit = +86.8°C)
Sensor 1:     +34.9°C  (low  = -273.1°C, high = +65261.8°C)

acpitz-acpi-0
Adapter: ACPI interface
temp1:        +60.0°C
```

**Comment by TicTac7x** [comment]
Fixed by running `sudo chmod o+r /sys/class/powercap/intel-rapl\:0/energy_uj` (like instructed in README, duh...) and restarting the game :)

**Comment by TicTac7x** [comment]
My quick and dirty solution was to edit sudoers file to allow to execute the command as sudo without password and i added the same command to autostart applications.

I added the following line to the end of `/etc/sudoers` (where `user` is your username):
```shell
user ALL=(ALL:ALL) NOPASSWD: /bin/chmod o+r /sys/class/powercap/intel-rapl\:0/energy_uj
```

And this command to autostart applications:
```shell
sudo /bin/chmod o+r /sys/class/powercap/intel-rapl:0/energy_uj
```

**Comment by gitdunk** [comment]
for me @TicTac7x's `visudo` method worked, but I had to use `%wheel` instead of `user`, that's the sudo group for Arch based distros, for others like Ubuntu you should use `%sudo`
