### ISSUE TITLE
MangoHud appears twice in Vulkan games

### ISSUE THREAD

**Issue by HughJass** [flightlessmango/MangoHud#82]
MangoHud appears twice in mangohud overlaping each other. Looks normal in OpenGL games. Older version did not have this issue. I tried the aur package as well as manual install from the release page on github.
![mangobug](https://user-images.githubusercontent.com/24876088/76839705-44cc8c00-6836-11ea-874a-2c530e6975f9.png)

**Comment by jackun** [comment]
Run `./install.sh uninstall` from older version package. There's probably either /usr/share/vulkan/implicit_layer.d/mangohud.json or something  in ~/.local/share/vulkan/implicit_layer.d/

**Comment by HughJass** [comment]
@jackun for the record I removed the aur package before installing manually. But you were right, I had both json files in /usr/... and ~/.local.... removed the ones in /usr/ and now it works. Thanks :)

**Comment by jackun** [comment]
If you installed from release package then /usr one's are the correct ones.

**Comment by HughJass** [comment]
Ok, I restored them and removed the ones in ~/.local
