### ISSUE TITLE
GLFWwindow init unable to identify correct parameters of gamescope left rotated display.

### ISSUE THREAD

**Issue by pastaq** [flightlessmango/MangoHud#823]
On all OXP and some Aya Neo devices, the built in display is a left rotated portrait mode rather than a right oriented portrait mode that exists in most popular devices. Using [this patch](https://aur.archlinux.org/packages/gamescope-plus) are able to get gamescope to rotate to the correct orientation. However, as the MangoHud app pulls the raw window parameters from xwayland/x11, it appears to get a 700x1280 portrait window scaled from the 0 position (top right when orienting the device correctly). This prevents the mangoapp from rendering in the correct location.

Video of the behavior: https://www.youtube.com/watch?v=bNf2VIq4od8

OS: ChimeraOS v35 Unstable
Device: Aya Neo AIR/OXP mini A7
MangoHud versions:
mangoapp 0.6.8-1
mangohud 0.6.8-1
mangohud-common 0.6.8-1

I'm not entirely sure if this is an issue that needs to be solved by mangohud or if it can be accounted for in our [PR for gamescope](https://github.com/Plagman/gamescope/pull/557) that adds the rotation functionality.

**Comment by ruineka** [comment]
This issue seems to start when you are in a game and start to toggle the various levels of stats from the performance overlay. I got everything related to `force-rotation` as well as the KMS props merged into the official gamescope now, so I'm going to dig into this further and try to find the exact culprit.

I was hoping that once I added the orientation quirks to the kernel and gamescope that this issue would go away, but unfortunately that wasn't the case.

**Comment by flightlessmango** [comment]
The mangoapp window was only slightly bigger than the hud itself, meaning it wasn't as big as the screen.
So setting "top-left" didn't translate to top-left of the screen, but top-left of the mangoapp window.
This has been reworked and is not set to a static 1280x800, this can probably be improved by getting resolution from gamescope.

I'm not sure how this impacts your situation, but it should be different if you check out d0a1c4ea075d0d2c31548960470e53d4dbd154c0

**Comment by ruineka** [comment]
> The mangoapp window was only slightly bigger than the hud itself, meaning it wasn't as big as the screen. So setting "top-left" didn't translate to top-left of the screen, but top-left of the mangoapp window. This has been reworked and is not set to a static 1280x800, this can probably be improved by getting resolution from gamescope.
> 
> I'm not sure how this impacts your situation, but it should be different if you check out [d0a1c4e](https://github.com/flightlessmango/MangoHud/commit/d0a1c4ea075d0d2c31548960470e53d4dbd154c0)

I tested using mangohud-git in the AUR as well as compile from source (latest in the repo and that specific commit) and the issue remains.

**Comment by flightlessmango** [comment]
Looks like I can replicate it with `--force-orientation left` indeed. I will look into it

**Comment by danyi** [comment]
I modified[d0a1c4e](https://github.com/flightlessmango/MangoHud/commit/d0a1c4ea075d0d2c31548960470e53d4dbd154c0) 

> app/main.cpp

 line 230

**Comment by Samsagax** [comment]
@flightlessmango would it be possible to set the window width/height based on display mode like is described [here](https://www.glfw.org/docs/latest/window.html#window_windowed_full_screen)

I could make a patch for you if you are busy.

**Comment by flightlessmango** [comment]
This should be fixed by 352d36549370e2ad4caf0c81a59f733a78d28838
