### ISSUE TITLE
libfmt dependency issue

### ISSUE THREAD

**Issue by vibudh007** [flightlessmango/MangoHud#832]
I'm running Arch Linux. I'm new to Github so bear with me.

The package `fmt` was updated to version 9.1.0-1 on the Arch repo today, 2022-09-01 14:41 UTC. Ever since then I haven't been able to run anything with mangohud enabled (such as games or programs through wine) or anything with a mangohud dependency (goverlay, mangoapp, etc). Disabling mangohud in games made them start to work again.

The error that crops up is 
`error while loading shared libraries: libfmt.so.8: cannot open shared object file: No such file or directory`
Trying to downgrade fmt to vesion 8.x.x results in the error
`installing fmt (8.1.1-2) breaks dependency 'libfmt.so=9-64' required by spdlog`
Trying to delete spdlog results in 
`removing spdlog breaks dependency 'spdlog' required by mangohud`

For context `spdlog` was last updated to version 1.10.0-3 today, 2022-09-01 12:38 UTC.

I'm not exactly sure if the dependency issue lies in spdlog or mangohud, but I'm sure mangohud users will be impacted more directly because of it, so I'm opening an issue here instead of the spdlog github page. But if spdlog is the cause, I'll put down an issue there as well if nobody has done that yet.

I hope the information I provided was sufficient in pinpointing the root of the issue :)

**Comment by flightlessmango** [comment]
Recompiling mangohud should solve the issue or give some interesting errors

**Comment by dspec12** [comment]
Yes, a recompile is necessary if on Arch. See the comments here: https://aur.archlinux.org/packages/mangohud
