### ISSUE TITLE
'Days Gone' fails to launch if using mangohud + proton experimental

### ISSUE THREAD

**Issue by adamdmoss** [flightlessmango/MangoHud#835]
Failure reproduces on Proton Experimental bleeding-edge and Proton Experimental default-branch: the game brings up its spash, but dies a second after bringing up the fullscreen/game window.  If I don't use mangohud the game runs fine.

Seems fine with Proton 7 (but hard to be sure because the game hangs just before the title screen, with or without mangohud).

Tested with mangohud master / fc31ac626434e9fcbe4a071e16351722224f44a2 .  I'm running with the mangohud wrapper, i.e. 'mangohud %command%'

Mangohud works fine with other games AFAICT.  Not sure if this is a new regression or (given that it works with Proton 7) a new bad dxvk interaction unique to this game.  :shrug:

**Comment by smvoss** [comment]
I actually seem to be having this exact issue as well but with `Deep Rock Galactic`.

Switching to 7 from experimental proton allowed the game to launch for me with mangohud, while it launches just fine in experimental without it.

Arch Linux, everything up to date, and the following:

``` 
$ pacman -Q | grep -i mango
lib32-mangohud-git 0.6.8.r16.gfc31ac6-1
mangohud-common-git 0.6.8.r16.gfc31ac6-1
mangohud-git 0.6.8.r16.gfc31ac6-1
```

**Comment by flightlessmango** [comment]
This is likely fixed in latest, reopen if still an issue
