### ISSUE TITLE
Manogohud segmentation fault when starting with the goverlay

### ISSUE THREAD

**Issue by mayakrunal** [flightlessmango/MangoHud#842]
Hi,
Mongohud giving the segmentation fault error when starting goverlay with following command. 
`mangohud --dlsym ./goverlay`
Initially i though may be it's goverlay issue and raised an issue there. however further testing showed it might be mongohud issue. Please have a look.  
[https://github.com/benjamimgois/goverlay/issues/24](url)

OS Specs:
OS: Manjaro Linux x86_64
Host: Inspiron 7501
Kernel: 5.15.65-1-MANJARO
Uptime: 31 mins
Packages: 1330 (pacman)
Shell: bash 5.1.16
Resolution: 1920x1080, 1920x1080
DE: Plasma 5.25.5
WM: KWin
Theme: [Plasma], Breeze [GTK2/3]
Icons: [Plasma], breeze [GTK2/3]
Terminal: dolphin
CPU: Intel i7-10750H (12) @ 5.000GHz
GPU: NVIDIA 01:00.0 NVIDIA Corporation TU117M
GPU: Intel CometLake-H GT2 [UHD Graphics]
Memory: 4602MiB / 15760MiB

**Comment by flightlessmango** [comment]
Is there a purpose to starting goverlay with mangohud?

**Comment by mayakrunal** [comment]
This is from goverlay source code.

//This script will launch the compiled goverlay binary the correct way
//QT_QPA_PLATFORM=xcb will force the application to run in x11 mode, so it works on wayland desktops.
// mangohud --dlsym will force the mangohud display on the spinning cube on goverlay.
// Executing this script with --style <style> one can choose different themes.
`export QT_QPA_PLATFORM=xcb
mangohud --dlsym @libexecdir@/goverlay $@`
https://github.com/benjamimgois/goverlay/blob/master/data/goverlay.sh.in

**Comment by flightlessmango** [comment]
I can't replicate it on my end
What I would need to diagnose this issues is gdb output with a debug mangohud build

**Comment by mayakrunal** [comment]
Damn, I am  C#, Java and all the other things guy. Basic C++ and trying my hand on it. How do i go about that.

**Comment by mayakrunal** [comment]
May be a stupid question but Do you have instructions i can refer to?

**Comment by mayakrunal** [comment]
clean-installed manjaro. working fine now. Something must be wrong with my previous setup, couldn't track down.

**Comment by andrew-lunarg** [comment]
> clean-installed manjaro. working fine now. Something must be wrong with my previous setup, couldn't track down.

Suggest this issue be closed then.
