### ISSUE TITLE
Retroarch segfaults if started with MANGOHUD=1

### ISSUE THREAD

**Issue by cih89** [flightlessmango/MangoHud#846]
Not sure if this is a Mangohud or Retroarch bug, but Retroarch will segfault and quit if started with Mangohud enabled, both in Wayland and X, both with Vulkan or OpenGL backend. It crashes as soon as a game is trying to be loaded. No issues whatsoever if started with MANGOHUD=0. 

Here's the error I get:
`[20009.581746] retroarch[43371]: segfault at 7fa6d6e56f7f ip 00007fa6d6e56f7f sp 00007fa6bb74ca40 error 14 in libncursesw.so.6.3[7fa6d6f62000+16000]
[20009.581764] Code: Unable to access opcode bytes at RIP 0x7fa6d6e56f55.`

Using Arch Linux with KDE 5.26, mangohud 0.6.8 from AUR and retroarch 1.11.1. GPU is AMD RX 6600XT with mesa drivers.

**Comment by gort818** [comment]
try using `mangohud` instead of `MANGOHUD=1`

**Comment by flightlessmango** [comment]
I was unable to repro this on master.
Re-open if it's still an issue on latest

**Comment by nfp0** [comment]
This is currently an issue for me. It works initially, but segfaults when opening any game.

Using Arch Linux with KDE Wayland, mangohud 0.8.0 and RetroArch 1.20.0

Can this be reopened?

EDIT: Disregard. I have tested this on master and it's working.
