### ISSUE TITLE
No Stats for Intel Arc A-Series GPUs (A750)

### ISSUE THREAD

**Issue by cybereality** [flightlessmango/MangoHud#850]
I just got an Intel Arc A750 and I'm seeing no stats for the GPU. Nothing for the CPU is displayed, and the MEM section is 0.

I understand this will be hard to test without the GPU, so please let me know if I can assist.

**Comment by flightlessmango** [comment]
This isn't related to the new GPUs, this is a known issue.
In short we're unable to get any GPU information for intel without root access.
https://github.com/flightlessmango/MangoHud/issues/558

**Comment by cybereality** [comment]
I understand. Just read though that thread and it's pretty much the reason people don't use Linux. Because of obtuse attitudes completely detached from what users need.

**Comment by Leopard1907** [comment]
Maybe worth a shot?

https://gitlab.freedesktop.org/drm/intel/-/issues/5018#note_1455627

**Comment by flightlessmango** [comment]
> Maybe worth a shot?
> 
> https://gitlab.freedesktop.org/drm/intel/-/issues/5018#note_1455627
I think, probably we could run `intel_gpu_top` in mangohud and have the user give special permissions to it.
I don't like that the user has to do extra stuff and install a dependency.
I need to think about it a bit

**Comment by flightlessmango** [comment]
I wrote a wrapper for `intel_gpu_top` e38413b2d8ec2560d8ec5367781836771072d6fd
It requires that you have intel_gpu_top installed on your system and set `sudo setcap cap_perfmon=+ep /usr/bin/intel_gpu_top`

**Comment by radu-munteanu** [comment]
Hi,

Is there any schedule for a new release that contains this feature? I see the latest release (0.6.8) is from eight months ago.

Thanks

**Comment by eclairevoyant** [comment]
I imagine the plan is to go with #877 instead. You can try building from git if you want this specifically though

**Comment by radu-munteanu** [comment]
I don't mind going with #877 or any other commit, as long as it adds metrics for newer Intel GPUs. I know I could build it from git, I want a release that I could later install it through the package repo offered by the distribution.

**Comment by eclairevoyant** [comment]
My point is the functionality is still WIP and demanding it won't speed things up, so you have other options instead for yourself

**Comment by flightlessmango** [comment]
If you have flatpak installed and set sniper runtime to beta it should work in proton

**Comment by flightlessmango** [comment]
Moving conversation to #1082
