### ISSUE TITLE
Using mangohud I get ~ 32% lower fps

### ISSUE THREAD

**Issue by AstroDrabb** [flightlessmango/MangoHud#854]
Not sure what information you want to see.  My config is a generic one made with goverlay.  Running glxgears with/without mangohud:

```
[0] jim@yoda $ glxgears
143043 frames in 5.0 seconds = 28608.434 FPS
140424 frames in 5.0 seconds = 28084.709 FPS
141273 frames in 5.0 seconds = 28254.561 FPS

[0] jim@yoda $ mangohud glxgears
46106 frames in 5.0 seconds = 9221.159 FPS
45917 frames in 5.0 seconds = 9183.293 FPS
47956 frames in 5.0 seconds = 9591.067 FPS

```
System is Arch Linux, R9 5900x, AMD RX 6800.
What information do you need?

**Comment by flightlessmango** [comment]
When running at these high frames, in the 20 thousands, you will indeed notice the performance impact of mangohud.
While we could probably rewrite things to be faster, I don't think this is a huge issue as it's relegated to an extreme amount of frames per second.
I would be more concerned if you could replicate this in a video game

**Comment by AstroDrabb** [comment]
I am downloading my steam library now.  I've never used MangoHud so I was just testing with glxgears and vkcube and noticed the big drop.  I usually set to play at 120 or 144 to stick to vsync.
In steam I just change the launch options to "MANGOHUD=1 %command%" correct?

**Comment by AstroDrabb** [comment]
Ok, playing a game didn't show any slow down, I was getting over 600fps in "The Walking Dead".  Thanks for the help.
