### ISSUE TITLE
Overwatch 2 crash when toggling logging off

### ISSUE THREAD

**Issue by ZeusThundr** [flightlessmango/MangoHud#855]
Logging starts as indicated by the red circle and when it is time to save/stop the logging the game crashes I also experienced this on Overwatch 1 a few weeks before the launch of Overwatch 2. I've seen a user benchmark uploaded just yesterday over on flightlessmango website for overwatch which makes me suspect I maybe doing something wrong.
I've have experienced this on vanilla arch, void linux, garuda linux, lutris, and bottles. Logging on vkcube works.

**Comment by flightlessmango** [comment]
reopen if still an issue
