### ISSUE TITLE
*/bin/wine: No such file or directory.

### ISSUE THREAD

**Issue by emmanuelrosa** [flightlessmango/MangoHud#856]
I've encountered the following error when using wine64; Meaning a wine build without WoW64:

![mangohud](https://user-images.githubusercontent.com/13485450/200629242-9bad7c2d-44f1-493a-aeb6-c6f31597a13a.png)

 I believe the problem is at this line because it's trying to execute `wine` and there's only `wine64`:
https://github.com/flightlessmango/MangoHud/blob/e38413b2d8ec2560d8ec5367781836771072d6fd/src/overlay.cpp#L845

**Comment by gort818** [comment]
Should be fixed here f6d980696dffd4976e4fc6aa5ebd4bd1d61a4099
