### ISSUE TITLE
A package update has caused mangohud to break

### ISSUE THREAD

**Issue by wodger1912** [flightlessmango/MangoHud#857]
Hi everyone,

So, I usually run mangohud on all my games (steam / native wine etc.) Today when attempting to start any game in steam with mangohud enabled within the command parameters, steam would attempt to start the game then just fail out. Disabling the command enables games to start normally - looked at steam running in terminal and no obvious errors there.

Checked Goverlay in terminal, and it fails out with:
`/usr/lib/goverlay: error while loading shared libraries: libspdlog.so.1: cannot open shared object file: No such file or directory`

Here is a list of updated packages/libraries done today:
`[2022-11-10T07:40:39+0800] [ALPM] installed python-zipp (3.10.0-1)`
`[2022-11-10T07:40:39+0800] [ALPM] installed python-importlib-metadata (5.0.0-1)`
`[2022-11-10T07:40:39+0800] [ALPM] upgraded popt (1.18-3 -> 1.19-1)`
`[2022-11-10T07:40:40+0800] [ALPM] upgraded btrfs-progs (6.0-1 -> 6.0.1-1)`
`[2022-11-10T07:40:40+0800] [ALPM] upgraded breeze (5.26.3-1 -> 5.26.3.1-1)`
`[2022-11-10T07:40:40+0800] [ALPM] upgraded chromium (107.0.5304.87-1 -> 107.0.5304.110-1)`
`[2022-11-10T07:40:40+0800] [ALPM] upgraded fwupd (1.8.6-1 -> 1.8.7-1)`
`[2022-11-10T07:40:40+0800] [ALPM] upgraded gssdp (1.6.0-1 -> 1.6.1-1)`
`[2022-11-10T07:40:40+0800] [ALPM] upgraded gupnp (1:1.6.0-1 -> 1:1.6.1-1)`
`[2022-11-10T07:40:40+0800] [ALPM] upgraded libnma-common (1.10.4-2 -> 1.10.4-3)`
`[2022-11-10T07:40:40+0800] [ALPM] upgraded libnma (1.10.4-2 -> 1.10.4-3)`
`[2022-11-10T07:40:40+0800] [ALPM] upgraded python-keyring (23.9.3-1 -> 23.11.0-1)`
`[2022-11-10T07:40:40+0800] [ALPM] upgraded python-setuptools (1:65.0.2-1 -> 1:65.1.0-1)`
`[2022-11-10T07:40:40+0800] [ALPM] upgraded python-wheel (0.38.1-1 -> 0.38.2-1)`
`[2022-11-10T07:40:40+0800] [ALPM] upgraded spdlog (1.10.0-3 -> 1.11.0-1)`
`[2022-11-10T07:40:40+0800] [ALPM] upgraded texinfo (6.8-2 -> 7.0-1)`
`[2022-11-10T07:40:40+0800] [ALPM] upgraded usbutils (014-2 -> 015-1)`
`[2022-11-10T07:40:40+0800] [ALPM] upgraded wpa_supplicant (2:2.10-6 -> 2:2.10-7)`

I suspect one or more of these are responsible for the issue, I will have a look again later to see if I can find the offending package (real life things to do :P )

Arch Linux running KDE Plasma

**Comment by flightlessmango** [comment]
You just need to recompile mangohud

**Comment by wodger1912** [comment]
> You just need to recompile mangohud

Cheers mate, I just popped back to see if any update. Forgot to mention all apps were from AUR.

Uninstalled Mangohud / Mangohud-common / Mangoapp / Goverlay and reinstalled from AUR

It asked for additional dependencies while installing:
`nlohmann-json (3.11.2-1)`
`fpc-src (3.2.2-2)`
`fpc (3.2.2-6)`
`lazarus (2.2.4-1)`

Checked and appears all OK now (re-added Mangohud switch and games start normally again in steam, as does Goverlay)

Thanks for the prompt response
