### ISSUE TITLE
No CPU Frequency for AMD Ryzen 5600X on Ubuntu 22.10

### ISSUE THREAD

**Issue by cybereality** [flightlessmango/MangoHud#858]
I'm getting 0 MHz for CPU frequency on a Ryzen 5600X on Ubuntu 22.10.

All other stats are shown, included CPU load and temperature.

**Comment by flightlessmango** [comment]
It's because cool and quiet is disabled in bios.
This needs to be fixed in mangohud.
As a temporary workaround you can enable cool and quiet

**Comment by cybereality** [comment]
Oh, wow, thanks. That worked!!!

Strange I didn't see that anywhere, cause I did search for a while before a submitting an issue.

Anyhow, I guess it's good that this info is here for anyone else searching Google.
