### ISSUE TITLE
GPU not showing on Wayland

### ISSUE THREAD

**Issue by sawhix** [flightlessmango/MangoHud#859]
It works on X11 but the GPU stats are not showing on Wayland. Tried with Cyberpunk and VKD3D. 
Graphics card NVIDIA 2080 super and 5.15.65.01 drivers.
OS: Ubuntu 22.10
MangoHud installed from distro repo deb, version 0.6.8

**Comment by Leopard1907** [comment]
Can you check that if you have `nvml` installed or not?

**Comment by sawhix** [comment]
> 

yes it's installed, nvidia-smi is working

**Comment by sawhix** [comment]
> Can you check that if you have `nvml` installed or not?

yes it's installed, nvidia-smi is working

**Comment by jackun** [comment]
> distro repo deb

Which repo, i think default debian one doesn't build with NVML.

**Comment by sawhix** [comment]
it was default ubuntu repo, i didn't change anything for it, just apt install mangohud, i will test on fedora and come back with the results, if it works on fedora then it's not mangohud's fault.

**Comment by Ralink88** [comment]
i have the same problem on ubuntu 22.10 under x11...same thing with goverlay.
I noticed in my case that if in the Nvidia control panel (515 proprietary) I change the PRIME SETTING from on demand to performance and restart mangohud detects the GPU.
I would like to find a way to have the GPU visible on demand, I tried to force start mangohud and goverlay with the dGpu but it didn't work. Some idea?

I'm on an Intel and Nvidia 840m laptop

**Comment by flightlessmango** [comment]
@sawhix 
> it was default ubuntu repo

Fairly sure that's the debian package which does not include nvml, nvml is required for wayland.

**Comment by flightlessmango** [comment]
@ChrisLauinger77 what distro? if it's ubuntu/debian derivative, then try and install using the release package instead.
[MangoHud-0.6.9.1](https://github.com/flightlessmango/MangoHud/releases/download/v0.6.9-1/MangoHud-0.6.9.1.r0.g7f94562.tar.gz)

**Comment by ChrisLauinger77** [comment]
> @ChrisLauinger77 what distro? if it's ubuntu/debian derivative, then try and install using the release package instead.
> 
> [MangoHud-0.6.9.1](https://github.com/flightlessmango/MangoHud/releases/download/v0.6.9-1/MangoHud-0.6.9.1.r0.g7f94562.tar.gz)

Yes its debian. https://packages.debian.org/bookworm/mangohud
I try the new version. Thx

**Comment by ChrisLauinger77** [comment]
> > @ChrisLauinger77 what distro? if it's ubuntu/debian derivative, then try and install using the release package instead.
> > [MangoHud-0.6.9.1](https://github.com/flightlessmango/MangoHud/releases/download/v0.6.9-1/MangoHud-0.6.9.1.r0.g7f94562.tar.gz)
> 
> Yes its debian. https://packages.debian.org/bookworm/mangohud I try the new version. Thx

with 0.6.9.1 it works - thx you so much !

**Comment by flightlessmango** [comment]
This issue is because of the Debian Free Software Guidelines.
NVML is non-free and so it's removed from the debian builds.
NVML is required to get nvidia metrics on wayland, but since it's not present it can't work.
In short this is not an issue.

**Comment by ChrisLauinger77** [comment]
> This issue is because of the Debian Free Software Guidelines. NVML is non-free and so it's removed from the debian builds. NVML is required to get nvidia metrics on wayland, but since it's not present it can't work. In short this is not an issue.

nvidia control panel states NVML Version:12.525.105.17. Why are you saying it is removed from debian ?
and debian has non-free repo for proprietary stuff. thats where the nvidia-driver can be installed. New is that they have non-free-firmware.

**Comment by flightlessmango** [comment]
The NVML module inside mangohud is excluded, not the system NVML

**Comment by ChrisLauinger77** [comment]
> The NVML module inside mangohud is excluded, not the system NVML

Ah mangohud has an own one. Yes debian does not want this. Thx for clarification !

**Comment by QkiZMR** [comment]
> Fairly sure that's the debian package which does not include nvml, nvml is required for wayland.

> The NVML module inside mangohud is excluded, not the system NVML

@flightlessmango You said mutually exclusive things. 
First you say that Debian doesn't support nvml because it's non-free, and then you say that the nvml module is disabled in MangoHud.

**Comment by flightlessmango** [comment]
@QkiZMR 
> @flightlessmango You said mutually exclusive things. First you say that Debian doesn't support nvml because it's non-free, and then you say that the nvml module is disabled in MangoHud.

To be more clear, the packager follows the DFSG guidelines and as such the nvml component in mangohud is not included.

**Comment by QkiZMR** [comment]
So if I install NVML MangoHud should see NVIDIA card and show metrics properly?

**Comment by 17314642** [comment]
@QkiZMR it should work if you install BOTH nvml (which comes with closed nvidia driver) and mangohud built with nvml support

**Comment by QkiZMR** [comment]
I'm using closed source driver and Mangohud from Ubuntu repository. So I need to compile Mangohud with NVML support?

**Comment by 17314642** [comment]
yes

**Comment by Amir-Hossein-Azimi** [comment]
I've tried everything, but NVML is not installing or working, even though I'm on Arch Linux and using Wayland. It was working fine and showing GPU metrics until two months ago, but now it doesn't.
