### ISSUE TITLE
Invalid Vulkan usage during VkCreateDevice - adding VkPhysicalDeviceFeatures when VkPhysicalDeviceFeatures2 is in the pNext chain

### ISSUE THREAD

**Issue by charles-lunarg** [flightlessmango/MangoHud#860]
This check should make sure that VkPhysicalDeviceFeatures2 isn't in the pNext chain first.
https://github.com/flightlessmango/MangoHud/blob/85007fe0bdda6c9a16f8046ad39be193409ccf67/src/vulkan.cpp#L1788

```
VUID-VkDeviceCreateInfo-pNext-00373
If the pNext chain includes a [VkPhysicalDeviceFeatures2](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkPhysicalDeviceFeatures2.html) structure, then pEnabledFeatures must be NULL
```
https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkDeviceCreateInfo.html

**Comment by flightlessmango** [comment]
does 8450291777c0ef3617ffbebeb1a38c97e1c7fdd1 resolve the issue?

**Comment by charles-lunarg** [comment]
I believe so.
Since it appears mangohud doesn't modify anything on the pFeatures struct, then just using the application's vkDeviceCreateInfo should be good.
