### ISSUE TITLE
Font not respected when in game (steam)

### ISSUE THREAD

**Issue by keijo0** [flightlessmango/MangoHud#863]
I have set in ~/.config/MangoHud/Mangohud.conf
font_file=/usr/share/fonts/font/font.ttf
font_file_text=/usr/share/fonts/font/font.ttf

and the correct font appears if i run 'mangohud glxgears' for example but when i launch a steam game (beamng drive in this instance) it doesn't use the font ive specified.

Is there away around this or am i completely missing something else?

**Comment by gort818** [comment]
Try placing in the font file in your home directory

**Comment by flightlessmango** [comment]
What @gort818 said.
When you run a game with proton in steam it runs through the steam runtime container.
This prevents us from accessing system wide things, but things in your home folder for example is accessible

**Comment by keijo0** [comment]
Yeah that works, thank you.
