### ISSUE TITLE
ERROR: ld.so: object 'libMangoHud.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.

### ISSUE THREAD

**Issue by cinnamonmatexfce** [flightlessmango/MangoHud#865]
I cannot get MangoHUD work with `wine32` on Debian 11.5 (Bullseye).
MangoHUD works fine in Steam (`Proton 7.0-5`).

Here's the packages:
```
mangohud/stable,now 0.6.1-1+b2 amd64 [installed]
nvidia-driver/stable,now 470.141.03-1~deb11u1 amd64 [installed]
nvidia-vulkan-common/stable,now 470.141.03-1~deb11u1 amd64 [installed,automatic]
nvidia-vulkan-icd/stable,now 470.141.03-1~deb11u1 amd64 [installed,automatic]
wine/stable,stable,now 5.0.3-3 all [installed]
wine32/stable,now 5.0.3-3 i386 [installed]
wine64/stable,now 5.0.3-3 amd64 [installed]
```

```
$ MANGOHUD_DLSYM=1 WINEDEBUG=fixme-all WINEARCH=win32 WINEPREFIX=~/winebottles/win32_game mangohud wine start game.exe
```

**Comment by gort818** [comment]
Do you have MangoHud 32 bit installed?

**Comment by cinnamonmatexfce** [comment]
> Do you have MangoHud 32 bit installed?

Damn! Shame on me...

SOLVED: `$ sudo apt install mangohud:i386`

**Comment by databoose** [comment]
I am getting this error, however there is no mangohud:i386 package on linux mint to install... any ideas?

**Comment by cinnamonmatexfce** [comment]
> I am getting this error, however there is no mangohud:i386 package on linux mint to install... any ideas?

I don't think there is none (offcial). I'm only seeing a community package of `mangohud`, I think you'd need to go compiling manually by yourself

**Comment by databoose** [comment]
> > I am getting this error, however there is no mangohud:i386 package on linux mint to install... any ideas?
> 
> I don't think there is none (offcial). I'm only seeing a community package of `mangohud`, I think you'd need to go compiling manually by yourself

Yeah i figured, it's not a giant deal since the game in question i am trying to run with mango is very old (32 bit entirely), and on retrospect this is probably an issue to do with ubuntu's upstream that linux mint for the most part uses, where they really don't like to ship 32 bit packages.

Apologies for necroposting, i should have looked into it first.
