### ISSUE TITLE
Problems with zink

### ISSUE THREAD

**Issue by bubba-champion** [flightlessmango/MangoHud#866]
Glxgears executed via `MESA_LOADER_DRIVER_OVERRIDE=zink mangohud glxgears` cause segmentation fault, and errors in kernel ring buffer, but with `MANGOHUD=1 MESA_LOADER_DRIVER_OVERRIDE=zink glxgears` works as intended.

Also when I'm trying to launch OpenGL games (for example Don't Starve Together) with `MESA_LOADER_DRIVER_OVERRIDE=zink mangohud %command%` steam launch option, i have graphical glitches and errors in kernel ring buffer, but with `MANGOHUD=1 MESA_LOADER_DRIVER_OVERRIDE=zink %command%` works as intended.

GPU: AMD Radeon RX 6400
Linux: 6.0.12
MangoHud: 0.6.8
Mesa: 22.3.1
OS: Void

**Comment by gort818** [comment]
That backtrace is probably useless.

So if LD_PRELOAD is set it crashes which is what the command `mangohud` is doing.

`MESA_LOADER_DRIVER_OVERRIDE=zink MANGOHUD=1  LD_PRELOAD=/usr/lib/mangohud/lib64/libMangoHud.so glxgears` crashes

`MESA_LOADER_DRIVER_OVERRIDE=zink MANGOHUD=1 LD_LIBRARY_PATH= LD_PRELOAD= glxgears` runs normally

**Comment by gort818** [comment]
Can you try this patch?
https://gist.github.com/gort818/ba96471c82832fc9201444dfff78f70b

**Comment by bubba-champion** [comment]
With this patch glxgears crashes after a few seconds when executed via `MESA_LOADER_DRIVER_OVERRIDE=zink mangohud glxgears`, but with `MESA_LOADER_DRIVER_OVERRIDE=zink vblank_mode=3 mangohud glxgears` seems works as intended.

When I'm launching some OpenGL games via `MESA_LOADER_DRIVER_OVERRIDE=zink mangohud %command%` looks like they works fine.

Also without this patch i have this error in dmesg `glxgears:zfq0[10562]: segfault at 93 ip 00007fab5af8d55c sp 00007fab50bfc8c0 error 4 in libMangoHud.so[7fab5aef8000+a7000]` and Xorg freeze

And this error with this patch `glxgears[5312]: segfault at 0 ip 00007fc67f4b2345 sp 00007fff67487c40 error 6 in libGLX_mesa.so.0.0.0[7fc67f495000+3d000]`

**Comment by gort818** [comment]
Can you try this patch ?
[glxpatch.txt](https://github.com/flightlessmango/MangoHud/files/10296740/glxpatch.txt)

**Comment by bubba-champion** [comment]
Looks like all of the above problems are solved with this patch, but I still have same problem in glxgears with AMDVLK vulkan driver.

Recently I found graphical bug, when mpv executed via `MESA_LOADER_DRIVER_OVERRIDE=zink mangohud mpv --no-config example.mp4` I observe strange behavior of FPS counter and frametime graph in fullscreen mode. In addition to this, MangoHud no longer works in mpv after this patch when executed via `mangohud mpv --no-config example.mp4` or `mangohud --dlsym mpv --no-config example.mp4`.

Also I'm wondering why when I execute glxgears via `MESA_LOADER_DRIVER_OVERRIDE=zink mangohud glxgears` I see a lack of vsync.

**Comment by gort818** [comment]
Thanks for all the feedback!

Here is the latest patch.. think this is the last one
[glxpatch.txt](https://github.com/flightlessmango/MangoHud/files/10341544/glxpatch.txt)


I tested MPV with zink. looks good to me.

So it seems MPV loads both opengl and vulkan libraries so with opengl mangohud will not work.

I don't see any issues with vsync on my end.

I let `MESSA_LOADER_DRIVER_OVERRIDE=zink mangohud glxgears` run for over 20 mins.. no crashes.

Not sure that is our error.

**Comment by gort818** [comment]
Might need to update `libX11` my 32bit version was a little old.

**Comment by bubba-champion** [comment]
When glxgears executed via `MESA_LOADER_DRIVER_OVERRIDE=zink mangohud glxgears` it works without any issues, but when I add `vblank_mode=0` to unlock fps, it crashes immediately with `xcb_request_check: Assertion !reply.' failed.` even with updated libX11. However, when I execute glxgears via `MANGOHUD=1 MESA_LOADER_DRIVER_OVERRIDE=zink vblank_mode=0 glxgears` it works fine.

**Comment by gort818** [comment]
Just tested on my end, I cannot reproduce. What version of libx11 are you running?
I am running
`pacman -Q libx11
libx11 1.8.3-3`

**Comment by gort818** [comment]
Also if you really need mangohud in mpv, try using vulkan
`mangohud  mpv --no-config  --gpu-api=vulkan file_example.mp4`

**Comment by bubba-champion** [comment]
The problem seems to be in Void Linux version of libX11 compiled with following args `--enable-ipv6 --enable-xlocaledir --without-xmlto --enable-static --enable-malloc0returnsnull --disable-thread-safety-constructor`, so i just recompiled it with Arch Linux args `--disable-static --disable-xf86bigfont` and now it works as intended.

**Comment by gort818** [comment]
I pushed a commit that should fix the issues you had with mpv if you want to check it out.

**Comment by bubba-champion** [comment]
Looks like zink broke again after the last commits.

MangoHud blinking when I execute glxgears via `MESA_LOADER_DRIVER_OVERRIDE=zink mangohud glxgears`.

When I compile MangoHud from this [commit](https://github.com/flightlessmango/MangoHud/commit/7b248efef7030406474850c95e3df8d21c3cc39a) all works fine.

@gort818

**Comment by gort818** [comment]
@bubba-champion Hmm I will check if I can reproduce, can you bisect?

**Comment by gort818** [comment]
I cannot reproduce.

**Comment by bubba-champion** [comment]
I bisected, and [this](https://github.com/flightlessmango/MangoHud/commit/ba7e2cb313dd80d1f2020d1c9b99ce9f3c412aaa) is the first bad commit for me.

**Comment by bubba-champion** [comment]
Here is a video demonstration of this bug

https://user-images.githubusercontent.com/112645980/216763855-82c19274-a393-4d3f-aad9-5bfc2b0b7ad4.mp4

**Comment by gort818** [comment]
Can you check if it also occurs with other applications besides glxgears?

**Comment by bubba-champion** [comment]
Looks like MangoHud not works in any Vulkan application, and works weird with Zink for me. I think there is a problem with loading the Vulkan library.
