### ISSUE TITLE
[suggestion] variable to get time since starting a game

### ISSUE THREAD

**Issue by webodan** [flightlessmango/MangoHud#867]
Hello,
since I haven't seen it in the readme or in the conf file of MangoHud, and I don't know how to implement it or make it work myself, I'd really appreciate some way of having a clock that logged how long the game has been running. 

Something like: `Started: 0:01` (that counts up every second) or whatever, it would be really useful to benchmark on my end, since I swapped GPUs and it would be great to keep track in an accurate way from the HUD while I'm looking at frametimes, temperatures etc.

Sorry if there was already a way to do it, if so please explain me why.

Thanks in advance.

**Comment by jn64** [comment]
Wouldn't the system time be more useful? Timer is ambiguous e.g. if you're comparing screenshots from different sessions.

The time_format in the example config only shows hours and minutes, but you can set it to the full date and time with seconds.

```
# MangoHud.conf
time
time_format=%F %T
```

**Comment by ndegruchy** [comment]
I think this would be a great feature. A simple count up timer to show current running time.

**Comment by webodan** [comment]
yeah that's exactly what i would like @ndegruchy , i just can't figure out how to impement it.
