### ISSUE TITLE
Transparency "doubles" Hud

### ISSUE THREAD

**Issue by ghtux** [flightlessmango/MangoHud#87]
With v 0.3, the hud transparency setting shows a second hud shadow. Screenshot attached. 

Anything else than background_alpha=1.0 leads to this behaviour.

![mangohud](https://user-images.githubusercontent.com/16836507/76965270-4f654f00-6924-11ea-8353-fa7e6287f131.png)

**Comment by flightlessmango** [comment]
this is probably #82

**Comment by ghtux** [comment]
Thanks! That´s the case.
