### ISSUE TITLE
[feature] Show directx version (9,10,11,12)

### ISSUE THREAD

**Issue by legluondunet** [flightlessmango/MangoHud#872]
Hello,
could it be possible that MONGOHUD showing game Directx version ( 9,10,11,12?)  ? 
Like DXVK hud:
![12561831-1576876579](https://user-images.githubusercontent.com/325405/209720261-dc6e60aa-3980-4142-9bf9-e1a351623372.png)

**Comment by flightlessmango** [comment]
DXVK would have to expose that through a vulkan extension and it's pretty unlikely.
But either way you would need to bug them about it as we can't do anything on our end
