### ISSUE TITLE
Call of Duty 4: Modern Warfare (2007) - close to desktop on changing graphics setting

### ISSUE THREAD

**Issue by Mr-nUUb** [flightlessmango/MangoHud#876]
Call of Duty 4: Modern Warfare (2007) is a DX9 game, therefore I have to use DXVK to get MangoHUD working. If MangoHUD is disabled, the game changes and saves all graphics settings. If MangoHUD is enabled, the following log is observed when changing resolution:

```
info:  Restoring display mode: 3440x1440@144
info:  Setting display mode: 3440x1440@144
info:  Restoring display mode: 2560x1440@75
info:  Setting display mode: 2560x1440@75
Initial process has exited (return code: 0)
```

According to the logs, resolution is changed twice (`DXVK_LOG_LEVEL=debug`) and then the game closes. Sorry, there are no crash logs or something. If more information is required, please tell me what and how to retrieve it.

**Comment by flightlessmango** [comment]
Could be same issues as #852
