### ISSUE TITLE
FPS limiter causes high variability in FPS

### ISSUE THREAD

**Issue by azn1999** [flightlessmango/MangoHud#879]
In the following image you can observe an average of 60 FPS, however frame times range from 12 ms to 22 ms. I am convinced this happens because of MangoHud's framerate limiter.

![Screenshot from 2023-01-04 22-07-22](https://user-images.githubusercontent.com/21178744/210700325-03026db1-124e-47b8-a645-688292acc96d.png)

So this is basically how I understand the FPS limiter is implemented in MangoHud. For each frame the following steps are executed
1. Sleep for some time
2. Let the game do its thing (update state, draw calls, etc.)
3. Swap buffer

To get a consistent FPS you would need to predict how long the 2nd step will take, and based on that time, compute for how long to sleep on step 1. The current implementation 'predicts' that step 2 will take the same time it took during the previous frame.

You can see how this could cause undesired variability in FPS. Lets suppose your target frametime is 16.6 ms (60 FPS) and, during the previous frame, step 2 took 4 ms. Then the algorithm 'predicts' this frame's 2nd step will also take 4 ms, so it decides to sleep for 16.6-4=12.6 ms in step 1. But if this frame's 2nd step takes 8 ms, you get a frametime of 12.6+8=20.6 ms.

In my opinion, a better way to implement this would be the following:

1. Let the game do its thing (update state, draw calls, etc.)
2. Sleep some amount of time (this time can be computed exactly, no predictions required)
3. Swap buffer

A disadvantage of this second approach is you get slightly higher latency, but you solve the first issue.

The fix is easy, just swap the steps in the relevant functions (glXSwapBuffers, glXSwapBuffersMscOML, etc.). By doing that I got the following result.

![Screenshot from 2023-01-04 22-11-39](https://user-images.githubusercontent.com/21178744/210700877-bf94045a-9409-4219-9422-26681b1f0777.png)

**Comment by Calinou** [comment]
> The fix is easy, just swap the steps in the relevant functions (glXSwapBuffers, glXSwapBuffersMscOML, etc.). By doing that I got the following result.

Feel free to open a pull request for this :slightly_smiling_face:
