### ISSUE TITLE
0.3.1 won't compile anymore for non x86_64/i686 arches

### ISSUE THREAD

**Issue by tim77** [flightlessmango/MangoHud#88]
`0.3.1` version won't compile anymore for non x86_64/i686 arches. This may be due https://github.com/flightlessmango/MangoHud/issues/75 fix.

Full build log for six different arches [here](https://koji.fedoraproject.org/koji/taskinfo?taskID=42596446).

**Comment by jackun** [comment]
This is getting into wontfix territory for me.

**Comment by tim77** [comment]
Yep, personally i don't consider this is as bug, JFYI. In same time someone may want to have `mangohud` on their tablet or smartphone. :) @jackun i think we can close this.

**Comment by jackun** [comment]
I'll probably still check it out why the `elf.h`is different , if I can get cross-build working somehow.

**Comment by jackun** [comment]
This https://github.com/flightlessmango/MangoHud/commit/f1c8acdb0fb28f9d060cff677e153942bb56047e probably fixes it but no idea if it actually runs.

**Comment by tim77** [comment]
> This [f1c8acd](https://github.com/flightlessmango/MangoHud/commit/f1c8acdb0fb28f9d060cff677e153942bb56047e) probably fixes it but no idea if it actually runs.

It compiles on all arches now. But don't know is it work on this arches as well.
