### ISSUE TITLE
How to find the right name of executable for naming the .conf

### ISSUE THREAD

**Issue by H34dl3ss** [flightlessmango/MangoHud#880]
Hi there! Happy NY!
I would like to set up a dedicated .conf file for the steam-based CS:GO.
Checking the running processes related to CS:GO revealed an hl.sh, and another hl2_linux64.sh or so.
Neither wine-hl2_linux64.conf nor wine-hl.conf is considered when the game is run.

How is the generic procedure to find out which file/executable has to be considered for naming the .conf?

**Comment by flightlessmango** [comment]
Added a new option `exec_name` which will show you the correct name in the hud.
03d64e5afb5c89eb6f0f70d30f20cbda207f43d8
