### ISSUE TITLE
VRAM on AMD 6800HS APU is incorrect after version 0.6.7-1

### ISSUE THREAD

**Issue by Rimits** [flightlessmango/MangoHud#883]
Hello ! report (maybe) a bug.
VRAM on my laptop reading seems wrong after version 0.6.7-1. It's OK with version 0.6.7.
My laptop is a lenovo yoga pro 14s, equipped with an AMD r7 6800HS cpu (no dGPU), and 2G of ram is reserved as vram in bios.
The actual vram usage reported by umr:
![截图 2023-01-05 18-44-52](https://user-images.githubusercontent.com/42634955/210764849-db78cb24-883c-4656-b04e-27277314ef6c.png)
The icorrect value reported in version 0.6.7-1. It seems that the 4.3G comes from both vram and GTT: 2048×68%+6836×43%=4332
![截图 2023-01-05 18-43-09](https://user-images.githubusercontent.com/42634955/210764787-c707007e-c2ad-4aeb-ba90-c6b96353b53e.png)
In 0.6.7 the vram reading is fine:
![截图 2023-01-05 18-51-42](https://user-images.githubusercontent.com/42634955/210764864-ed7cb683-4442-4f65-8ab8-e92d705074f5.png)

**Comment by flightlessmango** [comment]
While this is wrong, it was also an intentional change.
We wanted to show the actual available memory rather than strictly the vram.
You could make me an argument that this should be changed, but I think it's probably fine like this
