### ISSUE TITLE
Feature Request: IPMI fan readout

### ISSUE THREAD

**Issue by emansom** [flightlessmango/MangoHud#884]
**Is your feature request related to a problem? Please describe.**

I own a Supermicro workstation which I daily use and sometimes game on. This workstation is retrofitted with Noctua ULNA fans to keep the noise levels low, and the system is configured to run the [Super Micro Fan Control](https://github.com/petersulyok/smfc) utility in the background.

Currently, there's no way to show the system fan RPMs that are exposed through IPMI.

**Describe the solution you'd like**

During gaming I'd like to keep an eye on the fan RPMs that the Supermicro board reports through IPMI and [SMFC](https://github.com/petersulyok/smfc) adjusts.

**Comment by flightlessmango** [comment]
Can you not use the `exec` option to accomplish this?
