### ISSUE TITLE
[Feature Request] display P2P info if applicable

### ISSUE THREAD

**Issue by pubnoconst** [flightlessmango/MangoHud#886]
In Windows there is [Steam p2p info](https://github.com/tremwil/SteamP2PInfo) which shows the ping level and connection quality of connected players.
MangoHud is the to-go HUD for displaying stats on Linux. It'd be really cool if it could have an option to show p2p info as well.

**Comment by flightlessmango** [comment]
It's out of scope to write the infrastructure to fetch this information in MangoHud.
However if someone wrote this program on linux we could probably add support for displaying the information in mangohud.

**Comment by pubnoconst** [comment]
> It's out of scope to write the infrastructure to fetch this information in MangoHud.

Understood. Closing
