### ISSUE TITLE
Total War: Warhammer 3 fails to start with MangoHud autostart_log

### ISSUE THREAD

**Issue by LeaderOne** [flightlessmango/MangoHud#887]
I'm running Ubuntu 22.04 and am using MangoHud compiled from the master branch (not the version that comes with Ubuntu).  I'm launching Total War: Warhammer 3 using `mangohud %command%` from the game options in Steam.  When I set `autostart_log` to any value and also set `output_folder`, the game fails to start.  If I disable `autostart_log` I can launch the game, and still record with Shift+F2.  I tried to uninstall and reinstall from the develop branch but that branch doesn't compile on my system.  I also started with NODEVICE_SELECT=1, but that didn't help.

How can I get `autostart_log` to work?

**Comment by LeaderOne** [comment]
I was able to work past this by adding `logger->notify_data_valid();` to `autostart_log` in `logging.cpp`, line 264.  Looks like there's a race condition where the window won't render until it receives that signal, but the signal won't be sent until the window renders.  Not sure I did this right, though, so other suggestions would be helpful.

**Comment by flightlessmango** [comment]
That solution sounds fine, you could make a PR if you want.
This commit ba7e2cb313dd80d1f2020d1c9b99ce9f3c412aaa is also addressing a case of autostart_log crashing, you might want to see if that one fixes it as well or if both are needed

**Comment by LeaderOne** [comment]
Yes, that commit fixes the issue.  Either one works.
