### ISSUE TITLE
MangoHud install problem

### ISSUE THREAD

**Issue by Slo2018** [flightlessmango/MangoHud#889]
I got this error when i tried to install MangoHud (./build.sh build) in Ubuntu 22.10.

![Zaslonska slika 2023-01-13 02-07-14](https://user-images.githubusercontent.com/45156187/212214423-385d7fd2-849c-4fbc-83bd-1e396996cf58.png)

**Comment by gort818** [comment]
We haven't updated the build script, there are some new dependencies, you will need sudo `libglew-dev` and `libglfw3-dev`

**Comment by flightlessmango** [comment]
The change that caused this has been reverted, this shouldn't be an issue anymore
