### ISSUE TITLE
The README is missing some defaults

### ISSUE THREAD

**Issue by szmarczak** [flightlessmango/MangoHud#89]
The README does not specify what are the defaults for:

- full
- crosshair
- width
- height
- no_display
- reload_cfg
- time
- gpu_color
- gpu_color
- vram_color
- ram_color
- io_color
- engine_color
- frametime_color
- background_color
- text_color
- alpha
- background_alpha
- output_file
- font_file
- log_duration
- vsync
- gl_vsync

I think it would be good to add another column for the defaults.

### But, why?

I'd like to create a GUI app for managing MangoHud configs, so I need to know the defaults.

**Comment by flightlessmango** [comment]
the ones that have a default value is defined here [overlay_params.cpp](https://github.com/flightlessmango/MangoHud/blob/1915352c863784e6eea90282107d1ef074f43d98/src/overlay_params.cpp#L318)
output_file, vsync, gl_vsync, font_file and probably a few more does not have a default

**Comment by szmarczak** [comment]
So if I get this right, vsync defaults to the system value? What is the default font here?

**Comment by flightlessmango** [comment]
Yes the vsync values are basically NULL, defaults to program/system. The default font is [Unispace](https://www.dafont.com/unispace.font) [font_unispace.c](https://github.com/flightlessmango/MangoHud/blob/master/src/font_unispace.c)

**Comment by szmarczak** [comment]
Thank you very much!
