### ISSUE TITLE
Mangohud report VK3D3 when Wine3D3 is used

### ISSUE THREAD

**Issue by Frambooisier** [flightlessmango/MangoHud#891]
![Screenshot_20230114_025714](https://user-images.githubusercontent.com/15931041/212445536-1c05fd4e-0ad0-414c-9177-e12b5a0d1bca.png)

I started the game using PROTON_USE_WINED3D=1 %command% variable but mangohud (with ogverlay) report VKD3D, Im pretty sure VK3D3 is not used because vulkan HUD is active in proton config file and its not showing up.

**Comment by gort818** [comment]
I am pretty sure wined3d doesn't work for dx12.

**Comment by Frambooisier** [comment]
> I am pretty sure wined3d doesn't work for dx12.

I dont understand whats happening here, the game seems to be only DX12 but yet I am able to run it with wine3d3

**Comment by gort818** [comment]
PROTON_USE_WINED3D=1 | Use OpenGL-based wined3d instead of Vulkan-based DXVK for d3d11, d3d10, and d3d9
-- | --

What makes you think it's running with wined3d?

**Comment by Frambooisier** [comment]
@gort818 it's abit confusing, so excuse my ignorance, I think I get what you mean. The game still use VK3D3 becuase Winde3D3 only apply to DX11,10,9?

 What made me think it's running wine3d3:

1.The game crash without "proton_use_wine3d3" 

// is it possible, game uses both dx11 and dx12? so both wine3d3 and vk3d3 is used? If wine3d3 work only for <dx11 why would it help run the game?

2. The vulkan hud do not show up

 // now that I read it craefully it's "Enable DXVK's HUD" so it does not apply to VK3D3?

3. in-game benchmark and game's log present GPU as GTX470 instead of RTX3070 as it happens with wine3D3

**Comment by flightlessmango** [comment]
as stated `proton_use_wine3d3` doesn't disable vkd3d, so there's no reason why it wouldn't still be used.
This game is d3d12 only which it can't be run with wined3d either

**Comment by Frambooisier** [comment]
Can you help me understand why game starts with "proton_use_wine3d3" but refuse to launch without that flag?

**Comment by flightlessmango** [comment]
It's unrelated to mangohud, you would need to make an issue on proton instead

**Comment by Leopard1907** [comment]
> Can you help me understand why game starts with "proton_use_wine3d3" but refuse to launch without that flag?

One possible reason might be game does something on d3d11/10/9 side before it launches and that doesn't go well with DXVK-VKD3D combo but works with wined3d+vkd3d combo.

**Comment by Frambooisier** [comment]
Thank you @Leopard1907 for your answer, that was my thought also, but couldnt veryfiy. So it could be that it uses DX11 at launch then drop it to use DX12 hence mangohud not displaying that both Wine3d3 and VK3d3 is being used?

**Comment by Leopard1907** [comment]
Hard to say without a log, so my suggestion would be; get a proton log when dxvk is on ( wined3d variable not used) and post it in the Proton Github thread of the game, if there is not create the thread. Then state it works when dxvk is disabled. After that go to dxvk upstream repo, explain the situation and link to the message of yours in Proton thread and add logs with both dxvk on state and dxvk off state. This way you can likely get a fix for it.

https://github.com/ValveSoftware/Proton/issues

https://github.com/doitsujin/dxvk/issues

Your game library on Steam- right click to game-Properties- Launch Options : `PROTON_LOG=1 %command%` 

A log will be created in your home directory with the appid of the game. Which seems to be 1677280.

Do state game is not launched yet but you have been playing via playtest option also ( i assume you did that )
