### ISSUE TITLE
Support building with glfw-wayland

### ISSUE THREAD

**Issue by ChrisLane** [flightlessmango/MangoHud#893]
I am no longer able to build MangoHud against the [glfw-wayland](https://archlinux.org/packages/community/x86_64/glfw-wayland/) package on Arch Linux.

Now that package maintainers have updated their [PKGBUILDS](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=mangohud-git) to reflect that, I get a conflict where the package manager tries to replace glfw-wayland with glfw-x11.

I get this output containing errors currently due to undefined references to X11 methods https://gist.github.com/ChrisLane/19da48dbf37c2012b37b41ca25d48480.

It would be great if the MangoHud build system could support building against glfw-wayland.
Alternatively, perhaps this is already supported and the PKGBUILD is just missing some options?

**Comment by flightlessmango** [comment]
The reason we're using glfw-x11 is because mangoapp is an x11 application.
I don't think there's a way to build an x11 app with wayland glfw.
What you can do is to disable mangoapp in the meson options

**Comment by ChrisLane** [comment]
> The reason we're using glfw-x11 is because mangoapp is an x11 application. I don't think there's a way to build an x11 app with wayland glfw. What you can do is to disable mangoapp in the meson options

That sounds fine for my uses. I only use the overlay and not mangoapp.
