### ISSUE TITLE
Error when building - Dependency glew not found

### ISSUE THREAD

**Issue by ThePwnd** [flightlessmango/MangoHud#894]
I am running Pop!_OS 22.04 LTS.  As such, I have been advised by GOverlay's GitHub to build MangoHud from the source.  I have cloned the repo, run `meson build` and encountered the error:

"subprojects/imgui-1.81/meson.build:38:0: ERROR: Dependency "glew" not found, tried pkgconfig"

Here's the full log text - https://pastebin.com/HxnmWVsY

I tried `sudo apt install glew`, but it didn't find any packages with that name.  I also tried running `./build.sh build`, but that ended with the same error message.

**Comment by ThePwnd** [comment]
So quick update.  I did a search for apt packages containing "glew," and found libglew-dev and glew-utils, installed both packages, and that seems to have changed the error.  Now when I run `meson build`, I get an error saying:

"subprojects/imgui-1.81/meson.build:38:0: ERROR: Could not generate cargs for glew:
Package opengl was not found in the pkg-config search path.
Perhaps you should add the directory containing `opengl.pc'
to the PKG_CONFIG_PATH environment variable
Package 'opengl', required by 'glu', not found"

**Comment by TateFleming** [comment]
I have a similar issue, following.

**Comment by gort818** [comment]
do you have `mesa-common-dev`  installed?

**Comment by ThePwnd** [comment]
Just checked, and yes:

"mesa-common-dev is already the newest version (22.2.0-1pop0~1664294850~22.04~4e1b64f)."

**Comment by flightlessmango** [comment]
This was caused by me setting mangoapp to build by default, this has now been reverted and should resolve this issue.
dbe2f010a2ca370e605e36955b8579f9f6face94

**Comment by ThePwnd** [comment]
That worked!  Thanks for the help!
