### ISSUE TITLE
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libGLEW.so: error adding symbols: file in wrong format

### ISSUE THREAD

**Issue by wenyouyang** [flightlessmango/MangoHud#896]
I encountered an error when building on Ubuntu 22.04 LTS.

> FAILED: src/libMangoHud.so
g++ -m32  -o src/libMangoHud.so src/libMangoHud.a.p/mesa_util_os_socket.c.o src/libMangoHud.a.p/mesa_util_os_time.c.o src/libMangoHud.a.p/hud_elements.cpp.o src/libMangoHud.a.p/overlay.cpp.o src/libMangoHud.a.p/overlay_params.cpp.o src/libMangoHud.a.p/font.cpp.o src/libMangoHud.a.p/keybinds.cpp.o src/libMangoHud.a.p/font_unispace.c.o src/libMangoHud.a.p/logging.cpp.o src/libMangoHud.a.p/config.cpp.o src/libMangoHud.a.p/gpu.cpp.o src/libMangoHud.a.p/vulkan.cpp.o src/libMangoHud.a.p/blacklist.cpp.o src/libMangoHud.a.p/file_utils.cpp.o src/libMangoHud.a.p/amdgpu.cpp.o src/libMangoHud.a.p/intel.cpp.o src/libMangoHud.a.p/cpu.cpp.o src/libMangoHud.a.p/memory.cpp.o src/libMangoHud.a.p/iostats.cpp.o src/libMangoHud.a.p/notify.cpp.o src/libMangoHud.a.p/elfhacks.cpp.o src/libMangoHud.a.p/real_dlsym.cpp.o src/libMangoHud.a.p/pci_ids.cpp.o src/libMangoHud.a.p/battery.cpp.o src/libMangoHud.a.p/control.cpp.o src/libMangoHud.a.p/gamepad.cpp.o src/libMangoHud.a.p/nvml.cpp.o src/libMangoHud.a.p/loaders_loader_nvml.cpp.o src/libMangoHud.a.p/loaders_loader_nvctrl.cpp.o src/libMangoHud.a.p/nvctrl.cpp.o src/libMangoHud.a.p/loaders_loader_x11.cpp.o src/libMangoHud.a.p/shared_x11.cpp.o src/libMangoHud.a.p/dbus.cpp.o src/libMangoHud.a.p/loaders_loader_dbus.cpp.o src/libMangoHud.a.p/gl_glad.c.o src/libMangoHud.a.p/gl_gl_renderer.cpp.o src/libMangoHud.a.p/gl_gl_hud.cpp.o src/libMangoHud.a.p/gl_inject_egl.cpp.o src/libMangoHud.a.p/loaders_loader_glx.cpp.o src/libMangoHud.a.p/gl_inject_glx.cpp.o src/libMangoHud.a.p/meson-generated_.._.._vk_enum_to_str.c.o -Wl,--as-needed -Wl,--no-undefined -Wl,-O1 -shared -fPIC -Wl,--start-group -Wl,-soname,libMangoHud.so -Wl,-rpath,/usr/lib/x86_64-linux-gnu -Wl,-rpath-link,/usr/lib/x86_64-linux-gnu src/libMangoHud.a subprojects/imgui-1.81/libimgui.a subprojects/spdlog-1.8.5/src/libspdlog.a -pthread /usr/lib/x86_64-linux-gnu/libGLEW.so /usr/lib/x86_64-linux-gnu/libGL.so /usr/lib/x86_64-linux-gnu/libX11.so /usr/lib/x86_64-linux-gnu/libGLU.so /usr/lib/x86_64-linux-gnu/libglfw.so -Wl,--end-group
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libGLEW.so: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

I checked the library libglfw.so format, it is for x86-64.

> $ file /usr/lib/x86_64-linux-gnu/libglfw.so.3.3
/usr/lib/x86_64-linux-gnu/libglfw.so.3.3: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=e4e86cae6c52eff761b9509b8369a74f568229f2, stripped

It is deeply appreciated for any suggestions.

**Comment by TateFleming** [comment]
This may be related to issue #894. I have this problem as well.

**Comment by flightlessmango** [comment]
This was caused by me setting mangoapp to build by default, this has now been reverted and should resolve this issue.
dbe2f010a2ca370e605e36955b8579f9f6face94

**Comment by wenyouyang** [comment]
Thanks @flightlessmango , it works.
