### ISSUE TITLE
HUD doesn't show inside gamescope with MangoApp

### ISSUE THREAD

**Issue by italoghost** [flightlessmango/MangoHud#898]
Hi!

I am using the following parameters to launch both Valheim - a native Linux game - and Grim Dawn - through Proton:
```
gamescope -- sh -c "mangoapp& %command%"
```

But the HUD doesn't show up. I tried to toggle the HUD with Shift_R + F12 but didn't have success.

I wonder if I am doing something wrong. The parameters that I used above are from a response given on the Discord server, as I couldn't find any documentation on how to use it.

I am using Gnome + Wayland. Could be it? As MangoApp is a x11 application?

Gamescope and MangoHud are both the latest commits of today!

Thanks!

**Comment by mantarimay** [comment]
does mangohud run normally at the latest git version?

**Comment by flightlessmango** [comment]
> I am using Gnome + Wayland. Could be it? As MangoApp is a x11 application?

No that doesn't matter.

Try something more basic like `gamescope -- sh -c "mangoapp& vkcube"` in a terminal

**Comment by italoghost** [comment]
Oh, I just realized that it was removed from `mangohud-git` from the AUR. I will close this issue. Thanks anyway!
