### ISSUE TITLE
MangoHud overlay not showing on Tomb Raider (2013)

### ISSUE THREAD

**Issue by treier57lol** [flightlessmango/MangoHud#90]
On other Feral Interactive ports (in this example, DiRT 4), MangoHud works fine:
![Screenshot_20200321_113733](https://user-images.githubusercontent.com/33978534/77223880-2386db00-6b69-11ea-9437-1350c20b91ae.png)

But on Tomb Raider, no dice:
![Screenshot_20200321_113843](https://user-images.githubusercontent.com/33978534/77223885-326d8d80-6b69-11ea-8ea2-fa16b9cc1356.png)

Tried with both `mangohud %command%` and `MANGOHUD=1 %command%`, where both launch options worked with DiRT 4 but none on Tomb Raider. Running on Manjaro 19.0.2.

**Comment by jackun** [comment]
Try `mangohud.x86`

**Comment by treier57lol** [comment]
`mangohud.x86 %command%` didn't help.

**Comment by flightlessmango** [comment]
does mangohud work with glxgears?

**Comment by treier57lol** [comment]
Yes it does.
![Screenshot_20200321_122751](https://user-images.githubusercontent.com/33978534/77224536-6fd51980-6b6f-11ea-9999-59c1e06af72e.png)

**Comment by arrowgent** [comment]
tomb raider is OpenGL, using native linux.  not proton vulkan

**Comment by jackun** [comment]
Eh, it might be rendering into a 1x1px box

**Comment by treier57lol** [comment]
> Change game resolution to something else and then back.
That was the problem, changing resolutions fixed it, but only problem is it doesn't work again on the next launch. Launching with other resolutions also doesn't fix it until the resolution is changed. And yes, it is running in OpenGL. So now there is at least a workaround but it isn't a fix.

**Comment by treier57lol** [comment]
Have been playing the game for a little bit and encountered some weird camera glitches where the camera would fly off into the distance when going through camp menus, so the game itself is a little buggy. Don't know if that's the reason MangoHud doesn't display.

**Comment by pholostan** [comment]
I have the same problem, 0.3.1 and 0.3.5 does not work with my OpenGL games, but 0.3.0 does.
Steam games or GOG games etc, no go.

Stuff like glxgears do work, but not the games. Changing resolution does not help.

**Comment by jackun** [comment]
@pholostan try `MANGOHUD_DLSYM=1 mangohud blablah`

**Comment by flightlessmango** [comment]
Tried it to day without issues, feel free to reopen if it's still an issue

**Comment by treier57lol** [comment]
Yep, now it works flawlessly. Thank you!

**Comment by Translator5** [comment]
> Yep, now it works flawlessly. Thank you!

So you use steam version?
Could you please share your arg's line for tomb rider?

For me it simply do not work - maybe also because of the Steam Linux Runtime - that i have to run.

**Comment by treier57lol** [comment]
> For me it simply do not work - maybe also because of the Steam Linux Runtime - that i have to run.

Mangohud doesn't work on Steam Linux Runtime, please see issue #116.

**Comment by L1Q** [comment]
Some Linux distributions may ship 32-bit .so separately. On Manjaro, I had to install ``lib32-mangohud``, then start the game with ``mangohud %command%`` as usual.
