### ISSUE TITLE
Mangohud not working

### ISSUE THREAD

**Issue by mantarimay** [flightlessmango/MangoHud#900]
Distro: openSUSE Tumbleweed
Mangohud Version: [mangohud-0.6.8+53~git.abb5359](https://build.opensuse.org/package/show/home:mantarimay:winway/mangohud)

i tried to build mangohud latest git but it can't work on version 0.6.8+53 git.abb5359. even though it still worked when I tried on version 0.6.8+37 git.1a3fa6e.

screenshot: 
[version 0.6.8+37~git.1a3fa6e](https://0x0.st/ohP3.png)
[version 0.6.8+53~git.abb5359](https://0x0.st/ohPg.png)

**Comment by flightlessmango** [comment]
Not seeing any obvious that has changed between the version that could cause it.
Can you check if the libraries are located in the same place in both versions?

**Comment by mantarimay** [comment]
@flightlessmango  
here look different [at my screencast](https://0x0.st/ohP7.webm) 
version 0.6.8+37~git.1a3fa6e
/usr/lib64/mangohud/libMangoHud.so
version 0.6.8+53 git.abb5359
/usr/lib64/libMangoHud.so

**Comment by mantarimay** [comment]
I also did not find /usr/lib64/mangohud/libMangoApp.so

**Comment by mantarimay** [comment]
Fix with [`mv %{buildroot}%{_libdir}/libMangoHud.so %{buildroot}%{_libdir}/%{name}/`](https://download.copr.fedorainfracloud.org/results/gloriouseggroll/nobara/fedora-37-x86_64/05242194-mangohud/mangohud.spec)
thanks for nobara dev
