### ISSUE TITLE
JNI LinkageError

### ISSUE THREAD

**Issue by Edgars-Cirulis** [flightlessmango/MangoHud#906]
Error: LinkageError occurred while loading main class org.prismlauncher.EntryPoint
    java.lang.UnsatisfiedLinkError: /usr/lib/jvm/java-19-openjdk/lib/libnio.so: /usr/lib/jvm/java-19-openjdk/lib/libnio.so: undefined symbol: reuseport_available

A bug occurred when the update of jdk17-openjdk version 17.0.6.u10-2 was installed.

reuseport_available is provided by /usr/lib/jvm/java-17-openjdk/lib/libnet.so. That lib is not in the LD_LIBRARY_PATH. Unfortunately the pkg libnet also provides /usr/lib/libnet.so, which is known to ld. Since they changed from rpath to runpath in binutils, binaries are now linked with runpath by default which has no precedence over LD_LIBRARY_PATH anymore.
Setting LD_LIBRARY_PATH causes ld to load /usr/lib/libnet.so which fails to have the needed symbols.

**Comment by flightlessmango** [comment]
I don't understand how this is related to mangohud, can you elaborate on that?

**Comment by Edgars-Cirulis** [comment]
mangohud /usr/lib/jvm/java-17-openjdk/bin/java -jar pathtojar.jar

Due 17.0.6.u10-2  update ir broke mangohud on minecraft or any java applications based on JDK/JDRE17

**Comment by Edgars-Cirulis** [comment]
https://bugs.archlinux.org/task/77183

**Comment by Edgars-Cirulis** [comment]
Also breaks on java 8

**Comment by flightlessmango** [comment]
So this isn't caused by mangohud but it does break mangohud in these cases?

**Comment by Edgars-Cirulis** [comment]
Yes, It breaks. Check mangohud aur as Scrumplex said:

"**I think this package should adopt installing the libraries into their own path at /usr/lib/mangohud like other distributions, as the built-in mangohud wrapper script adds /usr/$LIB to LD_LIBRARY_PATH which can cause issues in that case**"

**Comment by Edgars-Cirulis** [comment]
Blame openjdk for breaking stuff.

**Comment by Edgars-Cirulis** [comment]
Any news about that? @flightlessmango
