### ISSUE TITLE
MangoHud doesn't appear to be working

### ISSUE THREAD

**Issue by ThePwnd** [flightlessmango/MangoHud#907]
I'm running Debian Steam on Pop!_OS 22.04 LTS, attempting to launch Left 4 Dead 2 with the launch parameter `MANGOHUD=1 %command%`, but the overlay does not appear in-game.  I've also tried the parameter `mangohud %command%`, but it still did not appear.  I built MangoHud from the latest source a couple days ago.

I don't see any other steps listed in the GitHub main page, and I watched a couple tutorials online, and it doesn't look like I've missed any steps.  However, I've also noticed that I can't get vkBasalt to run either.  Is there an implied step somewhere, or some Steam setting I'm not aware of that prevents third party addons like this from running in game?

**Comment by flightlessmango** [comment]
Read the opengl section again, I think the second part might be the cause, assuming you have already tried `--dlsym`
https://github.com/flightlessmango/MangoHud#opengl

**Comment by yash1610** [comment]
I have the same issue even with Vulkan games like Dota2 or while running games using proton like death stranding

**Comment by flightlessmango** [comment]
Are you using flatpak steam?

**Comment by yash1610** [comment]
No, I am using steam installed from the Archlinux repos with the https://aur.archlinux.org/packages/mangohud https://aur.archlinux.org/packages/lib32-mangohud packages

**Comment by yash1610** [comment]
mangohud vkcube -> ❌
sudo mangohud vkcube -> ✅
MANGOHUD=1 vkcube -> ❌
sudo MANGOHUD=1 vkcube -> ✅

**Comment by ThePwnd** [comment]
> Read the opengl section again, I think the second part might be the cause, assuming you have already tried `--dlsym` https://github.com/flightlessmango/MangoHud#opengl

This was a good thought.  I had missed this part of the main page.  However, I tried `MANGOHUD_DLSYM=1 %command%`, `MANGOHUD=1 --dlsym %command%` (that one wouldn't even let the game launch), and `mangohud --dlsym %command%`.  I also tried removing `ENABLE_VKBASALT=1` from the parameters as well, but that didn't change anything.

Regarding the second part, what is the path to the default MangoHud library?  I don't believe I passed any special params to it during install to change the directory.

**Comment by yash1610** [comment]
My issue, was completely of my own making, i had enabled the `no_display` option and forgotten about it. Sorry for the bother @flightlessmango

**Comment by flightlessmango** [comment]
> what is the path to the default MangoHud library

It depends, but generally you'd find it somewhere in `/usr/lib`

**Comment by ThePwnd** [comment]
I think I found it at `/usr/local/lib/x86_64-linux-gnu/mangohud/libMangoHud_dlsym.so`.  Not sure if that's the right one.  There's also `/usr/local/lib/x86_64-linux-gnu/libMangoHud.so`.

I believe the start script for Left 4 Dead 2 is actually hl2.sh, found in the installation directory for L4D2.  I see some mention of "LD_PRELOAD", but it's not clear how I should modify the file.  It looks to be a bash script, and I'm unfortunately not familiar with bash. =\  Here's the complete script for context - https://pastebin.com/kZVj0YgS - I changed line 60 to read `echo set env LD_PRELOAD=/usr/local/lib/x86_64-linux-gnu/mangohud/libMangoHud_dlsym.so >> "$ARGSFILE"` but the overlay still isn't showing up in game.  I don't suppose you could set me straight on the bash script?

**Comment by flightlessmango** [comment]
You want the non-dlsym version. But it doesn't look like that specific game is overwriting LD_PRELOAD, so I don't *think* that's the issue

**Comment by ThePwnd** [comment]
Well, I tried changing the path to point to the other .so file that I mentioned, and launched the game again, just to be safe.  Still no luck. =\

**Comment by shmerl** [comment]
That script seems to be doing this:

```
unset LD_PRELOAD
```

So it unsets the LD_PRELOAD that contains the library which is why it's not working probably.

**Comment by ThePwnd** [comment]
Not sure what's going on with GitHub.  I can't see your response @shmerl on the issue, but I can see it in my email.  There's also a bunch of other responses that I had seen previously from another user that have also disappeared...
At any rate, I tried commenting out the line that says `unset LD_PRELOAD`, but that still didn't get MangoHud to display in game.
    On Sunday, January 22, 2023 at 04:54:36 PM EST, shmerl ***@***.***> wrote:  
 
 


That script seems to be doing this:
unset LD_PRELOAD

So it unsets the LD_PRELOAD that contains the library which is why it's not working probably.

**Comment by shmerl** [comment]
I deleted the comment becasue I think it only applies to some debugger use case which shouldn't be what you are doing.

**Comment by ThePwnd** [comment]
Ah, that's a shame.  Thanks for the suggestion anyway

**Comment by ThePwnd** [comment]
So, some good news, this problem does seem to be exclusive to Left 4 Dead 2.  I just launched Rocket League last night with the parameters `MANGOHUD=1 ENABLE_VKBASALT=1 %command%` and both worked.  It would seem your suspicion is correct @flightlessmango that this is related to its being a native Linux game.

**Comment by ThePwnd** [comment]
So a few people on Reddit have been suggesting to me that I need to install and run the 32-bit version of MangoHud to run on L4D2...

I followed the build instructions for the 32-bit version, it built successfully, but the overlay doesn't appear in-game.  I don't see anything about needing to add different parameters for the 32-bit version, but I also didn't do anything to uninstall the 64-bit version.  Not sure how to do that, or if that's necessary, but my first guess is that I need to take some additional step to get L4D2 to look at the 32-bit version, and that it's probably still looking at the 64-bit version.   Thoughts?

**Comment by ThePwnd** [comment]
I got it working by installing Gamescope!  To anyone coming later, you can read more about the steps I took over on [vkBasalt's repo](https://github.com/DadSchoorse/vkBasalt/issues/203#issuecomment-1407423315) (because getting Gamescope to run on Pop!_OS 22 comes with its own set of challenges).  Hope this helps someone!
