### ISSUE TITLE
Installing MangoHud Version 0.3.1 bricks Solus Linux

### ISSUE THREAD

**Issue by FanderWasTaken** [flightlessmango/MangoHud#91]
I just wanted to check out the latest build with support for OpenGl, but after installing the release if I run any program it says that it can't find shared libraries. After reboot I get `Failed to execute /sbin/init` and nothing boots.

**Comment by jackun** [comment]
Relink `/usr/lib` back to correct folder.

**Comment by szmarczak** [comment]
I almost replaced my Solus distro with Manjaro if I didn't check that the link was broken :(

**Comment by jackun** [comment]
Sorry, the `tar -h` seemed to work on Arch. `install` it is then.

**Comment by szmarczak** [comment]
> Relink /usr/lib back to correct folder.

@FanderWasTaken the correct folder is `/usr/lib64`.

```
mv /usr/lib /usr/lib.mangohud.old
ln -s /usr/lib64 /usr/lib
```

**Comment by szmarczak** [comment]
This has been fixed in a579be8c9c15374582077e1a9e43915a5d7ddee8

When should we expect a release?

**Comment by flightlessmango** [comment]
> When should we expect a release?

I think this is already in 0.3.1

**Comment by szmarczak** [comment]
The release was on Mar 18, the fix was on Mar 21, so there's no way you travelled back in time :P

**Comment by jackun** [comment]
`Release` packages where updated with the fixed install script

**Comment by szmarczak** [comment]
Ah ok. Sorry. Thanks for fixing!
