### ISSUE TITLE
Add ability to display less ambigous GPU name

### ISSUE THREAD

**Issue by shmerl** [flightlessmango/MangoHud#910]
Currently MangoHUD reads GPU name from PCI info, which results in something ambiguous like this:

```
Radeon RX 6800/6800 XT / 6900 XT
```

It should be possible to get less ambiguous GPU name through Vulkan or OpenGL. See for example (in my case for RX 6800 XT):

```
glxinfo | rg Radeon
...
Device: AMD Radeon RX 6800 XT (navi21, LLVM 15.0.6, DRM 3.49, 6.1.7 ...
...
```

```
vulkaninfo | rg Radeon
...
deviceName        = AMD Radeon RX 6800 XT (RADV NAVI21)
...
```

**Comment by shmerl** [comment]
References: 

* https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkGetPhysicalDeviceProperties.html
* https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkPhysicalDeviceProperties.html

**Comment by flightlessmango** [comment]
We used to use this method before, but we switched for a reason I can't quite remember.
I assume these names weren't always accurate or were less descriptive than pciid in some cases

**Comment by 8836290** [comment]
Is parameter "gpu_text" not enough? I use it i.e "gpu_text=GTX1070" and it is all that is displayed as GPU name.

**Comment by shmerl** [comment]
That's a useful workaround, but it would be better to actually detect it correctly.

**Comment by flightlessmango** [comment]
Added here 41f923b
