### ISSUE TITLE
MangoHud should place MangoHud.conf in /etc, not in /usr/bin/MangoHud.conf

### ISSUE THREAD

**Issue by N0rbert** [flightlessmango/MangoHud#911]
I have just tried to run mangohud on Debian 11.
On program start it tries to load config-file from `/usr/bin/MangoHud.conf` , I find this as violation of FHS - see https://refspecs.linuxfoundation.org/FHS_3.0/fhs-3.0.html#etcHostspecificSystemConfiguration .

Please move/place configuration file into `/etc/MangoHud.conf` .

**Comment by flightlessmango** [comment]
The default config location is not in /usr/bin, we just check if there is a config next to the executable in order to check for game specific configs.

**Comment by dnmodder** [comment]
But it's not a bad idea to send the default configuration in /etc/MangoHud.conf.

**Comment by flightlessmango** [comment]
We could add /etc as one of the locations I suppose

**Comment by flightlessmango** [comment]
added `/etc/MangoHud.conf` as an option 2ffc579b7f4c974dfba17957704819e89cd38568
