### ISSUE TITLE
'mangohud %command%' Prevents FH5 and RDR2 from Launching

### ISSUE THREAD

**Issue by RPINerd** [flightlessmango/MangoHud#914]
I sincerely hope that I can help figure out a way to get more actual logging info for you to help here, but I have not yet been able to get a game to even log anything with PROTONLOG=1.. 

Basically the behavior is that with the two games I'm playing right now, Red Dead Redemption 2 and Forza Horizon 5, when I attempt to enable MangoHud in the steam launch commands, the game doesn't load. I click play, it says "starting" for a second or two, and then just turns back to the green "Play" button.

The weirdest part is that before the holiday season, mangohud was working beautifully and I didn't even have to include it in the launch options. I had assumed that with the launch of the SteamDeck, mangohud had perhaps just been integrated with proton.

I typically use ferals' gamemode when running anything under linux so
`gamemoderun %command%`  works fine
`PROTONLOG=1 gamemoderun %command%`  works and logs to <appID>.log
`mangohud %command%`  does not even launch
`mangohud gamemoderun %command%` no launchy
`mangohud PROTONLOG=1 %command%` no launchy and doesn't even make an <appID>.log file

I have tried proton 7.0-5, 7.0-6 and GE 7-4# but I don't think this has anything to do with Proton

**Comment by Leopard1907** [comment]
Try with mangohud master. Release version is too old.

**Comment by RPINerd** [comment]
> Try with mangohud master. Release version is too old.

Am I correct in interpreting that what you mean is to try building from a git clone (using the build.sh script)? Can I use the 'git' version from the AUR or is that not the same thing as building from source?

**Comment by Leopard1907** [comment]
Either building your own or using mangohud-git from aur. Both options are good for testing.

0.6.8 is from August 2022 this is why i said it is old and yes, that is latest release.

**Comment by RPINerd** [comment]
> Either building your own or using mangohud-git from aur. Both options are good for testing.
> 
> 0.6.8 is from August 2022 this is why i said it is old and yes, that is latest release.

Well I'll be.. running the *-git versions for mangohud in the AUR appears to have fixed the issue!

I feel like somewhere in the readme (maybe in the workarounds) it should mention that trying the *-git branch from the package manager may resolve issues? I can create a fork/branch/pull request to that effect if you'd like
