### ISSUE TITLE
I can't find the config file for Mangohud(flatpak)?

### ISSUE THREAD

**Issue by paparoxo360** [flightlessmango/MangoHud#916]
I installed Heroic game Launcher(flatpak version), and it needs Mangohud flatpak, it works without any issue, but I can't find mangohud's config file, searching online, they said it's on .var/app, but it's not there, does anyone know where the file is located? Thanks.

**Comment by flightlessmango** [comment]
configs aren't installed by default, you need to create one

**Comment by paparoxo360** [comment]
> configs aren't installed by default, you need to create one

Thanks for the reply, I have a Mangohud.conf file locate at /home/user/.config/, where should I copy it to?

**Comment by zenofile** [comment]
`$HOME/.var/app/com.heroicgameslauncher.hgl/config/MangoHud/MangoHud.conf` should work.

**Comment by paparoxo360** [comment]
> `$HOME/.var/app/com.heroicgameslauncher.hgl/config/MangoHud/MangoHud.conf` should work.
Thank you so much, you're a lifesaver, it worked.
