### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by Csokis** [flightlessmango/MangoHud#918]
Hi!

When I run the `./build.sh build` command, it stops with this error :(

Latest github version + Arch Linux.

> [63/66] Compiling C++ object src/libMangoHud.a.p/vulkan.cpp.o
FAILED: src/libMangoHud.a.p/vulkan.cpp.o
ccache c++ -Isrc/libMangoHud.a.p -Isrc -I../../src -I../../include -Isubprojects/imgui-1.81 -I../../subprojects/imgui-1.81 -I../../subprojects/imgui-1.81/backends -I../../subprojects/spdlog-1.8.5/include -I../../subprojects/Vulkan-Headers-1.2.158/include -I. -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -fvisibility=hidden -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Werror -std=c++14 -O3 -Werror=return-type -Wno-unused-parameter -fno-math-errno -fno-trapping-math -Wno-non-virtual-dtor -Wno-missing-field-initializers -Wno-format-truncation -fPIC -pthread -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS '-DPACKAGE_VERSION="v0.6.8"' -DSPDLOG_COMPILED_LIB -DNDEBUG -DSPDLOG_ACTIVE_LEVEL=SPDLOG_LEVEL_INFO -D_GNU_SOURCE -DHAVE_PTHREAD -DUSE_GCC_ATOMIC_BUILTINS -DHAVE_TIMESPEC_GET -DHAVE___BUILTIN_BSWAP32 -DHAVE___BUILTIN_BSWAP64 -DHAVE___BUILTIN_CLZ -DHAVE___BUILTIN_CLZLL -DHAVE___BUILTIN_CTZ -DHAVE___BUILTIN_EXPECT -DHAVE___BUILTIN_FFS -DHAVE___BUILTIN_FFSLL -DHAVE___BUILTIN_POPCOUNT -DHAVE___BUILTIN_POPCOUNTLL -DHAVE___BUILTIN_UNREACHABLE '-DMANGOHUD_ARCH="64bit"' -DHAVE_NVML -DHAVE_XNVCTRL -DHAVE_X11 -DHAVE_DBUS -DVK_USE_PLATFORM_XLIB_KHR -MD -MQ src/libMangoHud.a.p/vulkan.cpp.o -MF src/libMangoHud.a.p/vulkan.cpp.o.d -o src/libMangoHud.a.p/vulkan.cpp.o -c ../../src/vulkan.cpp
../../src/vulkan.cpp: In function ‘VkResult overlay_CreateDevice(VkPhysicalDevice, const VkDeviceCreateInfo*, const VkAllocationCallbacks*, VkDevice_T**)’:
../../src/vulkan.cpp:1752:29: error: unused variable ‘device_features’ [-Werror=unused-variable]
 1752 |    VkPhysicalDeviceFeatures device_features = {};
      |                             ^~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
ninja: build stopped: subcommand failed.

**Comment by gort818** [comment]
Will be fixed shortly

**Comment by gort818** [comment]
Fixed 87cc5c62fa25f32096ca9577074397be05f656f7
