### ISSUE TITLE
Temperature in Fahrenheit

### ISSUE THREAD

**Issue by SiliconPenguin** [flightlessmango/MangoHud#919]
Feature Request: It'd be nice to have an option of displaying temps in Imperial Units -> Fahrenheit, instead of only Celsius.

Issue: I added this line after gpu_stats to get the temperature in Fahrenheit: exec=sensors -f | grep 'edge' | cut -c 14-21 | tr -d +
This works in minetest, an opengl game, and The Long Dark, a VULKAN game. It isn't working in 7 Days To Die, a DXVK game. I have a very similar line for the cpu temp too. It works/doesn't work as mentioned above.  I'd swear it did work at first!

**Comment by flightlessmango** [comment]
It wouldn't be any technical issue in implementing this.
My concern would be that since Celsius is the standard in computer science, displaying Fahrenheit could cause confusion.
Maybe if it's clearly outlined that it's not Celsius? I don't know.

**Comment by SiliconPenguin** [comment]
Many tools have a command line option like "sensors -f", or "lm-sensors -f".  That shouldn't be very confusing - the user would have to use that on the command line. I don't have a problem using the output of a bash command, such as : "exec=sensors -f | grep 'edge' | cut -c 14-21 | tr -d +".
But the output won't display for the only game I really need it to. Without the option of running MangoHud with a command line switch, or being able to return a value from an external program, it isn't really useful for that game. Like I said, it's only that DXVK game that's failing to return the temp. BTW, I stripped everything from that config except the temp, and it still wouldn't show it.

**Comment by coffeecrisp** [comment]
If I may advertise here, flightlessmango,
I added this feature to my fork of MangoHud.

https://sourceforge.net/projects/mangohud2/

Add the line
TheTemperatureUnit=TU_CELSIUS
or
TU_FAHRENHEIT
TU_KELVIN

to your MangoHud.conf file.

The ReadMe.odt explains it and explain how you can modify the original source code.

**Comment by flightlessmango** [comment]
This has been added here 881b4d2e4a73626c11e25f1d80540a2ff8219bdc
`temp_fahrenheit`

**Comment by SiliconPenguin** [comment]
So... I've dug everywhere, and I can't tell how I'm supposed to use "temp_fahrenheit" . I assume it's a config parameter, like: temp_fahrenheit=true ?
I know I needed to grab the new branch with that: https://github.com/flightlessmango/MangoHud/commit/881b4d2e4a73626c11e25f1d80540a2ff8219bdc

So I grabbed it, and I could not get it to build. I was doing a `./build.sh build`, and ended up with 2 errors:

```[68/70] Linking target src/mangoapp
FAILED: src/mangoapp 
g++ -m32  -o src/mangoapp src/mangoapp.p/app_main.cpp.o -Wl,--as-needed -Wl,--no-undefined -Wl,-O1 -Wl,--start-group src/libMangoHud.a subprojects/imgui-1.81/libimgui.a subprojects/spdlog-1.8.5/src/libspdlog.a -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--exclude-libs,ALL -Wl,--version-script,/home/terryw/Downloads/hold4clamscan/MangoHud/src/mangohud.version -ldl -pthread /usr/lib64/libX11.so /usr/lib64/libglfw.so /usr/lib64/libGLEW.so /usr/lib64/libGL.so /usr/lib64/libGLU.so -Wl,--end-group
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /usr/lib64/libX11.so: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status```

And:

```[69/70] Linking target src/libMangoHud.so
FAILED: src/libMangoHud.so 
g++ -m32  -o src/libMangoHud.so src/libMangoHud.a.p/mesa_util_os_socket.c.o src/libMangoHud.a.p/mesa_util_os_time.c.o src/libMangoHud.a.p/hud_elements.cpp.o src/libMangoHud.a.p/overlay.cpp.o src/libMangoHud.a.p/overlay_params.cpp.o src/libMangoHud.a.p/font.cpp.o src/libMangoHud.a.p/keybinds.cpp.o src/libMangoHud.a.p/font_unispace.c.o src/libMangoHud.a.p/logging.cpp.o src/libMangoHud.a.p/config.cpp.o src/libMangoHud.a.p/gpu.cpp.o src/libMangoHud.a.p/vulkan.cpp.o src/libMangoHud.a.p/blacklist.cpp.o src/libMangoHud.a.p/file_utils.cpp.o src/libMangoHud.a.p/intel.cpp.o src/libMangoHud.a.p/cpu.cpp.o src/libMangoHud.a.p/memory.cpp.o src/libMangoHud.a.p/iostats.cpp.o src/libMangoHud.a.p/notify.cpp.o src/libMangoHud.a.p/elfhacks.cpp.o src/libMangoHud.a.p/real_dlsym.cpp.o src/libMangoHud.a.p/pci_ids.cpp.o src/libMangoHud.a.p/battery.cpp.o src/libMangoHud.a.p/control.cpp.o src/libMangoHud.a.p/gamepad.cpp.o src/libMangoHud.a.p/amdgpu.cpp.o src/libMangoHud.a.p/nvml.cpp.o src/libMangoHud.a.p/loaders_loader_nvml.cpp.o src/libMangoHud.a.p/loaders_loader_nvctrl.cpp.o src/libMangoHud.a.p/nvctrl.cpp.o src/libMangoHud.a.p/loaders_loader_x11.cpp.o src/libMangoHud.a.p/shared_x11.cpp.o src/libMangoHud.a.p/dbus.cpp.o src/libMangoHud.a.p/loaders_loader_dbus.cpp.o src/libMangoHud.a.p/gl_glad.c.o src/libMangoHud.a.p/gl_gl_renderer.cpp.o src/libMangoHud.a.p/gl_gl_hud.cpp.o src/libMangoHud.a.p/gl_inject_egl.cpp.o src/libMangoHud.a.p/loaders_loader_glx.cpp.o src/libMangoHud.a.p/gl_inject_glx.cpp.o src/libMangoHud.a.p/meson-generated_.._.._vk_enum_to_str.c.o -Wl,--as-needed -Wl,--no-undefined -Wl,-O1 -shared -fPIC -Wl,--start-group -Wl,-soname,libMangoHud.so src/libMangoHud.a subprojects/imgui-1.81/libimgui.a subprojects/spdlog-1.8.5/src/libspdlog.a -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--exclude-libs,ALL -Wl,--version-script,/home/terryw/Downloads/hold4clamscan/MangoHud/src/mangohud.version -pthread -ldl /usr/lib64/libGLEW.so /usr/lib64/libGL.so /usr/lib64/libX11.so /usr/lib64/libGLU.so /usr/lib64/libglfw.so -Wl,--end-group
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /usr/lib64/libGLEW.so: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.```

But I do get a "mangoapp" in /build/release/usr/bin/, and a "libMangoHud.so" in /build/release/usr/lib/mangohud/lib64/

After running around in circles for a couple of hours, I decided to grab "The Latest Release" in binary... I installed that, and oh, it's from April...  Any ideas?

**Comment by TheComputerGuy96** [comment]
@SiliconPenguin Are you compiling 32-bit or 64-bit MangoHUD?

**Comment by SiliconPenguin** [comment]
I'd be compiling for x86_64. I have lots of old DOS games that I sometimes play under wine, but I can't see using MangoHud for them.

**Comment by TheComputerGuy96** [comment]
@SiliconPenguin i think the build.sh script incorrectly keeps the 32-bit CC and CXX variables enabled

**Comment by SiliconPenguin** [comment]
Are you looking here?
```
    if [[ ! -f "build/meson32/build.ninja" && "$MACHINE" = "x86_64" ]]; then
        export CC="gcc -m32"
        export CXX="g++ -m32"
        export PKG_CONFIG_PATH="/usr/lib32/pkgconfig:/usr/lib/i386-linux-gnu/pkgconfig:/usr/lib/pkgconfig:${PKG_CONFIG_PATH_32}"
        meson build/meson32 --libdir lib/mangohud/lib32 --prefix /usr -Dappend_libdir_mangohud=false $@ ${CONFIGURE_OPTS}
    fi
'''

**Comment by TheComputerGuy96** [comment]
@SiliconPenguin Of course I am

**Comment by SiliconPenguin** [comment]
So, I commented out:

```
#        export CC="gcc -m32"
#        export CXX="g++ -m32"
#        export PKG_CONFIG_PATH="/usr/lib32/pkgconfig:/usr/lib/i386-linux-gnu/pkgconfig:/usr/lib/pkgconfig:${PKG_CONFIG_PATH_32}"
```
And the `./build.sh build` was successful!  Now to see if `./build.sh install` will work.

**Comment by SiliconPenguin** [comment]
Nope. The `./build.sh install` ended with: `install: cannot stat './build/release/usr/share/vulkan/implicit_layer.d/MangoHud.x86.json': No such file or directory`. I also saw "DEFAULTLIB: lib32".  So that's interesting.

**Comment by SiliconPenguin** [comment]
I changed DEFAULTLIB=lib32 to DEFAULTLIB=lib64, but that didn't help, same error message. Why is it looking for MangoHud.x86.json, instead of MangoHud.x86_64.json ??

**Comment by SiliconPenguin** [comment]
Commented out `/usr/bin/install -Dvm644 ./build/release/usr/share/vulkan/implicit_layer.d/MangoHud.x86.json /usr/share/vulkan/implicit_layer.d/MangoHud.x86.json` . Install went through... Lets see if it works...
Okay, MangoHud is indeed installed again, and functioning. However, `temp_fahrenheit=true` in the config appears to not be the correct way to enable `temp_fahrenheit`

**Comment by coffeecrisp** [comment]
Probably, you need to put temp_fahrenheit on a new line in the Mangohud.conf file.
Do not put temp_fahrenheit=true.
Just put temp_fahrenheit

**Comment by SiliconPenguin** [comment]
Thanks @coffeecrisp that did the trick.
