### ISSUE TITLE
Is there a way for windows support?

### ISSUE THREAD

**Issue by iagosousadev** [flightlessmango/MangoHud#921]
Now that MSI Afterburner is dying, do you have any plans to bring this to windows? Or maybe sameway on which i could do it on my own, something like that?

**Comment by YellowOnion** [comment]
@iagosousadev MSI Afterburner is an Overclocking software that comes with RTSS, an overlay, just download RTSS directly

Mangohud OpenGL and Vulkan probably won't be too hard to port, and the FPS meter stuff, but OS specific API stuff (like CPU usage), will all need Windows specific implementations.

As usual, this being an open source project, patches are probably going to be accepted, and if someone wants to hire a developer (crowd fund the work), then anything is possible.

It would be kind of nice if MangoHud had a plugin system like RTSS, you can use HWiNFO to include extra stats in RTSS, and being able to write scripts or something to include extra info in MangoHud would be nice, and help with operating out the Windows specific stuff.

**Comment by flightlessmango** [comment]
It's possible to build mangohud for windows, but it's not "supported" and the hud only shows in vulkan
