### ISSUE TITLE
Mangohud wraps the displayed elements overlapping the first line

### ISSUE THREAD

**Issue by 8836290** [flightlessmango/MangoHud#924]
When parameter "horizontal"  is enabled, Mangohud wraps the displayed elements overlapping the first line, no matter what is the value of table_columns i.e 20 or even 60. The wrapping happens at the same position right after the graph which is last displayed parameter in the first line. The second, wrapped line, always overlaps the first line.  If  "resolution" & "gamemode", parameters are disabled, wrapped text is removed.  Also if parameter "throttling_status" is enabled, when throttling occurs and is displayed on manguhud the wrapping occurs without text overwrites. Example on photo :

![mangohud text overlap](https://user-images.githubusercontent.com/58001454/218264265-674d9e06-8ba7-4103-842b-afc53ceca883.png)

**Comment by 8836290** [comment]
Further information 
Messing with parameters  CPU Power, show_fps_limit, gamemode and resolution, reveal interesting things about overlapping. Having all active, overlapping remains. Having active only show_fps_limit and gamemode, overlapping is gone. Additionally if cpu_power is disabled ( it does not show power draw on Ryzen 2 anyway), overlapping happens again!!!

**Comment by flightlessmango** [comment]
There's been some changes since this, can you verify that this is still an issue?

**Comment by 8836290** [comment]
> There's been some changes since this, can you verify that this is still an issue?

Just checked and seems to be solved with the latest version (0.6.9-1). The colored vertical columns remain though.


![Screenshot from 2023-05-05 15-43-28](https://user-images.githubusercontent.com/58001454/236461131-97319396-5257-4eb3-a283-cad4175f6ba8.png)

**Comment by flightlessmango** [comment]
If you have extra columns, it's probably because you're trying to display and element that isn't supported on your system
