### ISSUE TITLE
MangoApp fails to launch, "BadAtom" error.

### ISSUE THREAD

**Issue by Bitwolfies** [flightlessmango/MangoHud#926]
System: Arch Linux X64,, GTX3080, DKMS 525.89, Xorg/wayland.

Attempting to launch Mangoapp (Ex, Gamescope vkcube& mangoapp) will result in all the other apps working, but mangoapp errors out with this.

[2023-02-15 13:06:21.206] [info] [overlay.cpp:768] Uploading is disabled (permit_upload = 0)
X Error of failed request:  BadAtom (invalid Atom parameter)
  Major opcode of failed request:  20 (X_GetProperty)
  Atom id in failed request:  0x0
  Serial number of failed request:  275
  Current serial number in output stream:  275
terminate called without an active exception
Aborted (core dumped)

**Comment by flightlessmango** [comment]
That command is not correct. it would start mangoapp outside gamescope, which does not work.
You'd want to run something like `gamescope -- sh -c "vkcube& mangoapp"`
