### ISSUE TITLE
MangoHud not working in 32bit and DX9 games.

### ISSUE THREAD

**Issue by KajzerD** [flightlessmango/MangoHud#930]
I've been using Linux for the past 6 months more or less so I did try my best to debug stuff. The issue I am currently facing is that MangoHud just does not want to work with any 32bit or DX9 game. I went and compiled 32bit libs for MangoHud and Vulkan loader, still same issue. Then I downloaded latest release of MangoHud and used "mangohud-setup.sh" to install it, and games still won't launch with MangoHud. After that I distro hopped, I tried Debian, Linux Mint, Fedora 37, Vanilla Arch, and every single time my 32bit games and DX9 games on Steam would not work with MangoHud. Did anyone have the same issues lately? I also tried using Old and New Proton versions, didn't do anything. I have AMD gpu and I'm using standard MESA drivers that come with the system.

**Comment by KajzerD** [comment]
I have to mention that MangoHud works normally with VKCUBE and VKCUBE32. It also works fine with games running DX11, I tested Hunt Showdown and Apex Legends just to confirm, it works in both of those titles. Old DX9 games that I tried just would not work. DX9 games I tried: Mirror's Edge, Dishonored, Hitman Blood Money, Splinter Cell: Chaos Theory, GTA IV.

**Comment by KajzerD** [comment]
I'm going to attach latest log. I reinstalled Fedora 37 again, made sure I got 32libs for MangoHud, tried different proton versions, Overlay still won't work with any DX9 game and 32bit games. Glxgears and VKCube both show overlay normally. Bottles also shows overlay normally which is weird. Steam games however, nope. 
[steam-17410.log](https://github.com/flightlessmango/MangoHud/files/10777072/steam-17410.log)

**Comment by KajzerD** [comment]
Just finished testing all games inside of default Bottles gaming enviroment. All games boot up normally from Steam and their overlays work. I think this might have something to do with Native Linux Steam runtimes or something like that. If there is anything else I can provide in debugging this I will try. Hopefully this gets resolved.

**Comment by dubigrasu** [comment]
Just a shot in the dark, try changing the "Steam Linux Runtime-soldier" branch (Properties>Beta) from "None" to "Previous release"

**Comment by d07434b2c08f** [comment]
> Just a shot in the dark, try changing the "Steam Linux Runtime-**_soldier_**" branch (Properties>Beta) from "None" to "Previous release"

This fixed the issue for me, thanks.
Looks like this might be the problem: https://github.com/ValveSoftware/steam-runtime/issues/563

**Comment by KajzerD** [comment]
> Just a shot in the dark, try changing the "Steam Linux Runtime-**_soldier_**" branch (Properties>Beta) from "None" to "Previous release"

This actually fixed it. I actually wasted so much time reinstalling distros and trying to figure out what this is. Thank you so much!

**Comment by apprehensions** [comment]
aw man it doesn't fix it for me

**Comment by smcv** [comment]
> > Just a shot in the dark, try changing the "Steam Linux Runtime-**_soldier_**" branch (Properties>Beta) from "None" to "Previous release"
> 
> This fixed the issue for me, thanks.

Any time that workaround is successful, it indicates a regression in the Steam Linux Runtime. **The workaround will immediately stop working** the next time `Steam Linux Runtime - soldier` gets upgraded, unless someone [tells us that there is a regression](https://github.com/ValveSoftware/steam-runtime/issues/) so we can fix it properly.

I've opened https://github.com/ValveSoftware/steam-runtime/issues/564 for this particular regression, and a fix is in progress.

> Looks like this might be the problem: [ValveSoftware/steam-runtime#563](https://github.com/ValveSoftware/steam-runtime/issues/563)

No, that's a different issue, for which we will need more information.
