### ISSUE TITLE
d4aa74c breaks capturing with obs-vkcapture

### ISSUE THREAD

**Issue by hannesmann** [flightlessmango/MangoHud#933]
Commit d4aa74c149d8b0c1ff5593114d947d46adaf48f4 breaks OpenGL games when using [obs-vkcapture](https://github.com/nowrep/obs-vkcapture). Can be easily reproduced by launching glxgears with `obs-gamecapture mangohud glxgears`.

I'm not really sure what would cause this. Using `gdb` shows that the application hangs in `clock_gettime` which makes no sense.

**Comment by evelikov** [comment]
Haven't tried the `obs-vkcapture` to definitively confirm, but the PR should fix the issue. Can you give it a try?
