### ISSUE TITLE
Unable to run for native apps

### ISSUE THREAD

**Issue by Gigas002** [flightlessmango/MangoHud#934]
Trying to run mangohud overlay for native apps, e.g. `dolphin`, `firefox`, `chromium`, etc.

What I've tried:

```sh
MANGOHUD_DLSYM=1 LD_PRELOAD="/lib/mangohud/libMangoHud_dlsym.so" mangohud firefox
```

and

```sh
LD_PRELOAD="/lib/mangohud/libMangoHud.so" mangohud firefox
```

It works for native games, but not system application, it seems.

**Comment by flightlessmango** [comment]
The application has to be rendering with opengl or vulkan, otherwise there isn't anything to hook to

**Comment by melroy89** [comment]
yea that makes sense.

That being said. Firefox as well as Chome is recognizing my OpenGL when going to `about:support`. I bet in-browser games are using OpenGL for instance to play games?

Not only that according to the FF docs, Gecko is using OpenGL as well for hardware acceleration same for the Firefox WebRender module. Meaning it should really use OpenGL under the hood. Same for other browsers like Chrome.

**Comment by flightlessmango** [comment]
I can't tell if this is an actual issue. You would have to show that there is actually something to attach to and that mangohud fails to
