### ISSUE TITLE
New feature: Show application bitness

### ISSUE THREAD

**Issue by Faalagorn** [flightlessmango/MangoHud#94]
It would be nice whether a currently launched app is compiled for 32-bit or 64-bit on overlay somewhere, similar how Vulkan/OpenGL is shown. It would make troubleshooting issues and problems a little easier this way.

**Comment by arrowgent** [comment]
that would work for native software
anything inside of wine/proton would rely on the wine64 or wine binary
so dxvk, is it 64bit? 32bit?

a little exploration how that works and combines

**Comment by Faalagorn** [comment]
I guess just showing whenever lib32- or regular mangohud is loaded would be nice, but good point indeed

**Comment by flightlessmango** [comment]
This is added in develop now, it uses the `arch` param
