### ISSUE TITLE
vkBasalt options are all grey

### ISSUE THREAD

**Issue by not-NEKO** [flightlessmango/MangoHud#946]
It's probably a PEBCAK issue but apparently i can't really use vkbasalt, i don't really understand why because it's installed. It seems that i can activate CAS but not reshade effects. 
![image](https://user-images.githubusercontent.com/75278340/224400594-c7acd1ee-853d-4708-b14f-d1be113adfc5.png)

**Comment by not-NEKO** [comment]
the + and - buttons are unresponsive, so i think it's intended but i still can't figure out a solution.

**Comment by gort818** [comment]
Not our bug, this has nothing to do with MangoHud. Maybe you meant to post here https://github.com/benjamimgois/goverlay?

**Comment by not-NEKO** [comment]
oh wrong issue sorry i just clicked on the wrong git
