### ISSUE TITLE
D3Cold State check to prevent unnecessary power usage

### ISSUE THREAD

**Issue by alou-S** [flightlessmango/MangoHud#955]
You could add a simple D3Cold state check on the GPU before checking for usage values. This will prevent GPU from waking up if it is already sleeping and save power on Laptops. 

Power State can be checked on : `/sys/class/drm/card0/device/power_state`

Well either this can be implemented or a check can be implemented to see which GPU the game is running on.

**Comment by flightlessmango** [comment]
I don't understand the exact scenario this would be for.
The application mangohud is attached to will be using the GPU either way

**Comment by alou-S** [comment]
Basically on laptops since you have the option to use either the iGPU (Integrated) or the dGPU (Dedicated)

Well yeah more of a multi-gpu thing I guess?

**Comment by flightlessmango** [comment]
We should only be checking metrics on the GPU that's being used. Could you verify that this is actually happening?
