### ISSUE TITLE
How do I fix the horizontal stats bar being streted too far?

### ISSUE THREAD

**Issue by LethalManBoob** [flightlessmango/MangoHud#958]
Using bottom right layout
![image](https://user-images.githubusercontent.com/30273211/225457785-edca8f59-6c9b-475e-95d1-6ae51f63e5fe.png)

**Comment by flightlessmango** [comment]
You can't, it's a bug that needs to be fixed

**Comment by LethalManBoob** [comment]
> You can't, it's a bug that needs to be fixed

alright that's good to know. thanks.

**Comment by gort818** [comment]
Fixed here 3daf7d73b3dd22ad06bba47c37b772c5f4fc3ad7
with `horizontal_stretch=0`

**Comment by gort818** [comment]
Actually not completely fixed yet, need to make some adjustments still
