### ISSUE TITLE
Mangohud not displaying in HDD games 

### ISSUE THREAD

**Issue by edvardsanta** [flightlessmango/MangoHud#959]
I am not having this problem with my games in my nvme. I have an arch Linux which is installed in my nvme, my hd and my other games in nvme are in NTFS partitions, i am playing on steam and lutris, games in my nvme like GTA V display mangohud overlay, but games in my hd doesn't

**Comment by flightlessmango** [comment]
It's not very likely that it has anything to do with the type of hard drive.
What games don't show the hud and what distro are you on?

**Comment by edvardsanta** [comment]
Sorry, i forgot that I've opened this issue... 
I will send more informations about my setup

**Comment by flightlessmango** [comment]
What do you mean by HD games?

**Comment by edvardsanta** [comment]
Games in hard disk drive

**Comment by edvardsanta** [comment]
For example, valheim is in my nvme (NTFS partition) and resident evil 4 in my HDD 

![image-8.png](https://user-images.githubusercontent.com/75655486/229574564-1675f0f0-1bea-4943-9419-232a7674cb50.png)

![image-10.png](https://user-images.githubusercontent.com/75655486/229574563-712ba7ae-ca26-40d7-a536-a996eec708a1.png)

![image-6.png](https://user-images.githubusercontent.com/75655486/229574562-041f83a7-d09f-4b53-9c8d-bed696ecea3e.png)

![image-9.png](https://user-images.githubusercontent.com/75655486/229574561-dab9c3a2-4d8e-4581-adec-4eebed193c47.png)


All my games in HDD are not showing mangohud

**Comment by flightlessmango** [comment]
And if you move either game to the other hard drive, does it start/stop working?

**Comment by edvardsanta** [comment]
That has not worked, i moved resident evil 4, if i install new games on my SSD nvme, it works

**Comment by flightlessmango** [comment]
What was the solution?

**Comment by edvardsanta** [comment]
I have installed some games again, but i think this this "bug" was very specific with my HDD
