### ISSUE TITLE
CEMU reports DXVK while it's running Native vulkan

### ISSUE THREAD

**Issue by benjamimgois** [flightlessmango/MangoHud#96]
CEMU (the nintendo wiiu emulator) reports DXVK on mangoHud when it's running in native vulkan mode. If you disable the DXVK on the wine prefix it reports correctly, not a big issue but maybe it's something to look after.

![Captura de tela de 2020-03-22 17-35-57](https://user-images.githubusercontent.com/7688496/77260258-a8efb580-6c65-11ea-9045-2fcea55e37ca.png)

**Comment by Sporif** [comment]
This is because some vulkan games/apps use dxgi to load Vulkan. If the dxgi from dxvk (instead of wine's) is installed then the engine will be reported as DXVK. Also happened with Rage 2 when I tested it out.

You can use `WINEDLLOVERRIDES='dxgi=b'` to fix it without disabling dxvk.

**Comment by flightlessmango** [comment]
Yeah this might not be fixable, since dxgi is basically tricking us as to what engine it is

**Comment by jackun** [comment]
@benjamimgois can you try `develop`? ( https://github.com/flightlessmango/MangoHud/commit/ae3a155e220782d446a10604cac2a507abae66c8 )

**Comment by Sporif** [comment]
That fixes it for Rage 2.

**Comment by benjamimgois** [comment]
@jackun sorry, i haven't saw your post man. I'll test with the latest git.

**Comment by jackun** [comment]
@benjamimgois Try now ( https://github.com/flightlessmango/MangoHud/commit/042267f26bbefb607c059b1f54c36d3c135805a9 ) . Cemu create vulkan instance with version 1.2 api and layer loader ignored MangoHud because its `api_version` was 1.1.

**Comment by benjamimgois** [comment]
Hey @jackun i just tried the latest git and it is working properly now.
