### ISSUE TITLE
Xubuntu 22.10 Kernel 6.2 CS:GO problem

### ISSUE THREAD

**Issue by Slo2018** [flightlessmango/MangoHud#960]
MangoHud doesn't work/show in CS:GO in Xubuntu 22.10 (Kernel 6.2).

i5-13600K
RTX 4080

**Comment by flightlessmango** [comment]
Work fine for me with latest for opengl and vulkan.
What version of mangohud are you using?

**Comment by Slo2018** [comment]
0.6.8

**Comment by flightlessmango** [comment]
It's possible that it's been fixed since. Could you test with latest git?

**Comment by Slo2018** [comment]
I tried with latest git in Xubuntu 23.04 Daily Build and have the same problem. If i install MangoHud manually it's working in CS:GO but no GPU Power.

**Comment by Slo2018** [comment]
MangoHud works in all other games except in CS:GO.

**Comment by flightlessmango** [comment]
>MangoHud works in all other games except in CS:GO. In Linux Mint 21.1 also not working in CS:GO.

But it did work when you used lastest mangohud?

**Comment by Slo2018** [comment]
No.

**Comment by Slo2018** [comment]
> But it did work when you used lastest mangohud?

No.

**Comment by flightlessmango** [comment]
>If i install MangoHud manually it's working in CS:GO but no GPU Power.

So this statement was not correct?

**Comment by Slo2018** [comment]
> So this statement was not correct?

It was working with this commands:

sudo apt update

sudo apt install mangohud -y

**Comment by flightlessmango** [comment]
The mangohud package from apt is probably the debian one, it intentionally does not include NVML.
NVML is the library we use to get information like GPU power on recent nvidia hardware.
This should be resolved by uninstalling mangohud and using these instruction https://github.com/flightlessmango/MangoHud#building-with-build-script to build with the `build.sh` script
