### ISSUE TITLE
AMD CPU clock speed is 0

### ISSUE THREAD

**Issue by palexdev** [flightlessmango/MangoHud#964]
**Describe the bug**
For some reason, Mangohud is showing 0MHz for my CPU clock speed
I OCd my R5 1600 to 3.7GHz

**List relevant hardware/software information**
- Garuda Linux (Arch)
- Latest git version from Chaotic AUR
- RTX 2070

**Screenshots**
![image](https://user-images.githubusercontent.com/16880178/227729211-77e9377d-5d19-449a-85ad-2101a5492c63.png)
This is GOverlay but the issue is present in games too

In the past I installed both `zenpower` and `zenpower3` for CPU power usage to show correctly

**Comment by flightlessmango** [comment]
Quick solution is to enable Cool'n'Quiet in your bios.
But this is a bug that should be fixed

**Comment by palexdev** [comment]
I see, unfortunately I don't know if I can enable it because it is disabled automatic by my BIOS when I OC

**Comment by arabcian** [comment]
Having same problem on [MangoHud Version 0.6.9-1] no fix yet?

**Comment by flightlessmango** [comment]
Should be fixed here 6c46794496ee030d1aa15f6c162330a959ea07e7

**Comment by palexdev** [comment]
@flightlessmango thank you very much for your work!
