### ISSUE TITLE
OpenGL overlay not showing GPU (7900XTX)

### ISSUE THREAD

**Issue by VolBournz** [flightlessmango/MangoHud#965]
**Describe the bug**
GPU is not showing up with the OpenGL overlay.

**List relevant hardware/software information**
- Pop!_OS 22.04 LTS
- MangoHud version 0.6.8
- 7900XTX
- Kisak-mesa 23.0.1 drivers
- Kernel 6.2.6

**Screenshots**
![Screenshot from 2023-03-25 21-41-29](https://user-images.githubusercontent.com/17241246/227740733-d8aafa0b-b9aa-4ff8-8c25-07fa575aa03d.png)
![Screenshot from 2023-03-25 21-42-14](https://user-images.githubusercontent.com/17241246/227740739-113074b4-3228-4a86-aa43-09e32eac88ee.png)

**Additional context**
It works fine with the Vulkan overlay.

**Comment by jackun** [comment]
Can you post `glxinfo -B` output.

**Comment by VolBournz** [comment]
`name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: AMD (0x1002)
    Device: GFX1100 (gfx1100, LLVM 15.0.7, DRM 3.49, 6.2.6-76060206-generic) (0x744c)
    Version: 23.0.1
    Accelerated: yes
    Video memory: 24576MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
Memory info (GL_ATI_meminfo):
    VBO free memory - total: 23566 MB, largest block: 23566 MB
    VBO free aux. memory - total: 31610 MB, largest block: 31610 MB
    Texture free memory - total: 23566 MB, largest block: 23566 MB
    Texture free aux. memory - total: 31610 MB, largest block: 31610 MB
    Renderbuffer free memory - total: 23566 MB, largest block: 23566 MB
    Renderbuffer free aux. memory - total: 31610 MB, largest block: 31610 MB
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 24576 MB
    Total available memory: 56286 MB
    Currently available dedicated video memory: 23566 MB
OpenGL vendor string: AMD
OpenGL renderer string: GFX1100 (gfx1100, LLVM 15.0.7, DRM 3.49, 6.2.6-76060206-generic)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 23.0.1 - kisak-mesa PPA
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6 (Compatibility Profile) Mesa 23.0.1 - kisak-mesa PPA
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 23.0.1 - kisak-mesa PPA
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20`
