### ISSUE TITLE
RFE: allow build MangoHud against system installed cmocka

### ISSUE THREAD

**Issue by kloczek** [flightlessmango/MangoHud#969]
https://github.com/flightlessmango/MangoHud/blob/c037a0cca7b5f1c9d9948b0ff405778b10dcf0cd/meson.build#L264-L266

Looks like at the moment it is not possible to build MangoHud test suitee against system installed cmocka.

**Comment by flightlessmango** [comment]
fixed in 12a86ef36e308e281f4f1bc4b3ac5613e24ad53c
