### ISSUE TITLE
OpenGL Adaptive Sync not always working/app dependent

### ISSUE THREAD

**Issue by kodatarule** [flightlessmango/MangoHud#971]
**Describe the bug**
OpenGL "Adaptive Sync" not always working/app dependent 

**List relevant hardware/software information**
- Linux Distribution EndeavourOS 
- MangoHud version 0.6.8-5
- GPU RTX 3090

**To Reproduce**
1. Start any of the older OpenGL titles(CS 1.6/Half Life) with Adaptive Sync on(I have it globally enabled with goverlay) -> fps would not be capped at all and no sync would happen.

**Expected behavior**
The game to have locked frame rate to monitor's refresh rate and work properly with Adaptive Sync, if I use regular VSYNC mechanism for OpenGL it works.
**However OpenGL adaptive sync works just fine on Black Mesa which uses ToGL for it's OpenGL implementation.**

Full specs:
Operating System: EndeavourOS 
KDE Plasma Version: 5.27.3
KDE Frameworks Version: 5.104.0
Qt Version: 5.15.8
Kernel Version: 6.2.9-273-tkg-pds (64-bit)
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 5800X3D 8-Core Processor
Memory: 31,3 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 3090/PCIe/SSE2

**Comment by flightlessmango** [comment]
Afaik this is app dependent, it has to have the GLX_EXT_swap_control_tear extension or it won't work.
In other words there isn't much we can do
