### ISSUE TITLE
MangoHud not activate in Lutris

### ISSUE THREAD

**Issue by serj-47** [flightlessmango/MangoHud#972]
I installed Lutris and MangoHud from the flathub repository on my steam deck. Then I grant other applications to the configuration file MangoHud.
`sudo flatpack override --filesystem=xdg-config/MangoHud:ro` 
But I still can't turn on MangoHud, the activation button in Lutris is still inactive

**Comment by strycore** [comment]
This may be something that needs to be fixed on the Lutris Flatpak.

On the Deck, I use MangoHUD from the Game UI. By creating Steam shortcuts of Lutris games, I can launch them without going to the desktop mode and benefit of the features of the Deck UI (Steam Input, MangoHUD, ...)

**Comment by serj-47** [comment]
I also created shortcuts in steam from lutris and launch games from game mode. The problem is that with this launch method, the fps limit in SteamUI does not work in some games, and therefore, in games that use vkd3d, I cannot limit fps.

**Comment by flightlessmango** [comment]
This does not seem to be a mangohud issue
