### ISSUE TITLE
Add C API docs

### ISSUE THREAD

**Issue by BlueGoliath** [flightlessmango/MangoHud#98]
There doesn't seem to be any C API docs for MangoHUD. It would be nice if they were added so that people could use this in a native way.

**Comment by jackun** [comment]
If I understand you correctly this seems out of scope for MangoHud.

**Comment by ShayBox** [comment]
This is exactly the scope of mangohud, an api like rivatuner has which lets external programs get the info mangohud has for the active window, not really achievable though any other project unless it was a fork or patch of mangohud.

**Comment by ShayBox** [comment]
This would be a great addition, an easy to use library for other programs to use so they don't also have to hook in when MangoHud already has all this information needed. Rivatuner has the same thing.
