### ISSUE TITLE
Dayz broken 

### ISSUE THREAD

**Issue by zetxx** [flightlessmango/MangoHud#982]
**Describe the bug**
Dayz broken part of the icons and in-game layout

**List relevant hardware/software information**
- Linux Distribution
Arch linux latest
- MangoHud version
0.6.8.r145.g020e848-1
- GPU
amd radeon 560

**To Reproduce**
compile current version

**Expected behavior**
no broken layout

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://imgur.com/a/4f0mCyg)

**Additional context**
icons on top right and bottom right are transparent or semi transparent images

**Comment by gort818** [comment]
Can you build the latest master and let me know if it fixed

**Comment by zetxx** [comment]
> Can you build the latest master and let me know if it fixed

it is fixed :). thanks a lot
