### ISSUE TITLE
Resident Evil 3 Remake crash with mangohud Steam Launch Option

### ISSUE THREAD

**Issue by JoseZancanaro** [flightlessmango/MangoHud#985]
**Describe the bug**
As reported at: https://github.com/ValveSoftware/Proton/issues/3719#issuecomment-1505304047,
My game (Resident Evil 3 Remake) was crashing after starting a campaign. It appeared to be a problem with mangohud, which by removing it from steam launch options, the game seems to work normally.

**List relevant hardware/software information**
- Distro: Arch Linux
- Kernel: 6.2.10-arch1-1
- RAM: 16 GB
- GPU Driver: NVIDIA 530.41.03
- GPU: NVIDIA GeForce RTX 3050 Laptop GPU
- CPU: 11th Gen Intel Core i5-11400H @ 2.70GHz
- mangohud and lib32-mangohud packages from AUR.

**To Reproduce**
1. Using `mangohud %command%` Steam Launch Options to the Resident Evil 3 Remake game.
2. Star a new campaign.
3. Here, after load 100% in loading screen, the game crashes.

**Additional context**
I use MangoHud with GOverlay, and I can still use MangoHud normally, if I set it to 'Global Enable' by GOverlay.
I tested with different Protons: Proton Experimental [bleeding-edge] and GE-Proton7-49 (50, 51,54 and 55).
Using GE-Proton7-49, i can use mangohud in Steam Lauch Options without any problem.

**Comment by flightlessmango** [comment]
Works fine on my end.
If you have globally enabled in goverlay you don't need to set mangohud in launch options.
Try not setting launch options or setting `MANGOHUD=1 %command%` instead

**Comment by flightlessmango** [comment]
reopen if still an issue
