### ISSUE TITLE
Mangohud does not show cpu_power ingame vulkan

### ISSUE THREAD

**Issue by Mario156090** [flightlessmango/MangoHud#988]
Hello, I'm using mangohud for play DOTA2  over vulkan and the power cpu option always show me 0W with vulkan, if I test a OpenGL app or game the power always correctly.
Mi hardware is:

![image](https://user-images.githubusercontent.com/47507975/232127390-b4f86f33-ec82-45df-b80a-3ca46df24900.png)

Error capture:

![image](https://user-images.githubusercontent.com/47507975/232132893-e432a49c-6409-42cb-b0ee-10920f09656f.png)

`################### File Generated by GOverlay ###################

toggle_fps_limit=F1

legacy_layout=false
gpu_stats
gpu_temp
gpu_core_clock
gpu_power
gpu_load_change
gpu_load_value=50,90
gpu_load_color=FFFFFF,FFAA7F,CC0000
gpu_text=GPU
cpu_stats
cpu_temp
cpu_power
cpu_mhz
cpu_load_change
core_load_change
cpu_load_value=50,90
cpu_load_color=FFFFFF,FFAA7F,CC0000
cpu_color=2e97cb
cpu_text=CPU
io_color=a491d3
vram_color=ad64c1
ram
ram_color=c26693
fps
engine_color=eb5b5b
gpu_color=2e9762
wine_color=eb5b5b
frame_timing=0
frametime_color=00ff00
gamemode
media_player_color=ffffff
table_columns=3
background_alpha=0.4
font_size=24

background_color=020202
position=top-right
text_color=ffffff
round_corners=0
#GOVERLAY_THEME=mangohuddefault
toggle_hud=Shift_R+F12
toggle_logging=Shift_L+F2
upload_log=F5
output_folder=/home/mario
media_player_name=spotify
`

**Comment by hajosattila** [comment]
Same here...
![scrn-2023-05-01-09-31-03](https://user-images.githubusercontent.com/1567493/235423322-73e0515b-bfa5-4fde-a384-c48f9e200692.png)

**Comment by Mario156090** [comment]
@flightlessmango can you check this please?

**Comment by Leopard1907** [comment]
Did you try with master to see if there is any change in both OGL and Vulkan?

**Comment by Mario156090** [comment]
> Did you try with master to see if there is any change in both OGL and Vulkan?

I compiled from the source and same result.
