### ISSUE TITLE
Why in horizontal mode it only show "FPS" text instead of engine name like normal mode?

### ISSUE THREAD

**Issue by vanphong1310** [flightlessmango/MangoHud#990]
Is there any config parameter to show engine name?
![image](https://user-images.githubusercontent.com/16339542/232185511-368bad22-1523-4b35-aa26-6e40bb3976b7.png)

**Comment by flightlessmango** [comment]
It's designed as such to save space.
I've added a new option that will show short engine names, e.g gamescope is GS.
You can enable it by adding `engine_short_names`

**Comment by JustCryen** [comment]
Hi, I think this should be an option, having shortened names is better than the "FPS" text alone but I feel like having the full engine names in horizontal (or vertical in this case as well) should be an option too.  

I would also like to mention the little FPS text on the right side of the value when the engine name is visible.  
I would like to enable it in horizontal mode as well.  

I know this is not worthy of assigning any priority level but the horizontal mode looks poor in comparison to what can be done with the vertical mode.  
I think simplifying it should be up to the user to decide.
