### ISSUE TITLE
Resolution text in wrong place for horizontal

### ISSUE THREAD

**Issue by LiamDawe** [flightlessmango/MangoHud#992]
**Describe the bug**
When enabling horizontal mode in the 0.6.9 release (nice), the "Resolution" text is positioned correctly, but the actual res readout 1280x720 etc will be behind other parts of the Hud.

**List relevant hardware/software information**
- Fedora KDE 37
- MangoHud version: 0.6.9
- GPU - NVIDIA 2080 Ti

**To Reproduce**
Try out this config: 
[MangoHud.conf.tar.gz](https://github.com/flightlessmango/MangoHud/files/11239125/MangoHud.conf.tar.gz)

**Expected behavior**
The resolution text to be positioned correctly like other elements

**Screenshots**
![Screenshot_20230415_113125](https://user-images.githubusercontent.com/83223/232208642-54296afb-019a-473a-8e37-fbdf01b00ea6.png)

**Comment by flightlessmango** [comment]
Should be fixed in 034b378e10ed070875359f9deb707fcdf4b6a1ee.
Among with a few other elements that had the same issue

**Comment by flightlessmango** [comment]
Reopen if still not fixed
