### ISSUE TITLE
Sampler hook causes textures in FFXIV to blur

### ISSUE THREAD

**Issue by tyrone-sudeium** [flightlessmango/MangoHud#993]
**Describe the bug**
The sampler hook causes textures in certain games which set their own `mipLodBias` to render incorrectly in a default MangoHud configuration.

**List relevant hardware/software information**
- Linux Distribution: Arch Linux
- MangoHud version: git commit `191cf3775f317d31e2e72860a0c89498de6bae34`
- GPU: Radeon 6900XT

**To Reproduce**
1. Delete any mangohud configs
2. Change FFXIV's launch parameters in steam to `mangohud %command%`
3. Launch the game
4. Textures look wrong

**Expected behavior**
When `picmip` is not present at all in configuration, the sampler overlay should pass through the `mipLodBias` as-is rather than setting it to `0`.

**Screenshots**
You should open these images at 100% size to make the differences clear.

<details><summary>Running without MangoHud (how it should look):</summary>

![Screenshot_20230415_191439](https://user-images.githubusercontent.com/819705/232208775-9fcf0d12-4dc7-45ff-acdf-fe932ad660d0.png)

</details>

<details><summary>Running with MangoHud (blurry textures):</summary>

![Screenshot_20230415_192404](https://user-images.githubusercontent.com/819705/232208820-fea7cbd7-40ce-458b-8141-ca2c39898569.png)

</details>

**Additional context**
Textures in games which set their own `mipLodBias` will, in a default MangoHud configuration, have incorrect textures when run through MangoHud. This is because MangoHud hardcodes the `mipLodBias` to `0` if it's not otherwise set in the config file.

In my particular test case, the net result is that a stock standard MangoHud will produce very blurry textures in Final Fantasy XIV since that game sets the `mipLodBias` variously to `-0.5`, `-1`, `-1.5`, and `-2`, but MangoHud will override this to always be 0. A workaround is to explicitly set the `picmip` config value, but, if I change the config file to set `picmip=-2` for example, it will still be incorrect since it'll always set this value to `-2` everywhere, when the game itself wouldn't always set it to `-2`. Ideally if `picmip` isn't defined _at all_ in the config file then MangoHud should really just pass through the `mipLodBias` provided by the game, rather than `0`.

I'm sorry that I raised this as an issue rather than providing a patch in a PR, I tried to patch it myself but it seems nontrivial since I couldn't work out a way to check for the _presence_ of a value in config. For the time being, I've worked around it myself to completely disable the `picmip` feature by removing the `sampler.mipLodBias = params.picmip;` line altogether.

**Comment by flightlessmango** [comment]
8f79e9cef330e4db2a65552f5f0cd9899948832f this commit should fix the issue

**Comment by tyrone-sudeium** [comment]
8f79e9c does correct the issue, thank you!
