### ISSUE TITLE
Regression: mangohud errors on opengl applictions

### ISSUE THREAD

**Issue by theofficialgman** [flightlessmango/MangoHud#994]
**Describe the bug**
current git master errors with
```
[xcb] Unknown sequence number while processing reply
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
glxgears: ../../src/xcb_io.c:639: _XReply: Assertion `!xcb_xlib_threads_sequence_lost' failed.
```
when trying to run any opengl based program.

**List relevant hardware/software information**
- Linux Distribution Ubuntu Bionic
- MangoHud version git master 191cf3775f317d31e2e72860a0c89498de6bae34
- GPU Tegra X1

**To Reproduce**
1. run `mangohud glxgears`

**Expected behavior**
mangohud works normally

**Additional context**
edit: bisected to commit https://github.com/flightlessmango/MangoHud/commit/1055bc0c6c39d9ee775f78f32ef0edd78d12a1fe

**Comment by flightlessmango** [comment]
I can't repro this bug on my end. It would be great if you could bisect and narrow down the offending commit

**Comment by theofficialgman** [comment]
@flightlessmango bisected to commit https://github.com/flightlessmango/MangoHud/commit/1055bc0c6c39d9ee775f78f32ef0edd78d12a1fe
the linked commit is the first commit where it is broken

**Comment by theofficialgman** [comment]
git master works great as well if I revert that commit with `git revert 1055bc0c6c39d9ee775f78f32ef0edd78d12a1fe`

**Comment by gort818** [comment]
I can only reproduce the error with this `mangohud MESA_LOADER_DRIVER_OVERRIDE=zink glxgears32`

```
[xcb] Unknown sequence number while appending request
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
glxgears32: xcb_io.c:157: append_pending_request: Assertion `!xcb_xlib_unknown_seq_number' failed.
```

**Comment by flightlessmango** [comment]
```(gdb) bt
#0  0xf7fc7549 in __kernel_vsyscall ()
#1  0xf76880c7 in ?? () from /usr/lib32/libc.so.6
#2  0xf7635be7 in raise () from /usr/lib32/libc.so.6
#3  0xf761e126 in abort () from /usr/lib32/libc.so.6
#4  0xf761e023 in ?? () from /usr/lib32/libc.so.6
#5  0xf762df7f in __assert_fail () from /usr/lib32/libc.so.6
#6  0xf7a77f49 in ?? () from /usr/lib32/libX11.so.6
#7  0xf7a8099e in _XReply () from /usr/lib32/libX11.so.6
#8  0xf7a7463b in XQueryKeymap () from /usr/lib32/libX11.so.6
#9  0xf7ccf72d in x11_poller::poll (this=0xe5102cbc) at ../../src/shared_x11.cpp:25
#10 0xf7cd0bb3 in std::__invoke_impl<void, void (x11_poller::*)(), x11_poller*> (
    __f=@0xe5104878: (void (x11_poller::*)(x11_poller * const)) 0xf7ccf6e0 <x11_poller::poll()>, __t=@0xe5104874: 0xe5102cbc)
    at /usr/include/c++/12.2.1/bits/invoke.h:74
#11 0xf7cd0b10 in std::__invoke<void (x11_poller::*)(), x11_poller*> (
    __fn=@0xe5104878: (void (x11_poller::*)(x11_poller * const)) 0xf7ccf6e0 <x11_poller::poll()>) at /usr/include/c++/12.2.1/bits/invoke.h:96
#12 0xf7cd0a63 in std::thread::_Invoker<std::tuple<void (x11_poller::*)(), x11_poller*> >::_M_invoke<0u, 1u> (this=0xe5104874)
    at /usr/include/c++/12.2.1/bits/std_thread.h:258
#13 0xf7cd09ad in std::thread::_Invoker<std::tuple<void (x11_poller::*)(), x11_poller*> >::operator() (this=0xe5104874)
    at /usr/include/c++/12.2.1/bits/std_thread.h:265
#14 0xf7cd093c in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (x11_poller::*)(), x11_poller*> > >::_M_run (this=0xe5104870)
    at /usr/include/c++/12.2.1/bits/std_thread.h:210
#15 0xf72b81b1 in std::execute_native_thread_routine (__p=0xe5104870) at /usr/src/debug/gcc/gcc/libstdc++-v3/src/c++11/thread.cc:82
#16 0xf7685eca in ?? () from /usr/lib32/libc.so.6
#17 0xf772201c in ?? () from /usr/lib32/libc.so.6
```
gdb backtrace for completeness

**Comment by theofficialgman** [comment]
I am using Nvidia proprietary drivers on a tegra x1. So I assume whatever change was made in that commit just happens to work on some MESA drivers but it is likely not proper.

**Comment by jackun** [comment]
Try reverting https://github.com/flightlessmango/MangoHud/commit/1055bc0c6c39d9ee775f78f32ef0edd78d12a1fe  :(

**Comment by adamdmoss** [comment]
I'm on xorg-server 2:21.1.4-2ubuntu1.7~22.04.1 and whatever xlibs presumably come with Ubuntu 22.04.1/22.04.02.
Same issue.
Reverting 1055bc0c6c39d9ee775f78f32ef0edd78d12a1fe fixes it for me.

For me it doesn't just affect GL apps - it affects VK apps (vkcube) and (thus?) every Proton game I've tried.
